### ISSUE TITLE
Version 1.10 introduces a bug making transformer graph optimization crashing

### ISSUE THREAD

**Issue by pommedeterresautee** [microsoft/onnxruntime#10003]
**Describe the bug**
When I use ORT 1.10, `optimize_model` function to optimize Transformers model crash (issues during operator fusion)

```log
Traceback (most recent call last):
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-81439ed172c7>", line 40, in <module>
    optimized_model: BertOnnxModel = optimizer.optimize_model(
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 230, in optimize_model
    optimizer = optimize_by_fusion(model, model_type, num_heads, hidden_size, optimization_options)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 141, in optimize_by_fusion
    optimizer.optimize(optimization_options)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 327, in optimize
    self.fuse_embed_layer()
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 84, in fuse_embed_layer
    fusion.apply()
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_base.py", line 43, in apply
    self.fuse(node, input_name_to_nodes, output_name_to_node)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_embedlayer.py", line 609, in fuse
    super().fuse(node, input_name_to_nodes, output_name_to_node)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_embedlayer.py", line 597, in fuse
    if self.fuse_bert(node, add_before_layernorm, input_name_to_nodes, output_name_to_node):
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_embedlayer.py", line 567, in fuse_bert
    if not self.match_position_embedding(segment_embedding_gather, input_ids, output_name_to_node):
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_embedlayer.py", line 263, in match_position_embedding
    if self.match_position_embedding_distilbert(position_embedding_gather, input_ids, output_name_to_node):
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_embedlayer.py", line 119, in match_position_embedding_distilbert
    expand, shape = path1
ValueError: too many values to unpack (expected 2)

```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 21.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0
- Python version: 3.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.5
- GPU model and memory: 3090 RTX, 24Gb

**To Reproduce**

```python
from collections import OrderedDict

import torch
from onnxruntime.transformers import optimizer
from onnxruntime.transformers.fusion_options import FusionOptions
from onnxruntime.transformers.onnx_model_bert import BertOnnxModel
from torch.onnx import TrainingMode
from transformers import AutoModelForSequenceClassification, PreTrainedModel, PreTrainedTokenizer, AutoTokenizer, \
    BatchEncoding

onnx_path = "model.onnx"
hub_model = "cardiffnlp/twitter-roberta-base-sentiment"  # because it has lots of downloads, quite classic

model_pytorch: PreTrainedModel = AutoModelForSequenceClassification.from_pretrained(hub_model)
model_pytorch.cuda()
model_pytorch.eval()
tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(hub_model)
inputs_pytorch: BatchEncoding = tokenizer("something interesting here", return_tensors="pt")
inputs_pytorch.to("cuda")
dynamic_axis = OrderedDict()
for k in inputs_pytorch.keys():
    dynamic_axis[k] = {0: "batch_size", 1: "sequence"}
dynamic_axis["output"] = {0: "batch_size"}

with torch.no_grad():
    torch.onnx.export(
        model_pytorch,  # model to optimize
        args=tuple(inputs_pytorch.values()),  # tuple of multiple inputs
        f=onnx_path,  # output path / file object
        opset_version=12,  # the ONNX version to use, 13 if quantized model, 12 for not quantized ones
        do_constant_folding=True,  # simplify model (replace constant expressions)
        input_names=list(inputs_pytorch.keys()),  # input names
        output_names=["output"],  # output axis name
        dynamic_axes=dynamic_axis,  # declare dynamix axis for each input / output
        training=TrainingMode.EVAL,  # always put the model in evaluation mode
        verbose=False,
    )

optimization_options = FusionOptions("bert")
optimized_model: BertOnnxModel = optimizer.optimize_model(
    input=onnx_path,
    model_type="bert",
    use_gpu=True,
    opt_level=1,
    num_heads=0,  # automatic detection
    hidden_size=0,  # automatic detection
    optimization_options=optimization_options,
)

```

**Expected behavior**
I am expecting that there is no crash like on version 1.9.0

**Screenshots**
N/A

**Additional context**

Same code with ORT 1.9.0 works (no crash, etc.).

**Comment by tianleiwu** [comment]
It looks like a bug introduced by https://github.com/microsoft/onnxruntime/pull/9205 int the following line:
https://github.com/microsoft/onnxruntime/blob/a99c5189112afaefc4b97b5e23de8188317256ea/onnxruntime/python/tools/transformers/fusion_embedlayer.py#L114-L118. A quick fix is to undo the changes on those three lines.

@wangyems to take a look.
