### ISSUE TITLE
how to create float tensor with missing value using java runtime

### ISSUE THREAD

**Issue by reneix** [microsoft/onnxruntime#10036]
**Is your feature request related to a problem? Please describe.**
I'm using lightgbm classifier exported onnx model  pred in java runtime.
my onnx model included missing value imputer , but I have no idea how to create a tensor with missing values.

when using Float[][]  createTensor throw exception as below, however, float[][] works.
my question is when using float[][], I can't set missing values as null or something else....

please help.

exception :
ai.onnxruntime.OrtException: Cannot create an OnnxTensor from a base type of class java.lang.Float
	at ai.onnxruntime.TensorInfo.constructFromJavaArray(TensorInfo.java:232)
	at ai.onnxruntime.OnnxTensor.createTensor(OnnxTensor.java:337)
	at ai.onnxruntime.OnnxTensor.createTensor(OnnxTensor.java:321)

code snap as below:
            for (Map.Entry<String, Float[]> kv : floatFeature.entrySet()) {
                String feaName = kv.getKey();
                Float[] feaValues = kv.getValue();
                Float[][] feaValues2d = new Float[feaValues.length][1];
                for (int i = 0; i < feaValues.length; i++) {
//                    feaValues2d[i] = ArrayUtils.toPrimitive(new Float[] {feaValues[i]});
                    feaValues2d[i] = new Float[] {feaValues[i]};
                }
                OnnxTensor test = OnnxTensor.createTensor(env, feaValues2d);
                newTensor.put(feaName, test);
            }

**System information**
- ONNX Runtime version (you are using):
-         <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.9.0</version>
        </dependency>

**Comment by Craigacp** [comment]
LightGBM says it treats `NaN` as a missing value by default. Assuming the ONNX converter for LightGBM does the same, then you can set the missing elements of your input to `NaN` in Java and it should work.

**Comment by reneix** [comment]
@Craigacp thanks, NaN works for float tensor !
btw, for String tensor， null not works for missing value, but "" works

**Comment by Craigacp** [comment]
Yeah, I'd expect String tensor handling to be a special case as it's going to be very model dependent. In general ORT doesn't do nulls, but we can add Sparse Tensor support into the Java API which will allow you to naturally exclude some elements. I'm not sure if you can have a String sparse tensor though.

**Comment by paranjapeved15** [comment]
@Craigacp Float.NaN would work for float variables, but what if I need to pass nulls for Int and Long type variables?

**Comment by Craigacp** [comment]
Those aren't representable in the ONNX format, so it depends how your model was generated. It may use sparse tensors, which are supported, or it may use some sentinel value.

**Comment by paranjapeved15** [comment]
@Craigacp can you give an example of sparse tensors in java?

**Comment by Craigacp** [comment]
https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/ai/onnxruntime/SparseTensorTest.java

**Comment by paranjapeved15** [comment]
@Craigacp I don't understand what exactly is happening in the code above. Can you please elaborate?
Also, following onnx documentation is pretty hard, for example I am not sure what CSRCTensor means; so when I go to the java docs https://onnxruntime.ai/docs/api/java/ai/onnxruntime/OnnxSparseTensor.CSRCTensor.html, it does not state what csrc tensor means 😢. I think there is much room to improve onnx documentation and give code examples (with appropriate comments) for such operations.

**Comment by Craigacp** [comment]
Firstly, I think it's probably unlikely that your model does use sparse tensors as they have limited support in the ONNX standard and are mostly supported by extension operators. If you can explain what your model is and how it's exported into ONNX we might be able to provide more useful input.

Second, that's a [compressed sparse row matrix](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)). The definition is a little complicated, there are two sets of indices, the outer indices have the number of values in each row, the inner indices are the position in that row. The Java sparse tensor work isn't very well documented as it was built out for a specific use case which didn't happen and so I'm not sure how much support there is in ONNX Runtime for the rest of the parts it needs. I should probably go through and uplift the C API documentation onto the various Java tensor classes which would at least give a bit of a hint, but I've not had time.

**Comment by paranjapeved15** [comment]
@Craigacp here are some details of my model:
model: XGBoost classifier
input features: combination of some floats and ints (all numeric features)
converted to onnx as: 
convert_sklearn(
    pipe, 'pipeline_xgboost',
    initial_inputs, target_opset=18)
registered converter and shape calculator for xgboost.

**Comment by Craigacp** [comment]
I think @xadupre can probably help here as it depends on how the model converter deals with XGBoost's missing values support.

**Comment by AndreGodinho7** [comment]
Hi there, 

I am also having an issue with missing values after using an `SimpleImputer(strategy='constant', fill_value=-999)` with xgboost, as it throws the below error:
```
  File "/opt/conda/lib/python3.11/site-packages/onnxmltools/convert/xgboost/operator_converters/XGBoost.py", line 29, in validate
    raise RuntimeError("Cannot convert a XGBoost model where missing values are not "
RuntimeError: Cannot convert a XGBoost model where missing values are not nan but -999.
```

This is my pipeline:
```
MISSING_VALUE = -999

numeric_feature_selector = ColumnTransformer([
     ("selector", "passthrough", NUMERICAL_FEATURES)
 ], remainder="drop")

num_feature_imputer = SimpleImputer(strategy='constant', fill_value=MISSING_VALUE)

pipe_preprocess_numeric_old = Pipeline([
    ("feature_selector_numeric", numeric_feature_selector),
    ("feature_imputer_numeric", num_feature_imputer)
])

categorical_feature_selector = ColumnTransformer([
     ("selector", "passthrough", CATEGORICAL_FEATURES)
 ], remainder="drop")

pipe_preprocess_categoric_old = Pipeline([
    ("feature_selector_categoric", categorical_feature_selector),
    ("encoding", OrdinalEncoder()),
])

preprocessor_feu = FeatureUnion([
        ("num", pipe_preprocess_numeric_old),
        ("cat", pipe_preprocess_categoric_old),
])

model = xgb.XGBClassifier(
    max_depth=5,
    learning_rate=0.01,
    n_estimators=100,
    objective='binary:logistic',
    eval_metric=['auc', 'error', 'logloss'],
    min_child_weigth=20,
    colsample_by_tree=0.5,
    missing=MISSING_VALUE,
    tree_method='hist',
    random_state=0,
    n_jobs=-1
)

model_custom = ClassifierWrapper(model, 'predict_proba')

pipe_model = make_pipeline(preprocessor_feu, model_custom)

final_model = Pipeline([
    ('models', FeatureUnion([
        ("propensity_model", pipe_model),
        # ("uncertainty_model", pipe_uncertainty_model),
    ]))
])

final_model.fit_transform(df_features, target)

update_registered_converter(
    xgb.XGBClassifier,
    "XGBoostXGBClassifier",
    calculate_linear_classifier_output_shapes,
    convert_xgboost,
    options={"nocl": [True, False], "zipmap": [True, False, "columns"]},
)

update_registered_converter(
    ClassifierWrapper,
    "SklearnClassifierWrapper",
    classifier_wrapper_shape_calculator,
    classifier_wrapper_converter,
)

onx = convert_sklearn(
    final_model,
    "final_model",
    initial_types=dtypes_df_features,
)

```

My pipeline requires 2 `update_registered_converter` calls:
1. one for xgboost as documented in [Convert a pipeline with a XGBoost model](https://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_xgboost.html)
2. another for `ClassifierWrapper`, that is wrapping a Classifier in order to extend the `.fit()` and `.transform()` to avoid `TypeError: All estimators should implement fit and transform.`. This is because I also have other Classifiers within my pipeline, which I didn't place here so that my answer is not too verbose. Nonetheless, I leave the conversion code below, which is still in progress and more tuned to `predict_proba` calls, which was developed based on [When a custom model is neither a classifier nor a regressor](https://onnx.ai/sklearn-onnx/auto_examples/plot_custom_parser.html)

```
class ClassifierWrapper(BaseEstimator, TransformerMixin):
    def __init__(
            self,
            estimator: BaseEstimator,
            score_function: str,
            fit_params: Optional[Dict[str, Any]] = None
    ):
        TransformerMixin.__init__(self)
        BaseEstimator.__init__(self)
        self.estimator = estimator
        self.fit_params = fit_params
        self.score_function = score_function

    def fit(self, df_x: pd.DataFrame, df_y: pd.Series) -> "ClassifierWrapper":
        fit_p = self.fit_params

        if fit_p is not None:
            self.estimator_ = clone(self.estimator).fit(
                df_x, df_y, **fit_p
            )
        else:
            self.estimator_ = clone(self.estimator).fit(df_x, df_y)

        return self

    def transform(self, df_x: pd.DataFrame) -> np.ndarray:
        # result = getattr(self.estimator_, self.score_function)(df_x)

        if self.score_function == 'predict_proba':
            result = self.predict_proba(df_x)
            print(f"transform > predict_proba - type(result): {type(result)}")

        return result
    
    def predict_proba(self, df_x) -> np.ndarray:
        return self.estimator_.predict_proba(df_x)

def classifier_wrapper_shape_calculator(operator):
    input = operator.inputs[0]  # inputs in ONNX graph
    outputs = operator.outputs  # outputs in ONNX graph
    op = operator.raw_operator  # scikit-learn model (must be fitted)
    print(f"predictable_classifier_shape_calculator: len(outputs): {len(outputs)}")
    if len(outputs) != 1:
        raise RuntimeError("1 outputs expected not {}.".format(len(outputs)))

    N = input.type.shape[0]  # number of observations
    C = op.estimator_.classes_.shape[0]  # dimension of outputs

    # new output definition
    outputs[0].type = FloatTensorType([N, C])  # probability for each class in the model 

# Then the converter model. We reuse existing converter.
def classifier_wrapper_converter(scope, operator, container):
    # input = operator.inputs[0]      # input in ONNX graph
    outputs = operator.outputs  # outputs in ONNX graph
    op = operator.raw_operator  # scikit-learn model (mmust be fitted)

    # We reuse existing converter and declare it
    # as a local operator.
    model = op.estimator_
    alias = get_model_alias(type(model))
    classifier_wrapper_op = scope.declare_local_operator(alias, model)
    classifier_wrapper_op.inputs = operator.inputs

    # We add an intermediate outputs.
    classifier_wrapper_probabilities = scope.declare_local_variable("class_wrapper_prob", FloatTensorType())
    classifier_wrapper_op.outputs.append(classifier_wrapper_probabilities)

    # We adjust the output of the submodel.
    shape_calc = get_shape_calculator(alias)
    shape_calc(classifier_wrapper_op)
```

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
