### ISSUE TITLE
error: ‘nodiscard’ : onnxruntime DNNL/1DNN

### ISSUE THREAD

**Issue by Datta0** [microsoft/onnxruntime#10094]
**Describe the bug**
While trying to build onnxruntime for oneDNN for source using the command `./build.sh --enable_training --use_dnnl` , it throws the error.

**System information**
- OS Platform and Distribution : CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: N/A
- Python version: 3.9.5
- Visual Studio version (if applicable):N/A
- GCC/Compiler version (if compiling from source): 9.2.0
- CUDA/cuDNN version: None
- GPU model and memory: No GPU

**To Reproduce**
- Clone the repo https://github.com/microsoft/onnxruntime
- Run `./build.sh --enable_training --use_dnnl`

**Console output**
```
 > $ which gcc
~/GCC-9.2.0/bin/gcc
 > $ which g++
~/GCC-9.2.0/bin/g++
 > $ g++ --version
g++ (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


 > $ ./build.sh --enable_training --use_dnnl
2021-12-20 18:52:55,408 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
2021-12-20 18:52:55,409 build [DEBUG] - Command line arguments:
  --build_dir /home/nimmaturi.venkatadat/onnxruntime/build/Linux --enable_training --use_dnnl
2021-12-20 18:52:55,416 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2021-12-20 18:52:55,416 build [INFO] - Build started
2021-12-20 18:52:55,416 util.run [INFO] - Running subprocess in '/home/nimmaturi.venkatadat/onnxruntime'
  git submodule sync --recursive
Synchronizing submodule url for 'cmake/external/SafeInt/safeint'
Synchronizing submodule url for 'cmake/external/coremltools'
Synchronizing submodule url for 'cmake/external/cub'
Synchronizing submodule url for 'cmake/external/cxxopts'
Synchronizing submodule url for 'cmake/external/date'
Synchronizing submodule url for 'cmake/external/dlpack'
Synchronizing submodule url for 'cmake/external/eigen'
Synchronizing submodule url for 'cmake/external/emsdk'
Synchronizing submodule url for 'cmake/external/flatbuffers'
Synchronizing submodule url for 'cmake/external/googlebenchmark'
Synchronizing submodule url for 'cmake/external/googletest'
Synchronizing submodule url for 'cmake/external/json'
Synchronizing submodule url for 'cmake/external/libprotobuf-mutator'
Synchronizing submodule url for 'cmake/external/mimalloc'
Synchronizing submodule url for 'cmake/external/mp11'
Synchronizing submodule url for 'cmake/external/nsync'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnxruntime-extensions'
Synchronizing submodule url for 'cmake/external/protobuf'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/pytorch_cpuinfo'
Synchronizing submodule url for 'cmake/external/re2'
Synchronizing submodule url for 'cmake/external/tensorboard'
Synchronizing submodule url for 'cmake/external/tvm'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/HalideIR'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dlpack'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dmlc-core'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/tvm_update'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/cutlass'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/dlpack'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/dmlc-core'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/libbacktrace'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/tvm_update/3rdparty/vta-hw'
Synchronizing submodule url for 'cmake/external/wil'
Synchronizing submodule url for 'server/external/spdlog'
2021-12-20 18:52:57,413 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-12-20 18:52:57,414 util.run [INFO] - Running subprocess in '/home/nimmaturi.venkatadat/onnxruntime'
  git submodule update --init --recursive
2021-12-20 18:53:00,243 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-12-20 18:53:00,243 build [INFO] - Generating CMake build tree
2021-12-20 18:53:00,244 util.run [INFO] - Running subprocess in '/home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug'
  /usr/local/bin/cmake /home/nimmaturi.venkatadat/onnxruntime/cmake -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_BUILD_WINML_TESTS=ON -Donnxruntime_GENERATE_TEST_REPORTS=ON -DPython_EXECUTABLE=/home/nimmaturi.venkatadat/anaconda3/bin/python3 -DPYTHON_EXECUTABLE=/home/nimmaturi.venkatadat/anaconda3/bin/python3 -Donnxruntime_ROCM_VERSION= -Donnxruntime_USE_MIMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=OFF -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_OBJC=OFF -Donnxruntime_BUILD_SHARED_LIB=OFF -Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF -Donnxruntime_USE_DNNL=ON -Donnxruntime_DNNL_GPU_RUNTIME= -Donnxruntime_DNNL_OPENCL_ROOT= -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_OPENMP=OFF -Donnxruntime_USE_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_TENSORRT_HOME= -Donnxruntime_USE_STVM=OFF -Donnxruntime_STVM_HOME=/home/nimmaturi.venkatadat/onnxruntime/cmake/external/tvm_update -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_MIGRAPHX_HOME= -Donnxruntime_CROSS_COMPILING=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=OFF -Donnxruntime_DISABLE_RTTI=OFF -Donnxruntime_DISABLE_EXCEPTIONS=OFF -Donnxruntime_MINIMAL_BUILD=OFF -Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF -Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF -Donnxruntime_REDUCED_OPS_BUILD=OFF -Donnxruntime_REDUCED_OP_TYPE_SUPPORT=OFF -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_ENABLE_TRANSFORMERS_TOOL_TEST=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ACL_2002=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=ON -Donnxruntime_ENABLE_TRAINING_OPS=OFF -Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF -Donnxruntime_ENABLE_CPU_FP16_OPS=ON -Donnxruntime_USE_NCCL=ON -Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_ROCM=OFF -Donnxruntime_ROCM_HOME= -DOnnxruntime_GCOV_COVERAGE=OFF -Donnxruntime_USE_MPI=ON -Donnxruntime_ENABLE_MEMORY_PROFILE=OFF -Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF -Donnxruntime_BUILD_WEBASSEMBLY=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_SIMD=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF -Donnxruntime_WEBASSEMBLY_MALLOC=dlmalloc -Donnxruntime_ENABLE_EAGER_MODE=OFF -Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF -Donnxruntime_NVCC_THREADS=1 -Donnxruntime_ENABLE_CUDA_PROFILING=OFF -Donnxruntime_DEV_MODE=ON -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -Donnxruntime_ENABLE_MEMLEAK_CHECKER=ON -DCMAKE_BUILD_TYPE=Debug
Building ONNX Runtime for x86_64
Use gtest from submodule
-- Found Python: /home/nimmaturi.venkatadat/anaconda3/bin/python3 (found version "3.9.7") found components: Interpreter
Use protobuf from submodule
--
-- 3.16.0.0
-- Using the single-header code from /home/nimmaturi.venkatadat/onnxruntime/cmake/external/json/single_include/
NVCC_ERROR =
NVCC_OUT = No such file or directory
-- Found PythonInterp: /home/nimmaturi.venkatadat/anaconda3/bin/python3 (found version "3.9.7")
Generated: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-ml.proto
Generated: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-operators-ml.proto
Generated: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-data.proto
--
-- ******** Summary ********
--   CMake version             : 3.22.1
--   CMake command             : /usr/local/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 4.8.5
--   CXX flags                 :  -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -Wnon-virtual-dtor
--   Build type                : Debug
--   Compile definitions       : EIGEN_MPL2_ONLY;ENABLE_CPU_FP16_TRAINING_OPS;PLATFORM_POSIX;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : /home/nimmaturi.venkatadat/onnxruntime/cmake/external
--
--   ONNX version              : 1.10.1
--   ONNX NAMESPACE            : onnx
--   ONNX_USE_LITE_PROTO       : ON
--   USE_PROTOBUF_SHARED_LIBS  : OFF
--   Protobuf_USE_STATIC_LIBS  : ON
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
--
--   Protobuf compiler         :
--   Protobuf includes         :
--   Protobuf libraries        :
--   BUILD_ONNX_PYTHON         : OFF
-- Found MPI_C: /home/nimmaturi.venkatadat/anaconda3/lib/libmpi.so (found version "3.1")
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
CMake Warning at CMakeLists.txt:1723 (message):
  MPI is not found.  Please define onnxruntime_MPI_HOME to specify the path
  of MPI.  Otherwise, NCCL will be disabled.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug
2021-12-20 18:53:02,321 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-12-20 18:53:02,322 build [INFO] - Building targets for Debug configuration
2021-12-20 18:53:02,322 util.run [INFO] - Running subprocess in '/home/nimmaturi.venkatadat/onnxruntime'
  /usr/local/bin/cmake --build /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug --config Debug
[  0%] Performing update step for 'project_dnnl'
[  0%] No patch step for 'project_dnnl'
[  0%] Performing configure step for 'project_dnnl'
-- DNNL_LIBRARY_NAME: dnnl
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE)
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Primitive cache is enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/src/project_dnnl-build
[  1%] Performing build step for 'project_dnnl'
Consolidate compiler generated dependencies of target dnnl_cpu_x64
[ 59%] Built target dnnl_cpu_x64
Consolidate compiler generated dependencies of target dnnl_common
[ 72%] Built target dnnl_common
Consolidate compiler generated dependencies of target dnnl_cpu
[ 98%] Built target dnnl_cpu
[100%] Built target dnnl
[100%] Built target compat_libs
[100%] Built target compat_libs.2
[100%] Built target compat_libs.2.4
[  1%] Performing install step for 'project_dnnl'
[ 59%] Built target dnnl_cpu_x64
[ 72%] Built target dnnl_common
[ 98%] Built target dnnl_cpu
[100%] Built target dnnl
[100%] Built target compat_libs
[100%] Built target compat_libs.2
[100%] Built target compat_libs.2.4
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_dnnl_programming_flow.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_programming_model.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_dnnl_object_snapshot.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/conf.py
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/mem_fmt_padded_blk.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_singlescalar.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_training_inference_scope.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/mem_fmt_img2.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_bf16_diagram.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/strides.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_depthwise_fusion.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/mem_fmt_blk.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_diagram.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/unrolled_stack_rnn.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_multiscalar.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_overview_flow.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/mem_fmt_img1.png
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/rst/img_inference_scope.jpg
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/reference/html
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libdnnl.so.2.4
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libdnnl.so.2
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libdnnl.so
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_config.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_debug.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_ocl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_ocl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_sycl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_sycl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_sycl_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_threadpool.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_threadpool.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_threadpool_iface.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/dnnl_version.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn_config.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn_debug.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn_dnnl_mangling.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/mkldnn_version.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_debug.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_ocl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_ocl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_ocl_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_sycl.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_sycl.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_sycl_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_threadpool.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_threadpool.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_threadpool_iface.hpp
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_types.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_config.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/include/oneapi/dnnl/dnnl_version.h
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/cmake/dnnl/dnnl-config.cmake
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/cmake/dnnl/dnnl-config-version.cmake
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/cmake/dnnl/dnnl-targets.cmake
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/cmake/dnnl/dnnl-targets-debug.cmake
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libmkldnn.so
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libmkldnn.so.2
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/lib64/libmkldnn.so.2.4
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/LICENSE
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/THIRD-PARTY-PROGRAMS
-- Up-to-date: /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/dnnl/install/share/doc/dnnl/README
[  1%] Completed 'project_dnnl'
[  1%] Built target project_dnnl
Consolidate compiler generated dependencies of target flatbuffers
[  1%] Built target flatbuffers
Consolidate compiler generated dependencies of target clog
[  1%] Built target clog
Consolidate compiler generated dependencies of target cpuinfo
[  2%] Built target cpuinfo
Consolidate compiler generated dependencies of target libprotobuf
[  8%] Built target libprotobuf
Consolidate compiler generated dependencies of target libprotoc
[ 14%] Built target libprotoc
Consolidate compiler generated dependencies of target protoc
[ 14%] Built target protoc
[ 14%] Running gen_proto.py on onnx/onnx.in.proto
Processing /home/nimmaturi.venkatadat/onnxruntime/cmake/external/onnx/onnx/onnx.in.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-ml.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-ml.proto3
generating /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx_pb.py
[ 14%] Running C++ protocol buffer compiler on /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-ml.proto
[ 14%] Built target gen_onnx_proto
[ 14%] Running gen_proto.py on onnx/onnx-data.in.proto
Processing /home/nimmaturi.venkatadat/onnxruntime/cmake/external/onnx/onnx/onnx-data.in.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-data.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-data.proto3
generating /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx_data_pb.py
[ 14%] Running C++ protocol buffer compiler on /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-data.proto
[ 14%] Built target gen_onnx_data_proto
Consolidate compiler generated dependencies of target libprotobuf-lite
[ 16%] Built target libprotobuf-lite
[ 16%] Running gen_proto.py on onnx/onnx-operators.in.proto
Processing /home/nimmaturi.venkatadat/onnxruntime/cmake/external/onnx/onnx/onnx-operators.in.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-operators-ml.proto
Writing /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-operators-ml.proto3
generating /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx_operators_pb.py
[ 16%] Running C++ protocol buffer compiler on /home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug/external/onnx/onnx/onnx-operators-ml.proto
[ 16%] Built target gen_onnx_operators_proto
Consolidate compiler generated dependencies of target onnx_proto
[ 16%] Building CXX object external/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
[ 16%] Building CXX object external/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
[ 16%] Building CXX object external/onnx/CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
[ 16%] Linking CXX static library libonnx_proto.a
[ 16%] Built target onnx_proto
[ 16%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/nimmaturi.venkatadat/onnxruntime/onnxruntime/core/common/cpuid_info.cc.o
In file included from /home/nimmaturi.venkatadat/onnxruntime/include/onnxruntime/core/common/common.h:37:0,
                 from /home/nimmaturi.venkatadat/onnxruntime/onnxruntime/core/common/cpuid_info.h:6,
                 from /home/nimmaturi.venkatadat/onnxruntime/onnxruntime/core/common/cpuid_info.cc:22:
/home/nimmaturi.venkatadat/onnxruntime/include/onnxruntime/core/common/status.h: In function ‘constexpr const char* onnxruntime::common::StatusCodeToString(onnxruntime::common::StatusCode)’:
/home/nimmaturi.venkatadat/onnxruntime/include/onnxruntime/core/common/status.h:79:1: error: body of constexpr function ‘constexpr const char* onnxruntime::common::StatusCodeToString(onnxruntime::common::StatusCode)’ not a return-statement
 }
 ^
/home/nimmaturi.venkatadat/onnxruntime/include/onnxruntime/core/common/status.h: At global scope:
/home/nimmaturi.venkatadat/onnxruntime/include/onnxruntime/core/common/status.h:114:21: error: ‘nodiscard’ attribute directive ignored [-Werror=attributes]
 class [[nodiscard]] Status {
                     ^
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/onnxruntime_common.dir/home/nimmaturi.venkatadat/onnxruntime/onnxruntime/core/common/cpuid_info.cc.o] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_common.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/home/nimmaturi.venkatadat/onnxruntime/tools/ci_build/build.py", line 2391, in <module>
    sys.exit(main())
  File "/home/nimmaturi.venkatadat/onnxruntime/tools/ci_build/build.py", line 2309, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/nimmaturi.venkatadat/onnxruntime/tools/ci_build/build.py", line 1192, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/nimmaturi.venkatadat/onnxruntime/tools/ci_build/build.py", line 653, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/nimmaturi.venkatadat/onnxruntime/tools/python/util/run.py", line 42, in run
    completed_process = subprocess.run(
  File "/home/nimmaturi.venkatadat/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/nimmaturi.venkatadat/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.

> $

```

**Comment by skottmckay** [comment]
I don't think your local environment is being used by cmake as the cmake output has:

> -- C++ compiler : /usr/bin/c++
-- C++ compiler version : 4.8.5

**Comment by Datta0** [comment]
Sorry for the troubles, my bad.
Closing this issue
