### ISSUE TITLE
unable to find library -latomic when build onnxruntime-web

### ISSUE THREAD

**Issue by wikiwen** [microsoft/onnxruntime#10244]
**Describe the bug**
I try to build onnxruntime-web according to [page](https://github.com/microsoft/onnxruntime/tree/v1.10.0/js#onnxruntime-web).
But I build failed with `--enable_wasm_threads`.

I run these commond:
`./build.sh --config Release --build_wasm --skip_tests --disable_wasm_exception_catching --disable_rtti --parallel 24 --enable_wasm_simd --enable_wasm_threads`
but it raise **wasm-ld: error: unable to find library -latomic**

The detailed information is below
```
wasm-ld: error: unable to find library -latomic
em++: error: '/home/work/emsdk/upstream/bin/wasm-ld -o ort-wasm-simd-threaded.wasm CMakeFiles/onnxruntime_webassembly.dir/home/work/onnxruntime/onnxruntime/wasm/api.cc.o external/nsync/libnsync_cpp.a external/protobuf/cmake/libprotobuf-lite.a external/onnx/libonnx.a external/onnx/libonnx_proto.a libonnxruntime_common.a libonnxruntime_flatbuffers.a libonnxruntime_framework.a libonnxruntime_graph.a libonnxruntime_mlas.a libonnxruntime_optimizer.a libonnxruntime_providers.a libonnxruntime_session.a libonnxruntime_util.a external/re2/libre2.a external/protobuf/cmake/libprotobuf-lite.a -latomic -L/home/work/onnxruntime/cmake/external/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /home/work/onnxruntime/cmake/external/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o -lGL-mt -lal -lhtml5 -lc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -ldlmalloc-mt -lc_rt_wasm -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpxa53597v.undefined --import-memory --shared-memory --strip-debug --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=__emscripten_pthread_data_constructor --export-if-defined=__pthread_tsd_run_dtors --export-if-defined=_emscripten_call_on_thread --export-if-defined=_emscripten_main_thread_futex --export-if-defined=_emscripten_thread_init --export-if-defined=emscripten_current_thread_process_queued_calls --export-if-defined=_emscripten_allow_main_runtime_queued_calls --export-if-defined=emscripten_get_global_libc --export-if-defined=emscripten_main_browser_thread_id --export-if-defined=emscripten_main_thread_process_queued_calls --export-if-defined=emscripten_register_main_browser_thread_id --export-if-defined=emscripten_run_in_main_runtime_thread_js --export-if-defined=emscripten_stack_set_limits --export-if-defined=emscripten_sync_run_in_main_thread_2 --export-if-defined=emscripten_sync_run_in_main_thread_4 --export-if-defined=emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=pthread_testcancel --export-if-defined=pthread_exit --export-if-defined=memalign --export-if-defined=malloc --export-if-defined=free --export-if-defined=_get_tzname --export-if-defined=_get_daylight --export-if-defined=_get_timezone --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)
CMakeFiles/onnxruntime_webassembly.dir/build.make:114: recipe for target 'ort-wasm-simd-threaded.js' failed
make[2]: *** [ort-wasm-simd-threaded.js] Error 1
CMakeFiles/Makefile2:1274: recipe for target 'CMakeFiles/onnxruntime_webassembly.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_webassembly.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/work/onnxruntime/tools/ci_build/build.py", line 2362, in <module>
    sys.exit(main())
  File "/home/work/onnxruntime/tools/ci_build/build.py", line 2282, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/work/onnxruntime/tools/ci_build/build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/work/onnxruntime/tools/ci_build/build.py", line 639, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/work/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/work/software/cmake-3.22.1-linux-x86_64/bin/cmake', '--build', '/home/work/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j24']' returned non-zero exit status 2.
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v1.10.0
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by hanbitmyths** [comment]
I tried to reproduce the error, but a build was successful with '--enable_wasm_threads' option. One question is, did you build with emsdk environment out of onnxruntime? I see emsdk path is '/home/work/emsdk' from your log. An emsdk path for onnxruntime is by default 'cmake/external/emsdk' if it's not set from outside. Can you try use emsdk in onnxruntime?

**Comment by wikiwen** [comment]
> 

Thank you very much! You are right. I hava already install latest emsdk before bulding onnxruntimejs. It seems onnxruntime's emsdk don't work in this situation
