### ISSUE TITLE
量化错误，我查看了链接库确实没用找个方法

### ISSUE THREAD

**Issue by yanni1995** [microsoft/onnxruntime#10306]
Traceback (most recent call last):
  File "D:/pythonProject1/quanonnx.py", line 12, in <module>
    quantized_model = quantize_qat(model_fp32, model_quant, op_types_to_quantize=['Conv'])
  File "D:\Python\lib\site-packages\onnxruntime\quantization\quantize.py", line 349, in quantize_qat
    op_types_to_quantize)
  File "D:\Python\lib\site-packages\onnxruntime\quantization\onnx_quantizer.py", line 33, in __init__
    model = onnx.shape_inference.infer_shapes(model)
AttributeError: module 'onnx' has no attribute 'shape_inference'

**Comment by tianleiwu** [comment]
@yanni1995,

It seems that shape_inference existed since ONNX v1.2.1:
https://github.com/onnx/onnx/blob/rel-1.10.0/onnx/shape_inference.py

which version of onnx are you using?

**Comment by tianleiwu** [comment]
Close stable issue.
