### ISSUE TITLE
pthread sent an error! undefined:undefined: ortWasmThreaded is not defined

### ISSUE THREAD

**Issue by wanghsinche** [microsoft/onnxruntime#10311]
**Describe the bug**
the `onnxruntime-web` session throws error after I fed a tensor to it.
```bash
$ node dist/cjs/index.js
{
  '1333': y {
    dims: [ 1, 512 ],
    type: 'float32',
    data: Float32Array(512) [
       0.19509059190750122,   0.005832061171531677,   0.19013230502605438,
       0.07287406921386719,    0.09865348041057587,  -0.38348495960235596,
      -0.31866735219955444,   -0.06933963298797607,    0.2287290096282959,
       -0.5080304145812988,   -0.04768948629498482,  -0.19477435946464539,
       0.15714240074157715, -0.0070142000913619995,   -0.2809197008609772,
         0.693807065486908,     0.3640846014022827,   -0.6380854845046997,
      0.024721451103687286,   -0.05640354007482529,   0.13146863877773285,
       0.09124630689620972,     0.2906871438026428,   -0.3516911566257477,
        0.2665897011756897,     0.1177620068192482, -0.003499045968055725,
        -0.555557131767273,   -0.14366188645362854,    0.7694481015205383,
       -0.5368849635124207,     0.6752858757972717,   -0.2616346776485443,
      -0.16207267343997955,    0.14834225177764893,  -0.23971784114837646,
        0.6265624761581421,    -0.1812530755996704,  -0.43627047538757324,
      0.000588681548833847,   -0.03934420645236969,   0.16445469856262207,
       0.44608235359191895,     0.4290218949317932,    0.5170336961746216,
       0.22228360176086426,   -0.04835335910320282,   -0.3905872106552124,
      -0.09506790339946747,  -0.017808526754379272,   -0.3220152258872986,
      -0.08404305577278137,    0.06856104731559753, -0.011806145310401917,
       0.25164735317230225,   0.013864099979400635,  -0.31206727027893066,
      -0.09955008327960968,  -0.001577228307723999,  -0.14273464679718018,
       0.24552685022354126,    0.11774954199790955,  -0.25029006600379944,
        0.0345984548330307,   -0.31446129083633423,   -0.4163998067378998,
       0.07797203958034515,   -0.22405347228050232,    0.2915961742401123,
      -0.21091671288013458,    -0.3281900882720947,   -0.4504505395889282,
      -0.19990746676921844,   -0.13711559772491455,  -0.10851071774959564,
       0.39865660667419434,    0.09274126589298248,   0.12686434388160706,
        0.5724270939826965,   -0.26828765869140625,    0.1480923891067505,
       0.01165253110229969,    0.46217626333236694, -0.056762829422950745,
        0.5808461904525757,   -0.20943908393383026,   -0.5674686431884766,
      -0.40804797410964966,   -0.09278246760368347,   0.22424444556236267,
       0.49996843934059143,   -0.14078037440776825,   0.27184420824050903,
       0.30232805013656616,  -0.059233419597148895,  -0.16002193093299866,
         0.565786600112915,   -0.20660731196403503,   0.06134903430938721,
       0.08788184821605682,
      ... 412 more items
    ],
    size: 512
  }
}
worker.js onmessage() captured an uncaught exception: ReferenceError: ortWasmThreaded is not defined

```
I am very sure the input tensor is converted in right shape because it works in `onnxruntime-node` .

**Urgency**
 none.

**System information**
- Linux Ubuntu 18 at WSL2:
- ONNX Runtime installed from (source or binary):     "onnxruntime-web": "^1.10.0"
- ONNX Runtime version: 1.10.0
- node version: v16.13.1
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: none
- GPU model and memory: 

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by CanyonWind** [comment]
found a similar problem, could someone share some thoughts plz?

**Comment by luisfelipesayavedra** [comment]
same issue here

**Comment by digitarald** [comment]
Got another case ([repo](https://github.com/microsoft/vscode-extension-recommender) which only affects Node 16. It works with 12.x and 14.x.

```
/mnt/vss/_work/1/s/node_modules/onnxruntime-web/dist/ort-web.node.js:6
…

ReferenceError [Error]: ortWasmThreaded is not defined
    at self.onmessage (node_modules/onnxruntime-web/dist/ort-wasm-threaded.worker.js:6:1186)
    at MessagePort.<anonymous> (node_modules/onnxruntime-web/dist/ort-wasm-threaded.worker.js:6:202)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

**Comment by rchiodo** [comment]
I figured out a workaround (although this may depend upon how you're loading it).

Set the BUILD_DEFS.DISABLE_WASM_THREAD to true. 

Here's what it looks like in my webpack:

```
        new webpack.DefinePlugin({
            BUILD_DEFS: {
                DISABLE_WEBGL: true,
                DISABLE_WASM: false,
                DISABLE_WASM_THREAD: true,
            },
        }),

```

**Comment by DavidGOrtega** [comment]
> I figured out a workaround (although this may depend upon how you're loading it).
> 
> Set the BUILD_DEFS.DISABLE_WASM_THREAD to true.
> 
> Here's what it looks like in my webpack:
> 
> ```
>         new webpack.DefinePlugin({
>             BUILD_DEFS: {
>                 DISABLE_WEBGL: true,
>                 DISABLE_WASM: false,
>                 DISABLE_WASM_THREAD: true,
>             },
>         }),
> ```
> 
> That should skip the code that attempts to load the ortWasmThreaded

@rchiodo  You can just set the number of threads to 1 to avoid the issue.

```
const ort = require('onnxruntime-web');
ort.env.wasm.numThreads = 1
```

However this is not fixing the real issue that is not being able to run wasm multithreaded.
