### ISSUE TITLE
Failed to load Library - OnnxRuntime Yolov5 GPU Support C#

### ISSUE THREAD

**Issue by MagnusGabell** [microsoft/onnxruntime#10336]
**Describe the bug**
I have made a program .net6 Console app in VS 2022 C# that can use the Yolo5 model as onnx format for CPU. When changing the library to GPU I get

Microsoft.ML.OnnxRuntime.OnnxRuntimeException
HResult=0x80131500
Message=[ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
Source=Microsoft.ML.OnnxRuntime
StackTrace:
at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithCudaProvider(Int32 deviceId)
at Yolov5Net.App.Program.Main(String[] args) in C:\Development\YoloV5\yolov5-net\src\Yolov5Net.App\Program.cs:line 23

How can I get the program to utilize the GPU instead of CPU?
I have installed : cuda and cuDNN according to instructions.
Tested latest and version 10.1.
Graphic card is Quadro M1200.

System information

OS: Windows 10
Model: Yolo5l
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

To Reproduce
Write a code for CPU then change to GPU by adding a
var opts = new SessionOptions(); opts.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE; var so = SessionOptions.MakeSessionOptionWithCudaProvider(1);
It crash on MakeSessionOptionWithCudaProvider(1). I dont want to use 0 cause its built in GFX.
![image](https://user-images.githubusercontent.com/8070347/150298829-60978e75-5df5-4f86-95ee-a90887ce61ce.png)

Additional context
Please help. I dont know how to get this final step to work. The libraries are all copied in to bin. They exists everywhere.
Is this related to the Windows 10 pipeline issue for onnx?

**Comment by yuslepukhin** [comment]
If you have dev environment handy, run this recursively on every of the below DLLs and find out which one is missing in your setup:

dumpbin /DEPENDENTS onnxruntime_providers_cuda.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30138.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file onnxruntime_providers_cuda.dll

File Type: DLL

  Image has the following dependencies:

    cublas64_11.dll
    cudnn64_8.dll
    cufft64_10.dll
    onnxruntime_providers_shared.dll
    cudart64_110.dll
    KERNEL32.dll
    MSVCP140D.dll
    VCRUNTIME140D.dll
    VCRUNTIME140_1D.dll
    ucrtbased.dll

**Comment by MagnusGabell** [comment]
Hi,
Thanks for replying. The dumpbin has the following:

Dump of file onnxruntime_providers_cuda.dll

File Type: DLL

  Image has the following dependencies:

    cublas64_11.dll
    cudnn64_8.dll
    cufft64_10.dll
    onnxruntime_providers_shared.dll
    cudart64_110.dll
    api-ms-win-core-synch-l1-1-0.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll

  Summary

        1000 .00cfg
      122000 .data
        B000 .gfids
        5000 .idata
        1000 .nvFatBi
    11D7D000 .nv_fatb
       40000 .pdata
      174000 .rdata
       15000 .reloc
        1000 .rsrc
      EE6000 .text
        1000 .tls

**Comment by skottmckay** [comment]
> I dont want to use 0 cause its built in GFX.

Do you have two separate CUDA capable GPUs or just one?

Does it work if you set device to `0` instead of `1`?

**Comment by MagnusGabell** [comment]
I have 1 cude supported gpu. Its my laptop so it has these:
![image](https://user-images.githubusercontent.com/8070347/150745950-41ef6342-dff2-48d8-a1bd-ed0d86966724.png)

**Comment by skottmckay** [comment]
That's a different error to what you had previously. What ONNX Runtime nuget packages are you using? Can you try 1.10 as that has some additional handling for errors around CUDA library loads.

**Comment by skottmckay** [comment]
> Perhaps I should mention that I use VS2022 and dumpbin does not exist in that installation.

It exists. Open a Developer {Powershell|Command Prompt} for VS 2022 for the path to be automatically populated.

Should be somewhere like C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\HostX86\x86\dumpbin.exe

**Comment by MagnusGabell** [comment]
> > Perhaps I should mention that I use VS2022 and dumpbin does not exist in that installation.
> 
> It exists. Open a Developer {Powershell|Command Prompt} for VS 2022 for the path to be automatically populated.
> 
> Should be somewhere like C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\HostX86\x86\dumpbin.exe

Nope. But it does not matter. I search the entire folder. I had VS2019 installed and that solved it :D Might be a package I didnt install with the VS2022

**Comment by MagnusGabell** [comment]
> 
You are right. Different error. Didn't see that. Still dont know how to proceed. I will double check the code so that I have not changed anything else. Sorry 'bout that.

**Comment by MagnusGabell** [comment]
> That's a different error to what you had previously. What ONNX Runtime nuget packages are you using? Can you try 1.10 as that has some additional handling for errors around CUDA library loads.
> 
> As there is only one CUDA device, use device id of 0.

The difference and why I got the new error was that I read somewhere that I should only have onnxRuntime and not onnxruntime.GPU.

So the new error is when I do NOT use onnxRuntime.GPU but only .onnxRuntime. Changing back to ONLY having xxx.GPU I get the missing reference.

**Comment by skottmckay** [comment]
I'm using v1.10 without issue.

The Packages in my solution look like this:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/979079/150876355-84a402dc-83de-4831-8dbb-b610fed6ae3f.png">

If I get the path to the ORT GPU package and look at the symbols in the native onnxruntime.dll I see the necessary exports.

```
> dumpbin /exports C:\Users\s\.nuget\packages\microsoft.ml.onnxruntime.gpu\1.10.0\runtimes\win-x64\native\onnxruntime.dll
Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\s\.nuget\packages\microsoft.ml.onnxruntime.gpu\1.10.0\runtimes\win-x64\native\onnxruntime.dll

File Type: DLL

  Section contains the following exports for onnxruntime.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           4 number of functions
           4 number of names

    ordinal hint RVA      name

          1    0 00021C00 OrtGetApiBase = OrtGetApiBase
          2    1 000F2F60 OrtSessionOptionsAppendExecutionProvider_CPU = OrtSessionOptionsAppendExecutionProvider_CPU
          3    2 00032640 OrtSessionOptionsAppendExecutionProvider_CUDA = OrtSessionOptionsAppendExecutionProvider_CUDA
          4    3 00032220 OrtSessionOptionsAppendExecutionProvider_Tensorrt = OrtSessionOptionsAppendExecutionProvider_Tensorrt
```

Can you please check you see the same, and that the onnxruntime.dll in the build output directory (probably under something like bin\Debug\net6.0\runtimes\win-x64\native\onnxruntime.dll) is the same?

**Comment by MagnusGabell** [comment]
> > Perhaps I should mention that I use VS2022 and dumpbin does not exist in that installation.
> 
> It exists. Open a Developer {Powershell|Command Prompt} for VS 2022 for the path to be automatically populated.
> 
> Should be somewhere like C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\HostX86\x86\dumpbin.exe

DUMPBIN is being shipped within Common Tools for Visual C++, so be sure to select this feature in the process of installation of Visual Studio. The utility resides at:

**Comment by MagnusGabell** [comment]
> I'm using v1.10 without issue.
> 
> The Packages in my solution look like this:
> 
> <img alt="image" width="267" src="https://user-images.githubusercontent.com/979079/150876355-84a402dc-83de-4831-8dbb-b610fed6ae3f.png">
> 
> If I get the path to the ORT GPU package and look at the symbols in the native onnxruntime.dll I see the necessary exports.
> 
> ```
> > dumpbin /exports C:\Users\s\.nuget\packages\microsoft.ml.onnxruntime.gpu\1.10.0\runtimes\win-x64\native\onnxruntime.dll
> Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> Dump of file C:\Users\s\.nuget\packages\microsoft.ml.onnxruntime.gpu\1.10.0\runtimes\win-x64\native\onnxruntime.dll
> 
> File Type: DLL
> 
>   Section contains the following exports for onnxruntime.dll
> 
>     00000000 characteristics
>     FFFFFFFF time date stamp
>         0.00 version
>            1 ordinal base
>            4 number of functions
>            4 number of names
> 
>     ordinal hint RVA      name
> 
>           1    0 00021C00 OrtGetApiBase = OrtGetApiBase
>           2    1 000F2F60 OrtSessionOptionsAppendExecutionProvider_CPU = OrtSessionOptionsAppendExecutionProvider_CPU
>           3    2 00032640 OrtSessionOptionsAppendExecutionProvider_CUDA = OrtSessionOptionsAppendExecutionProvider_CUDA
>           4    3 00032220 OrtSessionOptionsAppendExecutionProvider_Tensorrt = OrtSessionOptionsAppendExecutionProvider_Tensorrt
> ```
> 
> Can you please check you see the same, and that the onnxruntime.dll in the build output directory (probably under something like bin\Debug\net6.0\runtimes\win-x64\native\onnxruntime.dll) is the same?

This is my dump (using 2022 after installing C++ tools)
![image](https://user-images.githubusercontent.com/8070347/150930120-7385c5e3-50bb-4de4-9ddd-c5f0ad7f300b.png)

Then in my bin folder I have:
![image](https://user-images.githubusercontent.com/8070347/150930231-6a96adef-a719-48f0-ba64-b36af0eaa32d.png)

**Comment by MagnusGabell** [comment]
I created a new .NET6 app and just added the necessities:
![image](https://user-images.githubusercontent.com/8070347/150930931-78b5d47d-7cf7-4ecb-86e1-65f94595f9b8.png)

No luck. Same problem

**Comment by skottmckay** [comment]
It's calling the OrtSessionOptionsAppendExecutionProvider_CUDA entry point but failing to find the necessary CUDA libraries when attempting to create the CUDA execution provider. Are the CUDA libraries you installed accessible in the PATH?

You can add something like this to dump the environment and check the contents of the PATH value. 

```c#
            IDictionary environmentVariables = Environment.GetEnvironmentVariables();
            foreach (DictionaryEntry de in environmentVariables)
            {
                Console.WriteLine("  {0} = {1}", de.Key, de.Value);
            }
```

Alternatively you could open onnxruntime_providers_cuda.dll in https://github.com/lucasg/Dependencies and check it can find all the necessary CUDA dlls.

**Comment by MagnusGabell** [comment]
I dumpt out the env. variables:
[env_variables.txt](https://github.com/microsoft/onnxruntime/files/7931598/env_variables.txt)

**Comment by skottmckay** [comment]
I believe v1.10 of ORT requires CUDA 11.x as per https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

Can you try with a more recent CUDA version?

**Comment by MagnusGabell** [comment]
hi, I will update...

**Comment by MagnusGabell** [comment]
I installed Cuda11 toolkit and same problem. Will try to uninstall Cuda 10

**Comment by skottmckay** [comment]
Please confirm that the PATH environment variable the C# app is using includes your new CUDA install bin directory (would potentially need to restart Visual Studio to pickup that change to the environment variables), and that the bin directory contains 

cublas64_11.dll
cudnn64_8.dll
cufft64_10.dll
cudart64_110.dll

**Comment by MagnusGabell** [comment]
Thats it! I search for all the dll above and copied them to my project. Then added "Copy if newer".
Now it compiles without problem. Seems like it cant find the dll's or does not copy to my project with nuget install.

I wont celebrate just yet. Will try my original program and if that works I owe you!

**Comment by MagnusGabell** [comment]
Thanks for your patience and support! It now compiles without errors. I do not get any GPU-usage so it still must be utilizing the CPU but the compilation error is gone and I close this and open a new one! Again! appreciate the support!

**Comment by skottmckay** [comment]
The complete list of CUDA dlls isn't actually known to ORT. Some additional ones may be internally loaded by the CUDA dlls as they execute, and those don't show up as explicit dependencies. For example with the model I tested, during execution the CUDA code needed to load cudnn_cnn_infer64_8.dll (and that also has a dependency on zlibwapi.dll). 

As such it's easier to make sure the complete CUDA install directory is in the path and those dlls aren't copied to the build output directory. Alternatively you would need to figure out the complete list of CUDA dlls by copying the explicit dependencies and then working through any errors during execution for other missing ones.

**Comment by skottmckay** [comment]
You can check node assignments by setting logging to VERBOSE in the session options. When the model is loaded there will be a message saying which nodes are assigned to the CUDA EP. 

```c#
            so.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE;
```

e.g.
```
2022-01-25 21:15:44.0451722 [V:onnxruntime:, inference_session.cc:153 onnxruntime::`anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] Node placements
2022-01-25 21:15:44.0452611 [V:onnxruntime:, inference_session.cc:155 onnxruntime::`anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] All nodes have been placed on [CUDAExecutionProvider].
```

**Comment by MagnusGabell** [comment]
Thanks. I understand the problem. I would prefer to have the Path working cause, as you mention, I now get issues with cudnn_cnn_infer64_8.dll and even if I copied them it still cant get pass it. So I guess I need to ensure the PATH settings working properly. Damn annoying. Always like this with AI-stuff. worse in Linux :-|

**Comment by skottmckay** [comment]
Absolutely painful. :)

Make sure you have installed the zlib dll as cudnn_cnn_infer64_8.dll requires that. It's mentioned in the [prerequisites section](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#prerequisites-windows) of the cuDNN installation guide.

I overlooked that when I did my setup and discovered the missing dependency using https://github.com/lucasg/Dependencies

**Comment by MagnusGabell** [comment]
My god. I have now "installed" also the zlib. The Path variables to these: 
cublas64_11.dll
cudnn64_8.dll
cufft64_10.dll
cudart64_110.dll
should they be in the windows environment path or in VS? Cuase it does not like the windows env. settings

**Comment by MagnusGabell** [comment]
Never ending story....

2022-01-25 12:43:36.3685790 [I:onnxruntime:, inference_session.cc:273 onnxruntime::InferenceSession::ConstructorCommon::<lambda_170e990513fc9d5f38b2e7643b4ded3c>::operator ()] Flush-to-zero and denormal-as-zero are off
2022-01-25 12:43:36.3687303 [I:onnxruntime:, inference_session.cc:280 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2022-01-25 12:43:38.8014544 [I:onnxruntime:, inference_session.cc:1228 onnxruntime::InferenceSession::Initialize] Initializing session.
2022-01-25 12:43:38.8016350 [I:onnxruntime:, inference_session.cc:1265 onnxruntime::InferenceSession::Initialize] Adding default CPU execution provider.
2022-01-25 12:43:38.8671627 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '562'. It is no longer used by any node.
2022-01-25 12:43:38.8673154 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '745'. It is no longer used by any node.
2022-01-25 12:43:38.8679013 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '627'. It is no longer used by any node.
2022-01-25 12:43:38.8680330 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '682'. It is no longer used by any node.
2022-01-25 12:43:38.8682053 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '568'. It is no longer used by any node.
2022-01-25 12:43:38.8685175 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '671'. It is no longer used by any node.
2022-01-25 12:43:38.8688887 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '681'. It is no longer used by any node.
2022-01-25 12:43:38.8693488 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '621'. It is no longer used by any node.
2022-01-25 12:43:38.8695811 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '738'. It is no longer used by any node.
2022-01-25 12:43:38.8697111 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '566'. It is no longer used by any node.
2022-01-25 12:43:38.8698371 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '677'. It is no longer used by any node.
2022-01-25 12:43:38.8699480 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '569'. It is no longer used by any node.
2022-01-25 12:43:38.8706995 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '685'. It is no longer used by any node.
2022-01-25 12:43:38.8710489 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '561'. It is no longer used by any node.
2022-01-25 12:43:38.8713099 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '619'. It is no longer used by any node.
2022-01-25 12:43:38.8715338 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '634'. It is no longer used by any node.
2022-01-25 12:43:38.8717904 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '565'. It is no longer used by any node.
2022-01-25 12:43:38.8720190 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '737'. It is no longer used by any node.
2022-01-25 12:43:38.8722822 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '678'. It is no longer used by any node.
2022-01-25 12:43:38.8725444 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '739'. It is no longer used by any node.
2022-01-25 12:43:38.8727989 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '740'. It is no longer used by any node.
2022-01-25 12:43:38.8730545 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '741'. It is no longer used by any node.
2022-01-25 12:43:38.8735306 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '742'. It is no longer used by any node.
2022-01-25 12:43:38.8746384 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '743'. It is no longer used by any node.
2022-01-25 12:43:38.8750466 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '744'. It is no longer used by any node.
2022-01-25 12:43:38.8756147 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '746'. It is no longer used by any node.
2022-01-25 12:43:38.8758707 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '747'. It is no longer used by any node.
2022-01-25 12:43:38.8761067 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '748'. It is no longer used by any node.
2022-01-25 12:43:38.8765960 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is no longer used by any node.
2022-01-25 12:43:38.8791081 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is no longer used by any node.
2022-01-25 12:43:38.8796068 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '626'. It is no longer used by any node.
2022-01-25 12:43:38.8803063 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '684'. It is no longer used by any node.
2022-01-25 12:43:38.8808031 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '679'. It is no longer used by any node.
2022-01-25 12:43:38.8811957 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '729'. It is no longer used by any node.
2022-01-25 12:43:38.8821765 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '692'. It is no longer used by any node.
2022-01-25 12:43:38.8836838 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '691'. It is no longer used by any node.
2022-01-25 12:43:38.8853714 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '624'. It is no longer used by any node.
2022-01-25 12:43:38.8858538 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '633'. It is no longer used by any node.
2022-01-25 12:43:38.8861121 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '563'. It is no longer used by any node.
2022-01-25 12:43:38.8864191 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '613'. It is no longer used by any node.
2022-01-25 12:43:38.8868615 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '576'. It is no longer used by any node.
2022-01-25 12:43:38.8871048 [I:onnxruntime:, graph.cc:3529 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '575'. It is no longer used by any node.
2022-01-25 12:43:38.8900434 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2022-01-25 12:43:38.8933430 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2022-01-25 12:43:38.9052683 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2022-01-25 12:43:38.9565621 [V:onnxruntime:, inference_session.cc:153 onnxruntime::`anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] Node placements
2022-01-25 12:43:38.9567644 [V:onnxruntime:, inference_session.cc:155 onnxruntime::`anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] All nodes have been placed on [CUDAExecutionProvider].
2022-01-25 12:43:38.9715747 [V:onnxruntime:, session_state.cc:67 onnxruntime::SessionState::CreateGraphInfo] SaveMLValueNameIndexMapping
2022-01-25 12:43:38.9720100 [V:onnxruntime:, session_state.cc:113 onnxruntime::SessionState::CreateGraphInfo] Done saving OrtValue mappings.
Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!

**Comment by MagnusGabell** [comment]
is this something?
![image](https://user-images.githubusercontent.com/8070347/150972766-43c9ac94-8328-4cc9-95af-752047595a8d.png)

Msiing dependency oobe-query-11-1-0

**Comment by MagnusGabell** [comment]
I copied the cuDNN dlls to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin
This removed the failure of finding the files. :-|

It now utilizes the GPU. However extreamly slow and I hope it has to do with the program reinitializing some cuda-context for every image and can be abstracted so that it only insert new image into the pipeline and not recreate it every time.

Path environment settings does not work to solve the reference to the files.

**Comment by MagnusGabell** [comment]
it says in the output that is adding Default CPU execution provider which I assume means that it does not fully utilize the GPU
![image](https://user-images.githubusercontent.com/8070347/151003352-5fecfdce-3469-42fe-bc52-26ef03817997.png)

**Comment by skottmckay** [comment]
> 2022-01-25 12:43:38.9565621 [V:onnxruntime:, inference_session.cc:153 onnxruntime::anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] Node placements 2022-01-25 12:43:38.9567644 [V:onnxruntime:, inference_session.cc:155 onnxruntime::anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp] All nodes have been placed on [CUDAExecutionProvider].

Based on this output all nodes were assigned to GPU.

ORT CUDA EP requires both CUDA and cuDNN. It could be said more explicitly on https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements instead of you having to infer it from the two columns in the version info table.

There are a long list of runs for how/where a library can be loaded. Using PATH works for me with all the CUDA and cuDNN dlls in one directory (as per the cuDNN install instructions which says to copy files to the CUDA install paths).

Regarding speed, how are you creating the input values? The 'ToTensor' helpers are horribly inefficient. Fixed in the lastest code but that isn't in the 1.10 release. 

When we execute the input data needs to be copied from CPU to CUDA and the results from CUDA to CPU. That device copy time can be significant if the model is fast. If you can batch up some images that should reduce the per-image overhead. 

When measuring performance to compare CPU vs CUDA make sure it's just for the InferenceSession.Run. CPU won't have the device copy overhead in that call so it's possible CPU can be faster for smaller models (although for yolov5l I wouldn't expect that to be the case).

**Comment by mgabell** [comment]
> Based on this output all nodes were assigned to GPU. - **Cool. I just saw that in the startup it said all were added to CPU so didn't trust the line :D**
> 
> ORT CUDA EP requires both CUDA and cuDNN. It could be said more explicitly on https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements instead of you having to infer it from the two columns in the version info table. **It seems I am terrible at reading instructions from nVidia. Thanks for your patience**
> 
> There are a long list of rules for how/where a library can be loaded. Using PATH works for me with all the CUDA and cuDNN dlls in one directory (as per the cuDNN install instructions which says to copy files to the CUDA install paths). **This seems to work for me too. once I copied cuDNN to CUDA it worked. But strange still. Why not just add two PATH locations. But doesn't mater as long as it works.**
> 
> Regarding speed, how are you creating the input values? The 'ToTensor' helpers are horribly inefficient. Fixed in the lastest code but that isn't in the 1.10 release. **This I will look into. and see if I understand what you mean when I look into the code**
> 
> When we execute the input data needs to be copied from CPU to CUDA and the results from CUDA to CPU. That device copy time can be significant if the model is fast. If you can batch up some images that should reduce the per-image overhead.
**What I did was to load all images into a List<ImageObject> consisting of the Image. This was then introduced to the for loop executing the inference. I will show you how I do it. I have a hunch that is bad practice.**
> 
> When measuring performance to compare CPU vs CUDA make sure it's just for the InferenceSession.Run. CPU won't have the device copy overhead in that call so it's possible CPU can be faster for smaller models (although for yolov5l I wouldn't expect that to be the case). 

**For this I have made two things, first I have, like you probably got, is that I measure the loop time. The time it takes for the program to read the image from the List and until it picks up the next. So sure some CPU-GPU overhead. I have not created any threading, so I could have more consumers, but its just one and one. I have made this in python too and using 10 threads for consuming and one for producing I get 45fps roughly at 1600x1300 input image size. So the one second it takes for ML seems like there must be more than just the threading and consuming more at the same time. I think there are more to the input data and how it execute the inference. As a comparison (different model) on a Jetson with tensor flow you create a GPU context outside of the loop and threading. It feels like that is somehow making things more efficient. That is the reason I think I reinitialize things with my new construction in C#**

**Comment by MagnusGabell** [comment]
Seems like I have two accounts. Sorry for the confusion. 
Anyhow. I have attached my code that I use. I ripped it from BobLd. I dont know where to look when you talk about the creating the input values.  
Note that their commit for the Yolo5 branch is not working, there are some minor adjustments that were needed, that I made to the code attached.
https://github.com/BobLd/YOLOv4MLNet/tree/yolo-v5

Zip attached. 
[Yolo5GPU.zip](https://github.com/microsoft/onnxruntime/files/7948782/Yolo5GPU.zip)
d

**Comment by skottmckay** [comment]
Looking at the code there are no calls to the ORT ToTensor extension methods so that concern doesn't apply.

The 1600x1300 images you're processing are massive. If you can do so without sacrificing accuracy I'd strongly suggest resizing them to something smaller to greatly improve performance (or retraining the model with smaller images).

ORT has an IOBinding facility that can be used if the model input/output is on GPU to avoid CPU <-> GPU device copies. However you're resizing the image during pre-processing so I don't think that's applicable here. Possibly you could do the copy to GPU prior to the 'run' call to parallelize a bit more.

**Comment by MagnusGabell** [comment]
Hi, Thanks. I think its strange though. I run the yolo model in linux and python at 45 fps . I feed the model with 1600x1300 images and resize them. I must agree its not comparable since the python is run on a RX3090 and 10 threads where as this is run on the Quadro M1200. So sure. But What is so apparent is that the GPU and CPU speed appears to be the same.

I think (I think, I am not training, and havent checked the script) the images in the pytorch Yolo model is resized too into 640x640px. So retrain does not make sense. What I could believe is that the CPU and GPU processing is the same due to the copying and that my GFX-card is so slow compared to RTX3090 that is appears as the CPU is equally fast due to overhead copying. 

I think I will create a threaded version and create an image queue that will send the images to the GPU. This, if kept in .net core I can use in linux too. Perhaps I can compile and run the program in linux where I have the 3090. (Probably dead end with the Cuda cuDNN versions :(
