### ISSUE TITLE
build onnxruntime error linux

### ISSUE THREAD

**Issue by SuperGoKong** [microsoft/onnxruntime#10364]
**Describe the bug**
I build the onnxruntime in linux system. command is: ./build.sh --skip_tests --use_cuda --config Release --build_shared_lib --parallel --cuda_home /usr/local/cuda-11.5 --cudnn_home /usr/local/cuda-11.5

[ 41%] Built target onnxruntime_framework
make: *** [Makefile:166：all] 错误 2
Traceback (most recent call last):
  File "/home/didi/test_model/onnxruntime/tools/ci_build/build.py", line 2397, in <module>
    sys.exit(main())
  File "/home/didi/test_model/onnxruntime/tools/ci_build/build.py", line 2315, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/didi/test_model/onnxruntime/tools/ci_build/build.py", line 1191, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/didi/test_model/onnxruntime/tools/ci_build/build.py", line 654, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/didi/test_model/onnxruntime/tools/python/util/run.py", line 42, in run
    completed_process = subprocess.run(
  File "/home/didi/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/didi/test_model/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.

**System information**
-  Linux Ubuntu 18.04:
- ONNX Runtime installed from source 
- ONNX Runtime version: 1.11.0
- Python version:3.8
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:11.3
- GPU model and memory:2g

**Comment by tianleiwu** [comment]
Is there other error message?

I used to build like the following
```
export CUDACXX="/usr/local/cuda/bin/nvcc"

sh build.sh --config Release  --build_shared_lib --parallel  --use_cuda --cuda_version  11.0 --cuda_home /usr/local/cuda --cudnn_home /usr/local/cuda --build_wheel --skip_test --cmake_path /usr/local/bin/cmake 
```

**Comment by goksinan** [comment]
I faced the same issue on my Linux machine after downgrading the gcc compiler (4.8.5). I think what fixed the issue for me was switching back to gcc 7.5, but I tried the following as well:

1. Sometimes building older versions of onnxruntime helps:
```
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
git checkout v1.10.0
```

2. You can try a previous version of CMake rather than the latest one. There are prebuilt binaries for Linux here [https://github.com/Kitware/CMake/releases](https://github.com/Kitware/CMake/releases). Try 3.18 for example.
```
./build.sh --config Release--build_shared_lib --parallel --cmake_path <download_directory>/cmake-3.18.6-Linux-x86_64/bin/cmake
```
