### ISSUE TITLE
Error: 'libcublas.so.9.1: cannot open shared object file: No such file or directory' with the latest Cuda version

### ISSUE THREAD

**Issue by adriacabeza** [microsoft/onnxruntime#1049]
I am using onnxruntime for the inference of my model (which comes from keras). When I use CPU with onnxruntime everything goes well, but when I install onnxruntime-gpu (by using pip) I do get a CUDA error. My first guess was that the library versions did not match but since I do have a later version (v10) I believe it should work too.

My error message:

```bash
/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/_pybind_state.py:12: UserWarning: Cannot load onnxruntime.capi. Error: 'libcublas.so.9.1: cannot open shared object file: No such file or directory'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "fromKeras2ONNXRuntimewithTRT.py", line 7, in <module>
    import onnxruntime as rt
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'
```

**System information**
- Linux Ubuntu 16.04
-  ONNX Runtime installed by pip
- ONNX Runtime 0.4.0 (both CPU and GPU)
- Python 3.5.2
- Cuda compilations tools V.10.1.105

Some more information
```bash
➜  /workspace ldconfig -v |  grep libcublas
/sbin/ldconfig.real: Path `/usr/local/cuda/lib64' given more than once
/sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib64: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.23.so is the dynamic linker, ignoring

	libcublasLt.so.10 -> libcublasLt.so.10.1.0.105
	libcublas.so.10 -> libcublas.so.10.1.0.105**

```

**Comment by snnn** [comment]
>  I do have a later version (v10) I believe it should work too.
Sorry, it's not true.  see: [http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html)

If the program was built with CUDA 9.0, you could run it with cuda 9.1, but not 10.x or 8.x. The major number can't be changed.  This is a general rule from the system's linker.

**Comment by adriacabeza** [comment]
Hey @snnn,  I downgraded to CUDA 9.0 (I am working an TensorRT 4.0 image) and I still do get the same error:

``` 
/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/_pybind_state.py:12: UserWarning: Cannot load onnxruntime.capi. Error: 'libcublas.so.9.1: cannot open shared object file: No such file or directory'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "fromKeras2ONNXRuntimewithTRT.py", line 7, in <module>
    import onnxruntime as rt
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'  
```


Here some information:
``` 
dpkg -l | grep -i cuda
ii  cuda-command-line-tools-9-0        9.0.176-1                             amd64        CUDA command-line tools
ii  cuda-core-9-0                      9.0.176-1                             amd64        CUDA core tools
ii  cuda-cublas-9-0                    9.0.425-1                             amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-9-0                9.0.425-1                             amd64        CUBLAS native dev links, headers
ii  cuda-cudart-9-0                    9.0.176-1                             amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-9-0                9.0.176-1                             amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-9-0                     9.0.176-1                             amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-9-0                 9.0.176-1                             amd64        CUFFT native dev links, headers
ii  cuda-curand-9-0                    9.0.176-1                             amd64        CURAND native runtime libraries
ii  cuda-curand-dev-9-0                9.0.176-1                             amd64        CURAND native dev links, headers
ii  cuda-cusolver-9-0                  9.0.176-1                             amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-9-0              9.0.176-1                             amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-9-0                  9.0.176-1                             amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-9-0              9.0.176-1                             amd64        CUSPARSE native dev links, headers
ii  cuda-driver-dev-9-0                9.0.176-1                             amd64        CUDA Driver native dev stub library
ii  cuda-license-9-0                   9.0.425-1                             amd64        CUDA licenses
ii  cuda-misc-headers-9-0              9.0.176-1                             amd64        CUDA miscellaneous headers
ii  cuda-npp-9-0                       9.0.176-1                             amd64        NPP native runtime libraries
ii  cuda-npp-dev-9-0                   9.0.176-1                             amd64        NPP native dev links, headers
ii  cuda-nvgraph-9-0                   9.0.176-1                             amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-9-0               9.0.176-1                             amd64        NVGRAPH native dev links, headers
ii  cuda-nvml-dev-9-0                  9.0.176-1                             amd64        NVML native dev links, headers
ii  cuda-nvrtc-9-0                     9.0.176-1                             amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-9-0                 9.0.176-1                             amd64        NVRTC native dev links, headers
ii  libcudnn7                          7.2.1.38-1+cuda9.0                    amd64        cuDNN runtime libraries
ii  libcudnn7-dev                      7.2.1.38-1+cuda9.0                    amd64        cuDNN development libraries and headers
ii  libnccl-dev                        2.2.13-1+cuda9.0                      amd64        NVIDIA Collectives Communication Library (NCCL) Development Files
ii  libnccl2                           2.2.13-1+cuda9.0                      amd64        NVIDIA Collectives Communication Library (NCCL) Runtime
ii  libnvinfer-dev                     4.1.2-1+cuda9.0                       amd64        TensorRT development libraries and headers
ii  libnvinfer-samples                 4.1.2-1+cuda9.0                       amd64        TensorRT samples and documentation
ii  libnvinfer4                        4.1.2-1+cuda9.0                       amd64        TensorRT runtime libraries
ii  python3-libnvinfer                 4.1.2-1+cuda9.0                       amd64        Python 3 bindings for TensorRT
ii  python3-libnvinfer-dev             4.1.2-1+cuda9.0                       amd64        Python 3 development package for TensorRT
ii  python3-libnvinfer-doc             4.1.2-1+cuda9.0                       amd64        Documention and samples of python bindings for TensorRT
ii  tensorrt                           4.0.1.6-1+cuda9.0                     amd64        Meta package of TensorRT 
```


``` 
dpkg -l | grep -i nvidia
ii  libnccl-dev                        2.2.13-1+cuda9.0                      amd64        NVIDIA Collectives Communication Library (NCCL) Development Files
ii  libnccl2                           2.2.13-1+cuda9.0                      amd64        NVIDIA Collectives Communication Library (NCCL) Runtime
```



System information
Linux Ubuntu 16.04
ONNX Runtime installed by pip
ONNX Runtime 0.4.0 (both CPU and GPU)
Python 3.5.2

What am I missing?

**Comment by snnn** [comment]
Gould you try cuda 9.1 instead?

**Comment by adriacabeza** [comment]
@snnn 

I can't because the TensorRT image I am working with needs or Cuda 9.0 or Cuda 10.1

Is there a way to make it work with 9.0 as you said before?

**Comment by snnn** [comment]
You can:
1. Either install multiple cuda versions. (They won't conflict with each other)
2.  Or build onnxruntime by yourself. Then you can choose either CUDA 9.1 or CUDA 10.x.

**Comment by adriacabeza** [comment]
@snnn I am trying to build it by myself and even though I specify cuda,cdnn and tensorrt, whenever it finishes I still get CPU as my device and I do want to use my GPU.

**Comment by deimsdeutsch** [comment]
I am facing the same issue and its quite ridiculous. We cannot change the cuda version of because of dependencies. Can you guys release a build for cuda 9.0. Also the naming-conventions no way specify which version is compatible with which version of cuda leading to too much confusion.

**Comment by snnn** [comment]
Please pardon me, tensorflow, like us, only support CUDA 10.0.  see: https://www.tensorflow.org/install/gpu
