### ISSUE TITLE
Resize error: Scale value should be greater than 0.

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/onnxruntime#10513]
**Describe the bug**
The Resize/Cubic Operator incorrectly identifies empty scales as illegal scales.

**Network Architecture**
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/19810594/153340395-f044269f-6ebe-4519-925e-55ff798a8f69.png">

[netflix-progdown-by2.onnx.zip](https://github.com/microsoft/onnxruntime/files/8038207/netflix-progdown-by2.onnx.zip)

**Reproduce**
1. This model file can be loaded correctly by onnx runtime (with `onnx.checker.check_model(onnx_model)`).
2. We use `polygraphy` to test the onnx file, and the logs are:

Command:
`polygraphy run netflix-progdown-by2.onnx --onnxrt --verbose --float-min=1 --float-max=2 --int-min=1 --int-max=2`

**Error Log**
```
2022-02-10 01:26:16.330086005 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running Resize node. Name:'Resize__69' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsample.h:286 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.Traceback (most recent call last):
  File "/home/jianh/.local/bin/polygraphy", line 72, in <module>
    sys.exit(main())
  File "/home/jianh/.local/bin/polygraphy", line 63, in main
    status = args.subcommand(args)
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/tools/base/tool.py", line 134, in __call__
    return self.run(args)
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/tools/run/run.py", line 180, in run
    exec(str(script))
  File "<string>", line 29, in <module>
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/comparator/comparator.py", line 223, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/comparator/comparator.py", line 134, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/backend/base/runner.py", line 170, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/home/jianh/.local/lib/python3.6/site-packages/polygraphy/backend/onnxrt/runner.py", line 69, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/home/jianh/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Resize node. Name:'Resize__69' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsample.h:286 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.
```

**Comment by hariharans29** [comment]
Why do you say the Resize operator incorrectly identifies empty scales as illegal ?

The [ONNX spec for Resize](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize) says this: "It takes value greater than 0. If it's less than 1, it's sampling down, otherwise, it's upsampling. " 

So, per the standard, ORT's complaint seems valid.

**Comment by hijkzzz** [comment]
> Why do you say the Resize operator incorrectly identifies empty scales as illegal ?
> 
> The [ONNX spec for Resize](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize) says this: "It takes value greater than 0. If it's less than 1, it's sampling down, otherwise, it's upsampling."
> 
> So, per the standard, ORT's complaint seems valid.

Hi, the attr `scale` of Resize in this network is empty; So the attr `size` should actually be used to calculate the output size, Rather than check legitimacy of attr `scale`.

**Comment by hariharans29** [comment]
In that case, [scales is again computed](https://github.com/microsoft/onnxruntime/blob/7e092a7e3f8f9f590de0ac5548035e8fa4d512f8/onnxruntime/core/providers/cpu/tensor/upsample.h#L354) from the `sizes` and the `X`'s shape and it seems like when these "computed scales" are validated , it hits the issue that one or more of these computes scales is 0.

This seems to be a dynamic shape model. This error could point to feeding in input shapes that the model can't handle either because it is not trained to handle these shapes or there was a problem during export to a dynamic shape model.

**Comment by xunleiw** [comment]
Hello @hariharans29,
How can I resize a -1x768x128x128 tensor to -1x768x256x256 by using "sizes" parameter of "Resize" op?
Do I have to specify "scales [1,1,2,2]" and set "sizes" empty?
