### ISSUE TITLE
error: definition of implicit copy constructor for 'SafeInt<unsigned long>' is deprecated because it hasprovided copy assignment operator [-Werror,-Wdeprecated-copy-with-user-provided-copy]

### ISSUE THREAD

**Issue by luopengting** [microsoft/onnxruntime#10585]
**Describe the bug**
When i executed `./build.sh --config Release --build_wasm --skip_tests --disable_wasm_exception_catching --disable_rtti`, errors:
```
[ 16%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o
In file included from /home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:5:
In file included from /home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.h:28:
In file included from /home1/workspace/onnxruntime/onnxruntime/core/common/safeint.h:35:
/home1/workspace/onnxruntime/cmake/external/SafeInt/safeint/SafeInt.hpp:5725:35: error: definition of implicit copy constructor for 'SafeInt<unsigned long>' is deprecated because it hasprovided copy assignment operator [-Werror,-Wdeprecated-copy-with-user-provided-copy]
    _CONSTEXPR14 SafeInt< T, E >& operator =( const SafeInt< T, E >& rhs ) SAFEINT_NOTHROW
                                  ^
/home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:136:22: note: in implicit copy constructor for 'SafeInt<unsigned long>' first required here
      while (bytes > curr_region_allocation_bytes_) {
                     ^
1 error generated.
em++: error: '/home1/app/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_t -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home1/workspace/onnxruntime/cmake/external/emsdk/uemscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DMLAS_NO_ONNXRUNTIME_THREADPOOL -DNSYNC_ATOMIC_CPP11 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DONNX__PROTO=1 -DORT_NO_RTTI -DPLATFORM_POSIX -D__ONNX_NO_DOC_STRINGS -I/home1/workspace/onnxruntime/include/onnxruntime -I/home1/workspace/onnxruntime/include/onnxruntime/core/sessome1/workspace/onnxruntime/cmake/external/nsync/public -I/home1/workspace/onnxruntime/build/Linux/Release -I/home1/workspace/onnxruntime/onnxruntime -I/home1/workspace/onnxruntime/cmake/external/eigen -I/include -I/home1/workspace/onnxruntime/cmake/external/SafeInt -I/home1/workspace/onnxruntime/cmake/external/mp11/include -I/home1/l005rkspace/onnxruntime/cmake/external/onnx -I/home1/workspace/onnxruntime/build/Linux/Release/external/onnx -I/home1/workspace/onnxruntime/cmake/external/protobuf/src -I/home1/l0workspace/onnxruntime/cmake/external/flatbuffers/include -ffunction-sections -fdata-sections -flto -O3 -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -fPIC -fno-rtti -Wall -Wextra -Wno-unused-pa-Werror -std=gnu++17 -MD -MT CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o -MF CMakeFiles/onnxruntime_framework.dir/home1/l0workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o.d -c /home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc -o CMakeFiles/onnxruntime_framework.dir/home1/l/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o' failed (returned 1)
CMakeFiles/onnxruntime_framework.dir/build.make:121: recipe for target 'CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o' faile
make[2]: *** [CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc.o] Error 1
CMakeFiles/Makefile2:1073: recipe for target 'CMakeFiles/onnxruntime_framework.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_framework.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 2362, in <module>
    sys.exit(main())
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 2282, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 639, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home1/workspace/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/home1/miniconda3/envs/torch_py37/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home1/miniconda3/envs/torch_py37/bin/cmake', '--build', '/home1/workspace/onnxruntime/build/Linux/Release', '--config', 'Release']'  non-zero exit status 2.

```

**Urgency**
Important, today.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary):source 
- ONNX Runtime version:[v1.10.0](https://github.com/microsoft/onnxruntime/releases/tag/v1.10.0)
- Python version:3.7.5
- Visual Studio version (if applicable):NA
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**To Reproduce**
Execute `./build.sh --config Release --build_wasm --skip_tests --disable_wasm_exception_catching --disable_rtti`

**Expected behavior**
Build successfully.

**Screenshots**
NA

**Additional context**
NA

**Comment by hanbitmyths** [comment]
It's not reproducible. Are you using your own emscripten for build instead of emsdk submodule in onnxruntime?

**Comment by luopengting** [comment]
![image](https://user-images.githubusercontent.com/22173722/154790090-464e1d35-1491-4077-b42e-00e84d776d40.png)

I unset the environment variable about `em`. Problem solved. Thanks a lot!
