### ISSUE TITLE
error: parameter 'b' set but not used [-Werror,-Wunused-but-set-parameter]

### ISSUE THREAD

**Issue by luopengting** [microsoft/onnxruntime#10584]
**Describe the bug**
When i execute: `./build.sh --config Release --build_wasm --skip_tests --disable_wasm_exception_catching --disable_rtti
`
Errors:
```
[ 23%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o
In file included from /home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc:4:
In file included from /home1/workspace/onnxruntime/onnxruntime/core/common/safeint.h:35:
/home1/workspace/onnxruntime/cmake/external/SafeInt/safeint/SafeInt.hpp:1324:46: error: parameter 'b' set but not used [-Werror,-Wunused-but-set-parameter]
    _CONSTEXPR14 static void CastThrow( bool b, T& t ) SAFEINT_CPP_THROW
                                             ^
1 error generated.
em++: error: '/home1/l00521040/app/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -fvisibility=default -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=34 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/home1/workspace/onnxruntime/cmake/external/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DBUILD_MLAS_NO_ONNXRUNTIME -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DNSYNC_ATOMIC_CPP11 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO=1 -DORT_NO_RTTI -DPLATFORM_POSIX -D__ONNX_NO_DOC_STRINGS -I/home1/workspace/onnxruntime/include/onnxruntime -I/home1/workspace/onnxruntime/include/onnxruntime/core/session -I/home1/workspace/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src -I/home1/workspace/onnxruntime/cmake/external/nsync/public -I/home1/l00521040/workspace/onnxruntime/build/Linux/Release -I/home1/onnxruntime/onnxruntime -I/home1/l00521040/workspace/onnxruntime/cmake/external/eigen -I/include -I/home1/workspace/onnxruntime/cmake/external/SafeInt -I/home1/workspace/onnxruntime/cmake/external/mp11/include -I/home1/workspace/onnxruntime/cmake/external/onnx -I/home1/workspace/onnxruntime/build/Linux/Release/external/onnx -I/home1/workspace/onnxruntime/cmake/external/protobuf/src -I/home1/workspace/onnxruntime/cmake/external/flatbuffers/include -ffunction-sections -fdata-sections -flto -O3 -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -fPIC -fno-rtti -Wall -Wextra -Wno-unused-parameter -Werror -std=gnu++17 -MD -MT CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o -MF CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o.d -c /home1/l00521040/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc -o CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o' failed (returned 1)
CMakeFiles/onnxruntime_framework.dir/build.make:91: recipe for target 'CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_framework.dir/home1/workspace/onnxruntime/onnxruntime/core/framework/allocator.cc.o] Error 1
CMakeFiles/Makefile2:1584: recipe for target 'CMakeFiles/onnxruntime_framework.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_framework.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 2418, in <module>
    sys.exit(main())
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 2333, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 1194, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home1/workspace/onnxruntime/tools/ci_build/build.py", line 655, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home1/workspace/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/home1/miniconda3/envs/torch_py37/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home1/l00521040/miniconda3/envs/torch_py37/bin/cmake', '--build', '/home1/workspace/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.

```

**Urgency**
Important, today.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: commit ccd7a2d8407c37c264258cb79725cd2cb6b31328
- Python version:3.7.5
- Visual Studio version (if applicable):NA
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**To Reproduce**
execute: `./build.sh --config Release --build_wasm --skip_tests --disable_wasm_exception_catching --disable_rtti
`

**Expected behavior**

**Screenshots**

**Additional context**
Is this a bug? When I modify `onnxruntime/cmake/external/SafeInt/safeint/SafeInt.hpp` :  line1324
Modify
```
_CONSTEXPR14 static void CastThrow( bool b, T& t ) SAFEINT_CPP_THROW
```
as
```
_CONSTEXPR14 static void CastThrow( T t, bool& b ) SAFEINT_CPP_THROW
```

It fixed!

**Comment by hanbitmyths** [comment]
Same as [here](https://github.com/microsoft/onnxruntime/issues/10585). It's not reproducible. I think you're using your own emsdk instead of a submodule in onnxruntime repo.

**Comment by luopengting** [comment]
> Same as [here](https://github.com/microsoft/onnxruntime/issues/10585). It's not reproducible. I think you're using your own emsdk instead of a submodule in onnxruntime repo.

![image](https://user-images.githubusercontent.com/22173722/154603572-9d2cc547-e4d7-4dc1-9ffe-9d27102d607b.png)

Maybe it's because I configured environment variables.
I'll cancel it and try again.
