### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by Stoooner** [microsoft/onnxruntime#10600]
在Ubuntu18.04上编译onnxruntime时遇到的错误：
Checking python scripts for PEP8 conformance using flake8
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:5:1: D205 1 blank line required between summary line and description
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:10:15: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:11:14: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:13:1: I101 Imported names are in the wrong order. Should be ExecutionMode, ExecutionOrder, GraphOptimizationLevel, ModelMetadata, NodeArg, OrtAllocatorType, OrtArenaCfg, OrtDevice, OrtMemType, OrtMemoryInfo, RunOptions, SessionIOBinding, SessionOptions, create_and_register_allocator, disable_telemetry_events, enable_telemetry_events, get_all_providers, get_available_providers, get_device, set_default_logger_severity, set_seed
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:23:1: I101 Imported names are in the wrong order. Should be IOBinding, InferenceSession, OrtValue
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:23:1: I202 Additional newline in a group of imports. 'from onnxruntime.capi.onnxruntime_inference_collection import InferenceSession, IOBinding, OrtValue' is identified as Third Party and 'from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, RunOptions, SessionOptions, set_default_logger_severity, enable_telemetry_events, disable_telemetry_events, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode, ExecutionOrder, OrtDevice, SessionIOBinding, OrtAllocatorType, OrtMemType, OrtArenaCfg, OrtMemoryInfo, create_and_register_allocator' is identified as Third Party.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:24:1: I100 Import statements are in the wrong order. 'from onnxruntime.capi import onnxruntime_validation' should be before 'from onnxruntime.capi.onnxruntime_inference_collection import InferenceSession, IOBinding, OrtValue'
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/__init__.py:26:1: I202 Additional newline in a group of imports. 'from onnxruntime.capi.training import *' is identified as Third Party and 'from onnxruntime.capi import onnxruntime_validation' is identified as Third Party.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/python/__init__.py:1:1: D104 Missing docstring in public package
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/python/_pybind_state.py:9:1: I201 Missing newline between import groups. 'import onnxruntime.capi._ld_preload' is identified as Third Party and 'import warnings' is identified as Stdlib.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/onnxruntime/python/_pybind_state.py:25:23: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:38:36: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:43:1: D103 Missing docstring in public function
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:44:41: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:48:15: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:73:1: D103 Missing docstring in public function
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:75:25: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/download_cmake.py:75:60: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:1:1: D100 Missing docstring in public module
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:12:1: I201 Missing newline between import groups. 'import mysql.connector' is identified as Third Party and 'import argparse' is identified as Stdlib.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:13:1: I100 Import statements are in the wrong order. 'import json' should be before 'import mysql.connector' and in a different group.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:13:1: I201 Missing newline between import groups. 'import json' is identified as Stdlib and 'import mysql.connector' is identified as Third Party.
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:15:1: I100 Import statements are in the wrong order. 'import os' should be before 'import sys'
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:18:1: D103 Missing docstring in public function
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:20:21: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:21:25: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:21:46: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:23:9: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:23:31: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:24:25: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:24:47: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:28:1: D103 Missing docstring in public function
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:40:1: D103 Missing docstring in public function
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:86:1: B902 blind except Exception: statement
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:91:16: Q000 Double quotes found but single quotes preferred
[flake8 PEP8 ERROR] /home/stoner/vscode_workplace/onnxruntime/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py:96:1: B902 blind except Exception: statement
CMakeFiles/pep8_check.dir/build.make:81: recipe for target 'CMakeFiles/pep8_check' failed
make[2]: *** [CMakeFiles/pep8_check] Error 1
CMakeFiles/Makefile2:1913: recipe for target 'CMakeFiles/pep8_check.dir/all' failed
make[1]: *** [CMakeFiles/pep8_check.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/stoner/vscode_workplace/onnxruntime/tools/ci_build/build.py", line 2088, in <module>
    sys.exit(main())
  File "/home/stoner/vscode_workplace/onnxruntime/tools/ci_build/build.py", line 2023, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/stoner/vscode_workplace/onnxruntime/tools/ci_build/build.py", line 1060, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/stoner/vscode_workplace/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/stoner/vscode_workplace/onnxruntime/tools/python/util/run.py", line 42, in run
    env=env, shell=shell)
  File "/home/stoner/anaconda3/envs/stark/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/stoner/vscode_workplace/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
-------------------------------------------------------------------------------------------------------------
已经编译到98%了，出现了大面积的[flake8 PEP8 ERROR] ，编译的命令如下：
./build.sh --build_shared_lib --skip_tests --config Release --use_cuda --cudnn_home /usr/local/cuda/ --cuda_home /usr/local/cuda  --use_tensorrt --tensorrt_home /home/stoner/TensorRT-7.2.3.4/
还麻烦大佬们帮忙看看咋回事呢

**Comment by skottmckay** [comment]
What version of flake8 are you using and is there anything non-standard about your flake8 installation? Normally we would see error codes starting with 'F' from flake8, but your output does not have that. https://flake8.pycqa.org/en/latest/user/error-codes.html

We run flake8 in CI builds and see no errors currently (build would fail if there were errors).
