### ISSUE TITLE
Building OnnxRuntime v1.10.0 with CUDAExecutionProvider for sm_75 GPU fails in CUDA10.2 environment

### ISSUE THREAD

**Issue by lp6m** [microsoft/onnxruntime#10610]
**Describe the bug**
Building OnnxRuntime v1.10.0 with CUDAExecutionProvider for sm_75 GPU fails in CUDA10.2 environment.
The [CUDAExecutionProvider documentation](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) says that onnxruntime v1.10.0 requires CUDA 11.4 to use the CUDAExecutionProvider.   
But the [Jetson Zoo](https://elinux.org/Jetson_Zoo#ONNX_Runtime) has `onnxruntime-gpu` package for JetPack with CUDA 10.2, so I am now trying to build v1.10.0 for x86_64 architecture with CUDA 10.2.  
Building OnnxRuntime v1.10.0 with CUDAExecutionProvider fails in this error:

```
nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)
nvcc error   : 'ptxas' core dumped
CMakeFiles/onnxruntime_providers_cuda.dir/build.make:1377: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/workspaces/cuda10_ort_build/onnxruntime/onnxruntime/core/providers/cuda/math/topk_impl.cu.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/workspaces/cuda10_ort_build/onnxruntime/onnxruntime/core/providers/cuda/math/topk_impl.cu.o] Error 139
CMakeFiles/Makefile2:1300: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/workspaces/cuda10_ort_build/onnxruntime/tools/ci_build/build.py", line 2362, in <module>
    sys.exit(main())
  File "/workspaces/cuda10_ort_build/onnxruntime/tools/ci_build/build.py", line 2282, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/workspaces/cuda10_ort_build/onnxruntime/tools/ci_build/build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/workspaces/cuda10_ort_build/onnxruntime/tools/ci_build/build.py", line 639, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/workspaces/cuda10_ort_build/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/workspaces/cuda10_ort_build/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j40']' returned non-zero exit status 2.
```
When I remove the [`sm_75` architecture specification](https://github.com/microsoft/onnxruntime/blob/v1.10.0/cmake/CMakeLists.txt#L1604) from CMAKE_CUDA_FLAGS, the build will all succeed.  
CUDA10.2 is supposed to support the sm_75 architecture, so I think there needs to be some kind of modification to file `onnxruntime/core/providers/cuda/math/topk_impl.cu`.  
Do you have any information about this problem?

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v1.10.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA:10.2.89, cuDNN: 7.6.5
- GPU model and memory: V100/RTX2070(both failed)

**To Reproduce**

### build environment
https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_21-07.html
```
docker pull nvcr.io/nvidia/tensorrt:20.03-py3
```

### build command
```
git clone --recursive -b v1.10.0 https://github.com/microsoft/onnxruntime
cd onnxruntime
pip install cmake
./build.sh \
--config Release \
--cudnn_home /usr/lib/x86_64-linux-gnu/ \
--cuda_home /usr/local/cuda \
--use_cuda \
--enable_pybind \
--build_wheel \
--parallel $(nproc) \
--skip_tests
```

**Expected behavior**
build success

**Screenshots**

**Additional context**

**Comment by JaheimLee** [comment]
Same problem. Is there any progress?

**Comment by sunjunlishi** [comment]
Same problem. Is there any progress? yes,me too

**Comment by sunjunlishi** [comment]
--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52
