### ISSUE TITLE
QLinearGlobalAveragePool error occurred while inference quantized model with "INT8"

### ISSUE THREAD

**Issue by kmss1258** [microsoft/onnxruntime#10617]
Hello, I quantize own model from here (https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/run.py)
The model seems to be successfully quantized with INT8, but inference fails with the following error:

> Traceback (most recent call last):
  File "run_for_quantize_gap_ops.py", line 151, in <module>
    main()
  File "run_for_quantize_gap_ops.py", line 147, in main
    benchmark(output_model_path)
  File "run_for_quantize_gap_ops.py", line 90, in benchmark
    _ = session.run([], {input_name1: input_data1, input_name2: input_data2})
  File "/home/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running QLinearGlobalAveragePool node. Name:'GlobalAveragePool_1_quant' Status Message: /onnxruntime_src/onnxruntime/contrib_ops/cpu/qlinear_global_average_pool.cc:98 virtual onnxruntime::common::Status onnxruntime::contrib::QLinearGlobalAveragePool::Compute(onnxruntime::OpKernelContext*) const Unsupported 'dtype' value: 3

dtype value 3 seems to mean INT8.
I calibrate the model with dummy data, and quantize the model with following code : 

> quantize_static(input_model_path,
                    output_model_path,
                    dr,
                    quant_format=args.quant_format,
                    per_channel=args.per_channel,
                    activation_type=**QuantType.QInt8**, 
                    weight_type=**QuantType.QInt8**)

QuantType.**QUInt8** can inference successfully, but QInt8 is not.
I think QLinearGLobalAveragePool is available to use int8 datatype in here (https://github.com/microsoft/onnxruntime/blob/master/docs/ContribOperators.md#com.microsoft.QLinearGlobalAveragePool).

What can I do to use **UInt8** by inference in **QLinearGlobalAveragePool**?

my simple model file : [cpu.zip](https://github.com/microsoft/onnxruntime/files/8112846/cpu.zip)

my system info
> Windows 10 : python 3.7, onnxruntime 1.10.0, onnx 1.10.2, no gpu
Ubuntu 20.04 (with WSL2) : python 3.8.10, onnxruntime 1.10.0, onnx 1.10.2, no gpu

**Comment by kmss1258** [comment]
I solved this problem through onnxruntime build by myself. It seems like some bug in public pip package.

The build environment is as follows : 

> Windows 10 64bits, no gpu, python 3.7, onnxruntime 1.11.0 (own build), onnx 1.10.0 (for opset version 15, not 16), Visual Studio 2019

Build command as follows :
> .\build.bat --config RelWithDebInfo --build_shared_lib --build_wheel --parallel --cmake_generator "Visual Studio 16 2019”

And some additional command : 
> pip3 install --upgrade ./build/Windows/RelWithDebInfo/RelWithDebInfo/dist/onnxruntime-1.11.0-cp37-cp37m-win_amd64.whl
