### ISSUE TITLE
[ORTModule] Tensors are not in the same device

### ISSUE THREAD

**Issue by jiafatom** [microsoft/onnxruntime#10897]
**Describe the bug**
When I am working on wrapping a pytorch module through ORTModule, I have the following issue:
```python
 f'See details below:\n\n{_utils.get_exception_as_string(self._exception)}'), UserWarning)
dule.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./MainzVision/Networks/Image/cls_vit.py", line 517, in forward
    x, prev = blk(x, prev)
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "./MainzVision/Networks/Image/cls_vit.py", line 233, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x)))
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/tmp/code/MainzVision/MainzTrainerCore/MainzTrain/Models/Networks/moe_module/ort_moe/moe.py", line 251, in forward
    combine_weights, dispatch_mask, capacity_fp = self.gate(reshaped_input, nonpadding=reshaped_nonpadding, lid=kwargs.get('lid', -1))
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/tmp/code/MainzVision/MainzTrainerCore/MainzTrain/Models/Networks/moe_module/ort_moe/topKgate.py", line 414, in forward
    lid=lid,
  File "/tmp/code/MainzVision/MainzTrainerCore/MainzTrain/Models/Networks/moe_module/ort_moe/topKgate.py", line 578, in top1gating
    indices_s = torch.where(mask1_sum_dim1 > 0, indices_s, num_experts) # Assign tokens to "expert num_experts" (fake expert) for dropping cases
RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:4 and x and y are on cuda:4 and cpu respectively


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_utils.py", line 254, in get_exception_as_string
    raise exception
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_utils.py", line 254, in get_exception_as_string
    raise exception
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_utils.py", line 254, in get_exception_as_string
    raise exception
  [Previous line repeated 2 more times]
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_training_manager.py", line 231, in forward
    build_gradient_graph = self._export_model(*inputs, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 322, in _export_model
    schema, *inputs, **kwargs)
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 392, in _get_exported_model
    RuntimeError(f'There was an error while exporting the PyTorch model to ONNX: '
  File "/home/jiafa/.local/lib/python3.6/site-packages/onnxruntime/training/ortmodule/_fallback_exceptions.py", line 72, in wrap_exception
    raise new_exception(raised_exception) from raised_exception
onnxruntime.training.ortmodule._fallback_exceptions.ORTModuleONNXModelException: There was an error while exporting the PyTorch model to ONNX: 
```
In short, for `indices_s = torch.where(mask1_sum_dim1 > 0, indices_s, num_experts)`, `indices_s` is on cuda and `num_experts` is on cpu. This is a big model, so I haven't got a small reproduced model yet. To give more contexts, `num_experts = logits.shape[1]` is a shape value, so it is on cpu. `indices_s = torch.argmax(logits_w_noise if logits_gumbel > 0 else gates, dim = 1)` is on cuda.

**Urgency**
This is from our internal users.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 
- ONNX Runtime installed from (source or binary): binary 
- ONNX Runtime version: onnxruntime_training-1.11.0.dev20220125001
- Python version: 3.6

**Comment by pengwa** [comment]
Sounds like a bug related to PyTorch exporter?

**Comment by jingyanwangms** [comment]
Moving the scalar to cuda `torch.tensor(num_experts).to(device='cuda')` works, but this error is not there for Pytorch no ORTModule so we should fix it. Likely in exporter
