### ISSUE TITLE
kalid-onnxruntime  Fatal error: Gemm is not a registered function/op

### ISSUE THREAD

**Issue by supersaint001** [microsoft/onnxruntime#11021]
**Describe the bug**
final.onnx is convert from kaldi (final.mdl)

    self.ort_session = onnxruntime.InferenceSession("final.onnx")

Traceback (most recent call last):
  File "load.py", line 25, in <module>
    load_model_onnx('final.onnx')
  File "load.py", line 6, in load_model_onnx
    self.ort_session = onnxruntime.InferenceSession(onnx_model_path)
  File "/home/work/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/work/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 370, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from final.onnx failed:Fatal error: Gemm is not a registered function/op

**Comment by fs-eire** [comment]
Hi @supersaint001 could you share us the final.onnx file or the complete steps of model converting?
