### ISSUE TITLE
onnxruntime==1.11.0 installation error in python 3.10.0

### ISSUE THREAD

**Issue by hanzigs** [microsoft/onnxruntime#11064]
Hi,
I am upgrading my python to 3.10.0, currently using 3.9.5 where onnxruntime==1.8.0 working good.
I installed 1.11.0 and 1.10.0 in py3.10.0, I am getting following error while installing
May I have some help please

with 1.11.0
```
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.11.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime==1.11.0
```
with 1.10.0
```
Collecting onnxmltools==1.10.0
  Downloading onnxmltools-1.10.0-py2.py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 6.4 MB/s
Collecting onnx
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
Requirement already satisfied: numpy in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from onnxmltools==1.10.0) (1.21.5)
Collecting skl2onnx
  Downloading skl2onnx-1.11-py2.py3-none-any.whl (274 kB)
     |████████████████████████████████| 274 kB 6.8 MB/s
Requirement already satisfied: protobuf>=3.12.2 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from onnx->onnxmltools==1.10.0) (3.19.4)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from onnx->onnxmltools==1.10.0) (4.1.1)
Collecting onnxconverter-common>=1.7.0
  Downloading onnxconverter_common-1.9.0-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB ...
Requirement already satisfied: scikit-learn>=0.19 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from skl2onnx->onnxmltools==1.10.0) (1.0.2)
Requirement already satisfied: scipy>=1.0 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from skl2onnx->onnxmltools==1.10.0) (1.8.0)
Requirement already satisfied: joblib>=0.11 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from scikit-learn>=0.19->skl2onnx->onnxmltools==1.10.0) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pg\anaconda3\envs\automlpy3100t2\lib\site-packages (from scikit-learn>=0.19->skl2onnx->onnxmltools==1.10.0) (3.1.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\pg\anaconda3\envs\autoMLpy3100t2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"'; __file__='"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\pg\AppData\Local\Temp\pip-wheel-8_uqqxd7'
       cwd: C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\
  Complete output (59 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b']
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:17 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/pg/AppData/Local/Temp/pip-install-8q_xncv0/onnx_d78f6ccfe11d46dc8be0ac1f2484e37b/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 336, in <module>
      setuptools.setup(
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 232, in run
      self.run_command('cmake_build')
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 218, in run
      subprocess.check_call(cmake_args)
    File "C:\Users\pg\anaconda3\envs\py3100t2\lib\subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\pg\\anaconda3\\envs\\py3100t2\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\pg\\anaconda3\\envs\\py3100t2\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx, onnxconverter-common, skl2onnx, onnxmltools
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\pg\anaconda3\envs\autoMLpy3100t2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"'; __file__='"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pg\AppData\Local\Temp\pip-record-ytvjgwq3\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\pg\anaconda3\envs\py3100t2\Include\onnx'
         cwd: C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\
    Complete output (60 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\pg\\anaconda3\\envs\\autoMLpy3100t2\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b']
    CMake Error at CMakeLists.txt:17 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.


    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/pg/AppData/Local/Temp/pip-install-8q_xncv0/onnx_d78f6ccfe11d46dc8be0ac1f2484e37b/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 336, in <module>
        setuptools.setup(
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\command\install.py", line 568, in run
        self.run_command('build')
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 232, in run
        self.run_command('cmake_build')
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\pg\AppData\Local\Temp\pip-install-8q_xncv0\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\setup.py", line 218, in run
        subprocess.check_call(cmake_args)
      File "C:\Users\pg\anaconda3\envs\py3100t2\lib\subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\pg\\anaconda3\\envs\\py3100t2\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\pg\\anaconda3\\envs\\py3100t2\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\pg\\anaconda3\\envs\\py3100t2\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp310-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.10', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\pg\anaconda3\envs\py3100t2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"'; __file__='"'"'C:\\Users\\pg\\AppData\\Local\\Temp\\pip-install-8q_xncv0\\onnx_d78f6ccfe11d46dc8be0ac1f2484e37b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pg\AppData\Local\Temp\pip-record-ytvjgwq3\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\pg\anaconda3\envs\py3100t2\Include\onnx' Check the logs for full command output.
```

**Comment by ytaous** [comment]
Hi, our onnxruntime does not officially support python 3.10, would it work if you try torch 1.11 + python 3.9?
https://download.onnxruntime.ai/

**Comment by hanzigs** [comment]
Thanks for the reply, I haven't tried with torch
Will there be any updates in near future, Thanks

**Comment by ytaous** [comment]
> Thanks for the reply, I haven't tried with torch Will there be any updates in near future, Thanks

what's your torch version? 1.10+ will be better. Perhaps you leave torch, and fall back just python to 3.9 and see it works for you.

**Comment by hanzigs** [comment]
I am not using torch, if I use py 3.9 with onnxruntime==1.8.0 it is working good,
Just would like to know whether there will be update for py 3.10, Thanks

**Comment by ytaous** [comment]
> I am not using torch, if I use py 3.9 with onnxruntime==1.8.0 it is working good, Just would like to know whether there will be update for py 3.10, Thanks

I see, then here is the link to our latest, again 3.10 has not been supported yet. I don't have estimated timing since we are just releasing 1.11. So I think it might be a few months away. 
https://pypi.org/project/onnxruntime/1.11.0/#files

**Comment by hanzigs** [comment]
Thank you vey much for the update
