### ISSUE TITLE
ONNXQuantizer: ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3850562186

### ISSUE THREAD

**Issue by reuben** [microsoft/onnxruntime#11072]
**Describe the bug**
Can't quantize a model larger than 2GB using `onnxruntime.quantization.quantize_dynamic`.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.3
- ONNX Runtime installed from (source or binary): PyPI
- ONNX Runtime version: 1.11
- Python version: 3.7

**To Reproduce**

Run the following script:

```python
import argparse
import torch
from onnxruntime.quantization.quantize import quantize
from transformers import Wav2Vec2ForCTC


def convert_to_onnx(model_id_or_path, onnx_model_name):
    model = Wav2Vec2ForCTC.from_pretrained(model_id_or_path)
    audio_len = 250000

    x = torch.randn(1, audio_len, requires_grad=True)

    torch.onnx.export(
        model,  # model being run
        x,  # model input (or a tuple for multiple inputs)
        onnx_model_name,  # where to save the model (can be a file or file-like object)
        export_params=True,  # store the trained parameter weights inside the model file
        opset_version=11,  # the ONNX version to export the model to
        do_constant_folding=True,  # whether to execute constant folding for optimization
        input_names=["input"],  # the model's input names
        output_names=["output"],  # the model's output names
        dynamic_axes={
            "input": {1: "audio_len"},  # variable length axes
            "output": {1: "audio_len"},
        },
    )


def quantize_onnx_model(onnx_model_path, quantized_model_path):
    print("Starting quantization...")
    from onnxruntime.quantization import QuantType, quantize_dynamic

    quantize_dynamic(
        onnx_model_path, quantized_model_path, weight_type=QuantType.QUInt8
    )

    print(f"Quantized model saved to: {quantized_model_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model",
        type=str,
        default="jonatasgrosman/wav2vec2-xls-r-1b-german",
        help="Model HuggingFace ID or path that will converted to ONNX",
    )
    args = parser.parse_args()
    model_id_or_path = args.model
    onnx_model_name = model_id_or_path.split("/")[-1] + ".onnx"
    convert_to_onnx(model_id_or_path, onnx_model_name)
    quantized_model_name = model_id_or_path.split("/")[-1] + ".quant.onnx"
    quantize_onnx_model(onnx_model_name, quantized_model_name)


if __name__ == "__main__":
    main()
```

Error:

```
Starting quantization...
Traceback (most recent call last):
  File "../testcase.py", line 57, in <module>
    main()
  File "../testcase.py", line 53, in main
    quantize_onnx_model(onnx_model_name, quantized_model_name)
  File "../testcase.py", line 34, in quantize_onnx_model
    onnx_model_path, quantized_model_path, weight_type=QuantType.QUInt8
  File "/Users/reuben/.pyenv-x86_64/versions/STT-deployment/lib/python3.7/site-packages/onnxruntime/quantization/quantize.py", line 365, in quantize_dynamic
    extra_options)
  File "/Users/reuben/.pyenv-x86_64/versions/STT-deployment/lib/python3.7/site-packages/onnxruntime/quantization/onnx_quantizer.py", line 33, in __init__
    model = onnx.shape_inference.infer_shapes(model)
  File "/Users/reuben/.pyenv-x86_64/versions/STT-deployment/lib/python3.7/site-packages/onnx/shape_inference.py", line 40, in infer_shapes
    model_str = model if isinstance(model, bytes) else model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3850555916
```

Similar issue: https://github.com/onnx/onnx/issues/3046

- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Model is quantized succesfully (works for example if you run the script with a smaller model, eg. `python testcase.py --model facebook/wav2vec2-large-960h-lv60-self`).

**Comment by reuben** [comment]
Sorry, accidentally clicked "Submit" before I finished writing up the report. For any email viewers, the first comment has been completed with more info, script to reproduce, etc.

**Comment by reuben** [comment]
I figured out a hacky fix just for my use case. Unfortunately I don't have time right now to clean it up for a proper PR but maybe it's a useful starting point: https://github.com/reuben/onnxruntime/commit/c464245822bc5e2688e2d8b3fef9aa92b8ef0e40

**Comment by yufenglee** [comment]
There is an option DisableShapeInference to disable the shape inference, which is not required for quantize_dynamic.

**Comment by mfuntowicz** [comment]
@yufenglee we are observing the same issue when statically quantizing (QDQ): 

```python
    quantizer.partial_fit(
  File "/data/Workspace/optimum/optimum/onnxruntime/quantization.py", line 206, in partial_fit
    self._calibrator = calibration_config.create_calibrator(
  File "/data/Workspace/optimum/optimum/onnxruntime/configuration.py", line 74, in create_calibrator
    return create_calibrator(**kwargs)
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnxruntime/quantization/calibrate.py", line 766, in create_calibrator
    return PercentileCalibrater(
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnxruntime/quantization/calibrate.py", line 448, in __init__
    super(PercentileCalibrater, self).__init__(model, op_types_to_calibrate, augmented_model_path, use_external_data_format,
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnxruntime/quantization/calibrate.py", line 324, in __init__
    super(HistogramCalibrater, self).__init__(model, op_types_to_calibrate, augmented_model_path, use_external_data_format)
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnxruntime/quantization/calibrate.py", line 63, in __init__
    self.augment_graph()
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnxruntime/quantization/calibrate.py", line 343, in augment_graph
    model = onnx.shape_inference.infer_shapes(model)
  File "/data/Workspace/optimum-qranium/.env/lib/python3.9/site-packages/onnx/shape_inference.py", line 40, in infer_shapes
    model_str = model if isinstance(model, bytes) else model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2235543724
```

**Comment by michaelroyzen** [comment]
@yufenglee I'm not sure this issue is fixed. While disabling shape inference works for quantization, optimization is still broken for saving models such as albert-xxl. The issue seems to be that [write_external_data_tensors](https://github.com/onnx/onnx/blob/529f7cab88eed143fc9f0126147e9732585e4c5e/onnx/__init__.py#L195) isn't actually respecting the condition when it's set to true:

> Traceback (most recent call last):
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 525, in <module>
    main()
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
    optimizer.export(
  File "/home/mroyzen/train_files/optimum/optimum/onnxruntime/optimization.py", line 149, in export
    optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format=True)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 934, in save_model_to_file
    save_model(self.model, output_path)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 202, in save_model
    s = _serialize(proto)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 71, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158499

Your help would be appreciated. [Linking to my issue](https://github.com/huggingface/optimum/issues/222) in Huggingface's Optimum library, but everything seems to be working on their end as evidenced by the stack trace.

Your help would be appreciated. Thanks
