### ISSUE TITLE
Can not build Webassembly version

### ISSUE THREAD

**Issue by ilyapavkin** [microsoft/onnxruntime#11192]
**Describe the bug**
Unable to build wasm or wasm_static_lib. 

```CMake Error at /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  external/protobuf/cmake/CMakeLists.txt:125 (find_package)
```
Error occurs after fetching code from git and successful libprotoc build.

<details>
  <summary>Part of log</summary>
  
  
  ```
2022-04-12 14:02:55,248 util.run [INFO] - Running subprocess in '/Users/ilya/Desktop/code/onnxruntime/build/MacOS/RelWithDebInfo'
  /usr/local/bin/cmake /Users/ilya/Desktop/code/onnxruntime/cmake -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_BUILD_WINML_TESTS=ON -Donnxruntime_GENERATE_TEST_REPORTS=ON -DPython_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9 -DPYTHON_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9 -Donnxruntime_ROCM_VERSION= -Donnxruntime_USE_MIMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=OFF -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_OBJC=OFF -Donnxruntime_BUILD_SHARED_LIB=OFF -Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_DNNL_GPU_RUNTIME= -Donnxruntime_DNNL_OPENCL_ROOT= -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_OPENMP=OFF -Donnxruntime_USE_NUPHAR_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_TENSORRT_HOME= -Donnxruntime_USE_TVM=OFF -Donnxruntime_TVM_CUDA_RUNTIME=OFF -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_MIGRAPHX_HOME= -Donnxruntime_CROSS_COMPILING=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=OFF -Donnxruntime_DISABLE_RTTI=OFF -Donnxruntime_DISABLE_EXCEPTIONS=OFF -Donnxruntime_MINIMAL_BUILD=OFF -Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF -Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF -Donnxruntime_REDUCED_OPS_BUILD=OFF -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_ENABLE_TRANSFORMERS_TOOL_TEST=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ACL_2002=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_ENABLE_TRAINING_OPS=OFF -Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF -Donnxruntime_ENABLE_CPU_FP16_OPS=OFF -Donnxruntime_USE_NCCL=ON -Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_ROCM=OFF -Donnxruntime_ROCM_HOME= -DOnnxruntime_GCOV_COVERAGE=OFF -Donnxruntime_USE_MPI=ON -Donnxruntime_ENABLE_MEMORY_PROFILE=OFF -Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF -Donnxruntime_BUILD_WEBASSEMBLY=ON -Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=ON -Donnxruntime_ENABLE_WEBASSEMBLY_SIMD=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF -Donnxruntime_ENABLE_EAGER_MODE=OFF -Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF -Donnxruntime_NVCC_THREADS=0 -Donnxruntime_ENABLE_CUDA_PROFILING=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_TOOLCHAIN_FILE=/Users/ilya/Desktop/code/onnxruntime/cmake/external/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -Donnxruntime_EMSCRIPTEN_SETTINGS=MALLOC=dlmalloc -DONNX_CUSTOM_PROTOC_EXECUTABLE=/Users/ilya/Desktop/code/onnxruntime/build/MacOS/host_protoc/protoc -Donnxruntime_DEV_MODE=ON -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo
Building ONNX Runtime for x86
-- Performing Test onnxruntime_HAVE_BUILTIN_ATOMICS
-- Performing Test onnxruntime_HAVE_BUILTIN_ATOMICS - Failed
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Could NOT find Threads (missing: Threads_FOUND) 
-- Found Patch: /usr/bin/patch  
Patch found: /usr/bin/patch
-- Performing Test COMPILER_SUPPORT_MF16C
-- Performing Test COMPILER_SUPPORT_MF16C - Failed
F16C instruction set is not supported.
-- Performing Test COMPILER_SUPPORT_FMA
-- Performing Test COMPILER_SUPPORT_FMA - Failed
FMA instruction set is not supported.
-- Performing Test COMPILER_SUPPORT_AVX
-- Performing Test COMPILER_SUPPORT_AVX - Failed
AVX instruction set is not supported.
One or more AVX/F16C instruction flags are not supported. 
Use gtest from submodule
CMake Warning (dev) at external/googletest/googletest/CMakeLists.txt:22 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'gtest_disable_pthreads'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python: /usr/local/opt/python@3.9/bin/python3.9 (found version "3.9.12") found components: Interpreter 
-- Could NOT find Threads (missing: Threads_FOUND) 
Doing crosscompiling
Use nsync from submodule
Use protobuf from submodule
-- 
-- 3.18.1.0
CMake Error at /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.23.0/share/cmake/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  external/protobuf/cmake/CMakeLists.txt:125 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/ilya/Desktop/code/onnxruntime/build/MacOS/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "/Users/ilya/Desktop/code/onnxruntime/build/MacOS/RelWithDebInfo/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/Users/ilya/Desktop/code/onnxruntime/tools/ci_build/build.py", line 2493, in <module>
    sys.exit(main())
  File "/Users/ilya/Desktop/code/onnxruntime/tools/ci_build/build.py", line 2393, in main
    generate_build_tree(
  File "/Users/ilya/Desktop/code/onnxruntime/tools/ci_build/build.py", line 1188, in generate_build_tree
    run_subprocess(
  File "/Users/ilya/Desktop/code/onnxruntime/tools/ci_build/build.py", line 673, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/Users/ilya/Desktop/code/onnxruntime/tools/python/util/run.py", line 42, in run
    completed_process = subprocess.run(
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '/Users/ilya/Desktop/code/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9', '-DPYTHON_EXECUTABLE=/usr/local/opt/python@3.9/bin/python3.9', '-Donnxruntime_ROCM_VERSION=', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_DNNL_GPU_RUNTIME=', '-Donnxruntime_DNNL_OPENCL_ROOT=', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_NUPHAR_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_MIGRAPHX_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_ENABLE_TRANSFORMERS_TOOL_TEST=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=ON', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_SIMD=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_EAGER_MODE=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_NVCC_THREADS=0', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-DCMAKE_OSX_ARCHITECTURES=x86_64', '-DCMAKE_TOOLCHAIN_FILE=/Users/ilya/Desktop/code/onnxruntime/cmake/external/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake', '-Donnxruntime_EMSCRIPTEN_SETTINGS=MALLOC=dlmalloc', '-DONNX_CUSTOM_PROTOC_EXECUTABLE=/Users/ilya/Desktop/code/onnxruntime/build/MacOS/host_protoc/protoc', '-Donnxruntime_DEV_MODE=ON', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo']' returned non-zero exit status 1.
  ```
  
</details>

**Urgency**
_none_

**System information**
- OS Platform and Distribution: MacOs 11.6
- ONNX Runtime installed from: Source
- ONNX Runtime version: 1.11.0
- Python version: 3.9.12
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): AppleClang 13.0.0.13000029
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
git clone https://github.com/microsoft/onnxruntime
cd onnxruntime
./build.sh --config RelWithDebInfo --build_wasm_static_lib --skip_tests --parallel

**Expected behavior**
Compilation succeeded. libonnxruntime_webassembly.a present in build dir.

**Screenshots**
_none_

**Additional context**
_none_

**Comment by fs-eire** [comment]
It looks like the EMSDK is not installed/activated.

Please goto `/Users/ilya/Desktop/code/onnxruntime/cmake/external/emsdk/`, and run the following commands:

```sh
./emsdk install 3.1.3
./emsdk activate 3.1.3
```

if `emcc --version` works, run the build commandline again.

**Comment by ilyapavkin** [comment]
For some reason, if I use EMSDK installed and activated outside of repo - build fails with error above. Even if I use 3.1.3 version.
So removing `source ~/.zprofile` (or `source <path_to_emsdk>/emsdk_env.sh`) from .zshrc and restarting terminal helps with this.

Thanks.

**Comment by vacing** [comment]
same problem, from CMakeError.log  I found the root cause:
onnxruntime inner wasm-ld required libc.so version 2.28, but there is only 2.17 in my Centos 7. I update my os then solved the problem.

CMakeError.log file: 
```bash
find ./ -name CMakeError.log
# ./Linux/Release/CMakeFiles/CMakeError.log
```

check libc.so version
```sh
ldd --version
```

**Comment by vacing** [comment]
> It looks like the EMSDK is not installed/activated.
> 
> Please goto `/Users/ilya/Desktop/code/onnxruntime/cmake/external/emsdk/`, and run the following commands:
> 
> ```shell
> ./emsdk install 3.1.3
> ./emsdk activate 3.1.3
> ```
> 
> if `emcc --version` works, run the build commandline again.

the [build guide of web platform](https://onnxruntime.ai/docs/build/web.html) seems outdated, cmake 3.24 or higher is required and onnxruntime use it's owrn nodejs and emcc toolchain inner. Also wasm-ld need libc version 2.28.
@fs-eire

**Comment by fs-eire** [comment]
added #14357 to update the version
