### ISSUE TITLE
CUDAExecutionProvider optimized model adds incompatible node resulting in Failed to find kernel for MemcpyToHost

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#11348]
**Describe the bug**

I get this error:

```text
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:NotImplemented] Failed to find kernel for MemcpyToHost(1) (node Memcpy). Kernel not found
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
```

This is a minimum test (also mentioned [here](https://github.com/pytorch/pytorch/issues/76344)).

```python
class MinTest(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        top_probs, top = x.max(1, keepdim=True)
        return top_probs, top

```

This is the exported model:

![image](https://user-images.githubusercontent.com/873905/165182186-9cd3b5f8-aea8-4ae0-80b2-42aff27674f5.png)

I can us this function to do basic cleanup and the graph would be the same:

```python
def optimize_graph(onnxfile, onnxfile_optimized=None):
    import onnxruntime as rt

    if not onnxfile_optimized:
        onnxfile_optimized = onnxfile[:-5] + "_optimized.onnx"  # ONNX optimizer is broken, using ORT to optimzie
    sess_options = rt.SessionOptions()
    sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_BASIC
    sess_options.optimized_model_filepath = onnxfile_optimized
    _ = rt.InferenceSession(onnxfile, sess_options, providers=['CPUExecutionProvider'])
    return onnxfile_optimized
```

But if I use CUDA EP for clean up:

```python
def optimize_graph(onnxfile, onnxfile_optimized=None):
    import onnxruntime as rt

    if not onnxfile_optimized:
        onnxfile_optimized = onnxfile[:-5] + "_optimized.onnx"  # ONNX optimizer is broken, using ORT to optimzie
    sess_options = rt.SessionOptions()
    sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_BASIC
    sess_options.optimized_model_filepath = onnxfile_optimized
    _ = rt.InferenceSession(onnxfile, sess_options, providers=['CUDAExecutionProvider'])
    return onnxfile_optimized
```

The graph adds this problematic node

![image](https://user-images.githubusercontent.com/873905/165183881-68eb5bd6-b5a8-4bb3-8ee9-f43deab5b0e9.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): 1.10
- ONNX Runtime version: 1.10
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Expected behavior**
Optimization should not add that extra incompatible node

**Comment by tianleiwu** [comment]
The optimized model is tied with the execution providers. You cannot use CUDA to optimize a model, then run the model in CPU. However, if you run the optimized model with same execution provider(s), there shall not be problem.

**Comment by hariharans29** [comment]
Prima facie, it is a bug since when the graph optimization level is GraphOptimizationLevel.ORT_ENABLE_BASIC, the dumped graph shouldn't contain any operators that are not part of the ONNX standard and in this case the dumped graph leaks some ORT partitioning information in the form of the MemCpy nodes. The fix is to dump the graph after the basic optimization has finished and before the paritioning and copy node insertion steps. 

But the impact of this should be low - as a work-around you can use just the CPU EP to dump the optimized graph and that won't leak ORT partitioning details (as you illustrated). The flip side is instantiating an InferenceSession using the CPU EP just for this.

**Comment by dashesy** [comment]
Any chance this bug can be addressed? I am now facing this again in exporting another model. The model is fp16 so I have to use `CUDAExecutionprovider` or it inserts lots of cast ops. But using `CUDAExecutionprovider` also inserts these `MemcpyToHost' ops that are problematic if I want to run the same model also on CPU.

**Comment by tianleiwu** [comment]
CPU does not support fp16, so you see a lot of cast ops. 

@dashesy, Saving the optimized model from ONNX Runtime will not get better performance (since same optimizations will be done when ONNXRuntime loading the original model) except reducing model load time. What's the reason that you need the optimized version?

**Comment by dashesy** [comment]
Yes the idea is to get rid of the warnings. The CPU does not support fp16, but adding those "cast" ops changes the model. 

The Python API used to be broken (crashing).

**Comment by tianleiwu** [comment]
See https://github.com/onnx/onnx/issues/3477

**Comment by dashesy** [comment]
I see, thanks. Yes that could work but requires doing this manually for all of them. There are 100s of unused initializers in a big model.

**Comment by jplu** [comment]
Any idea when this bug can be addressed? Thanks.
