### ISSUE TITLE
Build fail on Jetson Nano

### ISSUE THREAD

**Issue by egorsmkv** [microsoft/onnxruntime#11462]
**Describe the bug**

I cannot build the python wheel on Jetson Nano.

Logs:

```
...

Consolidate compiler generated dependencies of target onnxruntime_test_utils
[ 71%] Built target onnxruntime_test_utils
Consolidate compiler generated dependencies of target onnx_test_data_proto
[ 71%] Built target onnx_test_data_proto
Consolidate compiler generated dependencies of target onnx_test_runner_common
[ 72%] Built target onnx_test_runner_common
Consolidate compiler generated dependencies of target onnxruntime_test_cuda_ops_lib
[ 72%] Built target onnxruntime_test_cuda_ops_lib
Consolidate compiler generated dependencies of target gtest
[ 72%] Built target gtest
Consolidate compiler generated dependencies of target gmock
[ 73%] Built target gmock
Consolidate compiler generated dependencies of target onnxruntime_test_all
[ 73%] Linking CXX executable onnxruntime_test_all
CMakeFiles/onnxruntime_test_all.dir/home/yehor/onx/onnxruntime/onnxruntime/test/contrib_ops/bias_dropout_op_test.cc.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_test_all.dir/build.make:4206: recipe for target 'onnxruntime_test_all' failed
make[2]: *** [onnxruntime_test_all] Error 1
CMakeFiles/Makefile2:2179: recipe for target 'CMakeFiles/onnxruntime_test_all.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_test_all.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/yehor/onx/onnxruntime/tools/ci_build/build.py", line 2702, in <module>
    sys.exit(main())
  File "/home/yehor/onx/onnxruntime/tools/ci_build/build.py", line 2621, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/yehor/onx/onnxruntime/tools/ci_build/build.py", line 1267, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/yehor/onx/onnxruntime/tools/ci_build/build.py", line 698, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/yehor/onx/onnxruntime/tools/python/util/run.py", line 57, in run
    shell=shell,
  File "/home/yehor/archiconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/yehor/onx/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

**Comment by ashbhandare** [comment]
Hi, please take a look at the issue for possible resolution by using pre-built wheels: https://github.com/microsoft/onnxruntime/issues/6124
