### ISSUE TITLE
Inconsistent result of Resize compared to the reference implementation from ONNX

### ISSUE THREAD

**Issue by lazycal** [microsoft/onnxruntime#11496]
**Describe the bug**
ORT seems to implement Resize in a different way than ONNX's reference implementation and PyTorch. For instance, the following code snippet generates a model that resizes a tensor from shape [1,1,4,4] to [1,1,1,1], where PyTorch and ONNX's implementations yield the same result but ORT yields a different one:
```python
import torch
import numpy as np
from onnx.backend.test.case.node import resize
import onnxruntime as ort

out_size = [1, 1]


class Model(torch.nn.Module):
    def forward(self, x):
        return torch.nn.functional.interpolate(x, size=out_size, mode='bicubic')


model = Model()
x = torch.rand([1, 1, 4, 4]).numpy()
torch.onnx.export(model, torch.from_numpy(x), "output.onnx",
                  input_names=["input"], output_names=["output"], opset_version=13)
onnx.checker.check_model("output.onnx", full_check=True)

y_torch = model(torch.from_numpy(x)).detach().numpy()
y_onnx = resize.interpolate_nd(
    x, resize.cubic_coeffs, output_size=[1, 1, *out_size])
y_ort = ort.InferenceSession("output.onnx", provider_options=[
                             "CPUExecutionProvider"]).run(["output"], {"input": x})[0]

np.testing.assert_allclose(y_torch, y_onnx, atol=1e-5)  # passed
print('---> torch and onnx have the same output')
np.testing.assert_allclose(y_ort, y_onnx, atol=1e-5)  # failed
print('---> ort and onnx have the same output')
```
The output: 
```
---> torch and onnx have the same output
Traceback (most recent call last):
  File "test.py", line 309, in <module>
    np.testing.assert_allclose(y_ort, y_onnx, atol=1e-5)  # failed
  File "/workspace/.conda/envs/main/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/workspace/.conda/envs/main/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-05

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.53119436
Max relative difference: 0.79213237
 x: array([[[[0.139394]]]], dtype=float32)
 y: array([[[[0.670588]]]])
```
`bilinear` mode seems to have the same problem. Didn't try other modes.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.11.1
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: RTX 2080 8GB

**Model**
[output.onnx 2.zip](https://github.com/microsoft/onnxruntime/files/8674548/output.onnx.2.zip)

**Comment by lazycal** [comment]
This seems to be an error from PyTorch side. Sorry for the inconvenience. I am closing this issue and moving to PyTorch https://github.com/pytorch/pytorch/issues/79361.
