### ISSUE TITLE
Load ORT Model in React-Native Expo

### ISSUE THREAD

**Issue by fkodom** [microsoft/onnxruntime#11507]
**Describe the bug**
I'm trying to get `onnxruntime-react-native` working in a managed Expo app.  Whenever I try to create a new `InferenceSession`, I receive the error message:
```bash
Error: "Can't load a model: null is not an object (evaluating '(0,u.default)(this,p)[p].loadModel')"
...
```

Here is a minimal example on `snack.expo.dev` to reproduce the issue:
https://snack.expo.dev/@fkodom/expo-onnxruntime

When I run the example locally on my Macbook, I get a slightly different (but seemingly closely related) error:
```bash
Can't load a model: null is not an object (evaluating '(0, _classPrivateFieldLooseBase2.default)(this, _inferenceSession)[_inferenceSession].loadModel')
at node_modules/onnxruntime-react-native/lib/backend.ts:61:12 in OnnxruntimeSessionHandler#loadModel
at node_modules/onnxruntime-react-native/lib/backend.ts:49:2 in OnnxruntimeSessionHandler#loadModel
at node_modules/onnxruntime-react-native/lib/backend.ts:151:10 in OnnxruntimeBackend#createSessionHandler
at node_modules/onnxruntime-react-native/lib/backend.ts:145:2 in OnnxruntimeBackend#createSessionHandler
at node_modules/onnxruntime-common/dist/ort-common.node.js:6:6604 in c.create
```

I have confirmed that:
* `onnxruntime-react-native` is installed, and I can create `Tensor` objects.
* The model asset `mnist.ort` downloads successfully, and saves to a local URI.  
    * The model was pulled from [this example in the `microsoft/onnxruntime` docs](https://github.com/microsoft/onnxruntime/tree/master/js/react_native/e2e)

**Urgency**
None

**System information**
- OS -- Linux & Mac
- Expo -- `44.0.0`
- `onnxruntime-react-native` -- `1.11.0`
- Platforms:
    - iOS (device & simulator)
    - Android (simulator)

**To Reproduce**
Please see the example linked above (copied again here):
https://snack.expo.dev/@fkodom/expo-onnxruntime

Link to the ORT model that I'm using to initialize the `InferenceSession`:
https://github.com/microsoft/onnxruntime/blob/master/js/react_native/e2e/src/mnist.ort

Minimal reproducing code from the linked example:
```js
import React, { useState, useEffect } from 'react';

import { Asset } from 'expo-asset';
import { InferenceSession, Tensor } from "onnxruntime-react-native";

export default function App() {
  const [onnxSession, setOnnxSession] = useState(null);

  const initInferenceSession = async () => {
      const asset = Asset.fromURI("https://github.com/microsoft/onnxruntime/blob/master/js/react_native/e2e/src/mnist.ort");
      if (!asset.localUri) {
        console.log("Downloading asset.")
        await asset.downloadAsync();
        console.log("Local URI: " + asset.localUri);
      }

      try {
        const session = await InferenceSession.create(asset.localUri, { executionProviders: ['cpu'] });
        console.log("Session (initInferenceSession): " + session);
        setOnnxSession(session);
      } catch (e) {
        console.log(e);
      }
  }

  useEffect(() => { 
    initInferenceSession(); 
  }, []);

  return null;
}
```

**Expected behavior**
Able to create a new `InferenceSession` from an ORT model.

**Comment by fs-eire** [comment]
I have a repo demonstrating how to use ORTRN to create a simple hello-world app for react native. You can refer to it: https://github.com/fs-eire/ort-rn-hello-world

I think the problem is that onnxruntime-react-native does not work with expo managed workflow because it contains native module. I am not expert of expo/react-native so I am not sure if there is a way to solve this problem. So far it works with the bare workflow (using `expo prebuild` and update the android/ios project files).

**Comment by fs-eire** [comment]
I tried it with latest dev version (include in changes in the PR above) but seems snack.expo.dev does not consume it as the behavior of either `expo prebuild` or `eas build`. I think it is because native modules are not supported by snack.expo.dev
