### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by caleb-depotanalytics** [microsoft/onnxruntime#11505]
Is ONNX runtime compatible with ZCU102 and other non-alveo/EdgeAI Vitis-AI compatible platforms?
---
#### Document Details
* Title: Vitis AI
* Page: [https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html](https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html)
* Page Source: Vitis-AI-ExecutionProvider.md

**Comment by natke** [comment]
@edelaye Are you able to answer this question for us?

**Comment by caleb-depotanalytics** [comment]
@edelaye and @natke  - I was able to build onnxruntime on zcu102 using this script https://github.com/centennialsoftwaresolutions/vitis-ai-tutorial-helper-files/blob/main/install_onnxruntime_zcu102.sh

But as soon as I ran the vitisai-execution provider with this script (use any argument to make it run with vitisai instead of CPU) https://github.com/centennialsoftwaresolutions/vitis-ai-tutorial-helper-files/blob/main/compile_onnx_model.py. I got a Index out of bounds error.

**Comment by elliott-xilinx** [comment]
We have people using ONNXRuntime on our ZCU102/104 and also the VCK190 Versal boards.  I've asked one of my team members to follow up.  Are you getting a stack trace from the error that you can copy/paste?

**Comment by caleb-depotanalytics** [comment]
@elliott-xilinx - yeah here it is: 

_model.py ../yolov4_-1_3_384_384_dynamic.onnx fpgaer-files# python3 compile_onnx_
2022-06-08 22:43:37.854854490 [E:onnxruntime:, inference_session.cc:1458 operator()] Exception during initialization: IndexError: list index out of range

At:
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__
  compile_onnx_model.py(21): execute_with_fpga
  compile_onnx_model.py(28): <module>

Traceback (most recent call last):
  File "compile_onnx_model.py", line 28, in <module>
    execute_with_fpga(sys.argv[1])
  File "compile_onnx_model.py", line 21, in execute_with_fpga
    session = onnxruntime.InferenceSession(model_name, None, ["VitisAIExecutionProvider"], [vitis_ai_provider_options])
  File "/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 369, in _create_inference_sessio
n
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initializ
ation: IndexError: list index out of range

At:
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onn
x_2_xlayer
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__
  compile_onnx_model.py(21): execute_with_fpga
  compile_onnx_model.py(28): <module>


And that is coming from this inside the script:
def execute_with_fpga(model_name):
    target='DPUCADX8G'
    vitis_ai_provider_options = {'target': target, 'export_runtime_module': 'vitis_ai_dpu.rtmod'}
    session = onnxruntime.InferenceSession(model_name, None, ["VitisAIExecutionProvider"], [vitis_ai_provider_options])

**Comment by elliott-xilinx** [comment]
First thing I see is the target you're passing in is an Alveo DPU, (DPUCADX8G).  The Zync DPUs should typically be DPUCZDX8G.  Change that target on all your scripts.  Since we compile first on x86, you should make sure the first run on x86 also has DPUCZDX8G.

**Comment by caleb-depotanalytics** [comment]
Yeah, I had messed around with that variable quite a bit since I was getting the error, but it's the same log with DPUCZDX8G

root@xilinx-zcu102-2021_2:~/vitis-ai-tutorial-helper-files# python3 compile_onnx_model.py ../yolov4_-1_3_384_384_dynamic.onnx fpga
2022-06-08 23:03:21.272684680 [E:onnxruntime:, inference_session.cc:1458 operator()] Exception during initialization: IndexError: list index out of range

At:
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__
  compile_onnx_model.py(21): execute_with_fpga
  compile_onnx_model.py(28): <module>

Traceback (most recent call last):
  File "compile_onnx_model.py", line 28, in <module>
    execute_with_fpga(sys.argv[1])
  File "compile_onnx_model.py", line 21, in execute_with_fpga
    session = onnxruntime.InferenceSession(model_name, None, ["VitisAIExecutionProvider"], [vitis_ai_provider_options])
  File "/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 369, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: IndexError: list index out of range

At:
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/ops/onnx_l2_convolution.py(664): pad
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/onnx_2_xlayer_registry.py(116): __base_onnx_2_xlayer
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(165): _from_onnx
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/frontend/onnx/base.py(69): from_onnx_bytes_opaque_func
  /usr/lib/python3.8/site-packages/pyxir-0.2.0-py3.8-linux-aarch64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(369): _create_inference_session
  /usr/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py(324): __init__
  compile_onnx_model.py(21): execute_with_fpga
  compile_onnx_model.py(28): <module>

**Comment by musheikh2** [comment]
Getting exactly the same issue with every onnx model that I use except the Resnet 18 from the example here:

https://github.com/Xilinx/Vitis-AI/tree/master/third_party/onnxruntime

Cannot figure out what is special about Resnet 18 that the session runs fine. I haven't been able to find another model that runs fine.

Have you been able to figure out a solution @caleb-depotanalytics ?
