### ISSUE TITLE
CUDA_PATH is present but not recognized.

### ISSUE THREAD

**Issue by Sanuki-073** [microsoft/onnxruntime#11562]
**Describe the bug**

I installed this library using by
pip install onnxruntime-gpu

And I ran the program below:

```
import onnxruntime
print(onnxruntime.get_device())
model_path = "model/yolox_nano.onnx"
session = onnxruntime.InferenceSession(model_path,providers=['CUDAExecutionProvider' ,'CPUExecutionProvider'])
print(session.get_providers())
```

Then it outputs errors:
GPU
2022-05-18 23:41:07.9831225 [E:onnxruntime:Default, provider_bridge_ort.cc:1022 onnxruntime::ProviderLibrary::Get] LoadLibrary failed with error 126 "" when trying to load "C:\Users\s1260\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
Traceback (most recent call last):
  File "C:\Users\s1260\Desktop\workspace\yolox-bytetrack-mcmot-sample-master\runtime_test.py", line 4, in <module>
    session = onnxruntime.InferenceSession(model_path,providers=['CUDAExecutionProvider' ,'CPUExecutionProvider'])
  File "C:\Users\s1260\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\s1260\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:548 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

I have already installed CUDA and CUDNN and exported path following:

- %CUDA_PATH%\bin
- %CUDA_PATH%\libnvvp
- %CUDA_PATH%\lib\x64
- %CUDA_PATH%\include
- CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1

Could you please tell me what needs to be fixed?

What I tried: 
・install cuda11.4/cudnn (Nothing changed.)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version:1.11.1
- Python version:3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1/8.0.2.39
- GPU model and memory: RTX 3060

**Comment by Sanuki-073** [comment]
解決しました。

I installed ONNX Runtime version:1.11.1
But I installed ONNX Runtime version:1.8 following:
pip uninstall onnxruntime-gpu
pip install onnxruntime-gpu==1.8
