### ISSUE TITLE
onnxruntime with use_acl build

### ISSUE THREAD

**Issue by wangyunxiaa** [microsoft/onnxruntime#11603]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by wangyunxiaa** [comment]
with     `parser.add_argument("--disable_abseil", action='store_true', help="Do no use abseil and default to STL")`
the line 148 and line 194 error are disapper, but the line 50 still exist

**Comment by RyanUnderhill** [comment]
@yuslepukhin This should still be possible right? Hopefully just something simple missed with these build options to not build with abseil.

**Comment by yuslepukhin** [comment]
We think it was already fixed in this PR: https://github.com/microsoft/onnxruntime/pull/11448

**Comment by jywu-msft** [comment]
> We think it was already fixed in this PR: #11448

we need to merge that fix into master branch.

**Comment by wangyunxiaa** [comment]
thanks very much,
I chenged `std::vector<int64_t> output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads); `
to 
```
auto pads1 = pool_attrs.pads;
std::vector<int64_t> output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads1);
```
everything is ok.

**Comment by wangyunxiaa** [comment]
however, when i build android library whit the same code, I got another error as followings:
```
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:53:24: error: no viable conversion from 'onnxruntime::TensorShapeVector' (aka 'InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::vector<int64_t>' (aka 'vector<long>')
  std::vector<int64_t> output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads);
                       ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:557:5: note: candidate constructor not viable: no known conversion from 'onnxruntime::TensorShapeVector' (aka 'InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> > &' for 1st argument
    vector(const vector& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:564:5: note: candidate constructor not viable: no known conversion from 'onnxruntime::TensorShapeVector' (aka 'InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'initializer_list<std::__ndk1::vector<long, std::__ndk1::allocator<long> >::value_type>' (aka 'initializer_list<long>') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:570:5: note: candidate constructor not viable: no known conversion from 'onnxruntime::TensorShapeVector' (aka 'InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> > &&' for 1st argument
    vector(vector&& __x)
    ^
8 warnings generated.
8 warnings generated.
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:153:24: error: no matching constructor for initialization of 'std::vector<int64_t>' (aka 'vector<long>')
  std::vector<int64_t> dilations(PoolBase::pool_attrs_.dilations);
                       ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.h:36:12: note: in instantiation of member function 'onnxruntime::acl::Pool<float, onnxruntime::MaxPool<1> >::Compute' requested here
  explicit Pool(const OpKernelInfo& info) : onnxruntime::Pool<T, PoolType>(info) {
           ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:3003:32: note: in instantiation of member function 'onnxruntime::acl::Pool<float, onnxruntime::MaxPool<1> >::Pool' requested here
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:242:1: note: in instantiation of function template specialization 'std::__ndk1::make_unique<onnxruntime::acl::Pool<float, onnxruntime::MaxPool<1> >, const onnxruntime::OpKernelInfo &>' requested here
POOLING_KERNEL(MaxPool, float, MaxPool<1>, 1, 7)
^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:232:3: note: expanded from macro 'POOLING_KERNEL'
  ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX(                                              \
  ^
/models/onnxruntime/include/onnxruntime/core/framework/op_kernel.h:296:138: note: expanded from macro 'ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX'
        static_cast<KernelCreatePtrFn>([](FuncManager&, const OpKernelInfo& info, std::unique_ptr<OpKernel>& out) -> Status { out = std::make_unique<__VA_ARGS__>(info); return Status::OK(); })); \
                                                                                                                                         ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:501:40: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >::allocator_type' (aka 'const std::__ndk1::allocator<long>') for 1st argument
    _LIBCPP_INLINE_VISIBILITY explicit vector(const allocator_type& __a)
                                       ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:513:14: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >::size_type' (aka 'unsigned long') for 1st argument
    explicit vector(size_type __n);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:557:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(const vector& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:564:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'initializer_list<std::__ndk1::vector<long, std::__ndk1::allocator<long> >::value_type>' (aka 'initializer_list<long>') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:570:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(vector&& __x)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:520:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_InputIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:528:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:535:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_ForwardIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:542:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:495:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:515:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit vector(size_type __n, const allocator_type& __a);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:517:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:558:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(const vector& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:567:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(initializer_list<value_type> __il, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:578:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(vector&& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:518:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x, const allocator_type& __a);
    ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:153:24: error: no matching constructor for initialization of 'std::vector<int64_t>' (aka 'vector<long>')
  std::vector<int64_t> dilations(PoolBase::pool_attrs_.dilations);
                       ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.h:36:12: note: in instantiation of member function 'onnxruntime::acl::Pool<float, onnxruntime::AveragePool>::Compute' requested here
  explicit Pool(const OpKernelInfo& info) : onnxruntime::Pool<T, PoolType>(info) {
           ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:3003:32: note: in instantiation of member function 'onnxruntime::acl::Pool<float, onnxruntime::AveragePool>::Pool' requested here
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:243:1: note: in instantiation of function template specialization 'std::__ndk1::make_unique<onnxruntime::acl::Pool<float, onnxruntime::AveragePool>, const onnxruntime::OpKernelInfo &>' requested here
POOLING_KERNEL(AveragePool, float, AveragePool, 7, 9)
^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:232:3: note: expanded from macro 'POOLING_KERNEL'
  ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX(                                              \
  ^
/models/onnxruntime/include/onnxruntime/core/framework/op_kernel.h:296:138: note: expanded from macro 'ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX'
        static_cast<KernelCreatePtrFn>([](FuncManager&, const OpKernelInfo& info, std::unique_ptr<OpKernel>& out) -> Status { out = std::make_unique<__VA_ARGS__>(info); return Status::OK(); })); \
                                                                                                                                         ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:501:40: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >::allocator_type' (aka 'const std::__ndk1::allocator<long>') for 1st argument
    _LIBCPP_INLINE_VISIBILITY explicit vector(const allocator_type& __a)
                                       ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:513:14: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >::size_type' (aka 'unsigned long') for 1st argument
    explicit vector(size_type __n);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:557:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(const vector& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:564:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'initializer_list<std::__ndk1::vector<long, std::__ndk1::allocator<long> >::value_type>' (aka 'initializer_list<long>') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:570:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(vector&& __x)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:520:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_InputIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:528:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:535:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_ForwardIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:542:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:495:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:515:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit vector(size_type __n, const allocator_type& __a);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:517:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:558:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(const vector& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:567:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(initializer_list<value_type> __il, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:578:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(vector&& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:518:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x, const allocator_type& __a);
    ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:184:21: error: no matching function for call to 'PoolOperation'
  ACLNEPool pPool = PoolOperation<T>(context, pool_type, PoolBase::pool_attrs_, it, insert);
                    ^~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:31:11: note: candidate template ignored: substitution failure [with T = float]
ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
          ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:199:24: error: no matching constructor for initialization of 'std::vector<int64_t>' (aka 'vector<long>')
  std::vector<int64_t> dilations(PoolBase::pool_attrs_.dilations);
                       ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.h:55:12: note: in instantiation of member function 'onnxruntime::acl::MaxPoolV8<float>::Compute' requested here
  explicit MaxPoolV8(const OpKernelInfo& info) : onnxruntime::MaxPoolV8(info) {
           ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:3003:32: note: in instantiation of member function 'onnxruntime::acl::MaxPoolV8<float>::MaxPoolV8' requested here
    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
                               ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:248:1: note: in instantiation of function template specialization 'std::__ndk1::make_unique<onnxruntime::acl::MaxPoolV8<float>, const onnxruntime::OpKernelInfo &>' requested here
ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX(                                            \
^
/models/onnxruntime/include/onnxruntime/core/framework/op_kernel.h:296:138: note: expanded from macro 'ONNX_OPERATOR_VERSIONED_TYPED_KERNEL_EX'
        static_cast<KernelCreatePtrFn>([](FuncManager&, const OpKernelInfo& info, std::unique_ptr<OpKernel>& out) -> Status { out = std::make_unique<__VA_ARGS__>(info); return Status::OK(); })); \
                                                                                                                                         ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:501:40: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >::allocator_type' (aka 'const std::__ndk1::allocator<long>') for 1st argument
    _LIBCPP_INLINE_VISIBILITY explicit vector(const allocator_type& __a)
                                       ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:513:14: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >::size_type' (aka 'unsigned long') for 1st argument
    explicit vector(size_type __n);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:557:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'const std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(const vector& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:564:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'initializer_list<std::__ndk1::vector<long, std::__ndk1::allocator<long> >::value_type>' (aka 'initializer_list<long>') for 1st argument
    vector(initializer_list<value_type> __il);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:570:5: note: candidate constructor not viable: no known conversion from 'const onnxruntime::TensorShapeVector' (aka 'const InlinedVector<long, kTensorShapeSmallBufferElementsSize>') to 'std::__ndk1::vector<long, std::__ndk1::allocator<long> >' for 1st argument
    vector(vector&& __x)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:520:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_InputIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:528:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:535:9: note: candidate constructor template not viable: requires 2 arguments, but 1 was provided
        vector(_ForwardIterator __first,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:542:9: note: candidate constructor template not viable: requires at least 3 arguments, but 1 was provided
        vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a,
        ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:495:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    vector() _NOEXCEPT_(is_nothrow_default_constructible<allocator_type>::value)
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:515:14: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    explicit vector(size_type __n, const allocator_type& __a);
             ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:517:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:558:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(const vector& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:567:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(initializer_list<value_type> __il, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:578:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    vector(vector&& __x, const allocator_type& __a);
    ^
/models/software/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/vector:518:5: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
    vector(size_type __n, const value_type& __x, const allocator_type& __a);
    ^
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:220:21: error: no matching function for call to 'PoolOperation'
  ACLNEPool pPool = PoolOperation<T>(context, arm_compute::PoolingType::MAX, PoolBase::pool_attrs_, it, insert);
                    ^~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:31:11: note: candidate template ignored: substitution failure [with T = float]
ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
          ^
10 warnings and 6 errors generated.
CMakeFiles/onnxruntime_providers_acl.dir/build.make:187: recipe for target 'CMakeFiles/onnxruntime_providers_acl.dir/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_acl.dir/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc.o] Error 1
CMakeFiles/Makefile2:1776: recipe for target 'CMakeFiles/onnxruntime_providers_acl.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_acl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
8 warnings generated.
[ 63%] Linking CXX static library libonnxruntime_framework.a
8 warnings generated.
8 warnings generated.
8 warnings generated.
[ 63%] Linking CXX static library libonnxruntime_test_utils.a
[ 64%] Built target onnxruntime_test_utils
8 warnings generated.
[ 64%] Linking CXX static library libonnxruntime_providers.a
8 warnings generated.
8 warnings generated.
[ 64%] Linking CXX static library libonnxruntime_graph.a
[ 64%] Built target onnxruntime_graph
[ 71%] Built target onnxruntime_framework
8 warnings generated.
[ 72%] Linking CXX static library libonnxruntime_session.a
[ 74%] Built target onnxruntime_session
[ 94%] Built target onnxruntime_providers
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/models/onnxruntime/tools/ci_build/build.py", line 2703, in <module>
    sys.exit(main())
  File "/models/onnxruntime/tools/ci_build/build.py", line 2622, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/models/onnxruntime/tools/ci_build/build.py", line 1268, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/models/onnxruntime/tools/ci_build/build.py", line 699, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/models/onnxruntime/tools/python/util/run.py", line 57, in run
    shell=shell,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/models/onnxruntime/build/Android/MinSizeRel', '--config', 'MinSizeRel', '--', '-j40']' returned non-zero exit status 2.
```
by update the code to master ant pull the newest code, I cannot build it successfully either.
the git log
`commit 453c57f92f5294417f69d81a240484b7d59938f2 (HEAD -> master, origin/master, origin/HEAD)
Author: Changming Sun <chasun@microsoft.com>
Date:   Wed Jun 1 14:46:13 2022 -0700

    Revert "Directly use memory mapped data for external data initializers  (#11127)" (#11650)
    
    This reverts commit 541eff8d893020ac9ba9a60b0833649ac829ad3a, because it broke CUDA EP.  See: https://github.com/microsoft/onnxruntime/issues/11511 for more details.

`

**Comment by yuslepukhin** [comment]
There is a PR in progress to address the build issue: https://github.com/microsoft/onnxruntime/pull/11448
