### ISSUE TITLE
Error: (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size

### ISSUE THREAD

**Issue by seungtaek94** [microsoft/onnxruntime#11635]
**Describe the bug**
Hi,
I'm trying to inference below simpleNMS module from superpoint.

Its successfully convert to onnx without any warning message.

But, failed to inference using onnxruntime.
```
PS C:\Users\admin\Desktop\myModelZoo> & C:/Python39/python.exe c:/Users/admin/Desktop/myModelZoo/test.py
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\myModelZoo\test.py", line 35, in <module>
    ort_session = onnxruntime.InferenceSession("./test_nms.onnx", providers=['CPUExecutionProvider'])
  File "C:\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 370, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./test_nms.onnx failed:Node (MaxPool_1) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows10
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.11.1
- Python version: 3.9.4
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
``` python
import torch
import torch.nn as nn
import onnxruntime


class SimpleNMS(nn.Module):
    def __init__(self, nms_radius) -> None:
        super(SimpleNMS, self).__init__()

        self.pool = torch.nn.MaxPool2d(nms_radius*2+1, stride=1, padding=nms_radius)
    
    def forward(self, scores):
        zeros = torch.zeros_like(scores)
        max_mask = scores == self.pool(scores)

        for _ in range(2):
            supp_mask = self.pool(max_mask.float()) > 0
            supp_scores = torch.where(supp_mask, zeros, scores)
            new_max_mask = supp_scores == self.pool(supp_scores)
            max_mask = max_mask | (new_max_mask & (~supp_mask))
        
        return torch.where(max_mask, scores, zeros)


if __name__=="__main__":
    dummy = torch.rand(1, 256, 256)

    nms = SimpleNMS(4)    

    nms.eval()    
    torch.onnx.export(nms, dummy, "./test_nms.onnx", export_params=True, opset_version=14, input_names=['input'], output_names=['output'])

    torch_out = nms(dummy)

    ort_session = onnxruntime.InferenceSession("./test_nms.onnx", providers=['CPUExecutionProvider'])

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(dummy)}
    ort_outs = ort_session.run(None, ort_inputs)

    print('Torch Out: ', to_numpy(torch_out).shape)
    print('  Ort Out: ', ort_outs[0].shape)
```

**Comment by seungtaek94** [comment]
I've solved the problem, but I'm not sure that the right way to do it.

When use maxpool2d in ORT, input shape should be 4D("B, N, H, W") rather than 3D like above.
