### ISSUE TITLE
Installing ORTModule torch extension reports TypeError

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#11663]
**Describe the bug**

```
$ python -m onnxruntime.training.ortmodule.torch_cpp_extensions.install
```

reports `TypeError: Descriptors cannot not be created directly.`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: onnxruntime-training 1.11.1
- Python version: 3.8

**To Reproduce**

```
$ pip install onnxruntime-training==1.11.1
$ pip install torch==1.11.0
$ python -m onnxruntime.training.ortmodule.torch_cpp_extensions.install

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/__init__.py", line 32, in <module>
    from onnxruntime.capi import onnxruntime_validation
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_validation.py", line 138, in <module>
    has_ortmodule, package_name, version, cuda_version = validate_build_package_info()
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_validation.py", line 133, in validate_build_package_info
    raise import_ortmodule_exception
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_validation.py", line 66, in validate_build_package_info
    from onnxruntime.training.ortmodule import ORTModule # noqa
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/training/__init__.py", line 11, in <module>
    from .orttrainer import ORTTrainer, TrainStepInfo
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnxruntime/training/orttrainer.py", line 4, in <module>
    import onnx
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/onnx/onnx_ml_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/ashari/venv/may27/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by davidmezzetti** [comment]
A workaround for this is:

```
pip install protobuf==3.20.1
```

**Comment by thiagocrepaldi** [comment]
https://github.com/microsoft/onnxruntime/pull/11687
