### ISSUE TITLE
RuntimeError: Unable to handle object of type <class 'float'>

### ISSUE THREAD

**Issue by oohlala1204** [microsoft/onnxruntime#1166]
I am trying to feed data and run the onnx model,  and the code is as follows:
```
sess = rt.InferenceSession(onnx_path)

input_name = sess.get_inputs()[0].name
print("input name", input_name)
input_shape = sess.get_inputs()[0].shape
print("input shape", input_shape)
input_type = sess.get_inputs()[0].type
print("input type", input_type)

input_name2 = sess.get_inputs()[1].name
print("input name", input_name2)
input_shape2 = sess.get_inputs()[1].shape
print("input shape", input_shape2)
input_type2 = sess.get_inputs()[1].type
print("input type", input_type2)


output_name = sess.get_outputs()[0].name
print("output name", output_name)
output_shape = sess.get_outputs()[0].shape
print("output shape", output_shape)
output_type = sess.get_outputs()[0].type
print("output type", output_type)

# Generate batches for one epoch
batches = data_helpers.batch_iter(list(x_test), FLAGS.batch_size, 1, shuffle=False)

all_predictions = []
for x_test_batch in batches:
    print(type(x_test_batch))
    batch_predictions = sess.run([output_name], {input_name: x_test_batch, input_name2: 1.0})
    all_predictions = np.concatenate([all_predictions, batch_predictions])
```
I print the info of the inputs and outputs, as follow
```
input name: input_x:0
input shape: [None, 150]
input type: tensor(int32)
input name2: dropout_keep_prob:0
input shape2: []
input type2: tensor(float)
output name: output/predictions:0
output shape: [None]
output type: tensor(int64)
```
An error occurs as follow:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.2\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.2\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.2\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/TextCNN_Binary_Chinese/CNN_ChineseTextBinaryClassify/eval_onnx.py", line 103, in <module>
    batch_predictions = sess.run([output_name], {input_name: x_test_batch, input_name2: 1.0})
  File "C:\Users\t-toz\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\onnxruntime\capi\session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Unable to handle object of type <class 'float'>
```
As the above code shows, I have two inputs, one is "input_x", and the other is "dropout_keep_prob", whose type is float.

Any help would be greatly appreciated.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:0.4.0
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by skottmckay** [comment]
The type is 'tensor(float)' not 'float'. 

Based on the example code on https://microsoft.github.io/onnxruntime/ I believe you need to pass in the float value in a numpy array for it to be converted to a tensor. 

e.g. 
batch_predictions = sess.run([output_name], {input_name: x_test_batch, input_name2: numpy.array((1.0)).astype(numpy.float32)})

**Comment by oohlala1204** [comment]
Thank you so much. My problem is solved!

**Comment by 1138886114** [comment]
Thank you. Also solved my problem!

**Comment by 1138886114** [comment]
> 类型是“张量（浮动）”而不是“浮动”。
> 
> 基于https://microsoft.github.io/onnxruntime/上的示例代码，我相信您需要在 numpy 数组中传递浮点值才能将其转换为张量。
> 
> 例如 batch_predictions = sess.run([output_name], {input_name: x_test_batch, input_name2: numpy.array((1.0)).astype(numpy.float32)})

Thank you. Also solved my problem!
