### ISSUE TITLE
"(FusedConv) kernel is not supported" : Can't run FP16 onnx simple model

### ISSUE THREAD

**Issue by hyperfraise** [microsoft/onnxruntime#11768]
**Describe the bug**
Hi. My bug ressembles much [this one](https://github.com/microsoft/onnxruntime/issues/6320) but with FP16 type, but I find it odd since I do believe FP16 is supposed to be already compatible with onnxruntime, isn't it ? This bug happens when I try to run the model in onnxruntime. 

**To Reproduce**
```
import torch
import torchvision

export_model = torchvision.models.resnet101().cuda().eval().half()
inp = torch.from_numpy(np.zeros((8, 3, 224, 224))).cuda().half()
with torch.no_grad():
    torch.onnx.export(
        export_model,
        inp,
        "model.onnx",
        input_names=["input"],
        output_names=["output"],
        export_params=True,
    )
import onnxruntime as ort
import numpy as np
ort_sess = ort.InferenceSession('model.onnx', providers=['CUDAExecutionProvider'])
outputs = ort_sess.run(None, {'input': inp.numpy()})
print(f'Predicted:', outputs)

```

This results in the following error :
```
2022-06-08 12:21:10.005108537 [E:onnxruntime:, inference_session.cc:1587 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for FusedConv(1) (node Conv_8). Op with name (Conv_8) and type (FusedConv) kernel is not supported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (Conv_8) and type (FusedConv) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
)

CRITICAL:main_logger:
Traceback (most recent call last):
  File "pytorch/convert_model_to_torchscript.py", line 142, in <module>
    ort_sess = ort.InferenceSession('model.onnx', providers=['CUDAExecutionProvider'])
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
 Uncaught exception: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for FusedConv(1) (node Conv_8). Op with name (Conv_8) and type (FusedConv) kernel is not supported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (Conv_8) and type (FusedConv) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
)

```

Those are regular 2d convolutions though, I'm very surprised. Isn't onnxruntime compatible with fp16 inference ?

I have already tried converting the model to half after saving it with [this script](https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/float16.py), but the same error appears.

**Comment by hyperfraise** [comment]
Here is the Triton config file : 
```
name: "model"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP16
    dims: [ 8, 3, 224, 224 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP16
    dims: [ 8, 1 ]
  }
]
parameters { key: "cudnn_conv_algo_search" value: { string_value: "0" } }
parameters { key: "gpu_mem_limit" value: { string_value: "4294967200" } }

```

**Comment by hyperfraise** [comment]
So you're actually saying that onnxruntime doesn't support fp16 inference of simple old resnet ?

**Comment by jamt9000** [comment]
This is also happening for NVIDIA Jasper https://catalog.ngc.nvidia.com/orgs/nvidia/models/jasper_pyt_onnx_fp16_amp

**Comment by Magnus1cheng** [comment]
I think his might be a bug introduced in onnxruntime v1.11.0.
I used onnxrutnime v1.10 and v1.11 on same scripts. v1.11 produced same error like @[hyperfraise](https://github.com/hyperfraise) has, but v1.10 runs without any error. Hope someone can fix this in later version.

**Comment by hariharans29** [comment]
https://github.com/microsoft/onnxruntime/issues/12045#issuecomment-1171727997
