### ISSUE TITLE
LoadOrtModel ORT model verification failed

### ISSUE THREAD

**Issue by BioWar** [microsoft/onnxruntime#11781]
**Describe the bug**
I am creating **Java Android** application with the **model.ort** which should be loaded successfully in onnxruntime session as **bytearray[]**. But during the load process, the **env.createSession(model, opts)** fails with the next error code:

```
W/System.err: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: inference_session.cc:1093 LoadOrtModel ORT model verification failed.
W/System.err:     at ai.onnxruntime.OrtSession.createSession(Native Method)
        at ai.onnxruntime.OrtSession.<init>(OrtSession.java:87)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:261)
W/System.err:     at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:235)
        at com.example.onnxruntimeaartest.MainActivity.loadOrtModel(MainActivity.java:56)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:441)
W/System.err:     at android.view.View.performClick(View.java:7333)
        at android.widget.TextView.performClick(TextView.java:14160)
W/System.err:     at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
        at android.view.View.performClickInternal(View.java:7299)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27774)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Model was created from **TensorFlow savedModel format**, and **converted to onnx** with the next command:
`python -m tf2onnx.convert --saved-model saved_model_dir/ --output june8_saved_model_opset13.onnx --inputs image:0[1,1024,64,1] --opset=13`

The model.onnx was tested in Linux **C++ ONNXRuntime application and was working successfully** without any errors.

After that the **model.onnx was converted to mode.ort** format with the next command, using **onnxruntime v1.11.1**:
`python -m onnxruntime.tools.convert_onnx_models_to_ort june8_saved_model.onnx --optimization_style=Fixed`

Also, I tried to use conversion from **onnxruntime v1.10.0**:
` python -m onnxruntime.tools.convert_onnx_models_to_ort june8_saved_model_opset13.onnx --optimization_level basic --enable_type_reduction --save_optimized_onnx_model`

**AAR package for android** was created with the next command:
`./build.sh --android --android_sdk_path /home/pvorotyntse/Android/Sdk/ --android_ndk_path /home/pvorotyntse/Android/Sdk/ndk/24.0.8215888/ --android_abi arm64-v8a --android_api 27 --include_ops_by_config /home/pvorotyntse/tf_onnx/june8_saved_model_opset13.basic.required_operators_and_types.config --minimal_build extended --build_shared_lib --config Release --build_java --parallel`

And AAR package without **--include_ops_by_config** also was created and tested. 

After that the onnxruntime-release.aar package from _build/Android/Release/java/build/android/outputs/aar_ was copied to libs/onnxruntime.aar in Android project directory and installed with command:
`implementation files('src/main/libs/onnxruntime.aar')`

The next code was used to **load the model**:
```
int modelURI = R.raw.june8_saved_model_ort;

public void loadOrtModel(View view){
   OrtEnvironment env = OrtEnvironment.getEnvironment();
   try (OrtSession.SessionOptions opts = new SessionOptions()) {
       opts.addConfigEntry("session.load_model_format", "ORT");
       opts.addConfigEntry("session.use_ort_model_bytes_directly", "1");
       Log.i("Dev", "Opts created");

       InputStream inputStream = this.getResources().openRawResource(modelURI);
       byte[] modelOrt = new byte[inputStream.available()];
       int modelOrtAvailable = inputStream.available();

       int sizeModel = modelOrt.length;
       Log.i("Dev", "Model loaded to size "+sizeModel+", available "+modelOrtAvailable+", modelPathStr = "+modelPathStr);

       OrtSession session = env.createSession(modelOrt, opts);
       Log.i("Dev", "Inputs: ");
       for (NodeInfo i : session.getInputInfo().values()){
           Log.i("Dev", "====> "+i.toString());
       }
   } catch (OrtException | IOException e) {
       e.printStackTrace();
   }
}
```

**Urgency**
Medium Urgency. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.1 
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v1.11.1
- Python version: 3.8
- Visual Studio version (if applicable): NO VS
- GCC/Compiler version (if compiling from source): v9.4.0
- CUDA/cuDNN version: NO CUDA
- GPU model and memory: NO GPU

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Model.ort is loaded successfully in Java Android app with the onnxruntime.aar package created from source. 

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by BioWar** [comment]
**Issue solved.** The model was converted correctly, and the package was created correctly, but the error was in the model loading step to byteArray. 

Instead of:
```
       InputStream inputStream = this.getResources().openRawResource(modelURI);
       byte[] modelOrt = new byte[inputStream.available()];
```

It should be:
```
       InputStream inputStream = this.getResources().openRawResource(modelURI);
       byte[] modelOrt = new byte[inputStream.available()];
       BufferedInputStream buf = new BufferedInputStream((inputStream));
       buf.read(modelOrt, 0, modelOrt.length);
       buf.close
```
