### ISSUE TITLE
Target "Python::NumPy" not found during build from source on Windows10

### ISSUE THREAD

**Issue by vvchernov** [microsoft/onnxruntime#11796]
It is partly repeated [the issue](https://github.com/microsoft/onnxruntime/issues/9923), but the previous one was closed without solution. The difference is that I built default ONNX Runtime without any execution providers and other specifics, but caught the similar error during linking stage.

**Describe the bug**
Python::Numpy not found when building onnxruntime from source on Windows

**Urgency**
Looks like it is local problem related to environment, but attention of community to previos issue shows that it meets periodically and should be fixed

**System information**
- OS system: Windows 10 Pro 64-bit.
- ONNX Runtime installed from source:
- ONNX Runtime version (master) branch: 40d2c98e4d64d7931fcbb682c81dc53988c48dcc
- Python version: 3.10.5
- Git version 2.36.1.windows.1
- Cmake version 3.23.2
- Visual Studio 17 2022

**To Reproduce**
building with the following command line from source folder:
`build.bat --config Release --build_wheel --parallel --cmake_generator "Visual Studio 17 2022"`

**Expected behavior**
Build should pass.

**Additional context**
The error logs of the failed build:
```
Use flatbuffers from submodule
-- Configuring done
CMake Error at CMakeLists.txt:1347 (target_compile_definitions):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_COMPILE_DEFINITIONS>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1347 (target_compile_definitions):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_COMPILE_DEFINITIONS>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1347 (target_compile_definitions):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_COMPILE_DEFINITIONS>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1347 (target_compile_definitions):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_COMPILE_DEFINITIONS>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


CMake Error at CMakeLists.txt:1346 (target_include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:Python::NumPy,INTERFACE_INCLUDE_DIRECTORIES>

  Target "Python::NumPy" not found.
Call Stack (most recent call first):
  onnxruntime_python.cmake:76 (onnxruntime_add_include_to_target)
  CMakeLists.txt:2124 (include)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 2725, in <module>
    sys.exit(main())
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 2611, in main
    generate_build_tree(
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 1226, in generate_build_tree
    run_subprocess(
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 707, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Users\Валерий\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
```

There is additional note that before failure it also did not find numpy package in python but it exists:
```
Requirement already satisfied: numpy>=1.16.6 in c:\users\валерий\appdata\local\programs\python\python310\lib\site-packages (1.22.4)
...
-- Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS NumPy) (found suitable version "3.10.5", minimum required is "3.6")
```
I checked is numpy installed in python:
```
pip install numpy
Requirement already satisfied: numpy in c:\users\валерий\appdata\local\programs\python\python310\lib\site-packages (1.22.4)
```
And PATHs are expected:
```
>echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Users\Валерий\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Валерий\AppData\Local\Programs\Python\Python310\;C:\Users\Валерий\AppData\Local\Microsoft\WindowsApps;C:\Users\Валерий\AppData\Local\Programs\Microsoft VS Code\bin
```

I also tried to build without python by the line (without "build_wheel" key):
`build.bat --config Release --parallel --cmake_generator "Visual Studio 17 2022"`
As result the following error was raised:
```
  gpt_subgraph.cc
  logits_processor.cc
  sequences.cc
  word_conv_embedding.cc
Traceback (most recent call last):
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 2725, in <module>
    sys.exit(main())
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 2644, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 1287, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\ci_build\build.py", line 707, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Workshop\MSFT_ORT\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Users\Валерий\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'D:\\Workshop\\MSFT_ORT\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:8', '/nodeReuse:False']' returned non-zero exit status 1.
```

**Comment by snnn** [comment]
Apparently you have two python.exe in your PATH. The one you used with pip and numpy is not the one you used for building onnxruntime. Check C:\Users\xxx\AppData\Local\Microsoft\WindowsApps

**Comment by vvchernov** [comment]
Hello @snnn! The reason you said seems correct. But your tip did not help me, I removed python.exe from ..AppData\Local\Microsoft\WindowsApps (it stays in AppData\Local\Programs\Python\Python310\ only) but the problem and logs remained the same. I try to investigate where it finds numpy (or python) else. I think you rushed to close the issue

**Comment by tmoreau89** [comment]
@snnn I believe we are still blocked on this issue, could you please re-open and point us to a resource that could help us address this build issue?

**Comment by vvchernov** [comment]
Thanks @snnn! I understand all your statements and I have been trying to investigate cmake scripts in suggested way.
If it is environment problem what do you think about way to check it? May be reinstall cmake, python, VS Community and onnxruntime as result?

**Comment by xadupre** [comment]
I build onnxruntime on windows every two weeks with no issues. I use python 3.9 (onnx on python 3.10 has not been released yet). I never have python path in environment variable %PATH%, i add it when i need it. I use the standard python distribution (not anaconda). I rarely have issues.

**Comment by vvchernov** [comment]
Thanks for comments @xadupre! I think python should be in PATH due to during ONNX Runtime build the python script (build.py) is launched. May be it is python version issue, I should check

**Comment by xadupre** [comment]
I mean i add python path to PATH but it is only valid for the command line window i opened to run the build. Without adding it, it fails but that's how i check there is not other python.

**Comment by snnn** [comment]
python doesn't be in PATH when build.py is invoked.

**Comment by vvchernov** [comment]
Hello guys! Thanks for your help! I've resolved problem locally by hardcoded direct path to numpy to special cmake key (Python_NumPy_INCLUDE_DIR) before find_package(Python ...). In my understanding it is weird behavior of find_package method for python on CMake side. I continue to investigate CMake script for problem localization.

Notes for other readers: Python downgrading to 3.9 version, VS Community and CMake reinstalling did not help to solve the issue.

**Comment by nums11** [comment]
Closing as resolved
