### ISSUE TITLE
RuntimeError: Exporting the operator resolve_conj to ONNX opset version 12 is not supported. 

### ISSUE THREAD

**Issue by ravindra-ut** [microsoft/onnxruntime#11812]
**Describe the bug**
```
Traceback (most recent call last):
  File "convert_to_onnx.py", line 367, in <module>
    main(args)
  File "convert_to_onnx.py", line 357, in main
    export_longformer(model, onnx_model_path, args.export_padding)
  File "convert_to_onnx.py", line 307, in export_longformer
    torch_onnx_export(
  File "/home/ubuntu/workspace/onnxruntime/onnxruntime/python/tools/transformers/models/longformer/../../torch_onnx_export_helper.py", line 53, in torch_onnx_export
    torch.onnx.export(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator resolve_conj to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

```
**Urgency**
Longformer

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: >>> onnxruntime.__version__
'1.10.0'

- Python version: Python 3.8.12
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: Longformer

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- onnxruntime/onnxruntime/python/tools/transformers/models/longformer$ python3 convert_to_onnx.py --model longformer-base-4096 --precision fp16 --optimize_onnx
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Model exported to onnx

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by ravindra-ut** [comment]
The conversion also fails for opset 11 as well.
```
  File "convert_to_onnx.py", line 367, in <module>
    main(args)
  File "convert_to_onnx.py", line 357, in main
    export_longformer(model, onnx_model_path, args.export_padding)
  File "convert_to_onnx.py", line 307, in export_longformer
    torch_onnx_export(
  File "/home/ubuntu/workspace/onnxruntime/onnxruntime/python/tools/transformers/models/longformer/../../torch_onnx_export_helper.py", line 53, in torch_onnx_export
    torch.onnx.export(
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator resolve_conj to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

```

**Comment by leandro-svg** [comment]
I had this error aswell. I could solve it by using the version 13.
Hope it helps.

**Comment by KrystalBling** [comment]
> 我也有这个错误。我可以通过使用版本 13 来解决它。 希望它有所帮助。

I changed the opset version to 13, but still wrong.

**Comment by SolomidHero** [comment]
@KrystalBling 
It might be using `print()` for tensor or its shape in your model
See https://github.com/pytorch/pytorch/issues/73619

**Comment by lix19937** [comment]
Strange error reporting !
