### ISSUE TITLE
How to use webgl version?

### ISSUE THREAD

**Issue by fmscole** [microsoft/onnxruntime#11980]
When I set the tag in the html file:
`<script src="./ort.webgl.min.js" type="module"></script>`

I get the bug:
```
Uncaught (in promise) Error: no available backend found. ERR: 
    at backend-impl.js:80:11
    at h.create (inference-session-impl.js:169:31)
    at start ((index):97:48)
```
 So,myquestion is how to use the webgl version?

**Comment by fmscole** [comment]
I have resolved my question by add the option `{ executionProviders: ['webgl'] `,like:
html:
 `<script src="./node_modules/@tensorflow/tfjs/dist/tf.min.js" ></script>`
js:
`const session = await ort.InferenceSession.create('./mnist_cnn.onnx', { executionProviders: ['webgl'] });`

The docs and demo are too simple.
I find the key when I find 'onnxruntime-master\js\web\test\e2e\browser-test-webgl.js'.

But webgl do not surpport yolov5's op yet.
