### ISSUE TITLE
 failed to initialize a session in the GPU environment

### ISSUE THREAD

**Issue by liulhdarks** [microsoft/onnxruntime#11996]
**Describe the bug**
Error report when initializing a onnxruntime session in the GPU environment.
```
[2022-06-26 18:42:25] device: GPU
[2022-06-26 18:42:25] use CUDAExecutionProvider
[2022-06-26 18:42:26] Traceback (most recent call last):
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/./inferences/eas_service.py", line 88, in <module>
[2022-06-26 18:42:26]     server.init()
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/./inferences/eas_service.py", line 58, in init
[2022-06-26 18:42:26]     self.onnx_infer = Gpt2OnnxInference(model_root_path)
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/inferences/gpt2_onnx_inference.py", line 78, in __init__
[2022-06-26 18:42:26]     self.initialize()
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/inferences/gpt2_onnx_inference.py", line 85, in initialize
[2022-06-26 18:42:26]     self.ort_session = create_ort_session(os.path.join(self.model_root_path, "gpt2_beam_search.onnx"), True)
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/inferences/gpt2_onnx_inference.py", line 52, in create_ort_session
[2022-06-26 18:42:26]     ort_session = InferenceSession(model_path, sess_options, providers=execution_providers)
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/ENV/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
[2022-06-26 18:42:26]     self._create_inference_session(providers, provider_options, disabled_optimizers)
[2022-06-26 18:42:26]   File "/home/admin/docker_ml/workspace/predictor/gpt2_completion_model_gpu_onnx_demo_v1/ENV/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
[2022-06-26 18:42:26]     sess.initialize_session(providers, provider_options, disabled_optimizers)
[2022-06-26 18:42:26] RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 3: initialization error ; GPU=-598013440 ; hostname=gpt2-completion-model-gpu-onnx-demo-v1-9c5b54d55-4bdnr ; expr=cudaSetDevice(info_.device_id); 
```
Code
```
def create_ort_session(model_path, use_gpu):
    import onnxruntime
    from onnxruntime import SessionOptions, InferenceSession, __version__ as ort_version, GraphOptimizationLevel, \
        get_available_providers

    print("device:", onnxruntime.get_device())
    sess_options = SessionOptions()
    sess_options.graph_optimization_level = GraphOptimizationLevel.ORT_DISABLE_ALL
    execution_providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if use_gpu else ['CPUExecutionProvider']
    if use_gpu:
        if 'CUDAExecutionProvider' not in get_available_providers():
            raise RuntimeError("CUDAExecutionProvider is not avaiable for --use_gpu!")
        else:
            print("use CUDAExecutionProvider")

    ort_session = InferenceSession(model_path, sess_options, providers=execution_providers)
    return ort_session

if __name__ == "__main__":
   session = create_ort_session("....", True)
```
Is there a problem with CUDA and cuDNN versions?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.11.1
- Python version: 3.9.4
- CUDA version: 11.2
- cuDNN version: v8.2.4.15
- cudnn toolkit: 11.3

**Comment by tianleiwu** [comment]
The error happens during calling cudaSetDevice(info_.device_id). What GPU do you use?

According to https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html, ORT 1.11.1 is built with CUDA 11.4 and cuDNN 8.2.4. I think your version is compatible. Did you set path like the following (update path if needed) before running the test?
```
export PATH=/usr/local/cuda-11.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
