### ISSUE TITLE
onnxruntime arm32 build on ubuntu focal

### ISSUE THREAD

**Issue by jji2019** [microsoft/onnxruntime#12026]
**Describe the bug**
[Dockerfile.arm32v7](https://github.com/microsoft/onnxruntime/blob/v1.11.0/dockerfiles/Dockerfile.arm32v7) with base image **arm32v7/fedora:34** can generate pass build; however, using base image **[armv7hf-ubuntu-python:3.8-focal-20220622](https://hub.docker.com/r/balenalib/armv7hf-ubuntu-python/tags?page=1&name=3.8-focal-20220622)** cannot generate a correct build. 

The error message:
```
#23 1545.0 [100%] Linking CXX shared module onnx_cpp2py_export.cpython-38-arm-linux-gnueabihf.so
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x700): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::Init()':
#23 1548.1 (.text+0x700): dangerous relocation: unsupported relocation
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x790): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)':
#23 1548.1 (.text+0x790): dangerous relocation: unsupported relocation
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x7cc): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArena()':
#23 1548.1 (.text+0x7cc): dangerous relocation: unsupported relocation
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x9b0): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned int)':
#23 1548.1 (.text+0x9b0): dangerous relocation: unsupported relocation
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xbf8): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned int, void (*)(void*))':
#23 1548.1 (.text+0xbf8): dangerous relocation: unsupported relocation
#23 1548.1 /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xc94): R_ARM_TLS_LE32 relocation not permitted in shared object
#23 1548.1 /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))':
#23 1548.1 (.text+0xc94): dangerous relocation: unsupported relocation
#23 1548.2 collect2: error: ld returned 1 exit status
#23 1548.2 make[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-38-arm-linux-gnueabihf.so] Error 1
#23 1548.2 make[1]: *** [CMakeFiles/Makefile2:255: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
#23 1548.2 make: *** [Makefile:136: all] Error 2
#23 1548.2 /usr/local/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
#23 1548.2   warnings.warn(
#23 1548.3 Traceback (most recent call last):
#23 1548.3   File "setup.py", line 336, in <module>
#23 1548.3     setuptools.setup(
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
#23 1548.3     return distutils.core.setup(**attrs)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
#23 1548.3     return run_commands(dist)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
#23 1548.3     dist.run_commands()
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
#23 1548.3     self.run_command(cmd)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
#23 1548.3     super().run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#23 1548.3     cmd_obj.run()
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
#23 1548.3     self.run_command('build')
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
#23 1548.3     self.distribution.run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
#23 1548.3     super().run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#23 1548.3     cmd_obj.run()
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/command/build.py", line 24, in run
#23 1548.3     super().run()
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
#23 1548.3     self.run_command(cmd_name)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
#23 1548.3     self.distribution.run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
#23 1548.3     super().run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#23 1548.3     cmd_obj.run()
#23 1548.3   File "setup.py", line 232, in run
#23 1548.3     self.run_command('cmake_build')
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
#23 1548.3     self.distribution.run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
#23 1548.3     super().run_command(command)
#23 1548.3   File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
#23 1548.3     cmd_obj.run()
#23 1548.3   File "setup.py", line 226, in run
#23 1548.3     subprocess.check_call(build_args)
#23 1548.3   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#23 1548.3     raise CalledProcessError(retcode, cmd)
#23 1548.3 subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
#23 ERROR: executor failed running [/bin/sh -c python3 setup.py bdist_wheel &&     pip3 install --force-reinstall dist/* &&     cp dist/* /wheels/]: exit code: 1
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04 focal):
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.11.0
- Python version: 3.8
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): 9.4.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

```
 ******** Summary ********
CMake version             : 3.20.5
CMake command             : /usr/local/bin/cmake
System                    : Linux
C++ compiler              : /usr/bin/c++
C++ compiler version      : 9.4.0
CXX flags                 :  -Wnon-virtual-dtor
Build type                : Release
Compile definitions       : __STDC_FORMAT_MACROS
CMAKE_PREFIX_PATH         : 
CMAKE_INSTALL_PREFIX      : /usr/local
CMAKE_MODULE_PATH         : 
#23 47.25 -- 
ONNX version              : 1.11.0
ONNX NAMESPACE            : onnx
ONNX_USE_LITE_PROTO       : OFF
USE_PROTOBUF_SHARED_LIBS  : OFF
Protobuf_USE_STATIC_LIBS  : ON
ONNX_DISABLE_EXCEPTIONS   : OFF
ONNX_WERROR               : OFF
ONNX_BUILD_TESTS          : OFF
ONNX_BUILD_BENCHMARKS     : OFF
ONNXIFI_DUMMY_BACKEND     : OFF
ONNXIFI_ENABLE_EXT        : OFF

Protobuf compiler         : /usr/bin/protoc
Protobuf includes         : /usr/include
Protobuf libraries        : /usr/lib/arm-linux-gnueabihf/libprotobuf.a;-lpthread
BUILD_ONNX_PYTHON         : ON
  Python version        : 
  Python executable     : /usr/local/bin/python3
  Python includes       : /usr/local/include/python3.8
Configuring done
Generating done
```
**Additional context**
Using docker cross building.

**Comment by jji2019** [comment]
The error is similar to https://github.com/onnx/onnx/issues/3374:
```
libprotobuf.a
...
R_ARM_TLS_LE32 relocation not permitted in shared object
```

Should below arguments still the suggested solution?
```CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON"```
or
```CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF "```

**Comment by jji2019** [comment]
Close this issue and switch to https://github.com/onnx/onnx/issues/4327 as it might be related to ONNX only
