### ISSUE TITLE
Build wasm static library bug because of missing `testdata` folder.

### ISSUE THREAD

**Issue by trbasoglu** [microsoft/onnxruntime#12048]
**Describtion**
I try to build with `./build.sh --build_wasm_static_lib --config Release` command. It raise below error at %65. I get same error with misSizeRel config. Debug config has no problem. Copying testdata folder from debug solved issue. 
```shell
[ 65%] Linking CXX executable onnxruntime_webassembly_test.js
error: /home/trbasoglu/onnxruntime/build/Linux/Release/testdata@/testdata does not exist
em++: error: '/home/trbasoglu/onnxruntime/cmake/external/emsdk/upstream/emscripten/tools/file_packager onnxruntime_webassembly_test.data --from-emcc --export-name=Module --preload /home/trbasoglu/onnxruntime/build/Linux/Release/testdata@/testdata' failed (returned 1)
gmake[2]: *** [CMakeFiles/onnxruntime_webassembly_test.dir/build.make:124: onnxruntime_webassembly_test.js] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:950: CMakeFiles/onnxruntime_webassembly_test.dir/all] Error 2
gmake: *** [Makefile:182: all] Error 2
Traceback (most recent call last):
  File "/home/trbasoglu/onnxruntime/tools/ci_build/build.py", line 2725, in <module>
    sys.exit(main())
  File "/home/trbasoglu/onnxruntime/tools/ci_build/build.py", line 2644, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/trbasoglu/onnxruntime/tools/ci_build/build.py", line 1287, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/trbasoglu/onnxruntime/tools/ci_build/build.py", line 707, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/trbasoglu/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/home/trbasoglu/micromamba/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/trbasoglu/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

**Urgency**
None

**System information**
- OS Platform and Distribution :Pop!_OS 21.10
- ONNX Runtime installed from (source or binary): commit 40d2c98e4d64d7931fcbb682c81dc53988c48dcc
- ONNX Runtime version:ONNX Runtime v1.11.1
- Python version:3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):11.2.0
- CUDA/cuDNN version:-
- GPU model and memory:NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile]

**To Reproduce**
```
git clone --recursive https://github.com/Microsoft/onnxruntime
source cmake/external/emsdk/emsdk_env.sh
./build.sh --build_wasm_static_lib --config Release
```

**Comment by fs-eire** [comment]
The reason is, in release build by default we pass flag `--disable_wasm_exception_catching` for performance concerns (see also https://emscripten.org/docs/porting/exceptions.html)

The test cases need exceptions enabled to work, so with exception catching disabled, we don't run the tests in release build.
