### ISSUE TITLE
Builds C# bindings and creates nuget package

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#12042]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:1.6.0 GPU
- Python version:
- Visual Studio version (if applicable): vs 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2 / 8.0
- GPU model and memory: 2080ti

i try to  builds C# bindings and creates nuget package, the command is : build.bat  --build_nuget --config Release --parallel --use_cuda  --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --skip_tests --cmake_generator "Visual Studio 16 2019"

errors as follows: the dotnet version is 5.0 ,the csharp files is always not be compiled success, and i can't find nuget package under \nuget-artifacts,there is no nuget-artifacts file directory

fatal: Needed a single revision
\csharp\OnnxRuntime.CSharp.proj(94,5): error MSB3073: 命令“git rev-parse --short HEAD”已退出，代码为 128。
Traceback (most recent call last):
  File "C:\pythonrun\\tools\ci_build\build.py", line 2088, in <module>
    sys.exit(main())
  File "C:\pythonrun\\tools\ci_build\build.py", line 2068, in main
    args.use_mklml
  File "C:\pythonrun\\tools\ci_build\build.py", line 1668, in build_nuget_package
    run_subprocess(cmd_args, cwd=csharp_build_dir)
  File "C:\pythonrun\\tools\ci_build\build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\pythonrun\tools\python\util\run.py", line 42, in run
    env=env, shell=shell)
  File "D:\python\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dotnet', 'msbuild', 'OnnxRuntime.CSharp.proj', '/t:CreatePackage', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.Gpu"', '/p:Configuration="Release"', '/p:ExecutionProvider="None"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="C:\\pythonrun\\build\\Windows"']' returned non-zero exit status 1.

**Comment by edgchen1** [comment]
> fatal: Needed a single revision
\csharp\OnnxRuntime.CSharp.proj(94,5): error MSB3073: 命令“git rev-parse --short HEAD”已退出，代码为 128。

Looks like `git rev-parse --short HEAD` failed. Are you building from a git repo?

**Comment by cqray1990** [comment]
@edgchen1 i build with git clone -b v1.6.0 ...

**Comment by cqray1990** [comment]
@mattetti @mtodd @keeran

**Comment by wschin** [comment]
I can build nuget with VS 2022. Details are [here](https://github.com/microsoft/onnxruntime/issues/12061#issuecomment-1172551591).

**Comment by cqray1990** [comment]
@edgchen1  what did git rev-parse --short HEAD means? hoe solove this problem?
