### ISSUE TITLE
Error in symbloc_shape_infer.py: assert name in self.sympy_data_ or ...

### ISSUE THREAD

**Issue by ericchansen** [microsoft/onnxruntime#12127]
**Describe the Bug**

We're running most of this code in ultralytics/yolov5, https://hub.docker.com/layers/yolov5/ultralytics/yolov5/latest/images/sha256-5ea959b2f53d15cbeaf6188582fa601bfcec548aa8d2360b2a94b51b851bd106?context=explore. This error does not occur in 6.1 of ultralytics/yolov5, https://hub.docker.com/layers/yolov5/ultralytics/yolov5/v6.1/images/sha256-5bdc997160dce1397392c7903a12409c9ad83a00ab79ac9d9d0eb711a4e6713b?context=explore.

Background: We have an ONNX model that we exported with 1 dynamic axis on the input and output for batching. We used a variant of https://github.com/ultralytics/yolov5/blob/master/export.py to obtain the ONNX model.

We try the ONNX model on NVIDIA Triton server using the Tensor RT optimizations, and we get back an error that looks like this.

```
I0707 21:10:44.336203 45 model_repository_manager.cc:1022] loading: inventory_management_object_detection:2
I0707 21:10:44.442965 45 onnxruntime.cc:2056] TRITONBACKEND_ModelInitialize: inventory_management_object_detection (version 2)
I0707 21:10:44.450904 45 onnxruntime.cc:2099] TRITONBACKEND_ModelInstanceInitialize: inventory_management_object_detection_0 (GPU device 0)
2022-07-07 21:10:44.676913156 [E:onnxruntime:, inference_session.cc:1355 operator()] Exception during initialization: /workspace/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:893 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: onnx::Reshape_356 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs

I0707 21:10:44.681849 45 onnxruntime.cc:2133] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0707 21:10:44.682063 45 onnxruntime.cc:2079] TRITONBACKEND_ModelFinalize: delete model state
E0707 21:10:44.682095 45 model_repository_manager.cc:1186] failed to load 'inventory_management_object_detection' version 2: Internal: onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:893 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: onnx::Reshape_356 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs
```

We're paying special attention to `Please run shape inference on the onnx model first. Details can be found in https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs`. We tried to run the symbolic_shape_infer.py on the ONNX model, and then we get this error.

```
root@cc13cc141dce:/workspace#  cd /workspace ; /usr/bin/env python /root/.vscode-server-insiders/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/launcher 43573 -- /workspace/utils/symbolic_shape_infer.py --input /data/inventory-management/yolo-inventory-management-20220701/best.onnx --output /data/inventory-management/yolo-inventory-management-20220701/best_shape_inferred.onnx --auto_merge 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/utils/symbolic_shape_infer.py", line 2401, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
  File "/workspace/utils/symbolic_shape_infer.py", line 2357, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "/workspace/utils/symbolic_shape_infer.py", line 2255, in _infer_impl
    self._get_value(node, 1),
  File "/workspace/utils/symbolic_shape_infer.py", line 381, in _get_value
    assert name in self.sympy_data_ or name in self.initializers_
AssertionError
```

We're not sure what to do with this last error.

**Urgency**

We want to go live with this model sometime in the next month.

**System Information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Running symbolic_shape_infer.py inside latest from https://hub.docker.com/r/ultralytics/yolov5
- ONNX Runtime installed from (source or binary): see code snippet below
- ONNX Runtime version: 1.11.0, see code snippet below
- Python version: 3.8.13
- Visual Studio version (if applicable): not applicable
- GCC/Compiler version (if compiling from source): not applicable
- CUDA/cuDNN version: not applicable
- GPU model and memory: a bunch of A30's

```
root@cc13cc141dce:/workspace# pip show onnx
Name: onnx
Version: 1.11.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfai.foundation
License: Apache License v2.0
Location: /opt/conda/lib/python3.8/site-packages
Requires: numpy, protobuf, typing-extensions
Required-by: onnxsim-no-ort
```

**To Reproduce**

See description above.

**Expected Behavior**

Not having an error would be nice.

**Screenshots**

 None.

**Additional Context**

None.

**Comment by justinchuby** [comment]
Can you try exporting the model with the latest pytorch-nightly build? Be sure to also set simplify=False in the yolov5/export.py script

**Comment by justinchuby** [comment]
If there are any errors during the export process, please open an issue in the pytorch repo (https://github.com/pytorch/pytorch/issues). Thanks!

**Comment by garymm** [comment]
Seems like a bug in symbolic_shape_infer.py, not a converter.
@ytaous not sure what the right `component` label to use for that is. Could you please apply it?

**Comment by sammilei** [comment]
Hi, how did you solve it? I got the same error.
