### ISSUE TITLE
symbolic_shape_infer.py not working with models quantized with 🤗 Optimum for TensorRT

### ISSUE THREAD

**Issue by sam-h-bean** [microsoft/onnxruntime#12173]
**Describe the bug**
When running the symbolic inference script on a model quantized for TensorRT through the 🤗 Optimum library I am receiving the following error
```bash
root@tensorrt-nrfkc:/workspace# python symbolic_shape_infer.py --input model-quantized.onnx --output new-model-quantized.onnx --save_as_external_data --guess_output_rank --auto_merge --verbose 3
Potential unsafe merge between symbolic expressions: (floor(Min(64, Reshape_6250_o0__d3)/2 + 1/2),floor(Min(64, Reshape_6250_o0__d3)/2))
Potential unsafe merge between symbolic expressions: (floor(Min(64, Reshape_6252_o0__d3)/2),floor(Min(64, Reshape_6252_o0__d3)/2 + 1/2))
Traceback (most recent call last):
  File "symbolic_shape_infer.py", line 2424, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
  File "symbolic_shape_infer.py", line 2357, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "symbolic_shape_infer.py", line 2127, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "symbolic_shape_infer.py", line 1818, in _infer_Tile
    input_sympy_shape = self._get_sympy_shape(node, 0)
  File "symbolic_shape_infer.py", line 367, in _get_sympy_shape
    for d in self._get_shape(node, idx):
TypeError: 'NoneType' object is not iterable
```

**Urgency**
This is directly impacting the prospects of products you.com is building that need low-latency inference with billion-parameter language models.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- ONNX Runtime installed from (source or binary): `pip install -i https://test.pypi.org/simple/ ort-nightly-gpu==1.12.0.dev20220707003`
- ONNX Runtime version: 1.12.0 RC
- Python version: 3.8.10
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A 
- CUDA/cuDNN version:
- GPU model and memory:
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000001:00:00.0 Off |                    0 |
| N/A   30C    P0    34W / 250W |   3443MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

**To Reproduce**
```python
from optimum.onnxruntime import ORTQuantizer
from optimum.onnxruntime.modeling_ort import ORTModelForCausalLM
from optimum.onnxruntime.configuration import AutoQuantizationConfig
from transformers import AutoTokenizer, AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained('distilgpt2')
tokenizer = AutoTokenizer.from_pretrained('distilgpt2', padding=True, truncation=True)

qconfig = AutoQuantizationConfig.tensorrt(is_static=False, per_channel=False)
quantizer = ORTQuantizer(model=model, preprocessor=tokenizer, feature="causal-lm")
quantizer.export(
    onnx_model_path="model.onnx",
    onnx_quantized_model_output_path="model-quantized.onnx",
    quantization_config=qconfig,
)
```
then run
```bash
python symbolic_shape_infer.py --input model-quantized.onnx --output new-model-quantized.onnx --save_as_external_data --guess_output_rank --auto_merge --verbose 3

```

**Expected behavior**
Creates a .onnx file for the quantized model that can be run with TensorRT

**Comment by ytaous** [comment]
discussed in https://github.com/microsoft/onnxruntime/issues/12133

**Comment by sam-h-bean** [comment]
https://github.com/microsoft/onnxruntime/pull/12174

Not sure if this is the real fix but it got the script to run 🤷

**Comment by fxmarty** [comment]
@sam-h-bean To the best of my knowledge TensorRT can only consume QDQ models, so models quantized with static quantization of ONNX Runtime. Here it seems you want to use dynamic quantization. In this case, I suspect operators as `MatMulInteger` will not use the TensorRT execution provider. What did you do in the end?
