### ISSUE TITLE
Scan Op support

### ISSUE THREAD

**Issue by colinback** [microsoft/onnxruntime#1234]
**Is your feature request related to a problem? Please describe.**
I have a simple RNN ONNX model generated using tf2onnx (https://github.com/onnx/tensorflow-onnx/). 

When I try onnxruntime, it seems does not support Scan Operator.
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    sess = rt.InferenceSession(model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./basic_rnn_cell.onnx failed:Node:custom_rnn_scan_Scan__13 No Op registered for Scan with domain_version of 7
```

**System information**
- ONNX Runtime version (you are using): 0.4.0

**Describe the solution you'd like**
I expect that I can get inference result using onnxruntime. The input value is `x_val = np.random.rand(3, 1, 2).astype(np.float32, copy=False)`

**Describe alternatives you've considered**

**Additional context**
[basic_rnn_cell.onnx.zip](https://github.com/microsoft/onnxruntime/files/3295447/basic_rnn_cell.onnx.zip)

**Comment by colinback** [comment]
Hi, sorry I fix it. It's because tensorflow-onnx set opset 7 as default. When I set opset 8 during call `process_tf_graph`, the problem is gone.
