### ISSUE TITLE
Unable to build Onnxruntime 1.12.0 with OpenVINO 2020.3 on Windows 10

### ISSUE THREAD

**Issue by ilpropheta** [microsoft/onnxruntime#12342]
**Describe the bug**

I'm trying to build the latest release of Onnxruntime 1.12.0 with OpenVINO EP (2020.3) on Windows 10. Here is my command line:

```
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --use_openvino GPU_FP32
```

I am working only on the **Processor Graphics** scenario (no need for configuring Movidius nor Vision Accelerator).

I have followed the instructions [here](https://onnxruntime.ai/docs/build/eps.html#openvino) and correctly initialized the OpenVINO environment by running `setupvars.bat` before launching the build command.

The build breaks prematurely after CMake configuration. The issue seems related to `ngraph::onnx_importer` target that is not found. Here is the stack trace:

```
-- Configuring done
CMake Error at CMakeLists.txt:1312 (add_library):
  Target "onnxruntime_providers_openvino" links to target
  "ngraph::onnx_importer" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  onnxruntime_providers.cmake:808 (onnxruntime_add_shared_library_module)
  CMakeLists.txt:1992 (include)


CMake Error at CMakeLists.txt:1312 (add_library):
  Target "onnxruntime_providers_openvino" links to target
  "ngraph::onnx_importer" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  onnxruntime_providers.cmake:808 (onnxruntime_add_shared_library_module)
  CMakeLists.txt:1992 (include)


CMake Error at CMakeLists.txt:1312 (add_library):
  Target "onnxruntime_providers_openvino" links to target
  "ngraph::onnx_importer" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  onnxruntime_providers.cmake:808 (onnxruntime_add_shared_library_module)
  CMakeLists.txt:1992 (include)


CMake Error at CMakeLists.txt:1312 (add_library):
  Target "onnxruntime_providers_openvino" links to target
  "ngraph::onnx_importer" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  onnxruntime_providers.cmake:808 (onnxruntime_add_shared_library_module)
  CMakeLists.txt:1992 (include)


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    onnxruntime_USE_OPENVINO_DEVICE


CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "c:\source\onnxruntime\tools\ci_build\build.py", line 2744, in <module>
    sys.exit(main())
  File "c:\source\onnxruntime\tools\ci_build\build.py", line 2630, in main
    generate_build_tree(
  File "c:\source\onnxruntime\tools\ci_build\build.py", line 1240, in generate_build_tree
    run_subprocess(
  File "c:\source\onnxruntime\tools\ci_build\build.py", line 714, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "c:\source\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Program Files\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', 'c:\\source\\onnxruntime\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_NUPHAR_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_PLACEHOLDER_BUILDER=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_EAGER_MODE=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_OPENVINO=ON', '-Donnxruntime_USE_OPENVINO_MYRIAD=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32=ON', '-Donnxruntime_USE_OPENVINO_GPU_FP16=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_VAD_M=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F=OFF', '-Donnxruntime_USE_OPENVINO_MYRIAD_NP=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32_NP=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP16_NP=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32_NP=OFF', '-Donnxruntime_USE_OPENVINO_VAD_M_NP=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F_NP=OFF', '-Donnxruntime_USE_OPENVINO_HETERO=OFF', '-Donnxruntime_USE_OPENVINO_DEVICE=GPU_FP32', '-Donnxruntime_USE_OPENVINO_MULTI=OFF', '-Donnxruntime_USE_OPENVINO_AUTO=OFF', '-Donnxruntime_USE_FULL_PROTOBUF=ON', '-DProtobuf_USE_STATIC_LIBS=ON', '-Donnxruntime_DEV_MODE=ON', '-DONNX_USE_MSVC_STATIC_RUNTIME=OFF', '-Dprotobuf_MSVC_STATIC_RUNTIME=OFF', '-Dgtest_force_shared_crt=ON', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo']' returned non-zero exit status 1.
```

Does anyone know how to solve this problem?

Many thanks in advance,

Marco

**Comment by sfatimar** [comment]
We no longer support 2020.3 OpenVINO. Please use the latest version

**Comment by sfatimar** [comment]
There was a huge difference between OV 2020.3 and OV 2020.4 so it wont be possible to tweak the code in ORT 1.11 to get things working.  If you can upgrade to OV 2020.4 then you can still use ORT 1.12 I think. Why do you need to build ? Will existing executables in https://github.com/intel/onnxruntime/releases will not help you ? What is the target architecture CPU ?

**Comment by sfatimar** [comment]
I am sorry I checked. We deprecated OV 2020.4 with ORT 1.8 long back. I really think you are trying to use very old software
