### ISSUE TITLE
Unable to build tensorrt docker image

### ISSUE THREAD

**Issue by defqoon** [microsoft/onnxruntime#12373]
**Describe the bug**
Following the instructions [here](https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#tensorrt) to build the docker image.

Getting the following error:

```
[ 68%] Linking CUDA shared module libonnxruntime_providers_cuda.so
[ 68%] Built target onnxruntime_providers_cuda
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 2765, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 2680, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/code/onnxruntime/tools/ci_build/build.py", line 1315, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 724, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/onnxruntime/tools/python/util/run.py", line 57, in run
    shell=shell,
  File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/code/cmake-3.21.0-linux-x86_64/bin/cmake', '--build', '/code/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j16']' returned non-zero exit status 2.
The command '/bin/sh -c git clone --single-branch --branch ${ONNXRUNTIME_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime &&    /bin/sh onnxruntime/dockerfiles/scripts/install_common_deps.sh &&    trt_version=${TRT_VERSION:0:3} &&    /bin/sh onnxruntime/dockerfiles/scripts/checkout_submodules.sh ${trt_version} &&    cd onnxruntime &&    /bin/sh build.sh --parallel --build_shared_lib --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --config Release --build_wheel --skip_tests --skip_submodule_sync --cmake_extra_defines '"CMAKE_CUDA_ARCHITECTURES='${CMAKE_CUDA_ARCHITECTURES}'"' &&    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl &&    cd ..' returned a non-zero code: 1
````

**Urgency**
Low

**System information**
- OS Platform and Distribution: ubuntu 20.04
- CUDA/cuDNN version: 11.4
- GPU model and memory: rtx 8030

**To Reproduce**
Build the tensorrt docker image using the commands in the tutorial.

**Expected behavior**
Image should build correctly.

**Comment by askhade** [comment]
Can you paste the entire error message.

**Comment by defqoon** [comment]
> Can you paste the entire error message.

added the docker logs of the onnxruntime build step

**Comment by tianleiwu** [comment]
Try https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.ubuntu_cuda11_6_tensorrt8_4. It works for me.

**Comment by XYudong** [comment]
I met the same issue while `docker build -t onnxruntime-trt -f Dockerfile.tensorrt .`

error log: 
```
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 67%] Linking CUDA shared module libonnxruntime_providers_cuda.so
[ 67%] Built target onnxruntime_providers_cuda
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/code/onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/onnxruntime/tools/python/util/run.py", line 57, in run
    shell=shell,
  File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/code/cmake-3.21.0-linux-x86_64/bin/cmake', '--build', '/code/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.
The command '/bin/sh -c cd onnxruntime &&    /bin/sh build.sh --parallel --build_shared_lib --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --config Release --build_wheel --skip_tests --skip_submodule_sync --cmake_extra_defines '"CMAKE_CUDA_ARCHITECTURES='${CMAKE_CUDA_ARCHITECTURES}'"' &&    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl &&    cd ..' returned a non-zero code: 1
```

**Comment by XYudong** [comment]
> I met the same issue while `docker build -t onnxruntime-trt -f Dockerfile.tensorrt .` with current `main` and `v1.12.1` tag.
> 
> My OS is Debian 10.
> 
> error log:
> 
> ```
> nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
> [ 67%] Linking CUDA shared module libonnxruntime_providers_cuda.so
> [ 67%] Built target onnxruntime_providers_cuda
> make: *** [Makefile:166: all] Error 2
> Traceback (most recent call last):
>   File "/code/onnxruntime/tools/ci_build/build.py", line 2812, in <module>
>     sys.exit(main())
>   File "/code/onnxruntime/tools/ci_build/build.py", line 2727, in main
>     build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
>   File "/code/onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
>     run_subprocess(cmd_args, env=env)
>   File "/code/onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
>     return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
>   File "/code/onnxruntime/tools/python/util/run.py", line 57, in run
>     shell=shell,
>   File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/code/cmake-3.21.0-linux-x86_64/bin/cmake', '--build', '/code/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.
> The command '/bin/sh -c cd onnxruntime &&    /bin/sh build.sh --parallel --build_shared_lib --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --config Release --build_wheel --skip_tests --skip_submodule_sync --cmake_extra_defines '"CMAKE_CUDA_ARCHITECTURES='${CMAKE_CUDA_ARCHITECTURES}'"' &&    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl &&    cd ..' returned a non-zero code: 1
> ```

I think I figured out the problem. My NVIDIA Driver version is not compatible with the default `nvcr.io/nvidia/tensorrt` version in  the dockerfile. After changing the `TRT_CONTAINER_VERSION` in the dockerfile, I am able to build the image successfully. Thanks

**Comment by paulguerrie** [comment]
@XYudong can you provide more details?  What NVIDIA Driver version did you have and what version of tensorrt docker image did you change to? Thanks!
