### ISSUE TITLE
Fail to build onnxRT with oneDNN using official build command

### ISSUE THREAD

**Issue by cfgfung** [microsoft/onnxruntime#12382]
Hi,

I tried to build the onnxRT with oneDNNL using the following command in a docker:

"RUN cd ~ && git clone https://github.com/microsoft/onnxruntime.git && cd ~/onnxruntime && ./build.sh --enable_training --use_dnnl --build_wheel "

It seems that the safeint folder/file is missing and causes the build error. Is there any quick fix for this?

_**Error message:**
[ 57%] Building CXX object CMakeFiles/onnxruntime_providers_dnnl.dir/root/onnxruntime/onnxruntime/core/providers/dnnl/subgraph/dnnl_util.cc.o
[ 57%] Building CXX object CMakeFiles/onnxruntime_providers_dnnl.dir/root/onnxruntime/onnxruntime/core/providers/shared_library/provider_bridge_provider.cc.o
[91mIn file included from /root/onnxruntime/onnxruntime/core/providers/cpu/tensor/utils.h:10,
                 from /root/onnxruntime/orttraining/orttraining/training_ops/cpu/optimizer/adamw/adamwbase.h:8,
                 from /root/onnxruntime/onnxruntime/core/providers/shared_library/provider_bridge_provider.cc:43:
/root/onnxruntime/onnxruntime/core/common/safeint.h:35:10: fatal error: safeint/SafeInt.hpp: No such file or directory
   35 | #include "safeint/SafeInt.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[0m[91mmake[2]: *** [CMakeFiles/onnxruntime_providers_dnnl.dir/build.make:566: CMakeFiles/onnxruntime_providers_dnnl.dir/root/onnxruntime/onnxruntime/core/providers/shared_library/provider_bridge_provider.cc.o] Error 1
[0m[91mmake[1]: *** [CMakeFiles/Makefile2:1867: CMakeFiles/onnxruntime_providers_dnnl.dir/all] Error 2
[0m[91mmake: *** [Makefile:166: all] Error 2
[0m[91mTraceback (most recent call last):
  File "/root/onnxruntime/tools/ci_build/build.py", line 2765, in <module>
    sys.exit(main())
  File "/root/onnxruntime/tools/ci_build/build.py", line 2680, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/root/onnxruntime/tools/ci_build/build.py", line 1315, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/root/onnxruntime/tools/ci_build/build.py", line 724, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/root/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/opt/miniconda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/root/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.
[0mThe command '/bin/sh -c cd ~ && git clone https://github.com/microsoft/onnxruntime.git && cd ~/onnxruntime && ./build.sh --enable_training --use_dnnl --build_wheel' returned a non-zero code: 1
2022/07/29 04:31:32 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1_

**Comment by jywu-msft** [comment]
when you clone onnxruntime repo you need to use the clone --recursive option to fetch all the git submodules
reference the build instructions prerequisites
https://onnxruntime.ai/docs/build/inferencing.html#prerequisites
