### ISSUE TITLE
SequenceMap fails when the body contains constant nodes

### ISSUE THREAD

**Issue by jantonguirao** [microsoft/onnxruntime#12491]
**Describe the bug**
SequenceMap models that include constant nodes in the body fail.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.12.1
- Python version: 3.8.10
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
- Describe steps/code to reproduce the behavior.

```
import numpy as np  # type: ignore
import onnx
from onnx import parser
from onnx import checker
from onnx import helper
from onnx import TensorProto as tp
from onnx import save
import onnxruntime

op = onnx.OperatorSetIdProto()
op.version = 17

sample_g = parser.parse_graph('''
    zeropad (int64[3] x) => (int64[6] y)
    {
        zeros = Constant <value = int64[3] {0, 0, 0}> ()
        y = Concat <axis = 0> (x, zeros)
    }
    ''')

checker.check_graph(sample_g)

batch_m = helper.make_model(
    onnx.helper.make_graph(
        nodes=[
            onnx.helper.make_node('SequenceMap', body=sample_g, inputs=['in'], outputs=['out']),
        ],
        name='pad_to_largest',
        inputs=[onnx.helper.make_tensor_sequence_value_info('in', onnx.TensorProto.INT64, [3,])],
        outputs=[onnx.helper.make_tensor_sequence_value_info('out', onnx.TensorProto.INT64, [6,])],
    ),
    producer_name='test',
    opset_imports=[op]
)
checker.check_model(batch_m)
onnx.save(batch_m, 'test.onnx')

session = onnxruntime.InferenceSession('test.onnx', None)
inputs = [
    np.array([1, 2, 3], dtype=np.int64),
    np.array([4, 5, 6], dtype=np.int64)]

result = session.run([], {'in': inputs})
print(result)
```

Produces the following error:
```
Traceback (most recent call last):
  File "test_seq_map_error.py", line 38, in <module>
    session = onnxruntime.InferenceSession('test.onnx', None)
  File "/home/janton/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/janton/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. In Node, ("", Loop, "", -1) : ("_0x1c82f60_SequenceMap_input_sequence_seqlen": tensor(int64),"_0x1c82f60_SequenceMap_input_sequence_cond": tensor(bool),"_0x1c82f60_SequenceMap_out_sequence_0_seqempty": seq(tensor(int64)),) -> ("out": seq(tensor(int64)),) , Error Nodes in a graph must be topologically sorted, however input '_0x1c82f60_zeros' of node: 
name:  OpType: Concat
 is not output of any previous nodes.

```

**Expected behavior**
No errors are thrown.

**Screenshots**

**Additional context**
Removing the Constant node from the body makes the error go away.

**Comment by jantonguirao** [comment]
@gramalingam It seems that function inlining fails when dealing with subgraphs with Constant nodes

**Comment by gramalingam** [comment]
@jantonguirao , thanks, I will take a look. I am guessing a bug relating to renaming, when a constant is promoted to an initializer.

**Comment by gramalingam** [comment]
@jantonguirao : hope https://github.com/microsoft/onnxruntime/pull/12758 fixes this issue.

**Comment by jantonguirao** [comment]
I confirm that the issue is fixed with your PR. Thank you

**Comment by cbourjau** [comment]
I suppose this can be closed? @gramalingam

**Comment by gramalingam** [comment]
yes, thanks ... please let me know if there is anything not working yet
