### ISSUE TITLE
java  deploy in k8s Failed to load library libonnxruntime_providers_cuda.so with error

### ISSUE THREAD

**Issue by BillyChao** [microsoft/onnxruntime#12540]
**Deploy inference service using java in k8s   onnxruntime error**
ai.onnxruntime.OrtException: Error code - ORT_RUNTIME_EXCEPTION - message: /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1029 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublas.so.11: cannot open shared object file: No such file or directory
	at ai.onnxruntime.OrtSession$SessionOptions.addCUDA(Native Method)
	at ai.onnxruntime.OrtSession$SessionOptions.addCUDA(OrtSession.java:768)

**System information**
- OS Platform and Distribution (Alibaba Cloud Linux (Aliyun Linux) release 2.1903):
- ONNX Runtime installed from (maven ):
- ONNX Runtime version: 1.11.0
- Java version: 1.8
- CUDA  version: 11.2
- GPU model and memory:   Tesla T4  15G

**Comment by yufenglee** [comment]
Do you have cuda 11 installed? ORT doesn't pack cuda runtime

**Comment by BillyChao** [comment]
> Do you have cuda 11 installed? ORT doesn't pack cuda runtime

I install cuda 11.2 in k8s gpu node

**Comment by yuslepukhin** [comment]
Use `ldd` command to find out if the library can be found in the library paths.

**Comment by BillyChao** [comment]
> Use `ldd` command to find out if the library can be found in the library paths.
yep， libonnxruntime_providers_cuda.so  not found in  library,  I solve it by  1. install cuDNN  2. add custom path in  ldconfig, Thank you

**Comment by umi-soft** [comment]
I also encountered this problem。
Failed to load library libonnxruntime_providers_cuda.so with error: `libcublasLt.so.11`: cannot open shared object file: No such file or directory

**Comment by umi-soft** [comment]
> I also encountered this problem。 Failed to load library libonnxruntime_providers_cuda.so with error: `libcublasLt.so.11`: cannot open shared object file: No such file or directory
> 
> onnxruntime_gpu: 1.15.0 cuda 12.1 cudnn: 8.9.2.26

I also encountered this problem。
Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

onnxruntime_gpu: 1.15.0
cuda 12.1
cudnn: 8.9.2.26

what's mean about `custom path in ldconfig`，Can you explain it in detail? and code examples，Thanks

**Comment by LeiWang1999** [comment]
I got the same issue under cuda 12.1.

**Comment by ramayer** [comment]
Same error here. 

Worked with cuda 11.x.

Fails with cuda 12.
