### ISSUE TITLE
Could not find an implementation for ConvInteger(10) node with name 'Conv_59_quant'

### ISSUE THREAD

**Issue by talhaanwarch** [microsoft/onnxruntime#12558]
I am trying to quantize slow_r50 model, but when i load it, I got this error
```
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_59_quant'
```
Code to reproduce
```
class OurModel(LightningModule):
    def __init__(self):
        super(OurModel,self).__init__()
        self.model = torch.hub.load('facebookresearch/pytorchvideo', 'slow_r50', pretrained=False)
    def forward(self,x):
        return self.model(x)

model=OurModel()


input_sample = torch.randn((1,3,30, 256,256))
model.to_onnx('onnx.onnx', input_sample,opset_version=11, export_params=True)

from onnxruntime.quantization import quantize_dynamic, QuantType
model_fp32 = 'onnx/{}.onnx'.format(vital)
model_quant = 'onnx/{}-quantized.onnx'.format(vital)
quantized_model = quantize_dynamic(model_fp32, model_quant)
```
Full Error
```
---------------------------------------------------------------------------
NotImplemented                            Traceback (most recent call last)
Input In [88], in <cell line: 1>()
----> 1 onnxruntime.InferenceSession('onnx/{}-quantized.onnx'.format(vital))

File ~/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:347, in InferenceSession.__init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    344 disabled_optimizers = kwargs["disabled_optimizers"] if "disabled_optimizers" in kwargs else None
    346 try:
--> 347     self._create_inference_session(providers, provider_options, disabled_optimizers)
    348 except ValueError:
    349     if self._enable_fallback:

File ~/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:395, in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    392     disabled_optimizers = set(disabled_optimizers)
    394 # initialize the C++ InferenceSession
--> 395 sess.initialize_session(providers, provider_options, disabled_optimizers)
    397 self._sess = sess
    398 self._sess_options = self._sess.session_options

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_59_quant'
```
Is there any chance of getting it implemented.

**Comment by yufenglee** [comment]
We are working on adding support of ConvInteger: https://github.com/microsoft/onnxruntime/pull/12424.
It dups with #12362

**Comment by chinmayjog13** [comment]
Any update on this?

When I try to create an inference session with the dynamically quantized model, I still get the above error.

```
>>> ort_session = ort.InferenceSession(int8_path, providers=['CPUExecutionProvider'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chinmay/anaconda3/envs/v_pytorch2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/chinmay/anaconda3/envs/v_pytorch2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_0_quant'

**Comment by trantuankhoi** [comment]
any update on this, i get an error:
`onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_0_quant'`

**Comment by ogencoglu** [comment]
Same issue for segformer model
`NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name '/segformer/encoder/patch_embeddings.0/proj/Conv_quant'`
