### ISSUE TITLE
Missing `onnx` dependency when running cli

### ISSUE THREAD

**Issue by reinvantveer** [microsoft/onnxruntime#12575]
To reproduce:
```
pipenv install onnxruntime  # creates a new virtualenv with only onnxruntime
pipenv run python -m onnxruntime.tools.check_onnx_model_mobile_usability --help
```
Output: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/path/to/your/virtualenv/lib/python3.9/site-packages/onnxruntime/tools/check_onnx_model_mobile_usability.py", line 11, in <module>
    from .mobile_helpers import check_model_can_use_ort_mobile_pkg, usability_checker  # noqa
  File "/path/to/your/virtualenv/lib/python3.9/site-packages/onnxruntime/tools/mobile_helpers/check_model_can_use_ort_mobile_pkg.py", line 12, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```
Believe this dependency should be added to `requirements.txt`

**Comment by reinvantveer** [comment]
Probably duplicate of https://github.com/microsoft/onnxruntime/issues/9966

**Comment by snnn** [comment]
Sorry, at this moment, we don't plan to fix it. I suggest you manually install onnx before using the script. The core functionality of ONNX Runtime doesn't depend on ONNX python package.

**Comment by Cameron1391** [comment]
fuck you
