### ISSUE TITLE
RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'Mul_5'

### ISSUE THREAD

**Issue by SineStriker** [microsoft/onnxruntime#12595]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 19044.1889
- ONNX Runtime installed from (binary):
- ONNX Runtime version: 1.12.1
- Python version: 3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.5
- GPU model and memory: Nvidia 2070 8G

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

+ Export options
````
# infer_ins is a derived class from torch.nn.Module
infer_ins.pe.to('cpu')
with torch.no_grad():
    mel_input = torch.rand(1, 968, 80)

    torch.onnx.export(
        infer_ins.pe,
        (
            mel_input
        ),
        "xiaoma_pe.onnx",
        verbose=True,
        input_names=["mel_input"],
        output_names=["f0"],
        dynamic_axes={
            "mel_input": {
                0: "batch_size",
                1: "frames",
                2: "num_mel_bin",
            },
            "f0": {
                0: "batch_size",
                1: "frames"
            }
        },
        opset_version=11,
    )
````

+ Forward function
````
def forward(self, mel_input=None):
    ret = {}
    mel_hidden = self.mel_prenet(mel_input)[1]
    if self.conv_layers > 0:
        mel_hidden = self.mel_encoder(mel_hidden)

    ret['pitch_pred'] = pitch_pred = self.pitch_predictor(mel_hidden)

    pitch_padding = mel_input.abs().sum(-1) == 0
    use_uv = hparams['pitch_type'] == 'frame' and hparams['use_uv']

    ret['f0_denorm_pred'] = denorm_f0(
        pitch_pred[:, :, 0], (pitch_pred[:, :, 1] > 0) if use_uv else None,
        hparams, pitch_padding=pitch_padding)
    return ret
````

+ Use case
````
mel_input = torch.rand(1, 967, 80)
pe2 = ort.InferenceSession("xiaoma_pe.onnx")
f0 = self.pe2.run(None, 
    {
        'mel_input': to_numpy(mel_out)
    }
)
````

**Expected behavior**
No Error.

**Screenshots**
````
2022-08-16 00:07:27.3322084 [E:onnxruntime:, sequential_executor.cc:368 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Mul node. Name:'Mul_5' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:503 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 967 by 968

Traceback (most recent call last):
  File "C:\Users\truef\Documents\GitHub\DiffSinger\onnx_test_hifigan_pe.py", line 99, in <module>
    out = infer_ins.infer_once(c)
  File "C:\Users\truef\Documents\GitHub\DiffSinger\inference\svs\base_svs_infer.py", line 235, in infer_once
    output = self.forward_model(inp)
  File "C:\Users\truef\Documents\GitHub\DiffSinger\onnx_test_hifigan_pe.py", line 68, in forward_model
    f0 = self.pe2.run(None,
  File "C:\CodeEnv\miniconda3\envs\dfs\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'Mul_5' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:503 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 967 by 968
````

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by f-izzat** [comment]
How did you solve this? @SineStriker
