### ISSUE TITLE
Confusing exception about supported types 

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [microsoft/onnxruntime#12648]
Hello,

I'm porting a TF saved model using command line tools, the export went just fine without any unsupported node message. I can load the model using the java api, without any issues. 
The problem appears when I try to run the model to get predictions, I get this message,
```
Caused by: ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: These types are unsupported - ONNX_TYPE_UNKNOWN, ONNX_TYPE_OPAQUE, ONNX_TYPE_SPARSETENSOR.
	at ai.onnxruntime.OrtSession.run(Native Method)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:295)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:238)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:207)
```
I understand that the runtime is not capable of working with these types. Maybe this is related to the Java package shipping a version of the ONNX runtime that is older than the one in Python?
I would have expected the error to appear earlier, like when converting the graph....

Any help more than welcome :)

**Urgency**
Not urgent.

**System information**
- Linux Ubuntu 18
- ONNX Runtime installed from: Java 1.12.1.
- ONNX Runtime version: probably also 1.12.1 ?
- Python version: Java 1.8.
- CUDA/cuDNN version: only using CPU at the moment.
- GPU model and memory: NVidia GeForce GTx, but I believe it's not being used.

**To Reproduce**
- Tricky.

- **Expected behavior**
I expect the runtime will be able to interpret all the types that come with a valid onnx graph.

**Comment by Craigacp** [comment]
What's the output of `session.getOutputInfo`?

I don't think any of the APIs support `ONNX_TYPE_UNKNOWN` as it's an error type.  As we don't have a way of wrapping up pointers it's hard to know what we'd do with `ONNX_TYPE_OPAQUE` in Java, so we're unlikely to support that till we migrate to the foreign function API. Sparse tensor support is in this PR #10653.

**Comment by mlourencoeb** [comment]
Any news about this issue? @pranavsharma were you able to solve it?

I am currently getting the same output with a quantized model. Other quantized model works just fine.

Thanks in advance, 

/M

**Comment by Craigacp** [comment]
If you can provide more model details that would be helpful. Netron should show the inputs and outputs of the model (which is what this error message relates to), along with their types and shapes.

**Comment by albertoandreottiATgmail** [comment]
hi guys, I'll try to check, it's been a while...

**Comment by mlourencoeb** [comment]
I fixed the issue by explicitly setting my output tensor layer during session.run().

Best,
/M
