### ISSUE TITLE
[Build] cmake error: list sub-command REMOVE_ITEM requires two or more arguments

### ISSUE THREAD

**Issue by diablodale** [microsoft/onnxruntime#12967]
### Describe the issue

building on windows with cmake 3.19 fails with `list sub-command REMOVE_ITEM requires two or more arguments`
This is due to a cmake "bug" in 3.19 and lower with the `list(REMOVE_ITEM...)` command.
Seen in other projects like https://github.com/microsoft/vcpkg/pull/23410
Easy fix in forthcoming PR

### Target platform

Windows (might be others)

### Build script

```
.\build.bat --update --build --skip_tests --cmake_generator "Visual Studio 16 2019" --config RelWithDebInfo --build_shared_lib --parallel --use_dml --use_cuda --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4" --cuda_version 11.4 --cudnn_home "C:\repos-nobackup\cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive" --use_tensorrt --tensorrt_home "C:\repos-nobackup\TensorRT-8.4.1.5"
```

### Error / output

```
...
--   Protobuf compiler         :
--   Protobuf includes         :
--   Protobuf libraries        :
--   BUILD_ONNX_PYTHON         : OFF
Use flatbuffers from submodule
-- CMAKE_CUDA_COMPILER_VERSION: 11.4.152
CMake Error at onnxruntime_graph.cmake:63 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  CMakeLists.txt:2007 (include)


-- Found CUDA headers at C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4/include
-- Found TensorRT headers at C:/repos-nobackup/TensorRT-8.4.1.5/include
-- Find TensorRT libs at C:/repos-nobackup/TensorRT-8.4.1.5/lib/nvinfer.lib;C:/repos-nobackup/TensorRT-8.4.1.5/lib/nvinfer_plugin.lib
-- Configuring incomplete, errors occurred!
See also "C:/repos-nobackup/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "C:/repos-nobackup/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "C:\repos-nobackup\onnxruntime\tools\ci_build\build.py", line 2744, in <module>
    sys.exit(main())
  File "C:\repos-nobackup\onnxruntime\tools\ci_build\build.py", line 2630, in main
    generate_build_tree(
  File "C:\repos-nobackup\onnxruntime\tools\ci_build\build.py", line 1240, in generate_build_tree
    run_subprocess(
  File "C:\repos-nobackup\onnxruntime\tools\ci_build\build.py", line 714, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\repos-nobackup\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', 'C:\\repos-nobackup\\onnxruntime\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=C:\\python39\\python.exe', '-DPYTHON_EXECUTABLE=C:\\python39\\python.exe', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_NUPHAR_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=ON', '-Donnxruntime_TENSORRT_PLACEHOLDER_BUILDER=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=ON', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_EAGER_MODE=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_NVCC_THREADS=0', '-Donnxruntime_TENSORRT_HOME=C:\\repos-nobackup\\TensorRT-8.4.1.5', '-Donnxruntime_USE_FULL_PROTOBUF=ON', '-DProtobuf_USE_STATIC_LIBS=ON', '-Donnxruntime_DEV_MODE=ON', '-Donnxruntime_USE_CUDA=ON', '-Donnxruntime_CUDA_VERSION=11.4', '-Donnxruntime_CUDA_HOME=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.4', '-Donnxruntime_CUDNN_HOME=C:\\repos-nobackup\\cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive', '-DONNX_USE_MSVC_STATIC_RUNTIME=OFF', '-Dprotobuf_MSVC_STATIC_RUNTIME=OFF', '-Dgtest_force_shared_crt=ON', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64,cuda=11.4', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo']' returned non-zero exit status 1
```

### Visual Studio Version

16.11.18

**Comment by diablodale** [comment]
github form didn't have setup field....

* Microsoft Windows [Version 10.0.19044.2006]
* VS2019 Community v16.11.18
* Cmake 3.19.1

**Comment by adrianlizarraga** [comment]
@diablodale Thanks again for reporting this and providing workarounds. 

We can now close this PR because the minimum required version of CMake was recently [updated to 3.24](https://github.com/microsoft/onnxruntime/pull/13569).

**Comment by diablodale** [comment]
Sure, the forced newer cmake without its bug should also resolve this issue
