### ISSUE TITLE
This will raise ValueError since the tensor could be a numpy array, you can't use if on numpy arrays with more than one value

### ISSUE THREAD

**Issue by BruceDai003** [microsoft/onnxruntime#13054]
https://github.com/microsoft/onnxruntime/blob/2f9b358d16885c8330eaa34a932315e3b176082c/onnxruntime/python/tools/quantization/qdq_loss_debug.py#L170

This will raise ValueError since the tensor could be a numpy array, you can't use if on numpy arrays with more than one value

For example:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/liwei.dai/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/liwei.dai/tests/framework/paddleocr/tools/onnx_quant.py", line 500, in <module>
    main()
  File "/home/liwei.dai/tests/framework/paddleocr/tools/onnx_quant.py", line 166, in main
    results = create_activation_matching(qdq_activations, float_activations)
  File "/opt/apps/local/lib/python3/dist-packages/onnxruntime/quantization/qdq_loss_debug.py", line 223, in create_activation_matching
    _add_pre_post_qdq_pair(qdq_cmp, pre_name, pre_qdq_tensors, post_qdq_tensors)
  File "/opt/apps/local/lib/python3/dist-packages/onnxruntime/quantization/qdq_loss_debug.py", line 170, in _add_pre_post_qdq_pair
    if post_qdq_tensors and pre_qdq_tensors:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Maybe change it to ?
```
if post_qdq_tensors is not None and pre_qdq_tensors is not None:
```

**Comment by BruceDai003** [comment]
Similary issue here: https://github.com/microsoft/onnxruntime/blob/2f9b358d16885c8330eaa34a932315e3b176082c/onnxruntime/python/tools/quantization/qdq_loss_debug.py#L232
