### ISSUE TITLE
Unable to access memory during inference

### ISSUE THREAD

**Issue by tulasiram58827** [microsoft/onnxruntime#13182]
### Describe the issue

Hi, While execution session.run() I am getting SEGV errors. I guess it is unable to read the data. What are the validations I can do to confirm input tensors are fine?

```
auto output_tensors = m_ort_session.get()->Run(Ort::RunOptions{nullptr}, m_input_node_names.data(), &input_tensor, m_input_node_names.size(), 
                                                   m_input_node_names.data(), m_input_node_names.size());
 ```

```
ASAN:DEADLYSIGNAL
=================================================================
==15114==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f76068fc8f0 bp 0x7f76001fbc60 sp 0x7f76001fbae0 T7)
==15114==The signal is caused by a READ memory access.
==15114==Hint: address points to the zero page.
    #0 0x7f76068fc8ef  (lib/libonnxruntime.so.1.11.1+0x1ad8ef)
    #1 0x5b4c39 in Ort::Session::Run(Ort::RunOptions const&, char const* const*, Ort::Value const*, unsigned long, char const* const*, Ort::Value*, unsigned long) include/onnxruntime_cxx_inline.h:578
    #2 0x5b4c39 in Ort::Session::Run(Ort::RunOptions const&, char const* const*, Ort::Value const*, unsigned long, char const* const*, unsigned long) include/onnxruntime_cxx_inline.h:569
    #3 0x5b4c39 in dsa::cloud::ONNXExecutor::execute(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, dsa::inference::UserBuffer const*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dsa::inference::UserBuffer const*> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, dsa::inference::UserBuffer*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, dsa::inference::UserBuffer*> > > const&) 
```

I cannot attach model/full code. Please let me know if there are any ways to debug the issue. I am just expecting some pointers to debug.

Thank you

### To reproduce

It cannot be reproducable from your end as I cannot provide the model. Feel free to close the issue if this is a mandatory requirement

### Platform

Linux

### OS Version

18..04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.11

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

**Comment by tulasiram58827** [comment]
Issue resolved. It is because of accessing bad memory
