### ISSUE TITLE
[Build] Window build fails with C2220: the following warning is treated as an error

### ISSUE THREAD

**Issue by Boscillator** [microsoft/onnxruntime#13253]
### Describe the issue

Hello!

I'm attempting to build on window following the instructions here: https://onnxruntime.ai/docs/build/inferencing.html

After cloning I run `.\build.bat --config RelWithDebInfo --build_shared_lib --parallel` and the build is failing. It appears to be a problem with the warn level set to high. Here is the error and warnings.

```
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(116,1): error C2220: the followin
g warning is treated as an error [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_provide
rs.vcxproj]
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(116,1): warning C4805: '|': unsaf
e mix of type 'bool' and type 'int' in operation [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onn
xruntime_providers.vcxproj]
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(144,1): warning C4805: '&': unsaf
e mix of type 'bool' and type 'int' in operation [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onn
xruntime_providers.vcxproj]
```

After these errors the build continues for a bit and then errors with:
```
Traceback (most recent call last):
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 2812, in <module>
    sys.exit(main())
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\oscil\Documents\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\oscil\\Documents\\onnxruntime\\\\build\\Windows\\RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '/maxcpucount:12', '/nodeReuse:False']' returned non-zero exit status 1.
```

Earlier in the build I also get this error:
```
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\optimizer\conv_add_act_fusion.cc(274,1): error C2280: 'onnxruntim
e::SelectorActionRegistry::SelectorActionRegistry(void) noexcept': attempting to reference a deleted function [C:\Users
\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_optimizer.vcxproj]
```

Any ideas on what could be going wrong? This is on a fresh install of Visual Studio 2017 running inside the `x86_64 Cross Tools Command Prompt for VS 2017`

Thanks in advance!

### Urgency

Not particularly urgent.

### Target platform

Windows

### Build script

`.\build.bat --config RelWithDebInfo --build_shared_lib --parallel`

### Error / output

```
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(116,1): error C2220: the followin
g warning is treated as an error [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_provide
rs.vcxproj]
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(116,1): warning C4805: '|': unsaf
e mix of type 'bool' and type 'int' in operation [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onn
xruntime_providers.vcxproj]
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(144,1): warning C4805: '&': unsaf
e mix of type 'bool' and type 'int' in operation [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onn
xruntime_providers.vcxproj]
```

```
Traceback (most recent call last):
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 2812, in <module>
    sys.exit(main())
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\oscil\Documents\onnxruntime\\tools\ci_build\build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\oscil\Documents\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\oscil\\Documents\\onnxruntime\\\\build\\Windows\\RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '/maxcpucount:12', '/nodeReuse:False']' returned non-zero exit status 1.
```

### Visual Studio Version

VS 2017

**Comment by cloudhan** [comment]
Can you try out `.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_extra_defines onnxruntime_DEV_MODE=OFF`

**Comment by ytaous** [comment]
Maybe try VS 2019?

**Comment by Boscillator** [comment]
@cloudhan I tried that and it made the errors related to the warnings go away. However, the build still fails with
```
C:\Users\oscil\Documents\onnxruntime\onnxruntime\core\optimizer\selectors_actions\selector_action_transformer.cc(75,32)
: error C2280: 'onnxruntime::SelectorActionRegistry::SelectorActionRegistry(const onnxruntime::SelectorActionRegistry &
)': attempting to reference a deleted function [C:\Users\oscil\Documents\onnxruntime\build\Windows\RelWithDebInfo\onnxr
untime_optimizer.vcxproj]
```

@ytaous I tried that and it gave the same errors.

**Comment by ytaous** [comment]
see - https://github.com/microsoft/onnxruntime/issues/10235

**Comment by Boscillator** [comment]
Looks like it's working. Thanks!
