### ISSUE TITLE
[ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: the graph is not acyclic. 

### ISSUE THREAD

**Issue by aneesh1514** [microsoft/onnxruntime#13322]
### Describe the issue

Failed to import the mobilenet-SSD based model on onnxruntime using tidl backend. **The model loads properly with CPU provider.**

Preliminary subgraphs created = 2
Running runtimes graphviz - /data/home/paneesh/edgeai-tidl-tools/tidl_tools/tidl_graphVisualiser_runtimes.out ../../../model-artifacts//fd//allowedNode.txt ../../../model-artifacts//fd//tempDir/graphvizInfo.txt ../../../model-artifacts//fd//tempDir/runtimes_visualization.svg
Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "onnxrt_ep.py", line 174, in run_model
sess = rt.InferenceSession(config['model_path'] ,providers=EP_list, provider_options=[delegate_options, {}], sess_options=so)
File "/data/home/paneesh/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in init
self._create_inference_session(providers, provider_options)
File "/data/home/paneesh/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 315, in _create_inference_session
sess.initialize_session(providers, provider_options)
**onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: the graph is not acyclic.**

The onnx model is converted from a PyTorch model.

### To reproduce

NA

### Platform

Linux

### OS Version

18.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.7.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Other / Unknown

**Comment by tianleiwu** [comment]
@aneesh1514 , Could  you disable graph optimization using session options, and try again? If the problem still exist, it is likely that  your ONNX model is invalid, and you can post the issue to pytorch. If the problem disappear, please attach the onnx model, and we can take a look.

**Comment by RyanUnderhill** [comment]
@aneesh1514  When you say "The model loads properly with CPU provider." what do you mean? The OnnxRuntime CPU provider outside of Python?

**Comment by aneesh1514** [comment]
@RyanUnderhill , The model is working with CPUExecutionProvider

**Comment by tianleiwu** [comment]
@aneesh1514, is it possible to share the onnx model?  If you do not want to share weights, you can save the model as external data format with onnx.save API, and only share the .onnx file but not other files.

**Comment by birdflyto** [comment]
> @RyanUnderhill , The model is working with CPUExecutionProvider

Hi brother,  I met the same error with yolov7.onnx，have you find the reason why the error appear in using TI backend? Thanks！

**Comment by tianleiwu** [comment]
@birdflyto, could you share the onnx model and a script that could reproduce the error?
