### ISSUE TITLE
UpSample op converted through tf2onnx in opset version 9 gives error: Scale value should be greater than or equal to 1.

### ISSUE THREAD

**Issue by johnyang-nv** [microsoft/onnxruntime#13457]
### Describe the issue

I have two onnx files with opset versions 9 and 13 that converted Resize operation of Tensorflow 
```
input = tf.compat.v1.placeholder(tf.float32, [None, 300, 480, 3], name='input_')
output = tf.image.resize(input, [300, 240], name='output_')
```
which are converted with tf2onnx.

When trying to run onnxruntime.InferenceSession two files, 
while one with opset version 13 has no problems, 
one with opset version 9 fails with the scalevalidation error 

yields the following error:
```
>>> ort_sess_op9 = ort.InferenceSession('upsample_graph_opset9.onnx')
2022-10-26 02:11:25.257567960 [E:onnxruntime:, inference_session.cc:1500 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:285 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:285 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.
```

### To reproduce

onnxruntime ver: 1.13.1

Define the TF graph and save.
```
input = tf.compat.v1.placeholder(tf.float32, [None, 300, 480, 3], name='input_')
output = tf.image.resize(input, [300, 240], name='output_')
result = output
# creating a tensorflow graph
with tf.compat.v1.Session() as sess:        
    tf.compat.v1.train.write_graph(sess.graph_def, '', 'upsample_graph.pbtxt', as_text=False)
```
load the graph and save it as onnx with tf2onnx
```
python -m tf2onnx.convert --input /workspace/upsample_graph.pbtxt --inputs "input_:0" --outputs "output_/ResizeBilinear:0" --output  upsample_graph.onnx --opset 9 --verbose
```

yields the following error:
```
>>> ort_sess_op9 = ort.InferenceSession('upsample_graph_opset9.onnx')
2022-10-26 02:11:25.257567960 [E:onnxruntime:, inference_session.cc:1500 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:285 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:285 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by fdwr** [comment]
ONNX's [resampling operator Resize](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize) wasn't introduced until opset 10, meaning an opset 9 target can only resort to the nearest approximate match Upsample, which [by the spec](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Upsample-9) "It takes value greater than or equal to 1".

**Comment by johnyang-nv** [comment]
Understood. Thank you!
