### ISSUE TITLE
 input_shape of QLinearSoftmax must be existed

### ISSUE THREAD

**Issue by EmreOzkose** [microsoft/onnxruntime#13478]
Hi, I exported a Pytorch model to onnx. It works fine. Then I tried to quantize onnx model and got different outputs (tested with torch.all() and even atol=1e-1 is different). During these tests, my version onnxruntime was 1.12.1. Then I switch to 1.13.1. I quantized onnx model with 

```
calibration_data_folder = ...
input_model = "encoder.onnx"

audio_extension="flac"
num_files_to_process = 10
wav_data_reader = WavDataReader(calibration_data_folder, audio_extension, 80, num_files_to_process)

output_qt_model = f"quantized.onnx"
quantize_static(input_model,
                output_qt_model,
                wav_data_reader,
                quant_format=QuantFormat.QOperator, # QOperator QDQ
                optimize_model=True,
                activation_type=QuantType.QUInt8,
                weight_type=QuantType.QUInt8,
                calibrate_method=CalibrationMethod.MinMax,
                extra_options={"ActivationSymmetric": True, "WeightSymmetric": True}
                )
```

Above code works with ort 1.12.1 , but gives below error with ort 1.13.1

```
(onnx) user@server:/path/to/onnx_optimization$ python encoder_optimization.py
ort version: 1.13.1
2022-10-27 17:37:25.370007128 [E:onnxruntime:, inference_session.cc:1500 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/contrib_ops/cpu/quantization/qlinear_softmax.cc:74 onnxruntime::contrib::QLinearSoftmax::QLinearSoftmax(const onnxruntime::OpKernelInfo&) x_shape != nullptr && x_shape->dim_size() > 0 was false. input_shape of QLinearSoftmax must be existed

Traceback (most recent call last):
  File "encoder_optimization.py", line 24, in <module>
    encoder_optimized = ort.InferenceSession(optimized_path)
  File "/path/to/anaconda3/envs/onnx/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/path/to/anaconda3/envs/onnx/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/contrib_ops/cpu/quantization/qlinear_softmax.cc:74 onnxruntime::contrib::QLinearSoftmax::QLinearSoftmax(const onnxruntime::OpKernelInfo&) x_shape != nullptr && x_shape->dim_size() > 0 was false. input_shape of QLinearSoftmax must be existed

```

Should I add something to switch to 1.13.1 ?

**Comment by yufenglee** [comment]
@wejoncy, please help take a look at this issue.

@EmreOzkose, you can try excluding SoftMax from quantization by specifying op_types_to_quantize to bypass the issue. And for a transformer model, it is recommended to use dynamic_quantize on CPU.

**Comment by wejoncy** [comment]
@EmreOzkose Could you share me the quantized model? Will try to reproduce this issue and fix as soon as possible.

**Comment by EmreOzkose** [comment]
I am sharing onnx file: https://sestek-my.sharepoint.com/:u:/p/yunusemre_ozkose/Ee4JT6Ba0vpJjoIj487hCr0BiWF_DZ0fIdfvkwhJfq5ngA?e=4JHYaA

My optimization code is:
```
import os
import numpy as np
import onnxruntime as ort
from onnxruntime.quantization import quantize_static, CalibrationDataReader, QuantType, QuantFormat, CalibrationMethod


class WavDataReader(CalibrationDataReader):
    def __init__(self):
        self.preprocess_flag = True
        self.enum_data_dicts = []

    def get_next(self):
        if self.preprocess_flag:
            self.preprocess_flag = False
            feature = np.random.rand(1, 500, 80).astype('float32')
            feature_len = np.array([500])
            self.enum_data_dicts = iter([{'x': feature, 'x_lens': feature_len}])

        return next(self.enum_data_dicts, None)


input_model = "encoder_en.onnx"
wav_data_reader = WavDataReader()

print(ort.__version__)

output_qt_model = f"exported_models/encoder_en_static_qt_rand.onnx"
quantize_static(input_model,
                output_qt_model,
                wav_data_reader,
                quant_format=QuantFormat.QOperator, # QOperator QDQ
                optimize_model=True,
                activation_type=QuantType.QUInt8,
                weight_type=QuantType.QUInt8,
                calibrate_method=CalibrationMethod.MinMax,
                extra_options={"ActivationSymmetric": True, "WeightSymmetric": True}
                )


print('ONNX full precision model size (MB):', os.path.getsize(input_model)/(1024*1024))
print('ONNX quantized model size (MB):', os.path.getsize(output_qt_model)/(1024*1024))
```

**Comment by wejoncy** [comment]
I got what happend with this issue.

The input shape of `Softmax` does be dynamic and can be known at runtime, so it's normal that I get a null_ptr at initializing.

I have removed the check in Ctor of `softmax`, then it won't be crashed.

But I can't really run this model, even with all zero input. @EmreOzkose Could you share the code piece of how to feed this model or build this branch https://github.com/microsoft/onnxruntime/tree/fix_issue/13478 and try to run it again? Thanks
