### ISSUE TITLE
[Build] Failed to build ort shared library in win7 with cuda

### ISSUE THREAD

**Issue by seungtaek94** [microsoft/onnxruntime#13474]
### Describe the issue

Hi.

I tried to build onnxruntime shared library for c++ on win7 sp1 system with cuda.

But its failed with below message.

My Eviroments

- Onnxruntime: 1.12.1
- Os: win7 sp1 pro
- CMake: 3.24.2
- CUDA: 11.4.1
- Python: 3.8.0

### Target platform

Win7

### Build script

```
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --use_cuda --cuda_version 11.4 --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4"
```

### Error / output

<details>
<summary>some build log</summary>

```
ime::BFCArena::Extend] Extended allocation by 2097152 bytes.
5: 2022-10-27 14:54:11.0258719 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 3145728
5: 2022-10-27 14:54:11.0258844 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 000000002E640060 to 000000002E840060
5: 2022-10-27 14:54:11.0263368 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:12 (requ
ested) num_bytes: 2048000 (actual) rounded_bytes:2048000
5: 2022-10-27 14:54:11.0263567 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 4194304 bytes.
5: 2022-10-27 14:54:11.0263698 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 7340032
5: 2022-10-27 14:54:11.0263827 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 0000000038D90060 to 0000000039190060
5: 2022-10-27 14:54:11.0272170 [I:onnxruntime:, session_state_utils.cc:268 onnxr
untime::session_state_utils::SaveInitializedTensors] Done saving initialized ten
sors
5: 2022-10-27 14:54:11.0275753 [I:onnxruntime:, inference_session.cc:1518 onnxru
ntime::InferenceSession::Initialize] Session successfully initialized.
5: 2022-10-27 14:54:11.0332917 [I:onnxruntime:, sequential_executor.cc:176 onnxr
untime::SequentialExecutor::Execute] Begin execution
5: 2022-10-27 14:54:11.0333148 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:13 (requ
ested) num_bytes: 3154176 (actual) rounded_bytes:3154176
5: 2022-10-27 14:54:11.0333355 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 8388608 bytes.
5: 2022-10-27 14:54:11.0333484 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 15728640
5: 2022-10-27 14:54:11.0333615 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 000000003C170060 to 000000003C970060
5: Running simple inference with default provider
5: 2022-10-27 14:54:11.0383260 [I:onnxruntime:, inference_session.cc:342 onnxrun
time::InferenceSession::ConstructorCommon] Using global/env threadpools since us
e_per_session_threads_ is false
5: 2022-10-27 14:54:11.0425664 [I:onnxruntime:, inference_session.cc:1246 onnxru
ntime::InferenceSession::Initialize] Initializing session.
5: 2022-10-27 14:54:11.0425962 [I:onnxruntime:, inference_session.cc:1283 onnxru
ntime::InferenceSession::Initialize] Adding default CPU execution provider.
5: 2022-10-27 14:54:11.0426160 [I:onnxruntime:Default, bfc_arena.cc:26 onnxrunti
me::BFCArena::BFCArena] Creating BFCArena for Cpu with following configs: initia
l_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_c
hunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strateg
y: 0
5: 2022-10-27 14:54:11.0426383 [V:onnxruntime:Default, bfc_arena.cc:62 onnxrunti
me::BFCArena::BFCArena] Creating 21 bins of max chunk size 256 to 268435456
5: 2022-10-27 14:54:11.0433364 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime
::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
5: 2022-10-27 14:54:11.0435822 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime
::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
5: 2022-10-27 14:54:11.0437879 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0438145 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0438586 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0438911 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0439095 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0439279 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0439460 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0439644 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0439828 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440007 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440188 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440366 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440544 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440728 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0440907 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0441088 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0441269 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0477103 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0477310 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0477497 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0477681 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0478020 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0478462 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0478771 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0478956 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0479137 [V:onnxruntime:, selector_action_transformer.cc:1
28 onnxruntime::MatchAndProcess] Matched Conv
5: 2022-10-27 14:54:11.0562438 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire2/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0562742 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire2/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0562900 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'conv1_w_0'. It is no
 longer used by any node.
5: 2022-10-27 14:54:11.0563049 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire3/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563195 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire6/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563338 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire2/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563479 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire7/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563622 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire3/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563759 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire3/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0563897 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire4/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564043 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire4/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564180 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire4/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564317 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire8/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564458 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire5/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564595 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire5/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0564735 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire7/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0594304 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire5/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0594625 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire6/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0594900 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire6/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595037 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire9/squeeze1x1_w_0
'. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595180 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire7/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595315 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire8/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595452 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire8/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595587 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire9/expand1x1_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595721 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'fire9/expand3x3_w_0'
. It is no longer used by any node.
5: 2022-10-27 14:54:11.0595858 [I:onnxruntime:, graph.cc:3497 onnxruntime::Graph
::CleanUnusedInitializersAndNodeArgs] Removing initializer 'conv10_w_0'. It is n
o longer used by any node.
5: 2022-10-27 14:54:11.0599608 [V:onnxruntime:, session_state.cc:1186 onnxruntim
e::VerifyEachNodeIsAssignedToAnEp] Node placements
5: 2022-10-27 14:54:11.0599777 [V:onnxruntime:, session_state.cc:1188 onnxruntim
e::VerifyEachNodeIsAssignedToAnEp] All nodes have been placed on [CPUExecutionPr
ovider].
5: 2022-10-27 14:54:11.0600470 [V:onnxruntime:, session_state.cc:81 onnxruntime:
:SessionState::CreateGraphInfo] SaveMLValueNameIndexMapping
5: 2022-10-27 14:54:11.0600914 [V:onnxruntime:, session_state.cc:127 onnxruntime
::SessionState::CreateGraphInfo] Done saving OrtValue mappings.
5: 2022-10-27 14:54:11.0603483 [I:onnxruntime:, session_state_utils.cc:140 onnxr
untime::session_state_utils::SaveInitializedTensors] Saving initialized tensors.

5: 2022-10-27 14:54:11.0603784 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:4 (reque
sted) num_bytes: 4096 (actual) rounded_bytes:4096
5: 2022-10-27 14:54:11.0603997 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 1048576 bytes.
5: 2022-10-27 14:54:11.0604132 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 1048576
5: 2022-10-27 14:54:11.0604263 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 000000001EE60060 to 000000001EF60060
5: 2022-10-27 14:54:11.0606052 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:11 (requ
ested) num_bytes: 589824 (actual) rounded_bytes:589824
5: 2022-10-27 14:54:11.0606247 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 2097152 bytes.
5: 2022-10-27 14:54:11.0606370 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 3145728
5: 2022-10-27 14:54:11.0606496 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 000000002E640060 to 000000002E840060
5: 2022-10-27 14:54:11.0610908 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:12 (requ
ested) num_bytes: 2048000 (actual) rounded_bytes:2048000
5: 2022-10-27 14:54:11.0701604 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 4194304 bytes.
5: 2022-10-27 14:54:11.0701756 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 7340032
5: 2022-10-27 14:54:11.0701887 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 0000000038D90060 to 0000000039190060
5: 2022-10-27 14:54:11.0710698 [I:onnxruntime:, session_state_utils.cc:268 onnxr
untime::session_state_utils::SaveInitializedTensors] Done saving initialized ten
sors
5: 2022-10-27 14:54:11.0715029 [I:onnxruntime:, inference_session.cc:1518 onnxru
ntime::InferenceSession::Initialize] Session successfully initialized.
5: 2022-10-27 14:54:11.0715458 [I:onnxruntime:, sequential_executor.cc:176 onnxr
untime::SequentialExecutor::Execute] Begin execution
5: 2022-10-27 14:54:11.0715663 [I:onnxruntime:Default, bfc_arena.cc:317 onnxrunt
ime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:13 (requ
ested) num_bytes: 3154176 (actual) rounded_bytes:3154176
5: 2022-10-27 14:54:11.0715865 [I:onnxruntime:Default, bfc_arena.cc:197 onnxrunt
ime::BFCArena::Extend] Extended allocation by 8388608 bytes.
5: 2022-10-27 14:54:11.0715996 [I:onnxruntime:Default, bfc_arena.cc:200 onnxrunt
ime::BFCArena::Extend] Total allocated bytes: 15728640
5: 2022-10-27 14:54:11.0716125 [I:onnxruntime:Default, bfc_arena.cc:203 onnxrunt
ime::BFCArena::Extend] Allocated memory at 000000003C170060 to 000000003C970060
5: [       OK ] CApiTestGlobalThreadPoolsWithProviders/CApiTestGlobalThreadPools
WithProvider.simple3/4 (66 ms)
5: [----------] 15 tests from CApiTestGlobalThreadPoolsWithProviders/CApiTestGlo
balThreadPoolsWithProvider (2506 ms total)
5:
5: [----------] Global test environment tear-down
5: [==========] 15 tests from 1 test suite ran. (2506 ms total)
5: [  PASSED  ] 15 tests.
5/6 Test #5: onnxruntime_global_thread_pools_test ...   Passed    3.01 sec
test 6
    Start 6: onnxruntime_api_tests_without_env

6: Test command: C:\Users\rexgen\Desktop\onnxruntime\build\Windows\RelWithDebInf
o\RelWithDebInfo\onnxruntime_api_tests_without_env.exe "--gtest_output=xml:C:\Us
ers\rexgen\Desktop\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxr
untime_api_tests_without_env.exe.RelWithDebInfo.results.xml"
6: Working Directory: C:/Users/rexgen/Desktop/onnxruntime/build/Windows/RelWithD
ebInfo/RelWithDebInfo
6: Test timeout computed to be: 10800
6: [==========] Running 1 test from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 1 test from TestSessionOptions
6: [ RUN      ] TestSessionOptions.SetIntraOpNumThreadsWithoutEnv
6: [       OK ] TestSessionOptions.SetIntraOpNumThreadsWithoutEnv (0 ms)
6: [----------] 1 test from TestSessionOptions (0 ms total)
6:
6: [----------] Global test environment tear-down
6: [==========] 1 test from 1 test suite ran. (0 ms total)
6: [  PASSED  ] 1 test.
6/6 Test #6: onnxruntime_api_tests_without_env ......   Passed    0.01 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =  71.65 sec

The following tests FAILED:
          1 - onnxruntime_test_all (Failed)
Errors while running CTest
Output from these tests are in: C:/Users/rexgen/Desktop/onnxruntime/build/Window
s/RelWithDebInfo/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Traceback (most recent call last):
  File "C:\Users\rexgen\Desktop\onnxruntime\\tools\ci_build\build.py", line 2744
, in <module>
    sys.exit(main())
  File "C:\Users\rexgen\Desktop\onnxruntime\\tools\ci_build\build.py", line 2666
, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "C:\Users\rexgen\Desktop\onnxruntime\\tools\ci_build\build.py", line 1807
, in run_onnxruntime_tests
    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)
  File "C:\Users\rexgen\Desktop\onnxruntime\\tools\ci_build\build.py", line 714,
 in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=m
y_env)
  File "C:\Users\rexgen\Desktop\onnxruntime\tools\python\util\run.py", line 49,
in run
    completed_process = subprocess.run(
  File "C:\Users\rexgen\AppData\Local\Programs\Python\Python38\lib\subprocess.py
", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\ctest.E
XE', '--build-config', 'RelWithDebInfo', '--verbose', '--timeout', '10800']' ret
urned non-zero exit status 8.
```

</details>

### Visual Studio Version

Visual Studio 16 2019

### GCC / Compiler Version

19.29.30146.0

**Comment by seungtaek94** [comment]
Sorry. It's success to build shared lib but failed some test. But it is work fine.
