### ISSUE TITLE
[Build] Failed to build on Linux with TensorRT EP because NvInferVersion.h not found

### ISSUE THREAD

**Issue by CanyonWind** [microsoft/onnxruntime#13479]
### Describe the issue

Hi, the title says pretty much of the issue. When building with TensorRT EP, it failed one of the TensorRT tests (check below error message for details), saying `NvInferVersion.h: No such file or directory`.

But the `NvInferVersion.h` is correctly located at the TensorRT include folder, which has been identified by the build script: 
```
-- Abseil source dir:/home/username/onnxruntime/build/Linux/Debug/_deps/abseil_cpp-src                                                                                                                 
-- Looking for clock_gettime in rt                                                                 
-- Looking for clock_gettime in rt - found                                                                                                                                                            
-- Found TensorRT headers at /usr/local/TensorRT-8.4.3.1/include                                                                                                                                      
-- Find TensorRT libs at /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so;/usr/local/TensorRT-8.4.3.1/lib/libnvinfer_plugin.so;/usr/local/TensorRT-8.4.3.1/lib/libnvonnxparser.so                        
-- Configuring done                                                                                
-- Generating done   
```

```
(base) username@ip-address:~/onnxruntime$ ls /usr/local/TensorRT-8.4.3.1/include/
NvCaffeParser.h  NvInferConsistency.h      NvInferImpl.h        NvInferPlugin.h       NvInferRuntime.h        NvInferSafeRuntime.h  NvOnnxConfig.h  NvUffParser.h
NvInfer.h        NvInferConsistencyImpl.h  NvInferLegacyDims.h  NvInferPluginUtils.h  NvInferRuntimeCommon.h  NvInferVersion.h      NvOnnxParser.h  NvUtils.h
```

Help would be appreciated.

### Urgency

We have a **super urgent** deployment task relying on ORT-TensorRT.

### Target platform

Linux

### Build script

```
./build.sh --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT-8.4.3.1
```

### Error / output

```
In file included from /home/username/onnxruntime/onnxruntime/test/providers/tensorrt/tensorrt_basic_test.cc:11:                                                                                        
/home/username/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider_utils.h:12:10: fatal error: NvInferVersion.h: No such file or directory                                     
   12 | #include <NvInferVersion.h>                                                                                                                                                                   
      |          ^~~~~~~~~~~~~~~~~~                                                                                                                                                                   
compilation terminated.                                                                                                                                                                               
make[2]: *** [CMakeFiles/onnxruntime_test_all.dir/build.make:1140: CMakeFiles/onnxruntime_test_all.dir/home/username/onnxruntime/onnxruntime/test/providers/tensorrt/tensorrt_basic_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2139: CMakeFiles/onnxruntime_test_all.dir/all] Error 2                                                                                                             
make: *** [Makefile:166: all] Error 2                                                              
Traceback (most recent call last):                                                                 
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 2807, in <module>                                                                                                                    
    sys.exit(main())                                                                               
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 2721, in main                                                                                                                        
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)                                                                                                               
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 1347, in build_targets                                                                                                               
    run_subprocess(cmd_args, env=env)                                                              
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 738, in run_subprocess                                                                                                               
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)                                                                                                                
  File "/home/username/onnxruntime/tools/python/util/run.py", line 49, in run                                                                                                                          
    completed_process = subprocess.run(                                                            
  File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run                                                                                                                                     
    raise CalledProcessError(retcode, process.args,                                                
subprocess.CalledProcessError: Command '['/sensei-fs/users/username/setup/trt_dependencies/cmake-3.24.2-linux-x86_64/bin/cmake', '--build', '/home/username/onnxruntime/build/Linux/Debug', '--config', 
'Debug']' returned non-zero exit status 2.
```

**Comment by jywu-msft** [comment]
looks like you are using TensorRT 8.4.3.1
can  you try building without the --use_tensorrt_builtin_parser option?

**Comment by CanyonWind** [comment]
Thanks, will give it a try. 

Some more info — I built ORT with TensorRT 8.4.3.1 about one month ago and it worked well then. While I tried to checkout to an older commit and build that version, it throws an error now saying `1 - onnxruntime_test_all (Timeout)`. Any idea why it happened? Is it safe to add `--skip_tests` flag when build with TensorRT? thx

```
1: [       OK ] PadOpTest/0.Pad_Reflect_3D_Inner_No_Padding (8487 ms)                                                                                                                                        
1: [ RUN      ] PadOpTest/0.Pad_Reflect_3D_Last_Pad_Slice_Inner_No_Padding                                                                                                                                   
1/3 Test #1: onnxruntime_test_all .............***Timeout 10801.10 sec                                                                                                                                       
test 2                                                                                                                                                                                                       
    Start 2: onnx_test_pytorch_converted                                                                                                                                                                     
                                                                                                                                                                                                             
2: Test command: /home/username/onnxruntime/build/Linux/Debug/onnx_test_runner "/home/username/onnxruntime/cmake/external/onnx/onnx/backend/test/data/pytorch-converted"                                       
2: Working Directory: /home/username/onnxruntime/build/Linux/Debug                                                                                                                                            
2: Test timeout computed to be: 10800                                                                                                                                                                        
2: 2022-10-27 21:30:34.064282355 [E:onnxruntime:Default, testcase_driver.cc:39 RunParallel] Running tests in parallel: at most 59 models at any time                                                         
2: 2022-10-27 21:30:36.554505833 [E:onnxruntime:Default, testcase_driver.cc:61 RunModelsAsync] Running tests finished. Generating report                                                                     
2: result:                                                                                                                                                                                                   
2:      Models: 59                                                                                                                                                                                           
2:      Total test cases: 59                                                                                                                                                                                 
2:              Succeeded: 59                                                                                                                                                                                
2:              Not implemented: 0                                                                                                                                                                           
2:              Failed: 0                                                                                                                                                                                    
2:      Stats by Operator type:                                                                                                                                                                              
2:              Not implemented(0):                                                                   
2:              Failed:                                                                               
2: Failed Test Cases:                                                                                 
2/3 Test #2: onnx_test_pytorch_converted ......   Passed    5.63 sec           
test 3                                                                                                                                                                                                       
    Start 3: onnx_test_pytorch_operator                                                   
3: Test command: /home/username/onnxruntime/build/Linux/Debug/onnx_test_runner "/home/username/onnxruntime/cmake/external/onnx/onnx/backend/test/data/pytorch-operator"                                        
3: Working Directory: /home/username/onnxruntime/build/Linux/Debug                                                                                                                                            
3: Test timeout computed to be: 10800                                                                                                                                                                        
3: 2022-10-27 21:30:36.642262844 [E:onnxruntime:Default, testcase_driver.cc:39 RunParallel] Running tests in parallel: at most 24 models at any time                                                         
3: 2022-10-27 21:30:38.012276933 [E:onnxruntime:Default, testcase_driver.cc:61 RunModelsAsync] Running tests finished. Generating report                                                                     
3: result:                                                                                                                                                                                                   
3:      Models: 24                                                                                                                                                                                           
3:      Total test cases: 24                                                                                                                                                                                 
3:              Succeeded: 24                                                                                                                                                                                
3:              Not implemented: 0                                                                                                                                                                           
3:              Failed: 0                                                                                                                                                                                    
3:      Stats by Operator type:                                                                                                                                                                              
3:              Not implemented(0):                                                                                                                                                                          
3:              Failed:                                                                                                                                                                                      
3: Failed Test Cases:                                                                                                                                                                                        
3/3 Test #3: onnx_test_pytorch_operator .......   Passed    1.45 sec                                                                                                                                         
                                                                                                                                                                                                             
67% tests passed, 1 tests failed out of 3                                                                                                                                                                    
                                                                                                                                                                                                             
Total Test time (real) = 10808.26 sec                                                                                                                                                                        
                                                                                                                                                                                                             
The following tests FAILED:                                                                                                                                                                                  
          1 - onnxruntime_test_all (Timeout)                                                                                                                                                                 
Errors while running CTest                                                                                                                                                                                   
Output from these tests are in: /home/username/onnxruntime/build/Linux/Debug/Testing/Temporary/LastTest.log                                                                                                   
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                           
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 2793, in <module>                                                                                                                           
    sys.exit(main())                                                                                                                                                                                         
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 2711, in main                                                                                                                               
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)                                                                                                                                  
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 1847, in run_onnxruntime_tests                                                                                                              
    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)                                                                                                                                                    
  File "/home/username/onnxruntime/tools/ci_build/build.py", line 738, in run_subprocess                                                                                                                      
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)                                                                                                                       
  File "/home/username/onnxruntime/tools/python/util/run.py", line 49, in run                                                                                                                                 
    completed_process = subprocess.run(                                                                                                                                                                      
  File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run                                                                                                                                            
    raise CalledProcessError(retcode, process.args,                                                                                                                                                          
subprocess.CalledProcessError: Command '['/sensei-fs/users/username/setup/trt_dependencies/cmake-3.24.2-linux-x86_64/bin/ctest', '--build-config', 'Debug', '--verbose', '--timeout', '10800']' returned non-z
ero exit status 8.                                                                 
```

**Comment by chilo-ms** [comment]
I tried the build script you shared against main branch and the build was successful. One thing you can try is to remove the "build" folder and start a clean build since there might have some old cmake settings not being updated.

Regarding the unit test failure, could you run the onnxruntime_test_all with `--gtest_filter` to only test the particular unit test to see does it still time out? The `--skip_tests` only skips unit tests and the ORT TRT binaries will still be built.

**Comment by jywu-msft** [comment]
yes, you can skip tests during build. 
it's possible there is test time variance between different GPU archs and also you are running Debug so that may explain the timeout.

**Comment by yf711** [comment]
Hi @CanyonWind,  
I have tested on building ORT with the `--use_tensorrt_builtin_parser` option and it has no issue on the latest ORT 1.14.1 version.
Please feel free to try on that (Note ORT 1.14 requires TRT 8.5)

**Comment by yf711** [comment]
Hi @CanyonWind I will close this issue for now. Feel free to reopen it if you have any questions.
