### ISSUE TITLE
[Performance] Benchmark.py fails to run distilbert-base-uncased when batchsize > 1

### ISSUE THREAD

**Issue by skyline75489** [microsoft/onnxruntime#13508]
### Describe the issue

[Transformer Model Optimization Tool ](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers) fails to run `distilbert-base-uncased` when batchsize > 1

### To reproduce

```text
python benchmark.py -m  distilbert-base-uncased -b 2
```

This is the error:

```text
2022-10-31 12:16:27.090291: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-31 12:16:27.274198: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-31 12:16:27.733772: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-31 12:16:27.733847: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-31 12:16:27.733856: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/jialli/anaconda3/envs/mlperf-py39/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Arguments: Namespace(models=['distilbert-base-uncased'], model_source='pt', model_class=None, engines=['onnxruntime'], cache_dir='./cache_models', onnx_dir='./onnx_models', use_gpu=False, provider=None, precision=<Precision.FLOAT32: 'fp32'>, verbose=False, overwrite=False, optimizer_info=<OptimizerInfo.BYSCRIPT: 'by_script'>, validate_onnx=False, fusion_csv=None, detail_csv=None, result_csv=None, input_counts=[1], test_times=100, batch_sizes=[2], sequence_lengths=[4, 8, 16, 32, 64, 128, 256], disable_ort_io_binding=False, num_threads=[4], force_num_layers=None, disable_attention=False, disable_skip_layer_norm=False, disable_embed_layer_norm=False, disable_bias_skip_layer_norm=False, disable_bias_gelu=False, disable_layer_norm=False, disable_gelu=False, enable_gelu_approximation=False, disable_shape_inference=False, enable_gemm_fast_gelu=False, use_mask_index=False, no_attention_mask=False)
Model class name: AutoModel
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_transform.bias', 'vocab_projector.weight', 'vocab_transform.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Skip export since model existed: ./onnx_models/distilbert_base_uncased_1.onnx
Skip optimization since model existed: ./onnx_models/distilbert_base_uncased_1_fp32_cpu.onnx
Run onnxruntime on distilbert-base-uncased with input shape [2, 4]
Exception
Traceback (most recent call last):
  File "/home/jialli/Projects/onnxruntime/onnxruntime/python/tools/transformers/benchmark.py", line 841, in main
    results += run_onnxruntime(
  File "/home/jialli/Projects/onnxruntime/onnxruntime/python/tools/transformers/benchmark.py", line 273, in run_onnxruntime
    ort_outputs = ort_session.run(ort_output_names, ort_inputs)
  File "/home/jialli/anaconda3/envs/mlperf-py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running EmbedLayerNormalization node. Name:'EmbedLayerNormalization_0' Status Message: input_ids and position_ids shall have same shape

```

### Urgency

N/A

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

2ecd1d662203d3fb5d77bf2aa97f6b8bcd7d1759

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by tianleiwu** [comment]
I can reproduce the issue. It seems that the position_ids shape is [1, seq_len]. Solution is either the kernel handle the propagation to [batch_size, seq_len], or the fusion shall not fuse embed layer normalization. @wangyems to take a look.

For user, a walkaround is to add an option to disable embed layer normalization fusion like the following:
```
python benchmark.py -m  distilbert-base-uncased -b 2 --disable_embed_layer_norm --overwrite
```

**Comment by skyline75489** [comment]
Thanks @tianleiwu. Will discuss about it with Ye internally.
