### ISSUE TITLE
[Web] Uncaught (in promise) TypeError: cannot resolve operator 'Erf' with opsets: ai.onnx v15

### ISSUE THREAD

**Issue by SangbumChoi** [microsoft/onnxruntime#13729]
### Describe the issue

Not only opset 15, but also all the other opset gives error of 
`Uncaught (in promise) TypeError: cannot resolve operator 'Erf' with opsets: ai.onnx v15`

### To reproduce

https://drive.google.com/drive/folders/1B6U8mSKvc8jQr625vIXoTZxEsjdfvwLG?usp=sharing

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.12.1

### Execution Provider

WebGL

**Comment by tianleiwu** [comment]
@SangbumChoi, According to https://onnxruntime.ai/docs/reference/compatibility.html, 1.12 shall support opset version up to 17. Did you try other EP (like CPU or CUDA) to see whether other EP has same issue?

**Comment by SangbumChoi** [comment]
@tianleiwu WASM backend works perfectly fine. However this error occurs in only WebGL backend. I have not tried into different execution providers. 
For the opset version I followed https://github.com/onnx/onnx/blob/main/docs/Operators.md (which indicates erf is compatible to 9, 13)

**Comment by SangbumChoi** [comment]
I think it is because of using [GELU](https://pytorch.org/docs/stable/generated/torch.nn.functional.gelu.html#torch-nn-functional-gelu) activation

**Comment by SangbumChoi** [comment]
```
opset.ts:47 Uncaught (in promise) TypeError: cannot resolve operator 'Erf' with opsets: ai.onnx v13
    at t.resolveOperator (opset.ts:47:1)
    at t.WebGLSessionHandler.resolve (session-handler.ts:81:1)
    at t.Session.initializeOps (session.ts:242:1)
    at session.ts:93:1
    at t.Profiler.event (instrument.ts:337:1)
    at t.Session.initialize (session.ts:89:1)
    at session.ts:71:1
t.resolveOperator @ opset.ts:47
resolve @ session-handler.ts:81
initializeOps @ session.ts:242
(anonymous) @ session.ts:93
event @ instrument.ts:337
initialize @ session.ts:89
(anonymous) @ session.ts:71
await in (anonymous) (async)
get @ ModelStore.ts:37
loadModels @ ISFocalClickModel.ts:46
updateMasks @ ISFocalClickModel.ts:107
updateMask @ Editor.tsx:76
(anonymous) @ Editor.tsx:85
setCtrlPointsForUser @ Editor.tsx:86
(anonymous) @ Editor.tsx:294
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

```

**Comment by tianleiwu** [comment]
Erf is not supported in WebGL EP:
https://github.com/microsoft/onnxruntime/blob/main/js/web/docs/operators.md

**Comment by SangbumChoi** [comment]
@tianleiwu Thanks. I am aware of that Erf is not supported in WebGL operation. Then should leave this issue as open or close?

**Comment by SangbumChoi** [comment]
@tianleiwu Also I want to ask is there any documentation for making custom operation (e.g. Erf, DynamicQuantizeLinzer, etc...) that does not supported in WebGL? Maybe developers can PR their custom ops in ONNXRuntime!

**Comment by josephrocca** [comment]
> Then should leave this issue as open or close?

I think this issue should remain open to track the addition of this operator to the WebGL backend.

I'm also having this issue - I have tried opset v16.
