### ISSUE TITLE
Issue on GKE: Parse Failed to parse provider option "device_id"

### ISSUE THREAD

**Issue by christidis** [microsoft/onnxruntime#13753]
### Describe the issue

I am missing something for sure since I don't have much experience with this.
I have a dockerized image and I am trying to deploy pods in GKE GPU enabled nodes (NVIDIA T4)

```
>>> import onnxruntime as ort
>>> ort.get_device()
'GPU'
>>> ort.get_all_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'MIGraphXExecutionProvider', 'ROCMExecutionProvider', 'OpenVINOExecutionProvider', 'DnnlExecutionProvider', 'NupharExecutionProvider', 'VitisAIExecutionProvider', 'NnapiExecutionProvider', 'CoreMLExecutionProvider', 'ArmNNExecutionProvider', 'ACLExecutionProvider', 'DmlExecutionProvider', 'RknpuExecutionProvider', 'CPUExecutionProvider']
>>> 
```

but my attempts with a model fail with `Parse Failed to parse provider option "device_id":`
```
>>> import onnxruntime as ort
>>> model_path = '/checkpoints/model_quantized.onnx'
>>> providers = [
...     ('CUDAExecutionProvider', {
...         'device_id': 0,
...         'arena_extend_strategy': 'kNextPowerOfTwo',
...         'gpu_mem_limit': 2 * 1024 * 1024 * 1024,
...         'cudnn_conv_algo_search': 'EXHAUSTIVE',
...         'do_copy_in_default_stream': True,
...     }),
...     'CPUExecutionProvider',
... ]
>>> session = ort.InferenceSession(model_path, providers=providers)
2022-11-25 15:06:55.092350462 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=0 ; hostname=main-test-7f8879c9b7-5cb2p ; expr=cudaGetDeviceCount(&num_devices); 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:45 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:151 Parse Failed to parse provider option "device_id": cuda_execution_provider_info.cc:52 operator() cudaGetDeviceCount() failed.
```
(I am getting the same thing when setting other device ids).

and without a tuple but with a list of strings it fails with a different error:
`CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version`
```
>>> import onnxruntime as ort
>>> model_path = '/checkpoints/model_quantized.onnx'
>>> providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
>>> session = ort.InferenceSession(model_path, providers=providers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=-1568996352 ; hostname=main-test-7f8879c9b7-5cb2p ; expr=cudaSetDevice(info_.device_id);
```

Also `nvidia-smi` doesn't seem to be available 
```
# apt install nvidia-smi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nvidia-smi is a virtual package provided by:
  nvidia-utils-515 515.86.01-0ubuntu1
  nvidia-utils-510 510.108.03-0ubuntu1
  nvidia-utils-470 470.161.03-0ubuntu1
  nvidia-utils-520 520.61.05-0ubuntu1
  nvidia-utils-410 410.129-0ubuntu1
  nvidia-utils-515-server 515.65.01-0ubuntu0.18.04.1
  nvidia-utils-510-server 510.85.02-0ubuntu0.18.04.1
  nvidia-utils-470-server 470.141.10-0ubuntu0.18.04.1
  nvidia-utils-450-server 450.203.03-0ubuntu0.18.04.1
  nvidia-utils-418-server 418.226.00-0ubuntu0.18.04.2
  nvidia-utils-390 390.154-0ubuntu0.18.04.1
You should explicitly select one to install.

E: Package 'nvidia-smi' has no installation candidate
```

```
# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

For some reason onnxruntime doesn't find my GPU but the node is GPU enabled.
```
# lshw  -C display
  *-display                 
       description: 3D controller
       product: NVIDIA Corporation
       vendor: NVIDIA Corporation
       physical id: 4
       bus info: pci@0000:00:04.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: msix pm bus_master cap_list
       configuration: driver=nvidia latency=0
       resources: iomemory:20-1f iomemory:20-1f irq:11 memory:c0000000-c0ffffff memory:2c0000000-2cfffffff memory:2d0000000-2d1ffffff
```

What am I doing wrong?

### To reproduce

I have tried with all these images
```
#FROM nvidia/cuda:11.4.1-cudnn8-runtime-ubuntu20.04
#FROM nvidia/cuda:11.5.1-cudnn8-runtime-ubuntu20.04
#FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
#FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04
FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04
```

for the current image I have `1.10.1`, for the other images I get the same error when using the `1.12.1`.
```
scikit-learn==0.22.1
openapi-schema-validator==0.2.0
openapi-spec-validator==0.2.10
pytest==6.2.5
numpy==1.19.5
psutil==5.8.0
pytest-cov==3.0.0
onnxruntime-gpu==1.10.0
#onnxruntime-gpu==1.12.1
transformers==4.12.5
```

### Platform

Linux

### OS Version

Ubuntu 18.04, 20.04, 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04

**Comment by christidis** [comment]
OK I've found the problem to my issue. Apart from the configured taints and tolerations in order to deploy on a gpu-enabled nodepool you will also need to set the gpu limits in the resources for them to be available.

In my case I have 2 GPUs per GKE node, so I had to set this limit `nvidia.com/gpu: "2"`.

```
resources:
  limits:
    cpu: 6
    memory: 8G
    nvidia.com/gpu: "2"
  requests:
    cpu: 500m
    memory: 4G
```

Quite strange if you ask me, because when you don't set any limits for memory or cpu you are still able to use them. However, this is not the case for GPU. You have to claim the resources in order to use them in Kubernetes. This is equivalent to `--gpus all` in docker run.

After enabling this limit, `nvidia-smi` got enabled in the pod and I am able to use onnxruntime.
