### ISSUE TITLE
numpy==1.24.0 breaks `FusionReshape` transformer optimization

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#14017]
### Describe the issue

This line fails with gpt2: https://github.com/microsoft/onnxruntime/blob/fba09faf5be060b29b3dd0aea079a11c98c2da2b/onnxruntime/python/tools/transformers/fusion_reshape.py#L22

Previously there was a deprecation warning:

```
<tmp 2>+22:5: DeprecationWarning: setting an array element with a sequence. This was supported in some cases where the elements are arrays with a single element. For example `np.array([1, np.array([2])], dtype=int)`. In the future this will raise the same ValueError as `np.array([1, [2]], dtype=int)`.
  shape_value = np.asarray(shape, dtype=np.int64)
```

### To reproduce

```
import numpy as np

shape = [0, 0, np.array([4]), np.array([8])]

shape_value = np.asarray(shape, dtype=np.int64)
```

that raises with numpy==1.24.0
```
Traceback (most recent call last):
  File "<tmp 2>", line 22, in <module>
    shape_value = np.asarray(shape, dtype=np.int64)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

or alternatively:

```python
from optimum.onnxruntime import ORTOptimizer, ORTModelForSequenceClassification, OptimizationConfig

from transformers import AutoTokenizer
import tempfile 

tokenizer = AutoTokenizer.from_pretrained("hf-internal-testing/tiny-random-gpt2")
optimization_config = OptimizationConfig(optimization_level=2, enable_transformers_specific_optimizations=True)
with tempfile.TemporaryDirectory() as tmp_dir:
    model = ORTModelForSequenceClassification.from_pretrained(
        "hf-internal-testing/tiny-random-gpt2",
        from_transformers=True
    )
    model.save_pretrained(tmp_dir)
    optimizer = ORTOptimizer.from_pretrained(model)
    optimizer.optimize(optimization_config=optimization_config, save_dir=tmp_dir)
```

Now raising:

```
Traceback (most recent call last):
  File "<tmp 2>", line 15, in <module>
    optimizer.optimize(optimization_config=optimization_config, save_dir=tmp_dir)
  File "/home/fxmarty/hf_internship/optimum/optimum/onnxruntime/optimization.py", line 146, in optimize
    optimizer = optimize_model(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 255, in optimize_model
    optimizer = optimize_by_fusion(model, model_type, num_heads, hidden_size, optimization_options)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 154, in optimize_by_fusion
    optimizer.optimize(optimization_options)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model_bert.py", line 378, in optimize
    self.fuse_reshape()
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model_bert.py", line 89, in fuse_reshape
    fusion.apply()
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../fusion_base.py", line 46, in apply
    self.fuse(node, input_name_to_nodes, output_name_to_node)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../fusion_reshape.py", line 173, in fuse
    self.replace_reshape_node(shape, reshape_node, concat_node)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/onnxruntime/transformers/models/gpt2/../../fusion_reshape.py", line 23, in replace_reshape_node
    shape_value = np.asarray(shape, dtype=np.int64)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

### Urgency

urgent

### Platform

Linux

### OS Version

Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
I can reproduce it with numpy v1.24.0. I could provide a fix soon.

At the meantime, a walkaround is to use numpy v1.23.5.
