### ISSUE TITLE
[Build] core/framework/fence.h not found while build upon CANN

### ISSUE THREAD

**Issue by luoyangen** [microsoft/onnxruntime#14121]
### Describe the issue

while build for CANN machine with the code:
`./build.sh --config RelWithDebInfo --build_shared_lib --parallel --use_cann --build_wheel`

the error is : core/framework/fence.h is required by core/providers/cann/cann_fence.h
but the file fence.h doesnot exist

`onnxruntime/core/providers/cann/cann_fence.h:7:10: 致命错误：core/framework/fence.h：没有那个文件或目录
    7 | #include "core/framework/fence.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
`

### Urgency

urgent

### Target platform

aarch64, CANN

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --use_cann --build_wheel

### Error / output

onnxruntime/onnxruntime/core/providers/cann/cann_fence.h:7:10: 致命错误：core/framework/fence.h：没有那个文件或目录
    7 | #include "core/framework/fence.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
编译中断。

onnxruntime/core/providers/cann/cann_execution_provider.h:41:9: 错误：‘void* onnxruntime::CANNExecutionProvider::GetComputeStream() const’ marked ‘override’, but does not override
   41 |   void* GetComputeStream() const override { return static_cast<void*>(stream_); }
      |         ^~~~~~~~~~~~~~~~

core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明
  111 |     CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF);
      |                      ^~~~~~~~~~~~~~~~~~~~

onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明
  112 |     CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

onnxruntime/core/providers/cann/cann_allocator.h:22:3: 错误：‘FencePtr’不是一个类型名
   22 |   FencePtr CreateFence(const SessionState* session_state) override;
      |   ^~~~~~~~

### GCC / Compiler Version

gcc 9.4.0

**Comment by wangxiyuan** [comment]
> CC @wangxiyuan / @FFFrog

Thanks for reminding, checking now. @FFFrog has a patch to fix the issue already. https://github.com/microsoft/onnxruntime/pull/14058

**Comment by FFFrog** [comment]
> > > CC @wangxiyuan / @FFFrog
> > 
> > 
> > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058
> 
> Thanks. I tried to use the full directory "cann" of the branch "multi-stream" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:
> 
> `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`
> 
> `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

So sorry for that, could you show me the **cann** version you are using?

**Comment by luoyangen** [comment]
> > > > CC @wangxiyuan / @FFFrog
> > > 
> > > 
> > > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058
> > 
> > 
> > Thanks. I tried to use the full directory "cann" of the branch "multi-stream" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:
> > `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`
> > `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
> 
> So sorry for that, could you show me the **cann** version you are using? If possible, please upgrade CANN to [the latest version](https://www.hiascend.com/en/software/cann/community)

CANN version is 5.1.RC2.
I shall upgrade CANN.
Thanks.

**Comment by luoyangen** [comment]
> > > > CC @wangxiyuan / @FFFrog
> > > 
> > > 
> > > Thanks for reminding. @FFFrog has a patch to fix the issue already. #14058
> > 
> > 
> > Thanks. I tried to use the full directory "cann" of the branch "multi-stream" of project https://github.com/learningbackup/onnxruntime.git, but still have error while compiling. The error details are:
> > `onnxruntime/core/providers/cann/cann_call.cc:111:22: 错误：‘GRAPH_INVALID_IR_DEF’在此作用域中尚未声明 111 | CASE_ENUM_TO_STR(GRAPH_INVALID_IR_DEF); | ^~~~~~~~~~~~~~~~~~~~`
> > `onnxruntime/core/providers/cann/cann_call.cc:112:22: 错误：‘OP_WITHOUT_IR_DATATYPE_INFER_RULE’在此作用域中尚未声明 112 | CASE_ENUM_TO_STR(OP_WITHOUT_IR_DATATYPE_INFER_RULE); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
> 
> So sorry for that, could you show me the **cann** version you are using? If possible, please upgrade CANN to [the latest version](https://www.hiascend.com/en/software/cann/community)

Hi, after cann updated to 6.0.RC1, it successed complied, but cannot pass all the test steps. The error message is:
`
The following tests FAILED:
	  1 - onnxruntime_test_all (Failed)
Errors while running CTest
Output from these tests are in: /root/onnxruntime/build/Linux/RelWithDebInfo/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Traceback (most recent call last):
  File "/root/onnxruntime/tools/ci_build/build.py", line 2880, in <module>
    sys.exit(main())
  File "/root/onnxruntime/tools/ci_build/build.py", line 2785, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "/root/onnxruntime/tools/ci_build/build.py", line 1900, in run_onnxruntime_tests
    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)
  File "/root/onnxruntime/tools/ci_build/build.py", line 760, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/root/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/root/miniconda3/envs/onnx_runtime2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,subprocess.CalledProcessError: Command '['/root/miniconda3/envs/onnx_runti
[LastTestsFailed.log](https://github.com/microsoft/onnxruntime/files/10407606/LastTestsFailed.log)
[CTestCostData.txt](https://github.com/microsoft/onnxruntime/files/10407607/CTestCostData.txt)
me2/bin/ctest', '--build-config', 'RelWithDebInfo', '--verbose', '--timeout', '10800']' returned non-zero exit status 8.
`

And the test logs file is
[LastTest.log](https://github.com/microsoft/onnxruntime/files/10407603/LastTest.log)

**Comment by wangxiyuan** [comment]
The error log is:

```
[ RUN      ] CannExecutionProviderTest.FunctionTest
Traceback (most recent call last):
  File "/usr/local/Ascend/ascend-toolkit/6.0.RC1/python/site-packages/tbe/tvm/target.py", line 67, in <module>
    from decorator import decorate
ModuleNotFoundError: No module named 'decorator'
```
So please follow the message to install `decorator` package first. It is a dependences missing problem for ascend toolkit. For this kind of error, I assume you can fix it locally first. Thanks.

**Comment by luoyangen** [comment]
> The error log is:
> 
> ```
> [ RUN      ] CannExecutionProviderTest.FunctionTest
> Traceback (most recent call last):
>   File "/usr/local/Ascend/ascend-toolkit/6.0.RC1/python/site-packages/tbe/tvm/target.py", line 67, in <module>
>     from decorator import decorate
> ModuleNotFoundError: No module named 'decorator'
> ```
> 
> So please follow the message to install `decorator` package first. It is a dependences missing problem for ascend toolkit. For this kind of error, I assume you can fix it locally first. Thanks.

oooh! My bad! Didn't figure out the error message~Thanks!

**Comment by luoyangen** [comment]
@wangxiyuan Hi, Sorry to bother again.
After the decorator package installed, I successed to compile and install onnxruntime-cann. 
But still have some error while using cann provider in the onnxruntime。
The provider configuration is:

`
providers = [
    ('CANNExecutionProvider', {
        'device_id': 1,
        'max_opqueue_num': 10000,
        'arena_extend_strategy': 'kNextPowerOfTwo',
        'npu_mem_limit': 2 * 1024 * 1024 * 1024,
        'do_copy_in_default_stream': True,
    }),
]`

and the error info is:
![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)

And the code works well while i change the provider to **CPUExecutionProvider**。

Also the ascend log file under the directory "ascend/debug" details are:
**plog/plog-xxx.log:**
![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)

**device-0/device-xxx.log:**
![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)

**Comment by FFFrog** [comment]
> @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:
> 
> ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`
> 
> and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)
> 
> And the code works well while i change the provider to **CPUExecutionProvider**。
> 
> Also the ascend log file under the directory "ascend/debug" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)
> 
> **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)

So sorry for that.

Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the ```providers``` field, please.

If there are still errors, please enable debug log of Ascend and mail the log to ```ljw1101.vip@gmail.com```. 

Thank you

**Comment by xinxin12345** [comment]
> > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:
> > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`
> > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)
> > And the code works well while i change the provider to **CPUExecutionProvider**。
> > Also the ascend log file under the directory "ascend/debug" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)
> > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)
> 
> So sorry for that.
> 
> Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.
> 
> If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.
> 
> Thank you

"Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend."

**Comment by luoyangen** [comment]
> > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:
> > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`
> > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)
> > > And the code works well while i change the provider to **CPUExecutionProvider**。
> > > Also the ascend log file under the directory "ascend/debug" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)
> > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)
> > 
> > 
> > So sorry for that.
> > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.
> > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.
> > Thank you
> 
> "Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend."

My model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN.

**Comment by xinxin12345** [comment]
> > > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:
> > > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`
> > > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)
> > > > And the code works well while i change the provider to **CPUExecutionProvider**。
> > > > Also the ascend log file under the directory "ascend/debug" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)
> > > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)
> > > 
> > > 
> > > So sorry for that.
> > > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.
> > > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.
> > > Thank you
> > 
> > 
> > "Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend."
> 
> My model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN.

"May I know if you contacted Huawei engineers through this email ljw1101.vip@gmail.com?"

**Comment by wangxiyuan** [comment]
> > > > > @wangxiyuan Hi, Sorry to bother again. After the decorator package installed, I successed to compile and install onnxruntime-cann. But still have some error while using cann provider in the onnxruntime。 The provider configuration is:
> > > > > ` providers = [ ('CANNExecutionProvider', { 'device_id': 1, 'max_opqueue_num': 10000, 'arena_extend_strategy': 'kNextPowerOfTwo', 'npu_mem_limit': 2 * 1024 * 1024 * 1024, 'do_copy_in_default_stream': True, }), ]`
> > > > > and the error info is: ![image](https://user-images.githubusercontent.com/3061079/215312628-9e95e20f-6fc0-49ce-a217-3a8c112ed96a.png)
> > > > > And the code works well while i change the provider to **CPUExecutionProvider**。
> > > > > Also the ascend log file under the directory "ascend/debug" details are: **plog/plog-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312788-bc742a94-26bd-4b3c-8484-da8b49cfc5cf.png)
> > > > > **device-0/device-xxx.log:** ![image](https://user-images.githubusercontent.com/3061079/215312750-f8d660f2-a00b-4273-8460-2880059a7f30.png)
> > > > 
> > > > 
> > > > So sorry for that.
> > > > Can you refer to the [link](https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html#python) and try again? Pay attention to the `providers` field, please.
> > > > If there are still errors, please enable debug log of Ascend and mail the log to `ljw1101.vip@gmail.com`.
> > > > Thank you
> > > 
> > > 
> > > "Have you solved this problem? I encountered the same issue when testing with the Python interface. The model works fine with CPU but raises errors when using the CANN backend."
> > 
> > 
> > My model works now under the help of HUAWEI engineers. It was because one operator of my model was not supported by CANN.
> 
> "May I know if you contacted Huawei engineers through this email [ljw1101.vip@gmail.com](mailto:ljw1101.vip@gmail.com)?"

Hi, sorry that we missed the message for such a long time. Yes, you can send your problem to ljw1101.vip@gmail.com or wangxiyuan1007@gmail.com directly. Or describe it here.
