### ISSUE TITLE
[Training] Does the current training code support RNN model like seq2seq and Transformer and GNN model?

### ISSUE THREAD

**Issue by Looong01** [microsoft/onnxruntime#14139]
### Describe the issue

When I run a seq2seq model, it returned errors:

/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_training_manager.py:190: UserWarning: Fast path enabled - skipping checks. Rebuild graph: True, Execution agent: True, Device check: True
warnings.warn(
/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/rnn.py:953: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at /opt/conda/conda-bld/pytorch_1656352660876/work/aten/src/ATen/native/cudnn/RNN.cpp:968.)
result = _VF.gru(input, batch_sizes, hx, self._flat_weights, self.bias,
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PackPadded type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PackPadded type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PadPacked type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PadPacked type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PackPadded type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PackPadded type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PadPacked type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of prim::PadPacked type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of org.pytorch.aten::ATen type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_logger.py:52: UserWarning: There were one or more warnings or errors raised while exporting the PyTorch model. Please enable INFO level logging to view all warnings and errors.
warnings.warn(
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
Warning: Checker does not support models with experimental ops: ATen
Traceback (most recent call last):
File "/home/ypd-24-stu-9/.Temp/seq2seq/run.py", line 30, in
train.train(config.arch,
File "/home/ypd-24-stu-9/.Temp/seq2seq/train.py", line 144, in train
train_seq2seq_model(model, train_data, device, loss_fn, optimizer, model_path, epochs, log_path)
File "/home/ypd-24-stu-9/.Temp/seq2seq/train.py", line 68, in train_seq2seq_model
mb_pred, attn = model(mb_x, mb_x_len, mb_input, mb_y_len)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_utils.py", line 371, in _forward
return ortmodule._torch_module.forward(*inputs, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_utils.py", line 351, in _forward
return torch_module_ort._execution_manager(torch_module_ort.is_training()).forward(*inputs, kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_training_manager.py", line 271, in forward
self._fallback_manager.handle_exception(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_fallback.py", line 162, in handle_exception
raise exception
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_training_manager.py", line 224, in forward
self._build_graph()
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_training_manager.py", line 285, in _build_graph
super()._build_graph()
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 245, in _build_graph
self._graph_builder.build()
RuntimeError: /onnxruntime_src/orttraining/orttraining/core/graph/gradient_builder_registry.cc:28 onnxruntime::training::GradientDef onnxruntime::training::GetGradientForOp(const onnxruntime::training::GradientGraphConfiguration&, onnxruntime::Graph, const onnxruntime::Node, const std::unordered_set<std::basic_string >&, const std::unordered_set<std::basic_string >&, const onnxruntime::logging::Logger&, std::unordered_set<std::basic_string >&) gradient_builder != nullptr was false. The gradient builder has not been registered: GRU for node GRU_149

And when I trained a GNN model, it returned these:

home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_fallback.py:178: UserWarning: Fallback to PyTorch due to exception <class 'onnxruntime.training.ortmodule._fallback_exceptions.ORTModuleONNXModelException'> was triggered. Report this issue with a minimal repro at https://www.github.com/microsoft/onnxruntime. See details below:

RuntimeError: There was an error while exporting the PyTorch model to ONNX:

Traceback (most recent call last):
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_utils.py", line 312, in get_exception_as_string
raise exception
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 424, in _get_exported_model
torch.onnx.export(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/init.py", line 350, in export
return utils.export(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/utils.py", line 163, in export
_export(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/utils.py", line 1074, in _export
graph, params_dict, torch_out = _model_to_graph(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
graph, params, torch_out, module = _create_jit_graph(model, args)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
graph, torch_out = _trace_and_get_graph_from_model(model, args)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
graph, out = torch._C._create_graph_by_tracing(
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
outs.append(self.inner(*trace_inputs))
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
result = self.forward(*input, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/onnxruntime/training/ortmodule/_io.py", line 457, in forward
return _transform_output_to_flat_tuple(self._original_module(*new_args, **new_kwargs))
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
File "/home/ypd-24-stu-9/anaconda3/envs/Ort/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

### To reproduce

For the seq2seq model:
1. Add "from torch_ort import ORTModule" into codes
2. Add "model = ORTModule(model)" into codes after "model = Seq2seq(......)" and before "model.cuda()" or "model.to("cuda")"
3. Run "python train.py <other args>"

For the GNN model:
1. from torch_ort import ORTModule
2. Add this "model = ORTModule(model)" into codes after "model = GNN(......)" and before "model.cuda()" or "model.to("cuda")"
3. Run "python train.py <other args>"

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-training   1.12.0+cu113

### PyTorch Version

torch  1.12.0;     torch-ort   1.12.0

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.3

**Comment by Looong01** [comment]
Furthermore, does ORT training for PyTorch support WSL2?

**Comment by pengwa** [comment]
The quick answer is ORT training focuses on supporting transformer models only so far. So there is an error complaining no gradient op for GRU op. 

For the error "TypeError: forward() missing 1 required positional argument: 'input'", it is failing during model exporting to ONNX  phase, you might compare whether you give all inputs comparing with the forward function signature.

**Comment by Looong01** [comment]
> The quick answer is ORT training focuses on supporting transformer models only so far. So there is an error complaining no gradient op for GRU op.
> 
> For the error "TypeError: forward() missing 1 required positional argument: 'input'", it is failing during model exporting to ONNX phase, you might compare whether you give all inputs comparing with the forward function signature.

For this, "Add this "model = ORTModule(model)" into codes after "model = GNN(......)" and before "model.cuda()" or "model.to("cuda")"".

Is this adding position, that ORTModule() is after the instantiation of the model and before the transmitting to GPU, right?

**Comment by pengwa** [comment]
The way you wrapped using ORTModule looks fine I think. 

Looks anyway the model won't run shortly with ORTModule, maybe we can see what we can help on the error: "TypeError: forward() missing 1 required positional argument: 'input'". 

Could you please share the input that is given here, and what is the model forward function signature? Let's see what we can help here.

**Comment by Looong01** [comment]
> The way you wrapped using ORTModule looks fine I think.
> 
> Looks anyway the model won't run shortly with ORTModule, maybe we can see what we can help on the error: "TypeError: forward() missing 1 required positional argument: 'input'".
> 
> Could you please share the input that is given here, and what is the model forward function signature? Let's see what we can help here.

Actually, I installed Ort-training in WSL2. Is this related to the problems I met?
