### ISSUE TITLE
Mixed Precision ValueError: validation failed for model with all nodes in node_block_list

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [microsoft/onnxruntime#14235]
### Describe the issue

Hey guys,

Hope to find you well. I've opened tons of issues but I've never received replies, I just want to convert a model to mixed precision. The doc is wrong and the current code doesn't work for me. 

Related issues:

https://github.com/microsoft/onnxruntime/issues/13833 
https://github.com/NVIDIA/TensorRT/issues/2542
https://github.com/microsoft/onnxconverter-common/issues/251

In my opinion, is very weird since I seems like the only person in the community trying to just run a mixed precision model in ONNX and it looks like there is no documented way to do so.

Thanks in advance!

### To reproduce

Using torch=1.13.1

```python
import onnxruntime as ort
import torch
from torchvision.models import ConvNeXt_Small_Weights, convnext_small
from onnxconverter_common import float16
from onnxconverter_common.auto_mixed_precision import auto_convert_mixed_precision
import onnx

model_name = "model.onnx"
model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()

x = torch.randn(1, 3, 224, 224, device="cuda")
# Export the model
torch.onnx.export(
    model,  # model being run
    x,  # model input (or a tuple for multiple inputs)
    model_name,  # where to save the model (can be a file or file-like object)
    opset_version=16,
    export_params=True,  # store the trained parameter weights inside the model file
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names=["image"],  # the model's input names
    output_names=["output"],  # the model's output names
    dynamic_axes={
        "image": {0: "batch_size"},  # variable length axes
        "output": {0: "batch_size"},
    },
)

model = onnx.load("model.onnx")
# model_fp16 = float16.convert_float_to_float16(model)
# onnx.save(model_fp16, "model.fp16.onnx")

model_fp16 = auto_convert_mixed_precision(model, { "image" : x.cpu().numpy() }, None, rtol=0.01, atol=0.001, keep_io_types=True)
# auto_convert_mixed_precision_model_path("./model.onnx", { "image" : x.cpu().numpy() }, "./model_fp16.onnx", provider=["CUDAExecutionProvider"], rtol=0.01, atol=0.001, keep_io_types=True, verbose=False)
onnx.save(model_fp16, "model.fp16.onnx")
# let's check
print("Checking")
x = torch.randn(1, 3, 224, 224, device="cuda", dtype=torch.float16)
ort_session = ort.InferenceSession("model.fp16.onnx", providers=["CUDAExecutionProvider"])
outputs = ort_session.run(None, {"image": x.cpu().numpy()})
print(outputs[0].shape, outputs[0].dtype)
```

Will fail with stack trace

```
...
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:53: UserWarning: the float32 number -3.575223672669381e-08 will be truncated to -1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(neg_max, -min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:43: UserWarning: the float32 number 4.082721716258675e-08 will be truncated to 1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(pos_min, min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:53: UserWarning: the float32 number -7.970152182679158e-08 will be truncated to -1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(neg_max, -min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:43: UserWarning: the float32 number 4.87943907501176e-10 will be truncated to 1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(pos_min, min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:53: UserWarning: the float32 number -1.074658939614892e-08 will be truncated to -1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(neg_max, -min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:43: UserWarning: the float32 number 6.295249477261677e-08 will be truncated to 1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(pos_min, min_positive_val))
/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/float16.py:53: UserWarning: the float32 number -7.707149052293971e-08 will be truncated to -1e-07
  warnings.warn("the float32 number {} will be truncated to {}".format(neg_max, -min_positive_val))
False
Traceback (most recent call last):
  File "/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/export_to_onnx.py", line 32, in <module>
    model_fp16 = auto_convert_mixed_precision(model, { "image" : x.cpu().numpy() }, None, rtol=0.01, atol=0.001, keep_io_types=True)
  File "/home/zuppif/Documents/medium/how-to-docker+onnx+tensorrt/.venv/lib/python3.9/site-packages/onnxconverter_common/auto_mixed_precision.py", line 81, in auto_convert_mixed_precision
    raise ValueError("validation failed for model with all nodes in node_block_list")
ValueError: validation failed for model with all nodes in node_block_list
```

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

### Execution Provider Library Version

cuda 11.7

**Comment by xadupre** [comment]
I wonder what is the discrepancy when you compare torch with float32 and the same torch model converted into float16 (no onnx).

**Comment by FrancescoSaverioZuppichini** [comment]
@xadupre thanks for the reply, sure

```python
model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()
x = torch.randn(1, 3, 224, 224, device="cuda")
# let's store the outputs to compare the results
with torch.no_grad():
    out_torch = model(x)

# let's store the outputs to compare the results
with torch.no_grad():
    out_torch_half = model.half()(x.half())

print(torch.abs(out_torch_half - out_torch).mean())
```

Prints `tensor(0.0006, device='cuda:0')`



keep in mind I'd like to know **how to convert a model to mixed precision** 

People have said to me, do it in torch and export in ONNX, other people have said to me do it in ONNX, your doc shows how to do it ONNX but is causing this issue

**Comment by xadupre** [comment]
I looked at the code of auto_convert_mixed_precision and I think it needs to be improved. It is not recursive, it does not dig into subgraphs - loop, if. Then, it removes one by one nodes showing coefficients outside boundaries of float16. torch does not do that. For the time being, my recommandation is to keep using `float16.convert_float_to_float16(model)`.

**Comment by FrancescoSaverioZuppichini** [comment]
@xadupre, not sure I am following :) I am interested on mixed precision or at least I am interested to check the performance of the converted model with mixed precision in onnx

**Comment by FrancescoSaverioZuppichini** [comment]
Moreover, ONNX and Torch fp16 do not give the same result

```python
def export_fp16_model():
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda()
    x = torch.randn(1, 3, 224, 224, device="cuda")
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model.half()(x.half())
    # load fp32 model, convert to fp16
    model = onnx.load("model.onnx")
    model_fp16 = float16.convert_float_to_float16(model)
    onnx.save(model_fp16, model_name)
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())
  ```
  Prints `0.0239` 
  
  Same thing if I convert the model first in pytorch  
  
  ```python
  def export_fp16_from_torch_model():
    model_name = "model.fp16.onnx"
    model = convnext_small(ConvNeXt_Small_Weights.IMAGENET1K_V1).eval().cuda().half()
    x = torch.randn(1, 3, 224, 224, device="cuda").half()
    export_onnx(model, x, model_name)
    # let's store the outputs to compare the results
    with torch.no_grad():
        out_torch = model(x)
    # load fp16 model
    ort_session = ort.InferenceSession(model_name, providers=["CUDAExecutionProvider"])
    outputs = ort_session.run(None, {"image": x.half().cpu().numpy()})
    # checking the difference
    print(np.abs(out_torch.cpu().numpy() - outputs[0]).mean())
    ``` 

Prints `0.0239`

**Comment by FrancescoSaverioZuppichini** [comment]
To my understanding, to this day even if some people shows benchmarks, **NOBODY** was ever able to run a model in mixed precision in ONNX and it is crazy to have such little support and documentation (but thanks a lot for everything you are doing so far) but at least state somewhere that is not possible or it's unstable, so we don't waste hours - thanks a lot

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini try changing rtol and atol values to higher values. It should work.

that's cheating

**Comment by thiagocrepaldi** [comment]
The export seems to work, but the following stages fail. Maybe @xadupre @fatcat-z or @xiaowuhu may help
If this is no longer relevant, feel free to close the issue

**Comment by AndreyOrb** [comment]
I now faced the error. In my case, one of the initializers (weights) was above the default proposed limit 1e4 and it caused the fp16 model to produce results far away from the original fp32 model. Basically, that weight was truncated from 25k to 10k.

After explicitly increasing the maximum value to 1e5, the problem disappeared.
auto_mixed_precision.py:70
```
        model = float16.convert_float_to_float16(copy.deepcopy(model0), max_finite_val=1e5, node_block_list=node_block_list,
                                                 keep_io_types=keep_io_types, disable_shape_infer=True)
```

**Comment by Fazankabir** [comment]
@jayakommuru  [here ](https://github.com/microsoft/onnxconverter-common/issues/251#issuecomment-1411504927)is another discussion and also a conversion but not with `mixed_precision`.  
@FrancescoSaverioZuppichini  have you found any work around to do `mixed_precision` as i am loosing model accuracy with `float16.convert_float_to_float16`  and my goal is to have fast inference time wih onnx model on GPU with accepted accuracy. I could not found any proper documentation or any resource, I am stuck with this issue since days . Any help will be appreciated

**Comment by Schmidt-Hang** [comment]
Hallo, are you still there? I have the same problem. After checking, I found that the issue might be due to the extremely small values in your model's numpy array, such as -7.707149052293971e-08. In this case, no matter how small you set "rtol" or "atol," it becomes meaningless. However, when I increased "rtol" or "atol" to values like 5.0, 6.0, or even larger, it started working.

In conclusion, if all the values in your model are as small as -7.707149052293971e-08, it’s best to avoid using Mixed Precision. You’ll find that the results of Mixed Precision are the same as those from normal Float16 conversion.

I hope this would help you!

**Comment by AndreyOrb** [comment]
Still having the same issue.
