### ISSUE TITLE
No module named 'onnxruntime.transformers.io_binding_helper'

### ISSUE THREAD

**Issue by josephsachdeva** [microsoft/onnxruntime#14230]
### Describe the issue

Getting this issue, whenever we are building it in docker.

### Urgency

It is urgent, because it is causing our build fails

### Target platform

All

### Build script

pip install optimum[onnxruntime]
**onnxruntime version is 1.10**

### Error / output

Traceback (most recent call last):
  File "services/snippets_batch.py", line 21, in <module>
    from services.crud_embeddings.embeddings_crawler import EmbeddingsCRUD
  File "/src/services/crud_embeddings/embeddings_crawler.py", line 7, in <module>
    from middlewares.ml_models import sentence_transformer
  File "/src/middlewares/ml_models/__init__.py", line 2, in <module>
    from utils.dym.did_you_mean import load_model
  File "/src/utils/dym/did_you_mean.py", line 13, in <module>
    from optimum.pipelines import pipeline
  File "/usr/local/lib/python3.8/site-packages/optimum/pipelines.py", line 49, in <module>
    from .onnxruntime import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/usr/local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnxruntime.modeling_decoder because of the following error (look up to see its traceback):
No module named 'onnxruntime.transformers.io_binding_helper'

**Comment by xadupre** [comment]
onnxruntime.transformers.io_binding_helper was added in version 1.11. You need to update onnxruntime.
