### ISSUE TITLE
[Build] fails with onnxruntime_DISABLE_ABSEIL=ON

### ISSUE THREAD

**Issue by jf99** [microsoft/onnxruntime#14264]
### Describe the issue

The current release 1.13.1 cannot be built with `onnxruntime_DISABLE_ABSEIL=ON`. If that flag is not set though, it does build. It seems as if somebody has made changes to the C++ code without keeping the possible absence of abseil in mind.

### Target platform

Ubuntu 20.04 and 22.04

### Build script

```
./build.sh --config Release --parallel --cmake_extra_defines CMAKE_INSTALL_PREFIX=$INSTALL_DIR/usr onnxruntime_DISABLE_ABSEIL=ON --skip_tests
```

### Error / output

The relevant section of the build log:
```
...
/home/jf99/build/my-onnxruntime/onnxruntime/core/graph/graph.cc:3843:37: error: ‘class onnxruntime::InlinedHashMap<std::__cxx11::basic_string<char>, std::reference_wrapper<onnx::OpSchema> >’ has no member named ‘contains’
 3843 |     if (!reusable_fused_schema_map_.contains(schema_key)) {
      |                                     ^~~~~~~~
In file included from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/memory:62,
                 from /home/jf99/build/my-onnxruntime/include/onnxruntime/core/graph/graph.h:7,
                 from /home/jf99/build/my-onnxruntime/include/onnxruntime/core/graph/graph_viewer.h:6,
                 from /home/jf99/build/my-onnxruntime/onnxruntime/core/graph/graph_proto_serializer.h:6,
                 from /home/jf99/build/my-onnxruntime/onnxruntime/core/graph/graph_proto_serializer.cc:4:
/usr/include/c++/9/bits/stl_pair.h: In instantiation of ‘struct std::pair<const std::__cxx11::basic_string<char>, OrtValue>’:
/usr/include/c++/9/ext/aligned_buffer.h:91:28:   required from ‘struct __gnu_cxx::__aligned_buffer<std::pair<const std::__cxx11::basic_string<char>, OrtValue> >’
/usr/include/c++/9/bits/hashtable_policy.h:233:43:   required from ‘struct std::__detail::_Hash_node_value_base<std::pair<const std::__cxx11::basic_string<char>, OrtValue> >’
/usr/include/c++/9/bits/hashtable_policy.h:264:12:   required from ‘struct std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, OrtValue>, true>’
/usr/include/c++/9/bits/hashtable_policy.h:2027:13:   required from ‘struct std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, OrtValue>, true> > >’
/usr/include/c++/9/bits/hashtable.h:173:11:   required from ‘class std::_Hashtable<std::__cxx11::basic_string<char>, std::pair<const std::__cxx11::basic_string<char>, OrtValue>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, OrtValue> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char> >, std::hash<std::__cxx11::basic_string<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >’
/usr/include/c++/9/bits/unordered_map.h:105:18:   required from ‘class std::unordered_map<std::__cxx11::basic_string<char>, OrtValue, std::hash<std::__cxx11::basic_string<char> >, std::equal_to<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, OrtValue> > >’
/home/jf99/build/my-onnxruntime/include/onnxruntime/core/common/inlined_containers.h:128:7:   required from ‘class onnxruntime::InlinedHashMap<std::__cxx11::basic_string<char>, OrtValue>’
/home/jf99/build/my-onnxruntime/onnxruntime/core/framework/session_options.h:127:41:   required from here
/usr/include/c++/9/bits/stl_pair.h:215:11: error: ‘std::pair<_T1, _T2>::second’ has incomplete type
  215 |       _T2 second;                /// @c second is a copy of the second object
      |           ^~~~~~
In file included from /home/jf99/build/my-onnxruntime/onnxruntime/core/common/path_string.h:17,
                 from /home/jf99/build/my-onnxruntime/onnxruntime/core/common/path.h:9,
                 from /home/jf99/build/my-onnxruntime/include/onnxruntime/core/graph/graph.h:37,
                 from /home/jf99/build/my-onnxruntime/include/onnxruntime/core/graph/graph_viewer.h:6,
                 from /home/jf99/build/my-onnxruntime/onnxruntime/core/graph/graph_proto_serializer.h:6,
                 from /home/jf99/build/my-onnxruntime/onnxruntime/core/graph/graph_proto_serializer.cc:4:
/home/jf99/build/my-onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:242:10: note: forward declaration of ‘struct OrtValue’
  242 |   struct Ort##X;             \
      |          ^~~
/home/jf99/build/my-onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:255:1: note: in expansion of macro ‘ORT_RUNTIME_CLASS’
  255 | ORT_RUNTIME_CLASS(Value);
      | ^~~~~~~~~~~~~~~~~
...
make: *** [Makefile:182: all] Error 2
Traceback (most recent call last):
  File "/home/jf99/build/my-onnxruntime/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
  File "/home/jf99/build/my-onnxruntime/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/jf99/build/my-onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/jf99/build/my-onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/jf99/build/my-onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/jf99/build/my-onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
build exited with return code 1
```

### GCC / Compiler Version

`gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` and `gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`

**Comment by jf99** [comment]
After trying other versions, I can say that this issue also applies to OnnxRuntime 1.12.1 and 1.12.0. 1.11.1 is unaffected – obviously – as it does not have any abseil dependency in the first place.

**Comment by snnn** [comment]
Fixed by #13799. Will be in the next release.

**Comment by jf99** [comment]
@snnn Thanks for the quick reply on that. Notice that there are two different compiler errors in the above build log. The linked PR fixes only one of them. The other one complains that `OrtValue` is an incomplete type in [this line](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/session_options.h#L131).

I tried with commit 82d123b6c91845c7363981963ae3ba0843c5c4a5 as well as with the very recent commit cc7799835e9840d61e0ff16823b20e2be9186955. Building without abseil fails with both of them. With the latter, some additional errors show up (there might be even more if the build didn't stop after these):

```
/home/jf99/build/my-onnxruntime/onnxruntime/core/framework/allocation_planner.cc:1013:10: error: ‘deque’ is not a member of ‘std’
 1013 |     std::deque<NodeIndex> que;
      |          ^~~~~
/home/jf99/build/my-onnxruntime/onnxruntime/core/framework/allocation_planner.cc:28:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   27 | #include "nlohmann/json.hpp"
  +++ |+#include <deque>
   28 | using json = nlohmann::json;
/home/jf99/build/my-onnxruntime/onnxruntime/core/framework/allocation_planner.cc:1013:25: error: expected primary-expression before ‘>’ token
 1013 |     std::deque<NodeIndex> que;
      |                         ^
/home/jf99/build/my-onnxruntime/onnxruntime/core/framework/allocation_planner.cc:1013:27: error: ‘que’ was not declared in this scope
 1013 |     std::deque<NodeIndex> que;
      |                           ^~~
```

**Comment by AndreyOrb** [comment]
Onnx runtime vv1.15.0 announcement mentions that onnxruntime_DISABLE_ABSEIL build option will be removed, as the updated protobuf version requires abseil
