### ISSUE TITLE
[Build] fail to build for python311 on Windows using MSVC 2022

### ISSUE THREAD

**Issue by chrysophylax** [microsoft/onnxruntime#14302]
### Describe the issue

Hi,

I saw that there's no package built for python311 so I decided to try to build a local package using the instructions over at [onnx runtime docs/build](https://onnxruntime.ai/docs/build/inferencing.html) on my Windows machine.

However, I seem to error out in the configure step for CMake on a git conflict in something called blingfire-src. I am trying to build a python 3.11 bindings-compatible version that uses DirectML (`--use_dml`).

### Target platform

Windows 10

### Build script

```
python -m pip install cmake numpy
git checkout -v1.13.1
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022"  --use_dml --build_wheel --config Release --enable_pybind --build_shared_lib --skip_tests
```

### Error / output

```
[...]
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/ai-art/onnx/onnxruntime/build/Windows/Release/_deps/blingfire-subbuild
MSBuild version 17.4.1+9a89d02ff for .NET Framework
  Checking Build System
  Performing update step for 'blingfire-populate'
  Previous HEAD position was 0831265 Merge pull request #123 from gowthamrang-ds/cmake-linker-fix
  HEAD is now at 5089d31 Merge pull request #160 from TomasMorris/user/tomorri/cmake_install
  CONFLICT (modify/delete): scripts/requirements.txt deleted in Stashed changes and modified in Updated upstream.  Version Updated upstream of scripts/requirements.txt left in tree.
  Index was not unstashed.
  The stash entry is kept in case you need it again.
  CONFLICT (modify/delete): scripts/requirements.txt deleted in Stashed changes and modified in Updated upstream.  Version Updated upstream of scripts/requirements.txt left in tree.
  The stash entry is kept in case you need it again.
  CMake Error at D:/ai-art/onnx/onnxruntime/build/Windows/Release/_deps/blingfire-subbuild/blingfire-populate-prefix/tmp/blingfire-populate-gitupdate.cmake:264 (message):


    Failed to unstash changes in:
    'D:/ai-art/onnx/onnxruntime/build/Windows/Release/_deps/blingfire-src'.

    You will have to resolve the conflicts manually


C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-update.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-patch.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-configure.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-build.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-install.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\6bfee3e994f6eafef458683c82268d2f\blingfire-populate-test.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\b991037eea3b38b26b537843d573fd89\blingfire-populate-complete.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeFiles\c71ab12f8b439757b557fd689fbee7a1\blingfire-populate.rule;D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\CMakeLists.txt' exited with code 1. [D:\ai-art\onnx\onnxruntime\build\Windows\Release\_deps\blingfire-subbuild\blingfire-populate.vcxproj]
CMake Error at C:/Users/Billy/AppData/Local/Programs/Python/Python311/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1616 (message):
  Build step for blingfire failed: 1
Call Stack (most recent call first):
  C:/Users/Billy/AppData/Local/Programs/Python/Python311/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1756:EVAL:2 (__FetchContent_directPopulate)
  C:/Users/Billy/AppData/Local/Programs/Python/Python311/Lib/site-packages/cmake/data/share/cmake-3.25/Modules/FetchContent.cmake:1756 (cmake_language)
  external/onnxruntime-extensions/cmake/externals/blingfire.cmake:11 (FetchContent_Populate)
  external/onnxruntime-extensions/CMakeLists.txt:264 (include)


-- Configuring incomplete, errors occurred!
See also "D:/ai-art/onnx/onnxruntime/build/Windows/Release/CMakeFiles/CMakeOutput.log".
See also "D:/ai-art/onnx/onnxruntime/build/Windows/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "D:\ai-art\onnx\onnxruntime\\tools\ci_build\build.py", line 2812, in <module>
    sys.exit(main())
             ^^^^^^
  File "D:\ai-art\onnx\onnxruntime\\tools\ci_build\build.py", line 2693, in main
    generate_build_tree(
  File "D:\ai-art\onnx\onnxruntime\\tools\ci_build\build.py", line 1288, in generate_build_tree
    run_subprocess(
  File "D:\ai-art\onnx\onnxruntime\\tools\ci_build\build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai-art\onnx\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
 ```

### Visual Studio Version

Visual Studio 2022

**Comment by skottmckay** [comment]
Blingfire is used by [onnxruntime-extensions](https://github.com/microsoft/onnxruntime-extensions) not onnxruntime. Did you do a build with `--use_extensions` at some point? Might be worth trying a clean build (remove the existing build output directory). 

You also have two different `--config` values in your command line. I don't think that matters though - it will just use the last one.

**Comment by chrysophylax** [comment]
Oh, my, that's possible. Thank you for the pointer. I will try a clean build.

**Comment by chrysophylax** [comment]
Thank you, I do think I may have run something with extensions earlier while exploring settings - now I get much further building only python bindings+DML.

The error now seems to be a mismatch between pybind11 and files in \onnxruntime\python\onnxruntime_pybin* 
```
[...]build\Windows\Release\pybind11\src\pybind11\include\pybind11/pybind11.h(2296,30): error C2027: use of undefined type '_frame' (compiling source file [...]\onnxruntime\python\onnxruntime_pybind_state_common.cc) [ [...]\build\Windows\Release\onnxruntime_pybind11_state.vcxproj]
 [...]\Python\Python311\include\pytypedefs.h(22,16): message : see declaration of '_frame' (compiling source file  [...]\onnxruntime\python\onnxruntime_pybind_state_common.cc) [[...]\build\Windows\Release\onnxruntime_pybind11_state.vcxproj]
 [...]\build\Windows\Release\pybind11\src\pybind11\include\pybind11/pybind11.h(2295,33): error C2660: 'PyDict_GetItem': function does not take 1 arguments (compiling source file [...]\onnxruntime\python\onnxruntime_pybind_state_common.cc) [ [...]\build\Windows\Release\onnxruntime_pybind11_state.vcxproj]
 [...]\Python\Python311\include\dictobject.h(22,24): message : see declaration of 'PyDict_GetItem' (compiling source file  [...]\onnxruntime\python\onnxruntime_pybind_state_common.cc [[...]\build\Windows\Release\onnxruntime_pybind11_state.vcxproj]
 [...]\build\Windows\Release\pybind11\src\pybind11\include\pybind11/pybind11.h(2295,33): message : while trying to match the argument list '()' (compiling source
 file  [...]\onnxruntime\python\onnxruntime_pybind_state_common.cc) [ [...]\build\Windows\Release\onnxruntime_pybind11_state.vcxproj]
 ```
 
I am not sure if it's at all related, but docs for Python 3.11 mention that >3.10 , calling PyDict_GetItem additionally requires holding the GIL.

**Comment by chrysophylax** [comment]
Aha! I got it to build using 9c0c49900ef4caca50125fbb0517322af26a3d8d , python 3.11.

**Comment by chrysophylax** [comment]
For some reason it only built a 32-bit wheel, "onnxruntime_directml-1.14.0-cp311-cp311-win32.whl".
My Pyython is x86-64 and so is this Windows 10 install. VS2022 is also 64-bit.

**Comment by skottmckay** [comment]
Are you building from the Visual Studio command prompt/powershell window? That should default to x64. 

https://onnxruntime.ai/docs/build/inferencing.html#windows

build.amd64.1411.bat is really old (and probably should be removed). All it's doing it setting the VS environment to 64-bit and picking a rather old toolchain that was needed for a rather old version of CUDA.

**Comment by chrysophylax** [comment]
I was indeed running it from the VS command prompt window, not powershell.

**Comment by nums11** [comment]
Closing as resolved.
