### ISSUE TITLE
Program will stuck when creating 'Ort::Session'

### ISSUE THREAD

**Issue by baoachun** [microsoft/onnxruntime#14317]
### Describe the issue

version: 1.12 c++
cuda: 11.5

The program will stuck when creating session with CUDA provider.

### To reproduce

```
#include <iostream>

#include "onnxruntime_cxx_api.h"

using namespace std;

int main(int argc, char* argv[]) {
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
  Ort::SessionOptions session_options;

  OrtCUDAProviderOptions cuda_options;
  cuda_options.device_id = 0;
  cuda_options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearchExhaustive;
  cuda_options.gpu_mem_limit = static_cast<int>(SIZE_MAX * 1024 * 1024);
  cuda_options.arena_extend_strategy = 1;
  cuda_options.do_copy_in_default_stream = 1;
  cuda_options.has_user_compute_stream = 1;
  cuda_options.default_memory_arena_cfg = nullptr;
  session_options.AppendExecutionProvider_CUDA(cuda_options);
  session_options.SetGraphOptimizationLevel(
      GraphOptimizationLevel::ORT_ENABLE_ALL);

  const char* model_path = "opt1-new_freeze.onnx";
  Ort::Session session = Ort::Session(env, model_path, session_options);  // stuck
  std::cout << "session created success" << std::endl;

  return 0;
}
```

The gdb thread info:
![image](https://user-images.githubusercontent.com/22114318/212794299-513d935d-35b6-4431-b051-e8dd0791af38.png)

### Urgency

Yes

### Platform

Linux

### OS Version

centos7

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

f4663641764ccc3e93a617ab63ae4ff1badc2ee1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

cuda 11.5

**Comment by RyanUnderhill** [comment]
Onnxruntime 1.12 is an older version, can you try it with 1.13?

Are you required to use 1.12?

**Comment by baoachun** [comment]
> Onnxruntime 1.12 is an older version, can you try it with 1.13?
> 
> Are you required to use 1.12?

Yes, we have to use version 1.12.

I have just found that the problem is caused by without setting `SetIntraOpNumThreads`, the program is running successfully by setting `session_options.SetIntraOpNumThreads(4);` in c++. Is there no default value for this setting? In Python, if I do not set this parallelism, there will be a pthread warning. Therefore, I think this is a very important setting, and there needs to be a default value or warning if the user does not set it.

**Comment by pranavsharma** [comment]
Intra op num threads defaults to the number of physical cores. How many cores do you've on your machine? It's strange that this could be the reason for the hang.

**Comment by yuslepukhin** [comment]
This is a bug that was addressed in the 1.13.1.

**Comment by baoachun** [comment]
> Intra op num threads defaults to the number of physical cores. How many cores do you've on your machine? It's strange that this could be the reason for the hang.

48 cores

**Comment by baoachun** [comment]
The program also will stuck when turning on tensorrt even setting `SetIntraOpNumThreads`.

```
  OrtCUDAProviderOptions cuda_options;
  session_options.AppendExecutionProvider_CUDA(cuda_options);

  OrtTensorRTProviderOptions* trt_options = new OrtTensorRTProviderOptions();
  trt_options->device_id = 0;
  trt_options->trt_dump_subgraphs = 1;
  trt_options->trt_engine_cache_enable = 1;
  trt_options->trt_engine_cache_path = "./trt-cache/";
  trt_options->trt_max_workspace_size = 1073741824;
  trt_options->trt_max_partition_iterations = 1;
  trt_options->trt_min_subgraph_size = 3;
  session_options.AppendExecutionProvider_TensorRT(*trt_options);
  Ort::Session* session = new Ort::Session(env, model_path, session_options);
```

```
(gdb) bt
#0  0x00007f0b5ee7e3f0 in strlen@plt () from /data/cpp_env/lib64/libstdc++.so.6
#1  0x00007f0b5eecabf8 in std::char_traits<char>::length (__s=<optimized out>)
    at /data/cpp_env_install/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1428
#2  std::string::compare (this=<optimized out>, __s=0x35981218 "predict_330:0")
    at /data/cpp_env_install/gcc-10.2.0/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:1433
#3  0x00007f0ac3235d60 in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#4  0x00007f0ac3239c3e in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#5  0x00007f0ac323df91 in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#6  0x00007f0ac34edff5 in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#7  0x00007f0ac34ee3d9 in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#8  0x00007f0ac34eea7e in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
#9  0x00007f0b0a5ede3e in onnx2trt::ShapeTensor::ShapeTensor(nvinfer1::ITensor&, int) ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#10 0x00007f0b0a5ef257 in onnx2trt::op(onnx2trt::IImporterContext*, onnx2trt::ShapeTensor const&, onnx2trt::ShapeTensor const&, nvinfer1::ElementWiseOperation, bool, long, std::function<long (long, long)> const&&) () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#11 0x00007f0b0a5ef733 in onnx2trt::min(onnx2trt::IImporterContext*, onnx2trt::ShapeTensor const&, onnx2trt::ShapeTensor const&) ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#12 0x00007f0b0a5d3dc6 in onnx2trt::decodeOnnxStartsAndEnds(onnx2trt::IImporterContext*, onnx2trt::ShapeTensor const&, onnx2trt::ShapeTensor const&, onnx2trt::ShapeTensor&, onnx2trt::ShapeTensor&) () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#13 0x00007f0b0a5d077e in onnx2trt::(anonymous namespace)::importSlice(onnx2trt::IImporterContext*, onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&) () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#14 0x00007f0b0a5753ef in std::_Function_handler<onnx2trt::ValueOrStatus<std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> > > (onnx2trt::IImporterContext*, onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&), onnx2trt::ValueOrStatus<std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> > > (*)(onnx2trt::IImporterContext*, onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&)>::_M_invoke(std::_Any_data const&, onnx2trt::IImporterContext*&&, onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&)
    () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#15 0x00007f0b0a56a944 in onnx2trt::parseGraph(onnx2trt::IImporterContext*, onnx::GraphProto const&, bool, int*) ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
---Type <return> to continue, or q <return> to quit---
#16 0x00007f0b0a56f320 in onnx2trt::ModelImporter::importModel(onnx::ModelProto const&) ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#17 0x00007f0b0a56476a in onnx2trt::ModelImporter::parseWithWeightDescriptors(void const*, unsigned long) ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#18 0x00007f0b0a571ab6 in onnx2trt::ModelImporter::supportsModel(void const*, unsigned long, std::vector<std::pair<std::vector<unsigned long, std::allocator<unsigned long> >, bool>, std::allocator<std::pair<std::vector<unsigned long, std::allocator<unsigned long> >, bool> > >&, char const*) () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#19 0x00007f0b0a547ede in onnxruntime::TensorrtExecutionProvider::GetSupportedList(std::vector<std::pair<std::vector<unsigned long, std::allocator<unsigned long> >, bool>, std::allocator<std::pair<std::vector<unsigned long, std::allocator<unsigned long> >, bool> > >, int, int, onnxruntime::GraphViewer const&, bool*) const [clone .localalias] () from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#20 0x00007f0b0a54d4fb in onnxruntime::TensorrtExecutionProvider::GetCapability(onnxruntime::GraphViewer const&, std::vector<onnxruntime::KernelRegistry const*, std::allocator<onnxruntime::KernelRegistry const*> > const&) const ()
   from /data/cpp_env/lib64/libonnxruntime_providers_tensorrt.so
#21 0x00007f0b5fd3a0d7 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#22 0x00007f0b5fd3defe in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#23 0x00007f0b5fd3fe5d in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#24 0x00007f0b5fd40304 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#25 0x00007f0b5f60b621 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#26 0x00007f0b5f614333 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#27 0x00007f0b5f59e7c0 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#28 0x00007f0b5f5a6bb5 in ?? () from /data/cpp_env/lib64/libonnxruntime.so.1.12.0
#29 0x000000000040360a in Ort::Session::Session(Ort::Env&, char const*, Ort::SessionOptions const&) ()
#30 0x0000000000401c8f in main ()
```

```
(gdb) info thread
  Id   Target Id         Frame 
* 1    Thread 0x7f0b60643880 (LWP 101476) "onnx_test" 0x00007f0ac33388c3 in ?? () from /usr/local/TensorRT-8.4.3.1/lib/libnvinfer.so.8
  2    Thread 0x7f0b0bb6c700 (LWP 101479) "cuda-EvtHandlr" 0x00007f0b5e5f5ddd in poll () from /data/cpp_env/lib64/libc.so.6
  3    Thread 0x7f0b0b36b700 (LWP 101480) "cuda-EvtHandlr" 0x00007f0b5e5f5ddd in poll () from /data/cpp_env/lib64/libc.so.6
  4    Thread 0x7f0b0a4e0700 (LWP 101515) "onnx_test" 0x00007f0b5e5fae29 in syscall () from /data/cpp_env/lib64/libc.so.6
  5    Thread 0x7f0b09cdf700 (LWP 101516) "onnx_test" 0x00007f0b5e5fae29 in syscall () from /data/cpp_env/lib64/libc.so.6
  6    Thread 0x7f0b094de700 (LWP 101517) "onnx_test" 0x00007f0b5e5fae29 in syscall () from /data/cpp_env/lib64/libc.so.6
```
