### ISSUE TITLE
[Build] Windows 10 - Can't build DML backend with Nuget. 

### ISSUE THREAD

**Issue by canaxx** [microsoft/onnxruntime#14376]
Windows 10 - Can't build DML backend with Nuget.

After clonning the respository i try to build the ONNX library for DML backend in both VS 2019 & 2022 developer command promts with below commands.

.\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 17 2022" 		
.\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 16 2019" 

Usings "--build_nuget" with "--use_dml" argument causes build errors and nuget packages are not created where only using "--use_dml" argument causes no build errors.

On my machine ".Net6.0" & ".Net7.0" SDK's are installed. Can ".Net7.0" SDK be causing to build errors ?

### Target platform

Windows 10 - 21H1

### Build script

.\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 17 2022" 

### Error / output

D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\ApiDocs\ApiDocs.csproj geri yüklendi (446 ms
   içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Devices\
  Microsoft.ML.OnnxRuntime.Tests.Devices.csproj geri yüklendi (607 ms içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRunt
  ime.InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample.csproj geri yüklendi (674 ms içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\tools\Microsoft.ML.OnnxRuntime.PerfTool\Micr
  osoft.ML.OnnxRuntime.PerfTool.csproj geri yüklendi (519 ms içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRunt
  ime.InferenceSample.NetCoreApp\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp.csproj geri yüklendi (445 ms içind
  e).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Common\M
  icrosoft.ML.OnnxRuntime.Tests.Common.csproj geri yüklendi (717 ms içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRunt
  ime.InferenceSample.Forms\Microsoft.ML.OnnxRuntime.InferenceSample.Forms.csproj geri yüklendi (614 ms içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.On
  nxRuntime.csproj geri yüklendi (2,84 sec içinde).
  D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreA
  pp\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp.csproj geri yüklendi (2,88 sec içinde).
2023-01-20 17:31:15,142 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-01-20 17:31:15,142 util.run [INFO] - Running subprocess in 'D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp'
  dotnet msbuild OnnxRuntime.CSharp.sln '/p:Configuration="RelWithDebInfo"' '/p:OrtPackageId="Microsoft.ML.OnnxRuntime"' '/p:IsLinuxBuild="false"' '/p:OnnxRuntimeBuildDirectory="D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\build\Windows"'
MSBuild version 17.4.1+9a89d02ff for .NET
D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntim
e.InferenceSample.Forms.iOS\Microsoft.ML.OnnxRuntime.InferenceSample.Forms.iOS.csproj(162,3): error MSB4019: İçeri akta
rılan "C:\Program Files\dotnet\sdk\7.0.102\Xamarin\iOS\Xamarin.iOS.CSharp.targets" projesi bulunamadı. "C:\Program File
s\dotnet\sdk\7.0.102\\Xamarin\iOS\Xamarin.iOS.CSharp.targets" Import bildirimindeki ifadenin doğru olduğunu ve dosyanın
 diskte bulunduğunu onaylayın.
D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntim
e.InferenceSample.Forms.Android\Microsoft.ML.OnnxRuntime.InferenceSample.Forms.Android.csproj(117,3): error MSB4019: İç
eri aktarılan "C:\Program Files\dotnet\sdk\7.0.102\Xamarin\Android\Xamarin.Android.CSharp.targets" projesi bulunamadı.
"C:\Program Files\dotnet\sdk\7.0.102\\Xamarin\Android\Xamarin.Android.CSharp.targets" Import bildirimindeki ifadenin do
ğru olduğunu ve dosyanın diskte bulunduğunu onaylayın.
D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.iOS\Micros
oft.ML.OnnxRuntime.Tests.iOS.csproj(207,3): error MSB4019: İçeri aktarılan "C:\Program Files\dotnet\sdk\7.0.102\Xamarin
\iOS\Xamarin.iOS.CSharp.targets" projesi bulunamadı. "C:\Program Files\dotnet\sdk\7.0.102\\Xamarin\iOS\Xamarin.iOS.CSha
rp.targets" Import bildirimindeki ifadenin doğru olduğunu ve dosyanın diskte bulunduğunu onaylayın.
D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Droid\Micr
osoft.ML.OnnxRuntime.Tests.Droid.csproj(169,3): error MSB4019: İçeri aktarılan "C:\Program Files\dotnet\sdk\7.0.102\Xam
arin\Android\Xamarin.Android.CSharp.targets" projesi bulunamadı. "C:\Program Files\dotnet\sdk\7.0.102\\Xamarin\Android\
Xamarin.Android.CSharp.targets" Import bildirimindeki ifadenin doğru olduğunu ve dosyanın diskte bulunduğunu onaylayın.

........

Microsoft.ML.OnnxRuntime.PerfTool -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\tools\M
  icrosoft.ML.OnnxRuntime.PerfTool\bin\RelWithDebInfo\netcoreapp3.1\Microsoft.ML.OnnxRuntime.PerfTool.dll
  Microsoft.ML.OnnxRuntime.Tests.Common -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\tes
  t\Microsoft.ML.OnnxRuntime.Tests.Common\bin\RelWithDebInfo\netstandard2.0\Microsoft.ML.OnnxRuntime.Tests.Common.dll
  Microsoft.ML.OnnxRuntime.InferenceSample -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp\
  sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample\bin\Release\netstandard2.0\Microsoft.ML.OnnxRuntime.I
  nferenceSample.dll
  Microsoft.ML.OnnxRuntime.InferenceSample.Forms -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\c
  sharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample.Forms\bin\Release\netstandard2.0\Microsoft.ML.O
  nnxRuntime.InferenceSample.Forms.dll
  Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxrunt
  ime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp\bin\RelWithDebInfo\netcoreapp3.
  1\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp.dll
  Microsoft.ML.OnnxRuntime.Tests.NetCoreApp -> D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\csharp
  \test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\bin\RelWithDebInfo\netcoreapp3.1\Microsoft.ML.OnnxRuntime.Tests.NetCo
  reApp.dll
Traceback (most recent call last):
  File "D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\tools\ci_build\build.py", line 2732, in <module>
    sys.exit(main())
  File "D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\tools\ci_build\build.py", line 2685, in main
    build_nuget_package(
  File "D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\tools\ci_build\build.py", line 2077, in build_nuget_package
    run_subprocess(cmd_args, cwd=csharp_build_dir)
  File "D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\tools\ci_build\build.py", line 764, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Builds\OnnxRuntime_Microsoft\Master_2023_01_12_DML\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dotnet', 'msbuild', 'OnnxRuntime.CSharp.sln', '/p:Configuration="RelWithDebInfo"', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="D:\\Builds\\OnnxRuntime_Microsoft\\Master_2023_01_12_DML\\onnxruntime\\build\\Windows"']' returned non-zero exit status 1.

### Visual Studio Version

VS 2022 (.NET6.0 & .NET7.0)

**Comment by yuslepukhin** [comment]
It is difficult to understand the error messages.
For us, it is important to know why the publicly available packages for the purpose do not satisfy your requirements?

**Comment by canaxx** [comment]
Can you please confirm that below command is building ?

.\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 17 2022"

**Comment by yuslepukhin** [comment]
> Can you please confirm that below command is building ?
> 
> .\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 17 2022"

This command alone would not do it. One needs a series of commands that generate a Nuget specs and have a number of pre-build packages ready. The help for the command makes it clear, it is a part of a CI pipeline.

**Comment by canaxx** [comment]
Can the process be clearly documented to generate the Nuget packages ? 

.\build.bat --config RelWithDebInfo --build_shared_lib --build_nuget --use_dml --cmake_generator "Visual Studio 17 2022"

10 days ago above command was being successfully built and Nuget packages were being created. But when i try to use that Nuget packages, it was not working. Visual Studio 2022 recently had an update (to 17.4.4) and installed .Net7.0 with that update. I thought that was causing the errors. Also in the issues history there are some people who first build the Unmanaged libraries then built the C# examples manually. So that should not be a rocket science.

**Comment by skottmckay** [comment]
Typically a user wouldn't need to build the nuget package themselves, and `--build_nuget` is intended for internal usage. 

What are you trying to do? The DML EP is included in the Microsoft.AI.MachineLearning package if that you want to use that. 

https://www.nuget.org/packages/Microsoft.AI.MachineLearning/

**Comment by canaxx** [comment]
Thank you for the respond. I want to use DML backend for multi-scenario h.w environments (GPU, CPU, Onboard GPU cases) The GPU package for CUDA works with low latency. But when i install DML nuget packages i experienced that (Microsoft.ML.OnnxRuntime.DirectML) backend is broken. Thats why i tried to build the latest code with nightly commits. After some research i found below address to get nightly packages ;

https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly

I installed the nightly packages from above link but problems with broken DML backend persists such that below code gives error in runtime;

var options = new SessionOptions();
options.AppendExecutionProvider_DML(0);

var_onnxSession = new InferenceSession(model_path, options);

I dont interface same proplem with Microsoft.ML.OnnxRuntime.Gpu package. I tried above code both in VS2019 and VS2022 with same result.

**Comment by skottmckay** [comment]
Sounds like the issue to solve is why the DML EP isn't loading. Can you share the details of that error?

**Comment by canaxx** [comment]
Below are the steps to reproduce the error.

1. Open a .Net5.0 Forms project. 
2. Download latest (Microsoft.ML.OnnxRuntime.DirectML) nuget package from the below link.
   https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly
3. Put the nuget package to a folder in "D" drive (D:\\Nuget)
4. Add the "D:\\Nuget" folder to custom nuget folders in VS2022
5. Install nuget package (Microsoft.ML.OnnxRuntime.DirectML) to the project via Nuget Manager UI.
6. Debug the code till you reach the second line
  var options = new SessionOptions();
  options.AppendExecutionProvider_DML(0);   <---- At that point you receive below error

7. Below is the exception details. (stack trace)

  at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_DML(Int32 deviceId)
   at OnnxYOLODemo.YOLOv3Detector..ctor(String model_path, Boolean useDirectML) in D:\Git Repos\OnnxYoloDemo\OnnxYOLODemo\Yolo\YOLOv3Detector.cs:line 38
   at OnnxYOLODemo.MainWindow.btnStartCaptureYolov3_Click(Object sender, RoutedEventArgs e) in D:\Git Repos\OnnxYoloDemo\OnnxYOLODemo\MainWindow.xaml.cs:line 84
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at OnnxYOLODemo.App.Main()

**Comment by yuslepukhin** [comment]
Can you stop in the debugger to see which DML library is being loaded?
Check https://github.com/microsoft/onnxruntime/issues/13429

**Comment by canaxx** [comment]
From object browser and output window i can see "Microsoft.ML.OnnxRuntime.dll"  is loaded.

Exception thrown: 'Microsoft.ML.OnnxRuntime.OnnxRuntimeException' in Microsoft.ML.OnnxRuntime.dll
An unhandled exception of type 'Microsoft.ML.OnnxRuntime.OnnxRuntimeException' occurred in Microsoft.ML.OnnxRuntime.dll
[ErrorCode:RuntimeException]

**Comment by yuslepukhin** [comment]
Can your process find `DirectML.Debug.dll`?

Is it in the same folder as your executable? Is it in the PATH?

What does `where DirectML.Debug.dll` say?

https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by skottmckay** [comment]
Additionally can you either break when the exception is thrown or handle the Microsoft.ML.OnnxRuntime.OnnxRuntimeException exception to print out the error message it contains? 

Is device '0' valid for DML? If you open the Performance tab of Task Manager what device is listed as 'GPU 0' 
e.g. 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/979079/214705421-0a8e3194-48a6-4a88-b6fc-e34b29f9cb1d.png">

**Comment by canaxx** [comment]
@skottmckay 

I have on board GPU as device 0 and Nvidia gpu as device 1 on my laptop. I tested both of them and no differences in code flow. After updating to nigthly builds i can make inferencing. When i put the code in a task (Task.Run(()=>{...inferencing...})) code fails and flow closes.

@yuslepukhin 

VS Studio - "Debug/Windows/Module" doesnt show up "DirectML.Debug.dll", but code runs without exception and inferencing is done. Those dll files are near the executable if i choose target framework "x64". Other target frameworks doesnt let code run.

**Comment by skottmckay** [comment]
Have you tried adding code to catch the Microsoft.ML.OnnxRuntime.OnnxRuntimeException exception and print the error?

**Comment by nums11** [comment]
Closing as stale.
