### ISSUE TITLE
[ONNXRuntimeError] Unsupported OrtValue type with CUDA EP

### ISSUE THREAD

**Issue by laggui** [microsoft/onnxruntime#14457]
### Describe the issue

I have an ONNX model which takes multiples inputs, two of them are optional. Based on the optional inputs provided, different subgraphs are executed. The model works on the default CPU EP, but fails with the CUDA EP.

I can't distribute the original model, but I've provided a MWE that results in the same error. Sorry if the MWE is a bit long, it's just that I am creating the ONNX model + graph on the fly. I do something similar with the original model but the subgraphs are exported from PyTorch modules instead of being dummy Add and Const nodes.

![image](https://user-images.githubusercontent.com/7225623/215191960-50847766-3117-4e90-ad3c-dcd75ead9d4d.png)

Running the code below you should get the error with CUDA EP at the very last `session.run(...)` call when both optional inputs are not provided. I know that subgraph is valid because I can execute the same subgraph when it is not nested into another subraph as you can see from the test runs below.

```sh
$ python test_nested_optional.py
[27/01/2023-14:35:20] [ORTOptional] [I] [Optional] Testing w/ use_cuda=False
[27/01/2023-14:35:20] [ORTOptional] [I] [Optional] Success!
[27/01/2023-14:35:20] [ORTOptional] [I] [NestedOptional] Testing w/ use_cuda=False
[27/01/2023-14:35:20] [ORTOptional] [I] [NestedOptional] Success!
[27/01/2023-14:35:20] [ORTOptional] [I] [Optional] Testing w/ use_cuda=True
[27/01/2023-14:35:21] [ORTOptional] [I] [Optional] Success!
[27/01/2023-14:35:21] [ORTOptional] [I] [NestedOptional] Testing w/ use_cuda=True
2023-01-27 14:35:21.723113525 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code ret
urned while running If node. Name:'If.OptionalHasElement.x3' Status Message: Unsupported OrtValue type.
Traceback (most recent call last):
  File "test_hasopt.py", line 302, in <module>
    test_nested_optional_input(use_cuda=True)
  File "test_hasopt.py", line 288, in test_nested_optional_input
    ort_outs = session.run([output_name], ort_inputs)[0]
  File "/home/prime/miniconda3/envs/orttorch/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running If node. Name:'If.OptionalHasElement.x3' Status Message: Unsupported OrtValue type.
```

### To reproduce

```py
from copy import deepcopy
from typing import Optional, Sequence, Tuple

import numpy as np
import onnxruntime as ort
from onnx import ModelProto, NodeProto, TensorProto, ValueInfoProto, checker, helper

from common.logging import get_logger

# Default logger
logger = get_logger("ORTOptional")


def make_vi_like(vi: ValueInfoProto, name: str) -> ValueInfoProto:
    """Makes a copy of `vi` with a new name."""
    new_vi = deepcopy(vi)
    new_vi.name = name
    return new_vi


def make_optional_tensor_value_info(
    name: str, elem_type: int, shape: Sequence[int]
) -> ValueInfoProto:
    """Makes a `ValueInfoProto` with optional type."""
    tensor_type_proto = helper.make_tensor_type_proto(
        elem_type=elem_type,
        shape=shape,
    )
    opt_type_proto = helper.make_optional_type_proto(tensor_type_proto)

    vi = helper.make_tensor_value_info(name, elem_type, shape)
    vi.type.CopyFrom(opt_type_proto)
    return vi


def make_optional_vi(vi: ValueInfoProto, name: Optional[str] = None) -> ValueInfoProto:
    """Makes a copy of `vi` with optional type."""
    name = name or vi.name + ".opt"
    vi_type = vi.type.tensor_type
    vi_shape = [d.dim_param if d.dim_param else d.dim_value for d in vi_type.shape.dim]
    opt_vi = make_optional_tensor_value_info(name, vi_type.elem_type, vi_shape)
    return opt_vi


def make_const(
    vi: ValueInfoProto, name: str, value: int = 0
) -> Tuple[ValueInfoProto, NodeProto, TensorProto]:
    """Creates a constant 1D tensor from `vi`."""
    const_vi = make_vi_like(vi, name)
    const_shape = [d.dim_value for d in vi.type.tensor_type.shape.dim]
    const_shape_tensor = helper.make_tensor(
        f"{name}.shape", TensorProto.INT64, [len(const_shape)], const_shape
    )
    const_fill = helper.make_tensor(
        f"{name}.const.value", const_vi.type.tensor_type.elem_type, [1], [value]
    )
    const_node = helper.make_node(
        "ConstantOfShape",
        inputs=[const_shape_tensor.name],
        outputs=[const_vi.name],
        name=f"ConstantOfShape.{name}",
        value=const_fill,
    )
    return const_vi, const_node, const_shape_tensor


def make_opt() -> ModelProto:
    """Creates a simple graph with (`optional(x1)`, `x2`) tensor inputs."""
    x1_vi = helper.make_tensor_value_info("x1", TensorProto.FLOAT, [1, 2])
    x2_vi = helper.make_tensor_value_info("x2", TensorProto.FLOAT, [1, 2])
    y_vi = helper.make_tensor_value_info("y", TensorProto.FLOAT, [1, 2])
    opt_x1_vi = make_optional_vi(x1_vi, name="x1.opt")

    # Add subgraph
    y1_vi = make_vi_like(y_vi, "y.add")
    input_get_elem_node = helper.make_node(
        "OptionalGetElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_vi.name],
        name="OptionalGetElement.Input",
    )
    add_node = helper.make_node(
        "Add", inputs=[x1_vi.name, x2_vi.name], outputs=[y1_vi.name], name="Add_Op"
    )
    add_subgraph = helper.make_graph(
        [input_get_elem_node, add_node],
        name="add-x1-x2-subgraph",
        inputs=[],
        outputs=[y1_vi],
        value_info=[opt_x1_vi, x1_vi, x2_vi],
    )

    # Add const subgraph
    y2_vi = make_vi_like(y_vi, "y.add.const")
    const_vi, const_node, const_shape_tensor = make_const(x1_vi, "x1.const", value=1)
    add_const_node = helper.make_node(
        "Add",
        inputs=[const_vi.name, x2_vi.name],
        outputs=[y2_vi.name],
        name="Add_Const",
    )
    add_const_subgraph = helper.make_graph(
        [const_node, add_const_node],
        name="add-x2-const-subgraph",
        inputs=[],
        outputs=[y2_vi],
        value_info=[const_vi, x2_vi],
        initializer=[const_shape_tensor],
    )

    # Construct main graph
    x1_has_elem_vi = helper.make_tensor_value_info(
        "x1_has_elem",
        TensorProto.BOOL,
        shape=[],  # scalar
    )
    x1_has_elem_node = helper.make_node(
        "OptionalHasElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_has_elem_vi.name],
        name="OptionalHasElement.x1",
    )
    if_input_node = helper.make_node(
        "If",
        inputs=[x1_has_elem_vi.name],  # condition
        outputs=[y_vi.name],
        name="If.OptionalHasElement.x1",
        then_branch=add_subgraph,
        else_branch=add_const_subgraph,
    )
    graph = helper.make_graph(
        [x1_has_elem_node, if_input_node],
        "opt-graph",
        [opt_x1_vi, x2_vi],
        [y_vi],
        value_info=[x1_has_elem_vi],
    )

    m = helper.make_model(
        graph,
        opset_imports=[
            helper.make_opsetid("", 15),
        ],
    )
    checker.check_model(m, full_check=True)
    return m


def make_opt_nested() -> ModelProto:
    """Creates a nested graph with (`optional(x1)`, `x2`, `optional(x3)`) tensor inputs."""
    # Make nested subgraph w/ optional `x1` input
    subgraph = make_opt().graph
    opt_x1_vi, x2_vi = list(subgraph.input)
    # Clear inputs and keep `optional(x1)` as value_info
    subgraph.value_info.append(opt_x1_vi)
    subgraph.ClearField("input")

    # Additional inputs/outputs
    x3_vi = make_vi_like(x2_vi, "x3")
    opt_x3_vi = make_optional_vi(x3_vi, "x3.opt")
    out_vi = make_vi_like(subgraph.output[0], "out")
    add_const_out_vi = make_vi_like(out_vi, "out.1")

    # Make other subgraph for `x3` input operations
    x3_get_elem_node = helper.make_node(
        "OptionalGetElement",
        inputs=[opt_x3_vi.name],
        outputs=[x3_vi.name],
        name="OptionalGetElement.x3",
    )

    const_vi, const_node, const_shape_tensor = make_const(x3_vi, "x3.const", value=2)
    add_const_node = helper.make_node(
        "Add",
        inputs=[const_vi.name, x3_vi.name],
        outputs=[add_const_out_vi.name],
        name="Add_Const.1",
    )
    add_const_subgraph = helper.make_graph(
        [const_node, x3_get_elem_node, add_const_node],
        name="add-x3-const-subgraph",
        inputs=[],
        outputs=[add_const_out_vi],
        value_info=[opt_x3_vi, x3_vi, const_vi],
        initializer=[const_shape_tensor],
    )

    x3_has_elem_vi = helper.make_tensor_value_info(
        "x3_has_elem",
        TensorProto.BOOL,
        shape=[],  # scalar
    )
    x3_has_elem_node = helper.make_node(
        "OptionalHasElement",
        inputs=[opt_x3_vi.name],
        outputs=[x3_has_elem_vi.name],
        name="OptionalHasElement.x3",
    )
    if_input_node = helper.make_node(
        "If",
        inputs=[x3_has_elem_vi.name],  # condition
        outputs=[out_vi.name],
        name="If.OptionalHasElement.x3",
        then_branch=add_const_subgraph,
        else_branch=subgraph,
    )
    graph = helper.make_graph(
        [x3_has_elem_node, if_input_node],
        "graph",
        [opt_x1_vi, x2_vi, opt_x3_vi],
        [out_vi],
        value_info=[x3_has_elem_vi],
    )

    m = helper.make_model(
        graph,
        opset_imports=[
            helper.make_opsetid("", 15),
        ],
    )
    checker.check_model(m, full_check=True)

    return m


def test_optional_input(use_cuda: bool = False) -> None:
    """Validate ONNX model w/ optional input."""
    logger.info(f"[Optional] Testing w/ use_cuda={use_cuda}")
    model = make_opt()
    output_name = model.graph.output[0].name
    providers = ("CUDAExecutionProvider" if use_cuda else "CPUExecutionProvider",)
    session = ort.InferenceSession(
        model.SerializeToString(),
        providers=providers,
    )

    x1 = np.random.randn(1, 2).astype(np.float32)
    x2 = np.random.randn(1, 2).astype(np.float32)

    inputs = session.get_inputs()

    # When x1 is not provided, the output should be `x2 + const` (const=1)
    ort_inputs = {inputs[0].name: None, inputs[1].name: x2}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x2 + 1)

    # When x1 is provided, the output should be `x1 + x2`
    ort_inputs = {inputs[0].name: x1, inputs[1].name: x2}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x1 + x2)

    logger.info("[Optional] Success!")


def test_nested_optional_input(use_cuda: bool = False) -> None:
    """Validate ONNX model w/ nested subgraph conditionned on optional inputs."""
    logger.info(f"[NestedOptional] Testing w/ use_cuda={use_cuda}")
    model = make_opt_nested()
    output_name = model.graph.output[0].name
    providers = ("CUDAExecutionProvider" if use_cuda else "CPUExecutionProvider",)
    session = ort.InferenceSession(
        model.SerializeToString(),
        providers=providers,
    )

    x1 = np.random.randn(1, 2).astype(np.float32)
    x2 = np.random.randn(1, 2).astype(np.float32)
    x3 = np.random.randn(1, 2).astype(np.float32)
    inputs = session.get_inputs()

    # When x3 is provided, output should always be `x3 + const` (const=2)
    ort_inputs = {inputs[0].name: x1, inputs[1].name: x2, inputs[2].name: x3}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x3 + 2)

    ort_inputs = {inputs[0].name: None, inputs[1].name: x2, inputs[2].name: x3}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x3 + 2)

    # When x3 is not provided...
    # and x1 is provided, the output should be `x1 + x2`
    ort_inputs = {inputs[0].name: x1, inputs[1].name: x2, inputs[2].name: None}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x1 + x2)

    # and x1 not provided, the output should be `x2 + const` (const=1)
    ort_inputs = {inputs[0].name: None, inputs[1].name: x2, inputs[2].name: None}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x2 + 1)

    logger.info("[NestedOptional] Success!")


if __name__ == "__main__":
    # Remove CleanUnusedInitializersAndNodeArgs warnings
    ort.set_default_logger_severity(3)

    test_optional_input(use_cuda=False)
    test_nested_optional_input(use_cuda=False)

    test_optional_input(use_cuda=True)
    test_nested_optional_input(use_cuda=True)

```

### Platform

Linux

### OS Version

Ubuntu 20.04.2 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by RyanUnderhill** [comment]
Is it easy to try this with a later version of OnnxRuntime?

**Comment by laggui** [comment]
> Is it easy to try this with a later version of OnnxRuntime?

Thanks for the response! Yes, I get the same error with onnxruntime-gpu 1.13.1.

**Comment by laggui** [comment]
@RyanUnderhill Btw the same model (original and MWE) also works w/ OpenVINO EP. I've tried digging into the source, and from what I could see at first glance it seems to be related to input/output copy across devices, which would explain why only CUDA EP fails.

https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/utils.cc#L127

But still not sure why the first model with a single optional input executes correctly but the other model with two optional inputs (nested subgraphs) doesn't.
