### ISSUE TITLE
[Web] Runtime error using `onnxruntime-node` with webpack

### ISSUE THREAD

**Issue by abgoswam** [microsoft/onnxruntime#14505]
### Describe the issue

We have a  example of  using `onnxruntime-node` in a standalone TS file
- [gist](https://gist.github.com/abgoswam/9896de2e365b1716c9c0eb210c4b42a3)
- onnxruntime-node@1.13.1
- this runs successfully

However when we have the same code inside a `webpack` bundler, we hit issues at runtime:

```
     TypeError: o.binding.InferenceSession is not a constructor
      at new a (/home/abgoswam/_hackerreborn/copilot5/dist/webpack:/node_modules/onnxruntime-node/dist/backend.js:24:57)
      at /home/abgoswam/_hackerreborn/copilot5/dist/webpack:/node_modules/onnxruntime-node/dist/backend.js:66:29
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
``` 

**Root cause:**

- for using `onnxruntime-node`, we need the  folder structure  to be maintained for the  `.node` files and the dynamic library files
- this needs to be done for all 3 platforms (darwin/linux/win32) X  2 architectures (arm64/x64)

![image](https://user-images.githubusercontent.com/8822956/215842822-4b9a365f-06ab-4788-b3e5-86acf232f853.png)

unable to correctly locate these files result in runtime error.

**Approaches tried** 

1. using webpack [node-loader](https://webpack.js.org/loaders/node-loader/)
   - this renames the `.node` files and places them inside `dist`. 
   - but the associated files  e.g. `libonnxruntime.so.1.13.1` are not placed properly. 
       - folder structure of `darwin/linux/win32 platforms`  is not maintained
   - did not work

**Summary**

Bundling `onnxruntime-node` using webpack hits issues at runtime

Would it be possible to have a `webpack` example  for `onnxruntime-node` ?

### To reproduce

use webpack with `onnxruntime-node@1.13.1`

### Urgency

hacky approach: we use  `onnxruntime-web` instead to avoid dealing with  files not being placed correctly

https://github.com/microsoft/onnxruntime/issues/14504

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-node@1.13.1

### Execution Provider

Other / Unknown

**Comment by abgoswam** [comment]
cc @fs-eire

**Comment by hamidrezabstn** [comment]
Same issue here

**Comment by fs-eire** [comment]
we added a [new example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/quick-start_onnxruntime-node-bundler) for using bundlers on ort-node with nodejs. in this example we use `webpack-node-externals` in webpack config so that it preserves the folder structure.

**Comment by vlinder** [comment]
Best would be to build all binary code into the `.node` files and then use `node-loader` to load them. The `node-loader` has no feature to figure out what modules the .node files later load. (.dll, .so, .dylib..)

**Comment by vlinder** [comment]
It works but is a manual solution that can break with any update. Extra tricky with package managers like pnpm with its package version specific folder structure.
