### ISSUE TITLE
`convert_onnx_models_to_ort` doesn't work on `large_model` onnx files (zip with tensor values stored externally)

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#14697]
### Describe the issue

I've got a ~3GB model produced using `tf2onnx.convert.from_function(..., large_model=True, opset=16)`.

Here's what the `large_model` option does:

> large_model: When set, creates a zip file containing the ONNX protobuf model and large tensor values stored externally. This allows for converting models whose size exceeds the 2 GB.

The `onnx` file that is produced can't be converted with `onnxruntime.tools.convert_onnx_models_to_ort` due to an error - I think it expects a 'normal' onnx file.

### To reproduce

1. Download this: https://drive.google.com/file/d/1--6efTeiLoCCeTifDzABpHySmkJ4Bzkg/view?usp=sharing
2. Run this: `python -m onnxruntime.tools.convert_onnx_models_to_ort scheduler_loop_body.onnx`

And you'll get this error:

```
Converting models with optimization style 'Fixed' and level 'all'
Converting optimized ONNX model /content/scheduler_loop_body.onnx to ORT format model /content/scheduler_loop_body.ort
Error converting /content/scheduler_loop_body.onnx: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /content/scheduler_loop_body.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/tools/convert_onnx_models_to_ort.py", line 363, in <module>
    convert_onnx_models_to_ort()
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/tools/convert_onnx_models_to_ort.py", line 302, in convert_onnx_models_to_ort
    converted_models = _convert(
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/tools/convert_onnx_models_to_ort.py", line 159, in _convert
    _ = ort.InferenceSession(
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /content/scheduler_loop_body.onnx failed:Protobuf parsing failed.
```

### Urgency

Blocks conversion of all models >2GB.

### Platform

Linux

### OS Version

Ubuntu 18.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by josephrocca** [comment]
Wondering if anyone has managed to take a look at this? 

Here's a colab that reproduces the problem whole process (including producing the ONNX model): https://colab.research.google.com/gist/josephrocca/059d723b4b6b4b36de4ca1388906fe61/scheduler_step.ipynb

I've tested it just now to make sure that it's still a valid reproduction. It uses the TPU runtime simply because that one has the most RAM, and IIRC the normal CPU runtime ran out of ram.

**Comment by iliemihai** [comment]
I also have this problem

**Comment by thiagocrepaldi** [comment]
FYI @fatcat-z and @xiaowuhu
