### ISSUE TITLE
[Performance]  test_parity_gelu.py fails for MIGraphX runs with optimizers on

### ISSUE THREAD

**Issue by TedThemistokleous** [microsoft/onnxruntime#14702]
### Describe the issue

Unable to run this test unless optimizers are turned off. 

Getting the following output:

```
======================================================================
FAIL: test_cuda (__main__.TestGeluParity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_parity_gelu.py", line 226, in test_cuda
    self.run_one(self.optimized, gpu, hidden_size=self.hidden_size, formula=i)
  File "test_parity_gelu.py", line 181, in run_one
    self.run_test(
  File "test_parity_gelu.py", line 177, in run_test
    self.assertTrue(num_failure == 0, "Failed: " + test_name)
AssertionError: False is not true : Failed: device=cuda, float16=False, optimized=True, batch_size=4, sequence_length=2, hidden_size=768, formula=0, fp32_gelu_op=True

----------------------------------------------------------------------
Ran 2 tests in 10.867s

```

Interestingly I'm also seeing that we're using the ROCm EP instead of the MIGraphX EP during these runs

```
2023-02-15 22:41:15.991749495 [I:onnxruntime:, inference_session.cc:276 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2023-02-15 22:41:15.991786273 [I:onnxruntime:, inference_session.cc:294 ConstructorCommon] Dynamic block base set to 0
2023-02-15 22:41:16.056674229 [I:onnxruntime:, inference_session.cc:1233 Initialize] Initializing session.
2023-02-15 22:41:16.056765139 [I:onnxruntime:, session_state.cc:98 SetupAllocators] Allocator already registered for OrtMemoryInfo:[name:Cuda id:0 OrtMemType:0 OrtAllocatorType:1 Device:[DeviceType:1 MemoryType:0 DeviceId:0]]. Ignoring allocator from ROCMExecutionProvider
2023-02-15 22:41:16.056774968 [I:onnxruntime:, session_state.cc:98 SetupAllocators] Allocator already registered for OrtMemoryInfo:[name:CudaPinned id:0 OrtMemType:-1 OrtAllocatorType:1 Device:[DeviceType:0 MemoryType:2 DeviceId:0]]. Ignoring allocator from ROCMExecutionProvider
2023-02-15 22:41:16.056797951 [I:onnxruntime:, session_state.cc:98 SetupAllocators] Allocator already registered for OrtMemoryInfo:[name:MIP_CPU id:0 OrtMemType:-2 OrtAllocatorType:1 Device:[DeviceType:0 MemoryType:0 DeviceId:0]]. Ignoring allocator from ROCMExecutionProvider
2023-02-15 22:41:16.056983358 [V:onnxruntime:, session_state.cc:1116 VerifyEachNodeIsAssignedToAnEp] Node placements
2023-02-15 22:41:16.056993357 [V:onnxruntime:, session_state.cc:1119 VerifyEachNodeIsAssignedToAnEp]  All nodes placed on [ROCMExecutionProvider]. Number of nodes: 1
```

I've added log output with verbose debugging, as well as MIGraphX graph passes when we optimize the model

[gelu_debug_migx_compile_no_rocmEP_optimizer.log](https://github.com/microsoft/onnxruntime/files/10749251/gelu_debug_migx_compile_no_rocmEP_optimizer.log)
[gelu_debug_migx_compile_optimizer_on.log](https://github.com/microsoft/onnxruntime/files/10749249/gelu_debug_migx_compile_optimizer_on.log)
[gelu_debug_migx_compile_no_optimizers.log](https://github.com/microsoft/onnxruntime/files/10749250/gelu_debug_migx_compile_no_optimizers.log)

Not sure how to proceed with this one as everything appears to pass and work correctly when MIGraphX isn't using optimized onnx here.

### To reproduce

Run test_parity_gelu.py.

### Urgency

Blocking

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

Main - feb 15th

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

MIGraphX

### Execution Provider Library Version

ROCm 5.4.2

### Model File

GELU testing. 

### Is this a quantized model?

Unknown

**Comment by TedThemistokleous** [comment]
ping @cloudhan @PeixuanZuo

**Comment by PeixuanZuo** [comment]
Does MIGraphX support `Gelu`? I didn't find it in `mgx_supported_ops`(https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc#L810). I can see the log `All nodes placed on [ROCMExecutionProvider]` in [gelu_debug_migx_compile_no_rocmEP_optimizer.log](https://github.com/microsoft/onnxruntime/files/10749251/gelu_debug_migx_compile_no_rocmEP_optimizer.log)

**Comment by PeixuanZuo** [comment]
I added `Gelu` in `mgx_supported_ops` and get this log: `MIGraphX Error: /migraphx/src/src/onnx/onnx_parser.cpp:328: parse_graph: Unknown operator: Gelu`. I am not sure if it's a right change.

**Comment by TedThemistokleous** [comment]
I think in this case things work if we turn off optimizer.py. I currently have a changeset which turns off optimizer with a command line flag for the test.  I think since you're using unittest for this in python, it makes things a tad more cumbersome instead of using something like argparse

I'll have a fix around this tomorrow. Currently 1:10 AM here. 

Need to work out some small details with passing flags but I think this is close to working:

https://github.com/TedThemistokleous/onnxruntime/blob/42caee9a3b5f6c609c77e6141e7c457ae51e62f6/onnxruntime/test/python/transformers/test_parity_gelu.py#L229

I think if I can give you a change that turns off optimizer on command line, that will allow MIGraphX to do the optimization instead, and THEN run the test accordingly. 

I'll add an option for log level too so we can see the proper output per test run as on the MIGraphX end, we typically check for the correct EP running, proper hand offs between fallback EPs and additional info via the session_options in our inference sessions. 

let me know if this is a viable path forward.

**Comment by PeixuanZuo** [comment]
It sounds good to me, please have a good rest first.

**Comment by TedThemistokleous** [comment]
PR has been merged. . Thanks for the time @PeixuanZuo @tianleiwu
