### ISSUE TITLE
Dependency Problem (java onnxruntime)

### ISSUE THREAD

**Issue by brr53** [microsoft/onnxruntime#14787]
### Describe the issue

On some windows devices, we get the following error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\1\onnxruntime-java16314451339751629608\onnxruntime.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:765)
        at java.base/java.lang.System.load(System.java:1835)
        at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:332)
        at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:139)
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:29)

I'm not sure what causes this to happen on some devices but not all. We use the same java version on each device and same Windows 2019 operating system. 

### To reproduce

The below line is all that is needed for testing. 

OrtEnvironment.getEnvironment(); 

Maven setup. 
        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.13.1</version>
        </dependency>

### Urgency

As soon as possible. Onnxruntime is unusable on many devices currently.

### Platform

Windows

### OS Version

2019

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

Default CPU

**Comment by brr53** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe installing this manually fixed it. How can we do it automatic?

**Comment by Craigacp** [comment]
The ORT native binary is compiled by the VS toolchain, so it needs the redistributable which provides the libraries that it uses.
