### ISSUE TITLE
Running T5 export ONNX example leads to shape inference error 

### ISSUE THREAD

**Issue by brevity2021** [microsoft/onnxruntime#14963]
### Describe the issue

I was trying to get the t5 conversion example in the onnxruntime repo working since I was hoping to port the mixed precision technique to a similar model. But running the example itself gives me errors coming from shape inference. 

I am wondering if this is still a good example or not. If yes, what can we do to avoid the shape inference issue?
@tianleiwu it seems that you were working on this code. Can you please help?

I was running the command
`$python ./onnxruntime/python/tools/transformers/models/t5/convert_to_onnx.py -m t5-base -o --use_gpu -p fp16`

Got the error:

```
Arguments:Namespace(model_name_or_path='t5-base', model_type='t5', cache_dir='./cache_models', output='./onnx_models', optimize_onnx=True, use_gpu=True, precision=<Precision.FLOAT16: 'fp16'>, verbose=False, use_external_data_format=False, use_decoder_start_token=False, overwrite=False, disable_auto_mixed_precision=False, separate_encoder_and_decoder_init=False, use_int64_inputs=False)
PyTorch Version:1.13.1+cu117
Transformers Version:4.26.1
Onnxruntime Version:1.14.1
Graph optimization for T5 is not implemented yet.
Model name:encoder_decoder_init
Skip exporting: existed ONNX model ./onnx_models/t5-base_encoder_decoder_init.onnx
Optimizing model to ./onnx_models/t5-base_encoder_decoder_init_fp16.onnx
Removed 102 Cast nodes with output type same as input
Fused Reshape: 1
Removed 3 nodes
Remove reshape node /t5_encoder/encoder/Reshape since its input shape is same as output: ['batch_size', 'encode_sequence_length']
Remove reshape node /t5_decoder_init/decoder/Reshape since its input shape is same as output: ['batch_size', '1']
Fused RelativePositionBias: 2
Removed 46 nodes
opset version: 12
fp32 op: {'Add', 'ReduceMean', 'Sqrt', 'Relu', 'Pow', 'Div', 'Mul', 'Softmax'} fp16 op: {'Transpose', 'Shape', 'Reshape', 'Unsqueeze', 'RelativePositionBias', 'Cast', 'Sub', 'Constant', 'Concat', 'MatMul', 'ConstantOfShape', 'Gather'}
Found last MatMul node for logits: /t5_decoder_init/lm_head/MatMul
auto_mixed_precision parameters: {'keep_io_types': [], 'op_block_list': ['Pow', 'ReduceMean', 'Add', 'Sqrt', 'Div', 'Mul', 'Softmax', 'Relu'], 'node_block_list': [], 'force_fp16_initializers': True}
Traceback (most recent call last):
  File "/home/xx/onnxruntime/./onnxruntime/python/tools/transformers/models/t5/convert_to_onnx.py", line 272, in <module>
    main()
  File "/home/xx/onnxruntime/./onnxruntime/python/tools/transformers/models/t5/convert_to_onnx.py", line 251, in main
    output_paths = export_onnx_models(
  File "/home/xx/onnxruntime/./onnxruntime/python/tools/transformers/models/t5/convert_to_onnx.py", line 199, in export_onnx_models
    T5Helper.optimize_onnx(
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/t5_helper.py", line 254, in optimize_onnx
    T5Helper.auto_mixed_precision(m)
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/t5_helper.py", line 218, in auto_mixed_precision
    onnx_model.convert_float_to_float16(use_symbolic_shape_infer=True, **parameters)
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/../../onnx_model.py", line 619, in convert_float_to_float16
    model = shape_infer_helper.infer_shapes(model, auto_merge=True, guess_output_rank=False)
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/../../../symbolic_shape_infer.py", line 2537, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/../../../symbolic_shape_infer.py", line 2299, in _infer_impl
    self._onnx_infer_single_node(node)
  File "/home/xx/onnxruntime/onnxruntime/python/tools/transformers/models/t5/../../../symbolic_shape_infer.py", line 476, in _onnx_infer_single_node
    self.tmp_mp_ = shape_inference.infer_shapes(self.tmp_mp_)
  File "/home/xx/onnxruntime/venv/lib/python3.9/site-packages/onnx/shape_inference.py", line 40, in infer_shapes
    inferred_model_str = C.infer_shapes(
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [TypeInferenceError] Cannot infer type and shape for node name encoder_1. No opset import for domaincom.microsoft optype RelativePositionBias
```

### To reproduce

I was running `python ./onnxruntime/python/tools/transformers/models/t5/convert_to_onnx.py -m t5-base -o --use_gpu -p fp16` with the latest onnx repo

Hardware: `aws g5.2xlarge` instance (a10g GPU)
PyTorch Version:1.13.1+cu117
Transformers Version:4.26.1
Onnxruntime Version:1.14.1

### Urgency

We need mixed precision urgently for our model (pegasus architecture) export to ONNX, so any help would be appreciated!

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.7

**Comment by wangyems** [comment]
we'll soon push the optimization and fix to the t5 model

**Comment by tianleiwu** [comment]
For this, it need update symbolic shape inference for RelativePositionBias. @wangyems is working on this: https://github.com/microsoft/onnxruntime/pull/14967

@brevity2021, 
BTW, we have some kernel optimization for T5 is in pull request:
https://github.com/microsoft/onnxruntime/pull/14928
You might wait until that PR merged and use nightly package to evaluate all optimizations.

**Comment by brevity2021** [comment]
Thank you @wangyems  and @tianleiwu ! 

Actually, I am more interested in porting the mixed precision technique in this T5 example folder to [Pegasus](https://huggingface.co/docs/transformers/model_doc/pegasus) model exported to ONNX. I saw some related discussion in this [issue](https://github.com/microsoft/onnxruntime/issues/11119) but it was about one year ago. 

Wonder if there are any new thoughts on the mixed precision conversion for models unable to use fp16. @tianleiwu you mentioned in the above issue that "using float16 for past state (make sure past_key_values inputs and present outputs are in float16) bring most performance gain, and MatMul (and Attention) computed in fp16 has slight performance gain". Does it still hold? 

Maybe it's not something you are working on right now, but appreciate it if there are any insights!

**Comment by tianleiwu** [comment]
The [fp16 conversion tool](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/float16.py) is comprehensive. It could force some nodes or operators to run in float32 by node_block_list or op_block_list. I think it shall be able to apply to Pegasus model. 

You will need to do some experiments to evaluate precision and latency to find the best trade-off setting.
For mixed precision conversion, the rule still hold that you can put MatMul and Attention to run in fp16. Depending on tolerance of precision loss, you might need put normalization (like LayerNormalization, SkipLayerNormalization etc) and activation (Like Gelu etc) to run in fp32.
