### ISSUE TITLE
[Build] static assertion fails whel building from source with GCC 13.0.1

### ISSUE THREAD

**Issue by panthuncia** [microsoft/onnxruntime#14991]
### Describe the issue

Static assertion static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free); fails.

I've seen other people with similar issues when using very old versions of GCC- is the newest version of GCC also incompatible?

If not, what might be causing this issue?

Thanks!

### Target platform

Raspbian Stretch on Raspberry Pi 3B+

### Build script

./build.sh

### Error / output

[ 26%] Built target absl_cord
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/cpuid_info.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/cpuid_uarch.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/denormal.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/helper.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/logging/capture.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/logging/logging.cc.o
/onnxruntime/onnxruntime/core/common/logging/logging.cc: In constructor ‘onnxruntime::logging::LoggingManager::LoggingManager(std::unique_ptr<onnxruntime::logging::ISink>, onnxruntime::logging::Severity, bool, InstanceType, const std::string*, int)’:
/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:86: error: static assertion failed
  111 |     static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
CMakeFiles/onnxruntime_common.dir/build.make:145: recipe for target 'CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/logging/logging.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_common.dir/onnxruntime/onnxruntime/core/common/logging/logging.cc.o] Error 1
CMakeFiles/Makefile2:1687: recipe for target 'CMakeFiles/onnxruntime_common.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_common.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/onnxruntime/tools/ci_build/build.py", line 2769, in <module>
    sys.exit(main())
  File "/onnxruntime/tools/ci_build/build.py", line 2665, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/onnxruntime/tools/ci_build/build.py", line 1420, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/onnxruntime/tools/ci_build/build.py", line 769, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.

### GCC / Compiler Version

GCC 13.0.1 20230308

**Comment by skottmckay** [comment]
Can you please provide the cmake output where it lists the compiler used? 

Are you running a 32 or 64-bit OS?

I'm able to build on a Raspberry Pi B 3 rev 1.2 with gcc 8.3. 64-bit OS though. 

cmake output showing compiler version:
> -- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
