### ISSUE TITLE
[Web] TypeError: Cannot read properties of undefined (reading 'inputs')

### ISSUE THREAD

**Issue by iantimmis** [microsoft/onnxruntime#15006]
### Describe the issue

I've converted my PyTorch model into ONNX so that I can run inference in the browser. When trying to just create an ort.InferenceSession with this onnx file, I get the following error.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'inputs')
    at graph.ts:644:35
    at Array.forEach (<anonymous>)
    at p.finalizeGraph (graph.ts:643:29)
    at p.transformGraph (graph.ts:576:10)
    at new p (graph.ts:155:10)
    at Object.from (graph.ts:83:7)
    at e.Model.loadFromOnnxFormat (model.ts:44:25)
    at e.Model.load (model.ts:22:14)
    at session.ts:93:19
    at e.Profiler.event (instrument.ts:337:17)
```

### To reproduce

To trace the PyTorch model:

```python
with torch.no_grad():
        pytorch_out = model(input_tensor)
        jit_model = torch.jit.trace(model, input_tensor)
```

To export the model to ONNX

I saw a semi-similar issue that made it seem as if I had to turn on `keep_initializers_as_inputs`, so I tried setting that to True (where it was false before). Neither worked.

```python
torch.onnx.export(
        model,
        dummy_tensor,
        output_file,
        export_params=True,
        keep_initializers_as_inputs=True,
        opset_version=12,
        input_names=['input'],
        output_names=['output'])
```

To run the model in Javascript:

```javascript
const options = { executionProviders: ['webgl'], graphOptimizationLevel: 'all' };   
const session = await ort.InferenceSession.create('model.onnx', options);
```

Model found here: https://file.io/fW3WXwt9ecKp

### Urgency

Urgent to make progress on our product

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### Execution Provider

WebGL

**Comment by iantimmis** [comment]
I forgot to mention, creating an InferenceSession in Python with this same model works.

**Comment by skottmckay** [comment]
Possibly something is going wrong with the optimizations being done in the js code. When you run using python the native optimizers are used. 

Looking at the model only the Conv+Clip fusion seems likely to be the issue.

@fs-eire or @xzhu1900 any ideas

**Comment by iantimmis** [comment]
@skottmckay @fs-eire Any update on this?

**Comment by fs-eire** [comment]
sorry I came late. could you re-share the model as it is deleted now

**Comment by iantimmis** [comment]
Ah, I guess this website deletes the file after a single download. Unless someone jumps in here and downloads it first, this link should work: https://file.io/0ZaOJP2O7ALU

**Comment by shalvamist** [comment]
Hi iantimmis,

I reviewed the issue and was able to reproduce. it seems to be a problem with the JS graph parsing logic. 
I have a [PR ](https://github.com/microsoft/onnxruntime/pull/15185) to fix the issue and I was able to run the model locally on my side using ORT Web. 

I hope once this PR is merged you can pull latest and try it on your end with no other issues.

**Comment by erikvdplas** [comment]
I am looking to test your PR in my web app, since I am having this exact issue when using the WebGL execution backend. How can I install it?

**Comment by shalvamist** [comment]
Hi @erikvdplas,

This PR was merged last week. 
So, I would try to use onnxruntime-web package, it should have the fix integrated at this point. 
Please let me know if you face the same problem using the latest maybe it's a different issue that needs examination. 

Thanks

**Comment by JeroenMols** [comment]
Hi @shalvamist, 

Looking at the NPM releases, the last "dev" release was 15 days ago.
https://www.npmjs.com/package/onnxruntime-web?activeTab=versions

I am not running into this issue specifically, but I am running into the same issue as: https://github.com/microsoft/onnxruntime/issues/15388. If you can hook me up with a new release, I'm happy to help test this.

Thank you!

**Comment by shalvamist** [comment]
Hi All,

We had an update to the npm package yesterday. I think that update should help fix the issues discussed in this thread. 
Please try it out and update the thread with the results. 

BTW, We are also looking into possible paths to enable more frequent updates to the npm onnxruntime-web package.

Thanks
