### ISSUE TITLE
[Build] Problems with FP16 Layernorm

### ISSUE THREAD

**Issue by nzmora-nvidia** [microsoft/onnxruntime#15021]
### Describe the issue

When performing inference on an ONNX layer-norm graph which has FP16 inputs and outputs ORT throws an error: " NOT_IMPLEMENTED : Failed to find kernel for LayerNormalization(1)".

Details:
The actual graph is LN with FP16 input which is cast to FP32 and the output is cast back to FP16.
From the error messaged I figured that ORT was doing some pattern-matching to find optimized kernels, so I added to the end of the LN an addition operator with 0.00000001. With this, ORT doesn't detect the LN pattern and builds a correct inference session.

ORT should be able to build correctly without my hack.

### Urgency

I have a workaround but it is ugly.
This fix is required for one of Nvidia's projects but I cannot provide more info.

### Target platform

X86 Ubuntu 20.04

### Build script

All code and example ONNX files can be found in https://drive.google.com/drive/folders/17NtkQU8-5w9wuLN_HoR852Tae6bWjMWu?usp=sharing.

There are three files:
* fp16_layernorm_fail.py
* layernorm_fp16.onnx
* almost.layernorm_fp16.onnx

The script builds both ONNX files.

### Error / output

```
$ python3 fp16_layernorm_fail.py
----------------------------------------------------------------------
Testing almost.layernorm_fp16.onnx
----------------------------------------------------------------------
Testing layernorm_fp16.onnx
Traceback (most recent call last):
  File "fp16_layernorm_fail.py", line 38, in <module>
    infer(fname)
  File "fp16_layernorm_fail.py", line 28, in infer
    ort_s = s = ort.InferenceSession(fname)
  File "/home/REDUCTED/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/REDUCTED/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for LayerNormalization(1) (node LayerNormalization). Op with name (LayerNormalization) and type (LayerNormalization) kernel is not supported in CPUExecutionProvider. Encountered following errors: (Op with name (LayerNormalization) and type (LayerNormalization) Version mismatch. node_version: 1 kernel start version: 17 kernel_end_version: 2147483647
Op with name (LayerNormalization) and type (LayerNormalization) Version mismatch. node_version: 1 kernel start version: 17 kernel_end_version: 2147483647
Found kernel for Op with name (LayerNormalization) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 16). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (LayerNormalization) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 16). However the types are incompatible. This op has been implemented only for the following types (tensor(double),), but the node in the model has the following type (tensor(float))
```

### Visual Studio Version

N/A

### GCC / Compiler Version

9.4.0

**Comment by skottmckay** [comment]
LayerNormalization was added to the ONNX spec in opset 17. Prior to that it was an internal ORT operator.

The opset 17 CUDA implementation of LayerNormalization supports 16-bit floats

https://github.com/microsoft/onnxruntime/blob/538d64891ac8e43c1faf7846635c3a1bf7b6b6c5/onnxruntime/core/providers/cuda/nn/layer_norm.cc#L12-L22

Assuming you want to run on GPU, can you instead update the model to opset 17 and use the official [LayerNormalization](https://github.com/onnx/onnx/blob/main/docs/Operators.md#LayerNormalization) operator? 

You can update the opset using a tool in the ORT python package. 

`python -m onnxruntime.tools.update_onnx_opset --opset 17 model.onnx model.opset17.onnx`

**Comment by nzmora-nvidia** [comment]
@skottmckay thank you. I'm familiar with LN in opset 17 but I cannot use it because of dependencies in the SW stack I'm using.

In any case the problem occurs also when I use opset 17 - ORT seems to be trying to do pattern matching with an LN kernel and something is not to its liking so it aborts the build. 
But there is nothing wrong with the subgraph I provided to it, as can be seen when you look at the second ONNX file  (`almost.layernorm_fp16.onnx`) which makes a tiny change in the graph, thus breaking the template matching (I'm guessing here), and therefore ORT manages the subgraph.

**ORT should be able to build the subgraph `layernorm_fp16.onnx`. If he subgraph is illegal, please let me know what is wrong with it. If it is correct, please look into this issue.**

**Comment by skottmckay** [comment]
It has converted the nodes to a LayerNormalization node as per the error message so the pattern matching appears to be working:

> Op with name (LayerNormalization) and type (LayerNormalization) Version mismatch. node_version: 1 kernel start version: 17 
kernel_end_version: 2147483647

I believe the general expectation is that a GPU based EP (e.g. CUDA EP) is enabled if you're using fp16 data. The problem is the optimizer isn't skipping the insertion of the internal LayerNormalization operator that uses fp16 data when only the CPU EP is enabled, which results in a node that we have no kernel that can execute it.

If the CUDA or ROCm EP was enabled there is an fp16 kernel for the internal LayerNormalization operator

https://github.com/microsoft/onnxruntime/blob/538d64891ac8e43c1faf7846635c3a1bf7b6b6c5/onnxruntime/core/providers/cuda/nn/layer_norm.cc#L105-L118

Is there a reason for trying to run an fp16 model on CPU?

**Comment by nzmora-nvidia** [comment]
Thanks @skottmckay for the quick fix!

For anyone interested, Scott gave me this tip to work-around the issue I describe above: 
>  You can disable an optimizer if running from python. Add this to the InferenceSession constructor arguments:
       `, disabled_optimizers=["LayerNormFusion"]`
