### ISSUE TITLE
onnxruntime crashes on importing torch

### ISSUE THREAD

**Issue by tengerye** [microsoft/onnxruntime#15058]
### Describe the issue

I have an ONNX file which is exported from CLIP image encoder. I am surprised to find the order of import causes the errors of onnxruntime. Specifically, if I import `import onnxruntime as ort` before `import torch`, everything runs well. However, it raises error if the order is inverse. The error is like follows:
```
2023-03-15 17:41:36.365414715 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUBLAS failure 7: CUBLAS_STATUS_INVALID_VALUE ; GPU=0 ; hostname=cnsh1ml01 ; expr=cublasGemmHelper( Base::CublasHandle(), transB, transA, static_cast<int>(helper.N()), static_cast<int>(helper.M()), static_cast<int>(helper.K()), &alpha, reinterpret_cast<const CudaT*>(right_X->template Data<T>()), ldb, reinterpret_cast<const CudaT*>(left_X->template Data<T>()), lda, &zero, reinterpret_cast<CudaT*>(Y->template MutableData<T>()), ldc, device_prop); 
2023-03-15 17:41:36.365472999 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running MatMul node. Name:'/transformer/resblocks/resblocks.0/attn/MatMul' Status Message: CUBLAS error executing cublasGemmHelper( Base::CublasHandle(), transB, transA, static_cast<int>(helper.N()), static_cast<int>(helper.M()), static_cast<int>(helper.K()), &alpha, reinterpret_cast<const CudaT*>(right_X->template Data<T>()), ldb, reinterpret_cast<const CudaT*>(left_X->template Data<T>()), lda, &zero, reinterpret_cast<CudaT*>(Y->template MutableData<T>()), ldc, device_prop)
Traceback (most recent call last):
  File "/home/tye/projects/clip_deploy/onnx_debug.py", line 11, in <module>
    result=ort_sess.run(["IMAGE_EMBEDDING"], {"IMAGE": images})
  File "/home/tye/anaconda3/envs/deploy/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'/transformer/resblocks/resblocks.0/attn/MatMul' Status Message: CUBLAS error executing cublasGemmHelper( Base::CublasHandle(), transB, transA, static_cast<int>(helper.N()), static_cast<int>(helper.M()), static_cast<int>(helper.K()), &alpha, reinterpret_cast<const CudaT*>(right_X->template Data<T>()), ldb, reinterpret_cast<const CudaT*>(left_X->template Data<T>()), lda, &zero, reinterpret_cast<CudaT*>(Y->template MutableData<T>()), ldc, device_prop)
```

### To reproduce

```
import torch
import onnxruntime as ort
import numpy as np


if __name__ == "__main__":
    with open('test.npy', 'rb') as f:
        images = np.load(f)
    ort_sess = ort.InferenceSession("clip_vitl14.onnx", providers=['CUDAExecutionProvider'])
    result=ort_sess.run(["IMAGE_EMBEDDING"], {"IMAGE": images})
    print(f"result = {result}")
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.04

**Comment by skottmckay** [comment]
Are you able to share the model?

Have you tested with the latest ORT which is v1.14.1 to see if the issue still occurs?

**Comment by tengerye** [comment]
Hi @skottmckay thank you so much for your kind reply. Could you give me an email address so I can share the model with you? It model is too big.

**Comment by tengerye** [comment]
I haven't tried the latest ORT yet. But if you think it is necessary, I will try. @skottmckay

**Comment by tengerye** [comment]
Everything runs well with v1.14.1.

**Comment by Chaoran-F** [comment]
Hello, is this problem caused by the matching of cuda and other environment versions? I also encountered this problem. At present, I am not sure if there is a problem with my environment configuration, because I will not encounter this problem under CPUExecutionProvider. up

**Comment by Chaoran-F** [comment]
Hello, is this problem caused by the matching of cuda and other environment versions? I also encountered this problem. At present, I am not sure if there is a problem with my environment configuration, because I will not encounter this problem under CPUExecutionProvider.
