### ISSUE TITLE
NOT_IMPLEMENTED GridSample(16) on onnxruntime 1.14.1

### ISSUE THREAD

**Issue by fengzi0** [microsoft/onnxruntime#15137]
I'm trying to convert bevformer model from pytorch to onnx. After export onnx model, i can load the model by onnx but fail by onnxruntime. Is GridSample supported by onnxruntime 1.14.1 now?

Below is the log

```
>>> import onnxruntime
>>> import onnx
>>> onnxruntime.__version__
'1.14.1'
>>> onnx.__version__
'1.13.1'
>>> mm = onnx.load("checkpoints/onnx/bevformer_tiny_epoch_24.onnx")
>>> session = onnxruntime.InferenceSession("checkpoints/onnx/bevformer_tiny_epoch_24.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for GridSample(16) node with name 'GridSample_1736'
>>> 
```

**Comment by wangyems** [comment]
![image](https://user-images.githubusercontent.com/52801275/226689982-25a43cc3-a270-4546-afb6-96b85c99aa9c.png)
Currently ORT only supports float (https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md). It could be that in your model the input/output of this node is not float.

**Comment by najwabelarbi2** [comment]
hey fengzi0
did you manage to solve the issue please?
