### ISSUE TITLE
 RUNTIME_EXCEPTION : Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_t5' Status Message: bad_function_call

### ISSUE THREAD

**Issue by trajepl** [microsoft/onnxruntime#15603]
### Describe the issue

```
Testing beam search with onnxruntime...
use CUDAExecutionProvider
2023-04-20 12:29:27.335535695 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_t5' Status Message: bad_function_call
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/ptca/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/transformers/convert_generation.py", line 2329, in <module>
    main()
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/transformers/convert_generation.py", line 2315, in main
    result = test_t5_model(args, sentences=sentences)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/transformers/convert_generation.py", line 2213, in test_t5_model
    result = ort_session.run(None, inputs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_t5' Status Message: bad_function_call
```

### To reproduce

```
pip install onnxruntime-gpu==1.14.1

python -m onnxruntime.transformers.convert_generation -m t5-small --model_type t5 --output ./models/t5/onnx_models/t5_small_beam_search.onnx -p fp16 --use_gpu
```

### Platform

Linux

### OS Version

Ubuntu 20.04.5 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
I could reproduce the issue. The issue shall be resolved in main branch. You can try out our nightly package like the following:
```
pip uninstall onnxruntime-gpu
pip install ort-nightly-gpu -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
python -m onnxruntime.transformers.convert_generation -m t5-small --model_type t5 --output ./models/t5/onnx_models/t5_small_beam_search.onnx -p fp16 --use_gpu
```

In my machine, the output is like the following:
```
--------------------------------------------------
Testing beam search with onnxruntime...
use CUDAExecutionProvider
ORT outputs:
sequences [[[    0   312  5789   259 20624   302   154     0     0     0     0
       0     0     0     0     0     0     0     0     0     0     0
       0     0     0     0     0     0     0     0     0     0     0
       0     0     0     0     0     0     0     0     0     0     0
       0     0     0     0     0     0]]

 [[    0   585  3256    12   504    24  8636   830   490   533  1393
      12    70  2713     3     5   578     3     9  1782   300    54
     991    12  1364  1425    13  2189    21   321  3513    11  1082
       3     5     0     0     0     0     0     0     0     0     0
       0     0     0     0     0     0]]]
batch 0 sequence 0: Le produit est diffusé
batch 1 sequence 0: research continues to show that pets bring real health benefits to their owners. having a dog around can lead to lower levels of stress for both adults and kids.
--------------------------------------------------
Torch Sequences:
tensor([[[    0,   312,  5789,   259, 20624,   302,   154,     1,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0]],

        [[    0,   585,  3256,    12,   504,    24,  8636,   830,   490,   533,
           1393,    12,    70,  2713,     3,     5,   578,     3,     9,  1782,
            300,    54,   991,    12,  1364,  1425,    13,  2189,    21,   321,
           3513,    11,  1082,     3,     5,     1]]])
['Le produit est diffusé', 'research continues to show that pets bring real health benefits to their owners. having a dog around can lead to lower levels of stress for both adults and kids.']
--------------------------------------------------
ORT Sequences:
tensor([[[    0,   312,  5789,   259, 20624,   302,   154,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],

        [[    0,   585,  3256,    12,   504,    24,  8636,   830,   490,   533,
           1393,    12,    70,  2713,     3,     5,   578,     3,     9,  1782,
            300,    54,   991,    12,  1364,  1425,    13,  2189,    21,   321,
           3513,    11,  1082,     3,     5,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]])
['Le produit est diffusé', 'research continues to show that pets bring real health benefits to their owners. having a dog around can lead to lower levels of stress for both adults and kids.']
--------------------------------------------------
Torch and ORT result is  same
ORT {'test_times': 1, 'latency_variance': '0.00', 'latency_90_percentile': '376.61', 'latency_95_percentile': '376.61', 'latency_99_percentile': '376.61', 'average_latency_ms': '376.61', 'QPS': '5.31', 'parity': True}
```
