### ISSUE TITLE
[ONNXRuntimeError] 'Error: two nodes with same node name' with nested function

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#15849]
### Describe the issue

As title, here is one [example model](https://microsoft-my.sharepoint.com/:u:/p/bowbao/ETimfRVi9lFMopJyqUUbnM8BS26ri2ebmAjBQwd4LyEcaw?e=ExVh59).

When loading, it failed with below error:
```
Traceback (most recent call last):
  File "repro_ort_bug.py", line 41, in <module>
    onnxruntime.InferenceSession("nested_function.onnx")
  File "/home/bowbao/anaconda3/envs/torch38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/bowbao/anaconda3/envs/torch38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: two nodes with same node name (_0x56346bee65b0_n0).

```

```
<
   ir_version: 8,
   opset_import: ["" : 18, "pkg.onnxscript.torch_lib" : 1, "torch_export" : 1, "pkg.onnxscript.torch_lib" : 1, "torch_export" : 1],
   producer_name: "pytorch",
   producer_version: "2.0.0"
>
torch_jit (float[64,1,28,28] arg0) => (float[64,64,12,12] sigmoid_1) {
   l__self___conv1 = torch_export.torch.nn.modules.conv.Conv2d(L__self___conv1) (arg0, _param_constant0, _param_constant1)
   sigmoid = pkg.onnxscript.torch_lib.aten_sigmoid (l__self___conv1)
   detach = pkg.onnxscript.torch_lib.aten_detach (sigmoid)
   l__self___conv2 = torch_export.torch.nn.modules.conv.Conv2d(L__self___conv2) (sigmoid, _param_constant2, _param_constant3)
   sigmoid_1 = pkg.onnxscript.torch_lib.aten_sigmoid (l__self___conv2)
   detach_1 = pkg.onnxscript.torch_lib.aten_detach (sigmoid_1)
}
<
  domain: "pkg.onnxscript.torch_lib",
  opset_import: ["" : 18]
>
aten_sigmoid (self) => (return_val)
{
   return_val = Sigmoid (self)
}
<
  domain: "pkg.onnxscript.torch_lib",
  opset_import: ["" : 18]
>
aten_detach (self) => (return_val)
{
   return_val = Identity (self)
}
<
  domain: "pkg.onnxscript.torch_lib",
  opset_import: ["" : 18]
>
_aten_convolution_onnx <strides,pads,dilations,output_padding,groups>(input, weight, bias, transposed) => (result_12)
{
   tmp = Shape (weight)
   weight_size = Size (tmp)
   tmp_0 = Shape (input)
   tmp_1 = Size (tmp_0)
   tmp_2 = Equal (tmp_1, weight_size)
   no_batch = Not (tmp_2)
   input_6 = If (no_batch) <then_branch = thenGraph_23 () => ( input_4) {
      tmp_3 = Constant <value_ints = [0]> ()
      input_4 = Unsqueeze (input, tmp_3)
   }, else_branch = elseGraph_23 () => ( input_5) {
      input_5 = Identity (input)
   }>
   result_8 = If (transposed) <then_branch = thenGraph_26 () => ( result) {
      result = ConvTranspose <dilations: ints = @dilations, group: int = @groups, output_padding: ints = @output_padding, pads: ints = @pads, strides: ints = @strides> (input_6, weight, bias)
   }, else_branch = elseGraph_26 () => ( result_7) {
      result_7 = Conv <dilations: ints = @dilations, group: int = @groups, pads: ints = @pads, strides: ints = @strides> (input_6, weight, bias)
   }>
   result_12 = If (no_batch) <then_branch = thenGraph_48 () => ( result_10) {
      tmp_9 = Constant <value_ints = [0]> ()
      result_10 = Squeeze (result_8, tmp_9)
   }, else_branch = elseGraph_48 () => ( result_11) {
      result_11 = Identity (result_8)
   }>
}
<
  domain: "torch_export",
  opset_import: ["" : 18,"pkg.onnxscript.torch_lib" : 1]
>
torch.nn.modules.conv.Conv2d(L__self___conv1) (arg0, _param_constant0, _param_constant1) => (convolution)
{
   3 = Constant <value = bool...> ()
   convolution = pkg.onnxscript.torch_lib._aten_convolution_onnx <dilations = [1, 1], groups = 1, output_padding = [0, 0], pads = [0, 0, 0, 0], strides = [1, 1]> (arg0, _param_constant0, _param_constant1, 3)
}
<
  domain: "torch_export",
  opset_import: ["" : 18,"pkg.onnxscript.torch_lib" : 1]
>
torch.nn.modules.conv.Conv2d(L__self___conv2) (sigmoid, _param_constant2, _param_constant3) => (convolution_1)
{
   3 = Constant <value = bool...> ()
   convolution_1 = pkg.onnxscript.torch_lib._aten_convolution_onnx <dilations = [1, 1], groups = 1, output_padding = [0, 0], pads = [0, 0, 0, 0], strides = [2, 2]> (sigmoid, _param_constant2, _param_constant3, 3)
}
```

### To reproduce

Download model from link above. Run

```python
import onnxruntime
onnxruntime.InferenceSession("nested_function.onnx")
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.16.0.dev20230505007

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by satyajandhyala** [comment]
@BowenBao Can you help me fix this issue by reviewing the PR?
