### ISSUE TITLE
NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_0_quant'

### ISSUE THREAD

**Issue by chinmayjog13** [microsoft/onnxruntime#15888]
### Describe the issue

Following the documentation, I dynamically quantiized a resnet based model. The model is quantized and saved without error. However, when I try to create an inference session using the quantized model, the code crashes with the following error.

```
>>> ort_session = ort.InferenceSession(int8_path, providers=['CPUExecutionProvider'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chinmay/anaconda3/envs/v_pytorch2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/chinmay/anaconda3/envs/v_pytorch2/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name 'Conv_0_quant'
```

This is a duplicate of #12558 , which was closed a few months ago so I guess the support should have been added in onnxruntime, but I am still getting the same error.

### To reproduce

```
import onnx
from onnxruntime.quantization import quantize_dynamic, QuantType

model_fp32 = 'path/to/the/model.onnx'
model_quant = 'path/to/the/model.quant.onnx'
quantized_model = quantize_dynamic(model_fp32, model_quant)

import onnxruntime as ort
ort_session = ort.InferenceSession(model_quant, providers=['CPUExecutionProvider'])
```

[fp32_model](https://drive.google.com/file/d/1AfrxsOZ_zaslAFnkjuvl_gYAxb-WtSRr/view?usp=share_link)
[quantized_model](https://drive.google.com/file/d/1tb4xt93I-kjdYmHYJ50BbDV2hRFrg57l/view?usp=share_link)

### Urgency

Not very urgent, but not too low priority also.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by jpg-gamepad** [comment]
I am getting the same issue. I might try reverting to a previous build just to see if it was working before.

**Comment by jpg-gamepad** [comment]
I just tried the previous releases, they didn't work. Upon inspecting the code, it looks as if the patch may have never gotten deployed to release.
[Here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/cpu/quantization/conv_integer.cc#LL25C14-L25C14) and [here](https://github.com/microsoft/onnxruntime/blob/4dc4470cc7e178d9a8a134e6617e09394ce41d5a/onnxruntime/core/providers/cpu/cpu_execution_provider.cc#L375)

There should be a line that say `class ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME(kCpuExecutionProvider, kOnnxDomain, 10, uint8_t_int8_t, ConvInteger);`

Maybe @jchen351 knows what happened.

**Comment by CrisLS** [comment]
I'm having the same issue. Can I help get the patch applied?

**Comment by johnyquest7** [comment]
Same issue here. Do we have a timeline for the patch?

**Comment by trnhattan** [comment]
On the similar issue #3130, there is [comment](https://github.com/microsoft/onnxruntime/issues/3130#issuecomment-1105200621) that may temporarily solve the issue. But when we change `weight_type=QuantType.QInt8` to `QuantType.QUInt8`, the onnx quantized model seems to perform slower, as also [mentioned](https://github.com/microsoft/onnxruntime/issues/3130#issuecomment-1116900781) in that issue. And that also happened to me.

Beside, I think these issues happen due to onnx does not support `ConvInteger` for signed `Int8` datatype, [here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/cpu/quantization/conv_integer.cc#L31-L33).

**Comment by trnhattan** [comment]
In ONNX Runtime docs, in [Method Selection](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#method-selection) subsection, they said that:

> In general, it is recommended to use dynamic quantization for RNNs and transformer-based models, and **static quantization for CNN models**.

So I tried to follow the an [end-to-end example ](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/image_classification/cpu) given in the docs, and somehow it worked, the weights are `int8`. Here are steps that I did:

1. Convert FaceNet-InceptionResNet to ONNX model.
2. Create `CalibrationDataReader` by using some facial images.
3. Execute `quantize_static()`

**Comment by Apisteftos** [comment]
I have the same problem. I am finding that onnxruntime does not support the ConvInteger layer unfortunately, that means dynamic quantization is not working in onnxruntime if initial model has CNNs inside. Very sad!

**Comment by greyovo** [comment]
I found a workround to solve this, by setting:
```python
quantize_dynamic(input_model, output_model, weight_type=QuantType.QInt8, nodes_to_exclude=['/conv1/Conv'])
```
Here, `nodes_to_exclude` should be the conv layer name in your model. You may find it in the error message when loading the model using `InferenceSession`.
For example, for the error message mentioned in the title, it would be: 'Conv_0_quant'.

**Comment by Ibrah-N** [comment]
I'm also facing the same error tired solving this problem.

**Comment by ogencoglu** [comment]
Same issue for segformer model 
`NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name '/segformer/encoder/patch_embeddings.0/proj/Conv_quant'`

**Comment by theonewolf** [comment]
I just hit this issue too.  I will skip quantizing Conv layers.

**Comment by hu8813** [comment]
same error, it only works with QUint8 but not QInt8

**Comment by joelleoqiyi** [comment]
> I found a workaround to solve this, by setting:
> 
> ```python
> quantize_dynamic(input_model, output_model, weight_type=QuantType.QInt8, nodes_to_exclude=['/conv1/Conv'])
> ```
> 
> Here, `nodes_to_exclude` should be the list of conv layer name in your model. You may find it in the error message when loading the model using `InferenceSession`. For example, for the error message mentioned in the title of this issue, it would be: 'Conv_0_quant'.

Hi, I tried this while trying to quantize a whisper model (seq2seq) [see here](https://huggingface.co/docs/optimum/en/onnxruntime/usage_guides/quantization#quantize-seq2seq-models) however I am getting the following error 

```
NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name '/conv1/Conv_quant'
```

I tried to use `nodes_to_exclude` in my `AutoQuantizationConfig` to exclude the node but the error is still the same 

```
qconfig = AutoQuantizationConfig.avx512_vnni(is_static=False, per_channel=False, nodes_to_exclude=['/conv1/Conv_quant'])
```

Any help would be appreciated! 🙏

**Comment by moritzsur** [comment]
still only works with QUInt8 for me

**Comment by Fazankabir** [comment]
> , weight_type=QuantType.QInt8, operators_to_quantize=['MatMul', 'Attention', 'LSTM', 'Gather', 'Transpose', 'EmbedLayerNormalization']

were you able to solve the issue. I am facing the same with quatization and also i have more inference time with ONNX can be seen [here](https://github.com/NVlabs/SegFormer/issues/149)

**Comment by ogencoglu** [comment]
@fazankabir No solution found so far.

**Comment by Fazankabir** [comment]
I am able to do quantization with:
```
model_fp32 = 'model_Segformer.onnx'  
model_quant = "model_dynamic_quant.onnx"
quantized_model = quantize_dynamic(model_fp32, model_quant, weight_type=QuantType.QUInt8) 
```
instead of **QuantType.QInt8**

but while doing the inference it is taking even more time.
do you also have the issue with more inference time after exporting the segformer to onnx @ogencoglu ?

**Comment by ogencoglu** [comment]
I haven't tested that (onnx is a must for my case) but quantized onnx model has longer inference time than full precision one. So I ditched segformer all together. @Fazankabir

**Comment by mattam301** [comment]
> I am able to do quantization with:
> 
> ```
> model_fp32 = 'model_Segformer.onnx'  
> model_quant = "model_dynamic_quant.onnx"
> quantized_model = quantize_dynamic(model_fp32, model_quant, weight_type=QuantType.QUInt8) 
> ```
> 
> instead of **QuantType.QInt8**
> 
> but while doing the inference it is taking even more time. do you also have the issue with more inference time after exporting the segformer to onnx @ogencoglu ?

Yeh you right, a lot of operators in onnx are running in CPU instead of GPU after being quantized (maybe they haven't supported yet), so it might take more time to run some quantized model

**Comment by Johansmm** [comment]
Any news about this topic? 
I have the same issue on this code:
```python
import onnx
import onnxruntime as ort
import numpy as np

model = onnx.parser.parse_model(
    """
    <ir_version: 5, opset_import: [ "" : 18 ]>
    agraph (int8[N, 3, 32, 32] X) => (int32[N, 16, ?, ?] Y){
        Y = ConvInteger(X, W)
    }
    """
)
model.graph.initializer.extend(
    [onnx.numpy_helper.from_array(np.ones((16, 3, 3, 3), "int8"), "W")]
)

# Inference
feed = {"X": np.ones((1, 3, 32, 32), "int8")}
sess = ort.InferenceSession(model.SerializeToString(), providers=["CUDAExecutionProvider"])

# Error is raised here
y = sess.run(None, feed)[0]
```

**Comment by openmynet** [comment]
1. run
```python
quantized_model = quantize_dynamic(
    model_path,
    quantized_model_path,
    weight_type=QuantType.QInt8,
    nodes_to_exclude=[],
)
import onnxruntime as ort

ort_session = ort.InferenceSession(
    quantized_model_path, providers=["CPUExecutionProvider"]
)

```
find node
```bash
.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED :
 Could not find an implementation for ConvInteger(10) node with name '/model/patch_embed/proj/Conv_quant'
```
2.  nodes_to_exclude

delete `_quant`

**/model/patch_embed/proj/Conv_quant => /model/patch_embed/proj/Conv**

```python
quantized_model = quantize_dynamic(
    model_path,
    quantized_model_path,
    weight_type=QuantType.QInt8,
    nodes_to_exclude=[
    "/model/patch_embed/proj/Conv"  # /model/patch_embed/proj/Conv_quant => /model/patch_embed/proj/Conv
    ],
)
import onnxruntime as ort

ort_session = ort.InferenceSession(
    quantized_model_path, providers=["CPUExecutionProvider"]
)

```

**Comment by abaoxomtieu** [comment]
I fixed it by excluding the failed nodes. Most of the failures were in the IntergerConv nodes. 

```
import onnx

model_fp16_path = "./models/tusimple_18_V1_fp32.onnx"
model = onnx.load(model_fp16_path)

conv_nodes = []
for node in model.graph.node:
    if node.op_type == "Conv":
        conv_nodes.append(node.name)
conv_nodes

# ['/model/conv1/Conv',
#  '/model/layer1/layer1.0/conv1/Conv',
#  '/model/layer1/layer1.0/conv2/Conv',
#  '/model/layer1/layer1.1/conv1/Conv',
#  '/model/layer1/layer1.1/conv2/Conv',
#  '/model/layer2/layer2.0/conv1/Conv',
#  '/model/layer2/layer2.0/conv2/Conv',
#  '/model/layer2/layer2.0/downsample/downsample.0/Conv',
#  '/model/layer2/layer2.1/conv1/Conv',
#  '/model/layer2/layer2.1/conv2/Conv',
#  '/model/layer3/layer3.0/conv1/Conv',
#  '/model/layer3/layer3.0/conv2/Conv',
#  '/model/layer3/layer3.0/downsample/downsample.0/Conv',
#  '/model/layer3/layer3.1/conv1/Conv',
#  '/model/layer3/layer3.1/conv2/Conv',
#  '/model/layer4/layer4.0/conv1/Conv',
#  '/model/layer4/layer4.0/conv2/Conv',
#  '/model/layer4/layer4.0/downsample/downsample.0/Conv',
#  '/model/layer4/layer4.1/conv1/Conv',
#  '/model/layer4/layer4.1/conv2/Conv',
#  '/pool/Conv']

from onnxruntime.quantization import quantize_dynamic, QuantType

model_int8_path = "./models/model_int8_dynamic.onnx"
quantized_model = quantize_dynamic(
    model_fp16_path,  # Input model
    model_int8_path,  # Output model
    weight_type=QuantType.QInt8,
    nodes_to_exclude=conv_nodes,
)
print("Dynamic Quantization Complete!")
```

**Comment by ogencoglu** [comment]
And what is the inference speed @abaoxomtieu ? In my use case, partial quantization gets slower than non-quantized model on CPU.

**Comment by abaoxomtieu** [comment]
> And what is the inference speed [@abaoxomtieu](https://github.com/abaoxomtieu) ? In my use case, partial quantization gets slower than non-quantized model on CPU.

It's faster than float16 on my laptop

**Comment by itwastony** [comment]
> And what is the inference speed [@abaoxomtieu](https://github.com/abaoxomtieu) ? In my use case, partial quantization gets slower than non-quantized model on CPU.

the same...

**Comment by lyc8503** [comment]
Same issue, it's not stale

**Comment by rogierhofboer** [comment]
still an issue

**Comment by zhangzhao-gg** [comment]
still an issue
