### ISSUE TITLE
Importing onnxruntime_pybind11_state fails in Windows Python 3.8

### ISSUE THREAD

**Issue by take-cheeze** [microsoft/onnxruntime#16116]
### Describe the issue

Getting following errors when just importing onnxruntime
```
C:\Development\Python\Python310\lib\site-packages\onnxruntime\capi\_pybind_state.py:33: in <module>
from .onnxruntime_pybind11_state import *  # noqa
E   ImportError: DLL load failed while importing onnxruntime_pybind11_state: The specified procedure could not be found.
```

See https://ci.preferred.jp/pytorch-pfn-extras.torch200-win/131489/#L630 for detailed logs.

### To reproduce

```bash
pip install onnxruntime==1.15.0
python3 -c "import onnxruntime
```

### Platform

Windows

### OS Version

Server 2016

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Would you please use this guide: https://github.com/microsoft/onnxruntime/discussions/9630#discussioncomment-1571363 to generate a log and show it to me? Windbg might be able to give us more information.

**Comment by L-Johny** [comment]
I met the same issue on with Pyhton3.8 on Windwos 7.

**Comment by take-cheeze** [comment]
Seems this is solved by https://github.com/microsoft/onnxruntime/issues/15375
Using 1.15.1 fixed my problem. Thank you for releasing!

**Comment by guozilili** [comment]
> I met the same issue with Pyhton3.8 on Windwos 7.

I also encountered the same problem, how did I solve it in the end?

**Comment by Czytx** [comment]
> 
i also encountered the same problem, how did I solve it in the end?

**Comment by fdmadong** [comment]
pip uninstall onnxruntime
pip install onnxruntime==1.14.0
windows 7 + python 3.8.10 (64bit)
You can try it.

**Comment by ifeanyi-igweze** [comment]
> > pip uninstall onnxruntime pip install onnxruntime==1.14.0 windows 7 + python 3.8.10 (64bit) You can try it.
> 
> install least ms lib https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> it's works for me

I definitely recommend. Worked like a charm on my Win 11.

**Comment by Greg7000** [comment]
> onnxruntime==1.14.0

With 1.14.0 I could now see the GPU being used from task manager but I faced some weird runtime exceptions at some points, I then switched to 1.15.1 and everything went fine.

**Comment by huanhan** [comment]
> > pip uninstall onnxruntime pip install onnxruntime==1.14.0 windows 7 + python 3.8.10 (64bit) You can try it.
> 
> install least ms lib https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170
> 
> it's works for me

it's works for me ,windows 11,python 3.11

**Comment by catafest** [comment]
not works on Python version 3.13.5 :
```
Traceback (most recent call last):
  File "D:\_PythonProjects\PyQt6\keras_torch_rembg_001.py", line 11, in <module>
    from rembg import remove
  File "c:\Python3135\Lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "c:\Python3135\Lib\site-packages\rembg\bg.py", line 7, in <module>
    import onnxruntime as ort
  File "c:\Python3135\Lib\site-packages\onnxruntime\__init__.py", line 61, in <module>
    raise import_capi_exception
  File "c:\Python3135\Lib\site-packages\onnxruntime\__init__.py", line 24, in <module>
    from onnxruntime.capi._pybind_state import (
    ...<27 lines>...
    )
  File "c:\Python3135\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.
```

**Comment by edwiles** [comment]
@catafest for me this was fixed by repairing the installation of "Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.42.34433" in Installed Apps.

**Comment by snnn** [comment]
People who use conda please be sure to upgrade your vs2015_runtime package to the latest.
People who use other python distros please install the latest MSVC Runtime package from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 .  I assume there is no msvcp140.dll in the folder of your python.exe.

**Comment by calvinfoo** [comment]
this works for me

https://anaconda.org/anaconda/vs2015_runtime

**Comment by catafest** [comment]
fix with older version : 
```
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32 
print(onnxruntime.__version__)
1.20.0
```

**Comment by amin-nejad** [comment]
I am in an environment where I can't upgrade from python 3.10. I was getting this issue on all `onnxruntime` versions from `1.21.0` and above. Downgrading to `1.20.1` fixed the issue. Upgrading the MSVC Runtime (and rebooting) didn't seem to have any effect. Tested on Windows Server 2022.

**Comment by wiekern** [comment]
> fix with older version :
> 
> ```
> Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32 
> print(onnxruntime.__version__)
> 1.20.0
> ```

python 3.11 and onnxruntime 1.22 fixed with this method.
```txt
  File "onnxruntime\__init__.py", line 61, in <module>
  File "onnxruntime\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "onnxruntime\capi\_pybind_state.py", line 32, in <module>
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.
```

**Comment by binodil** [comment]
> I am in an environment where I can't upgrade from python 3.10. I was getting this issue on all `onnxruntime` versions from `1.21.0` and above. Downgrading to `1.20.1` fixed the issue. Upgrading the MSVC Runtime (and rebooting) didn't seem to have any effect. Tested on Windows Server 2022.

It helped me. Thanks, it saved, for sure, tons of my time)

**Comment by SebastianEngelhardt** [comment]
I think this should be reopend. Installing an older version works, but is not an satisfying solution.

**Comment by EricJeffrey** [comment]
**ENVIRONMENT**: windows 11, Python 3.12.8, PyQt5==5.15.11, PyQt5-Qt5==5.15.2, rapidocr==3.8.3, onnxruntime==1.26.0

## import order cause error
If I import PyQt before import RapidOCR (which import onnxruntime), there will be an error.
But if I import RapidOCR before PyQT, it will be just fine.

### 1.import pyqt5 before rapidocr
```py
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QApplication
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QColor, QPainter, QFont, QFontMetrics

from rapidocr import RapidOCR

print("work?")
ocr_engine = RapidOCR(params={})
print("work!")
```
```log
[INFO] 2026-06-15 12:59:39,971 [RapidOCR] base.py:22: Using engine_name: onnxruntime
Traceback (most recent call last):
  File "D:\Coding\tmp\foo.py", line 9, in <module>
    ocr_engine = RapidOCR(params={})
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\main.py", line 46, in __init__
    self._initialize(cfg)
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\main.py", line 71, in _initialize
    self.text_det = TextDetector(cfg.Det)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\ch_ppocr_det\main.py", line 47, in __init__
    self.session = get_engine(cfg.engine_type)(cfg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\inference_engine\base.py", line 25, in get_engine
    if not import_package(engine_type.value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\utils\utils.py", line 104, in import_package
    module = importlib.import_module(name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jeff\Software\Python3.12\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\onnxruntime\__init__.py", line 78, in <module>
    raise import_capi_exception
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\onnxruntime\__init__.py", line 26, in <module>
    from onnxruntime.capi._pybind_state import (
  File "C:\Users\Jeff\Software\Python3.12\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 动态链接库(DLL)初始化例程失败。

```

### 2.import rapidocr before pyqt5
```py
from rapidocr import RapidOCR
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QApplication
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QColor, QPainter, QFont, QFontMetrics

print("work?")
ocr_engine = RapidOCR(params={})
print("work!")
```
```log
work?
[INFO] 2026-06-15 13:03:47,324 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-06-15 13:03:47,662 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-06-15 13:03:47,662 [RapidOCR] main.py:65: Using C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-06-15 13:03:47,903 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-06-15 13:03:47,981 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-15 13:03:48,023 [RapidOCR] main.py:65: Using C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-06-15 13:03:48,211 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-06-15 13:03:48,262 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-06-15 13:03:48,301 [RapidOCR] main.py:65: Using C:\Users\Jeff\Software\Python3.12\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
work!
```
