### ISSUE TITLE
[Build]  line 2812, in <module>     sys.exit(main())

### ISSUE THREAD

**Issue by ishqDehlvi** [microsoft/onnxruntime#16179]
### Describe the issue

make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '--build', '/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/build/MacOS/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
cp: ./build/MacOS/Release/dist/*.whl: No such file or directory
~/Pictures/onnxruntime-silicon

### Urgency

It's urgent as I have to test the codes which are on deadline

### Target platform

MacOs

### Build script

./build-macos.sh   

### Error / output

make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 2812, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 2727, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '--build', '/Users/inzemamulhaq/Pictures/onnxruntime-silicon/onnxruntime/build/MacOS/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
cp: ./build/MacOS/Release/dist/*.whl: No such file or directory
~/Pictures/onnxruntime-silicon

**Comment by edgchen1** [comment]
What version of the code are you building? What's the full build command (i.e., what is in build-macos.sh?)? Can you provide more of the output? The first error is probably shown earlier.

**Comment by intcreator** [comment]
I tried building the latest commit from master using the following command:
```
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64
```
and I get the same error

Intel MacBook Pro Mid-2014
MacOS 10.14.4
Python 3.11.6
