### ISSUE TITLE
Load model failed - invalid model?

### ISSUE THREAD

**Issue by christian-vorhemus** [microsoft/onnxruntime#1634]
I trained the following model in Keras:

```python
model = Sequential([
    InputLayer(input_shape=[3,image_height,image_width]),
    Conv2D(filters=32, kernel_size=5, strides=1, padding='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPool2D(pool_size=8, padding='same'),
    Conv2D(filters=48, kernel_size=3, strides=1, padding='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPool2D(pool_size=5, padding='same'),
    Conv2D(filters=64, kernel_size=3, strides=1, padding='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPool2D(pool_size=3, padding='same'),
    Conv2D(filters=32, kernel_size=5, strides=1, padding='same'),
    Flatten(),
    Dense(100, activation='relu'),
    Dropout(0.1),
    Dense(12, activation='softmax')
])
```

Once training is finished, I convert it with the onnxmltools to ONNX v5 format:

`onnxmltools.utils.save_model()`

When I now try to load this model with

```python
import onnxruntime as rt
import onnx

print(onnx.__version__)
print(rt.__version__)

sess = rt.InferenceSession("./driver.onnx")
```

I get the following output:

```
1.5.0
0.5.0
Traceback (most recent call last):
  File "c:\Users\m\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\m\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 434, in main
    run()
  File "c:\Users\m\.vscode\extensions\ms-python.python-2019.6.24221\pythonFiles\lib\python\ptvsd\__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\m\Desktop\Self-driving-car\autcar\test.py", line 7, in <module>
    sess = rt.InferenceSession("./driver_keras.onnx")
  File "C:\Python36\lib\site-packages\onnxruntime\capi\session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./driver.onnx failed:This is an invalid model. Error in Node:TFNodes_flatten_1_strided_slice : Node (TFNodes_flatten_1_strided_slice) has input size 1 not in range [min=3, max=5].
```

You can download driver.onnx [here](https://1drv.ms/u/s!AlibP17lhWs9g7UVlwLhwKr6mZPAig?e=V5GHMR).

Now, when you create the model with ONNX v4 it suddenly works! Take [this model](https://1drv.ms/u/s!AlibP17lhWs9g7UWCXflk1kqldAfMA?e=q3U0j4) for example. It has the exact same model definition, the only difference is the format (ONNX v4 instead of ONNX v5)

**Comment by wenbingl** [comment]
@christian-vorhemus 
how do you save you model with ONNX v4 version? downgrade your ONNX pip package?

**Comment by snnn** [comment]
Hi,

This is a converter bug.

The problematic node is a Slice OP. Slice op get changed in opset 10. Its new version requires at least 3 inputs. While the older one(opset<=9) only has one input.  In your model, it's opset 10, but this node only has one input ,which is wrong.

Please report this bug to onnxmltools, @wenbingl will help.
