### ISSUE TITLE
[Documentation] Missing steps for setup of Xilinx KV260

### ISSUE THREAD

**Issue by ohunter** [microsoft/onnxruntime#16549]
### Describe the documentation issue

Not sure if this should be a documentation issue for the Onnx team or if Xilinx should be the one to fix this but here goes.

The paragraph on adaptable SoCs from AMD doesn't really give any instructions for how to set up a system in order to run inference on onnx models using the hardware acceleration they have. I follow the steps from AMD and perform the steps they tell me to and everything seems to be fine. The moment I start up python and run `import onnxruntime` I am faced with the following error which would indicate that there is some step missing.
```python
>>> import onnxruntime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/onnxruntime/__init__.py", line 55, in <module>
    raise import_capi_exception
  File "/usr/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 33, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: libonnxruntime_vitisai_ep.so: cannot open shared object file: No such file or directory
```

It seems like no one else has encountered the issue as there are no results for it online. 
Yes I have looked for `libonnxruntime_vitisai_ep.so` on the system but it does not exist.

### Page / URL

https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html#amd-adaptable-soc-installation

**Comment by xadupre** [comment]
Can you tell more about the envrionment you are using and the command line you run?

**Comment by ohunter** [comment]
Upon trying to recreate this I realized that I may have been following the wrong steps for the setup due to the way things are linked in the documentation. It seems like the target setup instructions point to Vitis AI version 3.0 which is understandable as it has the setup guide for the embedded targets. Then once the KV260 is set up correctly following the steps detailed [here](https://xilinx.github.io/Vitis-AI/3.0/html/docs/quickstart/mpsoc.html) the onnx documentation then says to follow the steps [here](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Programming-with-VOE). The issue then arises with the instructions on this page. 
![image](https://github.com/microsoft/onnxruntime/assets/2663525/d6cb6071-e322-4bc2-8a8e-7c7c3a725538)
The link takes you to the documentation for version 3.5 which then states the following:
- Supports ONNX Opset version 18, ONNX Runtime 1.16.0 and ONNX version 1.13
- C++ and Python API (supported Python version 3)
- In addition to the Vitis AI EP, you can incorporate other execution providers such as ACL EP to accelerate the inference with AMD DPU
- The ONNX Runtime supports computation on the ARM64 Cortex®-A72 cores and the supported target is VEK280 in VAI3.5

The second and last bullet points are probable the most important ones for this issue because if we switch to the 3.0 version of the document there is no such section describing the supported hardware, nor is there a section with an example written in python. Due to the installation instruction from before we know that Vitis AI 3.0 supports the Zynq based SoCs, but they are missing from the quick start guides for Vitis AI 3.5. As such it seems like the support for python with the Zynq based SoCs is missing at the moment. This should probably be mentioned somewhere I think. Especially since I was taken to the aforementioned links through this selection:
![image](https://github.com/microsoft/onnxruntime/assets/2663525/b538cdc8-234e-4cca-84df-71990a9f52d2)

**Comment by Mr-Robot-mars** [comment]
Ahh, finally found someone with same problem, did you find solution yet? :)

**Comment by ohunter** [comment]
Unfortunately I have not been able to follow this up so no.
