### ISSUE TITLE
onnxruntime test fail after successful model conversion

### ISSUE THREAD

**Issue by KNaudin** [microsoft/onnxruntime#1658]
**Describe the bug**
I am unable to infer on an image using an ONNX model I created using tf2onnx. Trying onnxruntime_test on my model gives the exact same error:
```
2019-08-20 16:09:58.4070009 [W:onnxruntime:Default, cuda_execution_provider.cc:1041 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise 
2019-08-20 16:09:58.4075049 [W:onnxruntime:Default, cuda_execution_provider.cc:1041 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: Conv__7405
2019-08-20 16:09:58.4083969 [W:onnxruntime:Default, cuda_execution_provider.cc:1041 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: Conv__7595
2019-08-20 16:09:58.4089498 [W:onnxruntime:Default, cuda_execution_provider.cc:1041 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: Conv__7631
input = image_tensor:0, shape = [1, 512, 512, 3]
Image shape = (1, 512, 512, 3)
outputs = ['detection_boxes:0', 'detection_classes:0', 'detection_scores:0', 'num_detections:0']
2019-08-20 16:10:03.2719586 [E:onnxruntime:, sequential_executor.cc:127 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise Status Message: Input channels C is not equal to kernel channels * group. C: 3 kernel channels: 1 group: -1
Traceback (most recent call last):
  File ".\inference.py", line 30, in <module>
    pred_onx = sess.run(outputs, {inputs.name: np.expand_dims(image, 0)})
  File "C:\Users\naudi\AppData\Local\Programs\Python\Python36\lib\site-packages\onnxruntime\capi\session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : Non-zero status code returned while running Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise Status Message: Input channels C is not equal to kernel channels * group. C: 3 kernel channels: 1 group: -1
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5.0
- Python version: 3.6.7
- Visual Studio version (if applicable): 2019 community
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7.6.1
- GPU model and memory: Nvidia GeForce GTX 1050 4Go

**To Reproduce**
Download the Tensorflow model from the Tensorflow Object Detection model zoo [here](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz) and convert it using 
` python -m tf2onnx.convert --opset 10 --fold_const --saved-model .\ssd_inception_v2_coco_2018_01_28\saved_model --output .\onnx\ssd_inceptionv2_2018.onnx`
When the model is done converting, try testing it with
`onnxruntime_test ssd_inceptionv2_2018.onnx`

I also tried with some code:
```
import cv2
import onnxruntime as rt
import numpy as np

image_name = 'car.jpg'
image = cv2.imread(image_name, cv2.IMREAD_UNCHANGED)
image = cv2.resize(image, (512,512))

sess = rt.InferenceSession('../onnx/ssd_inceptionv2_2018.onnx')

inputs = [node for node in sess.get_inputs()][0]
outputs = [node.name for node in sess.get_outputs()]

print("input = {}, shape = {}".format(inputs.name, inputs.shape))
print('Image shape = {}'.format(np.expand_dims(image, 0).shape))
print("outputs = {}".format(outputs))

pred_onx = sess.run(outputs, {inputs.name: np.expand_dims(image, 0)})
```
**Expected behavior**
The model inference using Tensorflow gives an output of boxes, scores, labels and number of detections.

**Additional context**
Models from the ONNX model zoo work fine, but any model converted from the TF model zoo does not seem to be able to process anything.

**Comment by snnn** [comment]
Why do you set image size to 512x512?

**Comment by KNaudin** [comment]
Someone commented but apparently their comment disappeared.
The comment asked why I resized my image; it's because at first the shape of the input was (1, unk, unk, unk, 3) and it gave me the exact same error. Someone in another thread mentionned it was because of an input shape mismatch so I re-exported my model but this time I overrode the input shape with `--inputs image_tensor:0[1,512,512,3]`. It didn't solve the issue I am facing.

**Comment by snnn** [comment]
I commented then deleted it.  I'll take a look. Most likely it's because of some shape mismatch.  Maybe you shouldn't override the input shape.

**Comment by KNaudin** [comment]
I exported the model without overriding the input shape. I get the same CUDA warnings as mentionned above and then I get this:
```
Traceback (most recent call last):
  File "c:\users\naudi\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\naudi\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\naudi\AppData\Local\Programs\Python\Python36\Scripts\onnxruntime_test.exe\__main__.py", line 9, in <module>
  File "c:\users\naudi\appdata\local\programs\python\python36\lib\site-packages\onnxruntime\tools\onnxruntime_test.py", line 68, in main
    high=1000, size=tuple(shape)).astype(integer_dict[input_meta.type])
  File "mtrand.pyx", line 1309, in mtrand.RandomState.uniform
  File "mtrand.pyx", line 242, in mtrand.cont2_array_sc
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by hariharans29** [comment]
There error message seems to indicate that this is not a valid onnx model. Group = -1 is not valid according to the onnx spec. 

Please try converting with latest fixes in tf2onnx or try converting to opset-11 if the converter supports it and if group = -1 still persists, please open an issue in the tf2onnx repo.

**Comment by KNaudin** [comment]
Weird that this would be a non-valid ONNX model since I converted it using the tf2onnx converter on an official, unmodified Tensorflow Model Zoo pb file. I will try your solution and come back to you.

**Comment by hariharans29** [comment]
Oh even if the source file was an official unmodified Tf pb file, the resultant onnx file is only as good as the intermediate conversion process. So, it is plausible that a conversion error resulted in an invalid final onnx file even if the source file is from a verified source.

**Comment by KNaudin** [comment]
I've done what you told me and I am getting a new error.
`RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from ./ssd_resnet_fpn_coco.onnx failed:[TypeInferenceError] Graph attribute inferencing failed: Node:Preprocessor/map/while/ResizeImage/resize_images/Squeeze Output:Preprocessor/map/while/ResizeImage/resize_images/Squeeze:0 [ShapeInferenceError] Mismatch between number of source and target dimensions. Source=3 Target=4`

Again it happens whether I am using an official unmodified TF PB or not. I am closing this since it looks like it's a converter issue, where it's not able to work with some layers.
