### ISSUE TITLE
TensorRT EP profile error w/ optional dynamic input shape specifiers

### ISSUE THREAD

**Issue by laggui** [microsoft/onnxruntime#16600]
### Describe the issue

For a model with a dynamic shape input that is optional, providing the TensorRT EP profile returns an error.

The provided MWE uses the python API but it also happens with the C++ package.

```
[ONNXRuntimeError] : 11 : EP_FAIL : Users need to specify all the dynamic shape inputs with associated profiles if they want to explicitly specify profiles through provider options.
```

### To reproduce

Self-contained MWE below.

The first test uses the same model without the profile specifying the min/max/opt input shapes. It succeeds.
The second test uses the same model but the input is not optional anymore, and specifies the shapes in the TRT profile.
The last test uses the model w/ optional input of dynamic shape and TRT profile. It crashes.

```sh
[Optional] Testing w/ trt_profile=False optional=True
Unsupported ONNX data type: <UNKNOWN> (0)
Unsupported ONNX data type: <UNKNOWN> (0)
Unsupported ONNX data type: <UNKNOWN> (0)
[Optional] Success!
[Optional] Testing w/ trt_profile=True optional=False
[Optional] Success!
[Optional] Testing w/ trt_profile=True optional=True
Unsupported ONNX data type: <UNKNOWN> (0)
Unsupported ONNX data type: <UNKNOWN> (0)
Traceback (most recent call last):
  File "/workspace/ort_inference/python/test_opt_dynamic_gh.py", line 212, in <module>
    test_optional_input_dynamic(trt_profile=True, optional=True)
  File "/workspace/ort_inference/python/test_opt_dynamic_gh.py", line 188, in test_optional_input_dynamic
    session = ort.InferenceSession(
  File "/home/prime/miniconda3/envs/ort115/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/prime/miniconda3/envs/ort115/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : Users need to specify all the dynamic shape inputs with associated profiles if they want to explicitly specify profiles through provider options.
```

```py
from copy import deepcopy
from typing import Optional, Sequence, Tuple

import numpy as np
import onnxruntime as ort
from onnx import ModelProto, NodeProto, TensorProto, ValueInfoProto, checker, helper


def make_vi_like(vi: ValueInfoProto, name: str) -> ValueInfoProto:
    """Makes a copy of `vi` with a new name."""
    new_vi = deepcopy(vi)
    new_vi.name = name
    return new_vi


def make_optional_tensor_value_info(
    name: str, elem_type: int, shape: Sequence[int]
) -> ValueInfoProto:
    """Makes a `ValueInfoProto` with optional type."""
    tensor_type_proto = helper.make_tensor_type_proto(
        elem_type=elem_type,
        shape=shape,
    )
    opt_type_proto = helper.make_optional_type_proto(tensor_type_proto)

    vi = helper.make_tensor_value_info(name, elem_type, shape)
    vi.type.CopyFrom(opt_type_proto)
    return vi


def make_optional_vi(vi: ValueInfoProto, name: Optional[str] = None) -> ValueInfoProto:
    """Makes a copy of `vi` with optional type."""
    name = name or vi.name + ".opt"
    vi_type = vi.type.tensor_type
    vi_shape = [d.dim_param if d.dim_param else d.dim_value for d in vi_type.shape.dim]
    opt_vi = make_optional_tensor_value_info(name, vi_type.elem_type, vi_shape)
    return opt_vi


def make_const(
    vi: ValueInfoProto, name: str, value: int = 0
) -> Tuple[ValueInfoProto, NodeProto, TensorProto]:
    """Creates a constant 1D tensor from `vi`."""
    const_vi = make_vi_like(vi, name)
    const_shape = [d.dim_value for d in vi.type.tensor_type.shape.dim]
    const_shape_tensor = helper.make_tensor(
        f"{name}.shape", TensorProto.INT64, [len(const_shape)], const_shape
    )
    const_fill = helper.make_tensor(
        f"{name}.const.value", const_vi.type.tensor_type.elem_type, [1], [value]
    )
    const_node = helper.make_node(
        "ConstantOfShape",
        inputs=[const_shape_tensor.name],
        outputs=[const_vi.name],
        name=f"ConstantOfShape.{name}",
        value=const_fill,
    )
    return const_vi, const_node, const_shape_tensor


def make_opt_dynamic() -> ModelProto:
    """Creates a simple graph with (`optional(x1)`, `x2`) tensor inputs."""
    x1_vi = helper.make_tensor_value_info("x1", TensorProto.FLOAT, [1, "n"])
    x2_vi = helper.make_tensor_value_info("x2", TensorProto.FLOAT, [1, 1])
    y_vi = helper.make_tensor_value_info("y", TensorProto.FLOAT, [1, "n"])
    opt_x1_vi = make_optional_vi(x1_vi, name="x1.opt")

    # Add subgraph
    y1_vi = make_vi_like(y_vi, "y.add")
    input_get_elem_node = helper.make_node(
        "OptionalGetElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_vi.name],
        name="OptionalGetElement.Input",
    )
    add_node = helper.make_node(
        "Add", inputs=[x1_vi.name, x2_vi.name], outputs=[y1_vi.name], name="Add_Op"
    )
    add_subgraph = helper.make_graph(
        [input_get_elem_node, add_node],
        name="add-x1-x2-subgraph",
        inputs=[],
        outputs=[y1_vi],
        value_info=[opt_x1_vi, x1_vi, x2_vi],
    )

    # Add const subgraph
    y2_vi = make_vi_like(x2_vi, "y.add.const")
    const_vi, const_node, const_shape_tensor = make_const(x2_vi, "x1.const", value=1)
    add_const_node = helper.make_node(
        "Add",
        inputs=[const_vi.name, x2_vi.name],
        outputs=[y2_vi.name],
        name="Add_Const",
    )
    add_const_subgraph = helper.make_graph(
        [const_node, add_const_node],
        name="add-x2-const-subgraph",
        inputs=[],
        outputs=[y2_vi],
        value_info=[const_vi, x2_vi],
        initializer=[const_shape_tensor],
    )

    # Construct main graph
    x1_has_elem_vi = helper.make_tensor_value_info(
        "x1_has_elem",
        TensorProto.BOOL,
        shape=[],  # scalar
    )
    x1_has_elem_node = helper.make_node(
        "OptionalHasElement",
        inputs=[opt_x1_vi.name],
        outputs=[x1_has_elem_vi.name],
        name="OptionalHasElement.x1",
    )
    if_input_node = helper.make_node(
        "If",
        inputs=[x1_has_elem_vi.name],  # condition
        outputs=[y_vi.name],
        name="If.OptionalHasElement.x1",
        then_branch=add_subgraph,
        else_branch=add_const_subgraph,
    )
    graph = helper.make_graph(
        [x1_has_elem_node, if_input_node],
        "opt-graph",
        [opt_x1_vi, x2_vi],
        [y_vi],
        value_info=[x1_has_elem_vi],
    )

    m = helper.make_model(
        graph,
        opset_imports=[
            helper.make_opsetid("", 15),
        ],
    )
    checker.check_model(m, full_check=True)
    return m


def make_dynamic() -> ModelProto:
    x1_vi = helper.make_tensor_value_info("x1", TensorProto.FLOAT, [1, "n"])
    x2_vi = helper.make_tensor_value_info("x2", TensorProto.FLOAT, [1, 1])
    y_vi = helper.make_tensor_value_info("y", TensorProto.FLOAT, [1, "n"])

    # Add subgraph
    add_node = helper.make_node(
        "Add", inputs=[x1_vi.name, x2_vi.name], outputs=[y_vi.name], name="Add_Op"
    )
    add_subgraph = helper.make_graph(
        [add_node],
        name="add-x1-x2-subgraph",
        inputs=[x1_vi, x2_vi],
        outputs=[y_vi],
    )
    m = helper.make_model(
        add_subgraph,
        opset_imports=[
            helper.make_opsetid("", 15),
        ],
    )
    checker.check_model(m, full_check=True)
    return m


def test_optional_input_dynamic(
    trt_profile: bool = True, optional: bool = True
) -> None:
    """Validate ONNX model w/ optional input of dynamic shape."""
    print(f"[Optional] Testing w/ trt_profile={trt_profile} optional={optional}")
    model = make_opt_dynamic() if optional else make_dynamic()
    output_name = model.graph.output[0].name
    input_name = model.graph.input[0].name
    if trt_profile:
        trt_ep = (
            "TensorrtExecutionProvider",
            {
                "trt_profile_min_shapes": f"{input_name}:1x1",
                "trt_profile_max_shapes": f"{input_name}:1x10",
                "trt_profile_opt_shapes": f"{input_name}:1x2",
            },
        )
    else:
        trt_ep = "TensorrtExecutionProvider"
    session = ort.InferenceSession(
        model.SerializeToString(),
        providers=(trt_ep,),
    )

    x1 = np.random.randn(1, 2).astype(np.float32)
    x2 = np.random.randn(1, 1).astype(np.float32)

    inputs = session.get_inputs()

    # When x1 is provided, the output should be `x1 + x2`
    ort_inputs = {inputs[0].name: x1, inputs[1].name: x2}
    ort_outs = session.run([output_name], ort_inputs)[0]
    np.testing.assert_equal(ort_outs, x1 + x2)

    print("[Optional] Success!")


if __name__ == "__main__":
    ort.set_default_logger_severity(3)

    test_optional_input_dynamic(trt_profile=False, optional=True)
    test_optional_input_dynamic(trt_profile=True, optional=False)
    test_optional_input_dynamic(trt_profile=True, optional=True)

```

### Platform

Linux

### OS Version

Ubuntu 20.04.2 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

TensorRT 8.6

**Comment by chilo-ms** [comment]
Thanks for reporting, will investigate this issue.

**Comment by chilo-ms** [comment]
@laggui
For the last test, the optional input for the main graph is `x1.opt` but the real use for this optional input is in the `add-x1-x2-subgraph` where the "add" node consumes `x1` input. The "OptionalGetElement" inside this subgraph is not supported by TRT, so the subgraph will be partitioned into TRT/CPU subgraphs, so one of the inputs of this TRT subgraph is `x1`.
Simply replace the `x1.opt` with `x1` for the provider option should work.

**Comment by laggui** [comment]
@chilo-ms just to make sure, are you suggesting that I remove the optional input for it to work? I know it works without the optional input, but in the actual model (not this MWE), the input really is optional and separate graphs are executed based on the availability of the input.

**Comment by chilo-ms** [comment]
@laggui
What I suggest for the last test is to make provider option as below:

            "TensorrtExecutionProvider",
            {
                "trt_profile_min_shapes": "x1:1x1",
                "trt_profile_max_shapes": "x1:1x10",
                "trt_profile_opt_shapes": "x1:1x2",
            },

**Comment by laggui** [comment]
@chilo-ms Ahhh yes ok that makes a lot of sense actually. Because the shapes provided in the profile are usually for the main graph input, I was confused and provided values for the optional.

But in reality it's not even executed with the TensorRT graph, and the node is dispatched to CPU. So the subgraph with the output of `OptionalGetElement` (here, `x1`) needs to know the shapes for that input.

That's an user error than, my apologies.  I also just tested with your suggestion and it works as expected.

Feel free to close!

**Comment by chilo-ms** [comment]
Yes, your understanding is right and thank for confirming.
For TRT EP, we can still think of a better way to handle the case of partitioning when providing profile shapes, that's our work!
