### ISSUE TITLE
op.SequenceEmpty(dtype=xxx) cannot be set to float16.

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/onnxruntime#16846]
### Describe the issue

op.SequenceEmpty(dtype=xxx) cannot be set to float16, it will ignore the dtype and result as float32.

### To reproduce

```python
from onnxscript import FLOAT, FLOAT16, opset18 as op

seq = op.SequenceEmpty(dtype=FLOAT16.dtype)
x = op.Cast(op.Constant(value_float=1.0), to=FLOAT16.dtype)
op.SequenceInsert(seq, x)  # This will failed
```

Error

```
Traceback (most recent call last):
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.10/site-packages/onnxscript/evaluator.py", line 446, in _call_ort
    session = ort.InferenceSession(
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/justinchu/anaconda3/envs/pytorch/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 399, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node () Op (SequenceInsert) [TypeInferenceError] Input Sequence and Tensor are expected to have the same elem type. Sequence=1 Tensor=10
```

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by xadupre** [comment]
What is the error message? Does it work with `x = op.Cast(op.Constant(value_floats=[1.0]), to=FLOAT16.dtype)`?

**Comment by pranavsharma** [comment]
Is this an issue with onnxruntime or onnx script? Please file the issue in an appropriate place.

**Comment by justinchuby** [comment]
I think this is an issue with onnx shape inferencing. @gramalingam I wonder if this is part of the fix we have since 1.14?
