### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by telestia** [microsoft/onnxruntime#16955]
### Describe the issue

I am renting GPU's online for run  s0md3v/roop on  docker container  and its working good but  sometimes I get this error

GPU: 4090
CPU: AMD Ryzen 9 5900x 12-core

### Target platform

linux/amd64

### Build script

python3 run.py -s source.png -t target.mp4 -o output.mp4 --execution-provider cuda --similar-face-distance 1.5 --execution-threads 16 --reference-face-position 0

### Error / output

EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] CUDA failure 804: forward compatibility was attempted on non supported HW ; GPU=-1684613632 ; hostname=bbf87817667f ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=238 ; expr=cudaSetDevice(info_.device_id); 

 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] CUDA failure 804: forward compatibility was attempted on non supported HW ; GPU=-1684613632 ; hostname=bbf87817667f ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=238 ; expr=cudaSetDevice(info_.device_id); 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/roop/run.py", line 6, in 
    core.run()
  File "/roop/roop/core.py", line 219, in run
    start()
  File "/roop/roop/core.py", line 137, in start
    if not frame_processor.pre_start():
  File "/roop/roop/processors/frame/face_swapper.py", line 45, in pre_start
    elif not get_one_face(cv2.imread(roop.globals.source_path)):
  File "/roop/roop/face_analyser.py", line 30, in get_one_face
    many_faces = get_many_faces(frame)
  File "/roop/roop/face_analyser.py", line 41, in get_many_faces
    return get_face_analyser().get(frame)
  File "/roop/roop/face_analyser.py", line 18, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name='buffalo_l', providers=roop.globals.execution_providers)
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t = void] CUDA failure 804: forward compatibility was attempted on non supported HW ; GPU=-1787346965 ; hostname=bbf87817667f ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=238 ; expr=cudaSetDevice(info_.device_id);

**Comment by yf711** [comment]
From your log it showed `CUDA failure 804: forward compatibility was attempted on non supported HW ; GPU=-1684613632`, which might be a sign that in your cloud vm instance, your code can't find the right GPU device or there is no nv/cuda driver.

Could you verify if your GPU is usable in your env and your code is calling the right device id? 
Feel free to share a minimal reproducible example to us if issue still exists.

**Comment by snnn** [comment]
Please try to upgrade your driver.
