### ISSUE TITLE
[Build] Failed to build with --build_wheel

### ISSUE THREAD

**Issue by dlorenz70** [microsoft/onnxruntime#16956]
### Describe the issue

I try to build ORT to work on a feature for on-device training and I follow that instruction:
https://onnxruntime.ai/docs/build/training.html

I see the error below when I run the build script, but I don't get the error when I build onnxruntime_pybind11_state.vcxproj in Visual Studio.

### Target platform

Windows 10

### Build script

.\build.bat --config RelWithDebInfo --cmake_generator "Visual Studio 17 2022" --build_shared_lib --parallel --enable_training_apis --build_wheel

### Error / output

`D:\onnxruntime\onnxruntime\python\onnxruntime_pybind_schema.cc(15,76): error C2039: 'OpSchema': is not a member of 'onn
x' [D:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
D:\onnxruntime\onnxruntime\core/session/inference_session.h(36,11): message : see declaration of 'onnx' [D:\onnxruntime
\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
D:\onnxruntime\onnxruntime\python\onnxruntime_pybind_schema.cc(15,84): error C2065: 'OpSchema': undeclared identifier [
D:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
D:\onnxruntime\onnxruntime\python\onnxruntime_pybind_schema.cc(15,53): error C2923: 'std::vector': 'OpSchema' is not a
valid template type argument for parameter '_Ty' [D:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_stat
e.vcxproj]
`
...
`2023-08-01 11:26:02,006 util.run [INFO] - Running subprocess in 'D:\onnxruntime\\build\Windows\RelWithDebInfo\RelWithDebInfo'
  'D:\Python\Python311\python.exe' 'D:\onnxruntime\setup.py' bdist_wheel --enable_training_apis
error: package directory 'onnxruntime\training' does not exist
Traceback (most recent call last):
  File "D:\onnxruntime\\tools\ci_build\build.py", line 2626, in <module>
    sys.exit(main())
             ^^^^^^
  File "D:\onnxruntime\\tools\ci_build\build.py", line 2547, in main
    build_python_wheel(
  File "D:\onnxruntime\\tools\ci_build\build.py", line 1964, in build_python_wheel
    run_subprocess(args, cwd=cwd)
  File "D:\onnxruntime\\tools\ci_build\build.py", line 787, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Python\\Python311\\python.exe', 'D:\\onnxruntime\\setup.py', 'bdist_wheel', '--enable_training_apis']' returned non-zero exit status 1.
`

### Visual Studio Version

2022

**Comment by dlorenz70** [comment]
Was fixed by installing additional python libs.
