### ISSUE TITLE
[Build] Trying to build onnxruntime from source with CUDA 12.2 ...

### ISSUE THREAD

**Issue by jiapei100** [microsoft/onnxruntime#16985]
### Describe the issue

By using the command, `./build.sh --use_cuda --cudnn_home /usr/local/cuda --cuda_home /usr/local/cuda --build_wheel`
I obtained the following [message in pastebin](https://pastebin.com/EHvsq7sP).

However, I would like **onnxruntime** uses my installed packages, rather than its own packages, such as 
- protobuf
- abseil-cpp
- pybind11
- etc.

Is there a way for me to build **onnxruntime** with my own **cmake configuration**?

### Urgency

Urgent to me 

### Target platform

Ubuntu 22.04

### Build script

`./build.sh --use_cuda --cudnn_home /usr/local/cuda --cuda_home /usr/local/cuda --build_wheel`

### Error / output

Refer to [pastebin](https://pastebin.com/EHvsq7sP) .

```console
......
-- pybind11 v2.10.1 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "....../onnxruntime/tools/ci_build/build.py", line 2626, in <module>
    sys.exit(main())
  File "....../onnxruntime/tools/ci_build/build.py", line 2484, in main
    generate_build_tree(
  File "....../onnxruntime/tools/ci_build/build.py", line 1373, in generate_build_tree
    run_subprocess(
  File "....../onnxruntime/tools/ci_build/build.py", line 787, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "....../onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['~/.local/bin/cmake', '....../onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/usr/bin/python3', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-
......
```

### Visual Studio Version

VSCode 1.80.2

### GCC / Compiler Version

11.4.0

**Comment by snnn** [comment]
```
CMake Error: File ....../onnxruntime/requirements.txt.in does not exist.
```

So, where it is missing? Is the path right?

**Comment by jiapei100** [comment]
@snnn
Thank you for your reply.... I have the [pastebin](https://pastebin.com/EHvsq7sP)  updated.

**Comment by jiapei100** [comment]
If I build from within **cmake**, I got the following [ERROR messages](https://pastebin.com/wm3XW1jc) .

**Comment by snnn** [comment]
The problem you reported should have been fixed. However, to make the build pass we still need another fix from: #16980

**Comment by snnn** [comment]
Dup with #16942
