### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by Apisteftos** [microsoft/onnxruntime#17131]
### Describe the issue

I am trying to build onnxruntime-gpu from the source but an error occurs

### Target platform

CUDA

### Build script

./build.sh --use_cuda --cudnn_home <cudnn home path> --cuda_home <cuda home path>

### Error / output

[ 48%] Built target onnxruntime_providers_shared
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/activation/activations.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/controlflow/if.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/controlflow/loop.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/controlflow/scan.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_allocator.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_check_memory.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_graph.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_profiler.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_provider_factory.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/cupti_manager.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/generator/constant_of_shape.cc.o
[ 48%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/generator/random.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/generator/range.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/gpu_data_transfer.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/integer_gemm.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/binary_elementwise_ops.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/clip.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/cumsum.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/einsum.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/einsum_utils/einsum_auxiliary_ops.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/gemm.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/matmul.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/matmul_integer.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/softmax.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/softmax_common.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/topk.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/unary_elementwise_ops.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/math/variadic_elementwise_ops.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/batch_norm.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/conv.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/conv_transpose.cc.o
[ 50%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/dropout.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/instance_norm.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/layer_norm.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/lrn.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/pool.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nn/shrink.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/nvtx_profile.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/object_detection/non_max_suppression.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/object_detection/roialign.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/reduction/reduction_functions.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/rnn/gru.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/rnn/lstm.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/rnn/rnn.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/cast_op.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/compress.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/concat.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/expand.cc.o
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/eye_like.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/flatten.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/gather.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/gather_elements.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/gather_nd.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/identity_op.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/nonzero_op.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/onehot.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/pad.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/quantize_linear.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/reshape.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/reverse_sequence.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/scatter_elements.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/scatter_nd.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/sequence_op.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/shape_op.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/size.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/slice.cc.o
[ 52%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/space_depth_ops.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/split.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/squeeze.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/tile.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/transpose.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/trilu.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/unsqueeze.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/upsample.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tensor/where.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tunable/cuda_tuning_context.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tunable/math/gemm.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tunable/math/matmul.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/tunable/util.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/shared_library/provider_bridge_provider.cc.o
[ 53%] Building CXX object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/shared_library/provider_ort_api_init.cc.o
[ 53%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:1337: CMakeFiles/onnxruntime_providers_cuda_obj.dir/home/kostas84/Desktop/ONNXPlatform/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1982: CMakeFiles/onnxruntime_providers_cuda_obj.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/kostas84/Desktop/ONNXPlatform/onnxruntime/tools/ci_build/build.py", line 2636, in <module>
    sys.exit(main())
  File "/home/kostas84/Desktop/ONNXPlatform/onnxruntime/tools/ci_build/build.py", line 2529, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/kostas84/Desktop/ONNXPlatform/onnxruntime/tools/ci_build/build.py", line 1440, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/kostas84/Desktop/ONNXPlatform/onnxruntime/tools/ci_build/build.py", line 789, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/kostas84/Desktop/ONNXPlatform/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/kostas84/Desktop/ONNXPlatform/venv/bin/cmake', '--build', '/home/kostas84/Desktop/ONNXPlatform/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.

### Visual Studio Version

1.81.0

### GCC / Compiler Version

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by seddonm1** [comment]
This process will create the same files as in the distributed binary (but uses a docker container to ensure all the requirements are met ) then copies the output to the current working directory. 

https://gist.github.com/seddonm1/5dc956b136a98b8d46d03ca205252b4a
