### ISSUE TITLE
[Build] Protobuf compiler not found

### ISSUE THREAD

**Issue by jsoto-gladia** [microsoft/onnxruntime#17234]
### Describe the issue

I get the following error when:
Protobuf compiler not found

when doing:
git clone https://github.com/microsoft/onnxruntime
cd onnxruntime/dockerfiles
docker build -t onnxruntime-cuda -f Dockerfile.cuda ..

### Target platform

V100s

### Build script

git clone https://github.com/microsoft/onnxruntime
cd onnxruntime/dockerfiles
docker build -t onnxruntime-cuda -f Dockerfile.cuda ..

### Error / output
```
#0 17.97   Downloading exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
#0 17.98 Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest->-r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requirements.txt (line 4)) (21.3)
#0 18.02 Building wheels for collected packages: onnx
#0 18.03   Building wheel for onnx (pyproject.toml): started
#0 18.94   Building wheel for onnx (pyproject.toml): finished with status 'error'
#0 18.96   error: subprocess-exited-with-error
#0 18.96   
#0 18.96   × Building wheel for onnx (pyproject.toml) did not run successfully.
#0 18.96   │ exit code: 1
#0 18.96   ╰─> [77 lines of output]
#0 18.96       running bdist_wheel
#0 18.96       running build
#0 18.96       running build_py
#0 18.96       running create_version
#0 18.96       running cmake_build
#0 18.96       -- The C compiler identification is GNU 11.3.0
#0 18.96       -- The CXX compiler identification is GNU 11.3.0
#0 18.96       -- Detecting C compiler ABI info
#0 18.96       -- Detecting C compiler ABI info - done
#0 18.96       -- Check for working C compiler: /usr/bin/cc - skipped
#0 18.96       -- Detecting C compile features
#0 18.96       -- Detecting C compile features - done
#0 18.96       -- Detecting CXX compiler ABI info
#0 18.96       -- Detecting CXX compiler ABI info - done
#0 18.96       -- Check for working CXX compiler: /usr/bin/c++ - skipped
#0 18.96       -- Detecting CXX compile features
#0 18.96       -- Detecting CXX compile features - done
#0 18.96       -- Found PythonInterp: /usr/bin/python3 (found version "3.10.12")
#0 18.96       -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.12")
#0 18.96       Generated: /tmp/pip-install-sdc9dvsm/onnx_63b69a58531e4081a27a64608b3e294a/.setuptools-cmake-build/onnx/onnx-ml.proto
#0 18.96       CMake Error at CMakeLists.txt:303 (message):
#0 18.96         Protobuf compiler not found
#0 18.96       Call Stack (most recent call first):
#0 18.96         CMakeLists.txt:334 (relative_protobuf_generate_cpp)
#0 18.96       
#0 18.96       
#0 18.96       -- Configuring incomplete, errors occurred!
#0 18.96       Traceback (most recent call last):
#0 18.96         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#0 18.96           main()
#0 18.96         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#0 18.96           json_out['return_val'] = hook(**hook_input['kwargs'])
#0 18.96         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
#0 18.96           return _build_backend().build_wheel(wheel_directory, config_settings,
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
#0 18.96           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
#0 18.96           self.run_setup()
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
#0 18.96           super(_BuildMetaLegacyBackend,
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
#0 18.96           exec(compile(code, __file__, 'exec'), locals())
#0 18.96         File "setup.py", line 342, in <module>
#0 18.96           setuptools.setup(
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
#0 18.96           return distutils.core.setup(**attrs)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
#0 18.96           return run_commands(dist)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
#0 18.96           dist.run_commands()
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
#0 18.96           self.run_command(cmd)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 18.96           cmd_obj.run()
#0 18.96         File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
#0 18.96           self.run_command('build')
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#0 18.96           self.distribution.run_command(command)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 18.96           cmd_obj.run()
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
#0 18.96           self.run_command(cmd_name)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#0 18.96           self.distribution.run_command(command)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 18.96           cmd_obj.run()
#0 18.96         File "setup.py", line 236, in run
#0 18.96           self.run_command("cmake_build")
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#0 18.96           self.distribution.run_command(command)
#0 18.96         File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
#0 18.96           cmd_obj.run()
#0 18.96         File "setup.py", line 222, in run
#0 18.96           subprocess.check_call(cmake_args)
#0 18.96         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
#0 18.96           raise CalledProcessError(retcode, cmd)
#0 18.96       subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-sdc9dvsm/onnx_63b69a58531e4081a27a64608b3e294a']' returned non-zero exit status 1.
#0 18.96       [end of output]
#0 18.96   
#0 18.96   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 18.96   ERROR: Failed building wheel for onnx
#0 18.96 Failed to build onnx
#0 18.96 ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
------
Dockerfile.cuda:16
--------------------
  15 |     
  16 | >>> RUN cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requireme\
  17 | >>> nts.txt && /bin/bash ./build.sh --allow_running_as_root --skip_submodule_sync --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) 'CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;86'
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requirements.txt && /bin/bash ./build.sh --allow_running_as_root --skip_submodule_sync --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) 'CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;86'" did not complete successfully: exit code: 1
```

**Comment by snnn** [comment]
This is because the latest development is using a not released ONNX version. We will change it to a released version when we do a release, and the problem will be solved.
