### ISSUE TITLE
[Build] Error: cpuid.h: No such file or directory when cross-compiling ORT 1.15.1 with NNAPI for arm64

### ISSUE THREAD

**Issue by louismeeckers** [microsoft/onnxruntime#17283]
### Describe the issue

When building/cross-compiling ONNX runtime 1.15.1 with the execution provider NNAPI (Android Neural Networks API) from a Linux x86-64 device for an arm64 device. I encounter an error at 84% because it seems that ARM does not have the CPUID feature.

### Target platform

arm64

### Build script

1) `source /u1/sdk/fsl-imx-xwayland/5.15-kirkstone-imx8mp/environment-setup-armv8a-poky-linux`
2) `alias cmake="/u1/miniconda3/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$OECORE_NATIVE_SYSROOT/usr/share/cmake/OEToolchainConfig.cmake -DONNX_CUSTOM_PROTOC_EXECUTABLE=/u1/protoc/bin/protoc"`
3) `./build.sh --config MinSizeRel --minimal_build extended --use_nnapi --disable_ml_ops --disable_exceptions --build_shared_lib --skip_tests`

CMake version is 3.27.0
protobuf version is 21.12

### Error / output

```
[ 84%] Building C object _deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/src/x86/init.c.o
In file included from /u1/onnxruntime_1.15.1/build/Linux/MinSizeRel/_deps/pytorch_cpuinfo-src/src/x86/init.c:5:
/u1/onnxruntime_1.15.1/build/Linux/MinSizeRel/_deps/pytorch_cpuinfo-src/src/x86/cpuid.h:5:18: fatal error: cpuid.h: No such file or directory
    5 |         #include <cpuid.h>
      |                  ^~~~~~~~~
compilation terminated.
gmake[2]: *** [_deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/build.make:118: _deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/src/x86/init.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:5324: _deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/u1/onnxruntime_1.15.1/tools/ci_build/build.py", line 2599, in <module>
    sys.exit(main())
  File "/u1/onnxruntime_1.15.1/tools/ci_build/build.py", line 2495, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/u1/onnxruntime_1.15.1/tools/ci_build/build.py", line 1434, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/u1/onnxruntime_1.15.1/tools/ci_build/build.py", line 781, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/u1/onnxruntime_1.15.1/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/u1/sdk/fsl-imx-xwayland/5.15-kirkstone-imx8mp/sysroots/x86_64-pokysdk-linux/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/u1/sdk/fsl-imx-xwayland/5.15-kirkstone-imx8mp/sysroots/x86_64-pokysdk-linux/usr/bin/cmake', '--build', '/u1/onnxruntime_1.15.1/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.
```

**Comment by skottmckay** [comment]
We build for arm and arm64 in CIs so it should work.

Not clear what you're trying to do though. NNAPI is an Android EP and it looks like you're doing a linux build. For Android you need to build with the Android NDK.

https://onnxruntime.ai/docs/build/android.html

**Comment by mlxu995** [comment]
same error when build from a Linux x86-64 device for an arm64 device (qnx platform).
Looking forward to getting some direction on how to build the onnxruntime for qnx

**Comment by bo-nemk** [comment]
Ran into something similar, what worked for me was to add the "--update" to the ./build.sh script. For transparency, the full command I ran was:

```
./build.sh --config MinSizeRel \
    --arm \
    --update \
    --build_shared_lib \
    --allow_running_as_root \
    --parallel 8 \
    --skip_tests \
    --compile_no_warning_as_error
```

This seems to update the make files. Apparently, it doesn't build them. So what I did was that I navigated to the build files (`/build/Linux/MinSizeRel` in my case), and confidently typed "make". That resolved the issue. Maybe it will help you too!

**Comment by skottmckay** [comment]
@mlxu995 what command line did you use? 

I'm not familiar with QNX. Does building for that platform usually involve the Android NDK or is there some QNX toolchain on top of the Android NDK that needs to be used? 

The original issue was attempting to do a linux build with NNAPI enabled. This combination is really only for unit testing some aspects of the NNAPI execution provider which run on CPU and don't require Android like node assignment. To do a build *FOR* Android with NNAPI enabled the Android build instructions using the Android NDK need to be followed.
