### ISSUE TITLE
[Build] subprocess.CalledProcessError: Command '['/home/ubuntu/onnx/bin/cmake', '--build', '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j8']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by ria143** [microsoft/onnxruntime#17418]
### Describe the issue

I've been trying to build ORT with oneDNN EP for several days, but I keep running into the following error which I can't solve:

```
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 2088, in <module>
    sys.exit(main())
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 2023, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 1060, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ubuntu/onnxruntime/tools/python/util/run.py", line 39, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/ubuntu/onnx/bin/cmake', '--build', '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j8']' returned non-zero exit status 2.
```

### Target platform

Ubuntu 20.04

### Build script

`./build.sh --use_dnnl --parallel --build_shared_lib --build_wheel --config RelWithDebInfo`

### Error / output

`subprocess.CalledProcessError: Command '['/home/ubuntu/onnx/bin/cmake', '--build', '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j8']' returned non-zero exit status 2.`

### GCC / Compiler Version

gcc 9.4.0

**Comment by skottmckay** [comment]
Where is cmake installed and what version is installed? Run `cmake --version` from the same shell you're building in to check.

/home/ubuntu/onnx/bin/cmake' Is not where I'd expect it to be found.

**Comment by ria143** [comment]
```
(onnx) ubuntu:~$ cmake --version
cmake version 3.27.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(onnx) ubuntu:~$ which cmake
/home/ubuntu/onnx/bin/cmake
```

Here onnx is the name of the virtual environment I am using.

**Comment by snnn** [comment]
The error comes from a child process of `make`, not cmake. Please show us more logs so that we can help. You may also redirct the logs to a log file and search `error:` there.

**Comment by ria143** [comment]
These are all the errors I got from the logs:

```
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/onnxruntime/python/backend/backend.py:8:1: F401 'onnx.ModelProto' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/onnxruntime/python/backend/backend_rep.py:10:1: F401 'typing.Any' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/onnxruntime/python/backend/backend_rep.py:10:1: F401 'typing.Tuple' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/nuget/generate_nuspec_for_native_nuget.py:466:11: E275 missing whitespace after keyword
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/nuget/validate_nuget.py:129:15: E275 missing whitespace after keyword
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Any' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Sequence' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Dict' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.List' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Type' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Set' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:21:1: F401 'typing.Tuple' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:22:1: F401 'onnx.AttributeProto' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_contrib_doc.py:22:1: F401 'onnx.FunctionProto' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/gen_opkernel_doc.py:11:1: F401 'typing.Type' imported but unused
[flake8 PEP8 ERROR] /home/ubuntu/onnxruntime/tools/python/ort_test_dir_utils.py:217:23: E275 missing whitespace after keyword
```

```
Cloning into 'pybind11'...
HEAD is now at 00a0aa99 v2.4.0 release
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo/pybind11/src/pybind11/tools/clang'...
make[2]: *** [CMakeFiles/pep8_check.dir/build.make:82: CMakeFiles/pep8_check] Error 1
make[1]: *** [CMakeFiles/Makefile2:1925: CMakeFiles/pep8_check.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 2088, in <module>
    sys.exit(main())
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 2023, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 1060, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ubuntu/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ubuntu/onnxruntime/tools/python/util/run.py", line 39, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/ubuntu/onnx/bin/cmake', '--build', '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j8']' returned non-zero exit status 2.
```

**Comment by skottmckay** [comment]
What version of ORT are you trying to build? With the latest version the pybind11 build would be under a _deps folder in the build output directory which isn't the case based on this message `Cloning into '/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo/pybind11/src/pybind11/tools/clang`

Can you also try completely deleting the build output directory (/home/ubuntu/onnxruntime/build/Linux/RelWithDebInfo) to make sure you're building from a completely clean setup.

**Comment by ria143** [comment]
Deleting just the output directory didn't work but starting over on a new instance did. You are correct, the directories were all messed up for some reason. After building on a new instance I was able to install and compile a program. Thank you for the help!

**Comment by ria143** [comment]
Deleting just the output directory didn't work but starting over on a new instance did. You are correct, the directories were all messed up for some reason. After building on a new instance I was able to install and compile a program. Thank you for the help!
