### ISSUE TITLE
list index (1) out of range in onnxruntime/transformers/fusion_transpose.py

### ISSUE THREAD

**Issue by kazssym** [microsoft/onnxruntime#17582]
I got the following error while optimizing an opset 12 unet model.

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\kazssym\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\kazssym\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\kazssym\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "c:\Users\kazssym\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\kazssym\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\models\stable_diffusion\optimize_pipeline.py", line 343, in <module>
    main()
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\models\stable_diffusion\optimize_pipeline.py", line 336, in main
    optimize_stable_diffusion_pipeline(
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\models\stable_diffusion\optimize_pipeline.py", line 247, in optimize_stable_diffusion_pipeline
    _optimize_sd_pipeline(
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\models\stable_diffusion\optimize_pipeline.py", line 139, in _optimize_sd_pipeline
    m = optimize_model(
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\optimizer.py", line 335, in optimize_model
    optimizer = optimize_by_fusion(model, model_type, num_heads, hidden_size, optimization_options)
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\optimizer.py", line 202, in optimize_by_fusion
    optimizer.optimize(optimization_options)
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\onnx_model_unet.py", line 136, in optimize
    insert_transpose_fusion.apply()
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\fusion_base.py", line 71, in apply
    self.fuse(node, input_name_to_nodes, output_name_to_node)
  File "e:\onnxruntime\.venv\lib\site-packages\onnxruntime\transformers\fusion_transpose.py", line 131, in fuse
    self.model.get_constant_value(unsqueeze_3.input[1]) == 3
IndexError: list index (1) out of range
```

The error location is here.

https://github.com/microsoft/onnxruntime/blob/705f8a371886828dcd2a380d10ba3a6549a60b9b/onnxruntime/python/tools/transformers/fusion_transpose.py#L131

I found `input` has only one element by debugging. Is it expected to have two instead?

**Comment by wangyems** [comment]
if using opset 13, unsqueeze is expected to have two inputs: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Unsqueeze

you can try export your model with newer opset or try modifying the code to get constant value from node's attributes based on op spec for opset 11: https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Unsqueeze-11

**Comment by tianleiwu** [comment]
@kazssym, thanks for reporting the issue. It is a bug that the fusion does not work with older opset.

It is recommended to use opset 14 to export stable diffusion models. That's also default setting in diffusers:
https://github.com/huggingface/diffusers/blob/73bb97adfc3d0cb184c5fd66a1d5699c249a7fd8/scripts/convert_stable_diffusion_checkpoint_to_onnx.py#L257
We have tested opset 14 for stable diffusion.
