### ISSUE TITLE
quantize_static fail with HistogramCalibrater.

### ISSUE THREAD

**Issue by guotuofeng** [microsoft/onnxruntime#17619]
### Describe the issue

In quantize_static, the TensorsData is created by using 
```
                if len(v) == 4:
                    self.data[k] = TensorData(lowest=v[0], highest=v[1], histogram=v[2], bins=v[3])
```
However, in `TensorData.__init__`, the following logic is check the keyword args.
```
class TensorData:
    _allowed = frozenset(["avg", "std", "lowest", "highest", "hist", "hist_edges"])

    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            if k not in TensorData._allowed:
                raise ValueError(f"Unexpected value {k!r} not in {TensorData._allowed}.")
            setattr(self, k, v)

    @property
    def range_value(self):
        if not hasattr(self, "lowest") or not hasattr(self, "highest"):
            raise AttributeError(f"Attributes 'lowest' and/or 'highest' missing in {dir(self)}.")
        return (self.lowest, self.highest)

    @property
    def avg_std(self):
        if not hasattr(self, "avg") or not hasattr(self, "std"):
            raise AttributeError(f"Attributes 'avg' and/or 'std' missing in {dir(self)}.")
        return (self.avg, self.std)
```

We can see the histogram key is not in the allowed keyword, therefore the following errors are raised.
```
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/***/passes/onnx/quantization.py", line 408, in _run_for_config
    quantize_static(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/onnxruntime/quantization/quantize.py", line 436, in quantize_static
    tensors_range = calibrator.compute_data()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/onnxruntime/quantization/calibrate.py", line 504, in compute_data
    return TensorsData(cal, self.collector.compute_collection_result())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/onnxruntime/quantization/calibrate.py", line 58, in __init__
    self.data[k] = TensorData(lowest=v[0], highest=v[1], histogram=v[2], bins=v[3])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/onnxruntime/quantization/calibrate.py", line 30, in __init__
    raise ValueError(f"Unexpected value {k!r} not in {TensorData._allowed}.")
ValueError: Unexpected value 'histogram' not in frozenset({'hist', 'lowest', 'hist_edges', 'avg', 'std', 'highest'}).
```

### To reproduce

See https://aiinfra.visualstudio.com/PublicPackages/_build/results?buildId=357286&view=logs&jobId=35ea891e-7d20-5395-2445-be2fa0298764&j=5f33dc1f-8f24-5b97-62d3-f49845ddf6c9&t=d902c85d-ad1e-5c9a-ae64-6b490d39ff57.

### Urgency

This bug break the onnxruntime quantization. it is a blocker.

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.6.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by LightSun** [comment]
same to me . how to fix it ?? 
```
    raise ValueError(f"Unexpected value {k!r} not in {TensorData._allowed}.")
ValueError: Unexpected value 'histogram' not in frozenset({'std', 'hist_edges', 'highest', 'avg', 'lowest', 'hist'}).

```
