### ISSUE TITLE
[Web] 

### ISSUE THREAD

**Issue by nikolaydyankov** [microsoft/onnxruntime#17700]
### Describe the issue

After updating to 1.16.0 I started getting this error:

```
Uncaught (in promise) Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [webnn] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.
    at t.resolveBackend (backend-impl.js:91:11)
    at async i.create (inference-session-impl.js:175:15)
    at async createSAM (SAM.ts:59:19)
    at async init (http://localhost:5001/src/routes/(app)/app/project/[projectId]/auto-detect/+page.svelte:936:9)
```

When I downgrade to 1.15.1 it's working again without errors. I'm using SvelteKit and made a bare minimum repo if you want to reproduce it.

### To reproduce

```
git clone https://github.com/nikolaydyankov/onnx-runtime-web-issue
npm install
npm run dev
```
Open localhost:5174 and see the console. Changing it back to 1.15.1 will remove the error.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by MountainAndMorning** [comment]
I am using electron of onnxruntime-web and get a `Not Found` error: 
```js
localhost:5173/Users/liangwanyou/Documents/TIMESlicePro/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/ort-wasm-simd.wasm 404
```

**Comment by hariharans29** [comment]
Hi @fs-eire / @guschmue - Can you please take a look ?

**Comment by fs-eire** [comment]
will take a look.

**Comment by fs-eire** [comment]
I was too busy back then and I am currently in vacation. Probably someone can help on this issue, or when I got some time after my vacation.
