### ISSUE TITLE
Can't build it from source

### ISSUE THREAD

**Issue by guranu** [microsoft/onnxruntime#17750]
### Describe the issue

Hello, so i wanted to build onnxruntime but when i try to i get this error:
```
~/onnxruntime $ ./build.sh --config RelWithDebInfo --build_shared_lib --parallel
2023-09-29 15:38:18,790 build [DEBUG] - Command line arguments:
  --build_dir /data/data/com.termux/files/home/onnxruntime/build/Linux --config RelWithDebInfo --build_shared_lib --parallel
Namespace(build_dir='/data/data/com.termux/files/home/onnxruntime/build/Linux', config=['RelWithDebInfo'], update=False, build=False, clean=False, parallel=0, nvcc_threads=-1, test=False, skip_tests=False, compile_no_warning_as_error=False, enable_nvtx_profile=False, enable_memory_profile=False, enable_training=False, enable_training_apis=False, enable_training_ops=False, enable_nccl=False, mpi_home=None, nccl_home=None, use_mpi=False, enable_onnx_tests=False, path_to_protoc_exe=None, fuzz_testing=False, enable_symbolic_shape_infer_tests=False, gen_doc=None, gen_api_doc=False, use_cuda=False, cuda_version=None, cuda_home=None, cudnn_home=None, enable_cuda_line_info=False, enable_pybind=False, build_wheel=False, wheel_name_suffix=None, numpy_version=None, skip_keras_test=False, build_csharp=False, build_nuget=False, msbuild_extra_options=None, build_java=False, build_nodejs=False, build_objc=False, build_shared_lib=True, build_apple_framework=False, cmake_extra_defines=None, target=None, x86=False, arm=False, arm64=False, arm64ec=False, msvc_toolset=None, windows_sdk_version=None, android=False, android_abi='arm64-v8a', android_api=27, android_sdk_path='', android_ndk_path='', android_cpp_shared=False, android_run_emulator=False, use_gdk=False, gdk_edition='.', gdk_platform='Scarlett', ios=False, ios_sysroot='', ios_toolchain_file='', xcode_code_signing_team_id='', xcode_code_signing_identity='', cmake_generator=None, osx_arch='x86_64', apple_deploy_target=None, disable_memleak_checker=False, build_wasm=False, build_wasm_static_lib=False, emsdk_version='3.1.44', enable_wasm_simd=False, enable_wasm_threads=False, disable_wasm_exception_catching=False, enable_wasm_api_exception_catching=False, enable_wasm_exception_throwing_override=True, wasm_run_tests_in_browser=False, enable_wasm_profiling=False, enable_wasm_debug_info=False, wasm_malloc=None, emscripten_settings=None, use_extensions=False, extensions_overridden_path=None, cmake_path='cmake', ctest_path='ctest', skip_submodule_sync=False, use_mimalloc=False, use_dnnl=False, dnnl_gpu_runtime='', dnnl_opencl_root='', use_openvino=None, use_coreml=False, use_webnn=False, use_snpe=False, snpe_root=None, use_nnapi=False, nnapi_min_api=None, use_jsep=False, use_qnn=False, qnn_home=None, use_rknpu=False, use_preinstalled_eigen=False, eigen_path=None, enable_msinternal=False, llvm_path=None, use_vitisai=False, use_tvm=False, tvm_cuda_runtime=False, use_tvm_hash=False, use_tensorrt=False, use_tensorrt_builtin_parser=True, use_tensorrt_oss_parser=False, tensorrt_home=None, test_all_timeout='10800', use_migraphx=False, migraphx_home=None, use_full_protobuf=False, llvm_config='', skip_onnx_tests=False, skip_winml_tests=False, skip_nodejs_tests=False, enable_msvc_static_runtime=False, enable_language_interop_ops=False, use_dml=False, dml_path='', use_winml=False, winml_root_namespace_override=None, dml_external_project=False, use_telemetry=False, enable_wcos=False, enable_lto=False, enable_transformers_tool_test=False, use_acl=None, acl_home=None, acl_libs=None, use_armnn=False, armnn_relu=False, armnn_bn=False, armnn_home=None, armnn_libs=None, build_micro_benchmarks=False, minimal_build=None, include_ops_by_config=None, enable_reduced_operator_type_support=False, disable_contrib_ops=False, disable_ml_ops=False, disable_rtti=False, disable_types=[], disable_exceptions=False, rocm_version=None, use_rocm=False, rocm_home=None, code_coverage=False, enable_lazy_tensor=False, ms_experimental=False, enable_external_custom_op_schemas=False, external_graph_transformer_path=None, enable_cuda_profiling=False, use_cann=False, cann_home=None, enable_rocm_profiling=False, use_xnnpack=False, use_azure=False, use_cache=False, use_triton_kernel=False, use_lock_free_queue=False, allow_running_as_root=False)
2023-09-29 15:38:18,797 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2023-09-29 15:38:18,797 build [INFO] - Build started
Synchronizing submodule url for 'cmake/external/emsdk'
Synchronizing submodule url for 'cmake/external/libprotobuf-mutator'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
2023-09-29 15:38:19,847 build [INFO] - Generating CMake build tree
CMake Deprecation Warning at CMakeLists.txt:14 (cmake_policy):
  The OLD behavior for policy CMP0104 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Warning (dev) at CMakeLists.txt:55 (include):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.27/Modules/Dart.cmake:47 (message):
  Policy CMP0145 is not set: The Dart and FindDart modules are removed.  Run
  "cmake --help-policy CMP0145" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:55 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /data/data/com.termux/files/usr/share/cmake-3.27/Modules/Dart.cmake:57 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable DART_ROOT is set to:

    DART_ROOT-NOTFOUND

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
Call Stack (most recent call first):
  CMakeLists.txt:55 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

Building ONNX Runtime for aarch64
Patch found: /data/data/com.termux/files/usr/bin/patch
Loading Dependencies URLs ...
Loading Dependencies ...
-- Abseil source dir:
-- Populating date
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/date-subbuild
[100%] Built target date-populate
-- Populating google_nsync
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/google_nsync-subbuild
[100%] Built target google_nsync-populate
CMake Deprecation Warning at /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/google_nsync-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Populating safeint
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/safeint-subbuild
[100%] Built target safeint-populate
-- Populating utf8_range
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/utf8_range-subbuild
[100%] Built target utf8_range-populate
-- Populating protobuf
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/protobuf-subbuild
[100%] Built target protobuf-populate
--
-- 3.21.12.0
-- Populating nlohmann_json
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/nlohmann_json-subbuild
[100%] Built target nlohmann_json-populate
CMake Deprecation Warning at /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/nlohmann_json-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Using the single-header code from /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/nlohmann_json-src/single_include/
-- Populating mp11
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/mp11-subbuild
[100%] Built target mp11-populate
-- Populating gsl
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/gsl-subbuild
[100%] Built target gsl-populate
-- Populating flatbuffers
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/flatbuffers-subbuild
[100%] Built target flatbuffers-populate
CMake Deprecation Warning at /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/flatbuffers-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Populating pytorch_cpuinfo
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/pytorch_cpuinfo-subbuild
[100%] Built target pytorch_cpuinfo-populate
-- Populating googletest
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/googletest-subbuild
[100%] Built target googletest-populate
-- Populating eigen
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/eigen-subbuild
[100%] Built target eigen-populate
-- Populating onnx
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild
[100%] Built target onnx-populate
CMake Deprecation Warning at /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-src/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-src/CMakeLists.txt:112 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Generated: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-build/onnx/onnx-ml.proto
Generated: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-build/onnx/onnx-operators-ml.proto
Generated: /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-build/onnx/onnx-data.proto
--
-- ******** Summary ********
--   CMake version                     : 3.27.6
--   CMake command                     : /data/data/com.termux/files/usr/bin/cmake
--   System                            : Android
--   C++ compiler                      : /data/data/com.termux/files/usr/bin/c++
--   C++ compiler version              : 16.0.6
--   CXX flags                         :  -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -Wnon-virtual-dtor
--   Build type                        : RelWithDebInfo
--   Compile definitions               : ORT_ENABLE_STREAM;EIGEN_MPL2_ONLY;_GNU_SOURCE;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH                 : /data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/installed
--   CMAKE_INSTALL_PREFIX              : /usr/local
--   CMAKE_MODULE_PATH                 : /data/data/com.termux/files/home/onnxruntime/cmake/external
--
--   ONNX version                      : 1.15.0rc1
--   ONNX NAMESPACE                    : onnx
--   ONNX_USE_LITE_PROTO               : ON
--   USE_PROTOBUF_SHARED_LIBS          : OFF
--   Protobuf_USE_STATIC_LIBS          : ON
--   ONNX_DISABLE_EXCEPTIONS           : OFF
--   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
--   ONNX_WERROR                       : OFF
--   ONNX_BUILD_TESTS                  : OFF
--   ONNX_BUILD_BENCHMARKS             : OFF
--
--   Protobuf compiler                 :
--   Protobuf includes                 :
--   Protobuf libraries                :
--   BUILD_ONNX_PYTHON                 : OFF
Finished fetching external dependencies
NVCC_ERROR =
NVCC_OUT = No such file or directory
CMake Error: File /data/data/com.termux/files/home/onnxruntime/requirements.txt.in does not exist.
CMake Error at CMakeLists.txt:1365 (configure_file):
  configure_file Problem configuring file


CMake Warning at CMakeLists.txt:1568 (message):
  MPI and NCCL disabled on Win build.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/onnxruntime/tools/ci_build/build.py", line 2695, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/home/onnxruntime/tools/ci_build/build.py", line 2553, in main
    generate_build_tree(
  File "/data/data/com.termux/files/home/onnxruntime/tools/ci_build/build.py", line 1429, in generate_build_tree
    run_subprocess(
  File "/data/data/com.termux/files/home/onnxruntime/tools/ci_build/build.py", line 800, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data/data/com.termux/files/usr/bin/cmake', '/data/data/com.termux/files/home/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/data/data/com.termux/files/usr/bin/python3', '-DPYTHON_EXECUTABLE=/data/data/com.termux/files/usr/bin/python3', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_USE_JSEP=OFF', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=OFF', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_WEBNN=OFF', '-Donnxruntime_USE_CANN=OFF', '-Donnxruntime_USE_TRITON_KERNEL=OFF', '-Donnxruntime_DISABLE_FLOAT8_TYPES=OFF', '-Donnxruntime_DISABLE_SPARSE_TENSORS=OFF', '-Donnxruntime_DISABLE_OPTIONAL_TYPE=OFF', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_PREFIX_PATH=/data/data/com.termux/files/home/onnxruntime/build/Linux/RelWithDebInfo/installed']' returned non-zero exit status 1.
```

I was expecting it to be built just fine.

### To reproduce

`./build.sh --config RelWithDebInfo --build_shared_lib --parallel`

### Urgency

No it isn't urgent.

### Platform

Android

### OS Version

10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

#17655

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Other / Unknown

**Comment by skottmckay** [comment]
Building on termux is untested and unsupported. 

Supported builds involve using the Android NDK. Instructions are here: https://onnxruntime.ai/docs/build/android.html

There are also pre-built packages for Android containing an AAR with support for multiple architectures on Maven and Nuget

https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime

**Comment by romanovj** [comment]
compiled in termux with
`LDFLAGS=-llog ./build.sh --config Release --build_shared_lib  --build_wheel --cmake_extra_defines CMAKE_INSTALL_PREFIX=$PREFIX CMAKE_SHARED_LINKER_FLAGS="-llog" CMAKE_SYSTEM_NAME=Linux CMAKE_SYSTEM_PROCESSOR=aarch64  --skip_submodule_sync`

tests on Snapdragon 662

```
[  FAILED  ] NhwcTransformerTests.ConvFp16
[  FAILED  ] NhwcTransformerTests.ConvMaxPoolFp16
[  FAILED  ] NhwcTransformerTests.ConvGlobalAveragePoolFp16
[  FAILED  ] NhwcTransformerTests.ConvAveragePoolFp16
```
