### ISSUE TITLE
[Build] Building wasm static lib in docker

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/onnxruntime#17780]
### Describe the issue

On Apple M2, Emscripten build fails when compiled in docker (from debian:12.1). There are two issues to address:

1. Emsdk installing fails `error: tool or SDK not found: '3.1.46'`:

```
2023-10-04 06:25:05,002 build [INFO] - Installing emsdk...
WARNING: arm64-linux binaries are not available for all releases.
See https://github.com/emscripten-core/emsdk/issues/547
error: tool or SDK not found: '3.1.46'
Traceback (most recent call last):
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 2695, in <module>
    sys.exit(main())
             ^^^^^^
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 2534, in main
    run_subprocess([emsdk_file, "install", emsdk_version], cwd=emsdk_dir)
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 800, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/piper-wasm/modules/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/piper-wasm/modules/onnxruntime/cmake/external/emsdk/emsdk', 'install', '3.1.46']' returned non-zero exit status 1.
```

2. When emsdk issue is resolved, the build proceeds until it fails on `qemu-i386: Could not open '/lib/ld-linux.so.2': No such file or directory`

```

-- WebAssembly Build is enabled
-- Configuring done (83.8s)
-- Generating done (4.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    Python_EXECUTABLE
    onnxruntime_EMSCRIPTEN_SETTINGS


-- Build files have been written to: /piper-wasm/modules/onnxruntime/build/Linux/Release
2023-10-04 06:20:29,039 build [INFO] - Building targets for Release configuration
[  0%] Running gen_proto.py on onnx/onnx.in.proto
Processing /piper-wasm/modules/onnxruntime/build/Linux/Release/_deps/onnx-src/onnx/onnx.in.proto
Writing /piper-wasm/modules/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto
Writing /piper-wasm/modules/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto3
generating /piper-wasm/modules/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx_pb.py
[  0%] Running C++ protocol buffer compiler on /piper-wasm/modules/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto
qemu-i386: Could not open '/lib/ld-linux.so.2': No such file or directory
gmake[2]: *** [_deps/onnx-build/CMakeFiles/gen_onnx_proto.dir/build.make:74: _deps/onnx-build/onnx/onnx-ml.pb.cc] Error 255
gmake[1]: *** [CMakeFiles/Makefile2:5585: _deps/onnx-build/CMakeFiles/gen_onnx_proto.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 2695, in <module>
    sys.exit(main())
             ^^^^^^
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 2588, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 1494, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/piper-wasm/modules/onnxruntime/tools/ci_build/build.py", line 800, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/piper-wasm/modules/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/piper-wasm/modules/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
root@e24313a5d869:/piper-wasm/modules/onnxruntime# 
```

### Target platform

wasm

### Build script

Following flags are being used:

```
./build.sh --config Release --build_wasm_static_lib --skip_tests --enable_wasm_debug_info --allow_running_as_root --disable_wasm_exception_catching --disable_rtti --emsdk_version 3.1.46
```

same errors when added

```
--cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64
```

### Error / output

`error: tool or SDK not found: '3.1.46'`

`qemu-i386: Could not open '/lib/ld-linux.so.2': No such file or directory`

**Comment by jozefchutka** [comment]
The workaround is to build using 64bit docker image which contains `/lib/ld-linux.so.2`

```
docker run -it --platform linux/amd64 debian:12.1
```
