### ISSUE TITLE
[Documentation] How do I use the DirectML EP from an NUnit unit test?

### ISSUE THREAD

**Issue by klasma** [microsoft/onnxruntime#17793]
I am not able to select the DirectML EP from a unit test. I assume that it is possible somehow and therefore I am tagging this as a documentation issue. I am using version 1.16.0 of the Microsoft.ML.OnnxRuntime.DirectML nuget and Windows 10. Here is the code that I am running:

```
using Microsoft.ML.OnnxRuntime;

namespace DirectMLTest
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void Test1()
        {
            var sessionOptions = new SessionOptions();
            sessionOptions.AppendExecutionProvider_DML();
            Assert.Pass();
        }
    }
}
```

I am getting the following error:

Microsoft.ML.OnnxRuntime.OnnxRuntimeException : [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\providers\dml\dml_provider_factory.cc(158)\onnxruntime.DLL!00007FFCAB1BA1C0: (caller: 00007FFCAB1B9EAE) Exception(1) tid(9b74) 887A0004 The specified device interface or feature level is not supported on this system.

   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_DML(Int32 deviceId)
   at DirectMLTest.Tests.Test1() in C:\git\DirectMLTest\DirectMLTest\DirectMLTest\UnitTest1.cs:line 16

If I run the same code in a console app, everything works as expected and it also works if I replace AppendExecutionProvider_DML with AppendExecutionProvider_CPU.

I am using the x64 configuration and not Any CPU. I read that the Any CPU configuration could cause similar problems.

**Comment by wschin** [comment]
Looks like you have an old DirectML. The code throwing that error is
```
  ORT_THROW_IF_FAILED(DMLCreateDevice1(d3d12_device.Get(),
                                   flags,
                                   DML_FEATURE_LEVEL_5_0,
                                   IID_PPV_ARGS(&dml_device)));
```
And `DML_FEATURE_LEVEL_5_0` is available after DirectML version 1.8.0.

**Comment by wchao1115** [comment]
@klasma if you get your ORT package from nuget.org, the dependencies tab should clearly mark which corresponding version of DirectML you'll need to successfully run ORT end to end. i.e. https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.DirectML#dependencies-body-tab

**Comment by klasma** [comment]
Thank you very much for your input. I am getting the Microsoft.ML.OnnxRuntime.DirectML nuget from nuget.org and the correct version of DirectML.dll seems to be in the bin directory next to my test assembly. Is an older version of the dll found somewhere in my windows installation? At first I thought that "C:\Windows\System32\directml.dll" was found, but if I drop that file in the bin-directory of my console application where everything works fine, I get a different error so I assumed that that was not the case. How do I solve this issue?

![image](https://github.com/microsoft/onnxruntime/assets/3187096/83a076b2-7260-4d53-99e2-84a4d4cafd72)

**Comment by edward0802** [comment]
@klasma did you resolve this issue on Windows 10?

**Comment by klasma** [comment]
No, i did not.

**Comment by edward0802** [comment]
@klasma thanks for the quick response. So there is no way to use Microsoft.ML.OnnxRuntime.DirectML v 1.16.0 on Windows 10? how about lower versions of Microsoft.ML.OnnxRuntime.DirectML do they work on Windows 10?

**Comment by klasma** [comment]
I was able to run inrerence, but not from tests in NUnit.

**Comment by klasma** [comment]
I never tried earlier versions.
