### ISSUE TITLE
session.disable_fallback() not working

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#17801]
### Describe the issue

When I specify CUDA EP, I expect that CUDA EP can be used in running session, but currently it falls back to CPU if CUDA EP has problem (like CUDA is not installed properly). Even when I disable fallback, the session still run in CPU EP.

### To reproduce

Install onnxruntime-gpu, but not install CUDA. Then try the following in python:

```
>>> import onnxruntime
>>> onnxruntime.__version__
'1.16.0'
>>> onnxruntime.get_available_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
>>> session = onnxruntime.InferenceSession("bert.onnx", providers=["CUDAExecutionProvider"])
2023-10-05 21:29:53.926793500 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2023-10-05 21:29:53.926827876 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:743 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
>>> session
<onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7f603c32fd90>
>>> session.get_providers()
['CPUExecutionProvider']
>>> import numpy as np
>>> session.run(None, {"input_ids": np.ones((1,77), dtype=np.int64), "input_mask": np.ones((1,77), dtype=np.int64), "segment_ids": np.ones((1,77), dtype=np.int64)})
[array([[ 1.0981518, -1.7005944]], dtype=float32)]
>>> session.disable_fallback()
>>> session.get_providers()
['CPUExecutionProvider']
>>> session.run(None, {"input_ids": np.ones((1,77), dtype=np.int64), "input_mask": np.ones((1,77), dtype=np.int64), "segment_ids": np.ones((1,77), dtype=np.int64)})
[array([[ 1.0981518, -1.7005944]], dtype=float32)]
```
Note: it seems that ORT 1.15.1 shows same behavior in Ubuntu so it is not a regression in ORT 1.16.

In Windows, the behavior is different (session creation failed):
```
>>> import onnxruntime
>>> onnxruntime.__version__
'1.16.0'
>>> onnxruntime.get_available_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
>>> session = onnxruntime.InferenceSession("E:\\sd_onnx\\sd-v1-5\\text_encoder\\model.onnx", providers=["CUDAExecutionProvider"])
2023-10-05 13:48:06.8260551 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-10-05 13:48:07.1677740 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 471, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\tlwu\.conda\envs\py310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 471, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
>>> session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'session' is not defined
```

### Urgency

Not urgent so you can treat it as low priority.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

pip install onnxruntime-gpu

### ONNX Runtime Version or Commit ID

1.16

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

None

**Comment by wschin** [comment]
Per the error message, looks like CUDA is not found by that EP.
```
EP Error E:\git\onnxruntime\onnxruntime\python\onnxruntime_pybind_state.cc:729 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page, make sure they're in the PATH, and that your GPU is supported.
```

A few things you can try.
- check if `pip onnxruntime-gpu` is installed (not `pip onnxruntime`)
- if you build from source, make sure the cuda library used to build ORT is discoverable.
- try `pip uninstall onnxruntime` to ensure not using old version.

**Comment by tianleiwu** [comment]
The session creation has a regression in 1.16 for Windows.
In 1.15.1, session creation with CUDA EP will fail if CUDA is not available. 
In 1.16, session creation is good (even though there is warning that session falls back to CPU EP) in same situation.

**Comment by tianleiwu** [comment]
Closed as not reproduced in official package.

**Comment by tianleiwu** [comment]
It seems that the error can reproduce in Ubuntu with ORT 1.16, so reopen the issue.

**Comment by pranavsharma** [comment]
This is weird. I tried reproducing this on all my machines and couldn't repro it even once. Without a GPU or CUDA deps you shouldn't be able to create a session in the first place, let alone call disable_fallback.
1. Windows machine (doesn't have a GPU card)
2. WSL2 (Ubuntu 20) (doesn't have a GPU card)
3. Linux machine (CUDA not installed)

May be give us access to your VM?

**Comment by snnn** [comment]
In your original issue's description, it said:

```
libcublasLt.so.11: cannot open shared object file: No such file or directory
```
So, it was all because it could not find CUDA. You have to fix it before you can disable CPU fallback.

**Comment by snnn** [comment]
So, you suggest that when CUDA is not available and the user has set to "disable_fallback()", the session should directly fail instead of running the model on CPU?

**Comment by pranavsharma** [comment]
> So, you suggest that when CUDA is not available and the user has set to "disable_fallback()", the session should directly fail instead of running the model on CPU? Is it the problem you want use to fix?

Well, the first issue is session should not even get constructed if CUDA provider is requested and there's no CUDA/GPU on the machine. That's what I see, but not what Tianlei sees. Disable fallback is the next step. See my comment above.

**Comment by tianleiwu** [comment]
@snnn, right now the main problem is the behavior is not consistent in different OS or environment. Some has session creation failed (so cannot run session). Some has session creation successfully, and fallback to CPU EP.

Actually, I do not care about disable_fallback() itself although it looks like a bug. It is because I can use session.get_providers() to see whether CUDA EP is used in the session, or has fallback to CPU.

If there is an API like 'onnxruntime.is_cuda_available()' to tell me  that CUDA EP is available to use. That will be better.

**Comment by snnn** [comment]
For historical reasons we had some special handling in the python code for loading CUDA EP for just manylinux . I guess if we removed them out, they will be all the same.
