### ISSUE TITLE
onnxruntime infer failed on GPU (build against with TensorRT

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1786]
I built onnxruntime with TensorRT, which I hope it could use TensorRT as backend and gain a huge acceleration from it. But it says something like this:

```
2019-09-09 23:18:14.952201864 [E:onnxruntime:Default, inference_session.cc:545 Initialize] Exception during initialization: /media/jintian/netac/ai/libs/onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:333 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for MemcpyFromHost (node Memcpy_1)
Stacktrace:

Traceback (most recent call last):
  File "demo_onnxrt_maskrcnn.py", line 96, in <module>
    sess = rt.InferenceSession("models/mask_rcnn/mask_rcnn_R_50_FPN_1x.onnx")
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /media/jintian/netac/ai/libs/onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:333 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for MemcpyFromHost (node Memcpy_1)
Stacktrace:

```

The model and code can inference successfully on onnxruntime CPU, but not with GPU (one installed from pip, one build from source with GPU support)

What could be the reason?

**Comment by jinfagang** [comment]
I think my drive and CUDA has no problem...
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   47C    P8    12W / 166W |    723MiB /  8118MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1489      G   /usr/lib/xorg/Xorg                            24MiB |
|    0      1527      G   /usr/bin/gnome-shell                          83MiB |
|    0      3885      G   /usr/lib/xorg/Xorg                           213MiB |
|    0      4071      G   /usr/bin/gnome-shell                         199MiB |
|    0      5946      G   ...uest-channel-token=15699860313587730374   199MiB |
+-----------------------------------------------------------------------------+

```

**Comment by stevenlix** [comment]
This mask_rcnn model has dynamic shapes, which are not supported by TensorRT.

**Comment by jinfagang** [comment]
@stevenlix Not supported by TensorRT or not supported by onnx-tensorrt?

currently ORT can not also deal with FasterRCNN.onnx and SSD.onnx which comes from official model zoo.

Does there anyway or direction that we can do to make them support? I think nowadays more and more network have dynamic shapes such as fully convolutional networks.

**Comment by jinfagang** [comment]
@stevenlix  Hi, Does onnxruntime able to inference dynamic input now??? TensorRT 6.0 has been add this feature!

**Comment by stevenlix** [comment]
We are working with Nvidia closely on enabling dynamic shape in ORT-TRT cases. So far there are still issues to fix on TRT and will update once it's done.

**Comment by RehanSD** [comment]
Hi @stevenlix ! I'm trying to build your branch of ONNXRT with TensorRT 6.0.1.5, CUDA10.0, and cuDNN7.6.5, but I run into the following errors when running `./build.sh`:
```
1: 2019-11-16 06:53:53.269072694 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2019-11-16 06:53:53   ERROR] (Unnamed Layer* 0) [TopK]: at least 2 dimensions are required for input
```
and
```
Run failed with status: There's no data transfer registered for copying tensors from Device: [ type:0 memory_type:0 device_id:0] to Device: [ type:1 memory_type:0 device_id:0]
```
When I try importing onnxruntime in python outside the onnxruntime repository folder, the import works, but the package seems to have no attributes, and when I import it inside the folder, I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/onnxruntime/onnxruntime/__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
ImportError: No module named 'onnxruntime.capi'
```
was hoping for some help to see where the install is failing.
Thank you!

**Comment by sam-h-bean** [comment]
@stevenlix Did this ever get added? I'm running into this currently
