### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by NEUzht** [microsoft/onnxruntime#18163]
### Describe the issue

When I use vs2019 build 1.15.0 on Windows11, I get the following error "Command '['Z:environmentcmakebincmake. EXE', '--build', './build_1Release', '--config', 'Release', '--', '/maxcpucount:8', '/nodeReuse:False', '/p:CL_MPCount=8']' returned non-zero exit status 1.”

### Target platform

windows

### Build script

python ./tools/ci_build/build.py --build_dir ./build_1 --skip_tests --update --build --config Release --cmake_generator "Visual Studio 16 2019" --parallel

### Error / output

 \Release\absl_cord.lib
Traceback (most recent call last):
  File "C:\Users\zht\Desktop\文件\githubio\onnxruntime\tools\ci_build\build.py", line 2599, in <module>
    sys.exit(main())
  File "C:\Users\zht\Desktop\文件\githubio\onnxruntime\tools\ci_build\build.py", line 2495, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\Users\zht\Desktop\文件\githubio\onnxruntime\tools\ci_build\build.py", line 1434, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\zht\Desktop\文件\githubio\onnxruntime\tools\ci_build\build.py", line 781, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\zht\Desktop\文件\githubio\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "Z:\environment\anaconda\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Z:\\environment\\cmake\\bin\\cmake.EXE', '--build', './build_1\\Release', '--config', 'Release', '--', '/maxcpucount:8', '/nodeReuse:False', '/p:CL_MPCount=8']' returned non-zero exit status 1.

### Visual Studio Version

2019

**Comment by snnn** [comment]
Please try the latest ONNX Runtime release with the latest Visual Studio release.  We no longer provide fixes for ONNX Runtime 1.15.0
