### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no onnxruntime4j_jni in java.library.path

### ISSUE THREAD

**Issue by ste-q** [microsoft/onnxruntime#18512]
### Describe the issue

I have generated the custom JAR on a Ubuntu machine (Ubuntu 22.04.1) with `./build.sh --config RelWithDebInfo --build_shared_lib --parallel --enable_training --skip_tests  --build_java` command. 
I am able to train models in java using the generated JAR. 
But I am not able to use this JAR in windows machine (Windows Server 2022 Standard ). 
I am getting `Exception in thread "main" java.lang.UnsatisfiedLinkError: no onnxruntime4j_jni in java.library.path
` error.

### To reproduce

Please get the generated JAR [here](https://drive.google.com/file/d/1L4d5rIiHfcaLoHphqxUNhp1o9k2fMNv0/view?usp=sharing),

Sample training script:
```
import ai.onnxruntime.*;
import java.util.*;


public class Main {
    private static final OrtEnvironment env = OrtEnvironment.getEnvironment();
    private static DataLoader train_data;
    private static DataLoader test_data;
    private static OrtTrainingSession trainingSession;
    private OrtSession infer_model_session;
 
    this.trainingSession = env.createTrainingSession(
                "checkpoint",
                "training_model.onnx",
                "eval_model.onnx",
                "optimizer_model.onnx");
    }
    public static void main(String[] args) throws OrtException, IOException {
        Main onnx_train = new Main();
        while (onnx_train.epoch<onnx_train.epochs){
            System.out.println("Epoch: "+onnx_train.epoch);
            onnx_train.runTrain();
            onnx_train.runTest();
            onnx_train.epoch = onnx_train.epoch + 1;
        }
    }

    public void runTrain() throws  OrtException{
        ArrayList<Float> losses = new ArrayList<>();
        for (Integer batch_id : train_processed_batch.keySet())  {
            Map<String, OnnxTensor> pinnedInputs = new HashMap<>();
            pinnedInputs.put("input",train_data.get(batch_id).get("input"));
            pinnedInputs.put("labels",train_processed_batch.get(batch_id).get("label"));
            try (OrtSession.Result firstOutput = trainingSession.trainStep(pinnedInputs)) {
                OnnxValue outputBuffer = firstOutput.get(0);
                losses.add((Float) outputBuffer.getValue());
            }
            trainingSession.optimizerStep();
            trainingSession.lazyResetGrad();
        }
        System.out.println("Train loss: "+average_losses(losses));
    }

    
}
```

On a Windows machine, I am encountering the following error on the line  `private static final OrtEnvironment env = OrtEnvironment.getEnvironment();`
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no onnxruntime4j_jni in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:371)
        at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:157)
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:33)
        at Main.<clinit>(Main.java:6)
```

### Platform

Windows

### OS Version

Windows Server 2022 Standard 

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

Default CPU

**Comment by Craigacp** [comment]
You need to compile it on Windows if you want to use it on Windows. The Linux build you made only contains Linux binaries.

**Comment by ste-q** [comment]
@Craigacp 
I have generated the **JAR** on a Windows machine. When I run the training code, I encounter the following error. The same training code works well on Linux with a custom training ONNX JAR build that was generated on the Linux machine.

```
Exception in thread "main" ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: training_session.cc:85 onnxruntime::training::api::TrainingSession::OptimizerStep No optimizer session initialized.
	at ai.onnxruntime.OrtTrainingSession.optimizerStep(Native Method)
	at ai.onnxruntime.OrtTrainingSession.optimizerStep(OrtTrainingSession.java:898)
	at ai.onnxruntime.OrtTrainingSession.optimizerStep(OrtTrainingSession.java:884)
	at main.java.org.example.Main.runTrain(Main.java:28)
	at main.java.org.example.Main.main(Main.java:38)

```
I have initiated the training class along with the optimizer path as follows.

```
 env.createTrainingSession(
                "checkpoint",
                "training_model.onnx",
                "eval_model.onnx",
                "optimizer_model.onnx"
        );
```

The **optimizer_model.onnx** file was generated in Python as follows:

```
import onnxruntime.training.onnxblock as onnxblock

# Building the optimizer graph
optimizer_block = onnxblock.optim.AdamW()
with onnxblock.empty_base() as accessor:
    _ = optimizer_block(model_params)
    optimizer_model = optimizer_block.to_model_proto()

# Saving all the files to use them later for the training.
onnx.save(optimizer_model, "optimizer_model.onnx") 
```

**Comment by Craigacp** [comment]
@baijumeswani Any ideas why the optimizer step wouldn't work on Windows if it worked on Linux?

**Comment by rkoystart** [comment]
@Craigacp @baijumeswani 
any idea why the error is raising. I am also getting the same error.

**Comment by Craigacp** [comment]
This is fixed by https://github.com/microsoft/onnxruntime/pull/18891.
