### ISSUE TITLE
OrtSessionOptions::~OrtSessionOptions segment fault on application exit

### ISSUE THREAD

**Issue by comphilip** [microsoft/onnxruntime#18616]
### Describe the issue

Simple C++ application for onnxruntime inference benchmark.
```c++
#include <dnnl_provider_options.h>
#include <onnxruntime_cxx_api.h>
#include <cpu_provider_factory.h>
#include "m33.h"
#include <array>
#include <ctime>
#include <random>
#include <chrono>
#include <iostream>

int main(int argc, char **argv)
{
    OrtDnnlProviderOptions dnnl_prodiver_options;
    int num_thread = 1;
    dnnl_prodiver_options.use_arena = 1;
    dnnl_prodiver_options.threadpool_args = static_cast<void *>(&num_thread);
    Ort::SessionOptions session_option;
    session_option.SetInterOpNumThreads(1);
    session_option.SetIntraOpNumThreads(1);
    session_option.AppendExecutionProvider_Dnnl(dnnl_prodiver_options);
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CPU(session_option, 1));
    Ort::Env env;
    Ort::Session session(env, m33_onnx, m33_onnx_len, session_option);
    Ort::IoBinding iobind(session);

    const int BATCH_SIZE = 30;
    std::array<float, BATCH_SIZE * 78 * 64> input;
    std::array<float, BATCH_SIZE * 4> output;
    std::array<int64_t, 3> input_share{BATCH_SIZE, 78, 64};
    std::array<int64_t, 2> output_share{BATCH_SIZE, 4};

    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

    auto input_tensor = Ort::Value::CreateTensor(memory_info, input.data(), input.size(), input_share.data(), input_share.size());
    auto output_tensor = Ort::Value::CreateTensor(memory_info, output.data(), output.size(), output_share.data(), output_share.size());

    iobind.BindInput("modelInput", input_tensor);
    iobind.BindOutput("modelOutput", output_tensor);
    Ort::RunOptions run_option;

    std::srand(std::time(nullptr));

    std::chrono::steady_clock::time_point begin;
    const int ITER_COUNTS = 10;
    for (int i = 0; i < ITER_COUNTS; i++)
    {
        // random data
        for (float &i : input)
        {
            i = std::rand();
        }
        session.Run(run_option, iobind);
        if (i == 0)
        {
            begin = std::chrono::steady_clock::now();
        }
    }
    std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
    std::cout << "Cost per prediction: " << std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count() / (ITER_COUNTS - 1) << "[µs]" << std::endl;
    return 0;
}
```
**It works well with CPU EP only**. After adding DNNL EP, segment fault on **application exit**.
 Call stack is
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5f8258e in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555555654850) at /usr/include/c++/11/bits/shared_ptr_base.h:168
168                 _M_dispose();
(gdb) bt
#0  0x00007ffff5f8258e in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555555654850)
    at /usr/include/c++/11/bits/shared_ptr_base.h:168
#1  0x00007ffff5f79b37 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x55555564fd38, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:705
#2  0x00007ffff5fb828a in std::__shared_ptr<onnxruntime::IExecutionProviderFactory, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x55555564fd30, 
    __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#3  0x00007ffff5fb82aa in std::shared_ptr<onnxruntime::IExecutionProviderFactory>::~shared_ptr (this=0x55555564fd30, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#4  0x00007ffff5fff394 in std::_Destroy<std::shared_ptr<onnxruntime::IExecutionProviderFactory> > (__pointer=0x55555564fd30)
    at /usr/include/c++/11/bits/stl_construct.h:151
#5  0x00007ffff5ffe9ac in std::_Destroy_aux<false>::__destroy<std::shared_ptr<onnxruntime::IExecutionProviderFactory>*> (__first=0x55555564fd30, 
    __last=0x55555564fd50) at /usr/include/c++/11/bits/stl_construct.h:163
#6  0x00007ffff5ffd659 in std::_Destroy<std::shared_ptr<onnxruntime::IExecutionProviderFactory>*> (__first=0x55555564fd30, __last=0x55555564fd50)
    at /usr/include/c++/11/bits/stl_construct.h:196
#7  0x00007ffff5ffc5da in std::_Destroy<std::shared_ptr<onnxruntime::IExecutionProviderFactory>*, std::shared_ptr<onnxruntime::IExecutionProviderFactory> > (__first=0x55555564fd30, __last=0x55555564fd50) at /usr/include/c++/11/bits/alloc_traits.h:848
#8  0x00007ffff5ffbbd7 in std::vector<std::shared_ptr<onnxruntime::IExecutionProviderFactory>, std::allocator<std::shared_ptr<onnxruntime::IExecutionProviderFactory> > >::~vector (this=0x555555652630, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/stl_vector.h:680
#9  0x00007ffff5ffa1b4 in OrtSessionOptions::~OrtSessionOptions (this=0x555555652400, __in_chrg=<optimized out>)
    at /build/onnxruntime-src/onnxruntime/core/session/abi_session_options.cc:16
#10 0x00007ffff5ffaaf9 in OrtApis::ReleaseSessionOptions (ptr=0x555555652400) at /build/onnxruntime-src/onnxruntime/core/session/abi_session_options.cc:70
#11 0x0000555555556dce in Ort::detail::OrtRelease(OrtSessionOptions*) ()
#12 0x0000555555557df9 in Ort::detail::Base<OrtSessionOptions>::~Base() ()
#13 0x0000555555556ed0 in Ort::detail::ConstSessionOptionsImpl<OrtSessionOptions>::~ConstSessionOptionsImpl() ()
#14 0x0000555555556f10 in Ort::detail::SessionOptionsImpl<OrtSessionOptions>::~SessionOptionsImpl() ()
#15 0x0000555555557878 in Ort::SessionOptions::~SessionOptions() ()
#16 0x00005555555569f1 in main ()
(gdb) 
```
```

### To reproduce

Run with provided sample C++ application.

### Urgency

_No response_

### Platform

Linux

### OS Version

ubuntu 22.04.3 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.16.3

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU, oneDNN

### Execution Provider Library Version

_No response_

**Comment by snnn** [comment]
Please move the  line 
```
    Ort::Env env;
```
to the top of the main function. That object needs be created before using any other ONNX Runtime APIs.

**Comment by comphilip** [comment]
@snnn thanks, it works.
