### ISSUE TITLE
C++ shared library built with onnxruntime cannot be loaded in Python with ctypes.

### ISSUE THREAD

**Issue by chaihahaha** [microsoft/onnxruntime#18773]
### Describe the issue

A C++ shared library which included the `onnxruntime_c_api.h` and called `OrtGetApiBase()->GetApi(ORT_API_VERSION)` cannot be loaded in Python with ctypes.

### To reproduce

This is the C++ source code of `mylib.cpp` :
```cpp
// mylib.cpp
#include "onnxruntime_c_api.h"

extern "C"  __declspec(dllexport) void hello_ort()
{
    const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);
    return;
}
```
This is the `CMakeLists.txt` to build it:
```cmake
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

cmake_minimum_required(VERSION 3.13)

# Project
project(MYLIB C CXX)
string(APPEND CMAKE_CXX_FLAGS " /W4")

if (CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(STATUS "64 bit")
    set(is_x64 TRUE)
endif()

if (CMAKE_SIZEOF_VOID_P EQUAL 4)
    message(STATUS "32 bit")
    set(is_x64 FALSE)
endif()


if(NOT ONNXRUNTIME_ROOTDIR)
    if (is_x64)
        set(ONNXRUNTIME_ROOTDIR "D:/libs/onnxruntime-win-x64-1.16.2")
    endif()
    if (NOT is_x64)
        set(ONNXRUNTIME_ROOTDIR "D:/libs/onnxruntime-win-x86-1.16.2")
    endif()
endif()

include_directories("${ONNXRUNTIME_ROOTDIR}/include" "${ONNXRUNTIME_ROOTDIR}/include/onnxruntime/core/session")

link_directories("${ONNXRUNTIME_ROOTDIR}/lib")

add_library(mylib SHARED "mylib.cpp")

target_link_libraries(mylib PRIVATE onnxruntime)

target_compile_features(mylib PRIVATE cxx_std_17)

#In onnxruntime deafault install path, the required dlls are in lib and bin folders
set(DLL_DIRS "${ONNXRUNTIME_ROOTDIR}/lib;${ONNXRUNTIME_ROOTDIR}/bin")

foreach(DLL_DIR IN LISTS DLL_DIRS)
  file(GLOB ALL_DLLS ${DLL_DIR}/*.dll)
  foreach(ORTDll IN LISTS ALL_DLLS)
    add_custom_command(TARGET mylib POST_BUILD 
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${ORTDll}"              
                $<TARGET_FILE_DIR:mylib>)
  endforeach()
endforeach()
```
Then build with the following command:
```cmd
@echo off
set VS_DEV_CMD="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
set ARCH="amd64"
call %VS_DEV_CMD% -arch=%ARCH%
cd /d %~dp0
mkdir build
cd build
cmake ..
cmake --build . --config Release
xcopy Release\* ..\
pause
```
And load the `mylib.dll` with Python ctypes:
```python
import ctypes
mylib=ctypes.CDLL("mylib.dll")
```
Finally, this error shows up:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\miniconda3\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

### Platform

Windows

### OS Version

Win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.2

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by chaihahaha** [comment]
It seems to be caused by the newest version of Visual Studio compiler. When compiled with compiler ver: 19.33.31630 there is no such issue.

**Comment by chaihahaha** [comment]
Solved after compiling onnxruntime with newest msvc.
