### ISSUE TITLE
ai.onnxruntime.OrtException: Unsupported type - FLOAT16

### ISSUE THREAD

**Issue by JiangWork** [microsoft/onnxruntime#18926]
When upgrade onnxruntime version to 1.16.x, if the onnx output type is float16, it will throw following exception:

```java
Caused by: ai.onnxruntime.OrtException: Unsupported type - FLOAT16
	at ai.onnxruntime.TensorInfo.makeCarrier(TensorInfo.java:288)
	at ai.onnxruntime.OnnxTensor.getValue(OnnxTensor.java:86)
```
<img width="988" alt="image" src="https://github.com/microsoft/onnxruntime/assets/19265485/43627457-91e8-43ad-9a10-f8b4f0bfc291">

Seems it misses FLOAT16 case here:
https://github.com/microsoft/onnxruntime/blob/main/java/src/main/java/ai/onnxruntime/TensorInfo.java#L311

Related PR: https://github.com/microsoft/onnxruntime/pull/16703

**Comment by Craigacp** [comment]
Don't use `getValue` for FP16, use [getShortBuffer](https://github.com/microsoft/onnxruntime/blob/main/java/src/main/java/ai/onnxruntime/OnnxTensor.java#L232) then either work with it as shorts or use the `Fp16Conversions` utilities to convert it to floats.

It's note in the PR that FP16 is currently unsupported for that method.

**Comment by Craigacp** [comment]
Ahh. So if you were already using this then you were happy with it returning `float` arrays for fp16 values? I'd forgot that that used to work and it got lost in the refactor. I'll put that back in with a test to catch it.

**Comment by JiangWork** [comment]
Thanks for replying. When i used old runtime version, it will return float for float16.  I will try this new API.

**Comment by Craigacp** [comment]
I've put up a PR to fix the problem - https://github.com/microsoft/onnxruntime/pull/18937.
