### ISSUE TITLE
[Build] Error when building a nujet package with OpenVINO and DML

### ISSUE THREAD

**Issue by xeeetu** [microsoft/onnxruntime#19031]
### Describe the issue

I decided to build the nuget package since it collects libraries and headers in one place, it's very convenient. You will help me a lot if you can tell me how to fix the error, or tell me what dependencies to write in my project after building the library without the --build nuget option.

### Urgency

As soon is possible

### Target platform

Windows 10

### Build script

.\build.bat --config Release --parallel --skip_tests --cmake_generator "Visual Studio 17 2022" --use_openvino AUTO:GPU,CPU --use_dml --build_nuget

### Error / output

  onnxruntime_test_all.vcxproj -> D:\onnxruntime\build\Windows\Release\Release\onnxruntime_test_all.exe
  Building Custom Rule D:/onnxruntime/cmake/CMakeLists.txt
2024-01-05 20:28:08,330 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-01-05 20:28:08,331 util.run [INFO] - Running subprocess in 'D:\onnxruntime\csharp'
  dotnet restore OnnxRuntime.DesktopOnly.CSharp.sln --configfile NuGet.CSharp.config
  Determining projects to restore...
  Restored D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp\Microsoft.M
  L.OnnxRuntime.InferenceSample.NetCoreApp.csproj (in 1.24 sec).
  Restored D:\onnxruntime\csharp\tools\Microsoft.ML.OnnxRuntime.PerfTool\Microsoft.ML.OnnxRuntime.PerfTool.csproj (in 1
  .24 sec).
  Restored D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample\Microsoft.ML.OnnxRunti
  me.InferenceSample.csproj (in 1.5 sec).
  Restored D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj (in 1.52 sec).
  Restored D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.InferenceSample.Forms\Microsoft.ML.Onn
  xRuntime.InferenceSample.Forms.csproj (in 1.52 sec).
  Restored D:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Common\Microsoft.ML.OnnxRuntime.Tests.Common.cspro
  j (in 1.53 sec).
  Restored D:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\Microsoft.ML.OnnxRuntime.Tests.NetCoreA
  pp.csproj (in 1.53 sec).
2024-01-05 20:28:12,254 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-01-05 20:28:12,254 util.run [INFO] - Running subprocess in 'D:\onnxruntime\csharp'
  dotnet msbuild OnnxRuntime.DesktopOnly.CSharp.sln '/p:Configuration="Release"' '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"' '/p:IsLinuxBuild="false"' '/p:OnnxRuntimeBuildDirectory="D:\onnxruntime\build\Windows"' '/p:TrainingEnabledNativeBuild="false"'
MSBuild version 17.5.1+f6fdcf537 for .NET
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=netstandard2.0]
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\Release\netstandard2.0\Microsoft.M
  L.OnnxRuntime.dll
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=netcoreapp3.1]
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\Release\netcoreapp3.1\Microsoft.ML
  .OnnxRuntime.dll
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=net6.0]
  Microsoft.ML.OnnxRuntime.InferenceSample -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.Inf
  erenceSample\bin\Release\netstandard2.0\Microsoft.ML.OnnxRuntime.InferenceSample.dll
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\Release\net6.0\Microsoft.ML.OnnxRu
  ntime.dll
C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3030: Could not copy the
file "D:\onnxruntime\build\Windows\Release\Release\onnxruntime.pdb" because it was not found. [D:\onnxruntime\csharp\te
st\Microsoft.ML.OnnxRuntime.Tests.Common\Microsoft.ML.OnnxRuntime.Tests.Common.csproj::TargetFramework=netstandard2.0]
  Microsoft.ML.OnnxRuntime.InferenceSample.Forms -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRunti
  me.InferenceSample.Forms\bin\Release\netstandard2.0\Microsoft.ML.OnnxRuntime.InferenceSample.Forms.dll
  Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.Onnx
  Runtime.InferenceSample.NetCoreApp\bin\Release\netcoreapp3.1\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp.dll
  Microsoft.ML.OnnxRuntime.PerfTool -> D:\onnxruntime\csharp\tools\Microsoft.ML.OnnxRuntime.PerfTool\bin\Release\netcor
  eapp3.1\Microsoft.ML.OnnxRuntime.PerfTool.dll
C:\Program Files\dotnet\sdk\7.0.203\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3030: Could not copy the
file "D:\onnxruntime\build\Windows\Release\Release\onnxruntime.pdb" because it was not found. [D:\onnxruntime\csharp\te
st\Microsoft.ML.OnnxRuntime.Tests.Common\Microsoft.ML.OnnxRuntime.Tests.Common.csproj::TargetFramework=net6.0]
Traceback (most recent call last):
  File "D:\onnxruntime\tools\ci_build\build.py", line 2685, in <module>
    sys.exit(main())
  File "D:\onnxruntime\tools\ci_build\build.py", line 2634, in main
    build_nuget_package(
  File "D:\onnxruntime\tools\ci_build\build.py", line 2129, in build_nuget_package
    run_subprocess(cmd_args, cwd=csharp_build_dir)
  File "D:\onnxruntime\tools\ci_build\build.py", line 798, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Users\xeetu\miniconda3\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dotnet', 'msbuild', 'OnnxRuntime.DesktopOnly.CSharp.sln', '/p:Configuration="Release"', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="D:\\onnxruntime\\build\\Windows"', '/p:TrainingEnabledNativeBuild="false"']' returned non-zero exit status 1.

### Visual Studio Version

2022

**Comment by xeeetu** [comment]
I change the command to; .\build.bat --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --skip_tests --cmake_generator "Visual Studio 17 2022" --use_openvino CPU_FP32 --use_dml --build_nuget
And get this output messages:
  onnxruntime_test_all.vcxproj -> D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime_test_all.exe
  Building Custom Rule D:/onnxruntime/cmake/CMakeLists.txt
  Ignoring COMPILE_WARNING_AS_ERROR target property and CMAKE_COMPILE_WARNING_AS_ERROR variable.
2024-01-07 06:03:34,892 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-01-07 06:03:34,893 util.run [INFO] - Running subprocess in 'D:\onnxruntime\csharp'
  dotnet restore OnnxRuntime.DesktopOnly.CSharp.sln --configfile NuGet.CSharp.config
  Determining projects to restore...
  All projects are up-to-date for restore.
2024-01-07 06:03:37,471 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-01-07 06:03:37,471 util.run [INFO] - Running subprocess in 'D:\onnxruntime\csharp'
  dotnet msbuild OnnxRuntime.DesktopOnly.CSharp.sln '/p:Configuration="RelWithDebInfo"' '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"' '/p:IsLinuxBuild="false"' '/p:OnnxRuntimeBuildDirectory="D:\onnxruntime\build\Windows"' '/p:TrainingEnabledNativeBuild="false"'
MSBuild version 17.5.1+f6fdcf537 for .NET
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=net6.0]
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=netcoreapp3.1]
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj::Targe
tFramework=netstandard2.0]
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\netcoreapp3.1\Micro
  soft.ML.OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\netstandard2.0\Micr
  osoft.ML.OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime -> D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\net6.0\Microsoft.ML
  .OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime.InferenceSample -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRuntime.Inf
  erenceSample\bin\Release\netstandard2.0\Microsoft.ML.OnnxRuntime.InferenceSample.dll
  Microsoft.ML.OnnxRuntime.Tests.Common -> D:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Common\bin\RelWith
  DebInfo\netstandard2.0\Microsoft.ML.OnnxRuntime.Tests.Common.dll
  Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreApp -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.Onnx
  Runtime.InferenceSample.NetCoreApp\bin\RelWithDebInfo\netcoreapp3.1\Microsoft.ML.OnnxRuntime.InferenceSample.NetCoreA
  pp.dll
  Microsoft.ML.OnnxRuntime.InferenceSample.Forms -> D:\onnxruntime\csharp\sample\InferenceSample\Microsoft.ML.OnnxRunti
  me.InferenceSample.Forms\bin\Release\netstandard2.0\Microsoft.ML.OnnxRuntime.InferenceSample.Forms.dll
  Microsoft.ML.OnnxRuntime.PerfTool -> D:\onnxruntime\csharp\tools\Microsoft.ML.OnnxRuntime.PerfTool\bin\RelWithDebInfo
  \netcoreapp3.1\Microsoft.ML.OnnxRuntime.PerfTool.dll
  Microsoft.ML.OnnxRuntime.Tests.Common -> D:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Common\bin\RelWith
  DebInfo\net6.0\Microsoft.ML.OnnxRuntime.Tests.Common.dll
  Microsoft.ML.OnnxRuntime.Tests.NetCoreApp -> D:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\bin
  \RelWithDebInfo\net6.0\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp.dll
2024-01-07 06:03:55,444 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-01-07 06:03:55,445 util.run [INFO] - Running subprocess in 'D:\onnxruntime\csharp'
  dotnet msbuild OnnxRuntime.CSharp.proj /t:CreatePackage '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"' '/p:Configuration="RelWithDebInfo"' '/p:ExecutionProvider="openvino"' '/p:IsLinuxBuild="false"' '/p:OnnxRuntimeBuildDirectory="D:\onnxruntime\build\Windows"' '/p:NugetExe="nuget.exe"'
MSBuild version 17.5.1+f6fdcf537 for .NET
  e7a0495a87
  e7a0495a874251e9747b2ce0683e0580282c54df
  PackageVersion=1.16.0-dev-20240107-0303-e7a0495a87
  Bundling managed assemblies into a NuGet package ...
C:\Users\xeetu\.nuget\packages\microsoft.build.tasks.git\1.0.0\build\Microsoft.Build.Tasks.Git.targets(24,5): warning :
 Could not find a part of the path 'D:\onnxruntime\cmake\external\onnxruntime-extensions\.git'. The source code won't b
e available via Source Link. [D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj]
  Successfully created package 'D:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\Microsoft.ML.Onnx
  Runtime.Managed.1.16.0-dev-20240107-0303-e7a0495a87.nupkg'.
  Generating nuspec for the native Nuget package ...
  Traceback (most recent call last):
    File "D:\onnxruntime\tools\nuget\generate_nuspec_for_native_nuget.py", line 1190, in <module>
      sys.exit(main())
    File "D:\onnxruntime\tools\nuget\generate_nuspec_for_native_nuget.py", line 1178, in main
      lines = generate_nuspec(args)
    File "D:\onnxruntime\tools\nuget\generate_nuspec_for_native_nuget.py", line 1129, in generate_nuspec
      generate_files(lines, args)
    File "D:\onnxruntime\tools\nuget\generate_nuspec_for_native_nuget.py", line 721, in generate_files
      for ngraph_element in os.listdir(ngraph_list_path):
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Intel\\openvino_
  2023.1.0\\deployment_tools\\ngraph\\lib\\'
D:\onnxruntime\csharp\OnnxRuntime.CSharp.proj(95,5): error MSB3073: The command "python ..\tools\nuget\generate_nuspec_
for_native_nuget.py --package_version 1.16.0-dev-20240107-0303-e7a0495a87 --package_name Microsoft.ML.OnnxRuntime.OpenV
ino --target_architecture x64 --build_config RelWithDebInfo --native_build_path D:\onnxruntime\build\Windows\RelWithDeb
Info\RelWithDebInfo --packages_path D:\onnxruntime\build\Windows\packages --ort_build_path D:\onnxruntime\build\Windows
 --sources_path D:\onnxruntime --commit_id e7a0495a874251e9747b2ce0683e0580282c54df --is_release_build false --executio
n_provider openvino" exited with code 1.
Traceback (most recent call last):
  File "D:\onnxruntime\tools\ci_build\build.py", line 2685, in <module>
    sys.exit(main())
  File "D:\onnxruntime\tools\ci_build\build.py", line 2634, in main
    build_nuget_package(
  File "D:\onnxruntime\tools\ci_build\build.py", line 2171, in build_nuget_package
    run_subprocess(cmd_args, cwd=csharp_build_dir)
  File "D:\onnxruntime\tools\ci_build\build.py", line 798, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "C:\Users\xeetu\miniconda3\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dotnet', 'msbuild', 'OnnxRuntime.CSharp.proj', '/t:CreatePackage', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"', '/p:Configuration="RelWithDebInfo"', '/p:ExecutionProvider="openvino"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="D:\\onnxruntime\\build\\Windows"', '/p:NugetExe="nuget.exe"']' returned non-zero exit status 1.
