### ISSUE TITLE
RunAsync C# API crashes without any error

### ISSUE THREAD

**Issue by vishnu-ms** [microsoft/onnxruntime#19140]
### Describe the issue

I'm running Onnx runtime 1.16.3 in a .NET Core web application. 
I'm able to run the model and get outputs when using session.Run() but want to be able to run the model async and evaluate any possible performance benefits. 
However, the application crashes without any exception when just RunAsync calls, but returns a result when `session.Run(options, inputValues, session.OutputNames)` is called before "session.RunAsync". 

This occurs both in a Linux container app and in local Docker container test (Linux using default CPU as ORT provider)

Can someone help resolve this issue? 

### To reproduce

Here's the C# code, can share ONNX file if needed

```
public async Task<double> RunInference(InferenceSession session, List<float> inputs)
{
    using RunOptions options = new RunOptions();
    using var inputOrt = OrtValue.CreateTensorValueFromMemory<float>(OrtMemoryInfo.DefaultInstance, inputs.ToArray(), [1, 30]);

    var outputOrtKey = OrtValue.CreateAllocatedTensorValue(OrtAllocator.DefaultInstance, TensorElementType.Int64, [1]);
    var outputOrtValue = OrtValue.CreateAllocatedTensorValue(OrtAllocator.DefaultInstance, TensorElementType.Float, [1]);

    using var ortMap = OrtValue.CreateMap(ref outputOrtKey, ref outputOrtValue);

    var inputOrtValues = new List<OrtValue> { inputOrt };

    var outputOrtValues = new List<OrtValue>
    {
        OrtValue.CreateAllocatedTensorValue(OrtAllocator.DefaultInstance, TensorElementType.Int64, [1]),
        OrtValue.CreateSequence(new List<OrtValue> { ortMap })
    };

    var inputValues = new Dictionary<string, OrtValue>
    {
        { session.InputNames[0], inputOrt }
    };

    // Works when line below is uncommented
    // var temp = session.Run(options, inputValues, session.OutputNames);
    var task = session.RunAsync(options, session.InputNames, inputOrtValues, session.OutputNames, outputOrtValues);

    var outputs2 = await task;

    var lastOutput = outputs2.Last();

    using var firstMap = lastOutput.GetValue(0, OrtAllocator.DefaultInstance);

    var inferenceMap = new Dictionary<long, double>();

    firstMap.ProcessMap((k, v) =>
    {
        var keySpan = k.GetTensorDataAsSpan<long>().ToArray();
        var valuesSpan = v.GetTensorDataAsSpan<float>().ToArray();
        var entryCount = (int)k.GetTensorTypeAndShape().ElementCount;

        for (int i = 0; i < entryCount; i++)
        {
            inferenceMap.Add(keySpan[i], valuesSpan[i]);
        }

    }, OrtAllocator.DefaultInstance);

    return inferenceMap.Aggregate((x, y) => x.Value > y.Value ? x : y).Key;
}
```

### Urgency

Not able to proceed

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### Execution Provider

Other / Unknown

**Comment by vishnu-ms** [comment]
UPDATE: When running session.Run and session.RunAsync back to back in same block of code, the web app crashes exactly in 2 requests: 
![image](https://github.com/microsoft/onnxruntime/assets/103695931/71795fcd-5fbd-4422-89d0-5239afd36f0e)
![image](https://github.com/microsoft/onnxruntime/assets/103695931/cf0b1d2c-aa38-4395-bcd4-74b5c51dbd1e)

@RandySheriff @pranavsharma can you pls help with this?

**Comment by pranavsharma** [comment]
Just spoke to @vishnu-ms. While there _might_ be issues with RunAsync C# API (which is why I'll just keep this open), Vishnu's use case doesn't require using RunAsync. I explained to him on the call and he'll report back.

**Comment by GeorgeS2019** [comment]
Add ![image](https://github.com/microsoft/onnxruntime/assets/49812372/9d543550-7570-4fe4-b191-bd0db912e7fa)

**Comment by fs-eire** [comment]
removed 'platform:web' tag, which is used for client-end (JS) app, not for server app.

**Comment by mario-dg** [comment]
Any updates on this?

**Comment by tjwald** [comment]
I am experiencing that RunAsync is not Thread safe - crashing on random issues, while using the async over sync approach does work.

If you remove the semaphore in [this](https://github.com/tjwald/high-perf-ML/blob/develop/ML.Infra/ModelExecutors/Onnx/AsyncOnnxModelExecutor.cs) class, then it crashes randomly, making the only option for achieving 100% GPU utilization to [use](https://github.com/tjwald/high-perf-ML/blob/develop/ML.Infra/ModelExecutors/Onnx/OnnxModelExecutor.cs):

```csharp
 IDisposableReadOnlyCollection<OrtValue> result = await Task.Run(
          () => Session.Run(RunOptions, Session.InputNames, ortValues, Session.OutputNames)).ConfigureAwait(false);
```

Causing overhead and reducing my requests per minute.

**Comment by RockNHawk** [comment]
I'm encountering the same issue, the `InferenceSession.Run` works well, but  `InferenceSession.RunAsync` usually crash with AccessViolationException. 

and the critical CallStask is the `OrtCallback`.

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.Tasks.Task.NotifyParentIfPotentiallyAttachedTask()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at Microsoft.ML.OnnxRuntime.InferenceSession+<RunAsync>d__75.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskCompletionSource`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(System.__Canon)
   at Microsoft.ML.OnnxRuntime.InferenceSession+<>c__DisplayClass75_0.<RunAsync>b__0(System.Collections.Generic.IReadOnlyCollection`1<Microsoft.ML.OnnxRuntime.OrtValue>, IntPtr)
   at Microsoft.ML.OnnxRuntime.InferenceSession.OrtCallback(IntPtr, IntPtr[], UInt32, IntPtr)

**Comment by tjwald** [comment]
Can we get any indication of of this bug will be addressed in any upcoming release?
This effects multiple EPs (GPU, DirectML, ...) and prevents using the async api which does reduce the overhead in many scenarios.

Maybe @luisquintanilla can you assist?

**Comment by RockNHawk** [comment]
Any updates on this?

**Comment by tjwald** [comment]
Hi, this is not stale and is still causing performance and scaling issues across different Exection providers.
Again, there is some race condition that is causing RunAsync to be unsafe for use in concurrent requests.
Please at least comment on this thread whether this is a known issue, a lower priority, higher priority, will be addressed in a future release, recommended workaround etc.

**Comment by RockNHawk** [comment]
this is not stale. ` InferenceSession.RunAsync` can not call concurrently (may crash with AccessViolationException.) but ` InferenceSession.Run` works well.
