### ISSUE TITLE
[Feature Request] Windows ARM64 native wheels

### ISSUE THREAD

**Issue by khmyznikov** [microsoft/onnxruntime#19161]
### Describe the feature request

- [ ] Add windows arm64 platform target for [python](https://pypi.org/project/onnxruntime/)
- [ ] QNN version as well

### Describe scenario use case

The capability of use Windows ARM as main machine for ML development, not only as inference target.

**Comment by jywu-msft** [comment]
this is in the works.

**Comment by snnn** [comment]
Github now provides Windows ARM64 bits: https://github.com/actions/python-versions/pull/291
Previously it was our main blocker.

**Comment by khmyznikov** [comment]
@jywu-msft @snnn since the runners [available for free](https://blogs.windows.com/windowsdeveloper/2025/04/14/github-actions-now-supports-windows-on-arm-runners-for-all-public-repos/), which roadblocks we still have to get the unified package win/win-arm as we have for apple?

**Comment by armwaheed** [comment]
Thanks @adrianlizarraga and @khmyznikov for working on this feature.

When I try to use [ONNX 1.19](https://pypi.org/project/onnx/#files) for Windows on Arm (`win_arm64`), I get the below error:
```
(onnx-arm) PS C:\Users\waheedbrown> python
Python 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:37:22) [MSC v.1942 64 bit (ARM64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\waheedbrown\%USERPROFILE%\venvs\onnx-arm\Lib\site-packages\onnx\__init__.py", line 83, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: The specified module could not be found.
```

May you please comment, when you have a chance?

**Comment by snnn** [comment]
I will work on it after the 1.23.0 release is done.

**Comment by MGN-GIT** [comment]
> When I try to use [ONNX 1.19](https://pypi.org/project/onnx/#files) for Windows on Arm (`win_arm64`), I get the below error:
> 
> ```
> (onnx-arm) PS C:\Users\waheedbrown> python
> Python 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:37:22) [MSC v.1942 64 bit (ARM64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import onnx
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\waheedbrown\%USERPROFILE%\venvs\onnx-arm\Lib\site-packages\onnx\__init__.py", line 83, in <module>
>     from onnx.onnx_cpp2py_export import ONNX_ML
> ImportError: DLL load failed while importing onnx_cpp2py_export: The specified module could not be found.
> ```
> 
> May you please comment, when you have a chance?

Generally, "DLL load failed" occurs in a python package when it fails to load its dependent dynamic library(dll). This may be due to improper linking of dlls while repairing the wheel. Does onnx python package contains any dll for windows for primary working? It can be .pyd too

**Comment by MGN-GIT** [comment]
@armwaheed I don't see any issue in my local Windows ARM64 setup, it is working fine for me:
```

c:\>python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 10:17:29) [MSC v.1941 64 bit (ARM64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> print(onnx.__version__)
1.19.0

```

**Comment by armwaheed** [comment]
Thanks @Greenie0701 for checking this. I'll try again on a fresh Windows on Arm VM. Perhaps I was missing a dependency(?)

> Does onnx python package contains any dll for windows for primary working?

I'm not sure and here's what I found from some quick investigation:

The onnx Python package does ship with a compiled native extension on Windows, and that extension depends on DLLs:
* Inside the installed package (Lib\site-packages\onnx), you’ll find a file like:
   ```
   onnx_cpp2py_export.pyd
   ```
* This .pyd itself depends on Microsoft’s runtime DLLs (e.g., vcruntime140.dll, msvcp140.dll, ucrtbase.dll)
* It requires external VC++ runtime DLLs that should already be installed
