### ISSUE TITLE
[Build] Build of onnxruntime in Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by shintaro-matsui** [microsoft/onnxruntime#19346]
### Describe the issue

I am trying to build onnxruntime from source, but it fails with an error.

My environment.
- Ubuntu 20.04
- CUDA 11.8
- cmake: 3.28.1
- onnxruntime: v1.16.3

### Urgency

Not urgent.

### Target platform

Ubnutu 20.04

### Build script

./build.sh --config Release --build_shared_lib --skip_tests --parallel

### Error / output

Just the last part of the error.

```
[ 59%] Building CXX object CMakeFiles/onnxruntime_session.dir/home/mz/repository/onnxruntime/onnxruntime/core/session/provider_registration.cc.o
/usr/bin/ld: /usr/local/lib/libcpuinfo.a(api.c.o): in function `cpuinfo_log_fatal.constprop.0':
api.c:(.text+0xa5): undefined reference to `clog_vlog_fatal'
/usr/bin/ld: /usr/local/lib/libcpuinfo.a(init.c.o): in function `cpuinfo_log_error':
init.c:(.text+0xa2): undefined reference to `clog_vlog_error'
/usr/bin/ld: /usr/local/lib/libcpuinfo.a(processors.c.o): in function `cpuinfo_log_error':
processors.c:(.text+0x122): undefined reference to `clog_vlog_error'
/usr/bin/ld: /usr/local/lib/libcpuinfo.a(smallfile.c.o): in function `cpuinfo_log_error.constprop.0':
smallfile.c:(.text+0xa3): undefined reference to `clog_vlog_error'
/usr/bin/ld: onnxruntime_mlas_test: internal symbol `clog_vlog_fatal' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnxruntime_mlas_test.dir/build.make:518: onnxruntime_mlas_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:2563: CMakeFiles/onnxruntime_mlas_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 59%] Building CXX object CMakeFiles/onnxruntime_session.dir/home/mz/repository/onnxruntime/onnxruntime/core/session/standalone_op_invoker.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/identity_elimination.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/initializer.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/insert_cast_transformer.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/isinf_reducesum_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/layer_norm_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/layout_transformation/layout_transformation.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/matmul_activation_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/matmul_add_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/matmul_integer_to_float.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/matmul_scale_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/matmul_transpose_fusion.cc.o
[ 59%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/nchwc_transformer.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/nhwc_transformer.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/noop_elimination.cc.o
[ 60%] Linking CXX static library libonnxruntime_framework.a
[ 60%] Built target onnxruntime_framework
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/not_where_fusion.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/optimizer_execution_frame.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/pre_shape_node_elimination.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/propagate_cast_ops.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/avx2_weight_s8_to_u8.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/clip_quantizelinear.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/ensure_unique_dq_for_node_unit.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/qdq_final_cleanup.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/qdq_propagation.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/qdq_s8_to_u8.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/qdq_util.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/relu_quantizelinear.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/s8_to_u8.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/selectors_actions/qdq_actions.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/selectors_actions/qdq_selector_action_transformer.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/selectors_actions/qdq_selectors.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/qdq_transformer/selectors_actions/shared/utils.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/quick_gelu_fusion.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/relu_clip_fusion.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/reshape_fusion.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/rocm_blas_alt_impl.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/rule_based_graph_transformer.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/selectors_actions/actions.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/selectors_actions/helpers.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/selectors_actions/selector_action_transformer.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/skip_layer_norm_fusion.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/slice_elimination.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/transpose_optimization/onnx_transpose_optimization.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/transpose_optimization/ort_optimizer_api_impl.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/transpose_optimization/ort_transpose_optimization.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/transpose_optimizer.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/unsqueeze_elimination.cc.o
[ 62%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/mz/repository/onnxruntime/onnxruntime/core/optimizer/utils.cc.o
[ 62%] Linking CXX static library libonnxruntime_session.a
[ 62%] Built target onnxruntime_session
[ 62%] Linking CXX static library libonnx.a
[ 62%] Built target onnx
[ 62%] Linking CXX static library libonnxruntime_optimizer.a
[ 62%] Built target onnxruntime_optimizer
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/mz/repository/onnxruntime/tools/ci_build/build.py", line 2684, in <module>
    sys.exit(main())
  File "/home/mz/repository/onnxruntime/tools/ci_build/build.py", line 2577, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/mz/repository/onnxruntime/tools/ci_build/build.py", line 1487, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/mz/repository/onnxruntime/tools/ci_build/build.py", line 798, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/mz/repository/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/mz/repository/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j24']' returned non-zero exit status 2.
```

### GCC / Compiler Version

The CXX compiler identification is GNU 9.4.0

**Comment by snnn** [comment]
Your system installed version of CPUINFO(/usr/local/lib/libcpuinfo.a) isn't compatible with the ONNX Runtime source code you are compiling.  Please try to uninstall the file, or do the build in a clean docker environment.
