### ISSUE TITLE
failed:Node (/pool_1/MaxPool) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size

### ISSUE THREAD

**Issue by Tian14267** [microsoft/onnxruntime#19349]
### Describe the issue

I covert my torch model to onnx, **it is ok**.  Then I use my onnx model with 
`onnx_model=onnxruntime.InferenceSession("model.onnx")`
and  it is error :
```
Traceback (most recent call last):
  File "inference_emotion.py", line 844, in <module>
    main_batch()
  File "inference_emotion.py", line 753, in main_batch
    LM = LoadOnnxModel()
  File "inference_emotion.py", line 563, in __init__
    self.onnx_model = onnxruntime.InferenceSession("model.onnx")
  File "/root/anaconda3/envs/emotion/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/anaconda3/envs/emotion/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./saved_models/emotion_roberta_base/model.onnx failed:Node (/pool_1/MaxPool) Op (MaxPool) [ShapeInferenceError] Attribute strides has incorrect size
```

so ,What happen to onnxruntime ? I don't why because i covert to onnx is OK. 

my **torch version**: 1.13.1
**onnxruntime**  : 1.16.3
**onnx**  ： 1.15.0，
**python**：3.8.18

### To reproduce

What the error in torch  code is like this:
![image](https://github.com/microsoft/onnxruntime/assets/27938135/03c57be0-77c2-4634-ba4a-0dc6b4bde936)

### Platform

Linux

### OS Version

centos 7

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

 1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6

**Comment by yufenglee** [comment]
Are you applying a 2D MaxPool on a 1D(N,C,L) shape? Did you run the model checker like this https://github.com/onnx/onnx/blob/main/onnx/examples/check_model.ipynb after exporting? You may share the onnx file for further investigation.

**Comment by Tian14267** [comment]
> Are you applying a 2D MaxPool on a 1D(N,C,L) shape? Did you run the model checker like this https://github.com/onnx/onnx/blob/main/onnx/examples/check_model.ipynb after exporting? You may share the onnx file for further investigation.

Thank you . And I check model with `check_model.ipynb`  and it's OK.  And my input shape in pool is (N, C, L),  and  I change  2D MaxPool  to 1D MaxPool, but it's also same error. 

![image](https://github.com/microsoft/onnxruntime/assets/27938135/c84d7050-e507-4815-b102-53c52d6a3c7b)

**I upload my onnx model in here** :
链接：https://pan.baidu.com/s/1cYuC7TjmC2r4_Znwztg3zQ 
提取码：cf2s 
--来自百度网盘超级会员V1的分享
