### ISSUE TITLE
Model cannot be used because the inference status is rejected

### ISSUE THREAD

**Issue by orhan-akarsu** [microsoft/onnxruntime#19624]
### Describe the issue

I have the yolov8 nano onnx model. I want to use this model on the web. I made the necessary improvements regarding this. It works as desired on the web with React. It does not work in the Cromium-based React Windows application.

![image](https://github.com/microsoft/onnxruntime/assets/113893868/c21fdf42-784e-43ed-90ad-ec3f3f16c267)
As you can see I am using this code. This way it works correctly in the browser. But in windows applitaction : 
![image](https://github.com/microsoft/onnxruntime/assets/113893868/1a9b5337-0a27-45fa-87c4-aed88df18926)

In this way, the model cannot be loaded successfully because the status is rejected.  When I look at the network through the Windows application, it does not download the necessary WASM file.

Upgrading the onnxweb version used from 1.14 to 1.17 did not solve the problem. No matter what I do the problem persists.

### To reproduce

-

### Urgency

I need to deliver the project within 1 week. I'm already past the deadline.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by skottmckay** [comment]
Isn't the 'create' method part of InferenceSessionFactory not InferenceSession?

https://github.com/microsoft/onnxruntime/blob/c12a20bef95df5437189687b94e7ba2f1bad1505/js/common/lib/inference-session.ts#L415-L458

**Comment by orhan-akarsu** [comment]
@skottmckay The usage patterns are the same, but I didn't see any inheritance. When I look at the avg.min.js file using the https://sokra.github.io/source-map-visualization/ tool:
![image](https://github.com/microsoft/onnxruntime/assets/113893868/51d76bb7-5e4e-4409-8abb-f79cde238866)
I don't see any inheritance.

**Comment by skottmckay** [comment]
Not following what you mean by the 'usage patterns' are the same. I'm not an expert on the JS API but I don't see a `create` method on the InferenceSession class so your code seems wrong. i.e. the error is not that it can't load the model it's that you're calling something that doesn't exist AFAICS. Same as if you called `Inference.doMagic(...)` to load the model, unless something adds a `create` method to InferenceSession outside of the definition of that class (maybe that's possible in JS).

What happens if you change `InferenceSession.create` to `InferenceSessionFactory.create`?

https://github.com/microsoft/onnxruntime/blob/c12a20bef95df5437189687b94e7ba2f1bad1505/js/common/lib/inference-session.ts#L341-L413

**Comment by orhan-akarsu** [comment]
@skottmckay When I used InferenceSession, it was working on the web, but not in the React Windows application.
Web: 
![image](https://github.com/microsoft/onnxruntime/assets/113893868/d7d473d7-bfde-44f7-a062-a1c9754022b4)
buf if use InferenceSessionFactory : 
![image](https://github.com/microsoft/onnxruntime/assets/113893868/81fe9fa5-1278-4b32-8dfd-8727b7003a38)

**Comment by skottmckay** [comment]
@fs-eire might be able to help

**Comment by orhan-akarsu** [comment]
@skottmckay
Error: no available backend found. ERR: [cpu] TypeError: v.dirname is not a function
    at Ln (backend-impl.ts:101:9)
    at async a.create (inference-session-impl.ts:201:21)
    at async Crate.__loadModels (crate2.js?v1708949341097:71:17)
    at async Crate.initialize (crate2.js?v1708949341097:49:7)
    at async mainService (workerNiz.js?v${timestamp}:25:7)


I encountered this as an error when I did not use the Promise structure.

**Comment by fs-eire** [comment]
I think the usage of Promise has no problem. I need more information (error messages or stacktrace or whatever) to know why it does not work on windows app. just knowing that a Promise is rejected does not give me enough info to understand the root cause.
