### ISSUE TITLE
[Build] Onnxruntime 1.6.0 Not pip installing

### ISSUE THREAD

**Issue by HShamimGEHC** [microsoft/onnxruntime#19633]
### Describe the issue

I am able to install newer version of ONNXruntime from the jetson zoo website:

However I am struggling with onnxruntime 1.6.0

### Urgency

Urgent

### Target platform

NVIDIA Jetson AGX Xavier

### Build script

nvidia@ubuntu:~$ wget https://nvidia.box.com/s/0hn1biilqnhii8dx6ojatdgjbd30ni0i -O onnxruntime_gpu-1.6.0-cp38-cp38-linux_aarch64.whl

nvidia@ubuntu:~$ pip3 install onnxruntime_gpu-1.6.0-cp38-cp38-linux_aarch64.whl

### Error / output

nvidia@ubuntu:~$ pip3 install onnxruntime_gpu-1.6.0-cp38-cp38-linux_aarch64.whl
Processing ./onnxruntime_gpu-1.6.0-cp38-cp38-linux_aarch64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    local_path = unpack_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 249, in unpack_file
    unzip_file(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by tianleiwu** [comment]
Please do not use wget for that URL since the content is HTML.

In Windows, I can use Chrome browser to open the page https://nvidia.box.com/s/0hn1biilqnhii8dx6ojatdgjbd30ni0i, and click "Download" button to download the wheel. It is a good zip file.

You may try wget on other version with URL that ends with `.whl` listed in https://elinux.org/Jetson_Zoo#ONNX_Runtime

**Comment by HShamimGEHC** [comment]
Ah yes I noticed wget works on other versions. Since I am running this from docker and need that version, what do you recommend I do?

**Comment by tianleiwu** [comment]
Try upload the wheel to some cloud storage, and use wget to download. Or just save the wheel to local directory, and use `-v` to map the folder during launching docker.
