### ISSUE TITLE
PyTorch model converted into onnx, getting this error : ORT_INVALID_ARGUMENT - message: Load model from ____ failed.

### ISSUE THREAD

**Issue by JBigelow02** [microsoft/onnxruntime#19700]
### Describe the issue

Hello, I am pretty new to AI models in general, so sorry if my problem is simple.

Anyway, I have this PyTorch model that i am using off of hugging face, and i have exported the model into the onnx format. I exported the file using python, and am trying to get the onnx file working in Java.

My build crashes when it comes to this line:
var session = env.createSession("\"C:\\Users\\L7400\\Desktop\\torch-model.onnx\"", new OrtSession.SessionOptions());
and i am not really sure how to proceed, as i cannot find a lot of information on this error.

### Urgency

Not super urgent, kind of at a halt in progression though.

### Target platform

Windows

### Build script

package mygroupid;
import java.util.Map;

import ai.onnxruntime.*;

public class OnnxTestCase {
    public static void main(String[] args) throws OrtException {
        System.out.println("Hello world!");

        var env = OrtEnvironment.getEnvironment();
        System.out.println("Hello world!2");
        var session = env.createSession("\"C:\\Users\\L7400\\Desktop\\torch-model.onnx\"", new OrtSession.SessionOptions());
        System.out.println("Hello world!3");

        OnnxTensor t1 = null;
        var inputs = Map.of("My name is JJ and I am going to the Mall.",t1);

        try (var results = session.run(inputs)) {
            System.out.println(results);
        }
    }
}

### Error / output

Hello world!
Hello world!2
Exception in thread "main" ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Load model from "C:\Users\L7400\Desktop\torch-model.onnx" failed:Load model "C:\Users\L7400\Desktop\torch-model.onnx" failed
        at ai.onnxruntime.OrtSession.createSession(Native Method)
        at ai.onnxruntime.OrtSession.<init>(OrtSession.java:74)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:236)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:221)
        at mygroupid.OnnxTestCase.main(OnnxTestCase.java:12)

### Visual Studio Version

1.86.2

### GCC / Compiler Version

?

**Comment by Craigacp** [comment]
You don't need to quote the string a second time, that's probably causing the filename parser in ORT to complain.

**Comment by JBigelow02** [comment]
> You don't need to quote the string a second time, that's probably causing the filename parser in ORT to complain.

I copied the filepath directly from the file properties, removing them gives errors.

**Comment by Craigacp** [comment]
What error do you get if the line is `var session = env.createSession("C:/Users/L7400/Desktop/torch-model.onnx", new OrtSession.SessionOptions());`?

**Comment by JBigelow02** [comment]
That line now works! Thank you! Unfortunately i am now getting this error code : Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at java.base/java.util.ImmutableCollections$Map1.<init>(Unknown Source)
        at java.base/java.util.Map.of(Unknown Source)
        at mygroupid.OnnxTestCase.main(OnnxTestCase.java:16)
But this error code comes after my 3rd print statement showing that your line works.

**Comment by Craigacp** [comment]
That's from the JDK itself, you can't put a null value into a `Map.of`. If you want to make a test tensor you can do `var tensor = OnnxTensor.createTensor(env, new float[5][10]);` which will make a float tensor full of zeros of size `[5,10]`.

**Comment by Craigacp** [comment]
I recommend loading the model in interactively in `jshell` which will make it easier to poke the model and inspect it without repeatedly re-running the test program.
