### ISSUE TITLE
[Web]  How should I get wasm file?

### ISSUE THREAD

**Issue by Iven10252158** [microsoft/onnxruntime#19829]
### Describe the issue

I use vue3+vite and load onnxruntime-web plugin. I meet some error. I get wasm file failed.

I wondering to know how should i get wasm file?

![截圖 2024-03-08 下午4 03 29](https://github.com/microsoft/onnxruntime/assets/68391879/8e0dbc35-6abe-4941-af95-c68601507d4f)
 
 My Vue3+Vite Version: 
 vue:"^3.4.15",
 vite: "~3.0.4",
 onnxruntime-web: "^1.17.1",
 vite-plugin-static-copy: "^1.0.1",
 
 In my vite.config.ts
 import { viteStaticCopy } from 'vite-plugin-static-copy'
 
 export default ({ mode }) => {
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }
  return defineConfig({
    base: process.env.VITE_APP_BASE_URL,
    plugins: [
      vue(),
      viteStaticCopy({
        targets: [
          {
            src: "./node_modules/onnxruntime-web/dist/*.wasm",
            dest: "./",
          },
        ],
      }),
      removeConsole(),
      }),
    ],
    css: {postcss},
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src')
      }
    },
}
 

### To reproduce

In My Vue app 
import * as ort from 'onnxruntime-web';
const modelDir = 'https://mode-marie-ai-2023.s3.ap-northeast-1.amazonaws.com/inspiration_generator/onnx/sam_onnx_quantized_vit_h.onnx'
onMounted(async () => {
  console.log('onMounted')
  try {
    if (modelDir === undefined) return
    const modelUrl:string = modelDir
   const aaa = await ort.InferenceSession.create(modelUrl)
    console.log('completed')
  } catch (error) {
    console.log(error)
  }
})

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### Execution Provider

Other / Unknown

**Comment by fs-eire** [comment]
you may need to figure out what is the actual path of .wasm files are served.

If the browser log, it tries to get the files at https://localhost:5173/admin/ort-wasm-simd.wasm, and this URL is not valid.

In your config, I see you copy the files to "./". Not sure how this will map to the actual deploy path. You need to figure out this.

Since your script tries to get the .wasm files from path "https://localhost:5173/admin/", I assume your bundle.js is in the same path. You may either figure out how to deploy the .wasm files to the same path, or use `ort.env.wasm.wasmPaths` to override the wasm paths if you know where it is.

**Comment by Mirror-Yu** [comment]
I also encountered this problem, using the onnx model, but reporting an error that wasm could not find，Have you solved it yet？

**Comment by yi-boide** [comment]
The same problem, I created a new empty project of react vite, the following loading also appeared this problem


```typescript
useEffect(() => {
    const initModel = async () => {
      try {
        env.wasm.wasmPaths = './'
        const model = await InferenceSession.create('./model/sam_onnx_quantized_example.onnx')
        console.log(model)
      } catch (e) {
        console.log(e)
      }
    }
    initModel()
  }, [])
```

**Comment by fs-eire** [comment]
Please use latest onnxruntime-web@dev version, which contains fixes for latest Vite and Nextjs

**Comment by yi-boide** [comment]
> Please use latest onnxruntime-web@dev version, which contains fixes for latest Vite and Nextjs

修复程序上生产版本了吗

**Comment by fs-eire** [comment]
> > Please use latest onnxruntime-web@dev version, which contains fixes for latest Vite and Nextjs
> 
> 修复程序上生产版本了吗

Please try 1.22

**Comment by yi-boide** [comment]
我之前使用的是1.20.0版本的，直接升级到1.22不兼容



---Original---
From: "Yulong ***@***.***&gt;
Date: Tue, Jun 10, 2025 04:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/onnxruntime] [Web]  How should I get wasm file? (Issue#19829)


fs-eire left a comment (microsoft/onnxruntime#19829)
   
Please use latest ***@***.*** version, which contains fixes for latest Vite and Nextjs
  
修复程序上生产版本了吗
  
Please try 1.22

**Comment by fs-eire** [comment]
> 我之前使用的是1.20.0版本的，直接升级到1.22不兼容
> […](#)

请问具体是哪里不兼容呢？建议提一个新的 issue，提供更多细节和错误信息，最好能有复现的步骤。

**Comment by yi-boide** [comment]
> > 我之前使用的是1.20.0版本的，直接升级到1.22不兼容
> > […](#)
> 
> 请问具体是哪里不兼容呢？建议提一个新的 issue，提供更多细节和错误信息，最好能有复现的步骤。

```typescript
useEffect(() => {
    if (!visible) return
    const initModel = async () => {
      try {
        env.wasm.wasmPaths = `${import.meta.env.VITE_BASE_URL1}`
        const model = await InferenceSession.create(
          `${import.meta.env.VITE_BASE_URL1}model/sam_onnx_quantized_example.onnx`
        )
        setModel(model)
      } catch (e) {
        console.log(e)
      }
    }
    if (model) return
    initModel()
  }, [visible])
```

会出现以下错误,1.20.1版本的时候是正常的：
```
useSam.ts:38 
 GET http://localhost:5174/ort-wasm-simd-threaded.jsep.mjs?import net::ERR_ABORTED 404 (Not Found)
useSam.ts:43 Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch dynamically imported module: http://localhost:5174/ort-wasm-simd-threaded.jsep.mjs?import, [cpu] Error: previous call to 'initWasm()' failed., [webnn] Error: previous call to 'initWasm()' failed., [webgpu] Error: previous call to 'initWasm()' failed.
    at async initModel (useSam.ts:38:23)
```

**Comment by fs-eire** [comment]
```
useSam.ts:38 
 GET http://localhost:5174/ort-wasm-simd-threaded.jsep.mjs?import net::ERR_ABORTED 404 (Not Found)
useSam.ts:43 Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch dynamically imported module: http://localhost:5174/ort-wasm-simd-threaded.jsep.mjs?import, [cpu] Error: previous call to 'initWasm()' failed., [webnn] Error: previous call to 'initWasm()' failed., [webgpu] Error: previous call to 'initWasm()' failed.
    at async initModel (useSam.ts:38:23)
```

The log indicates that you are not running onnxruntime-web v1.22.

requesting to "\<path-to-mjs>**?import**" is the old behavior. The code to fetch "`<path-to-mjs>?import`" is no longer existed in v1.22, so if you see the log above, you must have incorrectly installed onnxruntime-web.

suggest to do a clean installation (remove folder node_modules, package-lock.json and do `npm install`)
