### ISSUE TITLE
[Performance] Onnx Static Quantization 😭

### ISSUE THREAD

**Issue by shimaamorsy** [microsoft/onnxruntime#20239]
### Describe the issue

 I'm struggling to find the material to help me for solving my task. I'm trying to speed up the performance of YOLOv5-segmentation using static quantization. I have followed the ONNX Runtime official tutorial on how to apply static quantization

However, I encountered an error when i tried to preprocess the library
![error](https://github.com/microsoft/onnxruntime/assets/93089408/0e0a86ec-0d52-4634-8f13-ab4943c4df04)

### To reproduce

 [ONNX Runtime official tutorial](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md)

### Urgency

Very urgent,  I should complete my task this week 😭ONNX Runtime official tutorial

### Platform

Windows

### OS Version

Windows  11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by xadupre** [comment]
I tried to replicate your issue but it works for me with onnxruntime from main branch. I following the tutorial here to get the model you are using: https://github.com/ultralytics/yolov5?tab=readme-ov-file.

**Comment by shimaamorsy** [comment]
Could you recall the precise steps you took to quantize the YOLO library , Plz !

**Comment by shimaamorsy** [comment]
**Firstly**, I appreciate your response, and I'm pleased to report that following your instructions led to success for me.

However, may I make another request? Could you kindly provide a Python script that enables me to quantize yolov5-seg.onnx with an input shape of [1,3,640,640] to QInt8?

I'm relatively new to ONNX and quantization, and I'm still in the early stages of learning. As a result, I may not have the expertise to resolve any errors that arise. Your assistance would be greatly appreciated.

**Comment by shimaamorsy** [comment]
Initially, I appreciate your response. However, when I tried to use yolov5-seg.onnx, I encountered an error.

After exporting [yolov5n-seg.pt to the ONNX format](https://docs.ultralytics.com/tasks/segment/#export) :

`!python export.py --weights yolov5n-seg.pt --include torchscript onnx`

I attempted to preprocess it for [static quantization](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md). 
Unfortunately, I encountered an error during this process.
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\anaconda3\Lib\site-packages\onnxruntime\quantization\preprocess.py", line 127, in <module>
    quant_pre_process(
  File "G:\anaconda3\Lib\site-packages\onnxruntime\quantization\shape_inference.py", line 71, in quant_pre_process
    model = SymbolicShapeInference.infer_shapes(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\anaconda3\Lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 2855, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\anaconda3\Lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 2644, in _infer_impl
    out_rank = len(get_shape_from_type_proto(vi.type))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\anaconda3\Lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 37, in get_shape_from_type_proto
    assert not is_sequence(type_proto)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\anaconda3\Lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 32, in is_sequence
    assert cls_type in ["tensor_type", "sequence_type"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError`

As I have limited experience with ONNX and quantization, and I'm still in the early stages of learning, I lack the expertise to resolve these errors. Your help would be greatly appreciated.

**Comment by Labman4** [comment]
i solved this problem by update python=3.8 onnx=1.16.1 onnxruntime=1.18.1
