### ISSUE TITLE
Get reshape error for Tensorflow BERT model

### ISSUE THREAD

**Issue by jayjaywg** [Microsoft/onnxruntime#204]
Hi, 

I converted tensorflow BERT model to onnx by https://github.com/onnx/tensorflow-onnx, but when i do inference, i met error as 

_GENERAL ERROR : c:\agent\_work\3\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{70,**767**}_

the model have three inputs with shape [100,70], i don't know where did **767** come from? can anyone help?

**Comment by yufenglee** [comment]
@jayjaywg the input shape:{70,767} is for operator reshape, not the model input. I guess there may be something wrong with the converter. Could you please share the model to @pengwa and @guschmue ? Or log an issue in https://github.com/onnx/tensorflow-onnx instead?

**Comment by guschmue** [comment]
To convert a tensorflow bert model, follow the instructions here:
https://gist.github.com/guschmue/9f2ba608414bef13fa67cdf278ca1e99

**Comment by WilliamTambellini** [comment]
Hi @guschmue  
Could you please precise what you mean by : 
"We want to use placeholders but the TpuEstimator used in run_squad.py doesn't support this,
we require a small change in run_squad.py / model_fn_builder to pass in a argument to a flag
to use TpuEstimator or standard Estimator."
in export_to_saved_model.py ?
Kind

**Comment by guschmue** [comment]
Sorry, did not get a notify for the question.
This comment in export_to_saved_model.py - we want the input to be a Placeholder when we export the model as saved_model but with the used in bert TpuEstimator that doesn't work so in export_to_saved_model.py (which is mostly a copy of  run_squad.py) I replaced the  TpuEstimator with a normal Estimator. This is the code in ```if USE_TPU_ESTIMATOR ```

**Comment by WilliamTambellini** [comment]
Ok thanks. So perhaps the error I encounter is unrelated to that comment :  

INFO:tensorflow:Done calling model_fn.
Traceback (most recent call last):
  File "../export_to_saved_model.py", line 113, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "../export_to_saved_model.py", line 108, in main
    serving_input_receiver_fn=serving_input_receiver_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 663, in export_savedmodel
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 789, in _export_saved_model_for_mode
    strip_default_attrs=strip_default_attrs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 907, in _export_all_saved_models
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 984, in _add_meta_graph_for_mode
    config=self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1199, in _call_model_fn
    raise ValueError('model_fn should return an EstimatorSpec.')
ValueError: model_fn should return an EstimatorSpec.

TBC. Tks.
