### ISSUE TITLE
Onnx model throws an exception in 1.17.3 but works in 1.16.x

### ISSUE THREAD

**Issue by nmetulev** [microsoft/onnxruntime#20514]
### Describe the issue

Model: https://github.com/snakers4/silero-vad/tree/master/files

I'm trying to use this onnx model in my .NET Core WinAppSdk application with OnnxRuntime 1.17.3, which throws the following exception on inference. Running the exact same model and code with 1.16.x works as expected and no exception is thrown.

```
[ErrorCode:Fail] Non-zero status code returned while running If node. Name:'If_25' Status Message: if.cc:266 onnxruntime::If::Compute If nodes condition input must have exactly one element
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.RunImpl(RunOptions options, IntPtr[] inputNames, IntPtr[] inputValues, IntPtr[] outputNames)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 outputNames, RunOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 outputNames)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs)
   at TextPad.VoiceRecognition.VoiceActivity.SlieroVadOnnxModel.Call(Single[][] x, Int32 sr) in F:\source\TextPad\TextPad.Whisper\whisper\VoiceActivity\SlieroVadOnnxModel.cs:line 116
   at TextPad.VoiceRecognition.VoiceActivity.SlieroVadDetector.Apply(Byte[] data, Boolean returnSeconds) in F:\source\TextPad\TextPad.Whisper\whisper\VoiceActivity\SlieroVadDetector.cs:line 61
```

![image](https://github.com/microsoft/onnxruntime/assets/711864/3e7273ae-20a4-449e-92ef-5408988af690)

### To reproduce

You can use this project to repro: https://github.com/microsoft/Windows-DevRel/tree/gleb/AudioEditor-libs/Projects/AudioEditor
Uncomment this line: https://github.com/microsoft/Windows-DevRel/blob/gleb/AudioEditor-libs/Projects/AudioEditor/MainWindow.xaml.cs#L39

Feel free to reach out to me and I'm happy to walk through it to repro as well.

### Platform

Windows

### OS Version

22h2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.3

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yuslepukhin** [comment]
There was a change recently that exposes this model problem. Check your model to see if the given If node has an input with more than one element.
