### ISSUE TITLE
Build onnxruntime with SNPE EP on SA8155P

### ISSUE THREAD

**Issue by June1124** [microsoft/onnxruntime#21011]
### Describe the issue

![image](https://github.com/microsoft/onnxruntime/assets/52447302/004f6c3c-292d-47f4-b687-16b554ecd47b)

### Target platform

SA8155P

### Build script

**[COMMAND]**
build.bat --build_shared_lib --skip_submodule_sync --android --config Release --use_snpe --snpe_root F:/Work/QUALCOMM/snpe-1.61.0.3358 --android_sdk_path E:/AndroidSDK --android_ndk_path E:/AndroidSDK/ndk/26.2.11394342 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja --build_dir build\Android

### Error / output

1 error generated.
[460/1261] Building CXX object CMakeFiles/onnxruntime_util.dir/D_/Desktop/onnxruntime-1.13.1-recursive/onnxruntime/core/util/math_cpu.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Desktop\onnxruntime-1.13.1-recursive\\tools\ci_build\build.py", line 2952, in <module>
    sys.exit(main())
  File "D:\Desktop\onnxruntime-1.13.1-recursive\\tools\ci_build\build.py", line 2844, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\Desktop\onnxruntime-1.13.1-recursive\\tools\ci_build\build.py", line 1731, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\Desktop\onnxruntime-1.13.1-recursive\\tools\ci_build\build.py", line 861, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Desktop\onnxruntime-1.13.1-recursive\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "D:\ProgramData\anaconda3\envs\wxj\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'build\\Android\\Release', '--config', 'Release']' returned non-zero exit status 1.

**Comment by HectorSVC** [comment]
We don't support SNPE any more, please use QNN EP instead. https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html
