### ISSUE TITLE
[Feature Request] support FP8 calibraion method and quantization

### ISSUE THREAD

**Issue by zccyman** [microsoft/onnxruntime#21090]
Describe:

I set weight/activation with QuantType.QFLOAT8E4M3FN in quantize_static, but I get the following errors:

````
Traceback (most recent call last):
  File "/home/developer/workspace/code/onnxruntime/examples/only_one_conv/run.py", line 102, in <module>
    main()
  File "/home/developer/workspace/code/onnxruntime/examples/only_one_conv/run.py", line 71, in main
    quantize_static(
  File "/root/miniconda3/envs/ort/lib/python3.10/site-packages/onnxruntime/quantization/quantize.py", line 441, in quantize_static
    raise ValueError("Only Distribution calibration method is supported for float quantization.")
ValueError: Only Distribution calibration method is supported for float quantization.

```

so I think FP8 calibration and quantization is not supported so far ?

**Comment by yufenglee** [comment]
@zccyman, you can specify the calibration method to CalibrationMethod.Distribution

https://github.com/microsoft/onnxruntime/blob/01279d889671363008e91fd76917864b36b51cdd/onnxruntime/python/tools/quantization/quantize.py#L440C32-L440C62

**Comment by zccyman** [comment]
> @zccyman, you can specify the calibration method to CalibrationMethod.Distribution↳
> 
> https://github.com/microsoft/onnxruntime/blob/01279d889671363008e91fd76917864b36b51cdd/onnxruntime/python/tools/quantization/quantize.py#L440C32-L440C62

It's right. but I find another issue that per-channel quantization is not supported during fp8 quantization? the following error what I get:
```
Traceback (most recent call last):
  File "/home/developer/workspace/code/onnxruntime/examples/only_one_conv/run.py", line 110, in <module>
    main()
  File "/home/developer/workspace/code/onnxruntime/examples/only_one_conv/run.py", line 106, in main
    benchmark(output_model_path)
  File "/home/developer/workspace/code/onnxruntime/examples/only_one_conv/run.py", line 15, in benchmark
    session = onnxruntime.InferenceSession(model_path)
  File "/root/miniconda3/envs/ort/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/envs/ort/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from examples/only_one_conv/mobilenetv2-7.quant.onnx failed:This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (conv1.weight_quantized) of operator (DequantizeLinear) in node (conv1.weight_DequantizeLinear) is invalid.

def benchmark(model_path):
    session = onnxruntime.InferenceSession(model_path)
    input_name = session.get_inputs()[0].name

    total = 0.0
    runs = 10
    input_data = np.zeros((1, 3, 224, 224), np.float32)
    # Warming up
    _ = session.run([], {input_name: input_data})
    for i in range(runs):
        start = time.perf_counter()
        _ = session.run([], {input_name: input_data})
        end = (time.perf_counter() - start) * 1000
        total += end
        print(f"{end:.2f}ms")
    total /= runs
    print(f"Avg: {total:.2f}ms")

benchmark("examples/only_one_conv/mobilenetv2-7.quant.onnx")
[mobilenetv2-7.quant.zip](https://github.com/user-attachments/files/15907145/mobilenetv2-7.quant.zip)

```
