### ISSUE TITLE
Initialization crash using OnnxRuntime 17.0 (previously working on 16.3)

### ISSUE THREAD

**Issue by vpenades** [microsoft/onnxruntime#21205]
### Describe the issue

After upgrading from 16.3 to 17.0,  the application crashes when attempting to load the model.

```
ERROR  - Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\DmlGraphFusionHelper.cpp(451)\onnxruntime.DLL!00007FFBFC55CB19: (caller: 00007FFBFC4DFDE4) Exception(1) tid(3230) 80004005 Error no especificado

   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(Byte[] modelData, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(Byte[] model, SessionOptions options)
```

I've tried all subsequent versions up to 18.1 and all of them crash. If I revert back to 16.3, it works fine.

Also, this is apparently happening ONLY on low end machines with integrated _Intel HD Graphics_,

On other, more powerful computers we have it is working fine.

### To reproduce

- OnnxRuntime 17.0 and up
- DirectML
- Intel HD Graphics card

Example Computer:
- Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz   2.00 GHz
- Graphics card:  Intel(R) HD Graphics 5500
- RAM: 8,00 GB (7,90 GB usable)
- Windows 10 Pro,	22H2,  19045.4529,  1000.19058.1000.0

And attempt to load this model: [model_float32.zip](https://github.com/user-attachments/files/16029414/model_float32.zip)

### Urgency

We can stay in 16.3 for a while, but it would be nice if it could be clarified if the issue is related to the graphics card is no longer supported (again, exception messages could report this)

### Platform

Windows

### OS Version

Windows 10 Pro

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

17.0

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

1.13.1

**Comment by vpenades** [comment]
Fixed in OnnxRuntime 1.19
