### ISSUE TITLE
[Build] ModuleNotFoundError: No module named 'onnxruntime.capi'

### ISSUE THREAD

**Issue by lzivan** [microsoft/onnxruntime#21317]
### Describe the issue

Hi team,

I'm using CPU build from source.
```
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --build_wheel --skip_tests
```

The build is successfully done. Now I'm using conda with python 3.11.
The WHL file is under build\Windows\RelWithDebInfo\RelWithDebInfo\dist.
```
pip install onnxruntime-1.19.0-cp311-cp311-win_amd64.whl
```

However, when I'm running [onnxruntime-python-api.py](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/python/api/onnxruntime-python-api.py)

It presents:
```
Traceback (most recent call last):
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime-python-api.py", line 7, in <module>
    import onnxruntime
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime\__init__.py", line 54, in <module>
    from onnxruntime.capi import onnxruntime_validation
ModuleNotFoundError: No module named 'onnxruntime.capi'
```
So I checked the site-packages of onnxruntime under conda envs, it does exist.
![image](https://github.com/microsoft/onnxruntime/assets/102374003/fd08a6a5-7fc6-4732-b49c-7e505113b31a)

Please help, I'm not sure whether some packages are lost during the installation from whl.

### Target platform

Onnxruntime CPU

### Build script

```
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --build_wheel --skip_tests

pip install onnxruntime-1.19.0-cp311-cp311-win_amd64.whl
```

### Error / output
```
Traceback (most recent call last):
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime-python-api.py", line 7, in <module>
    import onnxruntime
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime\__init__.py", line 54, in <module>
    from onnxruntime.capi import onnxruntime_validation
ModuleNotFoundError: No module named 'onnxruntime.capi'
```

**Comment by lzivan** [comment]
This is my pip list after installation from WHL.
```
Package           Version
----------------- ---------
coloredlogs       15.0.1
filelock          3.15.4
flatbuffers       24.3.25
fsspec            2024.6.1
humanfriendly     10.0
intel-openmp      2021.4.0
Jinja2            3.1.4
MarkupSafe        2.1.5
mkl               2021.4.0
mpmath            1.3.0
networkx          3.3
numpy             2.0.0
onnxruntime       1.19.0
packaging         24.1
pip               24.0
protobuf          5.27.2
pyreadline3       3.4.1
setuptools        70.2.0
sympy             1.13.0
tbb               2021.13.0
torch             2.3.1
typing_extensions 4.12.2
wheel             0.43.0
```

**Comment by mgehre-amd** [comment]
I had the same problem when running python scripts from the onnxruntime git checkout, because it contains a folder named "onnxruntime" which gets confused with the onnxruntime package.

**Comment by lzivan** [comment]
Thanks for the response. I changed the name of the onnxruntime folder under the git repo, and it won't give me "onnxruntime.capi" error. But now it says "Module onnx is not installed". 

According to the error log, "onnx" is called under "torch". For "torch", I manually installed it by "pip install" after installing the WHL file. So for "onnx", do I need to manually install it by "pip install onnx"? Btw "onnx" is not installed after installing the WHL.

``` Error log
Traceback (most recent call last):
  File "C:\Users\arda\miniforge3\envs\test-onnx\Lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 219, in _add_onnxscript_fn
    import onnx
ModuleNotFoundError: No module named 'onnx'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime-python-api.py", line 127, in <module>
    main()
    ^^^^^^
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime-python-api.py", line 109, in main
    create_model()
  File "C:\Users\arda\zijie\onnxruntime\onnxruntime-python-api.py", line 30, in create_model
    torch.onnx.export(model(), (sample_x, sample_y), MODEL_FILE, input_names=["x", "y"], output_names=["z"],
  File "C:\Users\arda\miniforge3\envs\test-onnx\Lib\site-packages\torch\onnx\utils.py", line 516, in export
    _export(
  File "C:\Users\arda\miniforge3\envs\test-onnx\Lib\site-packages\torch\onnx\utils.py", line 1686, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arda\miniforge3\envs\test-onnx\Lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 221, in _add_onnxscript_fn
    raise errors.OnnxExporterError("Module onnx is not installed!") from e
torch.onnx.errors.OnnxExporterError: Module onnx is not installed!
```

**Comment by bluejack** [comment]
I have this problem also; did anyone find an answer?

**Comment by mgehre-amd** [comment]
> I have this problem also; did anyone find an answer?

This typically happens when your working directory is a checkout of the `onnxruntime` repo, which contains an `onnxruntime` folder. This confuses python to think that it look into that folder to find the package.

To solve this, run your python script from a different working directory.

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
