### ISSUE TITLE
Unable to append DML Provider

### ISSUE THREAD

**Issue by Article012** [microsoft/onnxruntime#21432]
### Describe the issue

`Microsoft.ML.OnnxRuntime.DirectML` I install only this package, and then when I tried `AppendExecutionProvider_DML()`
I got the following error: `Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] D:\a_work\1\s\onnxruntime\core\providers\dml\dml_provider_factory.cc(518)\onnxruntime.DLL!69 EB64F9: (caller: 69EB6661) Exception(1) tid(5df8) 887A0004 The specified device interface or feature level is not supported on this system.`

### To reproduce

in .net 4.8.1

install the Nuget packages Microsoft.ML.OnnxRuntime.DirectML and then 

```
var sessionOptions = new SessionOptions();
sessionOptions.AppendExecutionProvider_DML();
```

When I run this code, I get the error below

```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\providers\dml\dml_provider_factory.cc(518)\onnxruntime.DLL!69CE57A9: (caller: 69CE5911) Exception(1) tid(3ec4) 887A0004 The specified device interface or feature level is not supported on this system.

  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeApiStatus.shared.cs:line 33
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_DML(Int32 deviceId) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.shared.cs:line 274
   at asdasdasd.Form1.Form1_Load(Object sender, EventArgs e) in E:\Project\C#\sa\asdasdasd\asdasdasd\Form1.cs:line 29
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Funny thing is, it worked fine in .NET 8.0.

### Platform

Windows

### OS Version

22h2 (os build 19045 4412)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

### Model File

[model.zip](https://github.com/user-attachments/files/16322702/model.zip)

### Is this a quantized model?

Unknown

**Comment by Article012** [comment]
solve

**Comment by WinInsider** [comment]
@artist012 How? I have same problem...

**Comment by MeshHun** [comment]
> solve

how to?
