### ISSUE TITLE
[Inference] Unable to export model for Inference 

### ISSUE THREAD

**Issue by srijanie03** [microsoft/onnxruntime#21591]
### Describe the issue

I am following the following notebook to run training and subsequent inference on an ONNX model by @baijumeswani :

https://github.com/microsoft/onnxruntime-training-examples/blob/75e56de37daeea6ce50261d9d115102bda078c76/on_device_training/desktop/python/mnist.ipynb

I am able to generate the forward graph, training graph, eval graph, optimizer graph and the checkpoint. The model runs training smoothly. However, while trying this:

```py
model.export_model_for_inferencing("inference_model.onnx",["output"])
```

I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/training/api/module.py", line 204, in export_model_for_inferencing
    self._model.export_model_for_inferencing(os.fspath(inference_model_uri), graph_output_names)
RuntimeError: orttraining/orttraining/training_api/module.cc:685 onnxruntime::common::Status onnxruntime::training::api::Module::ExportModelForInferencing(const string&, gsl::span<const std::__cxx11::basic_string<char> >) const [ONNXRuntimeError] : 1 : FAIL :onnxruntime/core/graph/graph.cc:3989 onnx::GraphProto onnxruntime::Graph::ToGraphProtoWithExternalInitializers(const string&, const PathString&, size_t) const external_stream.is_open() was false.
```

I was able to generate the inference graph for a similar model by following the same procedure.  
What could be causing this issue?

### To reproduce

```py
state = CheckpointState("checkpoint")
model = Module("training_model.onnx", state, "eval_model.onnx")
optimizer = Optimizer("optimizer.onnx", model)

model.export_model_for_inferencing("inference_model.onnx",["output"])
```

### Urgency

Urgent

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.18.1

### PyTorch Version

2.4.0

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.4

**Comment by srijanie03** [comment]
The checkpoint.data file is 26G. Is that supposed to create an issue?
