### ISSUE TITLE
fail to run the MaskRCNN model

### ISSUE THREAD

**Issue by vera121** [microsoft/onnxruntime#2166]
**Describe the bug**
Hello, When  I try to run the MaskRCNN model from onnx model zoo (downloaded at https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn)
onnxruntime reports the error:
```
Traceback (most recent call last):
  File "onnx2ev/onnxruntime_compare.py", line 22, in <module>
    pred_onnx = sess.run([], {input_name: X})
  File "/home/yche/SNPS_Caffe/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:324 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 0 by 1
Stacktrace:
```

Here are the code I use:
```
import numpy as np
import onnxruntime as rt

sess = rt.InferenceSession("mask_rcnn_R_50_FPN_1x.onnx")
input_name = sess.get_inputs()[0].name
X = np.random.random((3, 800, 800)).astype(np.float32)
pred_onnx = sess.run([], {input_name: X})
```

**System information**
- OS Platform and Distribution Linux Ubuntu 16.04.3 LTS:
- ONNX Runtime installed from pip
- ONNX Runtime version: 0.5.0
- Python version: 3.6.5

**Comment by vera121** [comment]
Found the answer at https://github.com/microsoft/onnxruntime/issues/1670
The mask rcnn model needs real image input with its way of preprocessing, instead of random input.
Then the model can run and generate results.
