### ISSUE TITLE
[Bug] [onnxruntime-node] Error: no available backend found. ERR: [wasm] backend not found.

### ISSUE THREAD

**Issue by kabyanil** [microsoft/onnxruntime#21813]
I am creating an Electron app where I need to run inference on some onnx models through the Node.js backend. I have installed ``` "onnxruntime-node": "^1.19.0" ``` as dependency. I am initializing the models with -

```
const sessionOptions = {
         executionProviders: ['wasm'],
      }

const session = {
         model_1: await ort.InferenceSession.create("./assets/models/model_1.onnx", sessionOptions),
      }
```

This throws the following error when I run ```electron .``` -

```
Error: no available backend found. ERR: [wasm] backend not found.
    at resolveBackendAndExecutionProviders (~/my-electron-app/node_modules/onnxruntime-common/dist/cjs/backend-impl.js:124:15)
    at async InferenceSession.create (~/my-electron-app/node_modules/onnxruntime-common/dist/cjs/inference-session-impl.js:183:52)
```

I am on intel x64 MacOS 12.7.5 with Node.js version 20.16.0.

This issue to very urgent to me, as I am not able to write the inference code without first loading the model.

What is the issue here and how to resolve it?

**Comment by guschmue** [comment]
Try to change to replace 'wasm' with 'cpu'. onnxruntime-node would not include the webassemly  flavor.
If you want webassembly you can replace onnxruntime-node with onnxruntime-web - should be the same api but that one will support 'wasm' ep.

**Comment by kabyanil** [comment]
Thanks, I tried 'cpu' right after creating this issue, and it worked! Btw, which one is faster in your opinion?

**Comment by fs-eire** [comment]
usually `cpu` is faster than `wasm` in Node.js. however the best answer is to try both and check which one is faster in your application.

**Comment by kabyanil** [comment]
@fs-eire I found the cpu backend to be decently fast, with the models loading in ~1.x second, and inferencing in ~200 milliseconds. I couldn't test wasm as it wouldn't load in node.js though.
