### ISSUE TITLE
CUDA Error cudaErrorUnsupportedPtxVersion with NVIDIA H800 (Compute Capability 9.0) on ONNXRuntime GPU 1.19.2

### ISSUE THREAD

**Issue by xh-liu-tech** [microsoft/onnxruntime#22212]
### Description:

I'm encountering a CUDA error when attempting to execute a training process using ONNXRuntime GPU version 1.19.2 on a system with an NVIDIA H800 GPU (Compute Capability 9.0). The error indicates an unsupported PTX version, which I believe is related to compatibility issues between the GPU's compute capability and the precompiled ONNXRuntime binaries.

### Environment:

- Operating System: Linux
- Python Version: 3.10.14
- CUDA Toolkit Version: 12.1 (nvcc 12.1.66)
- NVIDIA Driver Version: 525.105.17
- GPU: NVIDIA H800 (Compute Capability 9.0)
- ONNXRuntime GPU Version: 1.19.2
- Installed via: pip

### Error Message:

```
2024-09-24 16:09:55.420104702 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorUnsupportedPtxVersion:the provided PTX was compiled with an unsupported toolchain.
09/24/2024 16:09:55 - ERROR - root - Failed to execute the training process: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorUnsupportedPtxVersion:the provided PTX was compiled with an unsupported toolchain.
Traceback (most recent call last):
  File "train.py", line 853, in <module>
    train_stage1_process(config)
  File "train.py", line 794, in train_stage1_process
    log_validation(
  File "train.py", line 249, in log_validation
    face_info = image_enc.get(
  File "/data/miniconda3/envs/env-py3.10/lib/python3.10/site-packages/insightface/app/face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "/data/miniconda3/envs/env-py3.10/lib/python3.10/site-packages/insightface/model_zoo/retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
  File "/data/miniconda3/envs/env-py3.10/lib/python3.10/site-packages/insightface/model_zoo/retinaface.py", line 152, in forward
    net_outs = self.session.run(self.output_names, {self.input_name : blob})
  File "/data/miniconda3/envs/env-py3.10/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_15' Status Message: CUDA error cudaErrorUnsupportedPtxVersion:the provided PTX was compiled with an unsupported toolchain.
Steps:   0%|
```

### Request for Assistance:

Is there a precompiled version of onnxruntime-gpu that supports Compute Capability 9.0 (NVIDIA H800)? If not, could support for this Compute Capability be included in upcoming releases? Alternatively, are there recommended steps to compile onnxruntime from source to ensure compatibility with the NVIDIA H800 GPU?

Thank you for your assistance and for maintaining the ONNX Runtime project.

### To reproduce

1. **Environment Setup:**
   - Create and activate a Conda environment with Python 3.10.
   - Install `onnxruntime-gpu` version 1.19.2 via `pip`.
   - Ensure CUDA Toolkit 12.1 and NVIDIA driver 525.105.17 with NVIDIA H800 GPU are installed and correctly configured.

2. **Run Insightface:**
   - Execute the `insightface.app.FaceAnalysis().get()` which utilizes `onnxruntime-gpu` for model inference.

3. **Encounter Error:**
   - The process fails with the CUDA error indicating an unsupported PTX version.

### Platform

Linux

### OS Version

TencentOS Server 4.0

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by tianleiwu** [comment]
There is no problem in our testing machine of H100 with Nvidia driver Version: 550.54.15; CUDA Version: 12.5.1.

Try upgrade nvidia driver shall resolve the issue . See https://forums.developer.nvidia.com/t/driver-compatiblity-cuda-12-1/253052

**Comment by xh-liu-tech** [comment]
> There is no problem in our testing machine of H100 with Nvidia driver Version: 550.54.15; CUDA Version: 12.5.1.
> 
> Try upgrade nvidia driver shall resolve the issue . See https://forums.developer.nvidia.com/t/driver-compatiblity-cuda-12-1/253052

Thank you for your response. I will try to upgrade the Nvidia driver.
