### ISSUE TITLE
Build failure on Windows 10 using OpenVino 2024.3 & 2024.4 both.

### ISSUE THREAD

**Issue by prashant-saxena** [microsoft/onnxruntime#22314]
### Describe the issue

Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 1800 Mhz, 4 Core(s), 8 Logical Processor(s)
GPU                 Intel UHD Graphics 620
CMake 3.30.4

Build fail on windows using openvino 2024.3 & 2024.4

### Urgency

Nope

### Target platform

Windows 10 x64

### Build script

1. git clone --recursive https://github.com/Microsoft/onnxruntime.git
2. cd onnxruntime
3. python 3.10.0 virtual environment installed
4. OpenVino 2024.3 / 2024.4 setupvars.bat executed before trying each package.
5. python -m pip install cmake

Build command
```
build.bat --config Release --use_openvino HETERO:GPU,CPU --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --skip_tests
```

### Error / output

With OpenVino 2024.3
```
...
...
  provider_ort_api_init.cc
  provider_bridge_provider.cc
  my_allocator.cc
  my_ep_data_transfer.cc
  my_ep_factory.cc
  my_execution_provider.cc
Creating library D:/projects/onnxruntime/build/Windows/Release/Release/test_execution_provider.lib and object D:/p
  rojects/onnxruntime/build/Windows/Release/Release/test_execution_provider.exp
  test_execution_provider.vcxproj -> D:\projects\onnxruntime\build\Windows\Release\Release\test_execution_provider.dll
Traceback (most recent call last):
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 2972, in <module>
    sys.exit(main())
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 2862, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 1730, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 865, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\projects\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['D:\\projects\\onnxruntime\\.venv\\Scripts\\cmake.EXE', '--build', 'D:\\projects\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:8', '/p:CL_MPCount=7', '/nodeReuse:False']' returned non-zero exit status 1.
```

With OpenVino 2024.4
```
<char>,std::allocator<char>>::operator =(const _StringViewIsh &)': could not deduce template argument for '__formal'
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xstring(599,9):
              'std::enable_if_t<false,int>' : Failed to specialize alias template
      D:\projects\onnxruntime\onnxruntime\core\providers\openvino\openvino_execution_provider.h(145,7):
      while trying to match the argument list '(const std::string, const char [15])'

Traceback (most recent call last):
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 2972, in <module>
    sys.exit(main())
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 2862, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 1730, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\projects\onnxruntime\tools\ci_build\build.py", line 865, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\projects\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['D:\\projects\\onnxruntime\\.venv\\Scripts\\cmake.EXE', '--build', 'D:\\projects\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:8', '/p:CL_MPCount=7', '/nodeReuse:False']' returned non-zero exit status 1.
```

### Visual Studio Version

17.11.4

**Comment by edgchen1** [comment]
Can you provide the full error message and the onnxruntime commit that you're using?

**Comment by prashant-saxena** [comment]
commit : d0ddfa9b9e
The problem is solved with these three changes:
1. Change in onnxruntime\onnxruntime\core\providers\openvino\openvino_execution_provider.h
```
from
explicit OpenVINOExecutionProviderInfo(const std::string& dev_type
to
explicit OpenVINOExecutionProviderInfo(std::string& dev_type
```
2. --config MinSizeRel
3. The  resulting onnxruntime_providers_openvino.dll was having a dependency on 
```
openvino_2024.4.0\runtime\bin\intel64\Debug\openvinod.dll (debug version)
```
because internally it's using
```
openvino_2024.4.0\runtime\cmake\OpenVINOTargets-debug.cmake instead of release.

Even after passing --skip_tests & --skip_onnx_tests, the build process is creating all the tests.

**Comment by edgchen1** [comment]
#21443 updated the signature of the OpenVINOExecutionProviderInfo ctor. It changed `dev_type` from `std::string` to `const std::string&`.

https://github.com/microsoft/onnxruntime/blob/d7367653ab28045ab95bf784642c6b0e48975df4/onnxruntime/core/providers/openvino/openvino_execution_provider.h#L97

However, `dev_type` is assigned to in this code path, so it cannot be `const std::string&`.

https://github.com/microsoft/onnxruntime/blob/d7367653ab28045ab95bf784642c6b0e48975df4/onnxruntime/core/providers/openvino/openvino_execution_provider.h#L145

FYI @jywu-msft and @preetha-intel
