### ISSUE TITLE
AttributeError: FLOAT8E4M3FN during quantization

### ISSUE THREAD

**Issue by maaft** [microsoft/onnxruntime#22640]
### Describe the issue

The preprocess step for quantization does not work with the latest onnxruntime version:

```shell
python -m onnxruntime.quantization.preprocess --input image_resize.onnx --output image_resize_q.onnx
``` 

```
Traceback (most recent call last):
  File "/home/foobar/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/foobar/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/__init__.py", line 1, in <module>
    from .calibrate import (  # noqa: F401
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/calibrate.py", line 22, in <module>
    from .quant_utils import apply_plot, load_model_with_shape_infer, smooth_distribution
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/quant_utils.py", line 144, in <module>
    onnx_proto.TensorProto.FLOAT8E4M3FN: float8e4m3fn,
AttributeError: FLOAT8E4M3FN
``` 

**The same thing works with onnxruntime 1.14.1** so we have some kind of degradation here.

## Failing Example

1. Make sure to use onnxruntime version 1.19.2
2. [Download](https://www.file-upload.net/en/download-15404515/image_resize.onnx.html) example model (simple image-resize)
3. `python -m onnxruntime.quantization.preprocess --input image_resize.onnx --output image_resize_quant.onnx`

```
Traceback (most recent call last):
  File "/home/foobar/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/foobar/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/__init__.py", line 1, in <module>
    from .calibrate import (  # noqa: F401
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/calibrate.py", line 22, in <module>
    from .quant_utils import apply_plot, load_model_with_shape_infer, smooth_distribution
  File "/home/foobar/anaconda3/lib/python3.8/site-packages/onnxruntime/quantization/quant_utils.py", line 144, in <module>
    onnx_proto.TensorProto.FLOAT8E4M3FN: float8e4m3fn,
AttributeError: FLOAT8E4M3FN
``` 

## Working Example
1. install onnxruntime 1.14.1 (pip install onnxruntime==1.14.1)
2. `python -m onnxruntime.quantization.preprocess --input image_resize.onnx --output image_resize_quant.onnx`
3. observe, that preprocessing now works

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

**Comment by justinchuby** [comment]
Please consider installing the latest version of ONNX.
