### ISSUE TITLE
[C#] The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by valucn** [microsoft/onnxruntime#22683]
### Describe the issue

The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Compunet.YoloV8.YoloV8Predictor..ctor(BinarySelector model, YoloV8Metadata metadata, YoloV8Configuration configuration, SessionOptions options)
   at Compunet.YoloV8.YoloV8Builder.Build()
   at Compunet.YoloV8.YoloV8Predictor.Create(BinarySelector model)

### To reproduce

using var predictor = YoloV8Predictor.Create("files/textv8.onnx");

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.18.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by fs-eire** [comment]
This is not a web/JavaScript/WebAssembly issue. I assume it is a C# issue. Please correct it if I was wrong.

**Comment by skottmckay** [comment]
Typically that is because it can't load onnxruntime.dll. Make sure it's in the same directory as the binary you're running.
