### ISSUE TITLE
INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"

### ISSUE THREAD

**Issue by baishouwujianfei** [microsoft/onnxruntime#22947]
### Describe the issue

hello, I encountered an error while using onnxruntime-gpu to start the model service through CUDA: `onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\contrib_ops\cuda\fused_conv.cc:19 onnxruntime::contrib::cuda::FusedConv<float>::FusedConv [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu". `The model runs normally when switched to the CPU with other parameters unchanged. How can I resolve this issue?

### To reproduce

none

### Urgency

general

### Platform

Windows

### OS Version

win 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-gpu 1.19.2

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA12.2

**Comment by skottmckay** [comment]
Seems like a bug in the Conv fusion optimizer. If the CUDA EP doesn't support LeakyRelu the optimizer shouldn't fuse the Conv and LeakyRelu if they're assigned to the CUDA EP.

**Comment by baishouwujianfei** [comment]
> Seems like a bug in the Conv fusion optimizer. If the CUDA EP doesn't support LeakyRelu the optimizer shouldn't fuse the Conv and LeakyRelu if they're assigned to the CUDA EP.

"Thank you for your reply. How can I avoid this bug, or should I wait for a fix?"

**Comment by skottmckay** [comment]
It's actually setup to ignore the nodes and not fuse if it's assigned to CUDA (technically it could fuse with Relu but right now it's ignoring all activations).

https://github.com/microsoft/onnxruntime/blob/a24723df16b442eaeb1e939a9ed6ffdcbdce7f2c/onnxruntime/core/optimizer/conv_activation_fusion.cc#L118-L119

How was the model created? Wondering if it was saved with CPU EP optimizations applied, and now when it's loaded with CUDA enabled it's invalid. i.e. the optimizer ran previously when the Conv + Activation were assigned to the CPU EP so they were fused.

**Comment by baishouwujianfei** [comment]
> It's actually setup to ignore the nodes and not fuse if it's assigned to CUDA (technically it could fuse with Relu but right now it's ignoring all activations).
> 
> [onnxruntime/onnxruntime/core/optimizer/conv_activation_fusion.cc](https://github.com/microsoft/onnxruntime/blob/a24723df16b442eaeb1e939a9ed6ffdcbdce7f2c/onnxruntime/core/optimizer/conv_activation_fusion.cc#L118-L119)
> 
> Lines 118 to 119 in [a24723d](/microsoft/onnxruntime/commit/a24723df16b442eaeb1e939a9ed6ffdcbdce7f2c)
> 
>  if (node_ep == kCudaExecutionProvider) { 
>    return std::nullopt; 
> How was the model created? Wondering if it was saved with CPU EP optimizations applied, and now when it's loaded with CUDA enabled it's invalid. i.e. the optimizer ran previously when the Conv + Activation were assigned to the CPU EP so they were fused.

Sorry, this is someone else's model that I downloaded from Hugging Face, so I'm not sure how the model was created.
link：https://huggingface.co/seasonstudio/openvoice_tone_clone_onnx/blob/main/tone_clone_model.onnx

**Comment by davispuh** [comment]
I have same issue but I'm using ROCm instead of CUDA.

````
25-07-24 02:48:59.701216167 [E:onnxruntime:, inference_session.cc:2280 operator()] Exception during initialization: /usr/src/debug/onnxruntime/onnxruntime-opt-rocm/onnxruntime/contrib_ops/rocm/fused_conv.cc:127 onnxruntime::contrib::rocm::FusedConv<T>::FusedConv(const onnxruntime::OpKernelInfo&) [with T = float] [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"
Stacktrace:
/usr/lib/libonnxruntime_providers_rocm.so(+0x160c9d) [0x7f6d8e560c9d]
/usr/lib/libonnxruntime_providers_rocm.so(+0x7b547) [0x7f6d8e47b547]
/usr/lib/libonnxruntime_providers_rocm.so(+0x29a781) [0x7f6d8e69a781]
/usr/lib/libonnxruntime_providers_rocm.so(+0xd447b) [0x7f6d8e4d447b]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0xfd60c0) [0x7f6e061d60c0]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0xb82b7e) [0x7f6e05d82b7e]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x47f6d5) [0x7f6e0567f6d5]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x3a61ce) [0x7f6e055a61ce]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x3b8b5f) [0x7f6e055b8b5f]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x35fba9) [0x7f6e0555fba9]
/usr/lib/libpython3.13.so.1.0(+0x194a8c) [0x7f6e34794a8c]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x2bb) [0x7f6e34760e3b]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x408e) [0x7f6e347752be]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(PyEval_EvalCode+0xa9) [0x7f6e3484c8b9]
/usr/lib/libpython3.13.so.1.0(+0x267563) [0x7f6e34867563]
/usr/lib/libpython3.13.so.1.0(+0x18c336) [0x7f6e3478c336]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x5664) [0x7f6e34776894]
/usr/lib/libpython3.13.so.1.0(+0x19419f) [0x7f6e3479419f]
/usr/lib/libpython3.13.so.1.0(PyObject_CallMethodObjArgs+0x10a) [0x7f6e347cf8aa]
/usr/lib/libpython3.13.so.1.0(PyImport_ImportModuleLevelObject+0xf66) [0x7f6e347cf0d6]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x7c29) [0x7f6e34778e59]
/usr/lib/libpython3.13.so.1.0(PyEval_EvalCode+0xa9) [0x7f6e3484c8b9]
/usr/lib/libpython3.13.so.1.0(+0x28af5c) [0x7f6e3488af5c]
/usr/lib/libpython3.13.so.1.0(+0x28801b) [0x7f6e3488801b]
/usr/lib/libpython3.13.so.1.0(+0x285718) [0x7f6e34885718]
/usr/lib/libpython3.13.so.1.0(+0x2849d2) [0x7f6e348849d2]
/usr/lib/libpython3.13.so.1.0(+0x284343) [0x7f6e34884343]
/usr/lib/libpython3.13.so.1.0(Py_RunMain+0x3fb) [0x7f6e3488248b]
/usr/lib/libpython3.13.so.1.0(Py_BytesMain+0x3b) [0x7f6e34839dcb]
/usr/lib/libc.so.6(+0x276b5) [0x7f6e344376b5]
/usr/lib/libc.so.6(__libc_start_main+0x89) [0x7f6e34437769]
python(_start+0x25) [0x55626d533045]

Traceback (most recent call last):
  [...]
  File "[...].py", line 70, in __init__
    self.session = onnxruntime.InferenceSession(model_path, sess_options=options, providers=providersList)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 561, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /usr/src/debug/onnxruntime/onnxruntime-opt-rocm/onnxruntime/contrib_ops/rocm/fused_conv.cc:127 onnxruntime::contrib::rocm::FusedConv<T>::FusedConv(const onnxruntime::OpKernelInfo&) [with T = float] [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"
Stacktrace:
/usr/lib/libonnxruntime_providers_rocm.so(+0x160c9d) [0x7f6d8e560c9d]
/usr/lib/libonnxruntime_providers_rocm.so(+0x7b547) [0x7f6d8e47b547]
/usr/lib/libonnxruntime_providers_rocm.so(+0x29a781) [0x7f6d8e69a781]
/usr/lib/libonnxruntime_providers_rocm.so(+0xd447b) [0x7f6d8e4d447b]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0xfd60c0) [0x7f6e061d60c0]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0xb82b7e) [0x7f6e05d82b7e]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x47f6d5) [0x7f6e0567f6d5]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x3a61ce) [0x7f6e055a61ce]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x3b8b5f) [0x7f6e055b8b5f]
/usr/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so(+0x35fba9) [0x7f6e0555fba9]
/usr/lib/libpython3.13.so.1.0(+0x194a8c) [0x7f6e34794a8c]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x2bb) [0x7f6e34760e3b]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x408e) [0x7f6e347752be]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(+0x1a8ec2) [0x7f6e347a8ec2]
/usr/lib/libpython3.13.so.1.0(_PyObject_MakeTpCall+0x21d) [0x7f6e34760d9d]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0xa45f) [0x7f6e3477b68f]
/usr/lib/libpython3.13.so.1.0(PyEval_EvalCode+0xa9) [0x7f6e3484c8b9]
/usr/lib/libpython3.13.so.1.0(+0x267563) [0x7f6e34867563]
/usr/lib/libpython3.13.so.1.0(+0x18c336) [0x7f6e3478c336]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x5664) [0x7f6e34776894]
/usr/lib/libpython3.13.so.1.0(+0x19419f) [0x7f6e3479419f]
/usr/lib/libpython3.13.so.1.0(PyObject_CallMethodObjArgs+0x10a) [0x7f6e347cf8aa]
/usr/lib/libpython3.13.so.1.0(PyImport_ImportModuleLevelObject+0xf66) [0x7f6e347cf0d6]
/usr/lib/libpython3.13.so.1.0(_PyEval_EvalFrameDefault+0x7c29) [0x7f6e34778e59]
/usr/lib/libpython3.13.so.1.0(PyEval_EvalCode+0xa9) [0x7f6e3484c8b9]
/usr/lib/libpython3.13.so.1.0(+0x28af5c) [0x7f6e3488af5c]
/usr/lib/libpython3.13.so.1.0(+0x28801b) [0x7f6e3488801b]
/usr/lib/libpython3.13.so.1.0(+0x285718) [0x7f6e34885718]
/usr/lib/libpython3.13.so.1.0(+0x2849d2) [0x7f6e348849d2]
/usr/lib/libpython3.13.so.1.0(+0x284343) [0x7f6e34884343]
/usr/lib/libpython3.13.so.1.0(Py_RunMain+0x3fb) [0x7f6e3488248b]
/usr/lib/libpython3.13.so.1.0(Py_BytesMain+0x3b) [0x7f6e34839dcb]
/usr/lib/libc.so.6(+0x276b5) [0x7f6e344376b5]
/usr/lib/libc.so.6(__libc_start_main+0x89) [0x7f6e34437769]
python(_start+0x25) [0x55626d533045]
````
