### ISSUE TITLE
[Build] Linking fails to find protobuf related functions

### ISSUE THREAD

**Issue by jspkay** [microsoft/onnxruntime#23103]
### Describe the issue

I'm trying desperately to build onnxruntime as is, without any customization.
I've read that libprotobuf has some problems when compiling.

I have read that onnxruntime is not compatible with version >=26 of protobuf, so I installed 25.3 (in conda libprotobuf=4.25.3).
I am using conda and as #17904 suggests, I was careful to remove any other protobuf version on my miniconda directory to avoid mismatch in linking.

Still the build fails... Suggestions ? 

### Target platform

Linux x64

### Build script

./build.sh --build --parallel --skip_tests

### Error / output

```
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::FindHelper(std::basic_string_view<char, std::char_traits<char> >, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::FindHelper(unsigned long, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
- /usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnxruntime_perf_test.dir/build.make:309: onnxruntime_perf_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:3234: CMakeFiles/onnxruntime_perf_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::FindHelper(std::basic_string_view<char, std::char_traits<char> >, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::FindHelper(unsigned long, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnx_test_runner.dir/build.make:236: onnx_test_runner] Error 1
make[1]: *** [CMakeFiles/Makefile2:3123: CMakeFiles/onnx_test_runner.dir/all] Error 2
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::FindHelper(std::basic_string_view<char, std::char_traits<char> >, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::FindHelper(unsigned long, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:940: undefined reference to `google::protobuf::internal::UntypedMapBase::FindFromTree(unsigned int, google::protobuf::internal::VariantKey, absl::lts_20240722::container_internal::btree_iterator<absl::lts_20240722::container_internal::btree_node<absl::lts_20240722::container_internal::map_params<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> >, 256, false> >, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>&, std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*>*>*) const'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
/usr/bin/ld: libonnx_test_data_proto.a(tml.pb.cc.o): in function `google::protobuf::internal::KeyMapBase<unsigned long>::Resize(unsigned int)':
/home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h:1053: undefined reference to `google::protobuf::internal::UntypedMapBase::TransferTree(absl::lts_20240722::btree_map<google::protobuf::internal::VariantKey, google::protobuf::internal::NodeBase*, std::less<google::protobuf::internal::VariantKey>, google::protobuf::internal::MapAllocator<std::pair<google::protobuf::internal::VariantKey const, google::protobuf::internal::NodeBase*> > >*, google::protobuf::internal::VariantKey (*)(google::protobuf::internal::NodeBase*))'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnxruntime_test_all.dir/build.make:5215: onnxruntime_test_all] Error 1
make[1]: *** [CMakeFiles/Makefile2:2974: CMakeFiles/onnxruntime_test_all.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/user/build/onnxruntime/tools/ci_build/build.py", line 2998, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/build/onnxruntime/tools/ci_build/build.py", line 2888, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/build/onnxruntime/tools/ci_build/build.py", line 1739, in build_targets
    run_subprocess(cmd_args, env=env)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/user/build/onnxruntime/tools/ci_build/build.py", line 867, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/user/build/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
        cmd,
    ...<6 lines>...
        shell=shell,
    )
  File "/home/user/miniforge3/envs/onnxrt/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/user/miniforge3/envs/onnxrt/bin/cmake', '--build', '/home/user/build/onnxruntime/build/Linux/Debug', '--config', 'Debug', '--', '-j40']' returned non-zero exit status 2. ```

### Visual Studio Version

_No response_

### GCC / Compiler Version

_No response_

**Comment by snnn** [comment]
> I was careful to remove any other protobuf version on my miniconda director

But the log shows it still gets protobuf from /home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h

**Comment by jspkay** [comment]
Sure it does! I never said I don't want to use conda!!! 
What I meant is that I deleted any additional unrelated folder as suggested by #17904.

I tried multiple times to solve my problems, but I nevere managed. This thing is impossible to compile...
Also, why exactly do you need a python script to call cmake? Wasn't it easier to just properly setup cmake?

**Comment by snnn** [comment]
Yes, you may directly use cmake. You don't have to use the build.py.  However, the file /home/user/miniforge3/envs/onnxrt/include/google/protobuf/map.h was causing conflicts.  Would you be able to create a clean env without this file?
