### ISSUE TITLE
[BUG][CUDAProvider] No attribute with name:'activation'is defined

### ISSUE THREAD

**Issue by Cookiee235** [microsoft/onnxruntime#23119]
## Bug Report

Loading and optimizing the model with CUDA crashed! In comparison, it can run well when executing optimization on the CPU.

### The crash stack trace:

```
Traceback (most recent call last):
  File "test", line 7, in <module>
    optimized_model = optimizer.optimize_model(model_path, opt_level=1, use_gpu=True)  
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/transformers/optimizer.py", line 381, in optimize_model
    temp_model_path = optimize_by_onnxruntime(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/transformers/optimizer.py", line 206, in optimize_by_onnxruntime
    onnxruntime.InferenceSession(onnx_model, sess_options, providers=providers, **kwargs)
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/capi/onnxruntime_inference_collection.py", line 465, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/capi/onnxruntime_inference_collection.py", line 537, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /software/onnxruntime/onnxruntime/contrib_ops/cuda/fused_conv.cc:67 onnxruntime::contrib::cuda::FusedConv<T>::FusedConv(const onnxruntime::OpKernelInfo&) [with T = float] [ONNXRuntimeError] : 1 : FAIL : No attribute with name:'activation'is defined.
```

### To reproduce

1. Download model [here](https://github.com/Cookiee235/ModelZoo/blob/main/model_with_activation.onnx)
2. Run the test script:

```
from onnxruntime.transformers import optimizer

model_path = "model_with_activation.onnx"
optimized_model_path = f"./opt.onnx"
optimized_model = optimizer.optimize_model(model_path, opt_level=1, use_gpu=True) 
```

Notice:
1. use_gpu=True & opt_level >=1     -->  crash
2. use_gpu=False           --> run well
3. opt_level = 0             --> run well

### Platform

Linux

### OS Version

Ubuntu 12.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

5c1b7cc

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
This is an invalid model. It has a node using FusedConv, but the node does not have activation attribute.
See https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.FusedConv

**Comment by Cookiee235** [comment]
@tianleiwu Thanks for your explanation. I’m still a bit confused. If the FusedConv operator requires an activation attribute, why does the provided model pass validation (`onnx.checker.check_model()`) and execute inference successfully on the CPU? Additionally, why does the model run without any exception when optimizations are disabled (opt_level=0)?

**Comment by tianleiwu** [comment]
FusedConv is not operator in onnx domain. It is in com.microsoft domain.  `onnx.checker.check_model()` has no knowledge of operators in com.microsoft domain, so it might ignore it.

CPU has different implementation for activation. When activation is not defined, it falls back to Identity. https://github.com/microsoft/onnxruntime/blob/0981bbf4ca4af4d7216299f15de784f19ce6123a/onnxruntime/contrib_ops/cpu/fused_activation.cc#L10-L34
So the model can be handled by CPU provider.

**Comment by Cookiee235** [comment]
@tianleiwu Thanks for the clarification.

Is it possible to modify the CPU provider implementation to align it with the CPU behavior? Specifically, we could convert the default value of activation to Identity. This would ensure that both CPU and GPU exhibit the same behavior.

@tianleiwu Do you think these changes would be a valid solution? Thanks again!

**Comment by tianleiwu** [comment]
> Is it possible to modify the CPU provider implementation to align it with the CPU behavior? Specifically, we could convert the default value of activation to Identity. This would ensure that both CPU and GPU exhibit the same behavior.

Yes, it is possible to change CUDA code to align with CPU behavior on this, and also update the spec to mark the attribute to optional.
