### ISSUE TITLE
FuseReluClip Unexpected data type for Clip 'min' input of 11

### ISSUE THREAD

**Issue by Cookiee235** [microsoft/onnxruntime#23116]
### Describe the issue

The valid model which has been checked by the `onnx.checker.check_model(model)` statement crash when executing the inference unexpected.
The crash message is shown below:

### The Crash stacktrace
```
 Traceback (most recent call last):
  File "test.py", line 10, in <module>
    original_session = ort.InferenceSession(model_path)
  File "C:\software\conda\envs\OPTFuzz\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\software\conda\envs\OPTFuzz\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 491, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\optimizer\relu_clip_fusion.cc:77 onnxruntime::FuseReluClip::Apply Unexpected data type for Clip 'min' input of 11
```

#### Step 2: run the following script:
```
import onnx
import onnxruntime as ort

model_path = "model_with_clip.onnx"
model = onnx.load(model_path)
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))

original_session = ort.InferenceSession(model_path)

```

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

5c1b7cc

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
ORT doesn't support fp64 for the min/max. We typically support common production use-cases. Not sure there's any need to use fp64 for the min/max so I'd suggest changing those to be fp32.

**Comment by xadupre** [comment]
onnxruntime should support min/max for float64 in onnxruntime but the optimizer FuseReluClip is not (see line https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/optimizer/relu_clip_fusion.cc#L61). I wonder if we should fail on this case.

**Comment by skottmckay** [comment]
If the implementation has limited type support FuseReluClip::SatisfyCondition should be checking the input types.
