### ISSUE TITLE
RuntimeError: Assertion `false` failed: No Adapter From Version $20 for GridSample

### ISSUE THREAD

**Issue by jikechao** [microsoft/onnxruntime#23112]
### Describe the issue

Converting the model opset version failed. By checking the document about `GridSample`, I found that opset 20 is a valid version for `GridSample`.

```
Traceback (most recent call last):
  File "test.py", line 247, in <module>
    combine_models_random(seed_model, donor_model, position_flag='random')
  File "test.py", line 221, in combine_models_random
    donor_model = onnx.version_converter.convert_version(donor_model, 16)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/onnx/version_converter.py", line 37, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:73: adapter_lookup: Assertion `false` failed: No Adapter From Version $20 for GridSample
```

### To reproduce

```
import onnx
model = onnx.load("...")
new_model = onnx.version_converter.convert_version(model, 16)
```

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest-version

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by gramalingam** [comment]
Hi, do you have an example model to repro this? Thanks!
