### ISSUE TITLE
[Bug][CUDAExecutionProvider] INVALID_ARGUMENT : unsupported conv activation mode "Sigmoid"

### ISSUE THREAD

**Issue by Cookiee235** [microsoft/onnxruntime#23114]
## Bug Report

The following script run with providers=["CPUExecutionProvider "] successfully. However, inference on the cuda with providers=["CUDAExecutionProvider "] failed.

## Bug Report
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    original_session = ort.InferenceSession(model_path, providers=["CUDAExecutionProvider"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/capi/onnxruntime_inference_collection.py", line 465, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/software/onnxruntime/build/Linux/Release/onnxruntime/capi/onnxruntime_inference_collection.py", line 537, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /software/onnxruntime/onnxruntime/contrib_ops/cuda/fused_conv.cc:68 onnxruntime::contrib::cuda::FusedConv<T>::FusedConv(const onnxruntime::OpKernelInfo&) [with T = float] [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : unsupported conv activation mode "Sigmoid"
```

### To reproduce

```
import onnx
import onnxruntime as ort

model_path = "../res/onnx_res_1215/res_executions/4790.onnx"
model = onnx.load(model_path)
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))
print(ort.get_available_providers())
original_session = ort.InferenceSession(model_path, providers=["CUDAExecutionProvider"])  # CPUExecutionProvider run well!

```

### Urgency

It's an urgent issue due to the reference to multiple similar bugs.

- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "Tanh"
- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "HardSigmoid"
- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "LeakyRelu"
- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "Clip"
- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "Sigmoid"
- [ ] ERROR: 2 : INVALID_ARGUMENT : unsupported conv activation mode "Tanh"

### Platform

Linux

### OS Version

Ubuntu 12.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

5c1b7cc

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
Currently only Relu is supported in FusedConv:
https://github.com/microsoft/onnxruntime/blob/ae970681372e20c3df3f1b40bfb0ee06a02c39c8/onnxruntime/contrib_ops/cuda/fused_conv.cc#L415-L421

Need some code change to support other activations with mapping to cuDNN: 
* CUDNN_ACTIVATION_SIGMOID
* CUDNN_ACTIVATION_TANH
* CUDNN_ACTIVATION_SWISH
* CUDNN_ACTIVATION_CLIPPED_RELU
* CUDNN_ACTIVATION_ELU

**Comment by Cookiee235** [comment]
Thank you for your response. I understand now. I'll keep this issue open to track the fix for activations in cuDNN.
