### ISSUE TITLE
[Build] setup.py: With --build_wheel getting: "No such file or directory: 'VERSION_NUMBER' " - but VERSION_NUMBER file is present

### ISSUE THREAD

**Issue by tzimmer420** [microsoft/onnxruntime#23126]
### Describe the issue

No such file or directory: 'VERSION_NUMBER' - but VERSION_NUMBER file is present
When using --build_wheel

### Target platform

Windows

### Build script

build.bat --config RelWithDebInfo --cmake_generator "Visual Studio 17 2022" --build_wheel --build_shared_lib --parallel --skip_tests --target onnxruntime_perf_test --enable_wcos --use_winml --enable_pybind --use_dml --skip_submodule_sync

### Error / output

Build output:
Traceback (most recent call last):
  File "C:\_debug\hgsai\ort\wip\setup.py", line 638, in <module>
    with open("VERSION_NUMBER") as f:
         ~~~~^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION_NUMBER'
Traceback (most recent call last):
  File "C:\_debug\hgsai\ort\wip\\tools\ci_build\build.py", line 2951, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\_debug\hgsai\ort\wip\\tools\ci_build\build.py", line 2873, in main
    build_python_wheel(
    ~~~~~~~~~~~~~~~~~~^
        source_dir,
        ^^^^^^^^^^^
    ...<23 lines>...
        enable_rocm_profiling=args.enable_rocm_profiling,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\_debug\hgsai\ort\wip\\tools\ci_build\build.py", line 2276, in build_python_wheel
    run_subprocess(args, cwd=cwd)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\_debug\hgsai\ort\wip\\tools\ci_build\build.py", line 867, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\_debug\hgsai\ort\wip\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
        cmd,
    ...<6 lines>...
        shell=shell,
    )
  File "C:\Program Files\Python313\Lib\subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Python313\\python.exe', 'C:\\_debug\\hgsai\\ort\\wip\\setup.py', 'bdist_wheel', '--wheel_name_suffix=directml']' returned non-zero exit status 1.

### Visual Studio Version

_No response_

### GCC / Compiler Version

_No response_

**Comment by fdwr** [comment]
> build.bat --config RelWithDebInfo --cmake_generator "Visual Studio 17 2022" --build_wheel --build_shared_lib --parallel --skip_tests --target onnxruntime_perf_test --enable_wcos --use_winml --enable_pybind --use_dm --skip_submodule_sync

`--use_dm` -> `--use_dml`?

**Comment by tzimmer420** [comment]
Yes, it’s –use_dml.
