### ISSUE TITLE
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node.

### ISSUE THREAD

**Issue by kurzacz** [microsoft/onnxruntime#2316]
**Describe the bug**
I'm trying to convert Mask RCNN model into ONNX, but while using your dedicated script I'm getting the following error:
```
[E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running Squeeze node. Name:'TFNodes/ROI/strided_slice_13__410' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,6000}
Stacktrace:

Traceback (most recent call last):
  File "onnx_converter.py", line 748, in <module>
    "input_image_meta": image_metas.astype(np.float32)})
  File "/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'TFNodes/ROI/strided_slice_13__410' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,6000}
Stacktrace:
```
(no more output after `Stacktrace:`)

**Urgency**
none

**System information**
- OS Platform and Distribution: Ubuntu 18.04.3 LTS
- ONNX Runtime installed from: binary (pip)
- ONNX Runtime version: 1.0.0
- Python version: 3.6.8
- Visual Studio version (if applicable): ---
- GCC/Compiler version (if compiling from source): ---
- CUDA/cuDNN version: --- (not using GPU)
- GPU model and memory: --- (not using GPU)

**To Reproduce**

1. Pull matterport/Mask_RCNN
`$ git pull https://github.com/matterport/Mask_RCNN`

2. Download model and dataset - follow instructions on Mask_RCNN/samples/balloon:
https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon#installation

3. `$ cd Mask_RCNN/samples/balloon`

4. Follow instruction for converting Mask RCNN models with `mask_rcnn.py` script:
https://github.com/onnx/keras-onnx/tree/master/applications/mask_rcnn

5. Modify `mask_rcnn.py` script:
`(29) COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_balloon.h5")`

```
(58) from balloon import BalloonConfig
(59) config = BalloonConfig()
(60) config.display()
```

6. Run conversion script:
`$ Mask_RCNN/samples/balloon$ python onnx_converter.py dataset/val/3800636873_ace2c2795f_b.jpg`

**Expected behavior**
I expected to have model transformed into ONNX model.

**Full output**
```
$ python onnx_converter.py dataset/val/3800636873_ace2c2795f_b.jpg
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           balloon
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001


WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1919: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:341: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:399: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:423: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:720: The name tf.sets.set_intersection is deprecated. Please use tf.sets.intersection instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:722: The name tf.sparse_tensor_to_dense is deprecated. Please use tf.sparse.to_dense instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:772: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2019-11-04 21:45:03.564681: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394580000 Hz
2019-11-04 21:45:03.565579: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xff9ca60 executing computations on platform Host. Devices:
2019-11-04 21:45:03.565606: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-04 21:45:05.674231: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-11-04 21:45:17.709744960 [E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running Squeeze node. Name:'TFNodes/ROI/strided_slice_13__410' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,6000}
Stacktrace:

Traceback (most recent call last):
  File "onnx_converter.py", line 748, in <module>
    "input_image_meta": image_metas.astype(np.float32)})
  File "/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'TFNodes/ROI/strided_slice_13__410' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,6000}
Stacktrace:

```

**Additional context**
I used model described in Mask RCNN tutorial:
https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46
For ONNX training reasons, I haven't modified balloon splash model.

**Comment by pranavsharma** [comment]
@jiafatom can you take a look? Might be a conversion issue?

**Comment by jiafatom** [comment]
@kurzacz We have included mask-rcnn conversion in keras-onnx converter nightly build, see [here](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_mask_rcnn.py). It is running smoothly, can you have a try?

**Comment by kurzacz** [comment]
Thank you for you attention.
I pulled whole project keras-onnx and ran your test case. It has been passed as you see below:

```
/test_mask_rcnn.py

/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:95: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:98: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:102: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.


Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                93
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           coco
NUM_CLASSES                    81
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001


WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1919: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:2018: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:399: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:423: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:720: The name tf.sets.set_intersection is deprecated. Please use tf.sets.intersection instead.

WARNING:tensorflow:From /home/asmox/AppDev/testing/venv-python3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:772: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2019-11-06 11:10:00.621574: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394625000 Hz
2019-11-06 11:10:00.622682: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xf157c70 executing computations on platform Host. Devices:
2019-11-06 11:10:00.622797: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-06 11:10:03.058215: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
ROI/packed_2 can be converted, fall back to tf2onnx
WARNING:tensorflow:From /home/asmox/AppDev/testing/keras-onnx/keras2onnx/subgraph.py:156: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
The layer <keras.layers.core.Lambda object at 0x7fdd07d8de10> doesn't have a specific converter, fall back.
rpn_model/lambda_1/Reshape can be converted, fall back to tf2onnx
The layer <keras.layers.core.Lambda object at 0x7fdd07d8de10> doesn't have a specific converter, fall back.
rpn_model_1/rpn_class_xxx/truediv can be converted, fall back to tf2onnx
The layer <keras.layers.core.Lambda object at 0x7fdd07d8de10> doesn't have a specific converter, fall back.
rpn_model_2/rpn_class_xxx/truediv can be converted, fall back to tf2onnx
The layer <keras.layers.core.Lambda object at 0x7fdd07d8de10> doesn't have a specific converter, fall back.
rpn_model_3/rpn_class_xxx/truediv can be converted, fall back to tf2onnx
The layer <keras.layers.core.Lambda object at 0x7fdd07d8de10> doesn't have a specific converter, fall back.
rpn_model_4/rpn_class_xxx/truediv can be converted, fall back to tf2onnx
pool_squeeze/Squeeze_1 can be converted, fall back to tf2onnx
rpn_class_raw/bias can be converted, fall back to tf2onnx
rpn_bbox_pred/bias can be converted, fall back to tf2onnx
rpn_class_raw/kernel can be converted, fall back to tf2onnx
rpn_bbox_pred/kernel can be converted, fall back to tf2onnx
rpn_conv_shared/bias can be converted, fall back to tf2onnx
rpn_conv_shared/kernel can be converted, fall back to tf2onnx
roi_align_classifier/Reshape can be converted, fall back to tf2onnx
roi_align_mask/Reshape can be converted, fall back to tf2onnx
lambda_3/strided_slice can be converted, fall back to tf2onnx
.
----------------------------------------------------------------------
Ran 1 test in 71.100s

OK
```

Those positive results encouraged me to try _mask_rcnn_ package from keras-onnx. I have also received positive results after some specific modifications related to source files of model and array of results' labels.

It's quite strange and I'm making further investigations about difference between files straight from your repository and code copy I joined to my project.
https://www.diffchecker.com/YSQH4xwJ

But, to sum up, it looks the problem doesn't lie within your repository. I would keep this issue open for few days more when I finally find the source of problem.

Thank you.

**Comment by WeiyiLi** [comment]
Hi, I got very similar error when I use onnx simplier to convert the onnx model. My error message is 

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : `RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 2. shape={2,20,128}`
Hopefully someone can find the solution. Thank you!

**Comment by jiafatom** [comment]
> Hi, I got very similar error when I use onnx simplier to convert the onnx model. My error message is
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:47 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 2. shape={2,20,128}
> Hopefully someone can find the solution. Thank you!

Where did you get the original onnx model? If it is from model zoo, then it is converted from pytorch model. Can the original model run? If you convert using keras-onnx, then please check my previous answer that we have this conversion in our nightly build.
