### ISSUE TITLE
[BUG] A model crashes on squeeze op

### ISSUE THREAD

**Issue by daquexian** [microsoft/onnxruntime#2429]
**Describe the bug**
The following model crashes

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- ONNX Runtime installed from (source or binary): PyPI
- ONNX Runtime version: 1.0.0
- Python version: 3.7
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
Use the following model:
https://drive.google.com/open?id=1BqzIynJNXv48gL1LOwfkpFvydKLqGD9U

Error message:
```
>>> sess.run(outputs, {"input": np.array(np.random.rand(2,3,512,512), dtype=np.float32)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daquexian/.local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/squeeze.h:33 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const onnxruntime::TensorShape&) input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 2. shape={2,20,128}
Stacktrace:
```

**Expected behavior**
The model works fine

**Additional context**
Related issue: https://github.com/daquexian/onnx-simplifier/issues/33

**Comment by daquexian** [comment]
It is not a bug of onnx runtime. https://github.com/daquexian/onnx-simplifier/issues/33#issuecomment-555816147
