### ISSUE TITLE
failed to start inference session with ShapeInferenceError

### ISSUE THREAD

**Issue by schyun9212** [microsoft/onnxruntime#2840]
**Describe the bug**
I'm trying to export maskrcnn-benchmark PyTorch model using torch.onnx.export.  But when I create a session to validate my model using onnxruntime.InferenceSession, I met ShapeInferenceError. How can I solve this problem?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04.3 LTS
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.1.0
- Python version: 3.7.6
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GeForce RTX 2080 Ti

**To Reproduce**

```python
import onnx
import onnxruntime as ort

model = onnx.load(MODEL_PATH)
onnx.checker.check_model(model)

ort_session = ort.InferenceSession(MODEL_PATH) # <--- Fail: [ONNXRuntimeError] : 1 : FAIL : Node () Op (ConstantOfShape) [ShapeInferenceError] Invalid shape value: 0
```
**Expected behavior**
```bash
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Traceback (most recent call last):
  File "test_onnx.py", line 14, in <module>
    ort_session = ort.InferenceSession(MODEL_PATH)
  File "/home/jade/.pyenv/versions/maskrcnn-tracing-latest/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/jade/.pyenv/versions/maskrcnn-tracing-latest/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node () Op (ConstantOfShape) [ShapeInferenceError] Invalid shape value: 0
```

**Additional context**
[This is my model](https://drive.google.com/file/d/11YRxdPVdfTGn9n9FxDfMxdXisfh4qkec/view?usp=sharing)

**Comment by schyun9212** [comment]
This issue occurred during the conversion process when the shape became zero after Resize.

**Comment by mrlzla** [comment]
Anyway how to fix the problem?
