### ISSUE TITLE
Jetson nano - building from source - problem 

### ISSUE THREAD

**Issue by Kammmil** [microsoft/onnxruntime#2860]
Hey guys,
can anyone help me out,
i am trying to build onnxruntime from source on jetson nano, but everytime i got an error (look below)
and i have no idea, where i am making mistake or how to fix it.
It would be really nice of you, if you could tell me how to make it work, if possible please explain it step by step :)
Thanks a lot for help :)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetson Nano, 
- ONNX Runtime installed from (source or binary): trying to build from source
- ONNX Runtime version: 1.1.0
- Python version: 3.6.9
- Visual Studio version (if applicable): No
- GCC/Compiler version (if compiling from source): cmake version: 3.13.0/3.13.4/3.16.2
- CUDA/cuDNN version: 10.0
- GPU model and memory: Jetson Nano

**To Reproduce**
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
./build.sh --use_cuda --cudnn_home /usr/local/cuda-10.0 --cuda_home /usr/local/cuda-10.0

**Expected behavior**
successful build 

**Additional context**
[ 25%] Building CXX object CMakeFiles/onnxruntime_util.dir/home/kamil/projects/onnxruntime/onnxruntime/core/util/math_cpu.cc.o
In file included from /home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/Core:313:0,
                 from /home/kamil/projects/onnxruntime/onnxruntime/core/util/math_cpuonly.h:31,
                 from /home/kamil/projects/onnxruntime/onnxruntime/core/util/math_cpu.cc:20:
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function ‘void Eigen::internal::gebp_traits<float, float, false, false, 4, 0>::updateRhs(const RhsScalar*, Eigen::internal::gebp_traits<float, float, false, false, 4, 0>::RhsPacketx4&) const’:
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1079:55: error: unused parameter ‘b’ [-Werror=unused-parameter]
   EIGEN_STRONG_INLINE void updateRhs(const RhsScalar* b, RhsPacketx4& dest) const
                                                       ^
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1079:71: error: unused parameter ‘dest’ [-Werror=unused-parameter]
 EIGEN_STRONG_INLINE void updateRhs(const RhsScalar* b, RhsPacketx4& dest) const
                                                                     ^~~~
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h: In member function ‘void Eigen::internal::gebp_traits<double, double, false, false, 4>::updateRhs(const RhsScalar*, Eigen::internal::gebp_traits<double, double, false, false, 4>::RhsPacketx4&) const’:
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1148:55: error: unused parameter ‘b’ [-Werror=unused-parameter]
   EIGEN_STRONG_INLINE void updateRhs(const RhsScalar* b, RhsPacketx4& dest) const
                                                       ^
/home/kamil/projects/onnxruntime/cmake/external/eigen/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1148:71: error: unused parameter ‘dest’ [-Werror=unused-parameter]
 EIGEN_STRONG_INLINE void updateRhs(const RhsScalar* b, RhsPacketx4& dest) const
                                                                     ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_util.dir/build.make:75: recipe for target 'CMakeFiles/onnxruntime_util.dir/home/kamil/projects/onnxruntime/onnxruntime/core/util/math_cpu.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_util.dir/home/kamil/projects/onnxruntime/onnxruntime/core/util/math_cpu.cc.o] Error 1
CMakeFiles/Makefile2:609: recipe for target 'CMakeFiles/onnxruntime_util.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_util.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 983, in <module>
    sys.exit(main())
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 922, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 200, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/kamil/projects/onnxruntime/build/Linux/Debug', '--config', 'Debug']' returned non-zero exit status 2.

**Comment by jywu-msft** [comment]
follow the instructions at
https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387

**Comment by Kammmil** [comment]
@jywu-msft 
Hey man,
thanks for the link,
but i still got error:
[ 69%] Building CXX object external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o
In file included from /home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt.hpp:28:0,
                 from /home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/ImporterContext.hpp:25,
                 from /home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.hpp:26,
                 from /home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.cpp:23:
/home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.cpp: In member function ‘virtual onnx2trt::Status onnx2trt::ModelImporter::importModel(const onnx::ModelProto&, uint32_t, const onnxTensorDescriptorV1*)’:
/home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/ModelImporter.cpp:513:36: error: ‘class nvinfer1::INetworkDefinition’ has no member named ‘hasImplicitBatchDimension’
   ASSERT(!_importer_ctx.network()->hasImplicitBatchDimension() &&
                                    ^
/home/kamil/projects/onnxruntime/cmake/external/onnx-tensorrt/Status.hpp:34:11: note: in definition of macro ‘ASSERT’
     if( !(condition) ) { \
           ^~~~~~~~~
external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/build.make:75: recipe for target 'external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o' failed
make[2]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o] Error 1
CMakeFiles/Makefile2:2333: recipe for target 'external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/all' failed
make[1]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 1043, in <module>
    sys.exit(main())
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 981, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 456, in build_targets
    run_subprocess(cmd_args)
  File "/home/kamil/projects/onnxruntime/tools/ci_build/build.py", line 196, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/kamil/projects/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.

**Comment by Kammmil** [comment]
- NVIDIA Jetson NANO/TX1
   * Jetpack UNKNOWN [L4T 32.2.3]
   * CUDA GPU architecture 5.3
 - Libraries:
   * CUDA 10.0.326
   * cuDNN 7.5.0.56-1+cuda10.0
   * TensorRT 5.1.6.1-1+cuda10.0
   * Visionworks 1.6.0.500n
   * OpenCV 3.4.8 compiled CUDA: YES
 - Jetson Performance: inactive

**Comment by jywu-msft** [comment]
You'll need TensorRT 6.x  (this has been the case since Onnxruntime 1.0)

see the tested configuration in the instructions

    * Name:           NVIDIA Jetson NANO/TX1                                                                                                           e-mail: raffaello@rnext.it
    * Type:           NANO/TX1
    * Jetpack:        4.3 [L4T 32.3.1]
    * GPU-Arch:       5.3
    * SN:             0323216129961
  - Libraries:
    * CUDA:           10.0.326
    * cuDNN:          7.6.3.28-1+cuda10.0
    * TensorRT:       6.0.1.10-1+cuda10.0

**Comment by Kammmil** [comment]
You can close it, you need tensorRT >= 6 for it to be working.
Thanks
