### ISSUE TITLE
Support for grid_sample layer in both ONNX and ORT

### ISSUE THREAD

**Issue by xgirones** [microsoft/onnxruntime#2962]
**Is your feature request related to a problem? Please describe.**

Need support for the PyTorch `grid_sample` operator in both ONNX and ORT in order to be able to run [Spatial Transformer Networks](https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html) with ORT. 

See [ONNX and grid_sample layer](https://github.com/pytorch/pytorch/issues/27212#issue-501445631) and [Spatial transformer operator](https://github.com/onnx/onnx/issues/2383#issue-501452260) issues on the PyTorch and ONNX repositories.

**Describe the solution you'd like**
To be able to run models that employ the PyTorch [grid_sample](https://pytorch.org/docs/stable/nn.functional.html#grid-sample) operator.

**Describe alternatives you've considered**
I do not think there is currently an alternative for it.

**Comment by hariharans29** [comment]
CC: @spandantiwari

**Comment by olokobayusuf** [comment]
Any word on this?

**Comment by faxu** [comment]
Please follow up on this issue- https://github.com/onnx/onnx/issues/883 It needs to be added to the ONNX spec, otherwise you can consider writing and registering a custom op.

**Comment by CosmicHunter** [comment]
Is there any update on how to convert the model to onnx with grid sampler?
I am having trouble, getting the error like this
~~~
 UserWarning: ONNX export failed on ATen operator grid_sampler because torch.onnx.symbolic_opset9.grid_sampler does not exist
  .format(op_name, opset_version, op_name))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-134-0350cc891688> in <module>()
----> 1 torch.onnx.export(models_module, (dummy_input,dummy_text), "test1.onnx", verbose=True)

7 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

RuntimeError: Exporting the operator grid_sampler to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.
~~~

**Comment by pustar** [comment]
+1

**Comment by CosmicHunter** [comment]
any update on this?

**Comment by PkuRainBow** [comment]
+1

**Comment by dazaier** [comment]
+1

**Comment by yingsiq** [comment]
+1

**Comment by RunningLeon** [comment]
Do we have any solution by now?  thx.

**Comment by yetaibing** [comment]
I encounted the same issue, do we have any solustions for this?
It is a bit long time from someone firstly metioned this issue.
any update??

**Comment by AmemiyaYuko** [comment]
any update?

**Comment by tejal567** [comment]
Much needed feature! Any update?

**Comment by timiil** [comment]
any update for support grid_sampler ?

```
System.InvalidOperationException: Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] Load model from D:\code\ml\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\bin\Debug\net5\../../../assets\Model\mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_slock1_cpu.onnx failed:Fatal error: grid_sampler is not a registered function/op
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)

```

**Comment by trantuankhoi** [comment]
any update?

**Comment by dawei03896** [comment]
any update?
