### ISSUE TITLE
Release source distribution is unusable

### ISSUE THREAD

**Issue by vigsterkr** [microsoft/onnxruntime#3288]
With released source (at least v1.2.0) it is not possible to build the project, since it's not a git repo:
```
./build.sh --config RelWithDebInfo --build_shared_lib --parallel
2020-03-21 07:50:41,877 Build [DEBUG] - Defaulting to running update, build [and test for native builds].
2020-03-21 07:50:41,877 Build [INFO] - Build started
2020-03-21 07:50:41,878 Build [DEBUG] - Running subprocess in '/home/wiking/onnxruntime-1.2.0'
['git', 'submodule', 'sync', '--recursive']
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/wiking/onnxruntime-1.2.0/tools/ci_build/build.py", line 1065, in <module>
    sys.exit(main())
  File "/home/wiking/onnxruntime-1.2.0/tools/ci_build/build.py", line 984, in main
    update_submodules(source_dir)
  File "/home/wiking/onnxruntime-1.2.0/tools/ci_build/build.py", line 217, in update_submodules
    run_subprocess(["git", "submodule", "sync", "--recursive"], cwd=source_dir)
  File "/home/wiking/onnxruntime-1.2.0/tools/ci_build/build.py", line 212, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128.
```

**Comment by pranavsharma** [comment]
This will work - ```git clone --single-branch --branch rel-1.2.0 https://github.com/microsoft/onnxruntime.git```

**Comment by vigsterkr** [comment]
@pranavsharma :) thnx, i know how to use git. this was not the point of this issue. a source release should be self-contained i.e. one expects that git (or any other source control system, let along connection to the internet) is not required to build the project...

**Comment by pranavsharma** [comment]
That's right. This is an open source project. Given that checking out the source using the release branch works, this is not our highest priority. Contributions are welcome though.

**Comment by hnuhchen** [comment]
hello, @vigsterkr @pranavsharma , did you sove the problem? I have the same problem now. 
I want to install onnxruntime-1.7.0 from source code in ZIP format(Because my device cannot connect to the network). It told me the error about git. So can you tell me how to solve the problem? 

Thank you.
