### ISSUE TITLE
Build ARM32v7 Error: /code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp:259:28: error: ‘nearbyintf’ is not a member of ‘std’

### ISSUE THREAD

**Issue by KodeWorker** [microsoft/onnxruntime#3565]
**Describe the bug**
I tried to cross compile for ARM with Docker, following the instructions on [this page](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#arm-32v7)

It failed at step 4. Run docker build
```
sudo docker build -t onnxruntime-arm32v7 -f Dockerfile.arm32v7 .
```

The error messages:
```
...
[  2%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o
/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp: In function ‘void MlasQuantizeLinear(const float*, OutputType*, size_t, float, OutputType)’:
/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp:259:28: error: ‘nearbyintf’ is not a member of ‘std’
         float FloatValue = std::nearbyintf(Input[n] / Scale) + float(ZeroPoint);
                            ^~~
CMakeFiles/onnxruntime_mlas.dir/build.make:231: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o' failed
make[2]: *** [CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1114, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 1038, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/code/onnxruntime/tools/ci_build/build.py", line 497, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 218, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master branch from git
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 7.5.0

**Comment by tracysh** [comment]
@KodeWorker Sorry about the build break, the fix for this has been merged into master.

**Comment by KodeWorker** [comment]
@tracysh Thank you for the reply. But this issue still ocurrs.

```
[  2%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o
/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp: In function ‘void MlasQuantizeLinear(const float*, OutputType*, size_t, float, OutputType)’:
/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp:259:28: error: ‘nearbyintf’ is not a member of ‘std’
         float FloatValue = std::nearbyintf(Input[n] / Scale) + float(ZeroPoint);
                            ^~~
CMakeFiles/onnxruntime_mlas.dir/build.make:231: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o' failed
make[2]: *** [CMakeFiles/onnxruntime_mlas.dir/code/onnxruntime/onnxruntime/core/mlas/lib/quantize.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1114, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 1038, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/code/onnxruntime/tools/ci_build/build.py", line 497, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 218, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2
The command '/bin/sh -c ./build.sh ${BUILDARGS} --update --build' returned a non-zero code: 1
```

**Comment by tracysh** [comment]
@KodeWorker I just tried that dockerfile on a clean system and my build has gotten past the MLAS steps. Any chance your build didn't do a clean fetch and needs to do a fetch from master of my change? Can you check mlasi.h to see if it has the #include <cmath> change?

**Comment by KodeWorker** [comment]
@tracysh My bad. I forgot to remove cache.
It's working now. Thanks a lot :)
