### ISSUE TITLE
Install fail in python3.8 (onnx has same error in python3.8 and does not support python3.8)

### ISSUE THREAD

**Issue by alexandreCameron** [microsoft/onnxruntime#3810]
**Describe the bug**
Install of package with python 3.8 fail by not with python 3.7

Important: onnx is available in python 3.7 and not python 3.8 https://github.com/onnx/onnx/issues/2734

Same error happened for onnx in python 3.8

**Urgency**

Current version of onnxruntime cannot be use in production for python3.8

**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04 LTS
- ONNX Runtime installed: onnxruntime-1.2.0-cp38-cp38-manylinux1_x86_64.whl 
- ONNX Runtime version:  1.2.0
- Python version: 3.8
- cmake version 3.17.2

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
No error are warning message at install.

**Logs**

```bash
pip install onnxruntime-1.2.0-cp38-cp38-manylinux1_x86_64.whl 
Processing ./onnxruntime-1.2.0-cp38-cp38-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.18.0 in /my_root/onnx_venv/lib/python3.8/site-packages (from onnxruntime==1.2.0) (1.18.2)
Collecting onnx>=1.2.3
  Using cached onnx-1.6.0.tar.gz (3.1 MB)
Requirement already satisfied: protobuf in /my_root/onnx_venv/lib/python3.8/site-packages (from onnx>=1.2.3->onnxruntime==1.2.0) (3.11.3)
Requirement already satisfied: six in /my_root/onnx_venv/lib/python3.8/site-packages (from onnx>=1.2.3->onnxruntime==1.2.0) (1.14.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /my_root/onnx_venv/lib/python3.8/site-packages (from onnx>=1.2.3->onnxruntime==1.2.0) (3.7.4.2)
Requirement already satisfied: setuptools in /my_root/onnx_venv/lib/python3.8/site-packages (from protobuf->onnx>=1.2.3->onnxruntime==1.2.0) (39.0.1)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /my_root/onnx_venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6a1kxsaw
       cwd: /tmp/pip-install-gdwnewcu/onnx/
  Complete output (210 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0")
  Generated: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Generated: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  CMake Warning at CMakeLists.txt:394 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11"
    (requested version 2.2) with any of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  --
  -- ******** Summary ********
  --   CMake version         : 3.17.2
  --   CMake command         : /home/alex/Programs/cmake/cmake-3.17.2-Linux-x86_64/bin/cmake
  --   System                : Linux
  --   C++ compiler          : /usr/bin/c++
  --   C++ compiler version  : 7.5.0
  --   CXX flags             :  -Wnon-virtual-dtor
  --   Build type            : Release
  --   Compile definitions   :
  --   CMAKE_PREFIX_PATH     :
  --   CMAKE_INSTALL_PREFIX  : /usr/local
  --   CMAKE_MODULE_PATH     :
  --
  --   ONNX version          : 1.6.0
  --   ONNX NAMESPACE        : onnx
  --   ONNX_BUILD_TESTS      : OFF
  --   ONNX_BUILD_BENCHMARKS : OFF
  --   ONNX_USE_LITE_PROTO   : OFF
  --   ONNXIFI_DUMMY_BACKEND : OFF
  --   ONNXIFI_ENABLE_EXT    : OFF
  --
  --   Protobuf compiler     : /usr/bin/protoc
  --   Protobuf includes     : /usr/include
  --   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
  --   BUILD_ONNX_PYTHON     : ON
  --     Python version      :
  --     Python executable   : /my_root/onnx_venv/bin/python3.8
  --     Python includes     : /usr/include/python3.8
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_dummy
  Scanning dependencies of target onnxifi_loader
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  3%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  /tmp/pip-install-gdwnewcu/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
  /tmp/pip-install-gdwnewcu/onnx/onnx/onnxifi_dummy.c:173:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
             *function = &onnxGetExtensionFunctionAddress;
                       ^
  /tmp/pip-install-gdwnewcu/onnx/onnx/onnxifi_dummy.c:176:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
             *function = &onnxSetIOAndRunGraph;
                       ^
  Processing /tmp/pip-install-gdwnewcu/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Writing /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
  generating /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  6%] Linking C static library libonnxifi_loader.a
  [  8%] Running C++ protocol buffer compiler on /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  [  8%] Built target onnxifi_loader
  Scanning dependencies of target onnxifi_wrapper
  [  9%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
  [ 11%] Linking C shared library libonnxifi_dummy.so
  [ 11%] Built target onnxifi_dummy
  [ 13%] Linking C shared module libonnxifi.so
  Writing mypy to onnx/onnx_ml_pb2.pyi
  [ 13%] Built target onnxifi_wrapper
  [ 13%] Built target gen_onnx_proto
  [ 14%] Running gen_proto.py on onnx/onnx-operators.in.proto
  Processing /tmp/pip-install-gdwnewcu/onnx/onnx/onnx-operators.in.proto
  Writing /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
  generating /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  [ 16%] Running C++ protocol buffer compiler on /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  Scanning dependencies of target onnx_proto
  [ 18%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
  [ 19%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
  [ 21%] Linking CXX static library libonnx_proto.a
  [ 24%] Built target onnx_proto
  Scanning dependencies of target onnx
  [ 26%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
  [ 27%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
  [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
  [ 31%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
  [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
  [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
  [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
  [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
  [ 39%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
  [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
  [ 42%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
  [ 44%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
  [ 45%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
  [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
  [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
  [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
  [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
  [ 54%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
  [ 55%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
  [ 57%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
  [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
  [ 60%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
  [ 62%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
  [ 63%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
  [ 65%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
  [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
  [ 68%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
  [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
  [ 72%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
  [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
  [ 75%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
  [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
  [ 78%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
  [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
  [ 81%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
  [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
  [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/optimizer/optimize.cc.o
  [ 86%] Building CXX object CMakeFiles/onnx.dir/onnx/optimizer/pass.cc.o
  [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/optimizer/pass_manager.cc.o
  [ 90%] Building CXX object CMakeFiles/onnx.dir/onnx/optimizer/pass_registry.cc.o
  [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
  [ 93%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
  [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
  [ 96%] Linking CXX static library libonnx.a
  [ 96%] Built target onnx
  Scanning dependencies of target onnx_cpp2py_export
  [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
  In file included from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/pytypes.h:12:0,
                   from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/cast.h:13,
                   from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/attr.h:13,
                   from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/pybind11.h:44,
                   from /tmp/pip-install-gdwnewcu/onnx/onnx/cpp2py_export.cc:1:
  /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  CMakeFiles/onnx_cpp2py_export.dir/build.make:82: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o' failed
  make[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o] Error 1
  CMakeFiles/Makefile2:243: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
  make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
  Makefile:149: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 315, in <module>
      setuptools.setup(
    File "/my_root/onnx_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/my_root/onnx_venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 209, in run
      self.run_command('cmake_build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 203, in run
      subprocess.check_call(build_args)
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '16']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx, onnxruntime
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /my_root/onnx_venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7huvzfc5/install-record.txt --single-version-externally-managed --compile --install-headers /my_root/onnx_venv/include/site/python3.8/onnx
         cwd: /tmp/pip-install-gdwnewcu/onnx/
    Complete output (116 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    Generated: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    CMake Warning at CMakeLists.txt:394 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    --
    -- ******** Summary ********
    --   CMake version         : 3.17.2
    --   CMake command         : /home/alex/Programs/cmake/cmake-3.17.2-Linux-x86_64/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 7.5.0
    --   CXX flags             :  -Wnon-virtual-dtor
    --   Build type            : Release
    --   Compile definitions   :
    --   CMAKE_PREFIX_PATH     :
    --   CMAKE_INSTALL_PREFIX  : /usr/local
    --   CMAKE_MODULE_PATH     :
    --
    --   ONNX version          : 1.6.0
    --   ONNX NAMESPACE        : onnx
    --   ONNX_BUILD_TESTS      : OFF
    --   ONNX_BUILD_BENCHMARKS : OFF
    --   ONNX_USE_LITE_PROTO   : OFF
    --   ONNXIFI_DUMMY_BACKEND : OFF
    --   ONNXIFI_ENABLE_EXT    : OFF
    --
    --   Protobuf compiler     : /usr/bin/protoc
    --   Protobuf includes     : /usr/include
    --   Protobuf libraries    : /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread
    --   BUILD_ONNX_PYTHON     : ON
    --     Python version      :
    --     Python executable   : /my_root/onnx_venv/bin/python3.8
    --     Python includes     : /usr/include/python3.8
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-gdwnewcu/onnx/.setuptools-cmake-build
    [  3%] Built target gen_onnx_proto
    [  6%] Built target onnxifi_loader
    [  9%] Built target onnxifi_dummy
    [ 13%] Built target onnxifi_wrapper
    [ 24%] Built target onnx_proto
    [ 96%] Built target onnx
    [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
    In file included from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/pytypes.h:12:0,
                     from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/cast.h:13,
                     from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/attr.h:13,
                     from /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/pybind11.h:44,
                     from /tmp/pip-install-gdwnewcu/onnx/onnx/cpp2py_export.cc:1:
    /tmp/pip-install-gdwnewcu/onnx/third_party/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    CMakeFiles/onnx_cpp2py_export.dir/build.make:82: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o' failed
    make[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o] Error 1
    CMakeFiles/Makefile2:243: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 315, in <module>
        setuptools.setup(
      File "/my_root/onnx_venv/lib/python3.8/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/my_root/onnx_venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 209, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-gdwnewcu/onnx/setup.py", line 203, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '16']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /my_root/onnx_venv/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gdwnewcu/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7huvzfc5/install-record.txt --single-version-externally-managed --compile --install-headers /my_root/onnx_venv/include/site/python3.8/onnx Check the logs for full command output.
```

**Comment by snnn** [comment]
Please report it to https://github.com/onnx/onnx. The failure happens when installing ONNX python package, not onnxruntime.

**Comment by snnn** [comment]
I believe both ONNX and onnxruntime supports python 3.8. The only problem is: ONNX didn't provide a prebuilt package for it.

**Comment by alexandreCameron** [comment]
@snnn  : https://github.com/microsoft/onnxruntime/blob/master/README.md#api-documentation indicates that supported python version are: 3.5, 3.6 and 3.7

I did not find any indication that onnx supports python 3.8

**Comment by alexandreCameron** [comment]
Onnx v1.7.0 release today is compatible with python 3.8 . With this new version of onnx, I did not get the problem when installing onnxruntime
