### ISSUE TITLE
NuGet package onnxruntime.dll error

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#4009]
**Describe the bug**
I have installed OnnxRuntime for C# using the NuGet package manager.  I installed the GPU version.  When I try to run the code, I get: Unable to load DLL 'onnxruntime.dll': The specified module could not be found.

I look at the output directory and there IS an onnxruntime.dll file there.

What I noticed when I first ran my program is that this dialogue came up:
![image](https://user-images.githubusercontent.com/45402633/82509428-dfb34200-9ad5-11ea-915f-6cd7e6b70618.png)

I clicked the first option (Download Source and Continue Debugging).  

This seemed to create:
![image](https://user-images.githubusercontent.com/45402633/82510118-c7442700-9ad7-11ea-92fc-fe769f05a76c.png)

However I then get the error shown above.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- ONNX Runtime version: 1.3.0
- Visual Studio version (if applicable): Community 2019
- CUDA/cuDNN version: 10.1/7.6

**Comment by snnn** [comment]
Please be sure that you've added the CUDA and CUDNN dlls into your PATH. 
A better solution is: copy these files into the same dir of the onnxruntime.dll that you're loading.

**Comment by solarflarefx** [comment]
@snnn Thanks for the prompt reply.

I believe I do have these in the environment variables:
![image](https://user-images.githubusercontent.com/45402633/82512758-fe6a0680-9ade-11ea-9403-5a939426e4e5.png)

![image](https://user-images.githubusercontent.com/45402633/82512786-1a6da800-9adf-11ea-928d-17ba9687d6dd.png)

![image](https://user-images.githubusercontent.com/45402633/82512822-340eef80-9adf-11ea-8cad-9786c748708d.png)


I added cudnn files to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1 : bin, include, lib directories.

Could it be something else in my configuration?

If any other dlls are missing, would Visual Studio still give the error of not being able to find onnxruntime.dll?  Which files should I explicitly add to the output directory?

**Comment by snnn** [comment]
The onnxruntime.dll depends on 

1.     advapi32.dll
2.     cublas64_10.dll
3.     cudart64_101.dll
4.     cudnn64_7.dll
5.     cufft64_10.dll
6.     curand64_10.dll
7.     kernel32.dll
8.     msvcp140.dll
9.     shlwapi.dll
10.     vcruntime140.dll
11.     vcruntime140_1.dll

Do you have all of them in your PATH ?

**Comment by pranavsharma** [comment]
Closing due to inactivity. Please re-open if required.

**Comment by FloP93** [comment]
I have the same problem after updating from 0.5.1 to 1.4.0 =>
![image](https://user-images.githubusercontent.com/34069654/88788286-69962000-d195-11ea-92ad-7bf18b2d0eec.png)

@snnn where do i find all those dlls? I copied 
cublas64_100.dll
cudart64_100.dll
cudnn64_7.dll
cufft64_100.dll
curand64_100.dll

but i dont know where to look for the rest

**Comment by snnn** [comment]
To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Type python.exe then press the "tab" key, check "Show loader snaps" box

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)

5.  Put your python commands into a script file, named "test.py"
```
import torch
import onnxruntime
```

6.  Start windbg, run python.exe with arguments of "test.py"
![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)

7. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135


Please post the log here if you can't find the problematic DLL by yourself.

**Comment by celowsky** [comment]
I have the same problem as the two folks above.
**My System**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro (version 1909) x64
ONNX Runtime version: 1.4.0
Visual Studio version (if applicable): Community 2019
CUDA/cuDNN version: 10.1/7.6.5
System Python version: 3.6.8

I installed pytorch and the onnxruntime for python (though I am trying to use the onnxruntime in a winforms-based c# application) with the following commands:
- `pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
- `pip install onnxruntime-gpu`

I can't post the output from your testing instructions, since it goes over both pastebin and github's limit, but it looks like libittnotify.dll and tbbmalloc.dll are the DLLs missing. Both seem to be related to threading on my Intel CPU, but I'm not sure why it's trying to use the CPU in the first place

**Comment by snnn** [comment]
Hi @celowsky 

The libittnotify.dll one is expected, it is optional. Probably it is because of something else.  Did you put CUDA and Cudnn DLLs in your PATH?

**Comment by celowsky** [comment]
Yes, I can confirm that both CUDA and Cudnn DLLs are in my path. The CheckCudaExecutionProviderDLLs() function on line 70 is able to load "cublas64_10.dll", "cudnn64_7.dll", and "curand64_10.dll". I've tried editing my system environment variables like @solarflex above and also copying them straight into the same directory where the code is executing (bin\x64\Debug). 

I have two gpus in my machine: a GTX 1060 and an RTX 2070. The RTX 2070 is graphics device 0 and the other card is 1.

**Comment by snnn** [comment]
Would you mind to send me the windbg log outputs? My email is: chasun at microsoft.com

**Comment by celowsky** [comment]
Can do. I just sent them over

**Comment by snnn** [comment]
Hi @celowsky, I couldn't find any error from it. Could you make test.py simpler? For example,  just one line of 
```
import onnxruntime
```

Now it contains both onnxruntime and pytorch, it's hard to say who caused the failure.

**Comment by snnn** [comment]
Oh, I see pytorch has a private cuda copy, I guess it was not using the CUDA DLLs provided by you. And that CUDA may differs than what onnxruntime expects.

**Comment by celowsky** [comment]
Yeah, is there a trace I could provide you with from my C# app that could help you debug?

**Comment by celowsky** [comment]
Maybe I could try loading my system CUDA installation in python?

**Comment by snnn** [comment]
Execuse me, what's the goal? Do you want to use onnxruntime's C# binding and the nuget package or the python package? which one failed to load? Does the python one work?

**Comment by celowsky** [comment]
Sorry I should have specified. I would like to use the C# binding and the `Microsoft.ML.Onnxruntime.Gpu` nuget package to detect objects using ONNX in ML.Net. In my project, I have a Yolo Darknet model I've trained from an image set using the following python script: https://gist.github.com/celowsky/a708870e2b316b592dc3c48ad2a3e16b.

I called the script like this: `python --img 416 --batch 16 --epochs 5 --data data\data.yaml --cfg models\yolov5x.yaml --weights weights\yolov5x.pt`

In my WinForms application, I click a button on my form to trigger the following function:
```c#
        private void OnLoadTrainingClick(object sender, EventArgs e)
        {
            Console.WriteLine("Detect image path is " + _detectImagesPath);
            this.mlContext = new MLContext();
            var capturer = new ScreenCapture();
            Bitmap windowImage = GetWindowBitmap();
            this.myBitmap = windowImage;
            this.myImage = new ImageNetData { Image = windowImage };
            this.images = new List<ImageNetData>();
            this.dataView = mlContext.Data.LoadFromEnumerable<ImageNetData>(this.images);
            var scorer = new OnnxModelScorer(_modelPath, this.mlContext, this.images);
            IEnumerable<float[]> probabilities = scorer.Score(this.dataView);
            YoloOutputParser parser = new YoloOutputParser();
            IEnumerable<IList<YoloBoundingBox>> boundingBoxes = probabilities
                .Select(probability => parser.ParseOutputs(probability))
                .Select(boxes => parser.FilterBoundingBoxes(boxes, 5, .5F));
            var imageName = Guid.NewGuid() + ".bmp";
            var image = DrawBoundingBox(imageName, windowImage);

            image.Save(Path.Combine(_detectImagesPath, imageName));
        }
```

The following line from the above snippet fails: `IEnumerable<float[]> probabilities = scorer.Score(this.dataView);`. Following the call stack leads me to the same error as the author of this issue: 
```
System.TypeInitializationException: 'The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.'
DllNotFoundException: Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
Most of the classes here are either identical or lightly adapted from this Microsoft tutorial: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx

Here are the exact classes I'm using:
OnnxModelScorer.cs: https://gist.github.com/celowsky/8c9c2435d547ec4d26f06af69b5a18ec
YoloOutputParser.cs: https://gist.github.com/celowsky/c88152146107a26e602cf717fd092e44
YoloBoundingBox.cs: https://gist.github.com/celowsky/f8a2618c89ab38cb2ef356e977cbc4a2

**Comment by snnn** [comment]
Could you replace the Microsoft.ML.Onnxruntime.Gpu  package with Microsoft.ML.Onnxruntime and try that first? The later one has less dependencies.

**Comment by celowsky** [comment]
Unfortunately, that still gives the exact same error. I feel like the issue may still be with how my dlls are being loaded. I notice that if I breakpoint right before the failed call and open the Modules window in Visual Studio 2019 under the **Debug > Windows** menu, `onnxruntime.dll` isn't listed, even though `Microsoft.ML.OnnxRuntime.dll` is. 

At the top of my system path environment variable I have the following directories listed:
- C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
- C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp

If I copy the `onnxruntime.dll` provider that I think is generated by the `Microsoft.ML.OnnxRuntime.dll` nuget package, I get a new error:

```
System.EntryPointNotFoundException: 'Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.'
```

**Comment by snnn** [comment]
By default, when you install a CUDA SDK, it will add itself to PATH. But you can't have multiple CUDA SDKs in the PATH, because some of the DLLs may have the filename but totally different content.

**Comment by celowsky** [comment]
I have since uninstalled it, and manually deleted the folders left behind in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA, but still receive the same error message

**Comment by celowsky** [comment]
I still am unable to find out which paths are being considered during the loading of this library. I have made sure that all the files listed in @snnn 's comment are available in my path, but it seems that their location in relation to the onnxruntime.dll also matters. I've also copied those files to the `packages\Microsoft.ML.OnnxRuntime.Gpu.1.4.0\runtimes\win-x64\native` to no avail. This ticket should be reopened

**Comment by snnn** [comment]
> I still am unable to find out which paths are being considered during the loading of this library
See: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by hamishkeith** [comment]
Did anyone get this working?  I have the same issue.  It works fine if i use CPU but if i try an target the GPU I left with the exception System.EntryPointNotFoundException: 'Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.'

I have checked and I have cuda 10 (only) installed, and it is added to my path.  All ML.net / dependences are 1.5.

**Comment by MagnusGabell** [comment]
This problem still exists in VS 2022. Any news about 
Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
   at Yolov5Net.App.Program.Main(String[] args) in C:\Development\ai_image_evaluation\YoloV5\yolov5-net\src\Yolov5Net.App\Program.cs:line 22

**Comment by snnn** [comment]
Please see my comment above, use windbg to get more information.

**Comment by gktval** [comment]
For my issue, it seems that it is trying to pull from both CUDA v10.1 and CUDA v12.3. In Environmental variables, I have the Path set to v 12.3 
![image](https://github.com/microsoft/onnxruntime/assets/7605046/f536bcc8-0ee2-423c-a078-01fcb82e4185)

Here is my log from windDbg:
0:000> g
ModLoad: 00007fff`43d40000 00007fff`43d71000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffe`18210000 00007ffe`18269000   C:\Program Files\dotnet\host\fxr\8.0.0-rc.2.23479.6\hostfxr.dll
ModLoad: 00007ffe`181a0000 00007ffe`18203000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\hostpolicy.dll
ModLoad: 00007ffe`17ca0000 00007ffe`1819a000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\coreclr.dll
ModLoad: 00007fff`425a0000 00007fff`4273f000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007fff`430b0000 00007fff`4343a000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007fff`43dd0000 00007fff`43ea7000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007fff`41b20000 00007fff`41b9a000   C:\WINDOWS\System32\bcryptPrimitives.dll
(2f14.5580): Unknown exception - code 04242420 (first chance)
ModLoad: 00007ffe`16cb0000 00007ffe`177cb000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Private.CoreLib.dll
ModLoad: 00007ffe`16b30000 00007ffe`16cab000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\clrjit.dll
ModLoad: 00007fff`403e0000 00007fff`403f8000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00000175`80300000 00000175`80308000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\LandUseTest_ConsoleApp.dll
ModLoad: 00000175`80300000 00000175`80308000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\LandUseTest_ConsoleApp.dll
ModLoad: 00000175`d76c0000 00000175`d76ce000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.dll
ModLoad: 00007ffe`16af0000 00007ffe`16b2f000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Collections.dll
ModLoad: 00000175`d8fc0000 00000175`d8ff6000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\Microsoft.ML.OnnxRuntime.dll
ModLoad: 000001b6`6dbd0000 000001b6`6dd52000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\Microsoft.ML.Data.dll
ModLoad: 00000175`d9020000 00000175`d903c000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\netstandard.dll
ModLoad: 000001b6`6dd60000 000001b6`6ddca000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\Microsoft.ML.Core.dll
ModLoad: 000001b6`6ddd0000 000001b6`6df96000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\TensorFlow.NET.dll
ModLoad: 00007ffe`16ac0000 00007ffe`16aea000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Console.dll
ModLoad: 00007ffe`16a40000 00007ffe`16ab9000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Linq.dll
ModLoad: 000001b6`6dfa0000 000001b6`6e04e000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\Newtonsoft.Json.dll
ModLoad: 00007ffe`169f0000 00007ffe`16a3e000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.Serialization.Formatters.dll
ModLoad: 00007ffe`169b0000 00007ffe`169ee000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Collections.Concurrent.dll
ModLoad: 00007ffe`16980000 00007ffe`169a2000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Diagnostics.TraceSource.dll
ModLoad: 00007ffe`165d0000 00007ffe`16974000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Linq.Expressions.dll
ModLoad: 00007ffe`16580000 00007ffe`165cf000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.Numerics.dll
ModLoad: 00007ffe`16540000 00007ffe`1657e000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Private.Uri.dll
ModLoad: 00007ffe`16440000 00007ffe`164f6000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.ComponentModel.TypeConverter.dll
ModLoad: 00007ffe`16520000 00007ffe`16532000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.ObjectModel.dll
ModLoad: 00007ffe`16420000 00007ffe`16433000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Threading.dll
ModLoad: 00007ffe`c8c60000 00007ffe`c8c6d000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.InteropServices.dll
ModLoad: 00007ffe`c8bf0000 00007ffe`c8bf8000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.Serialization.Primitives.dll
ModLoad: 00007ffe`16140000 00007ffe`1641e000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Data.Common.dll
ModLoad: 00000175`d9000000 00000175`d900a000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Xml.ReaderWriter.dll
ModLoad: 00007ffe`15930000 00007ffe`1613a000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Private.Xml.dll
ModLoad: 00007ffe`15910000 00007ffe`15922000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.ComponentModel.Primitives.dll
ModLoad: 00007ffe`c6320000 00007ffe`c6325000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.ComponentModel.dll
ModLoad: 00007fff`40cf0000 00007fff`40d18000   C:\WINDOWS\SYSTEM32\BCrypt.dll
ModLoad: 00000175`d9040000 00000175`d9048000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Reflection.Emit.ILGeneration.dll
ModLoad: 00000175`d9050000 00000175`d9058000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Reflection.Emit.Lightweight.dll
ModLoad: 00000175`d9060000 00000175`d9068000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Reflection.Primitives.dll
ModLoad: 00007ffe`158e0000 00007ffe`15905000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Memory.dll
ModLoad: 00000175`d9070000 00000175`d9078000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Text.Encoding.Extensions.dll
ModLoad: 000001b6`6e050000 000001b6`6e058000   C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.12\System.Runtime.InteropServices.RuntimeInformation.dll
ModLoad: 00007ffe`14da0000 00007ffe`158da000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\runtimes\win-x64\native\onnxruntime.DLL
ModLoad: 00007fff`2a8b0000 00007fff`2a8cd000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
ModLoad: 00007fff`2a7f0000 00007fff`2a87d000   C:\WINDOWS\SYSTEM32\MSVCP140.dll
ModLoad: 00007fff`2a7b0000 00007fff`2a7bc000   C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
ModLoad: 00007ffe`8e920000 00007ffe`8e927000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\runtimes\win-x64\native\onnxruntime_providers_shared.dll
ModLoad: 00007ffd`fdc80000 00007ffe`12039000   C:\Users\user\source\repos\landUseML\LandUse\LandUseTest_ConsoleApp\bin\x64\Debug\net7.0\runtimes\win-x64\native\onnxruntime_providers_cuda.dll
ModLoad: 00007ffd`f5960000 00007ffd`fdc79000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cufft64_10.dll
ModLoad: 00007ffe`14d50000 00007ffe`14d9b000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\cudnn64_8.dll
(2f14.5580): C++ EH exception - code e06d7363 (first chance)
(2f14.5580): C++ EH exception - code e06d7363 (first chance)
(2f14.5580): C++ EH exception - code e06d7363 (first chance)
(2f14.5580): CLR exception - code e0434352 (first chance)
(2f14.5580): CLR exception - code e0434352 (first chance)
(2f14.5580): CLR exception - code e0434352 (!!! second chance !!!)
KERNELBASE!RaiseException+0x6c:
00007fff`417d4ffc 0f1f440000      nop     dword ptr [rax+rax]
