### ISSUE TITLE
Errors while using docker build

### ISSUE THREAD

**Issue by kkmsft** [Microsoft/onnxruntime#402]
Host OS: ubuntu 16.04
docker version: Version:  18.09.1

When trying to build ONNX runtime from source by running:

export BUILD_DEVICE=cpu
 ./tools/ci_build/github/linux/run_dockerbuild.sh
 
build fails with the following errors. Any tips on what could be missing ?

2019-01-29 19:33:24,143 Build [DEBUG] - Running subprocess in '/home/onnxruntimedev'
['/usr/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'files.pythonhosted.org', 'setuptools', 'wheel', 'numpy']
The directory '/home/onnxruntimedev/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/onnxruntimedev/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/bf/ae/a23db1762646069742cc21393833577d3fa438eecaa59d11fb04fa57fcd5/setuptools-40.7.1-py2.py3-none-any.whl (574kB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/64/24/2e9c72f44cec8c872000d78c54230e40550c494647e352d1d06724cdaee6/numpy-1.16.0-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
Installing collected packages: setuptools, wheel, numpy
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path, 
 File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.5/distutils/command/install.py", line 350, in finalize_options
    self.create_home_path()
  File "/usr/lib/python3.5/distutils/command/install.py", line 575, in create_home_path
    os.makedirs(path, 0o700)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/onnxruntimedev/.local'
You are using pip version 8.1.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/onnxruntime_src/tools/ci_build/github/linux/../../build.py", line 604, in <module>
    sys.exit(main())
  File "/onnxruntime_src/tools/ci_build/github/linux/../../build.py", line 561, in main
    install_python_deps()
  File "/onnxruntime_src/tools/ci_build/github/linux/../../build.py", line 200, in install_python_deps
    run_subprocess([sys.executable, '-m', 'pip', 'install', '--trusted-host', 'files.pythonhosted.org'] + dep_packages)
  File "/onnxruntime_src/tools/ci_build/github/linux/../../build.py", line 156, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'files.pythonhosted.org', 'setuptools', 'wheel', 'numpy']' returned non-zero exit status 2

**Comment by snnn** [comment]
This script is only for being used in Azure DevOps(aka. VSTS).
I don't expect it can work well in other places.
