### ISSUE TITLE
Facing "ImportError: cannot import name 'get_all_providers'

### ISSUE THREAD

**Issue by jesudasvf** [microsoft/onnxruntime#4132]
**Describe the bug**
Facing an ImportError: cannot import name 'get_all_providers', when trying to use Keras2onnx for convert a keras model to onnx

**Urgency**
Failed in the first step to use onnx-runtime for inferencing a keras model. Need to know if I'm missing some step

**System information**
- OS Platform and Distribution: WIndows OS
- ONNX Runtime installed from (source or binary): binary, py package onnxruntime-gpu installed using pip 
- ONNX Runtime version: 1.3.0
- Python version: 3.6.8
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10 / 7.6.5
- GPU model and memory: NVIDIA RTX2060
- keras2onnx : 1.6.1 (pip installed)
- tensorflow-gpu : 1.15.0
- protpbuf : 3.12.2
- ide used : pycharm community edition 2020.1.1

**To Reproduce**
Run the following python script. The script tries to load a keras model 
---------------------------------------------------------------------------
import onnxruntime
import keras2onnx
import tensorflow as tf
from inference.batch_inference_all_gender_emotion_2D_audio_test_set_ravdess import get_mfcc_feature

# load the baseline spemoclass model
keras_baseline_model = r"C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_OnnxRT\saved_models\gender_emotion\SpeechAllGenderEmotionRecognition_2D_M.h5"
input_wav_file = r"C:\SL_Projects\SpeechEmotionRecognition\SpeechEmoReco_OnnxRT\test_wav_samples\RAVDESS\03-01-01-01-01-01-01.wav"

# convert to onnx model
onnx_model = keras2onnx.convert_keras(keras_baseline_model, keras_baseline_model.name)

# runtime prediction
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
features = get_mfcc_feature(input_wav_file, 40, 256)
x = features
x = x if isinstance(x, list) else [x]
feed = dict([(input.name, x[n]) for n, input in enumerate(sess.get_inputs())])
pred_onnx = sess.run(None, feed)

When you try to run the script, the import error is indicated.

C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 62562 --file C:/SL_Projects/SpeechEmotionRecognition/SpeechEmoReco_OnnxRT/inference/inf_using_onnx_rt.py
pydev debugger: process 33116 is connecting
Connected to pydev debugger (build 201.7223.92)
C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\onnxruntime\capi\_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: The specified module could not be found.'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\onnxruntime\__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode, OrtDevice, SessionIOBinding
ImportError: cannot import name 'get_all_providers'

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Can you please make sure the CUDA dependencies listed in system requirements are installed and findable via `PATH` ?

**Comment by jesudasvf** [comment]
Thanks @hariharans29 , 
I had to upgrade to CUDA 10.1 from 10. 

With the upgrade the import error is no longer there. 

However I'm facing an issue on onnxruntime.InferenceSession() call. Every time I get CUDA out of memory issue as given below

C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 50748 --file C:/SL_Projects/SpeechEmotionRecognition/SpeechEmoReco_OnnxRT/inference/inf_using_onnx_rt.py
pydev debugger: process 13620 is connecting
Connected to pydev debugger (build 201.7223.92)
2020-06-05 15:35:23.785976: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\librosa\util\decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
WARNING:tensorflow:From C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-06-05 15:35:39.904755: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-05 15:35:40.076788: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
2020-06-05 15:35:40.077301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-05 15:35:40.109643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-06-05 15:35:40.144659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-06-05 15:35:40.164271: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-06-05 15:35:40.230998: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-06-05 15:35:40.282656: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-06-05 15:35:40.283041: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-05 15:35:40.284323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-06-05 15:35:40.289764: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-05 15:35:40.295848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
2020-06-05 15:35:40.296347: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-06-05 15:35:40.296687: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-06-05 15:35:40.297015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-06-05 15:35:40.297345: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-06-05 15:35:40.297739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-06-05 15:35:40.298116: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-06-05 15:35:40.298458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-06-05 15:35:40.299212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-06-05 15:35:42.333292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-05 15:35:42.333780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-06-05 15:35:42.334125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-06-05 15:35:42.336502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4608 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\tensorflow_core\python\ops\math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
2020-06-05 15:35:58.4883554 [E:onnxruntime:, inference_session.cc:925 onnxruntime::InferenceSession::Initialize] Exception during initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=LENY540-SL-JESU ; expr=cudaMalloc((void**)&p, size); 
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/SL_Projects/SpeechEmotionRecognition/SpeechEmoReco_OnnxRT/inference/inf_using_onnx_rt.py", line 19, in <module>
    sess = onnxruntime.InferenceSession(content)
  File "C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\onnxruntime\capi\session.py", line 158, in __init__
    self._load_model(providers)
  File "C:\SL_Projects\SpeechEmotionRecognition\spemo_env_onnx\lib\site-packages\onnxruntime\capi\session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=LENY540-SL-JESU ; expr=cudaMalloc((void**)&p, size); 


The GPU NVIDIA RTX2060 has 6GB and CPU has 16GB RAM
