### ISSUE TITLE
Build failure on redundant move statement

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#4152]
**Describe the bug**
[This](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/perftest/TFModelInfo.cc#L51) line is throwing a compilation error on master branch when I try to build.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): master branch
- ONNX Runtime version: latest
- Python version: v3.6.9
- GCC/Compiler version (if compiling from source): GCC v9.2.1 20191102

**To Reproduce**
- clone the repo
- run the build.sh script
```
./build.sh --config RelWithDebInfo --build_shared_lib
```

**Full Error Message**
```
/home/josh/Downloads/tmp/onnxruntime/onnxruntime/test/perftest/TFModelInfo.cc: In static member function ‘static std::unique_ptr<TestModelInfo> TFModelInfo::Create(const PATH_CHAR_TYPE*)’:
/home/josh/Downloads/tmp/onnxruntime/onnxruntime/test/perftest/TFModelInfo.cc:51:19: error: redundant move in return statement [-Werror=redundant-move]
   51 |   return std::move(ret);
      |          ~~~~~~~~~^~~~~
/home/josh/Downloads/tmp/onnxruntime/onnxruntime/test/perftest/TFModelInfo.cc:51:19: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_perf_test.dir/build.make:82: recipe for target 'CMakeFiles/onnxruntime_perf_test.dir/home/josh/Downloads/tmp/onnxruntime/onnxruntime/test/perftest/TFModelInfo.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_perf_test.dir/home/josh/Downloads/tmp/onnxruntime/onnxruntime/test/perftest/TFModelInfo.cc.o] Error 1
CMakeFiles/Makefile2:888: recipe for target 'CMakeFiles/onnxruntime_perf_test.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_perf_test.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/josh/Downloads/tmp/onnxruntime/tools/ci_build/build.py", line 1795, in <module>
    sys.exit(main())
  File "/home/josh/Downloads/tmp/onnxruntime/tools/ci_build/build.py", line 1690, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/home/josh/Downloads/tmp/onnxruntime/tools/ci_build/build.py", line 868, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/josh/Downloads/tmp/onnxruntime/tools/ci_build/build.py", line 402, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/josh/Downloads/tmp/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.
```

**Solution**
Removing the explicit move statement appears to resolve the problem.
```
return ret;
```
The code then compiles and passes all tests.

**Comment by hariharans29** [comment]
Closed via #4163
