### ISSUE TITLE
ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher.

### ISSUE THREAD

**Issue by wangzhao123456** [microsoft/onnxruntime#4200]
**Hello, I use onnxruntime to optimize the onnx model. However, I got the following error. I wonder if there are some ways to upgrade the opset version of the onnx model to 7 or above? Thanks!**

2020-06-11 06:47:16.450501705 [W:onnxruntime:, model.cc:121 Model] ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher. For now, this opset 3 model may run depending upon legacy support of some older opset version operators.
2020-06-11 06:47:16.455193767 [W:onnxruntime:, graph.cc:2619 CleanUnusedInitializers] Removing initializer 'gpu_0/imagenet1k_blobs_queue_f22e83c9-22cd-4a8b-a66d-113af6b832b4_0'. It is not used by any node and should be removed from the model.
Traceback (most recent call last):
  File "test_onnxruntime.py", line 19, in <module>
    session = rt.InferenceSession("/root/test-onnx/resnet50-caffe2-v1-3.onnx", sess_options)
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(1)
![Onnxruntime_code](https://user-images.githubusercontent.com/15125451/84354886-3eab3900-abf4-11ea-8d01-e31cedf631d8.png)
![onnxruntime_error](https://user-images.githubusercontent.com/15125451/84354896-423ec000-abf4-11ea-8f7a-74bd0deb760e.png)

**Comment by pranavsharma** [comment]
This might help https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx

**Comment by wangzhao123456** [comment]
> This might help https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx

Thanks for your reply.  I can successfuly convert the opset version of onnx model from 6 to 7. But When I tried to convert the opset version from 3 to 7, It failed.
Thanks a lot.

**Comment by pranavsharma** [comment]
You should file this issue in the onnx repo here https://github.com/onnx/onnx/issues. This is not a onnxruntime issue.
