### ISSUE TITLE
Building from source fails due to undefined reference to 'libiconv'

### ISSUE THREAD

**Issue by debarundhar** [microsoft/onnxruntime#4234]
**Describe the bug**
When trying to build ONNX Runtime with TensorRT support from source I get errors related to `libiconv`. 
```
[ 96%] Linking CXX executable onnxruntime_test_all
libonnxruntime_providers.a(string_normalizer.cc.o): In function `onnxruntime::string_normalizer::Utf8Converter::from_bytes(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:124: undefined reference to `libiconv_open'
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:138: undefined reference to `libiconv'
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:146: undefined reference to `libiconv_close'
libonnxruntime_providers.a(string_normalizer.cc.o): In function `onnxruntime::string_normalizer::Utf8Converter::to_bytes(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) const':
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:156: undefined reference to `libiconv_open'
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:173: undefined reference to `libiconv'
/home/debarun/workspace/onnxruntime/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:180: undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_test_all.dir/build.make:3416: recipe for target 'onnxruntime_test_all' failed
make[2]: *** [onnxruntime_test_all] Error 1
CMakeFiles/Makefile2:591: recipe for target 'CMakeFiles/onnxruntime_test_all.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_test_all.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/debarun/workspace/onnxruntime/tools/ci_build/build.py", line 1826, in <module>
    sys.exit(main())
  File "/home/debarun/workspace/onnxruntime/tools/ci_build/build.py", line 1716, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/home/debarun/workspace/onnxruntime/tools/ci_build/build.py", line 871, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/debarun/workspace/onnxruntime/tools/ci_build/build.py", line 405, in run_subprocess
    env=my_env, shell=shell)
  File "/home/debarun/miniconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/debarun/miniconda3/bin/cmake', '--build', '/home/debarun/workspace/onnxruntime/build/Linux/Debug', '--config', 'Debug', '--', '-j12']' returned non-zero exit status 2.
```

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.3.0
- Python version: Anaconda Python 3.7.6
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): gcc 7.5.0, cmake 3.14.0
- CUDA/cuDNN version: CUDA 10.2, cuDNN 7.6.5
- GPU model and memory: Nvidia 2070 RTX 8GB

**To Reproduce**
```
git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
./build.sh --cudnn_home <path to cuDNN e.g. /usr/lib/x86_64-linux-gnu/> --cuda_home <path to folder for CUDA e.g. /usr/local/cuda> --use_tensorrt --tensorrt_home <path to TensorRT home> --enable_pybind --build_wheel
```

**Expected behavior**
The build should have succeeded since `libiconv` is available in Ubuntu 18.04 under `libc6`. See [https://askubuntu.com/questions/898826/why-is-there-no-libiconv-package-in-ubuntu](https://askubuntu.com/questions/898826/why-is-there-no-libiconv-package-in-ubuntu)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yuslepukhin** [comment]
We generally do not release on Ubuntu-18. However, the below links should give you an idea what we use to build it:

- [Ubuntu GPU Docker](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.ubuntu_gpu#L7
)

- [Ubuntu Packages](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/install_ubuntu.sh#L59)

**Comment by zhaosj98** [comment]
Firstly, you should have libiconv installed. Then add target link library `-liconv` in file `onnxruntime\cmake\onnxruntime.cmake` at line 120.
```shell
target_link_libraries(onnxruntime PRIVATE
    onnxruntime_session
    ${onnxruntime_libs}
    ${PROVIDERS_CUDA}
    ${PROVIDERS_NGRAPH}
    ${PROVIDERS_NNAPI}
    ${PROVIDERS_RKNPU}
    ${PROVIDERS_MIGRAPHX}
    ${PROVIDERS_OPENVINO}
    ${PROVIDERS_NUPHAR}
    ${PROVIDERS_VITISAI}
    ${PROVIDERS_DML}
    ${PROVIDERS_ACL}
    ${PROVIDERS_ARMNN}
    ${onnxruntime_winml}
    onnxruntime_optimizer
    onnxruntime_providers
    onnxruntime_util
    ${onnxruntime_tvm_libs}
    onnxruntime_framework
    onnxruntime_graph
    onnxruntime_common
    onnxruntime_mlas
    ${onnxruntime_EXTERNAL_LIBRARIES}
    -liconv)
```
