### ISSUE TITLE
Model with missing type information causes a SIGSEGV

### ISSUE THREAD

**Issue by Craigacp** [microsoft/onnxruntime#4349]
**Describe the bug**
The attached model file has an invalid domain string, and while it fails the onnx model checker, if you load it into onnx-runtime it takes down the whole process (including the JVM). This occurs with the python API too. We're performing some fuzz testing on the models which is how we hit this issue.

As the onnx model checker says it's invalid I'd expect ORT to give a status error (which the Java API would catch and throw an OrtException), rather than have it segfault the whole process.

**Urgency**
n/a

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS & linux
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: 1.3.1
- Python version: n/a (I used the Java API)

**To Reproduce**
Download the attached model, load it into a session.

[crashed1.onnx.zip](https://github.com/microsoft/onnxruntime/files/4839149/crashed1.onnx.zip)

**Expected behavior**
I expected an exception thrown by the ORT Java API.

**Additional context**
The stack trace is:
```
C  [libc++.1.dylib+0x37b37]  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x1b
C  [libonnxruntime.dylib+0x58d8af]  onnx::Utils::DataTypeUtils::ToDataTypeString(int)+0xbf
C  [libonnxruntime.dylib+0x58c51d]  onnx::Utils::DataTypeUtils::ToString(onnx::TypeProto const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x1fd
C  [libonnxruntime.dylib+0x58bf89]  onnx::Utils::DataTypeUtils::ToType(onnx::TypeProto const&)+0x49
C  [libonnxruntime.dylib+0x4d85f6]  onnxruntime::NodeArg::NodeArg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, onnx::TypeProto const*)+0x1c6
C  [libonnxruntime.dylib+0x4deece]  onnxruntime::Graph::GetOrCreateNodeArg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, onnx::TypeProto const*)+0x5e
C  [libonnxruntime.dylib+0x4dd954]  onnxruntime::Graph::Graph(onnxruntime::Model const&, onnx::GraphProto*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, long long, std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, onnxruntime::Graph*, onnxruntime::Node const*, onnxruntime::logging::Logger const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, onnx::FunctionProto const*, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, onnx::FunctionProto const*> > > const&)+0xd14
C  [libonnxruntime.dylib+0x4dea1e]  onnxruntime::Graph::Graph(onnxruntime::Model const&, onnx::GraphProto*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, long long, std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, onnxruntime::logging::Logger const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, onnx::FunctionProto const*, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, onnx::FunctionProto const*> > > const&)+0x5e
C  [libonnxruntime.dylib+0x512e27]  onnxruntime::Model::Model(onnx::ModelProto&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::list<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, std::__1::allocator<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection> > > const*, onnxruntime::logging::Logger const&)+0x767
C  [libonnxruntime.dylib+0x514228]  onnxruntime::Model::Load(onnx::ModelProto&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<onnxruntime::Model>&, std::__1::list<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, std::__1::allocator<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection> > > const*, onnxruntime::logging::Logger const&)+0x68
C  [libonnxruntime.dylib+0x3225c]  std::__1::__function::__func<onnxruntime::InferenceSession::Load()::$_4, std::__1::allocator<onnxruntime::InferenceSession::Load()::$_4>, onnxruntime::common::Status (std::__1::shared_ptr<onnxruntime::Model>&)>::operator()(std::__1::shared_ptr<onnxruntime::Model>&)+0x3c
C  [libonnxruntime.dylib+0x1f7f2]  onnxruntime::InferenceSession::Load(std::__1::function<onnxruntime::common::Status (std::__1::shared_ptr<onnxruntime::Model>&)>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x182
C  [libonnxruntime.dylib+0x20e10]  onnxruntime::InferenceSession::Load()+0xc0
C  [libonnxruntime.dylib+0x45787]  (anonymous namespace)::LoadAndInitializeSession(OrtEnv const*, OrtSessionOptions const*, std::__1::unique_ptr<onnxruntime::InferenceSession, std::__1::default_delete<onnxruntime::InferenceSession> >&, OrtSession**)+0x307
C  [libonnxruntime.dylib+0x45226]  OrtApis::CreateSession(OrtEnv const*, char const*, OrtSessionOptions const*, OrtSession**)+0x336
C  [libonnxruntime4j_jni.dylib+0x4e14]  Java_ai_onnxruntime_OrtSession_createSession__JJLjava_lang_String_2J+0x44
```
and the onnx model checker says:
```>>> onnx.checker.check_model(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'data_type' of tensor is required but missing.```

**Comment by snnn** [comment]
Thank you. I'll fix it.

**Comment by prabhat00155** [comment]
@Craigacp: This is not caused by invalid domain string. I tried another model with some random domain string and it works fine. The issue is caused by your Imputer node, which should have some input, but in your model there is no input to this node. So, the input tensor type is "undefined", which is not handled when mapping the input type to enum in ONNX and hence causes SIGSEGV.
This looks an invalid model, how did you generate the model? Did you use skl2onnx?

**Comment by Craigacp** [comment]
Ah ok. The model was generated by fuzzing a valid model as we're trying to figure out if user supplied models can take down the process (which this one does). The team doing the fuzzing was using AFL https://github.com/google/AFL to generate new models.

**Comment by prabhat00155** [comment]
There is an assert statement(https://github.com/onnx/onnx/blob/456ba4cace5b21cbd64b579ebd48e83aa4081b76/onnx/defs/data_type_utils.cc#L172), but I guess that works only in debug mode. I'll add a check there so that it doesn't throw segmentation fault.

**Comment by Craigacp** [comment]
Sounds good. Are there other similar asserts that should be made into runtime checks?

**Comment by prabhat00155** [comment]
Issue fixed in onnxruntime. We would only know about other similar asserts by testing more edge case scenarios like this.
