### ISSUE TITLE
Build with OpenVINO

### ISSUE THREAD

**Issue by oliveirara** [microsoft/onnxruntime#4445]
I tried to build onnxruntime with OpenVINO following the procedures from [BUILD.md#openvino](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino) but when the compiler tries `Linking CXX executable onnxruntime_test_all`, `undefined references` appears and end it up with errors:

```bash
[ 81%] [Building CXX object]
CMakeFiles/onnxruntime_test_all.dir/share/storage1/TNG/onnxruntime/onnxruntime/test/contrib_ops/inverse_test.cc.o[0m
libonnxruntime_providers_openvino.a(backend_manager.cc.o): In function `onnxruntime::openvino_ep::GlobalContext::GlobalContext()':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/contexts.h:12: undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::details::extract_exception(InferenceEngine::StatusCode, char*)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/details/ie_exception_conversion.hpp:62: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::GetBlob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:114: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:113: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:110: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::StartAsync()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:215: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:114: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `onnxruntime::openvino_ep::BasicBackend::BasicBackend(onnx::ModelProto const&, onnxruntime::openvino_ep::GlobalContext&, onnxruntime::openvino_ep::SubGraphContext const&)':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/basic_backend.cc:39: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::ExecutableNetwork::CreateInferRequestPtr()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_executable_network.hpp:122: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::InferRequest(std::shared_ptr<InferenceEngine::IInferRequest>, InferenceEngine::details::SOPointer<InferenceEngine::IInferencePlugin, InferenceEngine::details::SharedObjectLoader>)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:205: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::ExecutableNetwork::CreateInferRequestPtr()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_executable_network.hpp:122: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::InferRequest::InferRequest(std::shared_ptr<InferenceEngine::IInferRequest>, InferenceEngine::details::SOPointer<InferenceEngine::IInferencePlugin, InferenceEngine::details::SharedObjectLoader>)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:205: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::InferRequest::GetBlob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:113: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:110: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `onnxruntime::openvino_ep::VADMBackend::VADMBackend(onnx::ModelProto const&, onnxruntime::openvino_ep::GlobalContext&, onnxruntime::openvino_ep::SubGraphContext const&)':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/vadm_backend.cc:58: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/vadm_backend.cc:88: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::setPrecision(InferenceEngine::Precision)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:60: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::getTensorDesc() const':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:131: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::setLayout(InferenceEngine::Layout)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
gmake[2]: *** [onnx_test_runner] Error 1
gmake[1]: *** [CMakeFiles/onnx_test_runner.dir/all] Error 2
```

and

```bash
[ 95%] [Linking CXX executable onnxruntime_test_all]
libonnxruntime_providers_openvino.a(backend_manager.cc.o): In function `onnxruntime::openvino_ep::GlobalContext::GlobalContext()':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/contexts.h:12: undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::details::extract_exception(InferenceEngine::StatusCode, char*)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/details/ie_exception_conversion.hpp:62: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::GetBlob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:114: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:113: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:110: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::StartAsync()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:215: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:114: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `onnxruntime::openvino_ep::BasicBackend::BasicBackend(onnx::ModelProto const&, onnxruntime::openvino_ep::GlobalContext&, onnxruntime::openvino_ep::SubGraphContext const&)':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/basic_backend.cc:39: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::ExecutableNetwork::CreateInferRequestPtr()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_executable_network.hpp:122: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(basic_backend.cc.o): In function `InferenceEngine::InferRequest::InferRequest(std::shared_ptr<InferenceEngine::IInferRequest>, InferenceEngine::details::SOPointer<InferenceEngine::IInferencePlugin, InferenceEngine::details::SharedObjectLoader>)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:205: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::ExecutableNetwork::CreateInferRequestPtr()':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_executable_network.hpp:122: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::InferRequest::InferRequest(std::shared_ptr<InferenceEngine::IInferRequest>, InferenceEngine::details::SOPointer<InferenceEngine::IInferencePlugin, InferenceEngine::details::SharedObjectLoader>)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:205: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `InferenceEngine::InferRequest::GetBlob(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:113: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(vadm_backend.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/cpp/ie_infer_request.hpp:110: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
libonnxruntime_providers_openvino.a(vadm_backend.cc.o): In function `onnxruntime::openvino_ep::VADMBackend::VADMBackend(onnx::ModelProto const&, onnxruntime::openvino_ep::GlobalContext&, onnxruntime::openvino_ep::SubGraphContext const&)':
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/vadm_backend.cc:58: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/share/storage1/TNG/onnxruntime/onnxruntime/core/providers/openvino/backends/vadm_backend.cc:88: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::setPrecision(InferenceEngine::Precision)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:60: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::getTensorDesc() const':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:131: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o): In function `InferenceEngine::InputInfo::setLayout(InferenceEngine::Layout)':
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
libonnxruntime_providers_openvino.a(backend_utils.cc.o):/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/include/ie_input_info.hpp:91: more undefined references to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
gmake[2]: *** [onnxruntime_test_all] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_test_all.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/share/storage1/TNG/onnxruntime/tools/ci_build/build.py", line 1891, in <module>
    sys.exit(main())
  File "/share/storage1/TNG/onnxruntime/tools/ci_build/build.py", line 1780, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/share/storage1/TNG/onnxruntime/tools/ci_build/build.py", line 920, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/share/storage1/TNG/onnxruntime/tools/ci_build/build.py", line 422, in run_subprocess
    env=my_env, shell=shell)
  File "/share/storage1/TNG/Softwares/Anaconda3-2020.02/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/share/storage1/TNG/Softwares/Anaconda3-2020.02/bin/cmake', '--build', '/share/storage1/TNG/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j32']' returned non-zero exit status 2.]0;
```

The complete log file is attached at the end.

**System information**
- OS Platform and Distribution: CentOS Linux 7
- ONNX Runtime installed from (source or binary): latest, from source
- Python version: 3.7.7
- GCC/Compiler version (if compiling from source): 5.3.0
- OpenVINO version: 2020.03

**To Reproduce**
[log_onnxruntime.txt](https://github.com/microsoft/onnxruntime/files/4886266/log_onnxruntime.txt)

1. source <openvino_install_directory>/bin/setupvars.sh
2. git clone --recursive https://github.com/Microsoft/onnxruntime
3. cd onnxruntime
4. ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --use_openvino CPU_FP32

**Comment by jywu-msft** [comment]
@smkarlap , @suryasidd   any ideas?

**Comment by oliveirara** [comment]
Still not able to build, even with openvino_2020.4.287.

**Comment by jywu-msft** [comment]
openvino 2020.4 is not yet supported,
but 2020.3 should work. will ping some folks from Intel to see if they have any idea.

**Comment by suryasidd** [comment]
Hi @oliveirara, I tried the build on Centos 7 and it worked fine for me. My gcc version was 7.3 and cmake version is 3.18.0. 

Could you please try this configuration and let me know if it works ? 
To install gcc 7.3 without disturbing your 5.3 configuration, you can follow these steps:

$sudo yum install centos-release-scl-rh
$sudo yum install devtoolset-7-toolchain
$ scl enable devtoolset-7 bash

**Comment by oliveirara** [comment]
> Hi @oliveirara, I tried the build on Centos 7 and it worked fine for me. My gcc version was 7.3 and cmake version is 3.18.0.
> 
> Could you please try this configuration and let me know if it works ?
> To install gcc 7.3 without disturbing your 5.3 configuration, you can follow these steps:
> 
> $sudo yum install centos-release-scl-rh
> $sudo yum install devtoolset-7-toolchain
> $ scl enable devtoolset-7 bash

Hi @suryasidd, I compiled and installed gcc-7.3.0 and cmake-3.18.0 and still got the same error. Could you please provide your configuration flags for gcc and make? Perhaps I am missing something. 

[log.txt](https://github.com/microsoft/onnxruntime/files/4984155/log.txt)

Thanks,

**Comment by suryasidd** [comment]
I did not build gcc from source, I just used devtoolset and it configured gcc for me. From the log i didn't understand what "module load softwares/openvino/2020.3" does? Also, after sourcing the environment variables, could you please send the output of the command env?

**Comment by oliveirara** [comment]
> From the log i didn't understand what "module load softwares/openvino/2020.3" does?
You can ignore this. It does the same as source /opt/intel/...

I am not sure if this is relevant, but I didn't want to bother the admin again to install another software (devtoolset-7-toolchain). Previously I asked them to install OpenVINO. But I don't think this will make any difference...

Anyway, here is the env output.

[env.txt](https://github.com/microsoft/onnxruntime/files/4984239/env.txt)

**Comment by suryasidd** [comment]
The environment looks correct. Could you please also paste the output of the following command, 

tree /opt/intel/openvino_2020.3.194/deployment_tools/ > tree.txt. Might have to install tree using sudo yum install tree

Want to check if all the libraries and headers are available.

**Comment by oliveirara** [comment]
[tree.txt](https://github.com/microsoft/onnxruntime/files/4984746/tree.txt)

**Comment by suryasidd** [comment]
Hi @oliveirara, Could you please test it out with openvino 2020.4 ? We have not been able to reproduce this error with either 2020.3 or 2020.4.

**Comment by oliveirara** [comment]
Hi @suryasidd , 

I tried with openvino 2020.4.287, and still have this problem. I believe that this issue is related to linking problems with openvino libraries. 

Most of the errors are like this: 

`onnxruntime/core/providers/openvino/contexts.h:12: undefined reference to `InferenceEngine::Core::`

Maybe if I set up manually the path to openvino libraries inside onnxruntime/core/providers/openvino should in principle solve this problem.

I runned before build onnxruntime source <path-to-openvino>/bin/setupvars.sh, as usual.

**Comment by oliveirara** [comment]
Hi @suryasidd, I installed CentOS 7 on a virtual machine and I successfully built OnnxRuntime with OpenVINO 2020.04 (using devtoolset-7, as you mentioned earlier)! I also tested on devtoolset-9 which didn't work (errors appeared while building), and I also built successfully (just to check) on Ubuntu 18.04 LTS (virtual machine). Thank you for your attention 👍
