### ISSUE TITLE
remove_initializer_from_input.py not removing all ininitializers from inputs

### ISSUE THREAD

**Issue by cjtrueeb** [microsoft/onnxruntime#4507]
When using my exported TF model I am getting the following error:
```
Traceback (most recent call last):
  File "C:/Workspaces/ML/Zahnsegmentierung_KI/Model_Training/TestScript/TestOnnx.py", line 51, in <module>
    'labels_pl:0': np.random.randn(1, 2000).astype(np.int32), 'is_training_pl:0': np.array(False)})
  File "C:\Anaconda3\envs\py37\lib\site-packages\onnxruntime\capi\session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'conv0/batch_normalization/mul_3' Status Message: D:\2\s\include\onnxruntime\core/framework/op_kernel.h:88 onnxruntime::OpKernelContext::Input Missing Input: conv0/batch_normalization/cond_3/Merge:0
```
Therefore I have tried to use onnxruntime/tools/python/remove_initializer_from_input.py to clean up the inputs. After running the script and starting a session with the cleaned up model, I am still getting the same error. The warnings reveal that the model inputs still contain some initializers (most of them have been removed):

```
2020-07-14 15:44:10.7294799 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__49:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7295972 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__800 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7296120 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__799 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7298176 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__73:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7298704 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__814 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7298824 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__813 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7300587 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__97:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7301062 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__810 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7301178 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__809 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7303060 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__121:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7303546 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__806 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7303652 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__805 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7305517 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__812 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7305633 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__811 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7306118 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__808 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7319337 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__807 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7322793 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__169:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7323384 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__816 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7323516 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__815 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7325435 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__193:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7326140 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__802 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7326268 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__801 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7328374 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__217:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7329132 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__804 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7329604 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__803 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7331998 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer sub_graph_ending_node_Identity__241:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7333040 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__818 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7333171 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer const_fold_opt__817 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.7336573 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer cond__457 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2020-07-14 15:44:10.8512426 [E:onnxruntime:, sequential_executor.cc:281 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Mul node. Name:'conv0/batch_normalization/mul_3' Status Message: D:\2\s\include\onnxruntime\core/framework/op_kernel.h:88 onnxruntime::OpKernelContext::Input Missing Input: conv0/batch_normalization/cond_3/Merge:0
```

**System information**
- Windows 10
- onnxruntime 1.3.0
- model: tf2onnx 1.6.2 --opset 9

Unfortunately I cannot share the model.

**Comment by pranavsharma** [comment]
It's difficult to debug without looking at the model. The script https://github.com/microsoft/onnxruntime/blob/master/tools/python/remove_initializer_from_input.py is pretty simple and should be easy to debug.

**Comment by cjtrueeb** [comment]
I figured it out: The graph was using an is_training flag, which resulted in the Missing Input error in the Batch Normalization operations. Exporting the model with fixed flag is_training=False solved the problem for the moment.

**Comment by Octopusmode** [comment]
> I figured it out: The graph was using an is_training flag, which resulted in the Missing Input error in the Batch Normalization operations. Exporting the model with fixed flag is_training=False solved the problem for the moment.

Its also works for current version:
```
onnx                     1.13.0
onnx-simplifier          0.4.10
onnxruntime              1.13.1
```
