### ISSUE TITLE
onnxruntime compilation with --enable_nvtx_profile fails.

### ISSUE THREAD

**Issue by roberthoenig** [microsoft/onnxruntime#4569]
**Describe the bug**
I am trying to profile an onnxruntime session on the GPU using NVidia's profiling tools. To this end, I want onnxruntime to emit NVTX annotations. I tried to compiler onnxruntime from source by building `Dockerfile.cuda`, with `--enable_nvtx_profile` added to the `./build.sh` call. The build fails with an error during the linking stage:
```.sh
...
[ 98%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/test_main.cc.o
[ 98%] Linking CUDA device code CMakeFiles/onnxruntime_test_all.dir/cmake_device_link.o
[ 98%] Linking CXX executable onnxruntime_test_all
libonnxruntime_framework.a(sequential_executor.cc.o): In function `onnxruntime::SequentialExecutor::Execute(onnxruntime::SessionState const&, std::vector<int, std::allocator<int> > const&, std::vector<OrtValue, std::allocator<OrtValue> > const&, std::vector<int, std::allocator<int> > const&, std::vector<OrtValue, std::allocator<OrtValue> >&, std::unordered_map<unsigned long, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::function<onnxruntime::common::Status (onnxruntime::TensorShape const&, OrtMemoryInfo const&, OrtValue&, bool&)> > > > const&, onnxruntime::logging::Logger const&)':
sequential_executor.cc:(.text._ZN11onnxruntime18SequentialExecutor7ExecuteERKNS_12SessionStateERKSt6vectorIiSaIiEERKS4_I8OrtValueSaIS9_EES8_RSB_RKSt13unordered_mapImSt8functionIFNS_6common6StatusERKNS_11TensorShapeERK13OrtMemoryInfoRS9_RbEESt4hashImESt8equal_toImESaISt4pairIKmSS_EEERKNS_7logging6LoggerE+0x2f8): undefined reference to `vtable for onnxruntime::profile::NvtxRangeCreator'
sequential_executor.cc:(.text._ZN11onnxruntime18SequentialExecutor7ExecuteERKNS_12SessionStateERKSt6vectorIiSaIiEERKS4_I8OrtValueSaIS9_EES8_RSB_RKSt13unordered_mapImSt8functionIFNS_6common6StatusERKNS_11TensorShapeERK13OrtMemoryInfoRS9_RbEESt4hashImESt8equal_toImESaISt4pairIKmSS_EEERKNS_7logging6LoggerE+0x45c): undefined reference to `vtable for onnxruntime::profile::NvtxRangeCreator'
sequential_executor.cc:(.text._ZN11onnxruntime18SequentialExecutor7ExecuteERKNS_12SessionStateERKSt6vectorIiSaIiEERKS4_I8OrtValueSaIS9_EES8_RSB_RKSt13unordered_mapImSt8functionIFNS_6common6StatusERKNS_11TensorShapeERK13OrtMemoryInfoRS9_RbEESt4hashImESt8equal_toImESaISt4pairIKmSS_EEERKNS_7logging6LoggerE+0x3026): undefined reference to `vtable for onnxruntime::profile::NvtxRangeCreator'
sequential_executor.cc:(.text._ZN11onnxruntime18SequentialExecutor7ExecuteERKNS_12SessionStateERKSt6vectorIiSaIiEERKS4_I8OrtValueSaIS9_EES8_RSB_RKSt13unordered_mapImSt8functionIFNS_6common6StatusERKNS_11TensorShapeERK13OrtMemoryInfoRS9_RbEESt4hashImESt8equal_toImESaISt4pairIKmSS_EEERKNS_7logging6LoggerE+0x3046): undefined reference to `vtable for onnxruntime::profile::NvtxRangeCreator'
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_test_all.dir/build.make:3442: recipe for target 'onnxruntime_test_all' failed
make[2]: *** [onnxruntime_test_all] Error 1
make[1]: *** [CMakeFiles/onnxruntime_test_all.dir/all] Error 2
CMakeFiles/Makefile2:383: recipe for target 'CMakeFiles/onnxruntime_test_all.dir/all' failed
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1696, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 1652, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/code/onnxruntime/tools/ci_build/build.py", line 926, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 420, in run_subprocess
    env=my_env, shell=shell)
  File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/code/cmake-3.14.3-Linux-x86_64/bin/cmake', '--build', '/code/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: whatever is provided inDockerfile.cuda
- Visual Studio version (if applicable): /
- GCC/Compiler version (if compiling from source): whatever is provided in Dockerfile.cuda
- CUDA/cuDNN version: whatever is provided in Dockerfile.cuda
- GPU model and memory: NVidia P100, 16GB

**To Reproduce**
```.sh
$ git clone https://github.com/microsoft/onnxruntime.git
$ cd onnxruntime/dockerfiles
$ // edit Dockerfile.cuda by changing `./build.sh ...` to `./build.sh --enable_nvtx_profile ...`
$ docker build -t onnxruntime-source -f Dockerfile.cuda  .
```

**Expected behavior**
I expect onnxruntime to build without error :-).

**Comment by roberthoenig** [comment]
Update: 
* Building `Dockerfile.cuda` without any modifications succeeds on my machine.
* Checking out the [commit](https://github.com/microsoft/onnxruntime/commit/24eda3df3318d86f310918ad9021295d4a5c7898) where NVTX support got introduced, then building `Dockerfile.cuda` with `--enable_nvtx_profile` and 
```
RUN git clone --single-branch --branch ${ONNXRUNTIME_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime &&\
    cd onnxruntime &&\
    git checkout 24eda3df3318d86f310918ad9021295d4a5c7898 &&\
    cd .. &&\
...
```
fails with the same error.

**Comment by roberthoenig** [comment]
Another update: The build succeeds when I run it from this  Nvidia PyTorch NGC container: nvcr.io/nvidia/pytorch:20.07-py3
