### ISSUE TITLE
Fuzzed model takes down the runtime with a SIGSEGV

### ISSUE THREAD

**Issue by Craigacp** [microsoft/onnxruntime#4585]
**Describe the bug**
The attached model file takes down the runtime, in roughly the same place as #4349. This model was generated via the same fuzzing process as before.

**Urgency**
We'd like to deploy a system that accepts untrusted models without failing.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Platform: Java

**To Reproduce**
Open the attached model in a session.
[fuzz_2.onnx.zip](https://github.com/microsoft/onnxruntime/files/4960989/fuzz_2.onnx.zip)

**Expected behavior**
It to throw an OrtException saying the model is invalid.

**Additional context**
The stack trace is:

``` 
Stack: [0x00007000072b4000,0x00007000073b4000],  sp=0x00007000073b1f20,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc++.1.dylib+0x37b37]  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x1b
C  [libonnxruntime.dylib+0x5a7e4f]  onnx::Utils::DataTypeUtils::ToDataTypeString(int)+0xbf
C  [libonnxruntime.dylib+0x5a6abd]  onnx::Utils::DataTypeUtils::ToString(onnx::TypeProto const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x1fd
C  [libonnxruntime.dylib+0x5a6529]  onnx::Utils::DataTypeUtils::ToType(onnx::TypeProto const&)+0x49
C  [libonnxruntime.dylib+0x4ea4f6]  onnxruntime::NodeArg::NodeArg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, onnx::TypeProto const*)+0x1c6
C  [libonnxruntime.dylib+0x4f13de]  onnxruntime::Graph::GetOrCreateNodeArg(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, onnx::TypeProto const*)+0x5e
C  [libonnxruntime.dylib+0x4efc24]  onnxruntime::Graph::Graph(onnxruntime::Model const&, onnx::GraphProto*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, long long, std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, onnxruntime::Graph*, onnxruntime::Node const*, onnxruntime::logging::Logger const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, onnx::FunctionProto const*, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, onnx::FunctionProto const*> > > const&)+0xd64
C  [libonnxruntime.dylib+0x4f0f2e]  onnxruntime::Graph::Graph(onnxruntime::Model const&, onnx::GraphProto*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, int> > > const&, long long, std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, onnxruntime::logging::Logger const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, onnx::FunctionProto const*, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, onnx::FunctionProto const*> > > const&)+0x5e
C  [libonnxruntime.dylib+0x527d17]  onnxruntime::Model::Model(onnx::ModelProto&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::list<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, std::__1::allocator<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection> > > const*, onnxruntime::logging::Logger const&)+0x767
C  [libonnxruntime.dylib+0x529118]  onnxruntime::Model::Load(onnx::ModelProto&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<onnxruntime::Model>&, std::__1::list<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection>, std::__1::allocator<std::__1::shared_ptr<onnxruntime::IOnnxRuntimeOpSchemaCollection> > > const*, onnxruntime::logging::Logger const&)+0x68
C  [libonnxruntime.dylib+0x31ddc]  std::__1::__function::__func<onnxruntime::InferenceSession::Load()::$_4, std::__1::allocator<onnxruntime::InferenceSession::Load()::$_4>, onnxruntime::common::Status (std::__1::shared_ptr<onnxruntime::Model>&)>::operator()(std::__1::shared_ptr<onnxruntime::Model>&)+0x3c
C  [libonnxruntime.dylib+0x1ff92]  onnxruntime::InferenceSession::Load(std::__1::function<onnxruntime::common::Status (std::__1::shared_ptr<onnxruntime::Model>&)>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x182
C  [libonnxruntime.dylib+0x215b0]  onnxruntime::InferenceSession::Load()+0xc0
C  [libonnxruntime.dylib+0x45ec7]  (anonymous namespace)::LoadAndInitializeSession(OrtEnv const*, OrtSessionOptions const*, std::__1::unique_ptr<onnxruntime::InferenceSession, std::__1::default_delete<onnxruntime::InferenceSession> >&, OrtSession**)+0x307
C  [libonnxruntime.dylib+0x45966]  OrtApis::CreateSession(OrtEnv const*, char const*, OrtSessionOptions const*, OrtSession**)+0x336
C  [libonnxruntime4j_jni.dylib+0x4da4]  Java_ai_onnxruntime_OrtSession_createSession__JJLjava_lang_String_2J+0x44
```

The onnx model checker rejects this model as invalid saying:

```
>>> import onnx
>>> model = onnx.load("./Desktop/fuzz_2.onnx")
>>> onnx.checker.check_model(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized data_type (tensor name: index): 71
```

**Comment by snnn** [comment]
https://github.com/onnx/onnx/pull/2724

**Comment by snnn** [comment]
I also did fuzzing on this.

**Comment by Craigacp** [comment]
I'm not sure, is there a way I can test it? I seem to recall the onnx version is tightly tied into the ORT version, so I'm not sure where to modify the build process to get that particular branch pulled in.

**Comment by skottmckay** [comment]
Possibly needs another change in https://github.com/onnx/onnx/pull/2724.

```
std::string DataTypeUtils::ToDataTypeString(int32_t tensor_data_type) {
  TypesWrapper& t = TypesWrapper::GetTypesWrapper();
  auto iter = t.TensorDataTypeToTypeStr().find(tensor_data_type);
  assert(t.TensorDataTypeToTypeStr().end() != iter);
  return iter->second;
}

```
Instead of the `assert` which wouldn't fire in a release build, ToDataTypeString could return an error status (similar to other changes in that PR)

**Comment by Craigacp** [comment]
Did the necessary changes happen in the upstream onnx repo?

**Comment by snnn** [comment]
Will do. Thank you!

**Comment by Craigacp** [comment]
Looks like this model still causes a SIGSEGV in v1.6.0. Did the fix not get merged?

**Comment by askhade** [comment]
@Craigacp : https://github.com/onnx/onnx/pull/3265 should fix this issue but I do not have a way of reproing this. 
Once I send out the PR to pick this onnx commit in ORT can you help me verify this on my branch?

**Comment by Craigacp** [comment]
Sure, I can help. It should be straightforward to check all you do is load in the attached model, if the process (either java or python) dies with a segmentation fault then it's still broken, if you get an exception back out of ORT then it's fixed.
