### ISSUE TITLE
Cmake fail to create symbolic link

### ISSUE THREAD

**Issue by tsaizhenling** [microsoft/onnxruntime#4617]
trying to build onnxruntime on the nvidia xavier nx, with jetpack 4.2 on a microsd
following instructions here https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387
I used `compute_72` and `sm_72` instead

it seems to have mostly completed, but have problems with linking
```
[ 98%] Built target onnxruntime_test_framework_session_without_environment_standalone
[100%] Linking CXX shared library libnvonnxparser.so
CMake Error: failed to create symbolic link 'libnvonnxparser.so.6': function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
CMake Error: failed to create symbolic link 'libnvonnxparser.so': function not implemented
CMake Error: cmake_symlink_library: System Error: Function not implemented
external/onnx-tensorrt/CMakeFiles/nvonnxparser.dir/build.make:183: recipe for target 'external/onnx-tensorrt/libnvonnxparser.so.6.0.1' failed
make[2]: *** [external/onnx-tensorrt/libnvonnxparser.so.6.0.1] Error 1
make[2]: *** Deleting file 'external/onnx-tensorrt/libnvonnxparser.so.6.0.1'
CMakeFiles/Makefile2:2158: recipe for target 'external/onnx-tensorrt/CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/media/aaeon/6463-6563/onnxruntime/tools/ci_build/build.py", line 1043, in <module>
    sys.exit(main())
  File "/media/aaeon/6463-6563/onnxruntime/tools/ci_build/build.py", line 975, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/media/aaeon/6463-6563/onnxruntime/tools/ci_build/build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "/media/aaeon/6463-6563/onnxruntime/tools/ci_build/build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/media/aaeon/6463-6563/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

how do I fix the linking error?

**Comment by jywu-msft** [comment]
please follow the latest instructions for JetPack 4.3 (not 4.2)
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#jetson-tx1tx2nano-arm64-builds
