### ISSUE TITLE
Error while building release 1.3.1 from given source code.

### ISSUE THREAD

**Issue by Karnav123** [microsoft/onnxruntime#4642]
**Describe the bug**
I am trying to build onnxruntime from the version 1.3.1 source code given on the release branch page. But it is giving error and I am not able to figure out why. However if I build it from master branch 1.4.0 it successfully builds. I need version 1.3.1 dlls and headers.
**Urgency**
It is urgent for me.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):  Build from source
- ONNX Runtime version: 1.3.1
- Python version:
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Download the source code from https://github.com/microsoft/onnxruntime/archive/v1.3.1.zip and insatll cmake version 3.18 and run the build.bat script in Visual studio developer cmd.

**Expected behavior**
It should build successfully.

**Screenshots**
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

c:\apps\MVS16>D:\onnruntime131\onnxruntime-rel-1.3.1\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019"
2020-07-28 19:11:52,819 Build [DEBUG] - Defaulting to running update, build [and test for native builds].
2020-07-28 19:11:52,848 Build [INFO] - Build started
2020-07-28 19:11:52,848 Build [DEBUG] - Running subprocess in 'D:\onnruntime131\onnxruntime-rel-1.3.1'
['git', 'submodule', 'sync', '--recursive']
2020-07-28 19:11:54,555 Build [DEBUG] - Subprocess completed. Return code=0
2020-07-28 19:11:54,555 Build [DEBUG] - Running subprocess in 'D:\onnruntime131\onnxruntime-rel-1.3.1'
['git', 'submodule', 'update', '--init', '--recursive']
2020-07-28 19:11:56,147 Build [DEBUG] - Subprocess completed. Return code=0
2020-07-28 19:11:56,147 Build [INFO] - Generating CMake build tree
2020-07-28 19:11:56,148 Build [DEBUG] - Running subprocess in 'D:\onnruntime131\onnxruntime-rel-1.3.1\\build\Windows\RelWithDebInfo'
['D:\\onnruntime131\\onnxruntime-rel-1.3.1\\onnxruntime\\bin\\cmake.EXE', 'D:\\onnruntime131\\onnxruntime-rel-1.3.1\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=C:\\apps\\Python37\\python.exe', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_NGRAPH=OFF', '-Donnxruntime_USE_OPENVINO=OFF', '-Donnxruntime_USE_OPENVINO_MYRIAD=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP16=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_VAD_M=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F=OFF', '-Donnxruntime_USE_OPENVINO_BINARY=OFF', '-Donnxruntime_USE_NNAPI=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_FOR_WINDOWS_STORE=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_E2E_TESTS=OFF', '-Donnxruntime_USE_HOROVOD=OFF', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo']
-- The C compiler identification is MSVC 19.20.27508.1
-- The CXX compiler identification is MSVC 19.20.27508.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: c:/apps/MVS16/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: c:/apps/MVS16/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_D2FH4
-- Performing Test HAS_D2FH4 - Success
Disabling /d2FH4
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test HAS_QSPECTRE
-- Performing Test HAS_QSPECTRE - Failed
-- Performing Test HAS_GUARD_CF
-- Performing Test HAS_GUARD_CF - Success
Use gtest from submodule
CMake Error at CMakeLists.txt:310 (add_subdirectory):
  The source directory

    D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/googletest

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:311 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock


CMake Error at CMakeLists.txt:312 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock_main


CMake Error at CMakeLists.txt:313 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest


CMake Error at CMakeLists.txt:314 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest_main


CMake Error at CMakeLists.txt:315 (add_library):
  add_library cannot create ALIAS target "GTest::gmock" because target
  "gmock" does not already exist.


CMake Error at CMakeLists.txt:316 (add_library):
  add_library cannot create ALIAS target "GTest::gmock_main" because target
  "gmock_main" does not already exist.


CMake Error at CMakeLists.txt:317 (add_library):
  add_library cannot create ALIAS target "GTest::gtest" because target
  "gtest" does not already exist.


CMake Error at CMakeLists.txt:318 (add_library):
  add_library cannot create ALIAS target "GTest::gtest_main" because target
  "gtest_main" does not already exist.


-- Found PythonInterp: C:/apps/Python37/python.exe (found suitable version "3.7.4", minimum required is "3.4")
Use protobuf from submodule
CMake Error at CMakeLists.txt:397 (add_subdirectory):
  add_subdirectory given source
  "D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/protobuf/cmake"
  which is not an existing directory.


CMake Error at CMakeLists.txt:409 (add_library):
  add_library cannot create ALIAS target "protobuf::libprotobuf" because
  target "libprotobuf-lite" does not already exist.


CMake Error at CMakeLists.txt:454 (add_subdirectory):
  The source directory

    D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/date

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:465 (add_subdirectory):
  The source directory

    D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/re2

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:466 (set_target_properties):
  set_target_properties Can not find target to add properties to: re2


CMake Error at CMakeLists.txt:467 (add_library):
  add_library cannot create ALIAS target "re2::re2" because target "re2" does
  not already exist.


CMake Error at onnx/CMakeLists.txt:38 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.


-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/apps/MVS16/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/ml64.exe
-- Configuring incomplete, errors occurred!
See also "D:/onnruntime131/onnxruntime-rel-1.3.1/build/Windows/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "D:/onnruntime131/onnxruntime-rel-1.3.1/build/Windows/RelWithDebInfo/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "D:\onnruntime131\onnxruntime-rel-1.3.1\\tools\ci_build\build.py", line 1746, in <module>
    sys.exit(main())
  File "D:\onnruntime131\onnxruntime-rel-1.3.1\\tools\ci_build\build.py", line 1633, in main
    args, cmake_extra_args)
  File "D:\onnruntime131\onnxruntime-rel-1.3.1\\tools\ci_build\build.py", line 812, in generate_build_tree
    cwd=config_build_dir)
  File "D:\onnruntime131\onnxruntime-rel-1.3.1\\tools\ci_build\build.py", line 396, in run_subprocess
    env=my_env, shell=shell)
  File "C:\apps\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\onnruntime131\\onnxruntime-rel-1.3.1\\onnxruntime\\bin\\cmake.EXE', 'D:\\onnruntime131\\onnxruntime-rel-1.3.1\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=C:\\apps\\Python37\\python.exe', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_NGRAPH=OFF', '-Donnxruntime_USE_OPENVINO=OFF', '-Donnxruntime_USE_OPENVINO_MYRIAD=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP16=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_VAD_M=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F=OFF', '-Donnxruntime_USE_OPENVINO_BINARY=OFF', '-Donnxruntime_USE_NNAPI=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_FOR_WINDOWS_STORE=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_E2E_TESTS=OFF', '-Donnxruntime_USE_HOROVOD=OFF', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo']' returned non-zero exit status 1.

c:\apps\MVS16>
```

**Comment by skottmckay** [comment]
D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/googletest should have sync'd the googletest repo and there should be a number of files in that directory, including CMakeLists.txt. Basically everything you see here: https://github.com/google/googletest

You could try running `git submodule sync --recursive` and `git submodule update --init --recursive` manually to see if that pulls in the necessary files. The build script should do that though.

**Comment by Karnav123** [comment]
> D:/onnruntime131/onnxruntime-rel-1.3.1/cmake/external/googletest should have sync'd the googletest repo and there should be a number of files in that directory, including CMakeLists.txt. Basically everything you see here: https://github.com/google/googletest
> 
> You could try running `git submodule sync --recursive` and `git submodule update --init --recursive` manually to see if that pulls in the necessary files. The build script should do that though.

I tried running the above commands but it does not pull the requirements. Also, do we need to run `git init` after downloading the source code from the release branch?

**Comment by Karnav123** [comment]
I have successfully built the source code. Some tests are failing though.

**Comment by skottmckay** [comment]
The tests pass in CI builds. What particular tests fail and with what error?
