### ISSUE TITLE
Bad node spec for onnx model after using the calibration/quantization tool

### ISSUE THREAD

**Issue by jwpleow** [microsoft/onnxruntime#4803]
**Describe the bug**
After using the calibrate/quantize tool, the model that comes out fails `onnx.checker.check_model()`, but still works fine during inferencing. A similar issue has been reported before at https://github.com/onnx/onnx/issues/2371
```
Traceback (most recent call last):
  File "asdf.py", line 4, in <module>
    onnx.checker.check_model(model)
  File "/home/user/anaconda3/envs/nightlytorch/lib/python3.8/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: No opset import for domain ''

==> Context: Bad node spec: input: "input" output: "input_quantized" output: "input_scale" output: "input_zero_point" name: "input_QuantizeLinear" op_type: "DynamicQuantizeLinear"
```

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 and 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v1.3.0 and v1.4.0
- Python version: 3.8.3
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/models/pretrained/version-RFB-640.pth -> converted to onnx 

[Original model](https://drive.google.com/file/d/1KJJPe0-j1_kx-nJZfVkgSZth52U88ZBX/view?usp=sharing)
[Calibrated and quantized model which fails `onnx.helper.check_model`](https://drive.google.com/file/d/1BsJ7NyExvIxFeISg2WcVW8ytSywEuTAM/view?usp=sharing)
**Expected behavior**
The model to pass the check.

**Comment by hariharans29** [comment]
@yufenglee - can you please take a look ?

**Comment by i-amgeek** [comment]
I am getting this error too. 

```

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-11-d63b1cbc7f73> in <module>
----> 1 onnx.checker.check_model(quantized_model)

~/anaconda3/envs/pytorch_quant/lib/python3.8/site-packages/onnx/checker.py in check_model(model, full_check)
     91         m = onnx.load(model)
     92     else:
---> 93         C.check_model(model.SerializeToString())
     94         m = model
     95     if full_check:

ValidationError: No opset import for domain ''

==> Context: Bad node spec: input: "input" output: "input_ReduceMin:0" name: "input_ReduceMin" op_type: "ReduceMin" attribute { name: "keepdims" i: 0 type: INT }

```

## To reproduce:

```
class Model(nn.Module):

    def __init__(self, in_channels, out_channels, kernel_size, stride, padding):
        super().__init__()
        self.conv = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
            )
        
    def forward(self, x):
        return self.conv(x)

model = Model(3, 5, 3, 1, (1,2))



dummy_input = torch.randn(1, 3, 224, 224)
model.eval()
torch.onnx.export(
    model,
    dummy_input,
    "model.onnx",
    export_params = True,
    training = False,
    do_constant_folding = True,
    keep_initializers_as_inputs = False,
)

import onnx
from quantize import quantize, QuantizationMode
model = onnx.load('model.onnx')

# Quantize
quantized_model = quantize(
    model,
    per_channel = False,
    quantization_mode = QuantizationMode.IntegerOps,
    static = False,
)

onnx.checker.check_model(quantized_model)

```

**Comment by cannguyen275** [comment]
`==> Context: Bad node spec: input: "input0" output: "input0_ReduceMin:0" name: "input0_ReduceMin" op_type: "ReduceMin" attribute { name: "keepdims" i: 0 type: INT }`

I got this error, too. This is my code to quantize:
```python
import onnx
from quantize import quantize, QuantizationMode

path_to_model = 'model.onnx'
predictor = onnx.load(path_to_model)
quantized_model = quantize(predictor,
                           quantization_mode=QuantizationMode.IntegerOps, static=False)
# Save the quantized model
onnx.save(quantized_model, 'model_quantized.onnx')
```
Any idea to fix? Thanks!

**Comment by FerdinandZhong** [comment]
I have got the same error when doing quantization. No matter static or dynamic. 
```
quantized_model = quantize(
        model,
        quantization_mode=QuantizationMode.IntegerOps,
        static=True,
        quantization_params=quantization_params_dict,
        nodes_to_quantize=list(quantization_params_dict.keys())
    )
```

error: 
```
onnx.onnx_cpp2py_export.checker.ValidationError: No opset import for domain ''

==> Context: Bad node spec: input: "import/input_1:0" output: "import/input_1__12:0" name: "import/input_1__12" op_type: "Transpose" attribute { name: "perm" ints: 0 ints: 2 ints: 3 ints: 1 type: INTS }
```

- ONNX Runtime version: 1.4.0

May I know what causes the error?
