### ISSUE TITLE
Using AAR on android gives java.lang.IllegalStateException: Unsupported arch:armv7l exception

### ISSUE THREAD

**Issue by s94285** [microsoft/onnxruntime#4976]
**Describe the bug**
Using AAR on android gives java.lang.IllegalStateException: Unsupported arch:armv7l exception.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.7.5
- GCC/Compiler version (if compiling from source): 6.5.0

**To Reproduce**
Build AAR using following command
`./build.sh --android --android_sdk_path /home/kevin/Android/Sdk --android_ndk_path /home/kevin/Android/Sdk/ndk/21.2.6472646 --android_abi armeabi-v7a --android_api 28 --use_nnapi --build_java`
In android app:
```java
try(OrtEnvironment env = OrtEnvironment.getEnvironment();
    OrtSession.SessionOptions opts = new OrtSession.SessionOptions()){
    opts.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.BASIC_OPT);
    opts.addNnapi();
} catch (OrtException e) {
    e.printStackTrace();
}
```

**Expected behavior**
I checked the OnnxRuntime.class where the exception threw.
Seems like it support for amd64/x86_64/x86 only.
What about other arch like aarch64 and armv7l ?

**Additional context**
```
2020-08-31 10:13:20.611 2992-2992/com.example.onnxtest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.onnxtest, PID: 2992
    java.lang.ExceptionInInitializerError
        at ai.onnxruntime.OnnxRuntime.init(Unknown Source:0)
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:24)
        at ai.onnxruntime.OrtEnvironment.getEnvironment(OrtEnvironment.java:45)
        at com.example.onnxtest.MainActivity.onCreate(MainActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Unsupported arch:armv7l
        at ai.onnxruntime.OnnxRuntime.initOsArch(OnnxRuntime.java:65)
        at ai.onnxruntime.OnnxRuntime.<clinit>(OnnxRuntime.java:36)
        at ai.onnxruntime.OnnxRuntime.init(Unknown Source:0) 
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:24) 
        at ai.onnxruntime.OrtEnvironment.getEnvironment(OrtEnvironment.java:45) 
        at com.example.onnxtest.MainActivity.onCreate(MainActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6751) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by gwang-msft** [comment]
This change https://github.com/microsoft/onnxruntime/pull/3849 added initOsArch which will not handle Android OS arch
