### ISSUE TITLE
onnxruntime tools + transformers + tensorflow: inference for optimized DistilBert fails

### ISSUE THREAD

**Issue by vgrabovets** [microsoft/onnxruntime#4980]
**Describe the bug**
After running inference with optimized onnx version of tensorflow DistilBert from transformers it fails with `INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input`

Bert model expects 3 types of input (input_ids, attention_mask, token_type_ids), but it can work with only 2 (input_ids, attention_mask). 

- When using 3 inputs it works with initial tensorflow/keras version, converted onnx model from keras2onnx and optimized model by onnxruntime tools - everything is fine.
- When using 2 inputs it works with initial tensorflow/keras version, converted onnx model from keras2onnx and fails with optimized model by onnxruntime tools (`INVALID_ARGUMENT : Non-zero status code returned while running EmbedLayerNormalization node. Name:'EmbedLayer' Status Message: input index out of range`)

OK, I can use 3 inputs, though I don't need the 3rd one. But with DistilBert there is a problem:
- You can't use 3 inputs because initial transformer model doesn't support it https://huggingface.co/transformers/model_doc/distilbert.html
- When using 2 inputs it works with initial tensorflow/keras version, converted onnx model from keras2onnx and fails with optimized model by onnxruntime tools (`INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input`). But if batch size is 1, then it works.
Check debug info below.

**Urgency**
Not really but would be nice.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.5
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX1070, 8 GB

**To Reproduce**
```
# pip install keras2onnx==1.7.0 onnxruntime==1.4.0 tensorflow==2.3.0 onnxruntime-tools==1.4.2 transformers==3.0.2
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import logging
import tempfile

import keras2onnx
import onnxruntime
import tensorflow as tf

from onnxruntime_tools import optimizer
from transformers import (
    BertTokenizer, DistilBertTokenizer, TFBertForTokenClassification,
    TFDistilBertForTokenClassification,
)

# logging.basicConfig(level=logging.DEBUG)
for name, logger in logging.root.manager.loggerDict.items():
    logger.disabled=True

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('onnx_issue')
logger.setLevel(logging.DEBUG)

sentences = [
    'ONNX Runtime automatically applies most optimizations while loading a transformer model',
    'Some of the latest optimizations that have not yet been integrated into ONNX Runtime are available in this tool that tunes models for the best performance.',
]

MODELS = ('bert-base-uncased', 'distilbert-base-uncased')

ONNX_MODEL_PATH = tempfile.tempdir + '/model.onnx'
OPTIMIZED_MODEL_PATH = tempfile.tempdir + '/optimized_model.onnx'

MODEL_INPUT_VARIABLES = [
    ('input_ids', 'attention_mask', 'token_type_ids'),
    ('input_ids', 'attention_mask'),
]

MAX_LENGTH = 64
NUM_LABELS = 5


def build_model(model_name):
    if 'distil' in model_name:
        model = TFDistilBertForTokenClassification.from_pretrained(
            model_name,
            num_labels=NUM_LABELS,
        )
    else:
        model = TFBertForTokenClassification.from_pretrained(
            model_name,
            num_labels=NUM_LABELS,
        )
    model.layers[-1].activation = tf.keras.activations.softmax

    model_optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5)
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
    metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
    model.compile(optimizer=model_optimizer, loss=loss, metrics=[metric])

    return model


if __name__ == '__main__':
    for model_name in MODELS:
        logger.debug(f'MODEL: {model_name}')

        if 'distilbert' in model_name:
            tokenizer = DistilBertTokenizer.from_pretrained(model_name)
        else:
            tokenizer = BertTokenizer.from_pretrained(model_name)

        inputs = tokenizer.batch_encode_plus(
            sentences,
            add_special_tokens=True,
            max_length=MAX_LENGTH,
            padding='max_length',
            truncation=True,
            return_tensors='tf',
            return_token_type_ids=True,
        )

        input_ids = inputs['input_ids']
        attention_mask = inputs['attention_mask']
        token_type_ids = inputs['token_type_ids']

        model = build_model(model_name)

        for model_variables in MODEL_INPUT_VARIABLES:
            logger.debug(f'model input: {model_variables}')
            model._saved_model_inputs_spec = None

            try:
                if len(model_variables) == 3:
                    prediction = model((input_ids, attention_mask, token_type_ids))
                else:
                    prediction = model((input_ids, attention_mask))
                logger.debug(f'prediction with tensorflow successful')

            except Exception as err:
                logger.exception(f'tensorflow inference failed\n{err}')
                continue

            onnx_model = keras2onnx.convert_keras(model, model.name)

            keras2onnx.save_model(onnx_model, ONNX_MODEL_PATH)
            logger.debug(f'keras2onnx saved model')

            sess_options = onnxruntime.SessionOptions()
            session = onnxruntime.InferenceSession(
                ONNX_MODEL_PATH,
                sess_options,
                providers=['CPUExecutionProvider'],
            )

            if len(model_variables) == 3:
                input_names = [_input.name for _input in session.get_inputs()]
                input_name1, input_name2, input_name3 = input_names

                predictions = session.run(None, {
                    input_name1: input_ids.numpy(),
                    input_name2: attention_mask.numpy(),
                    input_name3: token_type_ids.numpy(),
                })
            else:
                input_names = [_input.name for _input in session.get_inputs()]
                input_name1, input_name2 = input_names

                predictions = session.run(None, {
                    input_name1: input_ids.numpy(),
                    input_name2: attention_mask.numpy(),
                })

            logger.debug('inference with onnx model successful')

            optimized_model = optimizer.optimize_model(
                ONNX_MODEL_PATH,
                model_type='bert_keras',
                num_heads=12,
                hidden_size=768,
            )
            optimized_model.use_dynamic_axes()
            optimized_model.save_model_to_file(OPTIMIZED_MODEL_PATH)

            logger.debug('onnxruntime tools optimized model')

            session = onnxruntime.InferenceSession(
                OPTIMIZED_MODEL_PATH,
                sess_options,
                providers=['CPUExecutionProvider'],
            )

            try:
                if len(model_variables) == 3:
                    predictions = session.run(None, {
                        input_name1: input_ids.numpy(),
                        input_name2: attention_mask.numpy(),
                        input_name3: token_type_ids.numpy(),
                    })
                else:
                    predictions = session.run(None, {
                        input_name1: input_ids.numpy(),
                        input_name2: attention_mask.numpy(),
                    })

                logger.debug('inference with optimized model successful')

            except Exception as err:
                logger.exception(f'inference with optimized model failed\n{err}')

```

**Expected behavior**
onnxruntime runs inference with DistilBert model from transformers (tensorflow/keras version), optimized by onnxruntime tools on batches with size more than 1.

**Screenshots**
```
DEBUG:onnx_issue:MODEL: bert-base-uncased
DEBUG:onnx_issue:model input: ('input_ids', 'attention_mask', 'token_type_ids')
DEBUG:onnx_issue:prediction with tensorflow successful
INFO:keras2onnx:The ONNX operator number change on the optimization: 2445 -> 1614
DEBUG:onnx_issue:keras2onnx saved model
DEBUG:onnx_issue:inference with onnx model successful
DEBUG:onnx_issue:onnxruntime tools optimized model
DEBUG:onnx_issue:inference with optimized model successful

DEBUG:onnx_issue:model input: ('input_ids', 'attention_mask')
DEBUG:onnx_issue:prediction with tensorflow successful
INFO:keras2onnx:The ONNX operator number change on the optimization: 2452 -> 1620
DEBUG:onnx_issue:keras2onnx saved model
DEBUG:onnx_issue:inference with onnx model successful
DEBUG:onnx_issue:onnxruntime tools optimized model
ERROR:onnx_issue:inference with optimized model failed
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running EmbedLayerNormalization node. Name:'EmbedLayer' Status Message: input index out of range
Traceback (most recent call last):
  File "onnx_issue.py", line 164, in <module>
    input_name2: attention_mask.numpy(),
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running EmbedLayerNormalization node. Name:'EmbedLayer' Status Message: input index out of range

DEBUG:onnx_issue:MODEL: distilbert-base-uncased
DEBUG:onnx_issue:model input: ('input_ids', 'attention_mask', 'token_type_ids')
ERROR:onnx_issue:tensorflow inference failed
Traceback (most recent call last):
  File "onnx_issue.py", line 96, in <module>
    prediction = model((input_ids, attention_mask, token_type_ids))
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py", line 832, in call
    training=training,
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/transformers/modeling_tf_distilbert.py", line 489, in call
    raise NotImplementedError
NotImplementedError

DEBUG:onnx_issue:model input: ('input_ids', 'attention_mask')
DEBUG:onnx_issue:prediction with tensorflow successful
INFO:keras2onnx:The ONNX operator number change on the optimization: 1282 -> 852
DEBUG:onnx_issue:keras2onnx saved model
DEBUG:onnx_issue:inference with onnx model successful
DEBUG:onnx_issue:onnxruntime tools optimized model
ERROR:onnx_issue:inference with optimized model failed
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input
Traceback (most recent call last):
  File "onnx_issue.py", line 164, in <module>
    input_name2: attention_mask.numpy(),
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input
```

**Comment by tianleiwu** [comment]
@wangyems to take a look since he is working on DistilBert optimization.

**Comment by wangyems** [comment]
> @wangyems to take a look since he is working on DistilBert optimization.

Sure I'll take a look

**Comment by vgrabovets** [comment]
It works, thank you.
