### ISSUE TITLE
DistilBERT: use_dynamic_axes doesn't work

### ISSUE THREAD

**Issue by vgrabovets** [microsoft/onnxruntime#5152]
**Describe the bug**
@wangyems it's related to https://github.com/microsoft/onnxruntime/issues/4980
Inference for batch with second dimension (sentence length) other than the one used during training for DistilBERT from transformers (keras/tensorflow) doesn't work: `onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_2 for the following indices
 index: 1 Got: 106 Expected: 128`.
For BERT it works, though. Take a look at debug info. 
Also I can confirm that it works for DistilBERT pytorch version.
I traced it up here: https://github.com/microsoft/onnxruntime/blob/9392aa2f64171eb6734e62e9a844b2e6a4618353/onnxruntime/python/tools/transformers/onnx_model_bert.py#L161 For DistilBERT `bert_graph_inputs` is empty, but even if I hardcode input names, than there is error inside C code regarding broadcasting.

**Urgency**
Not urgent but would be appreciated.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.5
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0, with update from https://github.com/microsoft/onnxruntime/pull/5123
- Python version: 3.7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX1070, 8 GB

**To Reproduce**
```
# pip install keras2onnx==1.7.0 onnxruntime==1.4.0 tensorflow==2.3.0 onnxruntime-tools==1.4.2 transformers==3.0.2

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import logging
import tempfile

import keras2onnx
import onnxruntime
import tensorflow as tf

from onnxruntime_tools import optimizer
from transformers import (
    BertTokenizer, DistilBertTokenizer, TFBertForTokenClassification,
    TFDistilBertForTokenClassification,
)

# logging.basicConfig(level=logging.DEBUG)
for name, logger in logging.root.manager.loggerDict.items():
    logger.disabled = True

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('onnx_issue')
logger.setLevel(logging.DEBUG)

sentences = [
    'ONNX Runtime automatically applies most optimizations while loading a transformer model',
    'Some of the latest optimizations that have not yet been integrated into ONNX Runtime are available in this tool that tunes models for the best performance.',
]

MODELS = (
    'bert-base-uncased',
    'distilbert-base-uncased',
)

ONNX_MODEL_PATH = tempfile.tempdir + '/model.onnx'
OPTIMIZED_MODEL_PATH = tempfile.tempdir + '/optimized_model.onnx'

MAX_LENGTH = 64
LENGTH_VARIATIONS = (MAX_LENGTH, MAX_LENGTH - 10)
NUM_LABELS = 5


def build_model(model_name):
    if 'distil' in model_name:
        model = TFDistilBertForTokenClassification.from_pretrained(
            model_name,
            num_labels=NUM_LABELS,
        )
    else:
        model = TFBertForTokenClassification.from_pretrained(
            model_name,
            num_labels=NUM_LABELS,
        )
    model.layers[-1].activation = tf.keras.activations.softmax

    model_optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5)
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False)
    metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
    model.compile(optimizer=model_optimizer, loss=loss, metrics=[metric])

    return model


if __name__ == '__main__':
    for model_name in MODELS:
        logger.debug(f'MODEL: {model_name}')

        if 'distil' in model_name:
            tokenizer = DistilBertTokenizer.from_pretrained(model_name)
        else:
            tokenizer = BertTokenizer.from_pretrained(model_name)

        inputs = tokenizer.batch_encode_plus(
            sentences,
            add_special_tokens=True,
            max_length=MAX_LENGTH,
            padding='max_length',
            truncation=True,
            return_tensors='tf',
            return_token_type_ids=True,
        )

        input_ids = inputs['input_ids']
        attention_mask = inputs['attention_mask']
        token_type_ids = inputs['token_type_ids']

        model = build_model(model_name)

        model._saved_model_inputs_spec = None

        try:
            if 'distil' not in model_name:
                prediction = model((input_ids, attention_mask, token_type_ids))
            else:
                prediction = model((input_ids, attention_mask))
            logger.debug(f'inference with tensorflow successful')

        except Exception as err:
            logger.exception(f'tensorflow inference failed\n{err}')
            continue

        onnx_model = keras2onnx.convert_keras(model, model.name)

        keras2onnx.save_model(onnx_model, ONNX_MODEL_PATH)
        logger.debug(f'keras2onnx saved model')

        sess_options = onnxruntime.SessionOptions()
        session = onnxruntime.InferenceSession(
            ONNX_MODEL_PATH,
            sess_options,
            providers=['CPUExecutionProvider'],
        )

        if 'distil' not in model_name:
            input_names = [_input.name for _input in session.get_inputs()]
            input_name1, input_name2, input_name3 = input_names

            predictions = session.run(None, {
                input_name1: input_ids.numpy(),
                input_name2: attention_mask.numpy(),
                input_name3: token_type_ids.numpy(),
            })
        else:
            input_names = [_input.name for _input in session.get_inputs()]
            input_name1, input_name2 = input_names

            predictions = session.run(None, {
                input_name1: input_ids.numpy(),
                input_name2: attention_mask.numpy(),
            })

        logger.debug('inference with onnx model successful')

        optimized_model = optimizer.optimize_model(
            ONNX_MODEL_PATH,
            model_type='bert_keras',
            num_heads=12,
            hidden_size=768,
        )
        optimized_model.use_dynamic_axes()
        optimized_model.save_model_to_file(OPTIMIZED_MODEL_PATH)

        logger.debug('onnxruntime tools optimized model')

        session = onnxruntime.InferenceSession(
            OPTIMIZED_MODEL_PATH,
            sess_options,
            providers=['CPUExecutionProvider'],
        )

        for length in LENGTH_VARIATIONS:
            logger.debug(
                'max sentence length %s; second dimension in test batch: %s',
                MAX_LENGTH,
                length,
            )

            try:
                if 'distil' not in model_name:
                    predictions = session.run(None, {
                        input_name1: input_ids.numpy()[:, :length],
                        input_name2: attention_mask.numpy()[:, :length],
                        input_name3: token_type_ids.numpy()[:, :length],
                    })
                else:
                    predictions = session.run(None, {
                        input_name1: input_ids.numpy()[:, :length],
                        input_name2: attention_mask.numpy()[:, :length],
                    })

                logger.debug('inference with optimized model successful')

            except Exception as err:
                logger.exception(f'inference with optimized model failed\n{err}')

```

**Expected behavior**
Inference for DistilBERT works for batches with second dimension length (sentence length) other than the one used during training. As it does for BERT.

**Screenshots**
```
DEBUG:onnx_issue:MODEL: bert-base-uncased
DEBUG:onnx_issue:inference with tensorflow successful
INFO:keras2onnx:The ONNX operator number change on the optimization: 2445 -> 1614
DEBUG:onnx_issue:keras2onnx saved model
DEBUG:onnx_issue:inference with onnx model successful
DEBUG:onnx_issue:onnxruntime tools optimized model
DEBUG:onnx_issue:max length 64; second dimension shape in test batch 64
DEBUG:onnx_issue:inference with optimized model successful
DEBUG:onnx_issue:max length 64; second dimension shape in test batch 54
DEBUG:onnx_issue:inference with optimized model successful

DEBUG:onnx_issue:MODEL: distilbert-base-uncased
DEBUG:onnx_issue:inference with tensorflow successful
INFO:keras2onnx:The ONNX operator number change on the optimization: 1282 -> 852
DEBUG:onnx_issue:keras2onnx saved model
DEBUG:onnx_issue:inference with onnx model successful
DEBUG:onnx_issue:onnxruntime tools optimized model
DEBUG:onnx_issue:max length 64; second dimension shape in test batch 64
DEBUG:onnx_issue:inference with optimized model successful
DEBUG:onnx_issue:max length 64; second dimension shape in test batch 54
ERROR:onnx_issue:inference with optimized model failed
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_2 for the following indices
 index: 1 Got: 54 Expected: 64
 Please fix either the inputs or the model.
Traceback (most recent call last):
  File "onnx_issue2.py", line 168, in <module>
    input_name2: attention_mask.numpy()[:, :length],
  File "/mnt/ubuntu_storage/models/ner/env/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_2 for the following indices
 index: 1 Got: 54 Expected: 64
 Please fix either the inputs or the model.
```

**Comment by debjyoti003** [comment]
@vgrabovets did you find the solution for this?

**Comment by vgrabovets** [comment]
> @vgrabovets did you find the solution for this?

I switched to Pytorch, there were no issues with conversion to ONNX.
