### ISSUE TITLE
Onnxruntime failed on the torch.mean function

### ISSUE THREAD

**Issue by zheng-ningxin** [microsoft/onnxruntime#5268]
**Describe the bug**
I try to run the mean function in onnxruntime-gpu and get the following error:
```
2020-09-23 12:32:48.283629600 [E:onnxruntime:Default, cuda_call.cc:119 CudaCall] CUDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=g3 ; expr=cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, reinterpret_cast<CudaT*>(output.template MutableData<T>()));
2020-09-23 12:32:48.283689300 [E:onnxruntime:, sequential_executor.cc:309 Execute] Non-zero status code returned while running ReduceMean node. Name:'' Status Message: CUDNN error executing cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, reinterpret_cast<CudaT*>(output.template MutableData<T>()))
Traceback (most recent call last):
  File "tmp.py", line 34, in <module>
    main()
  File "tmp.py", line 31, in main
    _ = sess.run(None, data)
  File "/home/core/anaconda3/envs/latency/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running ReduceMean node. Name:'' Status Message: CUDNN error executing cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, reinterpret_cast<CudaT*>(output.template MutableData<T>()))
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.7.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CuDNN 7.6.5
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

```
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
import os
import yaml
import json
import torch
import argparse
import torch.nn as nn
import onnxruntime

class MeanModule(nn.Module):
    def forward(self, x):
        # return x.mean([2, 3])
        return torch.mean(x, [2, 3])

def main():

    model = MeanModule()
    dummy_input = torch.ones(1, 3, 224, 224)
    dummy_output = model(dummy_input)
    onnx_model = '/tmp/onnx.onnx'
    torch.onnx.export(model, dummy_input, onnx_model)
    sess = onnxruntime.InferenceSession(onnx_model)
    sess.set_providers(['CUDAExecutionProvider'])
    inputs = sess.get_inputs()
 
    in_name = inputs[0].name
    # generate the inputs for onnx engine
    data = {}
    data[in_name] = dummy_input.detach().cpu().numpy()
    _ = sess.run(None, data)

if __name__ == '__main__':
    main()

```
onnx file:
[onnx.zip](https://github.com/microsoft/onnxruntime/files/5268123/onnx.zip)

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by tianleiwu** [comment]
The python script works well on my machines. I cannot reproduce the issue in both Windows and Linux machines.

Here is my environment with Cuda 10.1 and cuDNN 7.6.5:
```
{
 "python": "3.7.6.final.0 (64 bit)",
  "os": "Windows-10-10.0.19041-SP0",
  "onnxruntime": {
    "version": "1.4.0",
    "support_gpu": true
  },
  "pytorch": {
    "version": "1.6.0",
    "support_gpu": true,
    "cuda": "10.1"
  }
}
```
