### ISSUE TITLE
`make install` does not install `libonnxruntime_providers_shared.so` and `libonnxruntime_providers_tensorrt.so`

### ISSUE THREAD

**Issue by Hao-Yan** [microsoft/onnxruntime#5270]
Steps to repro:

- Sync to latest master
- Run `./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu --parallel --config Release --skip_submodule_sync  --skip_tests --build_shared_lib`
- Go to `build/Linux/Release/` and run `make install`

Expected result: 

`libonnxruntime_providers_shared.so` and `libonnxruntime_providers_tensorrt.so` should also be in the install folder.

Actual result:

![image](https://user-images.githubusercontent.com/6327453/94051733-d04a4b00-fd8c-11ea-8df9-0c21f01f3cd9.png)

**Comment by BharathJaina** [comment]
I'm also facing the build failure issue with the  docker container for the latest release, using the command ` docker build **--no-cache** -t onnxruntime-trt -f Dockerfile.tensorrt .`

Here are logs before failing:
Scanning dependencies of target onnxruntime_providers_shared
[ 76%] Building CXX object CMakeFiles/onnxruntime_providers_shared.dir/code/onnxruntime/onnxruntime/core/providers/shared/common.cc.o
[ 76%] Linking CXX shared library libonnxruntime_providers_shared.so
[ 76%] Built target onnxruntime_providers_shared
Scanning dependencies of target nvonnxparser_static
[ 76%] Building CXX object external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/NvOnnxParser.cpp.o
[ 76%] Building CXX object external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/ModelImporter.cpp.o
[ 76%] Building CXX object external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importConvTranspose(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:681:12: error: ‘class nvinfer1::IDeconvolutionLayer’ has no member named ‘setDilationNd’
     layer->setDilationNd(dilations);
            ^~~~~~~~~~~~~
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importGemm(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:1064:18: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
         squeeze->setZeroIsPlaceholder(false);
                  ^~~~~~~~~~~~~~~~~~~~
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importGRU(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:1345:20: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
         unsqueeze->setZeroIsPlaceholder(false);
                    ^~~~~~~~~~~~~~~~~~~~
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importLSTM(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:1851:22: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
         reshapeBias->setZeroIsPlaceholder(false);
                      ^~~~~~~~~~~~~~~~~~~~
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importRNN(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:2717:22: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
         reshapeBias->setZeroIsPlaceholder(false);
                      ^~~~~~~~~~~~~~~~~~~~
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘onnx2trt::NodeImportResult onnx2trt::{anonymous}::importTRT_Shuffle(onnx2trt::IImporterContext*, const onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&)’:
/code/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3797:12: error: ‘class nvinfer1::IShuffleLayer’ has no member named ‘setZeroIsPlaceholder’
     layer->setZeroIsPlaceholder(zeroIsPlaceholder);
            ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o] Error 1
external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/build.make:88: recipe for target 'external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o' failed
make[1]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/all] Error 2
CMakeFiles/Makefile2:2780: recipe for target 'external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/all' failed
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1866, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 1804, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel, args.target)
  File "/code/onnxruntime/tools/ci_build/build.py", line 950, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 449, in run_subprocess
    env=my_env, shell=shell)
  File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/code/cmake-3.14.3-Linux-x86_64/bin/cmake', '--build', '/code/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
The command '/bin/sh -c git clone --single-branch --branch ${ONNXRUNTIME_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime &&    /bin/sh onnxruntime/dockerfiles/scripts/install_common_deps.sh &&    cp onnxruntime/docs/Privacy.md /code/Privacy.md &&    cp onnxruntime/dockerfiles/LICENSE-IMAGE.txt /code/LICENSE-IMAGE.txt &&    cp onnxruntime/ThirdPartyNotices.txt /code/ThirdPartyNotices.txt &&    cd onnxruntime &&    /bin/sh ./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /workspace/tensorrt --config Release --build_wheel --update --build --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) &&    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl &&    cd .. &&    rm -rf onnxruntime cmake-3.14.3-Linux-x86_64' returned a non-zero code: 1

**Comment by Hao-Yan** [comment]
@BharathJaina , looks like your error is caused by wrong version of tensorrt. Latest master need tensorrt 7.1

**Comment by BharathJaina** [comment]
@Hao-Yan, The error is part of the Docker build procedure, I thought docker controls the selection of the version(s). Please let me know, how to correct the docker file.

**Comment by BharathJaina** [comment]
Thanks @Hao-Yan, seems I used the wrong master.

**Comment by wwbnjsace** [comment]
my build command is " ./build.sh --config Release --build_shared_lib --build_wheel --enable_pybind --use_openvino  " .after buiding ,it dose not generate any *.whl file in any location .
why?
