### ISSUE TITLE
Build onnxruntime on Raspberry Pi2 (x86, armv7l)!

### ISSUE THREAD

**Issue by duongvvuet** [microsoft/onnxruntime#5712]
**Describe the bug**
I am building onnxruntime c ++ for RPi2 (armv7l x86) and get an error...
```
/home/pi/onnxruntime/onnxruntime/test/providers/cpu/tensor/pad_test.cc:492:34: note: parameter passing for argument of type ‘std::initializer_list<long long int>’ changed in GCC 7.1
/home/pi/onnxruntime/onnxruntime/test/providers/cpu/tensor/pad_test.cc:492:34: note: parameter passing for argument of type ‘std::initializer_list<long long int>’ changed in GCC 7.1
[ 96%] Linking CXX executable onnxruntime_test_all
/usr/bin/ld: error: onnxruntime_test_all(.debug_info) is too large (0x1de3556b bytes)
/usr/bin/ld: error: onnxruntime_test_all(.debug_str) is too large (0x67e9049 bytes)
/usr/bin/ld: error: onnxruntime_test_all(.debug_loc) is too large (0x9bf3da7 bytes)
[ 96%] Built target onnxruntime_test_all
make: *** [Makefile:163: all] Error 2
Traceback (most recent call last):
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 2030, in <module>
    sys.exit(main())
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 1961, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 1017, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 492, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/pi/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j4']' returned non-zero exit status 2.

```
I'm not sure exactly what the error I got.

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- ONNX Runtime installed from: source
- ONNX Runtime version: 1.5.2
- GCC/Compiler version (if compiling from source): g++ (Raspbian 8.3.0-6+rpi1) 8.3.0

**To Reproduce**
I setting `-Donnxruntime_GENERATE_TEST_REPORTS=OFF`, `-Donnxruntime_DEV_MODE=OFF` and run `./build.sh --config RelWithDebInfo --build_shared_lib --parallel --x86 --skip_winml_tests --skip_test --arm`

**Expected behavior**
Please help me, how to build onnxruntime on RPi2

**Comment by snnn** [comment]
What if
``
./build.sh --config Release --build_shared_lib --parallel --x86 --skip_winml_tests --skip_test --arm
```

Change the config from "RelWithDebInfo" to "Release".
