### ISSUE TITLE
openvino build failed nuget

### ISSUE THREAD

**Issue by connordouglas1** [microsoft/onnxruntime#5749]
Hi OnnxRuntime,

Trying to build for openvino for C# using the .\build.bat --build_nuget --config RelWithDebInfo --use_openvino VAD-M_FP16
on windows 10 with vs2017 through command line.

No nuget package were made and all the test during the build process failed.

Please could someone point me in the right direction?

Here is my error log 

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_a2913.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a2913.dir\Debug\\" /Fd"cmTC_a2913.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  CheckIncludeFile.c

  

C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_a2913.vcxproj]

Checking whether the ASM_MASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is Clang using "--version" did not match "(clang version)":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is AppleClang using "--version" did not match "(Apple LLVM version)":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is ARMClang using "--version" did not match "armclang":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is HP using "-V" did not match "HP C":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -V
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is Intel using "--version" did not match "(ICC)":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is SunPro using "-V" did not match "Sun C":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -V
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is XL using "-qversion" did not match "XL C":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -qversion
MASM : fatal error A1017:missing source filename

**cmake output file**
The system is: Windows - 10.0.19041 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 08/11/2020 22:06:26.
Project "C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdC\.\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdC.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
Done Building Project "C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdC\CompilerIdC.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.27

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/3.18.4/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 08/11/2020 22:06:28.
Project "C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc141.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdCXX\.\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.18.4\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.90

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/3.18.4/CompilerIdCXX/CompilerIdCXX.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_70301.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_70301.dir\Debug\\" /Fd"cmTC_70301.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.18\Modules\CMakeCCompilerABI.c"

  CMakeCCompilerABI.c

  

  cmTC_70301.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_70301.exe

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_12e84.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_12e84.dir\Debug\\" /Fd"cmTC_12e84.dir\Debug\vc141.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.18\Modules\CMakeCXXCompilerABI.cpp"

  CMakeCXXCompilerABI.cpp

  

  cmTC_12e84.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_12e84.exe

Performing C++ SOURCE FILE Test HAS_QSPECTRE succeeded with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_d1e1f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D HAS_QSPECTRE /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++14 /Fo"cmTC_d1e1f.dir\Debug\\" /Fd"cmTC_d1e1f.dir\Debug\vc141.pdb" /Gd /TP /wd26812 /errorReport:queue C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\src.cxx

  src.cxx

  

  cmTC_d1e1f.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_d1e1f.exe

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAS_GUARD_CF succeeded with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_60003.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D HAS_GUARD_CF /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /guard:cf /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++14 /Fo"cmTC_60003.dir\Debug\\" /Fd"cmTC_60003.dir\Debug\vc141.pdb" /Gd /TP /wd26812 /errorReport:queue C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\src.cxx

  src.cxx

  

  cmTC_60003.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_60003.exe

Source file was:
int main() { return 0; }
Determining if the _strtof_l exist passed with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_ee4b4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D EIGEN_HAS_C99_MATH /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ee4b4.dir\Debug\\" /Fd"cmTC_ee4b4.dir\Debug\vc141.pdb" /Gd /TP /wd26812 /errorReport:queue C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  CheckSymbolExists.cxx

  

  cmTC_ee4b4.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_ee4b4.exe

File C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _strtof_l
  return ((int*)(&_strtof_l))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the _strtoui64_l exist passed with the following output:
Change Dir: C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_eebb8.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m && Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D EIGEN_HAS_C99_MATH /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_eebb8.dir\Debug\\" /Fd"cmTC_eebb8.dir\Debug\vc141.pdb" /Gd /TP /wd26812 /errorReport:queue C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckSymbolExists.cxx

  CheckSymbolExists.cxx

  

  cmTC_eebb8.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\Debug\cmTC_eebb8.exe

File C:/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef _strtoui64_l
  return ((int*)(&_strtoui64_l))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Checking whether the ASM_MASM compiler is MSVC using "-?" matched "Microsoft":
Microsoft (R) Macro Assembler (x64) Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        ML64 [ /options ] filelist [ /link linkoptions ]

/Bl<linker> Use alternate linker          /Sf Generate first pass listing
/c Assemble without linking               /Sl<width> Set line width
/Cp Preserve case of user identifiers     /Sn Suppress symbol-table listing
/Cx Preserve case in publics, externs     /Sp<length> Set page length
/D<name>[=text] Define text macro         /Ss<string> Set subtitle
/EP Output preprocessed listing to stdout /St<string> Set title
/F <hex> Set stack size (bytes)           /Sx List false conditionals
/Fe<file> Name executable                 /Ta<file> Assemble non-.ASM file
/Fl[file] Generate listing                /w Same as /W0 /WX
/Fm[file] Generate map                    /WX Treat warnings as errors
/Fo<file> Name object file                /W<number> Set warning level
/Fr[file] Generate limited browser info   /X Ignore INCLUDE environment path
/FR[file] Generate full browser info      /Zd Add line number debug info
/I<name> Add include path                 /Zf Make all symbols public
/link <linker options and libraries>      /Zi Add symbolic debug info
/nologo Suppress copyright message        /Zp[n] Set structure alignment
/Sa Maximize source listing               /Zs Perform syntax check only
/ZH:SHA_256 Use SHA256 for checksum
    in debug info (experimental)
/Gy[-] separate functions for linker
/errorReport:<option> Report internal assembler errors to Microsoft
    none - do not send report
    prompt - prompt to immediately send report
    queue - at next admin logon, prompt to send report
    send - send report automatically

.

**System information**
- Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- C#
- Visual Studio version VS2017 VS2019

**Comment by jywu-msft** [comment]
@sfatimar, @smkarlap , any ideas?

**Comment by smkarlap** [comment]
The logs seem to indicate CMake looking for various toolchain components, symbols, headers and libraries . The only actual failure that i see in it is the line in the very beginning indicating missing pthread.h header:-

`C:\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory`

Maybe pthread/boost libs are missing? 
online search for info on similar build errors indicate cmake version mismatches too. 
Can you also try to build with the baseline CPU execution build to narrow down the dependency mismatch. (do not use **--use_openvino VAD-M_FP16** build argument)

**Comment by connordouglas1** [comment]
Thanks Smkarlap,
Have download the pthread .dll but have no idea where in should go. Does it need to go into a certain folder or is there an environmental path needed?

Also

Ran a cpu build and got these errors in cmd no Nuget package was build

d98062da0
  d98062da0ce1ffb804325396cde10a41933cd154
  PackageVersion=1.5.2-dev-20201111-1244-d98062da0
  Bundling managed assemblies into a NuGet package ...
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [C:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj]
  Successfully created package 'C:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\Microsoft.ML.OnnxRuntime.Managed.1.5.2-dev-20201111-1244-d98062da0.nupkg'.
  Generating nuspec for the native Nuget package ...
          1 file(s) copied.
          1 file(s) copied.
  Bundling native shared library artifacts into a NuGet package ...
  Attempting to build package from 'NativeNuget.nuspec'.
EXEC : warning : NU5127: This package does not contain a lib/ or ref/ folder, and will therefore be treated as compatible for all frameworks. Since framework specific files were found under the build/ directory for netstandard1.1, consider creating the following empty files to correctly narrow the compatibility of the package: [C:\onnxruntime\csharp\OnnxRuntime.CSharp.proj]
  -lib/netstandard1.1/_._
EXEC : warning : NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [C:\onnxruntime\csharp\OnnxRuntime.CSharp.proj]
  - Add lib or ref assemblies for the netcoreapp target framework
  - Add lib or ref assemblies for the netstandard target framework
  - Add lib or ref assemblies for the net target framework
EXEC : warning : NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [C:\onnxruntime\csharp\OnnxRuntime.CSharp.proj]
  Successfully created package 'c:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\Microsoft.ML.OnnxRuntime.1.5.2-dev-20201111-1244-d98062da0.nupkg'.
2020-11-11 12:44:49,229 Build [DEBUG] - Subprocess completed. Return code=0
2020-11-11 12:44:49,229 Build [INFO] - Running subprocess in 'C:\onnxruntime\csharp'
['dotnet', 'test', 'test\\Microsoft.ML.OnnxRuntime.Tests\\Microsoft.ML.OnnxRuntime.Tests.csproj', '--filter', 'FullyQualifiedName!=Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels', '/p:IsLinuxBuild="false"', '', '/p:OnnxRuntimeBuildDirectory="c:\\onnxruntime\\build\\Windows"']
  Determining projects to restore...
  Restored C:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj (in 254 ms).
  Restored C:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj (in 586 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Microsoft.ML.OnnxRuntime -> C:\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\Debug\netstandard1.1\Microsoft.ML.OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime.Tests -> C:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\bin\Debug\netcoreapp2.1\Microsoft.ML.OnnxRuntime.Tests.dll
  The system cannot find the path specified.
C:\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj(76,5): error MSB3073: The command "c:\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\protoc.exe -I=..\..\..\onnxruntime\core\protobuf --csharp_out=. ..\..\..\onnxruntime\core\protobuf\onnx-ml.proto3" exited with code 3.
Traceback (most recent call last):
  File "c:\onnxruntime\tools\ci_build\build.py", line 2030, in <module>
    sys.exit(main())
  File "c:\onnxruntime\tools\ci_build\build.py", line 2014, in main
    run_csharp_tests(
  File "c:\onnxruntime\tools\ci_build\build.py", line 1664, in run_csharp_tests
    run_subprocess(cmd_args, cwd=csharp_source_dir)
  File "c:\onnxruntime\tools\ci_build\build.py", line 490, in run_subprocess
    completed_process = subprocess.run(
  File "C:\Users\codo01\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dotnet', 'test', 'test\\Microsoft.ML.OnnxRuntime.Tests\\Microsoft.ML.OnnxRuntime.Tests.csproj', '--filter', 'FullyQualifiedName!=Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels', '/p:IsLinuxBuild="false"', '', '/p:OnnxRuntimeBuildDirectory="c:\\onnxruntime\\build\\Windows"']' returned non-zero exit status 1.

c:\onnxruntime>

**Comment by sfatimar** [comment]
I think this is resolved. Please let me know if we can close the thread
