### ISSUE TITLE
Inputs with UINT8 should fallback to CUDA instead of failing to compile with TRT execution provider

### ISSUE THREAD

**Issue by joba01** [microsoft/onnxruntime#5785]
Models with uint8 inputs are not supported by TRT execution provider. This is fine, but the node should fallback to CUDA, instead of failing to to the conversion in onnxruntime.

**System information**
- ONNX Runtime version (you are using):
1.5.2

**Describe the solution you'd like**
In my case the first operation in the model is a cast to fp32 anyway, according to the onnx profiler this costs  **0.01ms** on CUDA.
Compared to doing this cast on a 512x616 grayscale image on the caller side before:
**Python**(numpy astype): **0.8ms**
**C#** (static array definition and copy with BlockCopy): **1ms**

Also int8 is not really an alternative, images/data that is received, either overflows are needs to be shifted, which also costs 0.65ms in python. Furthermore it needs retraining/further changes on the model (correct me if there is a smarter way).

Hence, just executing this operatoin in CUDA should be cheaper, either by beeing able to mark some operations to force them to run on a defined executor, or just hardcode it for this kind of casts.
**Describe alternatives you've considered**

**Additional context**
Tested on Nvidia T4/Quadro Intel and AMD CPUs

**Comment by jywu-msft** [comment]
if i'm understanding correctly, you're not using int8 for the purposes of accelerating inferencing (i.e. with Tensor cores)
which model is this? why does the model have uint8 inputs if it casts to fp32 immediately?

**Comment by joba01** [comment]
"if i'm understanding correctly, you're not using int8 for the purposes of accelerating inferencing (i.e. with Tensor cores)"
correct
"which model is this?"
A SSD architecture
"why does the model have uint8 inputs if it casts to fp32 immediately?"
images are received from sensors in int8 just standard 8bit RBG or grayscale images
casting/converting on GPU is mutch cheaper than preprocessing and than sending it to GPU. Furthermore the datastructures are blown up x3 without any information gain. 

Beeing able to process the data in the same format as it is received improves the thruput.

Furthermore this is possible with the CUDA and CPU providers. For many operations (e.g. PAD, RESIZE) onnx-runtime/onnx-trt is able to fallback to another provider when the operation is supported but not with the given parameters, hence my understanding is that this could be done the same way for casts.

**Comment by joba01** [comment]
I tried to make the point with the measurements above:
0.01ms on CUDA
~1ms on CPU

so a speedup of ~100 for this operation, without taking the more compact representation into account.

**Comment by jywu-msft** [comment]
thanks for the context and details. yes, it should be possible to fallback instead of fail.
we rely on onnx-tensorrt parser to tell us what TensorRT supports so it must not be handling this case/type properly.

**Comment by joba01** [comment]
I see. Can you link them to this request, can you forward it to them? Or do I have to repost it on their git-hub repo?

**Comment by joba01** [comment]
RSVP, what to do with this one, before it gets stale!

**Comment by joba01** [comment]
This Point is open, you confirmed that there probably is another party involved but you are not responsive on questions, on the other hand you have a bot that closes tickets automatically when you are not responding, this is quite annoying.

**Comment by jywu-msft** [comment]
> This Point is open, you confirmed that there probably is another party involved but you are not responsive on questions, on the other hand you have a bot that closes tickets automatically when you are not responding, this is quite annoying.

sorry about the stale-bot.  yes, I agree it can get very annoying for real issues.
Let me see if there's a way to flag issues so that they can't be automatically closed.

**Comment by jywu-msft** [comment]
> thanks for the context and details. yes, it should be possible to fallback instead of fail.
> we rely on onnx-tensorrt parser to tell us what TensorRT supports so it must not be handling this case/type properly.

Hi @kevinch-nv , is onnx-tensorrt marking uint8 type as unsupported?

**Comment by kevinch-nv** [comment]
Yes, we should be partition out all subgraphs with unsupported datatypes (including UINT8). 

@joba01 can you share the log of your run? The logging in ORT-TRT is messy so it may be possible that this is not the point of failure.

**Comment by joba01** [comment]
@kevinch-nv, thanks for the response, here the LOG:

Unsupported ONNX data type: UINT8 (2)

with trace logging enabled, there is no more useful information:
available_providers ['CPUExecutionProvider', 'CUDAExecutionProvider', 'TensorrtExecutionProvider']
2020-12-15 14:13:43.674040082 [I:onnxruntime:, inference_session.cc:1048 Initialize] Initializing session.
Unsupported ONNX data type: UINT8 (2)
2020-12-15 14:14:20.128606740 [W:onnxruntime:Default, cuda_execution_provider.cc:1843 GetCapability] CUDA kernel not found in registries for Op type: Pad node name: Pad__547

When disabling the TRT Provider, the model loads successfully:
2020-12-15 14:16:37.114901169 [I:onnxruntime:, inference_session.cc:1193 Initialize] Session successfully initialized.

I can provide you the model, with and without the UINT-8 input, on a private communication channel.

**Comment by joba01** [comment]
No this is (not great, but) fine.
When I change the UINT8 to INT32 in the model it can be converted to TRT Engines. The Padding nodes (these are nodes with less than 4 dimensions) are falling back to GPU. But these are not computational expensive and are at the end of the processing.

**Comment by joba01** [comment]
Because the whole model can also run in CUDA and the second node is a cast to float32 I see no technical reason why this is failing. As you mentioned, I think this is just a matter of partitioning the subgraphs that this first operation stays on the CUDA executor.

**Comment by jywu-msft** [comment]
sounds like based on @joba01 's description,  the pad nodes are inconsequential. 
should be due to uint8  if converting to int32 makes the model work with TensorRT EP.

**Comment by jywu-msft** [comment]
seems like this stalled over holidays.
@joba01 , sorry for the prolonged delay. can you share your model with me?
I'll loop in @kevinch-nv as needed.

**Comment by joba01** [comment]
I created a minimal example that I can share publicly  with uint8 and int32. The strange thing: I still get the warning about 'Unsupported ONNX data type: UINT8', but it does compile.
Still in the bigger model it only happens with uint8, therefore I guess it is a combinatorial problem.

I can share the model with you on a non-public channel.

Here is the complete error message of the original model:
```
Unsupported ONNX data type: UINT8 (2)
2021-01-18 15:41:51.429615509 [W:onnxruntime:Default, cuda_execution_provider.cc:1843 GetCapability] CUDA kernel not found in registries for Op type: Pad node name: Pad__547
2021-01-18 15:41:51.429650429 [W:onnxruntime:Default, cuda_execution_provider.cc:1843 GetCapability] CUDA kernel not found in registries for Op type: Pad node name: Pad__523
2021-01-18 15:41:51.429660626 [W:onnxruntime:Default, cuda_execution_provider.cc:1843 GetCapability] CUDA kernel not found in registries for Op type: GreaterOrEqual node name: Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/GreaterEqual
2021-01-18 15:41:51.432762133 [E:onnxruntime:, inference_session.cc:1205 operator()] Exception during initialization: /code/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:480 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::Provider_GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.

Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /code/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:480 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::Provider_GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.
```

I checked the created subgraphs and in both (the simple and the orignal model) the problematic casting operation is not in the subgraph that gets converted.

The following figure shows part of the original graph on the left and the subgraph extracten on the right. Cast ist not part of the subgraph, which is fine. But it still fails on TensorrtExecutionProvider::GetSupportedList
![image](https://user-images.githubusercontent.com/4116408/105013130-34310780-5a3f-11eb-8217-bace8fd9c338.png)

One difference is that the simple model only has one subgraph and the original one has ~7.
