### ISSUE TITLE
Build error in build.py

### ISSUE THREAD

**Issue by WilliamTambellini** [microsoft/onnxruntime#5980]
**Describe the bug**
Building error:
```
Traceback (most recent call last):
  File "/home/wtambellini/repos/onnxruntime/tools/ci_build/build.py", line 2069, in <module>
    sys.exit(main())
  File "/home/wtambellini/repos/onnxruntime/tools/ci_build/build.py", line 1984, in main
    install_python_deps()
  File "/home/wtambellini/repos/onnxruntime/tools/ci_build/build.py", line 585, in install_python_deps
    'files.pythonhosted.org'] + dep_packages)
  File "/home/wtambellini/repos/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/wtambellini/repos/onnxruntime/tools/python/util/run.py", line 42, in run
    env=env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--trusted-host', 'files.pythonhosted.org', 'setuptools', 'wheel', 'pytest', 'numpy>=1.16.6', 'sympy>=1.1', 'packaging', 'cerberus']' returned non-zero exit status 1
```

**Urgency**
none

**System information**
- OS : Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.5
- GCC/Compiler version (if compiling from source): 5.4

**To Reproduce**
- Describe steps/code to reproduce the behavior: On a default uptodate Ubuntu 16.04 :
./build.sh --config Release --build_shared_lib --parallel

**Expected behavior**
Build success

**Additional context**
This is due to python 3.5 : minimum req is now 3.6 but build.py has not been updated:
https://github.com/microsoft/onnxruntime/blob/2d9dcc4576f86b3eb6705dba1f8699eb52140b4e/tools/ci_build/build.py#L57

Would you mind if I prepare a PR to update build.py to properly check for python 3.6+ ?
 
Kind regards

**Comment by WilliamTambellini** [comment]
cf @xadupre

**Comment by xadupre** [comment]
It would be better to know the C++ build error before taking any decision. However, it should build. numpy version would also help to understand. However, torch, scikit-learn, numpy dropped support of python 3.5 (https://github.com/numpy/numpy/pull/16295). The main reason is probably the last release happened on Sept 2020 (https://www.python.org/downloads/release/python-3510/) and there won't be any new one. Tensorflow is doing the same: https://github.com/tensorflow/addons/issues/2183.

**Comment by WilliamTambellini** [comment]
It s not a C++ compil error but a python error about bad version of setuptools. 
Apparently someone even added a comment in build.sh: 
https://github.com/microsoft/onnxruntime/blob/2d9dcc4576f86b3eb6705dba1f8699eb52140b4e/build.sh#L21
I ve build successfully with python 3.6.

**Comment by snnn** [comment]
How did you get python 3.6 on Ubuntu 16.04?
