### ISSUE TITLE
Build issue when using `--build_wheel` without CUDA

### ISSUE THREAD

**Issue by georgen117** [microsoft/onnxruntime#6068]
**Describe the bug**
When using `--build_wheel` option the build will fail when building 

outputting the following build error:

```
Total Test time (real) =  28.62 sec
2020-12-07 13:15:00,547 util.run [DEBUG] - Subprocess completed. Return code: 0
2020-12-07 13:15:00,547 util.run [INFO] - Running subprocess in 'C:\Users\georgena\workspace\onnxruntime\\build\Windows\RelWithDebInfo\RelWithDebInfo'
['C:\\Users\\georgena\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', 'onnxruntime_test_python.py']
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 8, in <module>
    import onnxruntime as onnxrt
  File "C:\Users\georgena\workspace\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "C:\Users\georgena\workspace\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\_pybind_state.py", line 19, in <module>
    raise ImportError("CUDA Toolkit %s not installed on the machine." % CUDA_VERSION)
ImportError: CUDA Toolkit 10.2 not installed on the machine.
Traceback (most recent call last):
  File "C:\Users\georgena\workspace\onnxruntime\\tools\ci_build\build.py", line 2088, in <module>
    sys.exit(main())
  File "C:\Users\georgena\workspace\onnxruntime\\tools\ci_build\build.py", line 2026, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "C:\Users\georgena\workspace\onnxruntime\\tools\ci_build\build.py", line 1466, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnxruntime_test_python.py'], cwd=cwd, dll_path=dll_path)
  File "C:\Users\georgena\workspace\onnxruntime\\tools\ci_build\build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\georgena\workspace\onnxruntime\tools\python\util\run.py", line 39, in run
    completed_process = subprocess.run(
  File "C:\Users\georgena\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\georgena\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', 'onnxruntime_test_python.py']' returned non-zero exit status 1.
```

Using git bisect I was able to narrow the source of this build error to:
```
commit 2b35f7d4f6b1d39170859fd772e710f894cb1765 (HEAD, refs/bisect/bad)
Author: baijumeswani <bmeswani@microsoft.com>
Date:   Thu Dec 3 08:57:55 2020 -0800

    Fix build.py bug which prevents running some unit tests (#5990)

    Also ignore an exception occurred for execution providers which generate compiled nodes
```
**Urgency**
This is preventing building `--build_wheel` option.
I feel it is mid to high priority.

**System information**
- OS Platform and Distribution: **Windows 10**
- ONNX Runtime installed from:  (source or binary): **source**
- ONNX Runtime version: **HEAD of master branch after commit 2b35f7d4f6b1d39170859fd772e710f894cb1765**
- Python version: **3.8.3**
- Visual Studio version (if applicable): **Microsoft Visual Studio Professional 2019 Version 16.7.7**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Checkout onnxruntime `master` branch or `2b35f7d4f6b1d39170859fd772e710f894cb1765`

Build using one of the following options:
1 . `.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --build_wheel`
2.  `.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training --build_wheel`

- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Build will complete without failure.

**Comment by snnn** [comment]
We fixed it.

**Comment by georgen117** [comment]
> We fixed it.

Excellent. Glad to see the fix when in during the time I was trying to find the source of the error.
