### ISSUE TITLE
cudaErrorInvalidConfiguration in Reshape node

### ISSUE THREAD

**Issue by tanmaniac** [microsoft/onnxruntime#6078]
**Describe the bug**
I have a custom transformer-based model trained in Tensorflow 2.3.1 that I've successfully converted to ONNX with `tf2onnx`. However, when running the model in in ONNX Runtime in CUDA, I get an error complaining of `cudaErrorInvalidConfiguration:invalid configuration argument`.

**Urgency**
I personally have deadlines but I'm not a Microsoft employee so they probably don't apply

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (`nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04` docker)
- ONNX Runtime installed from (source or binary): from binary (PyPi) and from source
- ONNX Runtime version: 1.5.3, 1.3.1
- Python version: 3.6.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA 10.2 with cuDNN 8; CUDA 10.0 with cuDNN 7
- GPU model and memory: GTX 1660 Ti, Jetson Nano

**To Reproduce**
Unfortunately I cannot provide the model, but here is a minimal code snippet that reproduces the error. This is running on Ubuntu 18.04, on a GTX 1660 Ti, in a `nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04` Docker image with TensorRT 7.1.3. I have built this version of onnxruntime from source to add TensorRT support, but the same error occurs with a prebuilt binary.

```python
import onnxruntime as rt
import numpy as np

x = np.zeros((1, 1), dtype=np.int32)
y = np.zeros((1, 1), dtype=np.int32)
p = np.zeros((1, 10, 4), dtype=np.int32)
feats = np.zeros((1, 12, 16, 16, 120), dtype=np.float32)

input_dict = {
    "inp_1:0": y,
    "inp_2:0": x,
    "inp_3:0": p,
    "inp_4:0": feats
}

model_file = "../my_model.onnx"

print(f"Execution providers: {rt.get_available_providers()}")
ort_sess = rt.InferenceSession(model_file,
                               providers=["CUDAExecutionProvider"])

pred_onx = ort_sess.run(None, input_dict)
```

This generates the following output:

```bash
Execution providers: ['CPUExecutionProvider', 'CUDAExecutionProvider', 'TensorrtExecutionProvider']
2020-12-08 10:49:31.458104435 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running Reshape node. Name:'StatefulPartitionedCall/gesture_model_features/gesture_model/transformer_block/linear_multi_head_attention/Reshape_3' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
Traceback (most recent call last):
  File "reprod.py", line 22, in <module>
    pred_onx = ort_sess.run(None, input_dict)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Reshape node. Name:'StatefulPartitionedCall/gesture_model_features/gesture_model/transformer_block/linear_multi_head_attention/Reshape_3' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
```

**Expected behavior**
I expect the Reshape node to run without errors.

**Screenshots**
See snippet above

**Additional context**
Sorry, can't share the model. I have also cross-compiled onnxruntime for Jetson Nano with CUDA support and get the same issue with the same model (in C++). So I suspect something is wrong with the model, but I can't imagine why it would cause an error that seemingly has something to do with kernel block/warp size.

Thanks in advance for your help!

**Comment by yufenglee** [comment]
@jywu-msft and @stevenlix , please help to take a look.

**Comment by jywu-msft** [comment]
> @jywu-msft and @stevenlix , please help to take a look.

the above error message shows the user is setting the session to use CUDA EP , not TensorRT EP.

**Comment by yufenglee** [comment]
Add @pranavsharma as well.

**Comment by tanmaniac** [comment]
Thank you for the quick response on this! For additional context, when I try to run with TensorRT, the session is unable to build the TensorRT engine and falls back to CUDA, where it fails with the same error.

```diff
-model_file = "../my_model.onnx"
+# Followed instruction here: https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#shape-inference-for-tensorrt-subgraphs
+model_file = "../my_model_shaped_inference.onnx"
 
 print(f"Execution providers: {rt.get_available_providers()}")
 ort_sess = rt.InferenceSession(model_file,
-                               providers=["CUDAExecutionProvider"])
+                               providers=["TensorrtExecutionProvider"])
```
gives

```bash
Execution providers: ['CPUExecutionProvider', 'CUDAExecutionProvider', 'TensorrtExecutionProvider']
2020-12-08 19:26:40.478631461 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running TRTKernel_graph_tf2onnx_32 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_32_32' Status Message: TensorRT EP Failed to Build Engine.
EP Error: [ONNXRuntimeError] : 11 : EP_FAIL : Non-zero status code returned while running TRTKernel_graph_tf2onnx_32 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_32_32' Status Message: TensorRT EP Failed to Build Engine. using ['TensorrtExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2020-12-08 19:26:41.389730575 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running Reshape node. Name:'StatefulPartitionedCall/gesture_model_features/gesture_model/transformer_block/linear_multi_head_attention/Reshape_3' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : Non-zero status code returned while running TRTKernel_graph_tf2onnx_32 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_32_32' Status Message: TensorRT EP Failed to Build Engine.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reprod.py", line 22, in <module>
    pred_onx = ort_sess.run(None, input_dict)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 131, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Reshape node. Name:'StatefulPartitionedCall/gesture_model_features/gesture_model/transformer_block/linear_multi_head_attention/Reshape_3' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
python3: /onnx-runtime/onnxruntime/onnxruntime/core/framework/provider_bridge_ort.cc:653: onnxruntime::ProviderLibrary::~ProviderLibrary(): Assertion `!handle_' failed.
Aborted (core dumped)
```

I don't care too much about TensorRT since my target platform (Jetson Nano) can't do mixed-precision inference anyway; I believe TensorRT is outside the scope of this issue.

**Comment by jywu-msft** [comment]
it could be a model issue as you mention. we wouldn't be able to debug the issue without a repro case/minimal model.

**Comment by tanmaniac** [comment]
Got it, yes unfortunately the model is still relatively novel research so we don't want to share it just yet. In that case, I don't think it will be possible for you to debug this issue; I'd be fine with closing this issue and trying again with ORT in a later release (or with a later `tf2onnx` version).

Thank you for taking a look though!

**Comment by jywu-msft** [comment]
or if it's possible, can you provide more information about the failing reshape node?
What are the inputs/attributes etc. that are causing it to fail.

**Comment by Zalways** [comment]
> or if it's possible, can you provide more information about the failing reshape node? What are the inputs/attributes etc. that are causing it to fail.

i have met a problem when i use cuda inference:
Non-zero status code returned while running TopK node. Name:'/model/TopK' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

can you help me with my problem?
@jywu-msft   @tanmaniac

**Comment by jywu-msft** [comment]
> Got it, yes unfortunately the model is still relatively novel research so we don't want to share it just yet. In that case, I don't think it will be possible for you to debug this issue; I'd be fine with closing this issue and trying again with ORT in a later release (or with a later `tf2onnx` version).
> 
> Thank you for taking a look though!

thanks. sorry we couldn't be more help this time. closing this issue now.
