### ISSUE TITLE
CUBLAS error executing cublasGemmHelper

### ISSUE THREAD

**Issue by Nidhi-kumari** [microsoft/onnxruntime#6102]
**Describe the bug**
onnx optimized models fails to run on GPU system 
Tensorflow model has been created on TPU,  This model is converted to ONNX format and run on a GPU device.
That worked perfectly.
Then  the model is optimized using onnxruntime-tools 1.5.2 , The conversion of model is working but during the inference time it shows the issue below
`2020-12-10 08:09:27.565906905 [E:onnxruntime:Default, cuda_call.cc:119 CudaCall] CUBLAS failure 8: CUBLAS_STATUS_ARCH_MISMATCH ; GPU=0 ; hostname=DataElement ; expr=cublasGemmHelper( CublasHandle(), CUBLAS_OP_N, CUBLAS_OP_N, N, M, 1, &one, b_data, N, GetConstOnes<CudaT>(M), 1, &zero, out_data, N, device_prop);
2020-12-10 08:09:27.565940505 [E:onnxruntime:, sequential_executor.cc:309 Execute] Non-zero status code returned while running Gemm node. Name:'gemm' Status Message: CUBLAS error executing cublasGemmHelper( CublasHandle(), CUBLAS_OP_N, CUBLAS_OP_N, N, M, 1, &one, b_data, N, GetConstOnes<CudaT>(M), 1, &zero, out_data, N, device_prop)
Traceback (most recent call last):
  File "ner_onnx_distress.py", line 171, in <module>
    obj.prediction(sess, allwords)
  File "ner_onnx_distress.py", line 159, in prediction
    result = sess.run(["ArgMax:0"], data)
  File "/home/parabole/disk/DowJones/current_version/onnx_venv/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Gemm node. Name:'gemm' Status Message: CUBLAS error executing cublasGemmHelper( CublasHandle(), CUBLAS_OP_N, CUBLAS_OP_N, N, M, 1, &one, b_data, N, GetConstOnes<CudaT>(M), 1, &zero, out_data, N, device_prop)`

for creating the onnx model from the tensorflow model
`python -m tf2onnx.convert --saved-model $LAST_SAVED_MODEL --opset 11 --output='bert.onnx' `

This was the command used to create the optimized_onnx model
`python -m onnxruntime_tools.optimizer_cli --input='bert.onnx' --output 'bert_optimized.onnx' --model_type='bert_tf' --num_heads 12 --hidden_size 768 --float16 --disable_layer_norm --disable_skip_layer_norm --use_gpu`

Package versions:
onnx==1.7.0
onnxruntime-gpu==1.4.0
onnxruntime-tools==1.5.2
tf2onnx==1.7.1

**Urgency**
required urgently for meeting the deadline at work

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04.4
- ONNX Runtime installed from (source or binary): pip installation
- ONNX Runtime version: onnxruntime-gpu==1.4.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.1
- GPU model and memory:Tesla K80, 12GB

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by yufenglee** [comment]
@Nidhi-kumari , your GPU K80 is too old to support fp16 for [cublasSgemm](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemm). Please remove the --float16 option when running onnxruntime_tools.optimizer_cli.
