### ISSUE TITLE
 TypeError: forward() got an unexpected keyword argument 'past' when converting gpt2 from transformers to onnx

### ISSUE THREAD

**Issue by carter54** [microsoft/onnxruntime#6227]
**Describe the bug**
When I try to use 
```
python -m onnxruntime_tools.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32
```
following error raised:
```
PyTorch Version:1.7.1
Transformers Version:4.1.1
Onnxruntime Version:1.6.0
Exporting ONNX model to /home/hr/PycharmProjects/CodeCompletion_onnx/test/ModelArts_20200716/onnx/ModelArts_20200716_past.onnx
Traceback (most recent call last):
  File "/home/hr/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hr/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hr/anaconda3/lib/python3.8/site-packages/onnxruntime_tools/transformers/convert_to_onnx.py", line 247, in <module>
    main()
  File "/home/hr/anaconda3/lib/python3.8/site-packages/onnxruntime_tools/transformers/convert_to_onnx.py", line 150, in main
    Gpt2Helper.export_onnx(model,
  File "/home/hr/anaconda3/lib/python3.8/site-packages/onnxruntime_tools/transformers/gpt2_helper.py", line 253, in export_onnx
    outputs = model(*input_list)
  File "/home/hr/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hr/anaconda3/lib/python3.8/site-packages/onnxruntime_tools/transformers/gpt2_helper.py", line 54, in forward
    return super().forward(input_ids, position_ids=position_ids, attention_mask=attention_mask, past=past)
TypeError: forward() got an unexpected keyword argument 'past'
```

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04:
- ONNX Runtime installed from: pip install onnxruntime-gpu
- ONNX Runtime version: 1.6.0
- Python version: 3.8.5
- CUDA/cuDNN version: CUDA10.2, cuDNN8.0.3
- GPU model and memory: V100 16G

**To Reproduce**
```
python -m onnxruntime_tools.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32
```

**Comment by tianleiwu** [comment]
@carter54 , It is a known issue. Huggingface transformers 4.0 has a breaking change: past becomes past_key_values in GPT-2 models. You can use transformers 3.* to walk around or wait for our fix that is coming soon.

**Comment by carter54** [comment]
@tianleiwu I see, thx for the reply~
