### ISSUE TITLE
Python tests failing

### ISSUE THREAD

**Issue by jupvfranco** [microsoft/onnxruntime#6292]
**Describe the bug**
The tests `testMNISTTrainingAndTestingOpset12` and `testMNISTResumeTrainingAndTesting` are failing in my environment. 

```
======================================================================
FAIL: testMNISTResumeTrainingAndTesting (__main__.TestOrtTrainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_ort_trainer.py", line 389, in testMNISTResumeTrainingAndTesting
    assert_allclose(expected_losses, actual_losses, rtol=rtol, err_msg="loss mismatch")
  File "/home/jufranc/venv/custom-ort/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/jufranc/venv/custom-ort/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=0
loss mismatch
Mismatched elements: 10 / 10 (100%)
Max absolute difference: 0.18939674
Max relative difference: 1.13567928
 x: array([0.230067, 0.48428 , 0.307168, 0.32388 , 0.195438, 0.356166,
       0.308964, 0.377387, 0.248836, 0.30745 ])
 y: array([0.374456, 0.467166, 0.202641, 0.300827, 0.190617, 0.16677 ,
       0.152371, 0.281446, 0.43357 , 0.198028])
```
and
```
======================================================================
FAIL: testMNISTTrainingAndTestingOpset12 (__main__.TestOrtTrainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_ort_trainer.py", line 345, in testMNISTTrainingAndTestingOpset12
    TestOrtTrainer.run_mnist_training_and_testing(onnx_opset_ver = 12)
  File "onnxruntime_test_ort_trainer.py", line 340, in run_mnist_training_and_testing
    assert_allclose(expected_losses, actual_losses, rtol=rtol, err_msg="loss mismatch")
  File "/home/jufranc/venv/custom-ort/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/jufranc/venv/custom-ort/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=0
loss mismatch
Mismatched elements: 19 / 20 (95%)
Max absolute difference: 0.26157774
Max relative difference: 1.17456436
 x: array([2.333008, 1.068029, 0.630054, 0.52799 , 0.371007, 0.404445,
       0.304827, 0.459503, 0.423058, 0.479736, 0.230067, 0.48428 ,
       0.307168, 0.32388 , 0.195438, 0.356166, 0.308964, 0.377387,
       0.248836, 0.30745 ])
 y: array([2.334447, 0.860357, 0.517777, 0.545802, 0.416575, 0.403261,
       0.327761, 0.353241, 0.365205, 0.547779, 0.359476, 0.222702,
       0.350088, 0.192338, 0.180929, 0.197331, 0.229877, 0.357198,
       0.228235, 0.385183])
```

**Urgency**
Not urgent. For now, I'll build with the `--skip_tests` option.

**System information**
OS Platform and Distribution: Ubuntu 18.04.5 LTS
ONNX Runtime installed from: source
ONNX Runtime version: onnxruntime-gpu-1.5.0
GCC/Compiler version: 7.5.0
CUDA/cuDNN version: CUDA version 11.0 (and NCCL 2.7.8)
GPU model and memory: 4 * Tesla V100-PCIE-16GB

**To Reproduce**
Build with:
```
./build.sh --enable_training --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/local/cuda --config=Debug --build_wheel --parallel
```

or alternatively, under `build/Linux/Debug/` run:
```
python3 onnxruntime_test_ort_trainer.py
```

**Expected behavior**
All tests passing

**Comment by faxu** [comment]
@jupvfranco Are you still experiencing this issue?

**Comment by jupvfranco** [comment]
Hi,

on commit f22f04a109b4e0ffa592f50a49f0f2b4569e4cfa, I built with:

```./build.sh --enable_training --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/local/cuda --config=[Release|Debug] --build_wheel --parallel --skip_tests```

With Release, ```python3 onnxruntime_test_ort_trainer.py``` results in a segmentation fault, while with Debug I get an error similar to the above.

**Comment by baijumeswani** [comment]
closing this now since ORTTrainer has been deprecated. Please open a new issue if any problem is experienced with ortmodule/ ort training apis.
