### ISSUE TITLE
Error: Running double precision model exported from pyTorch

### ISSUE THREAD

**Issue by bissantz** [microsoft/onnxruntime#6320]
# Issue
I am using neural networks as closure models in CFD simulations for which double precision (64 bit floats) is required.
Short story: I am export a double precision model trained in pytorch to onnx and it fails to find the right implemenation for the Gemm operation. Everything works fine if i switch the dtype to float32.

Long story: see minimal working example below.

What can I do to make it work with 64bit floating values or is this simply not implemented yet?

# Environment
OS: macOS Mojave 10.14.6
Empty conda environment with torch and ort installed via pip.
``` bash
conda create --name ort python=3.6 pip=20.2.3
conda activate ort
pip install onnxruntime
pip install torch
```

# Error reproduction
```python
import onnxruntime as ort
import torch

# create simplest torch module
model = torch.nn.Linear(1, 1).double()
x = torch.ones(10, 1, dtype=torch.double)

# export model to onnx
torch.onnx.export(model,                           # model being run
                   x,                                          # model input (or a tuple for multiple inputs)
                   "linear.onnx",                    # where to save the model (can be a file or file-like object)
                   export_params=True,        # store the trained parameter weights inside the model file
                   opset_version=10,              # the ONNX version to export the model to
                   do_constant_folding=True,  # whether to execute constant folding for optimization
                   input_names = ['input'],    # the model's input names
                   output_names = ['output'], # the model's output names
                   dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                 'output' : {0 : 'batch_size'}})
                                 
# now running the model in ort
import onnxruntime

ort_session = onnxruntime.InferenceSession("linear.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
```

I get the following output:
```bash
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    ort_session = onnxruntime.InferenceSession("linear.onnx")
  File "/usr/local/anaconda3/envs/ort/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/anaconda3/envs/ort/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Gemm_0:Gemm(9)
```

If I change the dtype to 32bit floating values everything works fine. What confuses me is that when I check the [documentation for the Gemm](https://github.com/onnx/onnx/blob/master/docs/Operators.md#type-constraints-48) operation it says that float64 is supported. 

## Side note
I also tried to run this model in c++ based on the [squeezenet example](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp) and I get the same error. I installed onnxruntime via Homebrew.

**Comment by tracysh** [comment]
@xzhu1900: Sorry for the delayed response. ONNX Runtime recently added support for Gemm<double> (#6223). Not all combinations of types supported by ONNX are available in the runtime in order to keep code size down. You could try using the nightly build (https://test.pypi.org/project/ort-nightly/) if you'd like to try this out before the next release of the runtime.

**Comment by jbissantz** [comment]
Thanks for fixing this issue. The example code above runs now, using the nightly build.
While doing some testing I noticed that the onnxruntime_test script doesn't work, I used the python script located in tools instead:
```bash
(ort): $ onnxruntime_test linear.onnx 1000
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/ort/bin/onnxruntime_test", line 5, in <module>
    from onnxruntime.tools.onnxruntime_test import main
ImportError: cannot import name 'main'

(ort): $ python /usr/local/anaconda3/envs/ort/lib/python3.6/site-packages/onnxruntime/tools/onnxruntime_test.py linear.onnx 10000
model: torch-jit-export
version: 9223372036854775807
iterations: 10000
avg latency: 0.013897672599705401 ms
```
I have an additional question:
Because I'd like to use the onnxruntime C++-API to use it during runtime of CFD simulations, I was wondering which library files were shipped with pip. I used ```pip show .-f ort-nightly``` to examine all files included in the package and was surprised that I didn't find any *so and *dylib files. So what backend libraries are actually used in the python API and where are they located? Is there a repository to download the nightly binaries to be able to download and link them using cmake?

**Comment by jbissantz** [comment]
I ran some additional tests and encountered additional errors.
Due to some background optimization the Gemm operation is fused with the ReLU activation function and results in the FusedGemm operator which also does not support double precision. Could you let me know how I could disable this optimization or add double precision to the FusedGemm operator. 

Skript to reproduce the error:
```python
import onnxruntime as ort
import torch

class FlexMLP(torch.nn.Module):
      def __init__(self, n_inp, n_out, n_hidden_neurons=[32, 32], activation_fn=torch.nn.ReLU)
          super().__init__()

          self.n_inp = n_inp
          self.n_out = n_out
          self.n_neurons = [n_inp] + n_hidden_neurons + [n_out]
          self.hidden_layers = len(n_hidden_neurons)
          self.layers = torch.nn.ModuleList()
          self.activation = activation_fn

          # construct the network
          for i in range(len(self.n_neurons)-2):
              self.layers.append(torch.nn.Linear(self.n_neurons[i], self.n_neurons[i+1]))
              self.layers.append(self.activation())
          # add the last layer
          self.layers.append(nn.Linear(self.n_neurons[-2], self.n_neurons[-1])

      def forward(self, x):
          for layer in self.layers:
              x = layer(x)
          return x

# create simple multi layer perceptron
model = FlexMLP(1,1,[32]*3).double()
x = torch.ones(10, 1, dtype=torch.double)

# export model to onnx
torch.onnx.export(model,                           # model being run
                   x,                                          # model input (or a tuple for multiple inputs)
                   "FlexMLP.onnx",                    # where to save the model (can be a file or file-like object)
                   export_params=True,        # store the trained parameter weights inside the model file
                   opset_version=10,              # the ONNX version to export the model to
                   do_constant_folding=True,  # whether to execute constant folding for optimization
                   input_names = ['input'],    # the model's input names
                   output_names = ['output'], # the model's output names
                   dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                 'output' : {0 : 'batch_size'}})
                                 
# now running the model in ort
import onnxruntime

ort_session = onnxruntime.InferenceSession("FlexMLP.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
```

Error code:
```bash
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    ort_session = onnxruntime.InferenceSession("linear.onnx")
  File "/usr/local/anaconda3/envs/ort/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/anaconda3/envs/ort/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for FusedGemm(1) (node fused ). Op with name (fused ) and type (FusedGemm) kernel is not supported in CPUExecutionProvider. Encountered following errors: (Found kernel for Op with name (fused ) and type (FusedGemm) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(double))
)
```
