### ISSUE TITLE
onnxruntime ArmNN Build Failing with Release Tag 1.6.0 and with master 

### ISSUE THREAD

**Issue by ashutoshnaik** [microsoft/onnxruntime#6421]
I got the following error when building the onnxruntime on the ARM8 64 bit machine:

My commandline:
./build.sh --config MinSizeRel --update --build --use_armnn --armnn_home /home/ubuntu/ash_naik/armnn-onnx/armnn --armnn_libs /home/ubuntu/ash_naik/armnn-onnx/armnn/build

The Error:
```
[ 68%] Building CXX object CMakeFiles/onnxruntime_providers_armnn.dir/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc.o
In file included from /home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc:6:0:
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h: In member function ‘onnxruntime::common::Status onnxruntime::armnn_ep::Gemm<T>::Compute(onnxruntime::OpKernelContext*) const’:
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:46:5: error: ‘GemmHelper’ was not declared in this scope
     GemmHelper helper(X->Shape(), trans_A_ != CblasNoTrans, W->Shape(), trans_B_ != CblasNoTrans, useBias ? B->Shape() : TensorShape({}));
     ^~~~~~~~~~
In file included from /home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc:6:0:
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:46:136: error: expected primary-expression before ‘)’ token
     GemmHelper helper(X->Shape(), trans_A_ != CblasNoTrans, W->Shape(), trans_B_ != CblasNoTrans, useBias ? B->Shape() : TensorShape({}));
                                                                                                                                        ^
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:48:10: error: ‘helper’ was not declared in this scope
     if (!helper.State().IsOK())
          ^~~~~~
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:51:17: error: ‘helper’ was not declared in this scope
     int64_t M = helper.M();
                 ^~~~~~
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h: In instantiation of ‘onnxruntime::common::Status onnxruntime::armnn_ep::Gemm<T>::Compute(onnxruntime::OpKernelContext*) const [with T = float]’:
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc:39:1:   required from here
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:103:23: warning: narrowing conversion of ‘(__gnu_cxx::__alloc_traits<std::allocator<long int> >::value_type)(&(&((const onnxruntime::Tensor*)B)->onnxruntime::Tensor::Shape())->onnxruntime::TensorShape::GetDims())->std::vector<long int>::operator[](1)’ from ‘__gnu_cxx::__alloc_traits<std::allocator<long int> >::value_type {aka long int}’ to ‘unsigned int’ inside { } [-Wnarrowing]
             biasShape = {B->Shape().GetDims()[1]};
             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.h:103:23: warning: narrowing conversion of ‘(&(&((const onnxruntime::Tensor*)B)->onnxruntime::Tensor::Shape())->onnxruntime::TensorShape::GetDims())->std::vector<long int>::operator[](1)’ from ‘const value_type {aka const long int}’ to ‘unsigned int’ inside { } [-Wnarrowing]
CMakeFiles/onnxruntime_providers_armnn.dir/build.make:114: recipe for target 'CMakeFiles/onnxruntime_providers_armnn.dir/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_armnn.dir/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/onnxruntime/core/providers/armnn/math/gemm.cc.o] Error 1
CMakeFiles/Makefile2:1621: recipe for target 'CMakeFiles/onnxruntime_providers_armnn.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_armnn.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/tools/ci_build/build.py", line 2088, in <module>
    sys.exit(main())
  File "/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/tools/ci_build/build.py", line 2023, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/tools/ci_build/build.py", line 1060, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/tools/python/util/run.py", line 42, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/ubuntu/ash_naik/onnrumtime-build/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.
```

I had built the ArmNN SDK successfully as per : https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-onnx/single-page

Please let me know if I am missing anything

**Comment by manashgoswami** [comment]
Have you tried with `--config RelWithDebInfo` or `--config Release`?

The `build.sh` command for armnn is shown [here](https://github.com/microsoft/onnxruntime/blob/c43ca45c4fb5bf0d438d9cf8d20619faea55e1fd/BUILD.md#armnn)?

**Comment by skottmckay** [comment]
Try adding `#include "core/providers/cpu/math/gemm_helper.h"` to onnxruntime\core\providers\armnn\math\gemm.h, as GemmHelper is defined in that header. It's possible that was previously included indirectly via  `#include "core/providers/cpu/math/gemm.h"` but isn't any more.

**Comment by ashutoshnaik** [comment]
Hi @skottmckay 

I worked through the header file additions - had to add quite a few from the armnn build as well

I am now hitting a linker issue:

```
[ 59%] Built target onnxruntime_util
[ 60%] Built target onnx_test_runner_common
[ 67%] Built target onnxruntime_framework
[ 68%] Built target onnxruntime_providers_armnn
[ 72%] Built target nsync_cpp
[ 74%] Built target re2
[ 74%] Linking CXX executable onnxruntime_perf_test
/usr/bin/ld: cannot find -larmnn
/usr/bin/ld: cannot find -larmnn
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_perf_test.dir/build.make:193: recipe for target 'onnxruntime_perf_test' failed
make[2]: *** [onnxruntime_perf_test] Error 1
CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/onnxruntime_perf_test.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_perf_test.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/tools/ci_build/build.py", line 2088, in <module>
    sys.exit(main())
  File "/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/tools/ci_build/build.py", line 2023, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/tools/ci_build/build.py", line 1060, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/tools/python/util/run.py", line 42, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/ubuntu/ash_naik/onnxruntime_26_01/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.
```

I have ensured that the libarmnn.so is present as follows:
```

root@ip-172-31-20-78:~/ash_naik# ls -l ./armnn-onnx/armnn/build/*.so.*
lrwxrwxrwx 1 root   root         16 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnn.so.22 -> libarmnn.so.22.0
-rwxr-xr-x 1 root   root   30770968 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnn.so.22.0
lrwxrwxrwx 1 ubuntu ubuntu       16 Jan 20 17:59 ./armnn-onnx/armnn/build/libarmnn.so.23 -> libarmnn.so.23.0
-rwxr-xr-x 1 ubuntu ubuntu 12070512 Jan 20 17:59 ./armnn-onnx/armnn/build/libarmnn.so.23.0
lrwxrwxrwx 1 root   root         30 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnnBasePipeServer.so.22 -> libarmnnBasePipeServer.so.22.0
-rwxr-xr-x 1 root   root      37280 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnnBasePipeServer.so.22.0
lrwxrwxrwx 1 ubuntu ubuntu       30 Jan 20 17:59 ./armnn-onnx/armnn/build/libarmnnBasePipeServer.so.23 -> libarmnnBasePipeServer.so.23.0
-rwxr-xr-x 1 ubuntu ubuntu    37280 Jan 20 17:59 ./armnn-onnx/armnn/build/libarmnnBasePipeServer.so.23.0
lrwxrwxrwx 1 root   root         26 Jan 24 07:23 ./armnn-onnx/armnn/build/libarmnnOnnxParser.so.22 -> libarmnnOnnxParser.so.22.0
-rwxr-xr-x 1 root   root     490528 Jan 24 07:23 ./armnn-onnx/armnn/build/libarmnnOnnxParser.so.22.0
lrwxrwxrwx 1 ubuntu ubuntu       26 Jan 20 18:43 ./armnn-onnx/armnn/build/libarmnnOnnxParser.so.23 -> libarmnnOnnxParser.so.23.0
-rwxr-xr-x 1 ubuntu ubuntu   379744 Jan 20 18:43 ./armnn-onnx/armnn/build/libarmnnOnnxParser.so.23.0
lrwxrwxrwx 1 root   root         26 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoder.so.22 -> libtimelineDecoder.so.22.0
-rwxr-xr-x 1 root   root     105072 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoder.so.22.0
lrwxrwxrwx 1 ubuntu ubuntu       26 Jan 20 17:59 ./armnn-onnx/armnn/build/libtimelineDecoder.so.23 -> libtimelineDecoder.so.23.0
-rwxr-xr-x 1 ubuntu ubuntu   105072 Jan 20 17:59 ./armnn-onnx/armnn/build/libtimelineDecoder.so.23.0
lrwxrwxrwx 1 root   root         30 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoderJson.so.22 -> libtimelineDecoderJson.so.22.0
-rwxr-xr-x 1 root   root      69200 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoderJson.so.22.0
lrwxrwxrwx 1 ubuntu ubuntu       30 Jan 20 18:43 ./armnn-onnx/armnn/build/libtimelineDecoderJson.so.23 -> libtimelineDecoderJson.so.23.0
-rwxr-xr-x 1 ubuntu ubuntu    69200 Jan 20 18:43 ./armnn-onnx/armnn/build/libtimelineDecoderJson.so.23.0

```

PLease let me know why the --armnn_libs parameter above is not picking it, and how can I get over this.

Here is my full build command-line:

 ./build.sh --config RelWithDebInfo --update --build --use_armnn --armnn_home /home/ubuntu/ash_naik/armnn-onnx/armnn --armnn_libs /home/ubuntu/ash_naik/armnn-onnx/armnn/build``

Thanks a lot!


> Try adding `#include "core/providers/cpu/math/gemm_helper.h"` to onnxruntime\core\providers\armnn\math\gemm.h, as GemmHelper is defined in that header. It's possible that was previously included indirectly via `#include "core/providers/cpu/math/gemm.h"` but isn't any more.

**Comment by skottmckay** [comment]
I don't see a libarmnn.so there. Usually one of the versioned files would be symlinked to `libarmnn.so` to essentially select which version to use.

**Comment by ashutoshnaik** [comment]
Hi, It is present:
```

root@ip-172-31-20-78:~/ash_naik# ls -l ./armnn-onnx/armnn/build/*.so
lrwxrwxrwx 1 root root 14 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnn.so -> libarmnn.so.22
lrwxrwxrwx 1 root root 28 Jan 24 07:22 ./armnn-onnx/armnn/build/libarmnnBasePipeServer.so -> libarmnnBasePipeServer.so.22
lrwxrwxrwx 1 root root 24 Jan 24 07:23 ./armnn-onnx/armnn/build/libarmnnOnnxParser.so -> libarmnnOnnxParser.so.22
lrwxrwxrwx 1 root root 24 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoder.so -> libtimelineDecoder.so.22
lrwxrwxrwx 1 root root 28 Jan 24 07:23 ./armnn-onnx/armnn/build/libtimelineDecoderJson.so -> libtimelineDecoderJson.so.22
```

I suspect that the --armnn_libs flag is not getting picked up for some reason ?

**Comment by skottmckay** [comment]
Not sure. I don't have an arm setup to be able to easily repro. @Andrews548 may know better as the creator of the armnn EP.

**Comment by skottmckay** [comment]
There are many different issues going on with the ArmNN setup. Unfortunately that was added by ARM folks so whilst I can fix some aspects of the setup, there are parts that I'm not sure what the more correct/best way to approach it would be. Details in #6486.

To make it link a few different things would be required. I can create a PR tomorrow that should provide an example that can be pulled or copied.

**Comment by ashutoshnaik** [comment]
Thank you @skottmckay . At the minimum we need a working build / working set of instructions for onnxruntime with ArmNN . so that we can continue development on this.

**Comment by skottmckay** [comment]
Added PR with the changes to the ORT build setup. That should let you build without changing any files once checked in (or pull the branch with the PR to test locally if you don't want to wait for that). 

Note that you'll most likely need to provide the `--acl_home` and `--acl_libs` parameters when building for it to work. 

Tested with this command on a Raspberry Pi. Just failed linking onnxruntime_test_all as the 32-bit OS runs out of memory when doing so. I was getting link errors previously though and onnxruntime_perf_test built successfully, so I think the setup will at least build now.

```
./build.sh --build_dir build/ArmNN  --parallel --build_shared_lib --use_armnn --armnn_home ~/src/github/armnn-onnx/armnn --armnn_libs ~/src/github/armnn-onnx/armnn/build --acl_home ~/src/github/armnn-onnx/ComputeLibrary --acl_libs ~/src/github/armnn-onnx/ComputeLibrary/build
```

**Comment by skottmckay** [comment]
Fixes are merged now.
