### ISSUE TITLE
ArgMax failure on CUDA

### ISSUE THREAD

**Issue by tkanmae** [microsoft/onnxruntime#6482]
**Describe the bug**
ArgMax op fails on CUDA when it tries to execute the operation along an axis that has length of one.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6.0
- Python version: 3.8.7
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: CUDA 10.2.89, cuDNN 8.0.3.33
- GPU model and memory: Tesla K80, 11GB

**To Reproduce**

You can reproduce the error with the following script. I also attached the corresponding error message below.

Note that the script works fine if

* the input tensor's last axis has length of larger than one, e.g., `shape=(32, 2)`, or
* the execution provider is `CPUExecutionProvider`

I have PyTorch 1.7.1 in my environment.

```python
import torch
import torch.nn as nn
import onnxruntime

class ArgMaxModule(nn.Module):
    def forward(self, x):
        return x.argmax(dim=1)

def main():
    model = ArgMaxModule()

    input = torch.ones(32, 1)
    onnx_model = 'argmax.onnx'
    torch.onnx.export(model, input, onnx_model)

    sess = onnxruntime.InferenceSession(onnx_model)
    sess.set_providers(['CUDAExecutionProvider'])

    input_feed = {
        sess.get_inputs()[0].name: input.detach().cpu().numpy()
    }

   out =  sess.run(None, input_feed)


if __name__ == '__main__':
    main()
```

```
2021-01-28 05:01:39.656939343 [E:onnxruntime:Default, cuda_call.cc:119 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=whatever-vm ; expr=cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, temp_output.get());
2021-01-28 05:01:39.656988644 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running ArgMax node. Name:'ArgMax_0' Status Message: CUDNN error executing cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, temp_output.get())
Traceback (most recent call last):
  File "argmax.py", line 29, in <module>
    main()
  File "argmax.py", line 25, in main
    sess.run(None, input_feed)
  File "/home/ubuntu/debug-onnxruntime/.direnv/python-3.8.7/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running ArgMax node. Name:'ArgMax_0' Status Message: CUDNN error executing cudnnReduceTensor( cuda_ep.PerThreadCudnnHandle(), reduce_desc, indices_cuda.get(), indices_bytes, workspace_cuda.get(), workspace_bytes, &one, input_tensor, reinterpret_cast<const CudaT*>(input.template Data<T>()), &zero, output_tensor, temp_output.get())
```

**Expected behavior**
In the above script,  the output `out` must be an array with the shape of `(32,)`.

**Comment by tkanmae** [comment]
@ashbhandare Thanks you!
