### ISSUE TITLE
Build failure in `orttraining_pybind_state.cc` when building with `--enable_training` and `--build_wheel`

### ISSUE THREAD

**Issue by georgen117** [microsoft/onnxruntime#6536]
**Describe the bug**
When building on Windows with the following build script.
```
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training --build_wheel
```

Note building without `--build_wheel` and the build will pass.

the build fails when trying to build `orttraining_pybind_state.cc` with the following build error
```
  orttraining_pybind_state.cc
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(171,92): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable con
version) [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1176,5): message : could be 'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(nonstd::optional_lite::optional<onnxruntime::PathString> &&) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1151,5): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(const nonstd::optional_lite::optional<onnxruntime::PathString> &) noexcept(<expr>)' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1136,16): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathSt
ring>::operator =(nonstd::optional_lite::nullopt_t) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(171,92): message : while trying to match the argument list '(nonstd::optional_lite::optional<onnxruntime::PathString>, std::string)' [C:\
Users\georgena\workspace\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(174,86): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable con
version) [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1176,5): message : could be 'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(nonstd::optional_lite::optional<onnxruntime::PathString> &&) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1151,5): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(const nonstd::optional_lite::optional<onnxruntime::PathString> &) noexcept(<expr>)' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1136,16): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathSt
ring>::operator =(nonstd::optional_lite::nullopt_t) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(174,86): message : while trying to match the argument list '(nonstd::optional_lite::optional<onnxruntime::PathString>, std::string)' [C:\
Users\georgena\workspace\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(177,86): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable con
version) [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1176,5): message : could be 'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(nonstd::optional_lite::optional<onnxruntime::PathString> &&) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1151,5): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathStr
ing>::operator =(const nonstd::optional_lite::optional<onnxruntime::PathString> &) noexcept(<expr>)' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\cmake\external\optional-lite\include\nonstd/optional.hpp(1136,16): message : or       'nonstd::optional_lite::optional<onnxruntime::PathString> &nonstd::optional_lite::optional<onnxruntime::PathSt
ring>::operator =(nonstd::optional_lite::nullopt_t) noexcept' [C:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
C:\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc(177,86): message : while trying to match the argument list '(nonstd::optional_lite::optional<onnxruntime::PathString>, std::string)' [C:\
Users\georgena\workspace\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
Traceback (most recent call last):
  File "C:\onnxruntime\\tools\ci_build\build.py", line 2077, in <module>
    sys.exit(main())
  File "C:\onnxruntime\\tools\ci_build\build.py", line 2013, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 1019, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 524, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Users\georgena\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '--build', 'C:\\onnxruntime\\\\build\\Windows\\RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '/maxcpucount:32', '/nodeReuse:False']' returned non-zero exit status 1.
```

I used git bisect and found the first instance of the build failure was from:
```
commit fd21c84eb814371ea0dd86b4902dd137846e07c9
Author: ashbhandare <ash.bhandare@gmail.com>
Date:   Thu Jan 14 10:07:54 2021 -0800
    Enable graph save for orttrainer (#6333)
    * Enable graph save for orttrainer
    * Fix CI
    * Update orttraining/orttraining/python/training/orttrainer_options.py
    * Update orttraining/orttraining/python/training/orttrainer_options.py
    * Update orttraining/orttraining/python/training/orttrainer_options.py
    * Update orttraining/orttraining/python/training/orttrainer_options.py
    * Update orttraining/orttraining/python/training/orttrainer_options.py
    Co-authored-by: Thiago Crepaldi <thiago.crepaldi@microsoft.com>
```

Looking at the commit the lines that are causing the failure were added in this commit.

**Urgency**
no deadline but this is preventing the integrating work with master

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):  source
- ONNX Runtime version: head of master branch checked out on 02/01/2021
- Python version:  Python 3.8.3
- Visual Studio version (if applicable): Visual studio 2019 version 16.7.7
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Build on Windows using the following build command:
```
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training --build_wheel
```

**Expected behavior**
Build without error.

**Comment by georgen117** [comment]
I did a little looking this issue is likely a Windows only problem.

the line: `config.model_after_graph_transforms_path = parameters.model_after_graph_transforms_path;`

has two different types.

`parameters.model_after_graph_transforms_path` is of the type `std::string`

while 

`config.model_after_graph_transforms_path` is of the type `optional<PathString>` 

The `PathString` is a defined as: std::basic_string<wchar_t> on windows and std::basic_string<char> on other platforms.

There is a function `ToPathString()` that should convert the `std::string` to `wchar_t`

**Comment by georgen117** [comment]
I don't know if @ashbhandare wants to take a look at this commit since it is modifying their commit.

**Comment by snnn** [comment]
Don't close it. The PR #6538 make the build pass, but the behavior is totally wrong.  Please try to not convert a std::string to std::wstring, because you don't know what the encoding of the std::string is. The ToWideString function over-simplified the problem. It assumes the source string is UTF-8, but on Windows usually it isn't. The right fix is always using std::wstring for paths on Windows and std::string on Linux.  On Linux we can assume std::string is encoded in UTF-8. Though it is not always true but commonly it is so the assumption is acceptable. On the other hand,  on Windows normally path strings are not UTF-8 at all!
