### ISSUE TITLE
Inference error using migraohx-onnxruntime

### ISSUE THREAD

**Issue by zhangjia3** [microsoft/onnxruntime#6605]
When I use migraohx-onnxruntime to do inference, the following error occurs:

root@ce2f83fe55d2:/home/WS-DAN-AMD# python3 test_og.py
2021-02-08 08:58:46.454400130 [E:onnxruntime:, inference_session.cc:1286 operator()] Exception during initialization: /home/onnxruntime/onnxruntime/core/graph/function.cc:160 std::unique_ptr<onnx::OpSchema> onnxruntime::CreateSchema(const onnxruntime::Graph&, const onnxruntime::IndexedSubGraph&) input_arg->Type() != nullptr was false.

Traceback (most recent call last):
  File "test_og.py", line 35, in <module>
    sess = rt.InferenceSession(r'./ONNX/model_amd_c.onnx',so)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /home/onnxruntime/onnxruntime/core/graph/function.cc:160 std::unique_ptr<onnx::OpSchema> onnxruntime::CreateSchema(const onnxruntime::Graph&, const onnxruntime::IndexedSubGraph&) input_arg->Type() != nullptr was false.

**Comment by faxu** [comment]
CC @scxiao

**Comment by scxiao** [comment]
@faxu Thanks for forwarding me the issue.
@zhangjia3 is this the same issue you asked me in the "AMDMIGraphX" repository?

**Comment by zhangjia3** [comment]
@scxiao First of all thank you for your reply. Recently, I am trying to use migraphx to build the onnxrunntime environment inference onnx model. This problem is the problem encountered when I transform the model I trained into the onnx model for inference. The question I asked you in the "AMDMIGraphX" repository was a problem I encountered when testing with another model.

**Comment by scxiao** [comment]
@zhangjia3 I assumed you specified the EP to be MIGraphX, right? If you specify the EP to be the CPU, do you have the same error?

**Comment by zhangjia3** [comment]
Yes, I have set session.set_providers(MIGraphXExecutionProvider) in my inferenc code.



---Original---

**Comment by scxiao** [comment]
@zhangjia3 if you change 
```session.set_providers(MIGraphXExecutionProvider) ```
to 
```session.set_providers(CPUExecutionProvider)```, 
do you have the same error?

**Comment by zhangjia3** [comment]
@scxiao I have changed to session.set_providers(CPUExecutionProvider) ,but But still show the same error

**Comment by scxiao** [comment]
@faxu @zhangjia3 Looks like it is not something special to migraphx. Maybe you can rename the title to be general, then ONNXRurntime guys can know it could be a general issue.
