### ISSUE TITLE
General C# EP question

### ISSUE THREAD

**Issue by thoron** [microsoft/onnxruntime#6864]
How does one enable TensorRT EP in C#? I am at a loss here. Have tried building it from source many times and as far as I can see the nupkg looks fine and installs fine. When building DML nuget, the results were easy to integrate into the project. Just install the `Microsoft.ML.OnnxRuntime.1.7.0-dev-20210302-1048-2d6e10ba0.nupkg` package and the provider showed up in `OrtEnv.Instance().GetAvailableProviders()`. 

Installing the `Microsoft.ML.OnnxRuntime.TensorRT.1.7.0-dev-20210302-0936-2d6e10ba0.nupkg` places the expected files in `runtimes\win-x64\native`. Is there some environmental variable which must be set or similar to make the TensorRT EP available? I get the feeling the `Microsoft.ML.OnnxRuntime.1.7.0-dev-20210302-1048-2d6e10ba0.nupkg` must be build at same time as the EP nuget. Am I missing something? Sorry if this is the incorrect place to raise this question, did not know where else to look.

Somewhat related to another issue I have created #6857 

Kind regards,
Thomas

**Comment by jywu-msft** [comment]
@chilo-ms , can you advise as you've tested this in the past.

**Comment by chilo-ms** [comment]
Current onnxruntime C# API has not yet exposed TensorRT enable function, but this function is already there and will soon be exposed. Please see this [commit ](https://github.com/microsoft/onnxruntime/commit/33d7d6e4942a1adf32a769e965a05ef57012f5d2)first or build from this [branch](https://github.com/microsoft/onnxruntime/tree/c_sharp_tensorrt).

After built, there should be two nuget files, `Microsoft.ML.OnnxRuntime.Managed.1.7.0-dev-20210307-0735-9126faa35.nupkg` and `Microsoft.ML.OnnxRuntime.TensorRT.1.7.0-dev-20210307-0735-9126faa35.nupkg`, located at .\build\Windows\Release\Release\nuget-artifacts, and then install them.

And you can use TRT-EP simply like following code:
```
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
...
static InferenceSession session;
session = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithTensorrtProvider(0));
```

**Comment by thoron** [comment]
@chilo-ms I am encountering a issue when trying to build TensorRT nuget.

Running build command on Windows for commit `33d7d6e4942a1adf32a769e965a05ef57012f5d2 (HEAD -> c_sharp_tensorrt, origin/c_sharp_tensorrt)`
```cmd
./build.bat --config Release `
  --build_shared_lib --build_nuget --parallel `
  --cuda_version 11.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2" `
  --cudnn_home "C:\Users\thomas\bin\cudnn-11.2-windows-x64-v8.1.1.33" `
  --use_tensorrt --tensorrt_home "C:\Users\thomas\bin\TensorRT-7.2.2.3" `
  --cmake_generator "Visual Studio 16 2019" --skip_tests
```
Log, truncated for brevity.
```
....
crop_impl.cu
  binary_elementwise_ops_impl.cu
  image_scaler_impl.cu
_ __device__ function is not allowed [C:\Users\thomas\dev\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.v
cxproj]

  where_impl.cu
  fft_ops_impl.cu
  complex_mul_impl.cu
  bias_softmax_impl.cu
  binary_elementwise_ops_impl.cu
Traceback (most recent call last):
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 2003, in <module>
    sys.exit(main())
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 1938, in main
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 1017, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 536, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\thomas\dev\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\thomas\\dev\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:20', '/nodeReuse:False']' returned non-zero exit status 1
```
Any advice on how to continue so I can assist in the testing?

**Comment by chilo-ms** [comment]
Could you try CUDA11.0, CuDNN8 and TensorRT7.1.3.4/TensorRT7.2.2.3 ?

**Comment by thoron** [comment]
@chilo-ms I am unable to compile with CUDA 11.0 as I am also trying to test this on my GPU (RTX 3080, compute_86). I could compile with CUDA 11.1 but ran in to the same issue:
```

  topk_impl.cu
Traceback (most recent call last):
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 2003, in <module>
    sys.exit(main())
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 1938, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 1017, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\Users\thomas\dev\onnxruntime\tools\ci_build\build.py", line 536, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\thomas\dev\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\thomas\\dev\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:20', '/nodeReuse:False']' returned non-zero exit status 1.
```
I updated cmake to include 8.6.
```diff
diff --git a/cmake/CMakeLists.txt b/cmake/CMakeLists.txt
index 5307f4f85..a84a4ea73 100644
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -1196,16 +1196,17 @@ if (onnxruntime_USE_CUDA)
       # the following compute capabilities are removed in CUDA 11 Toolkit
       if (CMAKE_CUDA_COMPILER_VERSION VERSION_LESS 11)
         set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_30,code=sm_30") # K series
+        set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_37,code=sm_37") # K80
+        set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_50,code=sm_50") # M series
       endif()
       # 37, 50 still work in CUDA 11 but are marked deprecated and will be removed in future CUDA version.
-      set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_37,code=sm_37") # K80
-      set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_50,code=sm_50") # M series

       set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_52,code=sm_52") # M60
       set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_60,code=sm_60") # P series
       set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_70,code=sm_70") # V series
       if (CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL 11)
         set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_80,code=sm_80") # A series
+        set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_86,code=[sm_86,compute_86]") # A series
       endif()
     endif()
   endif()
```

I tried to compile with both TensorRT versions (7.1.3.4 and 7.2.2.3) and it produced the same error. Perhaps it is an issue with my GPU version? Build command:

```bat
./build.bat --config Release `
   --build_shared_lib --build_csharp --parallel `
   --use_cuda --cuda_version 11.1 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" `
   --cudnn_home "C:\Users\thomas\bin\cudnn-11.2-windows-x64-v8.1.1.33" `
   --use_tensorrt --tensorrt_home "C:\Users\thomas\bin\TensorRT-7.1.3.4" `
   --cmake_generator "Visual Studio 16 2019" --skip_tests --use_dml `
   --cmake_extra_defines="CMAKE_SYSTEM_VERSION=10.0.19041.0" --skip_submodule_sync
```

**Comment by chilo-ms** [comment]
I used the same build command you pasted above and it can successfully build on my Windows10 machine. 
Questions here, can you successfully build other applications/samples using the same CUDA 11.1 repo? What is your cmake version?
