### ISSUE TITLE
[JAVA Bindings + Android arm64-v8a] ONNXRuntime build documentation

### ISSUE THREAD

**Issue by ghost** [microsoft/onnxruntime#6923]
**Describe the bug**
The development environment described in https://github.com/microsoft/onnxruntime/issues/6842#issuecomment-789148544 is able to load ORT and inference using the compiled `onnxruntime-1.6.0.jar`/`onnxruntime-1.7.0.jar`. The compiled native libraries (*.so) are for `linux-aarch64`. Theoretically, Android app can use the same native library directly. However, after putting the `libonnxruntime4j_jni.so` into jniLibrary of apk, Android test app reads the jni so file but `libonnxruntime.so` is not loaded successfully.

Log:
```
2021-03-06 16:17:41.992 20216-20216/com.abc.testnativeapp I/ZMain: abi = arm64-v8a
2021-03-06 16:17:41.992 20216-20216/com.abc.testnativeapp I/ZMain: os.name = Linux
2021-03-06 16:17:41.992 20216-20216/com.abc.testnativeapp I/ZMain: os.arch = aarch64
2021-03-06 16:17:41.997 20216-20216/com.abc.testnativeapp D/AndroidRuntime: Shutting down VM
2021-03-06 16:17:41.999 20216-20216/com.abc.testnativeapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc.testnativeapp, PID: 20216
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libonnxruntime.so.1.6.0" not found: needed by /data/app/~~X_rIinOuT2qmVvAFaTol8w==/com.abc.testnativeapp-MtOqlRx_RxfZrZYf_peLHw==/base.apk!/lib/arm64-v8a/libonnxruntime4j_jni.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:137)
        at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:90)
        at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:24)
        at ai.onnxruntime.OrtEnvironment.getEnvironment(OrtEnvironment.java:45)
        at com.abc.testnativeapp.MainActivity.onCreate(MainActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-06 16:17:42.025 20216-20216/com.abc.testnativeapp I/Process: Sending signal. PID: 20216 SIG: 9

``` 

com.abc.testnativeapp.MainActivity.java
```
27:        Log.i(tag, "abi = " + getAbi());
28:        Log.i(tag, "os.name = " + System.getProperty("os.name", "generic"));
29:        Log.i(tag, "os.arch = " + System.getProperty("os.arch", "generic"));
30:
31:        this.ortEnvironment = OrtEnvironment.getEnvironment();
32:        this.ortSessionOptions = new OrtSession.SessionOptions();
```

[ai.onnxruntime.OnnxRuntime.java](https://github.com/microsoft/onnxruntime/blob/v1.6.0/java/src/main/java/ai/onnxruntime/OnnxRuntime.java#L137)
```
136:     if (isAndroid()) {
137:       System.loadLibrary("onnxruntime4j_jni");
138:     return;
139:     }
```

**To Reproduce**
- Using the same jar from https://github.com/microsoft/onnxruntime/issues/6842#issuecomment-789148544
- Add the compiled jar as a lib for Android app
- Add the compiled so as jniLib for Android app

**Expected behavior**
Doing inference using onnxruntime.jar on Android device

**Misc**
[ONNX_Runtime_for_Mobile_Platforms.md](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md) provides different mobile platform information. But got different error message. Is the doc specific for compiling into a onnxruntime.jar?
```
2021-03-07 00:57:27,359 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-03-07 00:57:27,360 build [ERROR] - Currently only support building protoc for Windows host while cross-compiling for ARM/ARM64/Store and linux cross-compiling iOS
```

**Comment by gwang-msft** [comment]
For Android development using java, please use Android Archive (AAR), see [Build Android Archive (AAR)]( https://www.onnxruntime.ai/docs/how-to/build.html#build-android-archive-aar)

**Comment by jji2019** [comment]
Hi @gwang-msft,

Thanks for providing additional documentation. I can find aar file under directory `<build_dir>/java/build/<android>/outputs/aar`. However, using aar, android app still cannot create a model session from onnx model file. 

Here is the error message from Android loading model
```
2021-03-09 11:02:29.670 31150-31150/com.abc.testnativeapp I/ZMain: abi = arm64-v8a
2021-03-09 11:02:29.670 31150-31150/com.abc.testnativeapp I/ZMain: os.name = Linux
2021-03-09 11:02:29.670 31150-31150/com.abc.testnativeapp I/ZMain: os.arch = aarch64
2021-03-09 11:02:29.697 31150-31150/com.abc.testnativeapp I/ZMain: dir = /storage/emulated/0
2021-03-09 11:02:29.697 31150-31150/com.abc.testnativeapp I/ZMain: onnxFile exists? true
2021-03-09 11:02:29.706 31150-31150/com.abc.testnativeapp E/ZMain: OrtException Error code - ORT_FAIL - message: Load model from /sdcard/test/resnet.onnx failed:system error number 13
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /sdcard/test/resnet.onnx failed:system error number 13
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err:     at ai.onnxruntime.OrtSession.createSession(Native Method)
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err:     at ai.onnxruntime.OrtSession.<init>(OrtSession.java:67)
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err:     at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:163)
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err:     at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:148)
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err:     at com.abc.testnativeapp.MainActivity.onCreate(MainActivity.java:55)
```

com.abc.testnativeapp.MainActivity.java
```
        Log.i(tag, "abi = " + getAbi());
        Log.i(tag, ", os.name = " + System.getProperty("os.name", "generic"));
        Log.i(tag, ", os.arch = " + System.getProperty("os.arch", "generic"));
        this.ortEnvironment = OrtEnvironment.getEnvironment();
        this.ortSessionOptions = new OrtSession.SessionOptions();
        try {
            // iport model and create session
            File onnxFile = new File("/sdcard/test/resnet.onnx");
            Log.i(tag, "onnxFile exists? " + onnxFile.exists());
            if (onnxFile != null) {
                ortSession = ortEnvironment.createSession(onnxFile.getAbsolutePath(), ortSessionOptions);
            } else {
                Log.i(tag, "onnxFile not there");
            }

```

In addition, the aar file is generated by a machine macOS x86_64 (Big Sur 11.1). I don't know if I need to set up additional environment other than android ndk for cross building to arm64-v8a.

Here is the aar build log from macOS. 
[20210309_android_success.log](https://www.dropbox.com/s/nmxct2blm35gakf/20210309_android_success.log?dl=0)
Snippet of the log:
```
myuser Workspace % git clone --branch v1.6.0 https://github.com/Microsoft/onnxruntime
myuser Workspace % cd onnxruntime
myuser onnxruntime % ./build.sh --android --android_sdk_path /Users/myuser/Library/Android/sdk --android_ndk_path /Users/myuser/Library/Android/sdk/ndk/22.0.7026061 --android_abi arm64-v8a --android_api 29 --build_java

...

[100%] Linking CXX executable onnxruntime_test_all
[100%] Built target onnxruntime_test_all
2021-03-08 21:51:58,740 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-03-08 21:51:58,741 build [INFO] - Running tests for MinSizeRel configuration
2021-03-08 21:51:58,742 build [INFO] - Build complete
```

**Comment by gwang-msft** [comment]
```
2021-03-09 11:02:29.707 31150-31150/com.abc.testnativeapp W/System.err: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /sdcard/test/resnet.onnx failed:system error number 13
```

Please see `https://android.googlesource.com/kernel/lk/+/upstream-master/include/errno.h#46`

**Comment by jji2019** [comment]
@gwang-msft, thanks! I thought this is the error code from ORT.

**Comment by jji2019** [comment]
btw, here is another build log from Linux x86_64 server.
jar is generated at `<build_dir>/java/build/libs/onnxruntime-1.6.0.jar`
aar file is not found.
The output folder `<build_dir>/java/build/android` is not created.

[20210309_android_success_linux_x86_64_server.log](https://www.dropbox.com/s/o2jrocmmll3h26b/20210309_android_success_linux_x86_64_server.log?dl=0)

**Comment by gwang-msft** [comment]
I did a build using Linux, the aar files are correctly generated under build/Android/Release/java/build/android/outputs/aar/

**Comment by jji2019** [comment]
Really appreciate that you provide the detailed path to the aar file! I found it is under my location at `<ort_build_dir>/build/Android/MinSizeRel/java/build/android/outputs/aar`
