### ISSUE TITLE
How to run a model exported with multiple input, using single input?

### ISSUE THREAD

**Issue by vishnu-hue** [microsoft/onnxruntime#6931]
Gpt2 model is exported with 2 inputs, one is primary input and the other one is optional. Is there a way to run the model with only one input.

**Comment by HectorSVC** [comment]
you should be able to run it with the single input which is primary input. Checkout same example here for GPT-2:
https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2

**Comment by vishnu-hue** [comment]
@HectorSVC  in this example the model exported with single input and it is run with single input but in my case the model is exported with two inputs "input_ids" and "past_key_values" and i want to run it with "input_ids" alone.

**Comment by HectorSVC** [comment]
I suppose it should be find. You can give it a try and let us know if any issues. or share the model to us.

**Comment by vishnu-hue** [comment]
```
import os
import torch
import onnx
import onnxruntime
import logging
from onnxruntime.quantization import quantize_dynamic, QuantType
import numpy as np
from transformers import GPT2Tokenizer, GPT2LMHeadModel, AutoConfig
logger = logging.getLogger('')


def export_onnx(model, config, tokenizer, device):
    model.to(device)

    inputs = tokenizer.encode_plus("Here is an example input for GPT2 model",
                                   add_special_tokens=True,
                                   return_tensors='pt')
    input_ids = inputs['input_ids'].to(device)
    logger.debug(f"input_ids={input_ids}")
    outputs = model(input_ids=input_ids, past_key_values=None)
    assert len(outputs) == 2
    logger.debug(f"output 0 shape={outputs[0].shape}")
    #logger.debug(f"outputs[1][0] shape={outputs[1][0].shape}")

    num_layer = model.config.n_layer
    present_names = [f'present_{i}' for i in range(num_layer)]
    output_names = ["last_state"] + present_names

    input_names = ['input_ids']

    # input_ids has only one word for model with past state.
    # Shape of input tensors:
    #    input_ids: (batch_size, 1)
    #    past_{i}:  (2, batch_size, num_heads, seq_len, hidden_size/num_heads)
    # Shape of output tensors:
    #    last_state: (batch_size, seq_len + 1, hidden_size)
    #    present_{i}:  (2, batch_size, num_heads, seq_len + 1, hidden_size/num_heads)
    dynamic_axes = {'input_ids': {0: 'batch_size'}, 'last_state': {0: 'batch_size', 1: 'seq_len_plus_1'}}

    for name in present_names:
        dynamic_axes[name] = {1: 'batch_size', 3: 'seq_len_plus_1'}

    past_names = [f'past_{i}' for i in range(num_layer)]
    input_names = ['input_ids'] + past_names
    dummy_past = [torch.zeros([2]+list(outputs[1][0][0].shape), dtype=torch.float32, device=device) for _ in range(num_layer)]
    for name in past_names:
        dynamic_axes[name] = {1: 'batch_size', 3: 'seq_len'}
    logger.debug(f"vocab_size:{model.config.vocab_size}")

    dummy_input_ids = torch.randint(low=0,
                                    high=model.config.vocab_size - 1,
                                    size=(1, 1),
                                    dtype=torch.int64,
                                    device=device)
    logger.debug(f"dummy_input_ids={dummy_input_ids}")
    export_inputs = (dummy_input_ids, tuple(dummy_past))

    # Let's run performance test on PyTorch before updating environment variable.
    with torch.no_grad():
        outputs = model(input_ids=dummy_input_ids, past_key_values=dummy_past)

    torch.onnx.export(model,
                      args=export_inputs,
                      f='gpt2_past.onnx',
                      input_names=input_names,
                      output_names=output_names,
                      example_outputs=outputs,
                      dynamic_axes=dynamic_axes,
                      opset_version=11,
                      do_constant_folding=True,
                      verbose=False)
    return outputs


def session_run_with_past():
    tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
    model = GPT2LMHeadModel.from_pretrained('distilgpt2')
    device = torch.device("cpu")
    model.to(device)
    inputs = tokenizer.encode_plus("Here is an example input for GPT2 ",
                                   add_special_tokens=True,
                                   return_tensors='pt')
    input_ids = inputs['input_ids'].to(device)
    logger.debug(f"input_ids={input_ids}")
    outputs = model(input_ids=input_ids, past_key_values=None)
    cpu_model = onnxruntime.InferenceSession("gpt2_past.onnx")
    model_inputs = tokenizer.encode_plus("model")
    input = dict()
    input["input_ids"] = model_inputs["input_ids"]
    inputs_onnx = {k: np.atleast_2d(v) for k, v in input.items()}
    past_key_value = [torch.zeros([len(outputs[1][0])]+list(outputs[1][0][0].shape), dtype=torch.float32, device=device) for _ in range(6)]
    sequence= cpu_model.run(None, {"input_ids":inputs_onnx["input_ids"],"past_0":past_key_value[0].detach().cpu().numpy(),"past_1":past_key_value[1].detach().cpu().numpy(),"past_2":past_key_value[2].detach().cpu().numpy(),"past_3":past_key_value[3].detach().cpu().numpy(),"past_4":past_key_value[4].detach().cpu().numpy(),"past_5":past_key_value[5].detach().cpu().numpy()})


def session_run():
    tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
    cpu_model = onnxruntime.InferenceSession("gpt2_past.onnx")
    model_inputs = tokenizer.encode_plus("Here is an example input for GPT2 model")
    input = dict()
    input["input_ids"] = model_inputs["input_ids"]
    inputs_onnx = {k: np.atleast_2d(v) for k, v in input.items()}
    sequence= cpu_model.run(None, {"input_ids":inputs_onnx["input_ids"]})


def main():
    tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
    model = GPT2LMHeadModel.from_pretrained('distilgpt2')
    config = AutoConfig.from_pretrained('distilgpt2')
    device = torch.device("cpu")
    export_onnx(model, config, tokenizer, device)


main()
session_run_with_past()
session_run()
```


In session_run_with_past() all the inputs are given and the model runs fine but in session_run() only one input is given and i get the following error:


```Traceback (most recent call last):
  File "gpt2_past_export.py", line 115, in <module>
    session_run()
  File "gpt2_past_export.py", line 102, in session_run
    sequence= cpu_model.run(None, {"input_ids":inputs_onnx["input_ids"]})
  File "/home/vishnu/anaconda3/envs/speech-recognition/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 119, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 7 inputs. Input Feed contains 1
```
Is there a way to avoid this error when giving less number of inputs than the number of inputs given during export.

**Comment by HectorSVC** [comment]
How did you make the input as optional input?
The error message is from the code here:
https://github.com/microsoft/onnxruntime/blob/ba51774a1f73f77948505816d8a57d405d40bd80/onnxruntime/python/onnxruntime_inference_collection.py#L182-L184
The code also confirms that we do support optional inputs.

**Comment by vishnu-hue** [comment]
How to make the input as optional input?

**Comment by HectorSVC** [comment]
Optional input usually initialized by Initializer. Check out the test code and example model below:
https://github.com/pranav-prakash/onnxruntime-riscv/blob/8cc2a12407cef7fedb6b07f71e6e1c707cfcf1a7/onnxruntime/test/framework/inference_session_test.cc#L998
https://github.com/pranav-prakash/onnxruntime-riscv/blob/2021-02-18/onnxruntime/test/testdata/optional_inputs_ir4.onnx

**Comment by vishnu-hue** [comment]
Thanks for the help.
