### ISSUE TITLE
expand fails when leading shape value is -1

### ISSUE THREAD

**Issue by MainRo** [microsoft/onnxruntime#7072]
**Describe the bug**
I am currently implementing an ONNX serializer of EBMs (explainable boosting machines). One of the needed operations is *expand*. The shape of the input tensors is [None, 1] and I need to expand them to [None, 3]

For example, given this input tensor:
[[0.1], [1.2], [11], [4.2]]

I expect this output tensor:
```
[
  [0.1, 0.1, 0.1],
  [1.2, 1.2, 1.2],
  [11, 11, 11], 
  [4.2, 4.2, 4.2]
]
```

When I set the shape input parameter to a tensor [-1, 3], onnx runtime fails with this error:
>onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Expand node. Name:'' Status Message: invalid expand shape

However, if I set it for to [4, 3], this works with the example input. Since the first dimension of my tensor is the batch size, I cannot fix the value in the input shape parameter.

Is this a bug in onnx-runtime, or should I use the operator in another way?

**Urgency**
This prevents the implementation of the support of multiclass classification in the serializer. I would get this working within several weeks.

**System information**
- ubuntu 18.04:
- ONNX Runtime installed from binary (pypi):
- ONNX Runtime version: 1.6.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**

```
sess = rt.InferenceSession('expand.onnx')
pred_onx = sess.run(None, {
            'i': [
                [0.1],
                [1.2],
                [11],
                [4.2],
            ]
        })
print(pred_onx)
```
**Expected behavior**

the result should be:
```
[
  [0.1, 0.1, 0.1],
  [1.2, 1.2, 1.2],
  [11, 11, 11], 
  [4.2, 4.2, 4.2]
]
```

**Screenshots**
Not applicable

**Additional context**
None

**Comment by MainRo** [comment]
[expand.zip](https://github.com/microsoft/onnxruntime/files/6170286/expand.zip)

**Comment by RandySheriffH** [comment]
@MainRo, looking into the case ...

**Comment by harishankar-gopalan** [comment]
Is there any way to work around this ? I have a BERT encoder graph where there is a similar Expand operation which seems to fail with similar error message.
`2022-07-03 16:19:02.557 java[91983:2786555] 2022-07-03 16:19:02.557614 [E:onnxruntime:, sequential_executor.cc:364 Execute] Non-zero status code returned while running Expand node. Name:'Expand_21' Status Message: invalid expand shape
Exception in thread "main" ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Expand node. Name:'Expand_21' Status Message: invalid expand shape
	at ai.onnxruntime.OrtSession.run(Native Method)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:293)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:236)
	at ai.onnxruntime.OrtSession.run(OrtSession.java:205)`

**Comment by DeepakSaini119** [comment]
I am facing a similar error 
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Expand node. Name:'/Expand' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument`

**Comment by DeepakSaini119** [comment]
> I am facing a similar error `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Expand node. Name:'/Expand' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument`

In this case, the error was misleading. the GPU was going OOM, reducing the batch size resolved this issue for me.
