### ISSUE TITLE
TensorRT supports only Bert based models but not Roberta based (or anything else)

### ISSUE THREAD

**Issue by pommedeterresautee** [microsoft/onnxruntime#7073]
**Describe the bug**
TensorRT provider compiles Bert based models but crashes when we try to use any other flavor, including Roberta based model.
Roberta based model works well with CPU and CUDA providers.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.10 (same on other Ubuntu 20.04)
- ONNX Runtime installed from (source or binary): source (from master branch tag `v1.7.1`)
- ONNX Runtime version: v1.7.1
- Python version: 3.8
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: 11.0 (tried with 11.1 too)
- GPU model and memory: Nvidia 3090 - 24 Gb (driver 460.32.03)

**To Reproduce**
```python
import logging
import os
from pathlib import Path

from onnxruntime import InferenceSession, SessionOptions, get_all_providers
from transformers.convert_graph_to_onnx import convert


def create_model_for_provider(path: str, provider: str) -> InferenceSession:
    assert provider in get_all_providers(), f"provider {provider} not found, {get_all_providers()}"

    options = SessionOptions()
    return InferenceSession(path, options, providers=[provider])


logging.basicConfig(level=logging.INFO)

onnx_path = "output/test_onnx/model.onnx"
# model = "bert-base"
model = "roberta-base"

try:
    os.remove(onnx_path)
except:
    pass

convert(framework="pt",
        model=model,
        output=Path(onnx_path),
        opset=12,
        pipeline_name="feature-extraction")

print("-------- CPU -------")
_ = create_model_for_provider(path=onnx_path, provider="CPUExecutionProvider")
print("-------- CUDA -------")
_ = create_model_for_provider(path=onnx_path, provider="CUDAExecutionProvider")
print("-------- TensorRt -------")
_ = create_model_for_provider(path=onnx_path, provider="TensorrtExecutionProvider")

```

It produces those logs:

```
ONNX opset version set to: 12
Loading pipeline (model: roberta-base, tokenizer: roberta-base)
Using framework PyTorch: 1.8.0+cu111
Found input input_ids with shape: {0: 'batch', 1: 'sequence'}
Found input attention_mask with shape: {0: 'batch', 1: 'sequence'}
Found output output_0 with shape: {0: 'batch', 1: 'sequence'}
Found output output_1 with shape: {0: 'batch'}
Ensuring inputs are in correct order
token_type_ids is not present in the generated input list.
Generated inputs order: ['input_ids', 'attention_mask']
/home/geantvert/.local/share/virtualenvs/okdoc/lib/python3.8/site-packages/transformers/modeling_utils.py:1759: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(
-------- CPU -------
-------- CUDA -------
2021-03-19 12:03:56.341882857 [W:onnxruntime:Default, fallback_cpu_capability.cc:135 GetCpuPreferredNodes] Force fallback to CPU execution for node: Gather_5
2021-03-19 12:03:56.341896060 [W:onnxruntime:Default, fallback_cpu_capability.cc:135 GetCpuPreferredNodes] Force fallback to CPU execution for node: Unsqueeze_7
2021-03-19 12:03:56.341901822 [W:onnxruntime:Default, fallback_cpu_capability.cc:135 GetCpuPreferredNodes] Force fallback to CPU execution for node: Gather_2
2021-03-19 12:03:56.341906551 [W:onnxruntime:Default, fallback_cpu_capability.cc:135 GetCpuPreferredNodes] Force fallback to CPU execution for node: Unsqueeze_6
2021-03-19 12:03:56.341911880 [W:onnxruntime:Default, fallback_cpu_capability.cc:135 GetCpuPreferredNodes] Force fallback to CPU execution for node: Concat_8
-------- TensorRt -------
2021-03-19 12:03:59.507090952 [E:onnxruntime:, inference_session.cc:1293 operator()] Exception during initialization: cannot create std::vector larger than max_size()
Traceback (most recent call last):
  File "/home/geantvert/workspace/..../src/benchmark.py", line 38, in <module>
    _ = create_model_for_provider(path=onnx_path, provider="TensorrtExecutionProvider")
  File "/home/geantvert/workspace/..../src/benchmark.py", line 13, in create_model_for_provider
    return InferenceSession(path, options, providers=[provider])
  File "/home/geantvert/.local/share/virtualenvs/okdoc/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/geantvert/.local/share/virtualenvs/okdoc/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: cannot create std::vector larger than max_size()
```

**Expected behavior**
I expect that the tensorRT provider to take Roberta based models like CUDA and CPU provider.
I have noticed that on https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT they only do tests on Bert based models, and may be it just doesn't support anything else but it's documented nowhere.

**Screenshots**
N/A

**Additional context**

More original (but very used) architecture produces even more strange errors like `distilbert-base-uncased` model.
Not shown in the code, but the produced models when used with CPU and CUDA providers works very well.

**Comment by stevenlix** [comment]
Thanks for reporting this. I've reproduced the issue and will take a look.

**Comment by pommedeterresautee** [comment]
@stevenlix Hi, have you made any progress on this strange bug?

**Comment by mkserge** [comment]
Hi, I am also running into the same exact issue. RoBERTa Large on ONNX with TensorRT runtime.

**Comment by mkserge** [comment]
@stevenlix any chance you managed to take a look at this? Have the same issue when initializing the session

```
create_model_for_provider
    session = InferenceSession(model_path, options, providers=[provider])
  File "/home/mrc/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/mrc/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: cannot create std::vector larger than max_size()
```

**Comment by stevenlix** [comment]
Please use OnnxRuntime master with TensorRT8.0 GA. I run Roberta and it passed.

**Comment by pommedeterresautee** [comment]
It is now working for me too. Closing.
