### ISSUE TITLE
Incompatible dimensions error in a Mul node at runtime.

### ISSUE THREAD

**Issue by II245** [microsoft/onnxruntime#7098]
**Describe the bug**
When I export a model from Pytorch (1.8.0) to onnx with jit decorator I get ShapeInferenceError at runtime. Please, see the output below.

```
1.8.0
{'o': tensor([[0.7016, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3032, 0.2104, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]], device='cuda:0')}
Traceback (most recent call last):
  File "fp32_jit_prim_dtype_repro.py", line 41, in <module>
    runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx')
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Mul_48) Op (Mul) [ShapeInferenceError] Incompatible dimensions
```

**Urgency**
none.

**System information**
 - OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
 - ONNX Runtime installed from (source or binary): binary
 - ONNX Runtime version: onnxruntime-1.6.0
 - Python version: Python 3.8.5
 - Pytorch version: 1.8.0
 - CUDA/cuDNN version: CUDA Version: 10.2
 - GPU model and memory: Tesla V100 (32G)

**To Reproduce**
```python
import onnxruntime
from torch import nn
import torch

print(torch.__version__)

@torch.jit.script
def compute_output_lengths(x, lengths_fraction):
	return (lengths_fraction * x.shape[-1]).ceil().long()

@torch.jit.script
def temporal_mask(x, lengths):
	return (torch.arange(x.shape[-1], device = x.device, dtype = lengths.dtype).unsqueeze(0) <
			lengths.unsqueeze(1)).view(x.shape[:1] + (1, ) * (len(x.shape) - 2) + x.shape[-1:])

class Model(nn.Module):
	def forward(self, x, xlen):
		l = compute_output_lengths(x, xlen)
		tm = temporal_mask(x, l)
		x = x * tm
		return dict(o=x)

model = Model()
model.to(device='cuda')

x = torch.rand(2, 10).to( device='cuda')
xlen = torch.rand(2).to( device='cuda')

print(model(x, xlen))

torch.onnx.export(
		model, (x, xlen),
		'fp32_jit_prim_dtype_repro.onnx',
		verbose=False,
		opset_version=12,
		export_params=None,
		do_constant_folding=True,
		input_names=['x', 'xlen']
)

runtime = onnxruntime.InferenceSession('fp32_jit_prim_dtype_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy(), xlen=xlen.cpu().numpy())))
```

[fp32_jit_prim_dtype_repro_onnx.zip](https://github.com/microsoft/onnxruntime/files/6185707/fp32_jit_prim_dtype_repro_onnx.zip)

**Expected behavior**
Inference without ONNXRuntimeError.

Thank you for your reply!

**Comment by KeDengMS** [comment]
Seems like an exporter problem where ```(1, ) * (len(x.shape) - 2)``` was handled incorrectly as Mul op. In PyTorch, the output is an empty tuple since len(x.shape) -2 = 0, while in the exported model it becomes a scalar 0. @spandantiwari

Below are the logs from symbolic shape inference:
```
Gather: Gather_32
  Input 0: 33 
  Input 1: 32 
  34: [1] 7
  Sympy Data: [2]
Squeeze: Squeeze_33
  Input 0: 34 
  35: [] 7
  Sympy Data: [2]
Constant: Constant_34
  36: [] 7
  Sympy Data: 2
Sub: Sub_35
  Input 0: 35 
  Input 1: 36 
  37: [] 7
  Sympy Data: [0]
Constant: Constant_36
  38: [1] 7
  Sympy Data: [1]
Mul: Mul_37
  Input 0: 38 
  Input 1: 37 
  39: [1] 7
  Sympy Data: [0] *** this is incorrect ***
Concat: Concat_38
  Input 0: 30 
  Input 1: 39 
  40: [2] 7
  Sympy Data: [2, 0]
```

**Comment by shubhambhokare1** [comment]
Opened similar issue in PyTorch, maybe we can close the issue here

**Comment by spandantiwari** [comment]
This seems like a export issue. We have opened an item under PyTorch for this: https://github.com/pytorch/pytorch/issues/55597, and will investigate this.

@II245 Please stay tuned to that thread. We will close this one here.
