### ISSUE TITLE
Failed to build MinSizeRel on Linux

### ISSUE THREAD

**Issue by huangrunqian** [microsoft/onnxruntime#7100]
**Describe the bug**
Hi, I was trying to build a MinSizeRel ORT on Linux, when I set the --config as Release, everything works fine, however, it would fail if I set the --config as MinSizeRel.

**Urgency**
Hope anyone can help me out soon :)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.3 LTS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.0
- Python version: 3.6.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc version 5.4.0, cmake version 3.20.0-rc3
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
The building command is as below:
`./build.sh --config=MinSizeRel --build_shared_lib --minimal_build --disable_ml_ops --disable_exceptions --include_ops_by_config required_operators.config --skip_tests --parallel`
And the required_operators.config looks like:
```
ai.onnx;1;ReduceMean,Squeeze,Transpose,Unsqueeze
ai.onnx;4;Concat
ai.onnx;6;Relu,Sqrt
ai.onnx;7;Add,Pow,Sub
ai.onnx;9;BatchNormalization,Gemm
com.microsoft;1;FusedConv
```

**Expected behavior**
Build successfully.

**Screenshots**

```
...
[ 77%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/sequence/concat_from_sequence.cc.o
[ 77%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/sequence/sequence_ops.cc.o
[ 77%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/tensor/cast_op.cc.o
[ 77%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/tensor/compress.cc.o
[ 77%] Linking CXX static library libonnx_test_data_proto.a
[ 77%] Built target onnx_test_data_proto
[ 78%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/TestCase.cc.o
[ 78%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/tensor/concat.cc.o
/home/github/onnxruntime/onnxruntime/core/providers/cpu/generator/random.cc: In function 'onnxruntime::common::Status onnxruntime::RandomNormalCompute(float, float, std::default_random_engine&, onnx::TensorProto::DataType, onnxruntime::Tensor&)':
/home/github/onnxruntime/onnxruntime/core/providers/cpu/generator/random.cc:275:15: error: '*((void*)& distribution +16)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 static Status RandomNormalCompute(float mean, float scale,
               ^
cc1plus: all warnings being treated as errors
[ 79%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/tensor/dynamicquantizelinear.cc.o
CMakeFiles/onnxruntime_providers.dir/build.make:229: recipe for target 'CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/generator/random.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/home/github/onnxruntime/onnxruntime/core/providers/cpu/generator/random.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/TestResultStat.cc.o
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/callback.cc.o
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/TestCaseResult.cc.o
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/dataitem_request.cc.o
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/heap_buffer.cc.o
[ 79%] Linking CXX static library libonnxruntime_framework.a
[ 79%] Built target onnxruntime_framework
[ 79%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/onnx_model_info.cc.o
[ 80%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/pb_helper.cc.o
[ 80%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/tensorprotoutils.cc.o
[ 80%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/testcase_driver.cc.o
[ 80%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/testcase_request.cc.o
[ 80%] Building CXX object CMakeFiles/onnx_test_runner_common.dir/home/github/onnxruntime/onnxruntime/test/onnx/testenv.cc.o
[ 80%] Linking CXX static library libonnx_test_runner_common.a
[ 80%] Built target onnx_test_runner_common
[ 81%] Linking CXX static library libonnxruntime_util.a
[ 81%] Built target onnxruntime_util
CMakeFiles/Makefile2:1549: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/github/onnxruntime/tools/ci_build/build.py", line 2003, in <module>
    sys.exit(main())
  File "/home/github/onnxruntime/tools/ci_build/build.py", line 1938, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/github/onnxruntime/tools/ci_build/build.py", line 1017, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/github/onnxruntime/tools/ci_build/build.py", line 536, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/github/onnxruntime/tools/python/util/run.py", line 44, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/github/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel', '--', '-j48']' returned non-zero exit status 2.
```

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by skottmckay** [comment]
I don't have that setup available to try and repo. We don't hit this issue in our CI builds. Could be due to different inlining that happens/doesn't happen between Release and MinSizeRel with that version of gcc, or possibly the latest cmake version creates a slightly different build config.
 
Do you need to use MinSizeRel or is Release fine? The Release build will be a little larger, but that may not be significant.

**Comment by huangrunqian** [comment]
I'm using Release build temporarily, however other users may also come into this problem when building MinSizeRel. Hope it can be fixed someday :)

**Comment by gwang-msft** [comment]
This is probably caused by the undefined behavior of std::normal_distribution constructors, 
'_The behavior is undefined if stddev is not greater than zero._',
see https://en.cppreference.com/w/cpp/numeric/random/normal_distribution/normal_distribution

And the behavior of warning ` -Werror=maybe-uninitialized` is different between different gcc versions, you may be able to unblock by using a more recent gcc version.

**Comment by huangrunqian** [comment]
I tried gcc 10.1.0, and it works! Maybe the documentation should be updated to tell the users about the minimun version of gcc :)
