### ISSUE TITLE
Invalid model after quantization for onnxruntime 1.7.0

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#7105]
**Describe the bug**
Model quantized with onnxruntime 1.7.0 can not be inferenced with onnxruntime 1.7.0:
```
Traceback (most recent call last):
  File "test.py", line 133, in <module>
    init()
  File "test.py", line 42, in init
    session = ort.InferenceSession(model)
  File "/opt/miniconda/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/opt/miniconda/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 226, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./after_quant.onnx failed:This is an invalid model. Error: two nodes wit (_MatMul_quant).
```
Quantization with no error:
```
Warning: The original model opset version is 10, which does not support node fusions. Please update the model to opset >= 11 for better performance.
```
Model can be quantized and inferenced with onnxruntime 1.5.2.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from official released python wheel
- ONNX Runtime version: 1.7.0
- Python version: 3.6

**To Reproduce**
quantize.py
```
'''onnx model quantization'''
import logging
import os
import onnx
from shutil import copy
from onnxruntime import quantization

quantization.quantize_dynamic("good.onnx", 'after_quant.onnx')
```
model before quantization can be found here.
[model.zip](https://github.com/microsoft/onnxruntime/files/6187432/model.zip)

**Comment by yufenglee** [comment]
The bug was fixed with PR #7111
