### ISSUE TITLE
Build python wheel failed

### ISSUE THREAD

**Issue by EasonChow001** [microsoft/onnxruntime#7143]
**Describe the bug**
I wanna build a python wheel use command like : 
`./build.sh --config Release --build_shared_lib --build_wheel --parallel`

But it seems failed in running some test cases and no wheel package be found in build:

.s.s.s.s2021-03-26 14:42:48.980295783 [W:onnxruntime:, graph.cc:1074 Graph] Initializer pos_at appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
.s.s.s.s.s.s.s.s.s.s.s

======================================================================

ERROR: test_if_seq_cpu (__main__.OnnxBackendNodeModelTest)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 309, in run
    ref_outputs.append(numpy_helper.to_array(tensor))
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/numpy_helper.py", line 28, in to_array
    raise ValueError(
ValueError: Currently not supporting loading segments.

======================================================================

ERROR: test_loop13_seq_cpu (__main__.OnnxBackendNodeModelTest)

---------------------------------------------------------------------

Traceback (most recent call last):

  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 301, in run
    inputs.append(numpy_helper.to_array(tensor))
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/numpy_helper.py", line 69, in to_array
    np.asarray(
ValueError: cannot reshape array of size 0 into shape (115,101,113,95,101,109,112,116,121)

======================================================================

ERROR: test_sequence_insert_at_back_cpu (__main__.OnnxBackendNodeModelTest)

----------------------------------------------------------------------

Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 301, in run
    inputs.append(numpy_helper.to_array(tensor))
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/numpy_helper.py", line 28, in to_array
    raise ValueError(
ValueError: Currently not supporting loading segments.

 ======================================================================

 ERROR: test_sequence_insert_at_front_cpu (__main__.OnnxBackendNodeModelTest)

 ----------------------------------------------------------------------

 Traceback (most recent call last):

  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/backend/test/runner/__init__.py", line 301, in run
    inputs.append(numpy_helper.to_array(tensor))
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/site-packages/onnx/numpy_helper.py", line 28, in to_array
    raise ValueError(
ValueError: Currently not supporting loading segments.

----------------------------------------------------------------------

 Ran 1844 tests in 8.604s

 FAILED (errors=4, skipped=1117)

 Traceback (most recent call last):

  File "/home/zys/onnxruntime/tools/ci_build/build.py", line 2017, in <module>
    sys.exit(main())
  File "/home/zys/onnxruntime/tools/ci_build/build.py", line 1949, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "/home/zys/onnxruntime/tools/ci_build/build.py", line 1421, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnx_backend_test_series.py'], cwd=cwd, dll_path=dll_path)
  File "/home/zys/onnxruntime/tools/ci_build/build.py", line 540, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/zys/onnxruntime/tools/python/util/run.py", line 41, in run
    completed_process = subprocess.run(
  File "/root/anaconda3/envs/py3.8-torch/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/py3.8-torch/bin/python3', 'onnx_backend_test_series.py']' returned non-zero exit status 1.

**Urgency**
We get strict project-related timelines.  Hoped be dealt as soon as possible.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux  x86_64
- ONNX Runtime installed from (source or binary):  source 
- ONNX Runtime version: 1.7.0
- Python version: Python 3.8.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):  gcc (GCC) 8.3.1
- CUDA/cuDNN version: 
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
I hoped get a built python wheel.

**Screenshots**
newest onnxruntime code with commit id = 3771e0bf10cde8 

**Additional context**

**Comment by EasonChow001** [comment]
@jcwchen Hi, i saw a relevant [issue,](https://github.com/onnx/onnx/issues/2984) but still not know how to fix it. Do u know about this failure?

**Comment by jcwchen** [comment]
Hi @EasonChow001,
Did you build the latest ORT?  It is an old issue in ONNX (but it has been fixed) and ORT has bumped its ONNX to support it. Or did you change the ONNX under ORT? Thanks

**Comment by snnn** [comment]
I think you need to install onnx from source  and from onnxruntime's cmake/external/onnx dir.

**Comment by EasonChow001** [comment]
> I think you need to install onnx from source and from onnxruntime's cmake/external/onnx dir.

YES!  Your are right. I removed cmake/external/onnx dir and reclone onnx project in cmake/external. It works !
