### ISSUE TITLE
Build problem in "Using NNAPI with ONNX Runtime Mobile"

### ISSUE THREAD

**Issue by evanescenceakii** [microsoft/onnxruntime#7186]
So I've successfully converted my onnx model to .ort and I'm trying to create the minimal build for android with NNAPI support.
After creating and Android Build with NNAPI included, as instructed, when I try this command:
`.\build.bat --config RelWithDebInfo --android --android_sdk_path C:\Users\chris\Android\ --android_ndk_path C:\Users\chris\Android\ndk\22.1.7171670\ --android_abi arm64-v8a --android_api 29 --cmake_generator Ninja --minimal_build extended --use_nnapi --disable_ml_ops --disable_exceptions --build_shared_lib --skip_tests --include_ops_by_config C:\Users\chris\Downloads\for_christina\data\model.required_operators.config`
I get this log:

```
2021-03-30 23:57:11,766 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2021-03-30 23:57:11,770 reduce_op_kernels [INFO] - Processing C:\Users\chris\onnxruntime\onnxruntime\core\providers\cpu\cpu_execution_provider.cc
2021-03-30 23:57:11,785 reduce_op_kernels [INFO] - Processing C:\Users\chris\onnxruntime\onnxruntime\contrib_ops\cpu\cpu_contrib_kernels.cc
2021-03-30 23:57:11,793 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,793 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:DFT(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,793 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,804 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:IDFT(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,806 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,814 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:HannWindow(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,818 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,818 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:HammingWindow(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,826 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,828 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:BlackmanWindow(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,838 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,840 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:MelWeightMatrix(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,848 op_registration_utils [WARNING] - Unknown domain for ONNX Runtime constant of kMSExperimentalDomain.
2021-03-30 23:57:11,849 reduce_op_kernels [WARNING] - Keeping kMSExperimentalDomain:STFT(1) registration from unknown domain: kMSExperimentalDomain
2021-03-30 23:57:11,854 reduce_op_kernels [INFO] - Processing C:\Users\chris\onnxruntime\orttraining\orttraining\training_ops\cpu\cpu_training_kernels.cc
2021-03-30 23:57:11,888 build [INFO] - Build started
2021-03-30 23:57:11,889 util.run [INFO] - Running subprocess in 'C:\Users\chris\onnxruntime'
['git', 'submodule', 'sync', '--recursive']
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary'
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary/src/3rdParty/eigen'
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary/src/3rdParty/re2'
Synchronizing submodule url for 'cmake/external/SafeInt/safeint'
Synchronizing submodule url for 'cmake/external/coremltools'
Synchronizing submodule url for 'cmake/external/cub'
Synchronizing submodule url for 'cmake/external/cxxopts'
Synchronizing submodule url for 'cmake/external/date'
Synchronizing submodule url for 'cmake/external/dlpack'
Synchronizing submodule url for 'cmake/external/eigen'
Synchronizing submodule url for 'cmake/external/flatbuffers'
Synchronizing submodule url for 'cmake/external/googletest'
Synchronizing submodule url for 'cmake/external/json'
Synchronizing submodule url for 'cmake/external/libprotobuf-mutator'
Synchronizing submodule url for 'cmake/external/mimalloc'
Synchronizing submodule url for 'cmake/external/mp11'
Synchronizing submodule url for 'cmake/external/nsync'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/optional-lite'
Synchronizing submodule url for 'cmake/external/protobuf'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/re2'
Synchronizing submodule url for 'cmake/external/tensorboard'
Synchronizing submodule url for 'cmake/external/tvm'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/HalideIR'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dlpack'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dmlc-core'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/wil'
Synchronizing submodule url for 'server/external/spdlog'
2021-03-30 23:57:15,555 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-03-30 23:57:15,555 util.run [INFO] - Running subprocess in 'C:\Users\chris\onnxruntime'
['git', 'submodule', 'update', '--init', '--recursive']
2021-03-30 23:57:35,871 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-03-30 23:57:35,871 build [INFO] - Building protoc for host to be used in cross-compiled build process
2021-03-30 23:57:35,881 util.run [INFO] - Running subprocess in 'C:\Users\chris\onnxruntime\\build\Windows\host_protoc'
['C:\\Program Files\\CMake\\bin\\cmake.EXE', 'C:\\Users\\chris\\onnxruntime\\cmake\\external\\protobuf\\cmake', '-Dprotobuf_BUILD_TESTS=OFF', '-Dprotobuf_WITH_ZLIB_DEFAULT=OFF', '-Dprotobuf_BUILD_SHARED_LIBS=OFF', '-G', 'Ninja']
--
-- 3.11.3.0
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/chris/onnxruntime/build/Windows/host_protoc
2021-03-30 23:57:36,791 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-03-30 23:57:36,791 util.run [INFO] - Running subprocess in 'C:\Users\chris\onnxruntime'
['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\chris\\onnxruntime\\\\build\\Windows\\host_protoc', '--config', 'Release', '--target', 'protoc']
[1/51] Building CXX object CMakeFiles/libprotobuf.dir/C_/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc.obj
FAILED: CMakeFiles/libprotobuf.dir/C_/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc.obj
C:\PROGRA~2\CODEBL~1\MinGW\bin\C__~1.EXE -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_PTHREAD -I. -IC:/Users/chris/onnxruntime/cmake/external/protobuf/src -std=c++11 -MD -MT CMakeFiles/libprotobuf.dir/C_/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc.obj -MF CMakeFiles\libprotobuf.dir\C_\Users\chris\onnxruntime\cmake\external\protobuf\src\google\protobuf\io\io_win32.cc.obj.d -o CMakeFiles/libprotobuf.dir/C_/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc.obj -c C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc
C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc: In function 'int google::protobuf::io::win32::stat(const char*, google::protobuf::io::win32::_stat*)':
C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc:315:40: error: cannot convert 'google::protobuf::io::win32::_stat*' to '_stat*' for argument '2' to 'int _wstat(const wchar_t*, _stat*)'
   return ::_wstat(wpath.c_str(), buffer);
                                        ^
In file included from C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc:52:0:
C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.h:75:51: note: class type 'google::protobuf::io::win32::_stat' is incomplete
 PROTOBUF_EXPORT int stat(const char* path, struct _stat* buffer);
                                                   ^
C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc: In function 'FILE* google::protobuf::io::win32::fopen(const char*, const char*)':
C:/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/io/io_win32.cc:337:10: error: '::_wfopen' has not been declared
   return ::_wfopen(wpath.c_str(), wmode.c_str());
          ^
[6/51] Building CXX object CMakeFiles/libprotobuf.dir/C_/Users/chris/onnxruntime/cmake/external/protobuf/src/google/protobuf/compiler/importer.cc.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\chris\onnxruntime\\tools\ci_build\build.py", line 2023, in <module>
    sys.exit(main())
  File "C:\Users\chris\onnxruntime\\tools\ci_build\build.py", line 1918, in main
    cmake_path, source_dir, build_dir, args)
  File "C:\Users\chris\onnxruntime\\tools\ci_build\build.py", line 1673, in build_protoc_for_host
    run_subprocess(cmd_args)
  File "C:\Users\chris\onnxruntime\\tools\ci_build\build.py", line 544, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\chris\onnxruntime\tools\python\util\run.py", line 44, in run
    env=env, shell=shell)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\Users\\chris\\onnxruntime\\\\build\\Windows\\host_protoc', '--config', 'Release', '--target', 'protoc']' returned non-zero exit status 1.
```

I have no idea what's wrong. Any leads?

**Comment by pranavsharma** [comment]
@gwang-msft @skottmckay can one of you take a look?

**Comment by gwang-msft** [comment]
The build process failed to build the protoc for the host system (Windows), and seems MinGW compiler is used, please try to build the host protoc using Visual Studio, for example, start the building process from a Visual Studio Developer command prompt

**Comment by evanescenceakii** [comment]
Thanks! Actually changing CMakeCache.txt 's line to this:
` CMAKE_CXX_FLAGS:STRING=-U__STRICT_ANSI__`
fixed this error. Continuing with new issues now!
