### ISSUE TITLE
onnxruntime can't recognize my custom op even though onnx can!

### ISSUE THREAD

**Issue by dedoogong** [microsoft/onnxruntime#7254]
I implemented a custome op of type "ASLFeatPluginX" in both onnx and onnx-runtime.

after loading my onnx model, it called onnx.checker.check_model(model) and it passed without any error.
but onnx-runtime shows 

  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:ASLFeatPluginX0 : No Op registered for ASLFeatPluginX with domain_version of 11

I changed some codes as below;

1. cpu/aslfeatx.cc
``` 
namespace onnxruntime {
namespace contrib { 

#define REGISTER_CPU_KERNEL_TYPED(T)                                            \
  ONNX_OPERATOR_TYPED_KERNEL_EX(                                                \
      ASLFeatPluginX,                                                           \
      kOnnxDomainAlias,                                                                \
      11,                                                                        \
      T,                                                                        \
      kCpuExecutionProvider,                                                    \
      KernelDefBuilder()                                                        \
          .TypeConstraint("T", BuildKernelDefConstraints<T>()),                 \
      ASLFeatPluginX<T>); 

REGISTER_CPU_KERNEL_TYPED(float)
REGISTER_CPU_KERNEL_TYPED(double)
//REGISTER_CPU_KERNEL_TYPED(MLFloat16)        

template <typename T>
ASLFeatPluginX<T>::ASLFeatPluginX(const OpKernelInfo& op_kernel_info)
    : OpKernel(op_kernel_info) { 
} 
template <typename T>
Status ASLFeatPluginX<T>::Compute(OpKernelContext* p_ctx) const { 
....
```
2. cuda/aslfeatx.cc
```
namespace onnxruntime {
namespace contrib { 
namespace cuda { 
 
 
#define REGISTER_CUDA_KERNEL_TYPED(T)                                            \
  ONNX_OPERATOR_TYPED_KERNEL_EX(                                                \
      ASLFeatPluginX,                                                           \
      kOnnxDomainAlias,                                                                \
      11,                                                                        \
      T,                                                                        \
      kCudaExecutionProvider,                                                    \
      KernelDefBuilder()                                                        \
          .TypeConstraint("T", BuildKernelDefConstraints<T>()),                 \
      ASLFeatPluginX<T>); 
        
REGISTER_CUDA_KERNEL_TYPED(float)

template <typename T>
ASLFeatPluginX<T>::ASLFeatPluginX(const OpKernelInfo& op_kernel_info)
    : CudaKernel(op_kernel_info) { 
} 

template <typename T>//, typename U>
Status ASLFeatPluginX<T>::ComputeInternal(OpKernelContext* ctx) const {
```
3. operator_sets.h
```
....

class ONNX_OPERATOR_SET_SCHEMA_CLASS_NAME(Onnx, 11, ASLFeatPluginX);
....
....
    fn(GetOpSchema<ONNX_OPERATOR_SET_SCHEMA_CLASS_NAME(Onnx, 11, ASLFeatPluginX)>());  
....
.... 
```
4. contrib_defs.cc ( PATH : onnxruntime/onnxruntime/core/graph/contrib_ops/contrib_defs.cc)
```

  ONNX_CONTRIB_OPERATOR_SCHEMA(ASLFeatPluginX)
      .SetDomain(kOnnxDomainAlias)
      .SinceVersion(11)
      .Input(0, "X", "Input tensor. Every matrix in the batch must be invertible.", "T")
      .Output(0, "Y", "Output tensor of the same type and shape as the input tensor.", "T")
      .TypeConstraint(
          "T",
          {//"tensor(float16)",
           "tensor(float)"},
           //"tensor(double)"},
          "Constrain input and output types to float tensors.")
      .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
        // Type inference
        using namespace ONNX_NAMESPACE;
```
5.  defs.cc ( PATH : onnxruntime/onnx/onnx/defs/tensor/defs.cc)
```
ONNX_OPERATOR_SET_SCHEMA(
    ASLFeatPluginX,
    11,
    OpSchema() 
        .Attr(
            "ksizes",          
            "Kernel Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE)        
        .Attr(
            "padding",          
            "Padding Sizes.",
            AttributeProto::STRING,
            OPTIONAL_VALUE)
        .Attr(
            "rates",          
            "Rates Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE)  
        .Attr(
            "strides",          
            "Strides Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE) 
        .Input(
            0,
            "X",
            "Input data tensor from the previous operator; "
            "4-D feature map of shape (N, C, H, W), "
            "where N is the batch size, C is the number of channels, "
            "and H and W are the height and the width of the data.",
            "T")
        .Output(
            0,
            "Y",
            "mesh-pached output, 4-D tensor of shape "
            "(num_rois, C(9), output_height, output_width).",
            "T")
        .TypeConstraint(
            "T",
            {"tensor(float)"},//"tensor(float16)", , "tensor(double)"
            "Constrain types to float tensors.")
        .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
```

**Urgency**
Very Urgent for my project

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.1
- Python version: 3.6
- Visual Studio version (if applicable): no
- GCC/Compiler version (if compiling from source): 7.5.0.
- CUDA/cuDNN version: 11.0/8.0.1
- GPU model and memory: V100/32GB

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by KeDengMS** [comment]
Could you follow this [doc](https://www.onnxruntime.ai/docs/how-to/add-custom-op.html) to add a custom op? Seems you are making changes to onnx which is not the recommended approach.

**Comment by dedoogong** [comment]
Thank you so much for your reply!
Yes, I already refered the link while implementing the custom op. 
The problem is, I use onnx-simplifer which call both onnx and onnx-runtime API as below;
```
....
onnx.checker.check_model(model)
....
....
rt.InferenceSession(model.SerializeToString(
    ), sess_options=sess_options, providers=['CPUExecutionProvider'])
```
and while running ORT's inferenceSession, it also checks the model as onnx does. 

As you mentioned, yes, the custom op definition is duplicated in both ONNX and ORT.
but if I omit the shema definition in onnx side, it throws the same error while running the first onnx model check.

**Comment by KeDengMS** [comment]
Would this [doc](https://www.onnxruntime.ai/docs/how-to/export-pytorch-model.html) help?

**Comment by dedoogong** [comment]
Oh thank you~! 
Sorry I already refered that page too ;) I will try to dig it more and report the result again later

**Comment by dedoogong** [comment]
when I ㅣload my model using Netron, it shows 
```
format ONNX v7
imports ai.onnx v13
```
so I used "kOnnxDomainAlias" instead of "kOnnxDomain" as it is just defined as "" in "constants.h" when specifying the domain in ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME and ONNX_CONTRIB_OPERATOR_SCHEMA.

Plus, I set all opversion to 11 including .SinceVersion() as below;

ONNX_OPERATOR_TYPED_KERNEL_EX(                                                \
      ASLFeatPluginY,                                                           \
      kOnnxDomainAlias,                                                                \
      11, 

ONNX_CONTRIB_OPERATOR_SCHEMA(BiasGelu)
      .SetDomain(kMSDomain)
      .SinceVersion(11)


is that correct?

**Comment by dedoogong** [comment]
I added some test code as below;
```

namespace onnxruntime {
namespace test {

TEST(ASLFeatYContribOpTest, ASLFeatPluginY_six_by_four_float) {
  std::cout<<"aslfeaty_test.cc helloworld"<<std::endl;
  OpTester test("ASLFeatPluginY", 1, kMSDomain);
  test.AddInput<float>("X", {1, 1, 6, 4}, {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,
                                           0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,
                                           0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,
                                           0.0f,0.0f,0.0f,0.0f,0.0f,0.0f});  

  test.AddOutput<float>("Y", {1, 9, 4, 2}, {0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f,
                                            1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f, 3.0f, 3.0f, 3.0f,

                                            0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f,
                                            1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f, 3.0f, 3.0f, 3.0f,

                                            0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f,
                                            1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f, 3.0f, 3.0f, 3.0f,

                                            0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f,
                                            1.0f, 1.0f, 1.0f, 2.0f, 2.0f, 2.0f, 3.0f, 3.0f, 3.0f});
  // (6-2) * (4-2) * 9
  test.Run();
}
```
and when I run the test, it shows the error "No registered execution providers were able to run the model."

I added some print messages to see the intermediate variable values 

aslfeatx_test.cc helloworld
rank4
 N C H W : 1x1x6x4
 kernel_start_version : 11 kernel_end_version : 2147483647
 valid_version : 0 node_since_version : 1
 kernel_start_version : 11 kernel_end_version : 2147483647
 valid_version : 0 node_since_version : 1
/workspace/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:924: Failure
Value of: has_run
  Actual: false
Expected: true
No registered execution providers were able to run the model.
[  FAILED  ] ASLFeatXContribOpTest.ASLFeatPluginX_six_by_four_float (3775 ms)
[----------] 1 test from ASLFeatXContribOpTest (3775 ms total)

[----------] 1 test from ASLFeatYContribOpTest
[ RUN      ] ASLFeatYContribOpTest.ASLFeatPluginY_six_by_four_float


I'm not sure why it fails to register my custom op even though I added all required codes(by refering "https://www.onnxruntime.ai/docs/how-to/export-pytorch-model.html") in ORT and built successfully.

**Comment by KeDengMS** [comment]
When you change ORT's implementation to kMSDomain, did you also change the onnx model to kMSDomain?

**Comment by dedoogong** [comment]
First, I think when I run "pip3 install /workspace/onnxruntime/build/Linux/RelWithDebInfo/dist/*.whl", it download prebuilt onnx from repo, not my customized onnx. that's why my codes doesn't have any impact.

```
trtuser@403d3ffdee74:/workspace/onnxruntime$ sudo pip3 install /workspace/onnxruntime/build/Linux/RelWithDebInfo/dist/onnxruntime_gpu-1.7.0-cp36-cp36m-linux_x86_64.whl
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing ./build/Linux/RelWithDebInfo/dist/onnxruntime_gpu-1.7.0-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (3.1.0)
Requirement already satisfied: cerberus in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (1.3.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (3.15.7)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (1.19.5)
Collecting onnx
  Downloading onnx-1.8.1-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |################################| 14.5 MB 8.5 MB/s 
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (20.9)
Requirement already satisfied: sympy in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (1.7.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.6/dist-packages (from onnxruntime-gpu==1.7.0) (1.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from cerberus->onnxruntime-gpu==1.7.0) (54.2.0)
Requirement already satisfied: cached-property in /usr/local/lib/python3.6/dist-packages (from h5py->onnxruntime-gpu==1.7.0) (1.5.2)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx->onnxruntime-gpu==1.7.0) (3.7.4.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from onnx->onnxruntime-gpu==1.7.0) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->onnxruntime-gpu==1.7.0) (2.4.7)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy->onnxruntime-gpu==1.7.0) (1.2.1)
Installing collected packages: onnx, onnxruntime-gpu
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx-simplifier 0.3.4 requires onnxruntime>=1.6.0, which is not installed.
Successfully installed onnx-1.8.1 onnxruntime-gpu-1.7.0

```

**Comment by KeDengMS** [comment]
This is why you should not change op schema in onnx. For manipulating onnx model in Python, please check onnx's [PythonAPIOverview.md](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md).

You may also find some Python code in test to check or change [opset_import](https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/docs/python/inference/examples/plot_profiling.py#L20-L27), or create node in [kMSDomain](https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/onnxruntime/test/python/contrib_ops/onnx_test_trilu.py#L22-L27).

**Comment by dedoogong** [comment]
Ok, now the original error is gone but another strange error appeared as below

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (ASLFeatPluginX0) Op (ASLFeatPluginX) [ShapeInferenceError] ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX Input rank must be >= 2.

and the printed value of input_shape.dim_size() was "0"! 
below is the code.
```
ONNX_OPERATOR_SET_SCHEMA(
    ASLFeatPluginX,
    11,
    OpSchema() 
        .Attr(
            "ksizes",          
            "Kernel Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE)        
        .Attr(
            "padding",          
            "Padding Sizes.",
            AttributeProto::STRING,
            OPTIONAL_VALUE)
        .Attr(
            "rates",          
            "Rates Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE)  
        .Attr(
            "strides",          
            "Strides Sizes.",
            AttributeProto::INTS,
            OPTIONAL_VALUE) 
        .Input(
            0,
            "X",
            "Input data tensor from the previous operator; "
            "4-D feature map of shape (N, C, H, W), "
            "where N is the batch size, C is the number of channels, "
            "and H and W are the height and the width of the data.",
            "T")
        .Output(
            0,
            "Y",
            "mesh-pached output, 4-D tensor of shape "
            "(num_rois, C(9), output_height, output_width).",
            "T")
        .TypeConstraint(
            "T",
            {"tensor(float)"},//"tensor(float16)", , "tensor(double)"
            "Constrain types to float tensors.")
        .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
          propagateElemTypeFromInputToOutput(ctx, 0, 0);     
        //if (hasInputShape(ctx, 0)) 
          const TensorShapeProto& input_shape =
              ctx.getInputType(0)->tensor_type().shape();
          const auto rank = static_cast<int>(input_shape.dim_size());    
          std::cout<<"ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX input_shape.dim_size() : "<<input_shape.dim_size() <<std::endl;
          std::cout<<"ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX rank"<<rank<<std::endl;
          if (rank < 2) {
            fail_shape_inference("ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX Input rank must be >= 2.")
          } 
...
```
the input node of this custom op is "Pad" and when I visualize the onnx file using Netron, there was no problem. 
you can check it here(Red box is the custom op) : https://github.com/dedoogong/ASLFeat_TRT/blob/main/aslfeatpluginx.png

**Comment by KeDengMS** [comment]
Seems earlier in the graph, there's an invalid Pad node with name _MirrorPad_. Its pads input is an initializer _pad_0_ with a shape of (4), while it's expected to be (8) since input_rank==4, according to [Pad opset11 spec](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#pad-11).

How is the model generated?

**Comment by dedoogong** [comment]
Oh, Ok thank you for your kind and fast reply!

First I used tf2onnx to convert a TF pb file to onnx
Second, I used onnx-graph surgery to replace some unsupported ops(ExtractPatch/DivNoNan) and some buggy(can't be parsed by onnx-tensorrt) ops.

below is the sub codes doing that
```
import onnx_graphsurgeon as gs
import numpy as np
import onnx
graph = gs.import_onnx(onnx.load("aslfeatv2_op11.onnx"))
target_name_list=['ExtractImagePatches', 'ExtractImagePatches_1', 'ExtractImagePatches_2',
                  'ExtractImagePatches_3', 'ExtractImagePatches_4', 'ExtractImagePatches_5']
to_remove_nodes={}
for t_name in target_name_list:
    to_remove_nodes[t_name] = [node for node in graph.nodes if node.name == t_name ][0]
count=0
to_remove_nodes_list=[]
for k in to_remove_nodes:
    target_node=to_remove_nodes[k]
    to_remove_nodes_list.append(target_node)  # ExtractImagePatches
    to_remove_nodes_list.append(target_node.i())  # # Reshape
    to_remove_nodes_list.append(target_node.i().i())  # Mul
    to_remove_nodes_list.append(target_node.i().i().i())  # Reshape
    to_remove_nodes_list.append(target_node.i().i().i().i()) # Reshape
    to_remove_nodes_list.append(target_node.i().i().i().i().i())# Range
    to_remove_nodes_list.append(target_node.i().i().i().i().i().o())  # Range->Size
    to_remove_nodes_list.append(target_node.i().i().i().i().i().o().o())  # Range->Size
    to_remove_nodes_list.append(target_node.i().i().i().i().i().o().o().o())  # Range->Size
    to_remove_nodes_list.append(target_node.o())  # Reshape
    to_remove_nodes_list.append(target_node.o().o())  # Cast
    if count%2:
        ASLFeatPlugin_node = gs.Node(op="ASLFeatPluginY", attrs=target_node.attrs)
        ASLFeatPlugin_node.name = 'ASLFeatPluginY' + str(count)
    else:
        ASLFeatPlugin_node = gs.Node(op="ASLFeatPluginX", attrs=target_node.attrs)
        ASLFeatPlugin_node.name = 'ASLFeatPluginX' + str(count)
    ASLFeatPlugin_node.inputs.append(target_node.i().i().i().i().i().i(1).i().i().i().i().i().outputs[0]) # Pad
    node_add_out = target_node.o().o().o()  # [node for node in graph.nodes if node.name == 'add_4'][0]
    ASLFeatPlugin_node.outputs.append(node_add_out.inputs[0])
    tmp_var_to_remain = node_add_out.inputs[1]  # Cast
    node_add_out.inputs.pop(), node_add_out.inputs.pop()
    node_add_out.inputs.append(tmp_var_to_remain)
    node_add_out.inputs.append(ASLFeatPlugin_node.outputs[0])
    graph.nodes.append(ASLFeatPlugin_node)
    if count % 2:
        for node in to_remove_nodes_list:
            node.outputs.clear()
        to_remove_nodes_list = []
    count += 1

#####################
# peak socre - "reflect" mode
#####################
mirror_pad_node_0 = [node for node in graph.nodes if node.name == 'MirrorPad' ][0]
#mirror_pad_node_0.attrs['pads']=gs.Constant('pad_0', values=np.asarray([3, 3, 3, 3]))
M_P_0=gs.Constant(name="pad_0", values=np.asarray([3, 3, 3, 3]))
mirror_pad_node_0.attrs['mode']='constant'
mirror_pad_node_0.inputs.pop()
mirror_pad_node_0.inputs.append(M_P_0)

mirror_pad_node_1 = [node for node in graph.nodes if node.name == 'MirrorPad_1' ][0]
pad_size=2
#mirror_pad_node_1.attrs['pads']=gs.Constant('pad_1', values=np.asarray([2, 2, 2, 2]))
M_P_1=gs.Constant(name="pad_1", values=np.asarray([2, 2, 2, 2]))
mirror_pad_node_1.attrs['mode']='constant'
mirror_pad_node_1.inputs.pop()
mirror_pad_node_1.inputs.append(M_P_1)

mirror_pad_node_2 = [node for node in graph.nodes if node.name == 'MirrorPad_2' ][0]
pad_size=1
#mirror_pad_node_2.attrs['pads']=gs.Constant('pad_2', values=np.asarray([1, 1, 1, 1]))
M_P_2=gs.Constant(name="pad_2", values=np.asarray([1, 1, 1, 1]))
mirror_pad_node_2.attrs['mode']='constant'
mirror_pad_node_2.inputs.pop()
mirror_pad_node_2.inputs.append(M_P_2)
```

**Comment by dedoogong** [comment]
You can see that 
```
M_P_0=gs.Constant(name="pad_0", values=np.asarray([3, 3, 3, 3]))
```
and Example 1 (constant mode): Insert 0 pads to the beginning of the second dimension.
pads = [0, 2, 0, 0] in the linked page. 
all shape(rank) is 4. why it should be 8? 
If it should be, which is the correct code to set the padding value( add padding only along H/W dims)
```
M_P_0=gs.Constant(name="pad_0", values=np.asarray([0, 0, 3, 3, 3, 3, 0, 0]))
```
or 
```
M_P_0=gs.Constant(name="pad_0", values=np.asarray([0, 0, 0, 0, 3, 3, 3, 3])) 
```

**Comment by KeDengMS** [comment]
Per Pad opset 11 [spec](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#inputs-2---3-9):

pads : tensor(int64)
Tensor of integers indicating the number of padding elements to add or remove (if negative) at the beginning and end of each axis. For 2D input tensor, it is the number of pixels. `pads` should be a 1D tensor of shape [2 * input_rank]. `pads` format should be: [x1_begin, x2_begin,...,x1_end, x2_end,...], where xi_begin is the number of pad values added at the beginning of axis `i` and xi_end, the number of pad values added at the end of axis `i`.

**Comment by dedoogong** [comment]
ok but unfortunately, the changed model produce the same error;;;
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNX Def ASLFeatPluginX rank0
ONNX Def ASLFeatPluginY rank0
ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX input_shape.dim_size() : 0
ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX rank0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/onnx-simplifier/onnxsim/__main__.py", line 90, in <module>
    main()
  File "/workspace/onnx-simplifier/onnxsim/__main__.py", line 78, in main
    custom_lib=args.custom_lib)
  File "/workspace/onnx-simplifier/onnxsim/onnx_simplifier.py", line 480, in simplify
    model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
  File "/workspace/onnx-simplifier/onnxsim/onnx_simplifier.py", line 381, in fixed_point
    x = func_b(x)
  File "/workspace/onnx-simplifier/onnxsim/onnx_simplifier.py", line 474, in constant_folding
    custom_lib=custom_lib)
  File "/workspace/onnx-simplifier/onnxsim/onnx_simplifier.py", line 229, in forward_for_node_outputs
    custom_lib=custom_lib)
  File "/workspace/onnx-simplifier/onnxsim/onnx_simplifier.py", line 195, in forward
    ), sess_options=sess_options, providers=['CPUExecutionProvider'])
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (ASLFeatPluginX0) Op (ASLFeatPluginX) [ShapeInferenceError] ONNXRUNTIME EXTERNAL ONNX Def ASLFeatPluginX Input rank must be >= 2.
)
you can check the model [aslfeatv2_op11_custom_const_padding_v3.zip](https://github.com/microsoft/onnxruntime/files/6269479/aslfeatv2_op11_custom_const_padding_v3.zip

**Comment by hariharans29** [comment]
You have added a contrib schema and updated the onnx def file to add a regular schema. I believe we can simplify things a lot. 

Can you start afresh in a new branch ? Looking at your model, you seem to have 2 custom ops - ASLFeatPluginX and ASLFeatPluginY which seem to be doing some special kind of padding. Is this correct ? Do you really need 2 custom ops or can you just use one and toggle the behavior using an attribute ?

To add a CUDA custom op implementation for ASLFeatPluginX , would this be a good example to follow - https://github.com/microsoft/onnxruntime/blob/4bc17ca04eccfb15fa2db0b0f1b4f5bd6d369a47/onnxruntime/test/shared_lib/test_inference.cc#L234 ?

**Comment by dedoogong** [comment]
Hello!
thanks for joining this issue,
1. Can you start afresh in a new branch ? OK I will
2.  Is this correct ? ah, it is just a simple custom op which cover below TF code.
Padding is not that special. just constant 1.
```
padding_list == [1,1,1,1]
padding = [[0, 0],
               [padding_list[0], padding_list[1]],  # top, bottom padding
               [padding_list[2], padding_list[3]],  # left, right padding
               [0, 0]]
inputs = tf.pad(inputs, padding)
in_h, in_w = [tf.shape(inputs)[i] for i in range(1, 3)] 
feat_h, feat_w = [in_h, in_w] 
x, y = tf.meshgrid(tf.range(feat_w), tf.range(feat_h))
x, y = [tf.reshape(i, [1, feat_h, feat_w, 1]) for i in [x, y]]  # shape [1, h, w, 1]
x, y = [tf.image.extract_patches(i,
                                 [1, kernel_size, kernel_size, 1],
                                 [1, strides, strides, 1],
                                 [1, dilation_rate, dilation_rate, 1],
                                 'VALID') for i in [x, y]]  # shape [1, out_h, out_w, filter_h * filter_w]

y, x = [tf.reshape(i, [batch_size, out_h, out_w, offset_num]) for i in [y, x]]
y, x = [tf.cast(i, tf.float32) for i in [y, x]]
```
So, the input of my custom op comes from Pad node and output is connected to Cast node. 
3. Do you really need 2 custom ops or can you just use one and toggle the behavior using an attribute ? hum, I'm not sure. maybe should use 2 separate ops. 
main cuda code is 
```
kernel_x(){
arr_out[idx ] = (w%3) + h - W*c; for X}
 and
kernel_y(){
arr_out[idx ] = (w/3) + h - W*c; for Y}
```

**Comment by dedoogong** [comment]
according to your recommendation, I added some codes but I can't see my test ops are not included in the build targets. 
[test_aslfeat.zip](https://github.com/microsoft/onnxruntime/files/6271812/test_aslfeat.zip)

Where can I add/set my custom files?(CMakeList.txt?)

**Comment by hariharans29** [comment]
There are ways you can continue debugging. In the custom op implementation's Compute() method, you can do a cudaStreamSync/cudaDeviceSync before doing a cudaMemcpy to host of the op's inputs and making sure the inputs look okay. If the input looks okay, launch your cuda kernel, do a stream sync/device sync again and do a cudaMemcpy to host of the op's output and inspecting its contents.

I would first create a single node onnx model containing your custom op alone and run it with different test cases (just like the tests here) and ensure your op's implementation is correct.


By the way, are using the same compute stream for launching your custom op as the stream used by inference session ? The test code shows how you can create a cuda stream, pass it to the session for use and you can use the same stream to launch your custom kernel - this should sync the execution between ORT's CUDA kernels and your custom kernel. Check here- https://github.com/microsoft/onnxruntime/blob/27e778909d75d0d7ff1177f3e86ef8c19db71d5d/onnxruntime/test/shared_lib/custom_op_utils.cc#L35

Hope this helps

**Comment by KeDengMS** [comment]
I tried your model of fixed Pad with symbolic shape inference, and it seems working after a minor fix #7285:
```
python -m onnxruntime.tools.symbolic_shape_infer --input /data/aslfeatv2_op11_custom_const_padding_v3.onnx --output /data/inf.onnx --guess_output_rank --int_max=8000 --auto_merge
```
For debugging, you may check if shape of your custom op output in the kernel matches the symbolic shape inference.

**Comment by dedoogong** [comment]
OK thank you, I will try but I want to try to convert the TF model to TF Lite and check the speed first. Then I will be back~!

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
