### ISSUE TITLE
Please, update the docs. Provider parameter "cuda_mem_limit" was renamed to "gpu_mem_limit" in nightly build.

### ISSUE THREAD

**Issue by II245** [microsoft/onnxruntime#7457]
**Describe the bug**
Hello! Try to restrict memory usage with cuda_mem_limit and use an example from here https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html
Seting up cuda_mem_limit doesn't work.
Please see output below
```
Traceback (most recent call last):
  File "ort_cuda_mem_limit.py", line 12, in <module>
    onnxruntime_session = onnxruntime.InferenceSession('conv_fp16.onnx',
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc:81 static onnxruntime::CUDAExecutionProviderInfo onnxruntime::CUDAExecutionProviderInfo::FromProviderOptions(const ProviderOptions&) [ONNXRuntimeError] : 1 : FAIL : provider_options_utils.h:148 Parse Unknown provider option: "cuda_mem_limit".
```
**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):
installed from here https://test-files.pythonhosted.org/packages/6e/86/3aab99be86d03cda88191b29389f26c86a65af55b0d8369791288f25084e/ort_gpu_nightly-1.7.0.dev202104231-cp38-cp38-manylinux2014_x86_64.whl
https://test-files.pythonhosted.org/packages/db/59/f8d60881a16fcb7e992d5a79bc3d247e100242af99adbe4c5144225a6221/ort_nightly-1.7.0.dev202104231-cp38-cp38-manylinux2014_x86_64.whl
- ONNX Runtime version: nightly-1.7.0.dev202104231 
- Python version: 3.8
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 11.1
- GPU model and memory: Tesla v100

**To Reproduce**
```python
import onnxruntime

providers = [
	('CUDAExecutionProvider', {
		'device_id': 0,
		'cuda_mem_limit': 2 * 1024 * 1024 * 1024,
	})
]

onnxruntime_session = onnxruntime.InferenceSession('conv_fp16.onnx', providers = providers)
```
Used onnx model is here [conv_fp16.zip](https://github.com/microsoft/onnxruntime/files/6380843/conv_fp16.zip)

**Expected behavior**
Proper cuda_mem_limit set up

**Screenshots**
-

**Additional context**
Used nightly build to examine these fixes https://github.com/microsoft/onnxruntime/issues/7212

**Comment by snnn** [comment]
The example in the doc is for C/C++.

You will need this: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_pybind_state.cc#L1105

set_gpu_mem_limit

**Comment by pranavsharma** [comment]
The set_ methods are now deprecated. See here: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_pybind_state.cc#L1071-L1077.

**Comment by II245** [comment]
Hello, found that "cuda_mem_limit" renamed to "gpu_mem_limit". Please, update the docs.
