### ISSUE TITLE
'Conv' operator doesn't support Double tensor type on runtime

### ISSUE THREAD

**Issue by bwmhamad** [microsoft/onnxruntime#7546]
**Describe the bug**
When using 'Conv' operator with Double Tensor type the following error occurs:

`
Traceback (most recent call last):
  File ".\onnx_fix_run.py", line 19, in <module>
    sess = rt.InferenceSession("onnx_check.onnx", so)
  File "C:\python\x64\python37\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "C:\python\x64\python37\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Conv(1)
`

**Urgency**
Moderate

**System information**
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
onnx: 1.9.0
onnxruntime: 1.7.0
onnxmltools: 1.7.0

**To Reproduce**
Please use the following example code to build model:

```python
import onnx, numpy as np, onnxmltools
from onnx import helper, TensorProto

type = TensorProto.DOUBLE #by setting to TensorProto.FLOAT it works fine

X = helper.make_tensor_value_info('X', type, [1, 1, 5, 5]) #input
W = helper.make_tensor_value_info('W', type, [1, 1, 3, 3]) #input

Y = helper.make_tensor_value_info('Y', type, [1, 1, 3, 3]) #output

node_def = helper.make_node('Conv', ['X', 'W'], ['Y'], auto_pad='SAME_LOWER', kernel_shape=[3, 3], strides=[2, 2],)

graph_def = helper.make_graph([node_def], 'onnx_check', [X, W], [Y],)

model_def = helper.make_model_gen_version(graph_def, producer_name='onnx_check')

## remove opset 13 and set it to 11 (latest for Conv as per docs)
model_def.opset_import.pop()
info = model_def.opset_import.add()
info.version = 11 #by setting this to 9, for example, we get 'Could not find an implementation for the node Conv(1)'

onnxmltools.utils.save_model(model_def, "onnx_check.onnx")

onnx.checker.check_model(model_def) #okay for both types
print('The model is checked!')
```

Please use the following example code to run model:

```python
import numpy as np, onnxruntime as rt

np_type = np.float64 #set to np.float32 when using tensor type FLOAT (works fine in that case)

x = np.array([[[[0., 1., 2., 3., 4.],
                [5., 6., 7., 8., 9.],
                [10., 11., 12., 13., 14.],
                [15., 16., 17., 18., 19.],
                [20., 21., 22., 23., 24.]]]]).astype(np_type)
w = np.array([[[[1., 1., 1.],
                [1., 1., 1.],
                [1., 1., 1.]]]]).astype(np_type)

inputs = { "X": x, "W": w }

## load and predict
so = rt.SessionOptions()
so.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_ALL #ORT_DISABLE_ALL gives same result
sess = rt.InferenceSession("onnx_check.onnx", so)

outputs = [ o.name for o in sess.get_outputs() ]
result = sess.run(outputs, inputs)
print(result)
```

**Expected behavior**
As described in [this ](https://github.com/onnx/onnx/blob/master/docs/Operators.md) document, ONNX should support _tensor(double)_ type for Conv

Can you please check this issue? If there's any fix, workaround, alternative or pointers to where I can add/implement this feature I will be happy to contribute

**Comment by bwmhamad** [comment]
For anyone wondering on how to workaround on this please follow below steps (might be similar to other operators):

1. Clone the repository
2. In file `onnxruntime/onnxruntime/core/providers/cpu/nn/conv.cc`
Register the existing Generic 'Conv' operator for _Double_ type
```C++
...
ONNX_CPU_OPERATOR_TYPED_KERNEL(
    Conv,
    11,
    double,
    KernelDefBuilder().TypeConstraint("T", DataTypeImpl::GetTensorType<double>()),
    Conv<double>);
```
3. In file `onnxruntime/onnxruntime/core/util/math_cpu.cc`
Register Im2col function for _Double_ type
```C++
...
template struct Im2col<float, StorageOrder::NCHW>;
template struct Im2col<uint8_t, StorageOrder::NCHW>;
template struct Im2col<double, StorageOrder::NCHW>; //added line
```
4. In file `onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc`
Add a class definition and kernel info for operator from step 2

```C++
...
class ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME(kCpuExecutionProvider, kOnnxDomain, 11, double, Conv);
...
BuildKernelCreateInfo<ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME(kCpuExecutionProvider, kOnnxDomain, 11, double, Conv)>,
```
5. Build the source code using following command: `.\build.bat --config Release --build_shared_lib --parallel --enable_pybind --skip_tests --build_wheel --update --build --cmake_generator "Visual Studio 16 2019"`
     . You have to specify `--cmake_generator "Visual Studio 16 2019"` option since it doesn't build with VS 2017 for whatever reason
     . Above command is for python build ONLY. For other builds please check [this ](https://www.onnxruntime.ai/docs/how-to/build.html) document 
6. You can now find the compiled _whl_ in the `onnxruntime/build/Windows/Release/Release/dist` directory. You can install this package in python using pip: `pip install onnxruntime-1.7.0-cp37-cp37m-win_amd64.whl --force-reinstall`

I've tried some simple tests on this and they came up okay but I'm not sure if this will cover all convolution cases.
If you think this solution is valuable to anyone kindly let me know so I can create a pull request.
Otherwise please feel free to close the issue.

**Comment by snnn** [comment]
It looks good to me.

**Comment by bwmhamad** [comment]
Dear @snnn,

Thank you for considering this change.
I've also added Double support for couple other operators required for my project and will add these to PR as well.
Also I might add Double support for operators from other issues with same context (if applicable.)
Will create a PR after merging changes and checking the guidelines.

**Comment by muyi6** [comment]
Dear @bwmhamad

First of all, thank you very much for your answer
Have you encountered the following problems，I got this error when i run a float64 resnet18 model and Is there any suggestion to solve this error？
`
onnxruntime.capi.onnxruntime_pybind11_stats.NotImplemented:[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for FusedConv(1) (node fused). Op with name (fused) and type (FusedConv) kernel is not supported in CPUExecutionProvider. Encountered following errors: (Found kernel for Op with name (fused) and type(FusedConv) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types(tensor(float),), but the node in the model has the following type (tensor(double))
`
