### ISSUE TITLE
Tests for creating NuGet package fail

### ISSUE THREAD

**Issue by Vrabor** [microsoft/onnxruntime#7552]
**Describe the bug**
Creation of NuGet package fails Tests when using openVino provider

**Urgency**
None, works fine without tests

**System information**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
* ONNX Runtime installed from (source or binary): source
* ONNX Runtime version: 1.7.0
* Visual Studio version (if applicable): 16.9.4
* GCC/Compiler version (if compiling from source): CMake 3.20.2

**To Reproduce:**
Run build with:
``` .\build.bat --config RelWithDebInfo --use_openvino GPU_FP32 --build_shared_lib --build_nuget --cmake_generator "Visual Studio 16 2019" ```

**Expected behavior**
The tests pass

**Additional context**
Building the package without tests with 
```.\build.bat --config RelWithDebInfo --use_openvino GPU_FP32 --build_shared_lib --build_nuget --cmake_generator "Visual Studio 16 2019" --skip_tests```
works fine, the resulting runtime works in my application as expected.

The Tests for the onnx-runtime itself seem to pass fine too:
(only the last few lines of output shown)
```
6: Test command: C:\SWDEV\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime_api_tests_without_env.exe "--gtest_output=xml:C:\SWDEV\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime_api_tests_without_env.exe.RelWithDebInfo.results.xml"
6: Test timeout computed to be: 3600
6: [==========] Running 1 test from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 1 test from TestSessionOptions
6: [ RUN      ] TestSessionOptions.SetIntraOpNumThreadsWithoutEnv
6: [       OK ] TestSessionOptions.SetIntraOpNumThreadsWithoutEnv (0 ms)
6: [----------] 1 test from TestSessionOptions (0 ms total)
6:
6: [----------] Global test environment tear-down
6: [==========] 1 test from 1 test suite ran. (0 ms total)
6: [  PASSED  ] 1 test.
6/6 Test #6: onnxruntime_api_tests_without_env ......   Passed    0.09 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1137.54 sec
```

But when creating the actual NuGet package, i get an error which translates to "The System couldn't fine the Path" (output is in German) followed by `C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj(76,5): error MSB3073: Der Befehl "C:\SWDEV\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\protoc.exe -I=..\..\..\cmake\external\onnx\onnx --csharp_out=. ..\..\..\cmake\external\onnx\onnx\onnx-ml.proto3" wurde mit dem Code 3 beendet.` what seems to be maybe a protobuf error?

Full Output of the NuGet part of the build process:
(let me know if you need more info)
```
100% tests passed, 0 tests failed out of 6

Total Test time (real) = 1137.54 sec
2021-05-03 12:08:20,310 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-05-03 12:08:20,311 util.run [INFO] - Running subprocess in 'C:\SWDEV\onnxruntime\csharp'
['dotnet', 'restore', 'OnnxRuntime.CSharp.sln', '--configfile', 'Nuget.CSharp.config']
  Wiederherzustellende Projekte werden ermittelt...
  "C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj" wiederhergestellt (in "660 ms").
  "C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj" wiederhergestellt (in "985 ms").
  2 von 4 Projekten sind für die Wiederherstellung auf dem neuesten Stand.
2021-05-03 12:08:26,183 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-05-03 12:08:26,183 util.run [INFO] - Running subprocess in 'C:\SWDEV\onnxruntime\csharp'
['dotnet', 'msbuild', 'OnnxRuntime.CSharp.sln', '/p:Configuration="RelWithDebInfo"', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="C:\\SWDEV\\onnxruntime\\build\\Windows"']
Microsoft (R)-Build-Engine, Version 16.9.0+57a23d249 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Microsoft.ML.OnnxRuntime -> C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\netstandard1.1\Microsoft.ML.OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime.InferenceSample -> C:\SWDEV\onnxruntime\csharp\sample\Microsoft.ML.OnnxRuntime.InferenceSample\bin\RelWithDebInfo\netcoreapp2.1\Microsoft.ML.OnnxRuntime.InferenceSample.dll
  Microsoft.ML.OnnxRuntime.PerfTool -> C:\SWDEV\onnxruntime\csharp\tools\Microsoft.ML.OnnxRuntime.PerfTool\bin\RelWithDebInfo\netcoreapp2.1\Microsoft.ML.OnnxRuntime.PerfTool.dll
  Microsoft.ML.OnnxRuntime.Tests -> C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\bin\RelWithDebInfo\netcoreapp2.1\Microsoft.ML.OnnxRuntime.Tests.dll
2021-05-03 12:08:52,152 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-05-03 12:08:52,153 util.run [INFO] - Running subprocess in 'C:\SWDEV\onnxruntime\csharp'
['dotnet', 'msbuild', 'OnnxRuntime.CSharp.proj', '/t:CreatePackage', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.OpenVino"', '/p:Configuration="RelWithDebInfo"', '/p:ExecutionProvider="openvino"', '/p:IsLinuxBuild="false"', '/p:OnnxRuntimeBuildDirectory="C:\\SWDEV\\onnxruntime\\build\\Windows"']
Microsoft (R)-Build-Engine, Version 16.9.0+57a23d249 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  add4e4225
  add4e4225ba69ba48a28889ff91e65bbc5f6f2ca
  PackageVersion=1.7.0-dev-20210503-1008-add4e4225
  Bundling managed assemblies into a NuGet package ...
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5048: Das Element "PackageIconUrl"/"iconUrl" ist veraltet. Erwägen Sie stattdessen, das Element "PackageIcon"/"Icon" zu verwenden. Weitere Informationen finden Sie unter https://aka.ms/deprecateIconUrl. [C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj]
  Das Paket "C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\RelWithDebInfo\Microsoft.ML.OnnxRuntime.Managed.1.7.0-dev-20210503-1008-add4e4225.nupkg" wurde erfolgreich erstellt.
  Generating nuspec for the native Nuget package ...
  Bundling native shared library artifacts into a NuGet package ...
  Es wird versucht, das Paket aus "NativeNuget.nuspec" zu erstellen.
  WARNUNG: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
  - Add lib or ref assemblies for the netcoreapp target framework
  - Add lib or ref assemblies for the netstandard target framework
  - Add lib or ref assemblies for the net target framework
  WARNUNG: NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
  Successfully created package 'C:\SWDEV\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\Microsoft.ML.OnnxRuntime.OpenVino.1.7.0-dev-20210503-1008-add4e4225.nupkg'.
2021-05-03 12:09:10,078 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-05-03 12:09:10,079 util.run [INFO] - Running subprocess in 'C:\SWDEV\onnxruntime\csharp'
['dotnet', 'test', 'test\\Microsoft.ML.OnnxRuntime.Tests\\Microsoft.ML.OnnxRuntime.Tests.csproj', '--filter', 'FullyQualifiedName!=Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels', '/p:IsLinuxBuild="false"', '/p:DefineConstants="USE_OPENVINO;"', '/p:OnnxRuntimeBuildDirectory="C:\\SWDEV\\onnxruntime\\build\\Windows"']
  Wiederherzustellende Projekte werden ermittelt...
  "C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\Microsoft.ML.OnnxRuntime.csproj" wiederhergestellt (in "423 ms").
  "C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj" wiederhergestellt (in "638 ms").
  Microsoft.ML.OnnxRuntime -> C:\SWDEV\onnxruntime\csharp\src\Microsoft.ML.OnnxRuntime\bin\Debug\netstandard1.1\Microsoft.ML.OnnxRuntime.dll
  Microsoft.ML.OnnxRuntime.Tests -> C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\bin\Debug\netcoreapp2.1\Microsoft.ML.OnnxRuntime.Tests.dll
  Das System kann den angegebenen Pfad nicht finden.
C:\SWDEV\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj(76,5): error MSB3073: Der Befehl "C:\SWDEV\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\protoc.exe -I=..\..\..\cmake\external\onnx\onnx --csharp_out=. ..\..\..\cmake\external\onnx\onnx\onnx-ml.proto3" wurde mit dem Code 3 beendet.
Traceback (most recent call last):
  File "C:\SWDEV\onnxruntime\\tools\ci_build\build.py", line 2119, in <module>
    sys.exit(main())
  File "C:\SWDEV\onnxruntime\\tools\ci_build\build.py", line 2097, in main
    run_csharp_tests(
  File "C:\SWDEV\onnxruntime\\tools\ci_build\build.py", line 1667, in run_csharp_tests
    run_subprocess(cmd_args, cwd=csharp_source_dir)
  File "C:\SWDEV\onnxruntime\\tools\ci_build\build.py", line 582, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\SWDEV\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Users\InCom\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dotnet', 'test', 'test\\Microsoft.ML.OnnxRuntime.Tests\\Microsoft.ML.OnnxRuntime.Tests.csproj', '--filter', 'FullyQualifiedName!=Microsoft.ML.OnnxRuntime.Tests.InferenceTest.TestPreTrainedModels', '/p:IsLinuxBuild="false"', '/p:DefineConstants="USE_OPENVINO;"', '/p:OnnxRuntimeBuildDirectory="C:\\SWDEV\\onnxruntime\\build\\Windows"']' returned non-zero exit status 1.
```

**Comment by Vrabor** [comment]
It seems like I was only partly right about the runtime working with the current build, adding `SessionOptions.AppendExecutionProvider_OpenVINO()` to my application crashes the runtime.
That would suggest to me that only the default ExecutionProvider is working and the OpenVINO one is broken

**Comment by ytaous** [comment]
@sfatimar , @smkarlap
Looks quite similar to https://github.com/microsoft/onnxruntime/issues/5749

**Comment by Vrabor** [comment]
So i checked and building without OpenVINO gets me the same error so it's most likely a problem with my buildchain / dependencies
