### ISSUE TITLE
CUDAExecutionProvider Not Available / GPU Not Visible on NVIDIA T4

### ISSUE THREAD

**Issue by anshoomehra** [microsoft/onnxruntime#7748]
**Describe the bug**
Do not see CUDAExecutionProvider or GPU available from ONNX Runtime even though onnxruntime-gpu is installed.

**Urgency**
In critical stage of project & hence urgent.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux lab-am-vm 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

- ONNX Runtime installed from (source or binary): PIP Install

- ONNX Runtime version: 
onnx==1.9.0
onnxruntime==1.7.0
onnxruntime-gpu==1.7.0

- Python version: 3.7.10

- CUDA/cuDNN version:  release 11.0, V11.0.194
- GPU model and memory: NVIDIA T4, 16G

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
import onnxruntime as ort

ort.get_device()
>>> 'CPU'

ort.get_available_providers()
>>> ['CPUExecutionProvider']
```

**Expected behavior**
Expecting device as GPU and provider as CUDAExecutionProvider

**Comment by hariharans29** [comment]
Did you install both onnxruntime and onnxruntime_gpu on your machine ? If so, can you try after uninstalling onnxruntime with pip uninstall onnxruntime ?

**Comment by anshoomehra** [comment]
@hariharans29 yes, I did uninstall and reinstall everything clean still the same issue. Sequence of install onnx, onnxruntime, onnxruntime-gpu…

onnx==1.9.0
onnxruntime==1.7.0
onnxruntime-gpu==1.7.0

**Comment by hariharans29** [comment]
You don't need onnx/onnxruntime installed if you plan to use onnxruntime_gpu.

Can you uninstall everything and just install onnxruntime_gpu ?

**Comment by hariharans29** [comment]
If there is an import failure with just onnxruntime_gpu installed, tleast it is on the right track. I suspect you are missing some dependencies listed here - https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements. Make sure these are installed before trying the import again.

**Comment by anshoomehra** [comment]
> If there is an import failure with just onnxruntime_gpu installed, atleast it is on the right track. I suspect you are missing some dependencies listed here - https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements. Make sure these are installed before trying the import again.

Yes the import fails with just onnxruntime_gpu, let me check on dependencies & revert back if that solves the issue ..

appreciate your time & prompt responses - thanks

**Comment by anshoomehra** [comment]
@hariharans29  I tried uninstalling onnxruntime and imports start to fail .. Should the import paths remain the same post uninstall??

```
from onnxruntime import (
    ExecutionMode,
    GraphOptimizationLevel,
    InferenceSession,
    SessionOptions,
)
```

Also, I tried looking for dependencies, these does not look like Python Libs, can you please guide on how can I verify the existence and versions of these?

![image](https://user-images.githubusercontent.com/24396120/118851332-a0adfd00-b89f-11eb-9fab-ad9602d1997a.png)

**Comment by anshoomehra** [comment]
@hariharans29 It worked!! I guess the issue was below :

I was installing onnx, onnxruntime and onnxruntime-gpu in this sequence and later uninstalled onnxruntime only which created import issues. Instead, I uninstalled onnx as well this time and just installed onnxruntime-gpu from sctrach and that made it work, **so for some reason onnx was conflicting the libs it seems ...**

Thank you so much for helping me get to this stage :-)

I see one issue though with this new method, one of the imports for quantize libs still fail, listed below - any suggestions on how to resolve this ?

![image](https://user-images.githubusercontent.com/24396120/118864226-c6420300-b8ad-11eb-9ab7-57140179b467.png)

**Comment by hariharans29** [comment]
@yufenglee - would you know about these quantization libs ?

@anshoomehra - The libraries listed above are CUDA RT, CuDNN libs. There is documentation on the web that shoul help you check for these. They are dependencies for our GPU builds.

**Comment by anshoomehra** [comment]
@hariharans29 I running into one another issue, not sure if you would suggest open new issue for this? 

I am able to export the model successfully with 'CUDAExecutionProvider', however running inference on GPU seems not to load all variables to GPU resulting in the below error, any other steps I may need apart from switching devices to GPU for model and tokenizer to make it fully run on GPU?

![image](https://user-images.githubusercontent.com/24396120/118872108-35bbf080-b8b6-11eb-9be7-6b64e8d7f50e.png)

![image](https://user-images.githubusercontent.com/24396120/118872167-44a2a300-b8b6-11eb-8c0b-edd4a5ef3069.png)

**Comment by hariharans29** [comment]
Please open a new issue with more details and a complete repro script

**Comment by anshoomehra** [comment]
@hariharans29 logged new [issue](https://github.com/microsoft/onnxruntime/issues/7796) as per your suggestion.

We can close this post @yufenglee resolves the quantization libraries import issue with onnxruntime-gpu.

Thanks again for all your help.

**Comment by FrancescoSaverioZuppichini** [comment]
I have the same issue, using nvidia container `nvcr.io/nvidia/pytorch:22.08-py3`

**Comment by Ahmet0691** [comment]
`from optimum.onnxruntime import ORTModelForQuestionAnswering`
`from transformers import pipeline, AutoTokenizer`
`import time`
`import torch`
`onnx_path = "C:\\Users\\Users\\PycharmProjects\\pythonProject10\\onnx"`
`model = ORTModelForQuestionAnswering.from_pretrained(onnx_path,file_name="model_quantized.onnx", device =0)`
`tokenizer = AutoTokenizer.from_pretrained(onnx_path)`
`nlp = pipeline("question-answering",model=model, tokenizer=tokenizer, device=0)`
`question = input (str("any questions : "))`
`with open('text.txt', 'r', encoding='utf8') as file:`
    `context = file.read()`
`start_time = time.time()`
`result = nlp(question= question, context=context)`
`end_time = time.time()`
`print(result)`
`print("Latency:", end_time - start_time)`


<sub>
**Error Massage** 
Traceback (most recent call last):
  File "C:\Users\Users\PycharmProjects\pythonProject10\quentiz.py", line 8, in <module>
    nlp = pipeline("question-answering",model=model, tokenizer=tokenizer, device=0)
  File "C:\Users\Users\.virtualenvs\pythonProject10\lib\site-packages\transformers\pipelines\__init__.py", line 903, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "C:\Users\Users\.virtualenvs\pythonProject10\lib\site-packages\transformers\pipelines\question_answering.py", line 269, in __init__
    **kwargs,
  File "C:\Users\Users\.virtualenvs\pythonProject10\lib\site-packages\transformers\pipelines\base.py", line 780, in __init__
    self.model = self.model.to(self.device)
  File "C:\Users\Users\.virtualenvs\pythonProject10\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 269, in to
    validate_provider_availability(provider)  # raise error if the provider is not available
  File "C:\Users\Users\.virtualenvs\pythonProject10\lib\site-packages\optimum\onnxruntime\utils.py", line 197, in validate_provider_availability
    f"Asked to use {provider}, but `onnxruntime-gpu` package was not found. Make sure to install `onnxruntime-gpu` package instead of `onnxruntime`."
ImportError: Asked to use CUDAExecutionProvider, but `onnxruntime-gpu` package was not found. Make sure to install `onnxruntime-gpu` package instead of `onnxruntime`.

Process finished with exit code 1
</sub>



**I uninstalled OnnxRuntime and removed OnnxRuntime-GPU, then reinstalled, tried these steps multiple times but could not find a solution. Please Help..**

**Comment by thawro** [comment]
In my case the following helped:
1. uninstall `onnxruntime`
2. uninstall `onnxruntime-gpu`
3. install `optimum[onnxruntime-gpu]`

more [here](https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/gpu#installation)

**Comment by takahashi-shotaro** [comment]
it works for me
1. `pip uninstall onnxruntime onnxruntime-gpu`
2. `pip install onnxruntime-gpu`

**Comment by merveenoyan** [comment]
I'm having the same error, and I have never installed `onnxruntime` and `onnx` but only `onnxruntime-gpu`. I also checked the `onnxruntime-gpu` to CUDA compatibility. This is on latest version of Colab.

```python
import onnxruntime

providers = onnxruntime.get_available_providers()
print(providers)

#  ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
```
and I didn't even notice that the session wasn't utilizing the GPU until benchmarking against CPU, so I did: 

```python
X_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(input_data, 'cuda', 0)
```
and started getting: 
```
RuntimeError: /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1554 onnxruntime::ProviderInfo_CUDA& onnxruntime::GetProviderInfo_CUDA() CUDA Provider not available, can't get interface for it
```

**Comment by JHW5981** [comment]
> it works for me
> 
> 1. `pip uninstall onnxruntime onnxruntime-gpu`
> 2. `pip install onnxruntime-gpu`

This works with error: "ValueError: Asked to use CUDAExecutionProvider as an ONNX Runtime execution provider, but the available execution providers are ['AzureExecutionProvider', 'CPUExecutionProvider']."

**Comment by Asachanel** [comment]
I had the same issue, I uninstalled onnx, onnxruntime as well as onnxruntime-gpu, and cleaned up the uninstall remnants inside site-packages, only onnxruntime-gpu was installed, and finally it worked

**Comment by ooaykac** [comment]
The issue might be based on installing order. After installing  onnxruntime-gpu, some library which has  onnxruntime dependicies might be install over  onnxruntime-gpu .  Check your requirements.txt and Dockerfile (if exitst) 

First Uninstall onnxruntime-gpu and onnxruntime in dockerfile.
Secondly install  requirements.txt 
Thirdly install only onnxruntime-gpu in Dockerfile.

I hope it can solve.

**Comment by Fmstrat** [comment]
> The issue might be based on installing order. 

This, but not in the order described. The problem for me was my `requirements.txt` had entries that had requirements of onnxruntime all their own, so the uninstall had to happen after:

```
RUN . /opt/venv/bin/activate && pip install -r requirements.txt
RUN . /opt/venv/bin/activate && pip uninstall -y onnxruntime
RUN . /opt/venv/bin/activate && pip install onnxruntime-gpu
```

For my project (InsightFace used), I needed to leave `onnx` installed.
