### ISSUE TITLE
Runtime Reporting BatchNorm not implemented.

### ISSUE THREAD

**Issue by ghostplant** [Microsoft/onnxruntime#775]
```sh
~/onnx_test/models$ sudo pip3 install onnxruntime
~/onnx_test/models$ onnxruntime_test inception_v2.onnx
Traceback (most recent call last):
  File "/usr/local/bin/onnxruntime_test", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/tools/onnxruntime_test.py", line 56, in main
    sess = onnxrt.InferenceSession(args.model_path, sess_options)
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(1)
```

Is this a BUG or not supporting BatchNormalization at the moment?

**Comment by snnn** [comment]
Your model is too old. 
You can get a new one in https://onnxruntimetestdata.blob.core.windows.net/models/20190327.zip
