### ISSUE TITLE
"Quantize_qat" for PyTorch QAT model

### ISSUE THREAD

**Issue by Kentaro-Mikami** [microsoft/onnxruntime#7764]
**Is your feature request related to a problem? Please describe.**
We tried to use "Quantize_qat" function for PyTorch QAT model.
We followed [PyTorch QAT tutrial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html), we could create QAT model. (Attached model) 
Then we tried to use "Quantize_qat" API for this model, but the error occured.
Would you give us your advise about this error?
-----------------------------------------------
 Traceback (most recent call last):
 File "C:/Users/UserName/PycharmProjects/pytorch_qat/turorial.py", line 450, in <module>
 quantized_model = quantize_qat(model_fp32, model_quant, weight_type=QuantType.QUInt8)
 File "C:\Users\UserName\AppData\Local\Programs\Python\Python37\lib\site-packages\onnxruntime\quantization\quantize.py"　　　, line 339, in quantize_qat
 quantizer.quantize_model()
 File "C:\Users\UserName\AppData\Local\Programs\Python\Python37\lib\site-packages\onnxruntime\quantization\onnx_quantiz　　　er.py", line 188, in quantize_model
 self.remove_fake_quantized_nodes()
 File "C:\Users\UserName\AppData\Local\Programs\Python\Python37\lib\site-packages\onnxruntime\quantization\onnx_quantiz　　　er.py", line 129, in remove_fake_quantized_nodes
 curr_node.name))
 ValueError: Remove fake-quantized node pair Error: Parent node is not found for QuantizeLinear_2.
-----------------------------------------------

**System information**
- ONNX Runtime version (you are using):V1.7.0

[mobilenet_quantization_scripted.zip](https://github.com/microsoft/onnxruntime/files/6512314/mobilenet_quantization_scripted.zip)

**Comment by Hrayo712** [comment]
I am running into a similar issue using torch 1.9.0 and ORT 1.8. Any hint/update into what might be the issue ?

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
