### ISSUE TITLE
ACL and ArmNN v21.02 EP has problem with GEMM

### ISSUE THREAD

**Issue by psk9211** [microsoft/onnxruntime#7784]
**Describe the bug**

When running onnxruntime inference with ArmNN and ACL v21.02 as EP, I got this error:
```bash
2021-05-21 10:21:41.671535343 [E:onnxruntime:, parallel_executor.cc:213 RunNodeAsync] Non-zero status code returned while running Gemm node. Name:'Gemm_174' Status Message: /home/pi/download/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: classifier.1.weight

2021-05-21 10:21:41.671666231 [E:onnxruntime:, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_174' Status Message: /home/pi/download/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: classifier.1.weight

Segmentation fault
```

I converted pre-trained mobilenet_v2 model into onnx format, and here is the GEMM node of ONNX model:
![image](https://user-images.githubusercontent.com/15812796/119080718-8dcd3100-ba35-11eb-9d57-f666f779ca4e.png)

And I use this code to convert models on x86 Machine:
```python
x = torch.randn(1, 3, 224, 224, requires_grad=True)

torch.onnx.export(torchvision.models.mobilenet_v2(pretrained=True),               # model being run
                x,                         # model input (or a tuple for multiple inputs)
                '/pth/to/mobilenet_v2.onnx',  
                export_params=True, 
                opset_version=12,  
                do_constant_folding=True, 
                input_names = ['input'],
                output_names = ['output'], 
                dynamic_axes={'input' : {0 : 'batch_size'}, 'output' : {0 : 'batch_size'}},
                verbose=True,
                operator_export_type=torch.onnx.OperatorExportTypes.ONNX)
```

Every other model that has Gemm nodes (FC layers) occurs the same error.

**Urgency**
None

**System information**
- RPI 4
    - OS Platform and Distribution : Raspberry Pi 4 [(64-bit OS)](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-04-09/), Cortex-A72, ARMv8-a
    - ONNX Runtime installed from (source or binary): from source
    - ONNX Runtime version: v1.8.0 (May 19th master branch)
    - Python version: 3.7.3
    - GCC/Compiler version (if compiling from source): v8.3.0
    - CUDA/cuDNN version: None
    - GPU model and memory: 4GB

- x86 machine
    - OS: Ubuntu 18.04.1 64-bit on Docker
    - ONNX Runtime installed from (source or binary): binary
    - ONNX Runtime version: v1.7.0
    - Python version: 3.8.3 conda env
    - CUDA/cuDNN version: CUDA v11
    - GPU model and memory: RTX Titan
    - Pytorch version : v1.8.1+cu102
    - Torchvision version : 0.9.1+cu102

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

1. Cross-compile ArmNN v21.02 on x86 machine
    - using this [DOC](https://arm-software.github.io/armnn/21.02/md__build_guide_cross_compilation.xhtml)
    - with aarch64-linux-gnu-gcc /  aarch64-linux-gnu-g++
    - with Tensorflow v2.3.1 and ONNX 1.6.0
    - with this CMake options:
```bash
CXX=aarch64-linux-gnu-g++ CC=aarch64-linux-gnu-gcc cmake .. \
        -DCMAKE_C_COMPILER_FLAGS=-fPIC \
        -DARMCOMPUTE_ROOT=$HOME/armnn-devenv/ComputeLibrary \
        -DARMCOMPUTE_BUILD_DIR=$HOME/armnn-devenv/ComputeLibrary/build/ \
        -DBOOST_ROOT=$HOME/armnn-devenv/boost_arm64_install/ \
        -DARMCOMPUTENEON=1 -DARMNNREF=1 \
        -DONNX_GENERATED_SOURCES=$HOME/armnn-devenv/onnx \
        -DBUILD_ONNX_PARSER=1 \
        -DTF_GENERATED_SOURCES=$HOME/armnn-devenv/tensorflow-protobuf \
        -DBUILD_TF_PARSER=1 \
        -DBUILD_TF_LITE_PARSER=1 \
        -DTF_LITE_GENERATED_PATH=$HOME/armnn-devenv/tflite \
        -DFLATBUFFERS_ROOT=$HOME/armnn-devenv/flatbuffers-arm64 \
        -DFLATC_DIR=$HOME/armnn-devenv/flatbuffers-1.12.0/build \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install \
        -DPROTOBUF_ROOT=$HOME/armnn-devenv/google/x86_64_pb_install/ \
        -DPROTOBUF_LIBRARY_DEBUG=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DPROTOBUF_LIBRARY_RELEASE=$HOME/armnn-devenv/google/arm64_pb_install/lib/libprotobuf.so.23.0.0 \
        -DBUILD_ARMNN_QUANTIZER=1 \
        -DBUILD_ARMNN_SERIALIZER=1 \
        -DSAMPLE_DYNAMIC_BACKEND=1 \
        -DDYNAMIC_BACKEND_PATHS=$HOME/armnn-devenv/armnn/src/dynamic/sample/build
```

- Copy the libs to RPI 4

 2. Build ONNX Runtime on RPI 4
    - Get ONNX Runtime v1.8.0
 ```bash
$ git rev-parse master
75dbc2a35eae0c8caf67c14584f2cd9237b2b1ad
```

- Edit files

```bash
--- a/onnxruntime/core/providers/acl/nn/conv.cc
+++ b/onnxruntime/core/providers/acl/nn/conv.cc
@@ -219,1 +219,1 @@ bool optimizable = bool(arm_compute::NEDepthwiseConvolutionLayer::validate(tconv.in->info(),

--- a/onnxruntime/core/providers/acl/nn/pool.cc
+++ b/onnxruntime/core/providers/acl/nn/pool.cc
@@ -64,1 +64,1 @@ layer->configure(tpool.in.get(), tpool.out.get(), arm_compute::PoolingLayerInfo(pool_type, arm_compute::DataLayout::UNKNOWN));
@@ -107,1 +107,1 @@ arm_compute::PoolingLayerInfo pool_info(pool_type, aclSize, arm_compute::DataLayout::UNKNOWN, aclPadStride, excludePadding, false);

--- a/onnxruntime/core/providers/acl/tensor/concat.cc
+++ b/onnxruntime/core/providers/acl/tensor/concat.cc
@@ -67,1 +67,1 @@ std::vector<const arm_compute::ITensor*> inputs_vector;
@@ -86,1 +86,2 @@
arm_compute::ITensor* temp = const_cast<arm_compute::ITensor*>(inputs_vector[i]);
arm_compute::Tensor* in = static_cast<arm_compute::Tensor*>(temp);
```

- Build

```bash
./build.sh --use_acl ACL_2002 --acl_home /home/pi/download/ComputeLibrary --acl_libs /home/pi/download/ComputeLibrary/build \
        --use_armnn --armnn_bn --armnn_relu --armnn_home /home/pi/armnn --armnn_libs /home/pi/armnn/build \
        --use_openmp \
        --config MinSizeRel --parallel \
        --update --build
```
```bash
./build.sh --use_acl ACL_2002 --acl_home /home/pi/download/ComputeLibrary --acl_libs /home/pi/download/ComputeLibrary/build \
        --use_armnn --armnn_bn --armnn_relu --armnn_home /home/pi/armnn --armnn_libs /home/pi/armnn/build \
        --use_openmp \
        --config MinSizeRel --parallel \
        --build_shared_lib --enable_pybind --build_wheel \
        --skip_tests
```

- Verify

```python
import onnxruntime as ort

print("onnxruntime: " + ort.__version__)
sess = ort.InferenceSession("/home/pi/mobilenet_v2.onnx")
print(sess.get_providers())
```
```bash
onnxruntime: 1.8.0
['ArmNNExecutionProvider', 'ACLExecutionProvider', 'CPUExecutionProvider']
```

 3. Run test code on RPI 4
 ```python
import onnxruntime as rt
import numpy as np

sess_options = rt.SessionOptions()
sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_ALL
sess_options.intra_op_num_threads=4
sess_options.execution_mode = rt.ExecutionMode.ORT_PARALLEL

EP_list = ['ArmNNExecutionProvider', 'ACLExecutionProvider', 'CPUExecutionProvider']

fp32_sess = rt.InferenceSession('/home/pi/projects/models/mobilenet_v2.onnx', sess_options, providers=EP_list)

x = np.random.random((1, 3, 224, 224)).astype(np.float32)
#fp32_sess.set_providers(['CPUExecutionProvider']) <- if I set to CPUEP, it works fine
#fp32_sess.set_providers([ 'ACLExecutionProvider']) <- Using ACL or ArmNN EP only also got errors
fp32_sess.run(None, {fp32_sess.get_inputs()[0].name: x})
```

**Additional context**
Are there any plans to support the latest version of Arm NN and ACL? v21.05 just released.

**Comment by psk9211** [comment]
Here's another bug.

 Re-building onnxrutime v1.8.0 (May 19th master branch) with ArmNN & ACL v20.02, which is officially supported version, still get these errors when using **ArmNNExecutionProvider** and **ACLExecutionProvider**. (On RPI 4)

```bash
2021-05-23 02:27:24.233628719 [E:onnxruntime:, parallel_executor.cc:213 RunNodeAsync] Non-zero status code returned while running Gemm node. Name:'Gemm_174' Status Message: /home/pi/download/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: classifier.1.weight

2021-05-23 02:27:24.233751829 [E:onnxruntime:, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_174' Status Message: /home/pi/download/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: classifier.1.weight

Traceback (most recent call last):
  File "ep_test.py", line 19, in <module>
    sess.run(None, {sess.get_inputs()[0].name: x})
  File "/home/pi/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Gemm node. Name:'Gemm_174' Status Message: /home/pi/download/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:36 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: classifier.1.weight

Bus error
```

And I got this error when using **CPUExecutionProvider**:
```bash
Bus error
```

I followed this [documentation](https://arm-software.github.io/armnn/20.02/index.xhtml#S3_2_cross_compilations_build_guide) with this Cmake options:
```bash
CXX=aarch64-linux-gnu-g++ \
CC=aarch64-linux-gnu-gcc \
cmake .. \
-DARMCOMPUTE_ROOT=$WORKDIR/ComputeLibrary \
-DARMCOMPUTE_BUILD_DIR=$WORKDIR/ComputeLibrary/build/ \
-DBOOST_ROOT=$BOOSTDIR \
-DARMCOMPUTENEON=1 -DARMNNREF=1 \
-DPROTOBUF_ROOT=$WORKDIR/google/x86_64_pb_install/ \
-DPROTOBUF_LIBRARY_DEBUG=$WORKDIR/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
-DPROTOBUF_LIBRARY_RELEASE=$WORKDIR/google/arm64_pb_install/lib/libprotobuf.so.15.0.1 \
-DONNX_GENERATED_SOURCES=$WORKDIR/onnx \
-DBUILD_ONNX_PARSER=1
```

Other settings, build options, and test code are the same as before.
The model is also the same one. (mobilenet v2)

**Comment by DesmondLei** [comment]
I encountered the same problem when building onnxruntime with ArmNN v21.05 as the EP on a Raspberry Pi 4 (64-bit OS). ArmNNExecutionProvider cannot be used to run models with GEMM nodes.

Besides, even if the model does not contain a GEMM node, there is always a segmentation fault at the end of the inference program. For example:
```
import onnxruntime as ort
import numpy as np
import torch
from torch import nn


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 1, kernel_size=3, stride=1, padding=1)

    def forward(self, X):
        X = self.conv1(X)
        X = nn.functional.relu(X)
        return X


model_path = "test_model.onnx"
model = TestModel()
model.eval()
dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(
    model,
    dummy_input,
    model_path,
    input_names=["input1"],
    output_names=["output1"],
)
ort_session = ort.InferenceSession(model_path)
# ort_session.set_providers(['CPUExecutionProvider'])
output = ort_session.run(None, {ort_session.get_inputs()[0].name: dummy_input.numpy()})
print("over")
```
The result is:
```
over
Segmentation fault
```
If I uncomment the line `# ort_session.set_providers(['CPUExecutionProvider'])`, the program will run normally.

Here is how I build onnxruntime:
`./build.sh --config Release --build_shared_lib --parallel --build_wheel --use_openmp --update --build --skip_tests --use_armnn --armnn_relu --armnn_bn --armnn_home /home/pi/Projects/armnn-pi/armnn/ --armnn_libs /home/pi/Projects/armnn-pi/armnn/build --acl_home /home/pi/Projects/armnn-pi/ComputeLibrary/ --acl_libs /home/pi/Projects/armnn-pi/ComputeLibrary/build`

**Comment by qinhj** [comment]
https://github.com/microsoft/onnxruntime/issues/7255#issuecomment-1692636342
