### ISSUE TITLE
Getting "onnxruntime::CudaCall CUDA failure 3: initialization error " when using ML.NET with CUDA

### ISSUE THREAD

**Issue by Magic73** [microsoft/onnxruntime#7828]
**Describe the bug**
The app is written in C# and uses .NET Core 3.1.
I'm using ML.NET by consuming these NuGet packages:

- Microsoft.ML 1.5.5
- Microsoft.ML.ImageAnalytics 1.5.5
- Microsoft.ML.OnnxRuntime.Gpu 1.7.1
- Microsoft.ML.OnnxTransformer 1.5.5

I get the next exception:
System.InvalidOperationException: 'Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] D:\3\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\3\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 3: initialization error ; GPU=128 ; hostname=LAB-1 ; expr=cudaSetDevice(info_.device_id); 

   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)'

I get this exception when I create this scoring pipeline:

```
var pipeline = _mlContext.Transforms.ResizeImages(inputColumnName: "bitmap", outputColumnName: "input_1:0", imageWidth: 416, imageHeight: 416, resizing: ResizingKind.IsoPad)
	.Append(_mlContext.Transforms.ExtractPixels(outputColumnName: "input_1:0", scaleImage: 1f / 255f, interleavePixelColors: true))
	.Append(_mlContext.Transforms.ApplyOnnxModel(
		fallbackToCpu: false,
		gpuDeviceId: gpuDeviceId,
		shapeDictionary: new Dictionary<string, int[]>()
		{
			{ "input_1:0", new[] { 1, 416, 416, 3 } },
			{ "Identity:0", new[] { 1, 52, 52, 3, 85 } },
			{ "Identity_1:0", new[] { 1, 26, 26, 3, 85 } },
			{ "Identity_2:0", new[] { 1, 13, 13, 3, 85 } },
		},
		inputColumnNames: new[]
		{
			"input_1:0"
		},
		outputColumnNames: new[]
		{
			"Identity:0",
			"Identity_1:0",
			"Identity_2:0"
		},
		modelFile: @"data\models\yolov4.onnx")
	);

```
Without using the GPU, all it works perfectly as expected (setting to true the fallbackToCpu boolean).

**System information**

OS Platform: Windows 10 Pro x64
Visual Studio version (if applicable): 2019
CUDA/cuDNN version: CUDA 11.3.0_465.89 / cuDNN: 8.2.0.53
GPU model and memory: NVidia GeForce GTX 980M

**Expected behavior**
Expected to run perfectly as the CPU-only version does. The error doesn't say too much (at least for me), to understand why the initialization fails.

**Comment by Magic73** [comment]
Nevermind, my fault. I hadn't updated the NVidia drivers :( Once updated, it works!
