### ISSUE TITLE
[python] [ORTTrainer] Can't use ORTTrainer

### ISSUE THREAD

**Issue by juharris** [microsoft/onnxruntime#8096]
**Describe the bug**
Can't initialize `ORTTrainer` with a simple model.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary (`pip install torch onnxruntime-training`)
- ONNX Runtime version: 1.8.0
- Python version: 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2, libcudnn7 (7.6.5.32-1+cuda10.2)
- Docker image: pytorch/pytorch:1.8.1-cuda10.2-cudnn7-devel
- GPU model and memory:
- `pip freeze | grep -iE 'torch|onnx'`:
```
onnx==1.9.0
onnxruntime-training==1.8.0
torch==1.9.0
```

**To Reproduce**
```bash
conda create --name python-3.8-ORT python=3.8
conda activate python-3.8-ORT
pip install torch onnxruntime-training
```

```Python
import os

import torch
import torch.nn as nn
from onnxruntime.training import ORTTrainer, ORTTrainerOptions, optim

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(10, 5, bias=False)
        self.a1 = nn.Sigmoid()
        self.l2 = nn.Linear(self.l1.out_features, 2, bias=False)

    def forward(self, x):
        result = self.l1(x)
        result = self.a1(result)
        result = self.l2(result)
        return result


os.makedirs('models', exist_ok=True)


def main():
    model = Net()

    loss_fn = nn.CrossEntropyLoss()

    model_description = {
        'inputs': [
            ('x', ['batch_size', 10]),
            ('label', ['batch_size'])
            ],
        'outputs': [
            ('loss', [], True),
            ('result', ['batch_size', 2])]}

    optimizer_config = optim.AdamConfig(lr=0.001)

    trainer = ORTTrainer(model, model_description, optimizer_config, loss_fn)

    trainer.train_step(torch.rand(1, 10), torch.tensor([1]))


if __name__ == "__main__":
    main()

```

Says:
```
Traceback (most recent call last):
  File "example.py", line 72, in <module>
    main()
  File "example.py", line 63, in main
    trainer.train_step(torch.rand(1, 10), torch.tensor([1]))
  File "/home/juharri/.conda/envs/python-3.8-ORT/lib/python3.8/site-packages/onnxruntime/training/orttrainer.py", line 348, in train_step
    self._init_onnx_model(sample_input)
  File "/home/juharri/.conda/envs/python-3.8-ORT/lib/python3.8/site-packages/onnxruntime/training/orttrainer.py", line 740, in _init_onnx_model
    self._init_session(optimizer_state_dict,
  File "/home/juharri/.conda/envs/python-3.8-ORT/lib/python3.8/site-packages/onnxruntime/training/orttrainer.py", line 755, in _init_session
    self._create_ort_training_session(optimizer_state_dict,
  File "/home/juharri/.conda/envs/python-3.8-ORT/lib/python3.8/site-packages/onnxruntime/training/orttrainer.py", line 708, in _create_ort_training_session
    self._training_session = ort.TrainingSession(self._onnx_model.SerializeToString(), ort_parameters,
  File "/home/juharri/.conda/envs/python-3.8-ORT/lib/python3.8/site-packages/onnxruntime/capi/training/training_session.py", line 29, in __init__
    config_result = self._sess.read_bytes(path_or_bytes, parameters, providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node MatMul_4_Grad/Gemm_0_transformed:Gemm(11)
```

**Expected behavior**
There should be no errors.

**Additional context**
I'm trying to produce a training graph so that I can compute gradients with an ONNX model in JavaScript.
This is just a simple example but I would like to pass some debug options with `ORTTrainerOptions`.

**Comment by thiagocrepaldi** [comment]
Did you try using CUDA as opposed to CPU?

**Comment by thiagocrepaldi** [comment]
Try something like:
```
    opts = orttrainer.ORTTrainerOptions({
        'debug' : {
            'deterministic_compute': True
        },
        'device' : {
            'id' : 'cuda',
            'mem_limit' : 10*1024*1024
        }
    })

trainer = ORTTrainer(model, model_description, optimizer_config, loss_fn, options=opts)


```

**Comment by juharris** [comment]
Thanks for the suggestion but I got the same error.

**Comment by baijumeswani** [comment]
@juharris closing this since ORTTrainer is now deprecated. Let me know if there is anything I can help with.
