### ISSUE TITLE
[python] [build] FileNotFoundError: Unable to find 'test_execution_provider.dll'

### ISSUE THREAD

**Issue by juharris** [microsoft/onnxruntime#8140]
**Describe the bug**
I can't build for Python on Windows because the tests fail.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:
- Python version: 3.8
- Visual Studio version (if applicable): VS 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
```
.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --enable_training --enable_pybind 
```
...
```
======================================================================
ERROR: testRegisterCustomEPsLibrary (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 979, in testRegisterCustomEPsLibrary
    raise FileNotFoundError("Unable to find '{0}'".format(shared_library))
FileNotFoundError: Unable to find 'test_execution_provider.dll'

----------------------------------------------------------------------
Ran 43 tests in 0.308s

FAILED (errors=1)
Traceback (most recent call last):
  File "C:\Users\juharri\workspace\onnx\onnxruntime\\tools\ci_build\build.py", line 2203, in <module>
    sys.exit(main())
  File "C:\Users\juharri\workspace\onnx\onnxruntime\\tools\ci_build\build.py", line 2130, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "C:\Users\juharri\workspace\onnx\onnxruntime\\tools\ci_build\build.py", line 1485, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnxruntime_test_python.py'], cwd=cwd, dll_path=dll_path)
  File "C:\Users\juharri\workspace\onnx\onnxruntime\\tools\ci_build\build.py", line 588, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\juharri\workspace\onnx\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Users\juharri\Miniconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\juharri\\Miniconda3\\python.exe', 'onnxruntime_test_python.py']' returned non-zero exit status 1.
```

**Expected behavior**
Tests pass.

**Additional context**
Looks like this is from https://github.com/microsoft/onnxruntime/pull/7332 @souptc do you know what I should do?

**Comment by souptc** [comment]
currently this test only enabled for windows non-training build. 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python.py#L975

I saw you are running a training build with "--enable_training" flag, then if shouldn't run this test. perhaps the
"
from onnxruntime.capi.ort_trainer import ORTTrainer
" 

test failed?

**Comment by juharris** [comment]
Looks like it ran because `import onnx` failed. So I did `pip install onnx`.  Now I get:
`No module named 'onnx.onnx_cpp2py_export'` when I try to run the tests.

Are the setup steps documented anywhere?

**Comment by snnn** [comment]
> Are the setup steps documented anywhere?


1. Install vcpkg from https://github.com/microsoft/vcpkg and run 
```
C:\vcpkg\vcpkg.exe install protobuf:x64-windows-static protobuf:x64-windows 
```
Or 
```
C:\vcpkg\vcpkg.exe install protobuf:x86-windows-static protobuf:x86-windows 
```

2. Run the following powershell script in "cmake\external\onnx" of onnxruntime's source dir.

```powershell
     $Env:USE_MSVC_STATIC_RUNTIME=1
     $Env:ONNX_ML=1
     $Env:CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=$(buildArch)-windows-static"
     python setup.py bdist_wheel
     python -m pip uninstall -y onnx -qq
     Get-ChildItem -Path dist/*.whl | foreach {pip --disable-pip-version-check install --upgrade $_.fullname}
```

**Comment by juharris** [comment]
Thanks @snnn is that required? If so, then shouldn't the build steps do it for me?

**Comment by snnn** [comment]
I was just trying to answer your question about how to install ONNX. If "pip install onnx" doesn't  work, you can report the issue to https://github.com/onnx/onnx, or try the commands above.

**Comment by juharris** [comment]
Thanks. I'm just trying to build this project.

**Comment by snnn** [comment]
You don't need to install onnx.

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
