### ISSUE TITLE
ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library

### ISSUE THREAD

**Issue by youngwang666** [microsoft/onnxruntime#8283]
[Enter feedback here]
Code:
env = OrtEnvironment.getEnvironment();
OrtSession.SessionOptions opts = new OrtSession.SessionOptions();
        try {
            int gpuDeviceId = 0;
            opts.addCUDA(gpuDeviceId);
            opts.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.BASIC_OPT);
            session = env.createSession(localModelPath, opts);
            LOGGER.info("Loading model from " + localModelPath);
        } catch (Exception e) {
            LOGGER.error("load onnx model error", e);
        }
I want to use GPU to run the onnx model. but got error:
load onnx model error
ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
at ai.onnxruntime.OrtSession$SessionOptions.addCUDA(Native Method) ~[onnxruntime_gpu-1.8.0.jar:1.8.0]
at ai.onnxruntime.OrtSession$SessionOptions.addCUDA(OrtSession.java:765) ~[onnxruntime_gpu-1.8.0.jar:1.8.0]

environment:
nvidia dirver:460.73.01    cuda version: 11.2   cudnn version:v8.1.0.77

How can I fix  this problem?
---
#### Document Details
* Title: Java API
* Page: [https://www.onnxruntime.ai/docs/reference/api/java-api.html](https://www.onnxruntime.ai/docs/reference/api/java-api.html)
* Page Source: java-api.md

**Comment by Craigacp** [comment]
I think you might need to build it from source to use CUDA 11.2. The jar on Maven central loads fine for me with CUDA 11.

**Comment by yuslepukhin** [comment]
This typically means that your CUDA libraries could not be found by the executable. A simple way to make sure they are found is either bin place them in  your exe folder or add them to the path. `where` command in cmd can tell if you if a dll can be found from the environment.

**Comment by youngwang666** [comment]
My application put in our serve not in my compute. And I also put the path to the bashrc file.like:
export CUDA_HOME=/usr/local/cuda-11.2
export PATH=/usr/local/cuda-11.2/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
by the way, The server system is centenOS7.2. jdk version is 1.8. 

Besides,I test cuda in python environment. config and result like the picture.（through torch1.8 to test the cuda whether available）
![image](https://user-images.githubusercontent.com/28757277/124414578-94193180-dd85-11eb-98a0-cad8d1a88207.png)
![image](https://user-images.githubusercontent.com/28757277/124414649-b448f080-dd85-11eb-898e-7c7acd446423.png)

I donot known where the problem is. Is ONNX need to specify the cuda version?

**Comment by youngwang666** [comment]
Thanks all.
I hava sovled this problem. The problem is cuda is not installed correctly. cudnn file just copy part to the 'cuda/lib64' .I reinstall the cuda11 to sovled this issue.

**Comment by EmreOzkose** [comment]
> 

Hi, can you a little bit detail about solution. I have the same problem with c++.

```
[lib] [error] [onnx] Failed to load library, error code: 126 Location: provider_bridge_ort.cc:902 onnxruntime::ProviderSharedLibrary::Ensure
[model-reader] [critical] Exception occurred. Detail : OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
model read failure : unexpected error  C:\path\to\Test.exe (process 29448) exited with code -1. 
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops. 
Press any key to close this window . . .  
````

**Comment by EmreOzkose** [comment]
The problem is visual studio22 cannot see onnxruntime.dll in the path and I added onnxruntime.dll to build directory. It was cpu version. I changed it with GPU version and it works now. However it is very very slow (25 times). I will dive into that problem.

**Comment by Devi1k** [comment]
I solved this problem, my cuda version is 11.2, and finally found that I need to set the maven dependency to onnxruntime_gpu instead of onnxruntime.

**Comment by Devi1k** [comment]
I solved this problem, my cuda version is 11.2、onnxruntime_gpu 1.9, and finally found that I need to set the maven dependency to onnxruntime_gpu instead of onnxruntime.
