### ISSUE TITLE
NOT_IMPLEMENTED : Could not find an implementation for the node Imputer:Imputer(1)

### ISSUE THREAD

**Issue by abuvaneswari** [microsoft/onnxruntime#8373]
When I run an onnx model that is an equivalent of an sklearn pipeline with SimpleImputer() (sklearn function) as one of the data transformation components, the onnxruntime session instantiation with the onnx model results in the NOT_IMPLEMENTED 
error.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.1
- Python version: 3.7
- CUDA/cuDNN version: Not used (EP - CPU)

**To Reproduce**
I attach the python code and the model that was generated from the running of this code at my end.
[housing_pipeline_gitissue.zip](https://github.com/microsoft/onnxruntime/files/6811126/housing_pipeline_gitissue.zip)

- Unzip the attached zip file, pip install the dependencies and run the python code as follows:
pip install scikit-learn==0.24.2 skl2onnx==1.9.0 onnxruntime==1.8.1 pandas==1.3.0 numpy==1.20.2 
python housing_pipeline_with_imputer.git.py

This trains the housing price prediction sklearn model very quickly and saves the onnx equivalent of the model. Loads the same and tries to execute it using onnxruntime.

**Expected behavior**
The model is supposed to run to completion and print results that are similar to the sklearn model output. In fact if you comment out the SimpleImputer line (line 34) and run the code, it runs to completion. This is the behavior we want with the SimpleImputer's presence as well.

**Actual Behavior**
Instantiation of onnxruntime session fails with the following error message:
2021-07-13 13:03:19.843741885 [I:onnxruntime:, inference_session.cc:230 operator()] Flush-to-zero and denormal-as-zero are off
2021-07-13 13:03:19.843781717 [I:onnxruntime:, inference_session.cc:237 ConstructorCommon] Creating andusing per session threadpools since use_per_session_threads_ is true
2021-07-13 13:03:19.847401342 [I:onnxruntime:Default, bfc_arena.cc:25 BFCArena] Creating BFCArena for Cpu with following configs: initial_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_chunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strategy: 0
2021-07-13 13:03:19.847472375 [V:onnxruntime:Default, bfc_arena.cc:61 BFCArena] Creating 21 bins of maxchunk size 256 to 268435456
2021-07-13 13:03:19.847528459 [I:onnxruntime:, inference_session.cc:1141 Initialize] Initializing session.
2021-07-13 13:03:19.855673206 [I:onnxruntime:, reshape_fusion.cc:42 ApplyImpl] Total fused reshape nodecount: 0
2021-07-13 13:03:19.856174460 [I:onnxruntime:, reshape_fusion.cc:42 ApplyImpl] Total fused reshape nodecount: 0
2021-07-13 13:03:19.856600973 [I:onnxruntime:, reshape_fusion.cc:42 ApplyImpl] Total fused reshape nodecount: 0
Traceback (most recent call last):
  File "housing_pipeline_with_imputer.git.py", line 100, in <module>
    pipe.predict(**model_dict)
  File "housing_pipeline_with_imputer.git.py", line 91, in predict
    sess = rt.InferenceSession(omodel)
  File "/home/buvana/anaconda3/envs/blis_uvnik_test_0711/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/buvana/anaconda3/envs/blis_uvnik_test_0711/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Imputer:Imputer(1)

**Comment by hariharans29** [comment]
It seems like the current Imputer implementation only support float and int64 - https://github.com/microsoft/onnxruntime/blob/31f291f0afa77aa5b96d8082bab57dadc8c11e51/onnxruntime/core/providers/cpu/ml/imputer.cc#L52. Your model seems to require double. Any chance you could make your model consume float inputs ?

**Comment by abuvaneswari** [comment]
@hariharans29 , thanks a lot for the timely response! I converted my input types to float32 and am now able to run the model fine. 👍
