### ISSUE TITLE
Failed to build onnxruntime with dockerfile.arm32v7

### ISSUE THREAD

**Issue by PengchengChang** [microsoft/onnxruntime#8426]
**Describe the bug**
Hi. I want to build a python wheel for a Raspberry Pi (armv7l). I followed the instruction [in this page](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#arm-32v7). When I build the image on a ubuntu 18.04 OS Platform with x86_64 cpu, an error in `./build.sh ${BUILDARGS} --update --build --build_shared_lib --build_wheel'` appears.

```
[ 26%] Built target onnx_proto
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/cpuid_info.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/denormal.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/helper.cc.o
[ 26%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/logging/capture.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/logging/logging.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/logging/sinks/ostream_sink.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/path.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/profiler.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/status.cc.o
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/threadpool.cc.o
CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/threadpool.cc.o
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:162:0,
                 from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/Tensor:14,
                 from /code/onnxruntime/include/onnxruntime/core/common/eigen_common_wrapper.h:32,
                 from /code/onnxruntime/onnxruntime/core/common/threadpool.cc:21:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:504:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                         ^~~~~~~~~~~~~
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:504:38: error: expected unqualified-id before ‘<’ token
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                                      ^
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:505:31: error: ‘type1’ was not declared in this scope
   typedef typename remove_all<type1>::type type;
                               ^~~~~
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:505:36: error: template argument 1 is invalid
   typedef typename remove_all<type1>::type type;
                                    ^
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:162:0,
                 from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/Tensor:14,
                 from /code/onnxruntime/include/onnxruntime/core/common/eigen_common_wrapper.h:32,
                 from /code/onnxruntime/onnxruntime/core/common/threadpool.cc:21:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:616:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                         ^~~~~~~~~~~~~
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:616:38: error: expected unqualified-id before ‘<’ token
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                                      ^
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:617:31: error: ‘type1’ was not declared in this scope
   typedef typename remove_all<type1>::type type;
                               ^~~~~
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/Meta.h:617:36: error: template argument 1 is invalid
   typedef typename remove_all<type1>::type type;
                                    ^
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:63:0,
                 from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/Tensor:53,
                 from /code/onnxruntime/include/onnxruntime/core/common/eigen_common_wrapper.h:32,
                 from /code/onnxruntime/onnxruntime/core/common/threadpool.cc:21:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
                                                        ^~~~
CMakeFiles/onnxruntime_common.dir/build.make:201: recipe for target 'CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/threadpool.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_common.dir/code/onnxruntime/onnxruntime/core/common/threadpool.cc.o] Error 1
CMakeFiles/Makefile2:1545: recipe for target 'CMakeFiles/onnxruntime_common.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_common.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 2208, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 2132, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/code/onnxruntime/tools/ci_build/build.py", line 1098, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/onnxruntime/tools/ci_build/build.py", line 593, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/onnxruntime/tools/python/util/run.py", line 41, in run
    completed_process = subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.
The command '/bin/sh -c ./build.sh ${BUILDARGS} --update --build --build_shared_lib --build_wheel' returned a non-zero code: 1
```

**Urgency**
It would be nice if somebody can help me quickly

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:v1.8.0
- Python version:3.9.5
- Visual Studio version (if applicable):None
- GCC/Compiler version (if compiling from source):6.3.0
- CUDA/cuDNN version:None
- GPU model and memory:None

**To Reproduce**
- Follow the instruction [in this page](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#arm-32v7).
```
sudo apt-get install -y qemu-user-static
mkdir onnx-build
cd onnx-build
docker build -t onnxruntime-arm32v7 -f Dockerfile.arm32v7 .
```

**Expected behavior**
After running the dockerfile, a python wheel for armv7l can be produced.

**Screenshots**
None

**Additional context**
I don't know what is the use of qemu-user-static. I just installed it as the instruction. Does it has relationship to this error?

**Comment by bianklancnik** [comment]
I am having the same error while following the same instruction on Raspberry Pi 4. Did you manage to solve the issue?

**Comment by snnn** [comment]
The file is out of maintain.

**Comment by snnn** [comment]
I suggest you use the base image from https://github.com/pypa/manylinux to replace the one in dockerfile.arm32v7 .

To build the base image: 
```bash
PLATFORM=armv7l POLICY=manylinux2014 COMMIT_SHA=latest ./build.sh
```

**Comment by PengchengChang** [comment]
> I am having the same error while following the same instruction on Raspberry Pi 4. Did you manage to solve the issue?

I didn't manage to do this. But I succeed in cross compiling. I suggest you to try it. Here is [the instruction](https://onnxruntime.ai/docs/how-to/build/inferencing#cross-compiling-on-linux).
