### ISSUE TITLE
RuntimeError when using DirectML as the backend on Windows 10

### ISSUE THREAD

**Issue by daoxian** [microsoft/onnxruntime#8435]
On Windows 10 (1809), I built Onnxruntime wheel 1.8.0 with --use_dml option successfully. When running the following Python-3.6 code:
```
import onnxruntime
EP_list = onnxruntime.get_available_providers()  # now we got: ['DmlExecutionProvider', 'CPUExecutionProvider']
.......
onnx_session = onnxruntime.InferenceSession('./onnx/mytest.onnx', providers=EP_list)
```
An error accurs:
```
Traceback (most recent call last):
  File "D:\work\iTag\OpenIS_V2.480\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\work\iTag\OpenIS_V2.480\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError
```

I tried to trace the sys API calling sequence (by API Monitor v2) in order to loate where the problem is.
 
![image](https://user-images.githubusercontent.com/34263430/126267251-fab07d9c-d17d-417f-9207-b378c1656326.png)

It looks like some file or module is missing.  

I used the Dependencies tool to check onnxruntime_pybind11_state.pyd to find whether some .dll files are missing, I got:
![image](https://user-images.githubusercontent.com/34263430/126268058-185991ea-917b-4258-a7bf-fcc44e58fa9d.png)
![image](https://user-images.githubusercontent.com/34263430/126268082-97c46c65-4f15-4ff7-ae76-77386ba2c840.png)
![image](https://user-images.githubusercontent.com/34263430/126268146-ac88b48a-a5d6-4ac6-b8ec-7a47b8f9b469.png)
After I searched the dll, I learned that they're Win32 API Sets that point to actual dll files, and I don't think they are really missing.

On the other hand, if I use 'CUDAExecutionProvider' instead, everything works fine.

Could anyone help me out? Any hint is appreciated.

**Comment by daoxian** [comment]
I successfully ran the same program on another Windows10 (winver 1809) PC, with the same python environment.
The unsuccessful one:
![image](https://user-images.githubusercontent.com/34263430/126432866-dd269504-3562-4fb6-83e4-163fd60c26fe.png)

The successful one:
![image](https://user-images.githubusercontent.com/34263430/126432901-0f1d94dd-77e6-4647-a1cf-41e75f5be1c2.png)


No idea why...

**Comment by daoxian** [comment]
Finally, after investigating all the available Graphic Adapters, I found the integrated intel graphic adapter disabled, which DirectX works on.  After enabling it,  the code works fine with onnxruntime+DirectML.
