### ISSUE TITLE
Error when getting InferenceSession

### ISSUE THREAD

**Issue by xjw00654** [microsoft/onnxruntime#8504]
**Describe the bug**
I converted a tf(saved_model) to onnx using `tf2onnx` and found no errors. Then, I use `onnxruntime` for testing the result, error occurs when creating the InferenceSession, the code and error msg as follow:

- RUN CODE
```python
onnxruntime.set_default_logger_severity(1)
self.sess = onnxruntime.InferenceSession('text_v8.onnx')
```

- TF saved_model CODE
```python
tf.saved_model.simple_save(
    self.sess,
    './text',
    inputs={
        'input_1:0': self.graph.get_tensor_by_name('input_1:0'),
        'image_shape:0': self.graph.get_tensor_by_name('image_shape:0'),
        'input_shape:0': self.graph.get_tensor_by_name('input_shape:0'),
    },
    outputs={self.box_score.name: self.graph.get_tensor_by_name(self.box_score.name)}
)
```
- tf2onnx convert CLI 
```bash
python -m tf2onnx.convert --saved-model ./text --opset 13 --output text_v8.onnx --tag serve
```

- ERROR MSG
```python
2021-07-27 09:41:04.805562800 [I:onnxruntime:, inference_session.cc:230 operator()] Flush-to-zero and denormal-as-zero are off
2021-07-27 09:41:04.805605700 [I:onnxruntime:, inference_session.cc:237 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-07-27 09:41:05.127363100 [I:onnxruntime:Default, bfc_arena.cc:25 BFCArena] Creating BFCArena for Cpu with following configs: initial_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_chunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strategy: 0
2021-07-27 09:41:05.127530400 [I:onnxruntime:, inference_session.cc:1141 Initialize] Initializing session.
2021-07-27 09:41:05.140133800 [I:onnxruntime:Default, bfc_arena.cc:305 AllocateRawInternal] Extending BFCArena for Cpu. bin_num:0 (requested) num_bytes: 8 (actual) rounded_bytes:256
2021-07-27 09:41:05.140283600 [I:onnxruntime:Default, bfc_arena.cc:185 Extend] Extended allocation by 1048576 bytes.
2021-07-27 09:41:05.140319600 [I:onnxruntime:Default, bfc_arena.cc:188 Extend] Total allocated bytes: 1048576
2021-07-27 09:41:05.140335100 [I:onnxruntime:Default, bfc_arena.cc:191 Extend] Allocated memory at 0x55e819704b80 to 0x55e819804b80
Traceback (most recent call last):
  File "/mnt/d/Codes/hub/test.py", line 13, in <module>
    OCR(images_path='examples', use_cpu=True, use_onnx=True, detect_angle=True)
  File "/mnt/d/Codes/hub/ocr_horizontal/main.py", line 37, in __init__
    self.model = self.load_model()
  File "/mnt/d/Codes/hub/ocr_horizontal/main.py", line 43, in load_model
    chinese_ocr = ChineseOCR(self.config)
  File "/mnt/d/Codes/hub/ocr_horizontal/model/ocr.py", line 52, in __init__
    self.text_detector_model = TextDetector()
  File "/mnt/d/Codes/hub/ocr_horizontal/model/text_detector/text_detector.py", line 44, in __init__
    self.onnx_detect_model = ONNXDetectYOLO()
  File "/mnt/d/Codes/hub/ocr_horizontal/model/text_detector/text/keras_detect.py", line 109, in __init__
    self.sess = onnxruntime.InferenceSession(self.config["model_path"])
  File "/home/xxx/anaconda3/envs/ocr/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/xxx/anaconda3/envs/ocr/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : indices element out of data bounds, idx=1 must be within the inclusive range [-1,0]
```

The most similar question is [#4523](https://github.com/huggingface/transformers/issues/4523) with the error as follow:
```python
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'Gather_32' Status Message: indices element out of data bounds, idx=1 must be within the inclusive range [-1,0]
```
But i have check the solutions in the issue but failed. Since my error msg did not tell me the error occur on which node or step, so i am really curious ...

More information about my model:
1. The model is a simple yolov3 based text detection model. Note that i merged the post-process part into the tf graph.
2. The model output will be shape=`?x5` where `?` means number of boxes and `5` means 4 boxes and 1 confidence.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows11 - wsl2 - Ubuntu18.04
- ONNX Runtime installed from (source or binary): binary - from `pip install`
- ONNX Runtime version: 1.8.1
- Python version:
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: using CPU only
- GPU model and memory: none

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
[onnx model link](https://drive.google.com/file/d/1N4n3-yVv_8MtL-NL2KBqOn0jR7N3Ro-3/view?usp=sharing)

**Expected behavior**
Getting InferenceSession successfully : )

**Screenshots**
none

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @xjw00654, it looks like tf2onnx is converting a ReverseV2 node incorrectly resulting in the exception in onnx runtime.  Can you upload a copy of your original TF model here: https://github.com/onnx/tensorflow-onnx/issues/1635

Thanks!

**Comment by faxu** [comment]
Closing this issue in this repo; please follow up to resolve the tensorflow-onnx issue in [onnx/tensorflow-onnx#1635](https://github.com/onnx/tensorflow-onnx/issues/1635)
