### ISSUE TITLE
onnxruntime.InferenceSession

### ISSUE THREAD

**Issue by carlsummer** [microsoft/onnxruntime#8505]
Traceback (most recent call last):
  File "/home/zengxh/workspace/lcnn/deploy/xxx.py", line 8, in <module>
    ort_session = onnxruntime.InferenceSession("/home/zengxh/workspace/lcnn/logs/210726-144038-88f281a-baseline/checkpoint_best.onnx")
  File "/home/zengxh/anaconda3/envs/CreepageDistance/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/zengxh/anaconda3/envs/CreepageDistance/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (GatherND_452) Op (GatherND) [ShapeInferenceError] Last dimension of `indices` input tensor in GatherND op must not be larger than the rank of `data` tensor

**Comment by carlsummer** [comment]
image = get_image(image_path, opt.predict_type).cuda()
    junc = torch.zeros(1, 2).cuda()
    jtyp = torch.zeros(1, dtype=torch.uint8).cuda()
    Lpos = torch.zeros(2, 2, dtype=torch.uint8).cuda()
    torch.onnx.export(mymodel, (image, junc, jtyp, Lpos), opt.onnx_path,
                      opset_version=11,
                      verbose=True,
                      export_params=True,  #是否导出params
                      do_constant_folding=True, #是否进行常量折叠进行优化
                      # dynamic_axes= {
                      #                'input': {0: 'image',1: 'junc',2: 'jtyp',3: 'Lpos'},
                      #                'output': {0: 'lines',1: 'score'}
                      #                },
                      input_names=['image',"junc","jtyp","Lpos"],
                      output_names=['lines',"score"],)

import onnxruntime  #cuda10.2==1.6.0
print(onnxruntime.get_device())
ort_session = onnxruntime.InferenceSession("/home/zengxh/workspace/lcnn/logs/210726-144038-88f281a-baseline/checkpoint_best.onnx")
