### ISSUE TITLE
not defined in file libcublasLt.so.11

### ISSUE THREAD

**Issue by nobody-cheng** [microsoft/onnxruntime#8594]
python: 3.7
GPU 3060 12G
NVIDIA-SMI: 460.84       
Driver Version: 460.84       
CUDA Version: 11.2
CUDNN Version: 8.0
ubuntu 18.04
onnx   1.10.1
onnxruntime-gpu   1.7.0

```
>>> import onnxruntime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gpu/anaconda3/envs/FXM/lib/python3.7/site-packages/onnxruntime/__init__.py", line 24, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/home/gpu/anaconda3/envs/FXM/lib/python3.7/site-packages/onnxruntime/capi/_pybind_state.py", line 9, in <module>
    import onnxruntime.capi._ld_preload  # noqa: F401
  File "/home/gpu/anaconda3/envs/FXM/lib/python3.7/site-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcublas = CDLL("libcublas.so.11", mode=RTLD_GLOBAL)
  File "/home/gpu/anaconda3/envs/FXM/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/gpu/anaconda3/envs/FXM/lib/python3.7/lib-dynload/../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

**Comment by yuslepukhin** [comment]
Find out how many `libcublasLt.so.11` you have on the system and make sure the correct one is loaded.
