### ISSUE TITLE
PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 0

### ISSUE THREAD

**Issue by wangyunxiaa** [microsoft/onnxruntime#8685]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.
I have a tf saved_model,and can convert it to onnx mode use the following commond:
`python -m tf2onnx.convert --saved-model v4 --output fangyan_new.onnx --opset 12
`
but when i do inference use onnxruntime, I got error:
```
2021-08-11 06:10:38.779554751 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Concat node. Name:'transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1' Status Message: concat.cc:87 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 0
2021-08-11 06:10:38.779621206 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Loop node. Name:'generic_loop_Loop__113' Status Message: Non-zero status code returned while running Concat node. Name:'transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1' Status Message: concat.cc:87 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 0
Traceback (most recent call last):
  File "onnx_infer_fangyan_lite.py", line 57, in <module>
    ort_outs = ort_session.run([output_name1], input_feed)
  File "/usr/local/lib64/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Loop node. Name:'generic_loop_Loop__113' Status Message: Non-zero status code returned while running Concat node. Name:'transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1' Status Message: concat.cc:87 PrepareForCompute Non concat axis dimensions must match: Axis 0 has mismatched dimensions of 1 and 0
```
the input and output asr as followings:
```
NodeArg(name='encoder_input:0', type='tensor(int32)', shape=['unk__2615', 'unk__2616'])
NodeArg(name='strided_slice_5', type='tensor(int32)', shape=['unk__2617', 0])
```
but the tfs model's output dim is [-1,-1]
```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['encoder_input'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: encoder_input:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['strided_slice_5'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: strided_slice_5:0
  Method name is: tensorflow/serving/predict
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.1
- Python version: 3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.3
- GPU model and memory: A10 22731MiB

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
I am confused that, the onnx model is no correct but I add the --inputs and --outputs flag while convert the model, there is no use, and try the frozen model to convert, the error persists.
**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.
the tfs model: [https://github.com/wangyunxiaa/model/blob/master/v4/saved_model.pb]
the onnx model: [https://github.com/wangyunxiaa/model/blob/master/v4.onnx]

**Comment by ytaous** [comment]
@hariharans29 - message looks similar to https://github.com/microsoft/onnxruntime/issues/8020 , but may be with different root cause.

**Comment by wangyunxiaa** [comment]
thank you for your reply,
I will reinstall onnxruntime from source with master branch, and have a retry.

I also have tried to run the onnx model with onnx_tf.backend, and I got an another error, does the onnx model is invalid?
`NodeArg(name='strided_slice_5', type='tensor(int32)', shape=['unk__2617', 0])`
the outputs showed that the output dims is different with tfs [-1, -1]

**Comment by wangyunxiaa** [comment]
I reinstall the onnxruntime from source with master branch, and have a try, the error change
```
2021-08-16 02:09:00.322869995 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Loop node. Name:'generic_loop_Loop__108' Status Message: Non-zero status code returned while running Reshape node. Name:'transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/Reshape' Status Message: /models/tensorRT/onnxruntime/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,512}, requested shape:{1,512,4,128}
Stacktrace:
```
BTW,when I transfromed the ori tf model  to onnx first time, it addedd a default string input,` INFO - Model inputs: ['encoder_input', 'word_embedder_1/global_mode:0']` , and the model cannot infer by onnxruntime:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from fangyan_lite.onnx failed:Node (generic_loop_Loop__144) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: This is an invalid model. Type Error: Type 'tensor(string)' of input parameter (word_embedder_1/global_mode:0) of operator (Equal) in node (transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/Equal) is invalid`
so, I delete the tf model string equal node, and the new model no the above error, But Got another error as mentioned, I am confused the error is onnx model error or onnxruntime error?
the tf model is: ### https://github.com/wangyunxiaa/model/blob/master/v4/saved_model.pb

**Comment by wangyunxiaa** [comment]
`python -m onnxruntime.tools.symbolic_shape_infer --input fangyan_new.onnx `
got flollowing error: 
```
input model: fangyan_new.onnx
Doing symbolic shape inference...
Stopping at incomplete shape inference at Concat: transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1
node inputs:
name: "transformer_decoder_2/while/Reshape_4:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 0
      }
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 512
      }
    }
  }
}

name: "transformer_decoder_1/layer_0/self_attention/multihead_attention/multihead_attention/value/Tensordot_1:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 512
      }
    }
  }
}

node outputs:
name: "transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
        dim_value: 2
      }
      dim {
        dim_value: 512
      }
    }
  }
}

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1935, in <module>
    args.guess_output_rank, args.verbose)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1898, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1733, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 903, in _infer_Loop
    if is_sequence(so.type):
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 28, in is_sequence
    assert cls_type in ['tensor_type', 'sequence_type']
AssertionError

```
maybe the onnxmodel is wrong when do convert

**Comment by Liuyong-zhixing** [comment]
cmd：python -m onnxruntime.quantization.preprocess --input yolov5s.onnx --output yolov5s-infer.onnx

debug info：
yyy2 tensor_type yyy2
yyy vi= name: "/model.24/Add_output_0"
type {
}
 yyy
yyy2 None yyy2

Traceback (most recent call last):
  File "C:\Users\13377\.conda\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\13377\.conda\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\13377\.conda\envs\py310\lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 2764, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
  File "C:\Users\13377\.conda\envs\py310\lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 2696, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "C:\Users\13377\.conda\envs\py310\lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 2498, in _infer_impl
    out_rank = len(get_shape_from_type_proto(vi.type))
  File "C:\Users\13377\.conda\envs\py310\lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 38, in get_shape_from_type_proto
    assert not is_sequence(type_proto)
  File "C:\Users\13377\.conda\envs\py310\lib\site-packages\onnxruntime\tools\symbolic_shape_infer.py", line 33, in is_sequence
    assert cls_type in ["tensor_type", "sequence_type"]

==》onnxmodel is wrong？

**Comment by Liuyong-zhixing** [comment]
> `python -m onnxruntime.tools.symbolic_shape_infer --input fangyan_new.onnx ` got flollowing error:
> 
> ```
> input model: fangyan_new.onnx
> Doing symbolic shape inference...
> Stopping at incomplete shape inference at Concat: transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1
> node inputs:
> name: "transformer_decoder_2/while/Reshape_4:0"
> type {
>   tensor_type {
>     elem_type: 1
>     shape {
>       dim {
>         dim_value: 0
>       }
>       dim {
>         dim_value: 1
>       }
>       dim {
>         dim_value: 512
>       }
>     }
>   }
> }
> 
> name: "transformer_decoder_1/layer_0/self_attention/multihead_attention/multihead_attention/value/Tensordot_1:0"
> type {
>   tensor_type {
>     elem_type: 1
>     shape {
>       dim {
>         dim_value: 1
>       }
>       dim {
>         dim_value: 1
>       }
>       dim {
>         dim_value: 512
>       }
>     }
>   }
> }
> 
> node outputs:
> name: "transformer_decoder_2/while/layer_0/self_attention/multihead_attention/multihead_attention/concat_1:0"
> type {
>   tensor_type {
>     elem_type: 1
>     shape {
>       dim {
>       }
>       dim {
>         dim_value: 2
>       }
>       dim {
>         dim_value: 512
>       }
>     }
>   }
> }
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1935, in <module>
>     args.guess_output_rank, args.verbose)
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1898, in infer_shapes
>     all_shapes_inferred = symbolic_shape_inference._infer_impl()
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1733, in _infer_impl
>     self.dispatcher_[node.op_type](node)
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 903, in _infer_Loop
>     if is_sequence(so.type):
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime/tools/symbolic_shape_infer.py", line 28, in is_sequence
>     assert cls_type in ['tensor_type', 'sequence_type']
> AssertionError
> ```
> 
> maybe the onnxmodel is wrong when do convert

encounter the same problem， fixed?

**Comment by dhruvbird** [comment]
I'm running into the same problem when using `python -m onnxruntime.tools.symbolic_shape_infer --input <path_to_file.onnx>`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dhruv/python_envs/.tiny_xformer/lib/python3.11/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 2886, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhruv/python_envs/.tiny_xformer/lib/python3.11/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 2818, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhruv/python_envs/.tiny_xformer/lib/python3.11/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 2568, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "/Users/dhruv/python_envs/.tiny_xformer/lib/python3.11/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 1159, in _infer_Loop
    if is_sequence(so.type):
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhruv/python_envs/.tiny_xformer/lib/python3.11/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 32, in is_sequence
    assert cls_type in ["tensor_type", "sequence_type"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
