### ISSUE TITLE
Error building onnxruntime during Docker build on Mac

### ISSUE THREAD

**Issue by leah-classpass** [microsoft/onnxruntime#8835]
**Describe the bug**
Running this command fails in a docker image build on Mac:
`RUN /opt/onnxruntime/tmp/onnxruntime/build.sh --config Release --build_shared_lib --parallel`

The error:
```
#15 93.61 Fetching submodule 3rdparty/dlpack
#15 94.22 Fetching submodule 3rdparty/dmlc-core
#15 96.41 From https://github.com/dmlc/dmlc-core
#15 96.41  * branch            04f91953ace74aced3bb317990515304c5425849 -> FETCH_HEAD
#15 96.41  * branch            2b75a0ce6f191ad0fcb5319039b41e990968542a -> FETCH_HEAD
#15 96.41  * branch            2e1fcedfed1253289ade441a56427e44fb9c98aa -> FETCH_HEAD
#15 96.41  * branch            39007ac49b6087339dc3104324cb4e0de47f1c5f -> FETCH_HEAD
#15 96.41  * branch            3a51614d39b69fdb5de1efcf1016426626d267a6 -> FETCH_HEAD
#15 96.41  * branch            46886a6b47f660cda581e497378204ccc029a01e -> FETCH_HEAD
#15 96.41  * branch            4d49691f1a9d944c3b0aa5e63f1db3cad1f941f8 -> FETCH_HEAD
#15 96.41  * branch            4f0564ec769477c66d480dd966088f172050c874 -> FETCH_HEAD
#15 96.41  * branch            519d013a213c0c447a971f51219473ef564d2348 -> FETCH_HEAD
#15 96.41  * branch            53751c3da2999d841f4f952639bd766505b51d84 -> FETCH_HEAD
#15 96.41  * branch            674a662c22b900b76e8a3c9b77987a2c5563ba71 -> FETCH_HEAD
#15 96.41  * branch            749e570c19423fe679a5f496e2394ba3bed75a16 -> FETCH_HEAD
#15 96.41  * branch            7afa45b87ce639b29d809cc15149f0caa48ac6c4 -> FETCH_HEAD
#15 96.41  * branch            7e84e8b036a3ff5c0104a3da1f4c7eebf94396ec -> FETCH_HEAD
#15 96.41  * branch            87a0c16267f94155957e527ac362269e5bb33f0e -> FETCH_HEAD
#15 96.41  * branch            8dd365636528175e785448cf8a9f4e494c8ee0e0 -> FETCH_HEAD
#15 96.41  * branch            946a54012d0c390675ab5b46cd990838d4183d6f -> FETCH_HEAD
#15 96.41  * branch            9b3f9753ae81d657743c555e0cacc4e43f0bed2d -> FETCH_HEAD
#15 96.41  * branch            a384fb9ed09d0c430c468db91abb3694deb88e54 -> FETCH_HEAD
#15 96.41  * branch            a527100d7d5001efc4954848a2fc6027e48c05f4 -> FETCH_HEAD
#15 96.41  * branch            a6c5701219e635fea808d264aefc5b03c3aec314 -> FETCH_HEAD
#15 96.41  * branch            c0871823b518093a0d04d6cba0a3291bc7b31401 -> FETCH_HEAD
#15 96.41  * branch            c2871f5db50830f5278ff6e323e8e51a6d5516dd -> FETCH_HEAD
#15 96.41  * branch            d3f7fbb53e5b037c0f5bf6bd21871ccc720690cc -> FETCH_HEAD
#15 96.41  * branch            e864aa6757cdbe78b1296fe5231fd3050b7802c3 -> FETCH_HEAD
#15 96.41  * branch            f294fc2271b27b0b6e2b117003ed2dc3d3ba8fda -> FETCH_HEAD
#15 97.46 From https://github.com/dmlc/dlpack
#15 97.46  * branch            10892ac964f1af7c81aae145cd3fab78bbccd297 -> FETCH_HEAD
#15 97.46  * branch            36e573893fc39d324ccf2f2962300da6da5898a2 -> FETCH_HEAD
#15 97.46  * branch            6fe55524e99de396043010001833938bfba53c0c -> FETCH_HEAD
#15 97.46  * branch            9422e98f3f4dafc6bc3473cf8484543ad376aab6 -> FETCH_HEAD
#15 97.46  * branch            9f433c5ecfdd47184339cdd2b99706d24fae3aa1 -> FETCH_HEAD
#15 97.46  * branch            a6e09b58dc00ee0065f5b7879800e646fbb01d1e -> FETCH_HEAD
#15 97.46  * branch            bee4d1dd8dc1ee4a1fd8fa6a96476c2f8b7492a3 -> FETCH_HEAD
#15 98.20 fatal: remote error: upload-pack: not our ref 0fe824d680fe9c2ccbd874d4a80b26d92e65fbec
#15 98.20 Errors during submodule fetch:
#15 98.20 	HalideIR
#15 98.22 Fetched in submodule path 'cmake/external/tvm', but it did not contain eab844a87298d500f1924f8a7cadb4cbee426093. Direct fetching of that commit failed.
#15 98.22 Traceback (most recent call last):
#15 98.22   File "/opt/onnxruntime/tmp/onnxruntime/tools/ci_build/build.py", line 2152, in <module>
#15 98.22     sys.exit(main())
#15 98.22   File "/opt/onnxruntime/tmp/onnxruntime/tools/ci_build/build.py", line 1927, in main
#15 98.22     update_submodules(source_dir)
#15 98.22   File "/opt/onnxruntime/tmp/onnxruntime/tools/ci_build/build.py", line 586, in update_submodules
#15 98.22     run_subprocess(["git", "submodule", "update", "--init", "--recursive"],
#15 98.22   File "/opt/onnxruntime/tmp/onnxruntime/tools/ci_build/build.py", line 581, in run_subprocess
#15 98.22     return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
#15 98.22   File "/opt/onnxruntime/tmp/onnxruntime/tools/python/util/run.py", line 41, in run
#15 98.22     completed_process = subprocess.run(
#15 98.22   File "/usr/lib/python3.9/subprocess.py", line 528, in run
#15 98.22     raise CalledProcessError(retcode, process.args,
#15 98.22 subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c /opt/onnxruntime/tmp/onnxruntime/build.sh --config Release --build_shared_lib --parallel]: exit code: 1
```

**Urgency**
This is blocking work, but is probably medium urgency.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina version 10.15.7 (19H1323)
- ONNX Runtime installed from (source or binary): github clone
- ONNX Runtime version: 1.5.2 thru 1.8.1 all fail
- Python version: N/A
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): latest through apt-get
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Docker engine version: 20.10.18 

**To Reproduce**
On a mac, run `onnxruntime/build.sh --config Release --build_shared_lib --parallel` in a Docker image build using Docker image base: `debian:bullseye-slim`

**Expected behavior**
A succesful docker build

**Comment by leah-classpass** [comment]
The docker commands to install:
```
RUN cd /opt/onnxruntime/tmp && \
    git clone --recursive --depth 1 --shallow-submodules https://github.com/Microsoft/onnxruntime

# use version that onnxruntime-sys expects
RUN cd /opt/onnxruntime/tmp/onnxruntime && \
    git fetch --depth 1 origin tag v1.6.0 && \
    git checkout v1.6.0
    ```

This used to pass, but perhaps the issue is with this: `--depth 1 --shallow-submodules`?

**Comment by snnn** [comment]
`--depth 1` can cause such issues.

**Comment by leah-classpass** [comment]
> `--depth 1` can cause such issues.

I understand. Do you have any idea why this recently started failing?

**Comment by leah-classpass** [comment]
Fyi this solution was in place due to the amount of time this library takes to build.

**Comment by snnn** [comment]
No, it is not. You got the error before the build was started.  If you add "--depth 1" there, you will save time and you bet nobody would change any code at the time when you pull out code, and you will have a chance seeing such errors. It's just a tradeoff. 

I will close the issue now because it is not an onnx runtime bug, it is more about git.
