### ISSUE TITLE
Runetime Error: Decoder with dynamic axes does not work with Encoder output

### ISSUE THREAD

**Issue by WQtong** [microsoft/onnxruntime#8910]
I am working on export a fairseq encoder-decoder model to ONNX. The encoder part works fine. When I exported decoder I give two arguemts: dummy input (token) and encoder output. After I exported the decoder, I ran it with onnx inference runtime. Since the batch size and seq length are dynamic, I use dynamic axes. This works perfectly with encoder.
The decoder says it needs three arguments, while the second is the encoder output embedding. When dealing with input the decoder says this error: 

> NodeArg(name='input1', type='tensor(int64)', shape=['batch_size', 'src_seq_len'])
NodeArg(name='input2', type='tensor(float)', shape=['src_seq_len', 'batch_size', 256])
NodeArg(name='input3', type='tensor(bool)', shape=['batch_size', 'src_seq_len'])
2021-08-31 17:39:27.026896130 [W:onnxruntime:, execution_frame.cc:721 VerifyOutputSizes] Expected shape from model of {10,10,256} does not match actual shape of {5,1,256} for output 115
2021-08-31 17:39:27.027197179 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_90' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:36 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{5,1,256}, requested shape:{-1,80,32}

> Traceback (most recent call last):
>   File "onnx_inerence.py", line 26, in <module>
>     outputs = ort_session_decoder.run(None, {'input1': dummy_input1, 'input2': outputs_encoder[0], 'input3': outputs_encoder[1]})
>   File "/opt/conda/envs/character-bert/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
>     return self._sess.run(output_names, input_feed, run_options)
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_90' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:36 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{5,1,256}, requested shape:{-1,80,32}

**Comment by WQtong** [comment]
When I export the batch size and seq length I use is 10 and 10. 
Since 5 and 1 here are src_length and batch_size which are dynamic, it should be fine to use other numbers during inference. However, only if I use same numbers during inference (10 and 10) the onnx decoder can run through. Otherwise it shows this issue. Can anyone help explain?

**Comment by WQtong** [comment]
My script for export:
`torch.onnx.export(torch_model_decoder, (dummy_input3, out_encoder), "decoder.onnx", opset_version=11 ,verbose=True, input_names=['input1', 'input2', 'input3'], output_names=["output"], dynamic_axes={'input1': {0: 'batch_size', 1: 'src_seq_len'}, 'input2': {0: 'src_seq_len', 1: 'batch_size'}, 'input3': {0: 'batch_size', 1: 'src_seq_len'}})`

**Comment by gwang-msft** [comment]
The input tensor has 5*1*256=1280 elements, the expected output shape is at least 80*32=2560 elements suppose the dynamic axis is 1, this is the reason of the failure running Reshape node.

**Comment by WQtong** [comment]
```
Traceback (most recent call last):
  File "onnx_inerence.py", line 26, in <module>
    outputs = ort_session_decoder.run(None, {'input1': dummy_input1, 'input2': outputs_encoder[0], 'input3': outputs_encoder[1]})
  File "/opt/conda/envs/character-bert/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_81' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{5,1,256}, requested shape:{1,8,32}
```
The error persists after I export with batch size & seq length = 1. When I do inference on example with seq = 5 it will show this error again, while input have 5 * 1 * 256 while request shape is 1*8*32. Also I don't know what tensor is the (1, 8, 32), it is not the final output of the network.

**Comment by shifujain** [comment]
> My script for export:
> `torch.onnx.export(torch_model_decoder, (dummy_input3, out_encoder), "decoder.onnx", opset_version=11 ,verbose=True, input_names=['input1', 'input2', 'input3'], output_names=["output"], dynamic_axes={'input1': {0: 'batch_size', 1: 'src_seq_len'}, 'input2': {0: 'src_seq_len', 1: 'batch_size'}, 'input3': {0: 'batch_size', 1: 'src_seq_len'}})`

@[WQtong](https://github.com/WQtong), after exporting the decoder did you check the input_meta for the decoder_session and the required dimensions. There might be an error while exporting. Can you please share a snippet of your decoder forward method arguments as well as the associated shapes of those arguments?
