### ISSUE TITLE
Optimization now fails with AssertionError: Graph is not a DAG

### ISSUE THREAD

**Issue by mkserge** [microsoft/onnxruntime#8921]
**Describe the bug**

Optimizing RoBERTa Large model with ONNX runtime now fails with "Graph is not a DAG" error on the save_model_to_file step.

**Urgency**
Not urgent, but currently blocking optimization completely.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: onnxruntime/onnxruntime-gpu==1.8.1 as well as ort-nightly-gpu==1.8.2.dev20210831001
- Python version: Python 3.8.10
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): GCC 9.4.0
- CUDA/cuDNN version: 11.4/8.2.2
- GPU model and memory: V100 16Gb

**To Reproduce**
In Python Shell, first convert the vanilla roberta-large model from Huggingface into ONNX.
```Python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> from transformers.convert_graph_to_onnx import convert
>>> convert(framework="pt", model="roberta-large", output=Path("/models/mrc-eng-usa-orig/onnx/roberta.onnx"), opset=14, pipeline_name="sentiment-analysis")
ONNX opset version set to: 14
Loading pipeline (model: roberta-large, tokenizer: roberta-large)
Some weights of the model checkpoint at roberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.bias', 'roberta.pooler.dense.bias', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.out_proj.bias', 'classifier.out_proj.weight', 'classifier.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using framework PyTorch: 1.10.0.dev20210831+cu111
Found input input_ids with shape: {0: 'batch', 1: 'sequence'}
Found input attention_mask with shape: {0: 'batch', 1: 'sequence'}
Found output output_0 with shape: {0: 'batch'}
Ensuring inputs are in correct order
token_type_ids is not present in the generated input list.
Generated inputs order: ['input_ids', 'attention_mask']
/home/browse/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:2168: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(
/home/browse/.local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:716: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
>>> quit()
```

Next, optimize the generated ONNX model using onnxruntime

```bash
browse@browse-optimizer-gpu-7484659594-dhqrb:~$ python -m onnxruntime.transformers.optimizer \
>     --input=/models/mrc-eng-usa-orig/onnx/roberta.onnx \
>     --model_type=bert \
>     --num_heads=16 \
>     --hidden_size=1024 \
>     --enable_gelu_approximation \
>     --verbose \
>     --opt_level=99 \
>     --use_gpu \
>     --output=/models/mrc-eng-usa-orig/onnx/roberta.opt.onnx
[Dropping  some of the output for brevity ]
[onnx_model.py:870 -   save_model_to_file()] Sort graphs in topological order
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/browse/.local/lib/python3.8/site-packages/onnxruntime/transformers/optimizer.py", line 336, in <module>
    main()
  File "/home/browse/.local/lib/python3.8/site-packages/onnxruntime/transformers/optimizer.py", line 327, in main
    optimizer.save_model_to_file(args.output, args.use_external_data_format)
  File "/home/browse/.local/lib/python3.8/site-packages/onnxruntime/transformers/onnx_model.py", line 871, in save_model_to_file
    self.topological_sort()
  File "/home/browse/.local/lib/python3.8/site-packages/onnxruntime/transformers/onnx_model.py", line 867, in topological_sort
    OnnxModel.graph_topological_sort(self.model.graph)
  File "/home/browse/.local/lib/python3.8/site-packages/onnxruntime/transformers/onnx_model.py", line 859, in graph_topological_sort
    assert (end == len(graph.node)), "Graph is not a DAG"
AssertionError: Graph is not a DAG
```

**Expected behavior**
Model should save.

**Comment by tianleiwu** [comment]
Currently, EmbedLayerNormalization does not support Roberta since it uses padding index in position embedding. The operator need some change to support it, and we do not have ETA right now.

It is fine to add --disable_embed_layer_norm to walkaround the issue.

**Comment by mkserge** [comment]
Thank you, I can confirm the workaround solves the issue.

Is the pull request #8914 resolving this issue with EmbedLayerNormalization you mention above, or there is more work that needs to be done? I am wondering if it's worth for me to try to compile from source on that branch and experiment with it? :)
