### ISSUE TITLE
CUDA build fails with RelWithDebInfo

### ISSUE THREAD

**Issue by spikecurtis** [microsoft/onnxruntime#8968]
**Describe the bug**
Fail to build with CUDA support if `--config RelWithDebInfo`.

Fails with

```
[ 60%] Linking CUDA shared module libonnxruntime_providers_cuda.so
[ 60%] Built target onnxruntime_providers_cuda
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/tools/ci_build/build.py", line 2162, in <module>
    sys.exit(main())
  File "/code/tools/ci_build/build.py", line 2086, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/code/tools/ci_build/build.py", line 1064, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/tools/ci_build/build.py", line 579, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/tools/python/util/run.py", line 44, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/code/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j16']' returned non-zero exit status 2.
The command '/bin/sh -c cd /code && /bin/bash ./build.sh --skip_submodule_sync --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config RelWithDebInfo --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) 'CMAKE_CUDA_ARCHITECTURES=30;37;50;52;60;70'' returned a non-zero code: 1
```

**Urgency**
Blocked

**System information**
`dockerfiles/Dockerfile.cuda` running on Docker 20.10.8 on Ubuntu 20.04

**To Reproduce**
Modify `dockerfiles/Dockerfile.cuda` to replace `Release` with `RelWithDebInfo`.  Build with 

```
docker build -t onnxruntime-cuda -f Dockerfile.cuda ..
```

**Expected behavior**
Build succeeds.

**Comment by spikecurtis** [comment]
Have been testing on `v1.8.2` tag.  Trying on `master` now

**Comment by spikecurtis** [comment]
FWIW, `master` is working fine, but for obvious reasons I don't want to be building on top of `master`.

**Comment by snnn** [comment]
When you run the docker build command, please redirect stdout and stderr to a file and search "error:". 
Like:
```
grep 'error:' build.log
```
Then send the output to us.

**Comment by spikecurtis** [comment]
I've resolved this problem.  When I checked out `v1.8.2`, I didn't update submodules.  I'll put together a docs PR to make this more clear.
