### ISSUE TITLE
error: option --use_dml not recognized

### ISSUE THREAD

**Issue by BenjaminWegener** [microsoft/onnxruntime#8980]
**Describe the bug**
build with --use_dml in windows fails with

Ran 1916 tests in 92.755s

OK (skipped=1168)
2021-09-07 17:57:20,747 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-07 17:57:20,747 build [WARNING] - onnxmltools and keras are not installed. The keras tests will be skipped.
2021-09-07 17:57:20,747 util.run [INFO] - Running subprocess in 'C:\Users\user\Documents\onnxruntime\\build\Windows\Release\Release'
  'C:\Python36\python.exe' 'C:\Users\user\Documents\onnxruntime\setup.py' bdist_wheel --use_dml
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --use_dml not recognized
Traceback (most recent call last):
  File "C:\Users\user\Documents\onnxruntime\\tools\ci_build\build.py", line 2317, in <module>
    sys.exit(main())
  File "C:\Users\user\Documents\onnxruntime\\tools\ci_build\build.py", line 2280, in main
    use_ninja=(args.cmake_generator == 'Ninja')
  File "C:\Users\user\Documents\onnxruntime\\tools\ci_build\build.py", line 1727, in build_python_wheel
    run_subprocess(args, cwd=cwd)
  File "C:\Users\user\Documents\onnxruntime\\tools\ci_build\build.py", line 621, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\user\Documents\onnxruntime\tools\python\util\run.py", line 45, in run
    env=env, shell=shell)
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'C:\\Users\\user\\Documents\\onnxruntime\\setup.py', 'bdist_wheel', '--use_dml']' returned non-zero exit status 1.

C:\Users\user\Documents\onnxruntime>

**System information**
windows 10 / AMD Vega 5 / python 3.6

**To Reproduce**
.\build.bat --cmake_generator "Visual Studio 16 2019" --config Release --build_wheel --use_dml --parallel

**Expected behavior**
building the wheel

**Comment by snnn** [comment]
Thank you for reporting this error. I created a PR. Would you please checkout the "snnn/dml" branch and try it? Please let me know if it works.

**Comment by BenjaminWegener** [comment]
Works fine, thank you.
