### ISSUE TITLE
Can't get the .whl file when using "--use_nnapi"

### ISSUE THREAD

**Issue by gdliang** [microsoft/onnxruntime#9012]
**Describe the bug**
Hi, when i build the onnxruntime with the nnapi on windows, i get the error below(the error is same on ubuntu18.04 ). The build command is:
build.bat --config RelWithDebInfo --use_nnapi --build_shared_lib --build_wheel --parallel --cmake_generator="Visual Studio 16 2019"

<font size=8>
2021-09-09 17:55:25,027 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-09 17:55:25,027 util.run [INFO] - Running subprocess in 'E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo'
  'C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\python.exe' onnxruntime_test_python.py
E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['NnapiExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
2021-09-09 17:55:25.5771305 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
...E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['NnapiExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
2021-09-09 17:55:25.6003125 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.6022786 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.6040731 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.6062028 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.6081452 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
..2021-09-09 17:55:25.6103158 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py:53: UserWarning: Specified provider 'InvalidProvider' is not in available provider names.Available providers: 'NnapiExecutionProvider, CPUExecutionProvider'
  warnings.warn("Specified provider '{}' is not in available provider names."
.2021-09-09 17:55:25.6132234 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6140532 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6168069 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
..2021-09-09 17:55:25.6195816 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
..2021-09-09 17:55:25.6220640 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6229748 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6250412 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6274878 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6299070 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.6326459 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6334821 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6357105 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.My EP provider created, with device id: 1, some_option: val
Create session with customize execution provider successfully!
.2021-09-09 17:55:25.6426097 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6446759 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6461709 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
..2021-09-09 17:55:25.6809167 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6818468 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6835836 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6844902 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_6956519901639360321_0 node. Name:'NnapiExecutionProvider_Nnapi_6956519901639360321_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6861311 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6870089 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_6956519901639360321_0 node. Name:'NnapiExecutionProvider_Nnapi_6956519901639360321_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6891570 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6902135 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_8055057627823776084_0 node. Name:'NnapiExecutionProvider_Nnapi_8055057627823776084_0_0' Status Message: Compute is not supported in this build.
E2021-09-09 17:55:25.6919719 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6929447 [E:onnxruntime:MultiThreadsTest:thread1, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
Exception in thread Thread-1:
Traceback (most recent call last):
2021-09-09 17:55:25.6932473 [E:onnxruntime:MultiThreadsTest:thread2, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
  File "C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\lib\threading.py", line 870, in run
    self.run()
  File "C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "onnxruntime_test_python.py", line 21, in run_model
    self._target(*self._args, **self._kwargs)
  File "onnxruntime_test_python.py", line 21, in run_model
    res = session_object.run([], {input_name: x}, run_options=run_options)
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    res = session_object.run([], {input_name: x}, run_options=run_options)
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.
.2021-09-09 17:55:25.6975206 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.6983986 [W:onnxruntime:Default, helper.cc:472 onnxruntime::nnapi::IsInputSupported] Dynamic shape is not supported for now, for input:X
.Skipping testRunModelWithCudaCopyStream when CUDA is not available
.2021-09-09 17:55:25.7008733 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.7030877 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.7054904 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
..2021-09-09 17:55:25.7079966 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.7099818 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.....2021-09-09 17:55:25.7138568 [I:onnxruntime:, inference_session.cc:304 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-09-09 17:55:25.7145972 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.7147294 [I:onnxruntime:, inference_session.cc:1242 onnxruntime::InferenceSession::Initialize] Initializing session.
2021-09-09 17:55:25.7148273 [I:onnxruntime:, inference_session.cc:1303 onnxruntime::InferenceSession::Initialize] This session will use the allocator registered with the environment.
2021-09-09 17:55:25.7150301 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-09-09 17:55:25.7157296 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-09-09 17:55:25.7161881 [I:onnxruntime:, session_state_utils.cc:140 onnxruntime::session_state_utils::SaveInitializedTensors] Saving initialized tensors.
2021-09-09 17:55:25.7163084 [I:onnxruntime:, session_state_utils.cc:266 onnxruntime::session_state_utils::SaveInitializedTensors] Done saving initialized tensors
2021-09-09 17:55:25.7164210 [I:onnxruntime:, inference_session.cc:1447 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
2021-09-09 17:55:25.7171105 [I:onnxruntime:, inference_session.cc:304 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2021-09-09 17:55:25.7176880 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
2021-09-09 17:55:25.7178160 [I:onnxruntime:, inference_session.cc:1242 onnxruntime::InferenceSession::Initialize] Initializing session.
2021-09-09 17:55:25.7180094 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-09-09 17:55:25.7182028 [I:onnxruntime:, reshape_fusion.cc:42 onnxruntime::ReshapeFusion::ApplyImpl] Total fused reshape node count: 0
2021-09-09 17:55:25.7186613 [I:onnxruntime:, session_state_utils.cc:140 onnxruntime::session_state_utils::SaveInitializedTensors] Saving initialized tensors.
2021-09-09 17:55:25.7187737 [I:onnxruntime:, session_state_utils.cc:266 onnxruntime::session_state_utils::SaveInitializedTensors] Done saving initialized tensors
2021-09-09 17:55:25.7188823 [I:onnxruntime:, inference_session.cc:1447 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
...2021-09-09 17:55:25.7337687 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.7361325 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.2021-09-09 17:55:25.7388353 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:661 onnxruntime::python::CreateExecutionProviderInstance] NNAPI execution provider can only be used to generate ORT format model in this build.
.
======================================================================
ERROR: testListAsInput (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 397, in testListAsInput
    res = sess.run([], {input_name: x.tolist()})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testOrtValue (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 857, in testOrtValue
    test_session_with_ortvalue_input(ortvalue1)
  File "onnxruntime_test_python.py", line 846, in test_session_with_ortvalue_input
    res = sess.run(["Y"], {"X": ortvalue})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testProfilerWithSessionOptions (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 595, in testProfilerWithSessionOptions
    sess.run([], {'X': x})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testRunModel (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 315, in testRunModel
    res = sess.run([output_name], {input_name: x})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_4698236792223093385_0 node. Name:'NnapiExecutionProvider_Nnapi_4698236792223093385_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testRunModel2 (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 347, in testRunModel2
    res = sess.run([output_name], {input_name: x})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_6956519901639360321_0 node. Name:'NnapiExecutionProvider_Nnapi_6956519901639360321_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testRunModel2Contiguous (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 362, in testRunModel2Contiguous
    res = sess.run([output_name], {input_name: x})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_6956519901639360321_0 node. Name:'NnapiExecutionProvider_Nnapi_6956519901639360321_0_0' Status Message: Compute is not supported in this build.

======================================================================
ERROR: testRunModelFromBytes (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 332, in testRunModelFromBytes
    res = sess.run([output_name], {input_name: x})
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi\onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running Nnapi_8055057627823776084_0 node. Name:'NnapiExecutionProvider_Nnapi_8055057627823776084_0_0' Status Message: Compute is not supported in this build.

----------------------------------------------------------------------
Ran 45 tests in 0.186s

FAILED (errors=7)
Traceback (most recent call last):
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\\tools\ci_build\build.py", line 2317, in <module>
    sys.exit(main())
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\\tools\ci_build\build.py", line 2241, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\\tools\ci_build\build.py", line 1572, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnxruntime_test_python.py'], cwd=cwd, dll_path=dll_path)
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\\tools\ci_build\build.py", line 621, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "E:\3_DL\ONNX\onnxruntime20210909\onnxruntime\tools\python\util\run.py", line 42, in run
    completed_process = subprocess.run(
  File "C:\Users\guodaoliang\Anaconda3\envs\pytorch170cuda110\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\guodaoliang\\Anaconda3\\envs\\pytorch170cuda110\\python.exe', 'onnxruntime_test_python.py']' returned non-zero exit status 1.
</font>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:1.8.1
- Python version:3.8
- Visual Studio version (if applicable):VS2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by gwang-msft** [comment]
The ONNX Runtime with NNAPI targeting Windows is for model conversion (.onnx -> .ort) only, it is normal some python tests  fail since those tests are trying to run inference with NNAPI EP, which is only supported on Android.

The actual conversion will work without issue, please try to build with `--skip_tests` parameter.

**Comment by gdliang** [comment]
> The ONNX Runtime with NNAPI targeting Windows is for model conversion (.onnx -> .ort) only, it is normal some python tests fail since those tests are trying to run inference with NNAPI EP, which is only supported on Android.
> 
> The actual conversion will work without issue, please try to build with `--skip_tests` parameter.

Thanks, i get the .whl file succefully by adding the `--skip_tests` .
