### ISSUE TITLE
returned non-zero exit status 1. when add option --build_wheel

### ISSUE THREAD

**Issue by roachsinai** [microsoft/onnxruntime#9097]
**Describe the bug**

I'm using command

`build.bat --config Release --cmake_generator "Visual Studio 16 2019" --use_openvino CPU_FP32 --build_shared_lib build_wheel --parallel --skip_tests`

to build OpenVINO-EP, but get `returned non-zero exit status 1`

```
(vino) D:\Libs\onnxruntime>build.bat --config Release --cmake_generator "Visual Studio 16 2019" --use_openvino CPU_FP32 --build_shared_lib build_wheel --parallel --skip_tests
...
...
...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241
,5): error MSB8066: “D:\Libs\onnxruntime\build\Windows\Release\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-mkd
ir.rule;D:\Libs\onnxruntime\build\Windows\Release\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-download.rule;D:
\Libs\onnxruntime\build\Windows\Release\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-update.rule;D:\Libs\onnxru
ntime\build\Windows\Release\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-patch.rule;D:\Libs\onnxruntime\build\W
indows\Release\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-configure.rule;D:\Libs\onnxruntime\build\Windows\Re
lease\CMakeFiles\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-build.rule;D:\Libs\onnxruntime\build\Windows\Release\CMakeFi
les\3fcfebd1187710a7ae153a8ebbd4e27b\pybind11-install.rule;D:\Libs\onnxruntime\build\Windows\Release\CMakeFiles\2301071
d6346c438b3d4bb0ec0080ca8\pybind11-complete.rule;D:\Libs\onnxruntime\build\Windows\Release\CMakeFiles\7e2daa9808df88121
60f990a58b4834e\pybind11.rule”的自定义生成已退出，代码为 1。 [D:\Libs\onnxruntime\build\Windows\Release\pybind11.vcxproj]
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  old.cc
cl : command line warning D9025: overriding '/external:W3' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\external\onnx\onnx.vcxproj]
  defs.cc
  onnx.vcxproj -> D:\Libs\onnxruntime\build\Windows\Release\external\onnx\Release\onnx.lib
  Building Custom Rule D:/Libs/onnxruntime/cmake/CMakeLists.txt
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
  provider_bridge_provider.cc
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
  my_allocator.cc
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
  my_ep_data_transfer.cc
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
  my_ep_factory.cc
cl : command line warning D9025: overriding '/external:W4' with '/external:W0' [D:\Libs\onnxruntime\build\Windows\Relea
se\test_execution_provider.vcxproj]
  my_execution_provider.cc
     Creating library D:/Libs/onnxruntime/build/Windows/Release/Release/test_execution_provider.lib and object D:/Libs/
  onnxruntime/build/Windows/Release/Release/test_execution_provider.exp
  test_execution_provider.vcxproj -> D:\Libs\onnxruntime\build\Windows\Release\Release\test_execution_provider.dll
Traceback (most recent call last):
  File "D:\Libs\onnxruntime\\tools\ci_build\build.py", line 2324, in <module>
    sys.exit(main())
  File "D:\Libs\onnxruntime\\tools\ci_build\build.py", line 2245, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\Libs\onnxruntime\\tools\ci_build\build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\Libs\onnxruntime\\tools\ci_build\build.py", line 625, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\Libs\onnxruntime\tools\python\util\run.py", line 45, in run
    env=env, shell=shell)
  File "C:\Users\benbenbj\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'D:\\Libs\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:16', '/nodeReuse:False']' returned non-zero exit status 1.
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Window 10
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version: 438175cb34d91ecc2f4d65c7c3092c3d734ecbd8
- Python version:3.7
- Visual Studio version (if applicable):2019 community lastest
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1
- GPU model and memory:

**To Reproduce**
- "C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat" to set openvino env variable
- cd onnxruntime source code directory
- build.bat --config Release --cmake_generator "Visual Studio 16 2019" --use_openvino CPU_FP32 --build_shared_lib --build_wheel --parallel --skip_tests

**Expected behavior**
Expect the build process success

**Screenshots**

![image](https://user-images.githubusercontent.com/9500049/133745058-53f7dcd9-917a-4c0e-9451-08b76f06a025.png)

![image](https://user-images.githubusercontent.com/9500049/133745110-96c4d642-1eea-433f-856a-a55efe25daa4.png)

**Additional context**

If remove option `--build_option`no errors.

**Comment by roachsinai** [comment]
closed as maybe should use inter fork version.
