### ISSUE TITLE
CMake error: could not find git for clone of pybind11

### ISSUE THREAD

**Issue by Prudvi-RapidQuest** [microsoft/onnxruntime#9124]
**Describe the bug**
Unable to build onnxruntime due to this error. It says could not find git for clone of pybind11. I looked at the call stack provided 
```
CMake Error at C:/Program Files/CMake/cmake-3.21.2-windows-x86_64/share/cmake-3.21/Modules/ExternalProject.cmake:2650 (message):
  error: could not find git for clone of pybind11
Call Stack (most recent call first):
  C:/Program Files/CMake/cmake-3.21.2-windows-x86_64/share/cmake-3.21/Modules/ExternalProject.cmake:3700 (_ep_add_download_command)
  external/pybind11.cmake:15 (ExternalProject_Add)
  onnxruntime_python.cmake:4 (include)
  CMakeLists.txt:1683 (include)
```
was able to traced the issue to the external/pybind11.cmake:15 (ExternalProject_Add) code 
```
if(NOT TARGET pybind11::module)
  include(ExternalProject)
  set(pybind11_INCLUDE_DIRS ${CMAKE_CURRENT_BINARY_DIR}/pybind11/src/pybind11/include)
  set(pybind11_URL https://github.com/pybind/pybind11.git)
  set(pybind11_TAG v2.7.1)
```
I found out that the pybind11 folder was empty so I cloned the pybind11 repository in this place and ran the command again but faced the same issue

**Urgency**
Very urgent, have to get ort model to run with NNAPI on Android by the end of the week.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): not installed/built yet
- ONNX Runtime version: not installed but cloned master branch 
- Python version: 3.9.7
- Visual Studio version (if applicable): VSCode 1.60.1
- GCC/Compiler version (if compiling from source): 11.2.0  
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
ran this build command
```
.\onnxruntime\build.bat --config MinSizeRel --android --android_sdk_path C:\Android\Sdk --android_ndk_path  C:\Android\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 29 --cmake_generator Ninja --minimal_build extended --use_nnapi --include_ops_by_config models\mpii\onnx\HRNET_noco_nobn.redesigned.basic.optimized.extended.required_operators.config  --build_wheel  --cmake_path "C:\Program Files\CMake\cmake-3.21.2-windows-x86_64\bin\cmake.exe" --ctest_path "C:\Program Files\CMake\cmake-3.21.2-windows-x86_64\bin\ctest.exe"
```

**Expected behavior**
the built.bat script must produce a .whl file with NNAPI support which can be installed as a python package

**Screenshots**

**Additional context**
This is the entire output
```
2021-09-20 17:21:04,547 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2021-09-20 17:21:04,557 reduce_op_kernels [INFO] - Processing C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxrunution_provider.cc
2021-09-20 17:21:04,567 reduce_op_kernels [INFO] - Processing C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxrun_kernels.cc
2021-09-20 17:21:04,576 reduce_op_kernels [INFO] - Processing C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxrunu\cpu_training_kernels.cc
2021-09-20 17:21:04,584 build [INFO] - Build started
2021-09-20 17:21:04,584 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['git', 'submodule', 'sync', '--recursive']
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary'
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary/src/3rdParty/eigen'
Synchronizing submodule url for 'cmake/external/FeaturizersLibrary/src/3rdParty/re2'
Synchronizing submodule url for 'cmake/external/SafeInt/safeint'
Synchronizing submodule url for 'cmake/external/coremltools'
Synchronizing submodule url for 'cmake/external/cub'
Synchronizing submodule url for 'cmake/external/cxxopts'
Synchronizing submodule url for 'cmake/external/date'
Synchronizing submodule url for 'cmake/external/dlpack'
Synchronizing submodule url for 'cmake/external/eigen'
Synchronizing submodule url for 'cmake/external/emsdk'
Synchronizing submodule url for 'cmake/external/flatbuffers'
Synchronizing submodule url for 'cmake/external/googlebenchmark'
Synchronizing submodule url for 'cmake/external/googletest'
Synchronizing submodule url for 'cmake/external/json'
Synchronizing submodule url for 'cmake/external/libprotobuf-mutator'
Synchronizing submodule url for 'cmake/external/mimalloc'
Synchronizing submodule url for 'cmake/external/mp11'
Synchronizing submodule url for 'cmake/external/nsync'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/optional-lite'
Synchronizing submodule url for 'cmake/external/protobuf'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/re2'
Synchronizing submodule url for 'cmake/external/tensorboard'
Synchronizing submodule url for 'cmake/external/tvm'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/HalideIR'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dlpack'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dmlc-core'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/wil'
Synchronizing submodule url for 'server/external/spdlog'
2021-09-20 17:21:06,562 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-20 17:21:06,562 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['git', 'submodule', 'update', '--init', '--recursive']
2021-09-20 17:21:22,823 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-20 17:21:22,823 build [INFO] - Building protoc for host to be used in cross-compiled build process
2021-09-20 17:21:22,823 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['C:\\Program Files\\CMake\\cmake-3.21.2-windows-x86_64\\bin\\cmake.exe', 'C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorchotobuf\\cmake', '-Dprotobuf_BUILD_TESTS=OFF', '-Dprotobuf_WITH_ZLIB_DEFAULT=OFF', '-Dprotobuf_BUILD_SHARED_LIBS=OFF', '-G', 'Ninja']
-- 
-- 3.16.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/onnxruntime/build/Windows/host_p
2021-09-20 17:21:23,604 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-20 17:21:23,604 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['C:\\Program Files\\CMake\\cmake-3.21.2-windows-x86_64\\bin\\cmake.exe', '--build', 'C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HR\Windows\\host_protoc', '--config', 'Release', '--target', 'protoc']
ninja: no work to do.
2021-09-20 17:21:23,852 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-20 17:21:23,853 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorch-to-TFLite\\env\\Scripts\\python.exe', '-m', 'pip', 'install', 'setuptoolpy>=1.1', 'packaging', 'cerberus']
Requirement already satisfied: setuptools in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (5
Requirement already satisfied: wheel in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (0.37.0
Requirement already satisfied: pytest in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (6.2.5
Requirement already satisfied: numpy>=1.16.6 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages
Requirement already satisfied: sympy>=1.1 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (1
Requirement already satisfied: packaging in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (21
Requirement already satisfied: cerberus in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (1.3
Requirement already satisfied: py>=1.8.2 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (fr
Requirement already satisfied: atomicwrites>=1.0 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-pack
Requirement already satisfied: attrs>=19.2.0 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-pack
Requirement already satisfied: colorama in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (fro
Requirement already satisfied: toml in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (from py
Requirement already satisfied: iniconfig in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages (fr
Requirement already satisfied: mpmath>=0.19 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packages 
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\prudvikamtam\touchcoreonedrive\work\hrnet-pytorch-to-tflite\env\lib\site-packa
2021-09-20 17:21:24,409 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-20 17:21:24,424 build [INFO] - Generating CMake build tree
2021-09-20 17:21:24,424 util.run [INFO] - Running subprocess in 'C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnx
['C:\\Program Files\\CMake\\cmake-3.21.2-windows-x86_64\\bin\\cmake.exe', 'C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorchime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPuchCoreOneDrive\\Work\\HRNet-PyTorch-to-TFLite\\env\\Scripts\\python.exe', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDA_VERSION=', '-CUDA_HOME=', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-DonnxruSHARED_LIB=OFF', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_DNNL_GPU_RUNTIME=', '-DonnxruntimPI_BUILTIN=ON', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', ', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Do_MIGRAPHX_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-DonnISABLE_EXCEPTIONS=OFF', '-Donnxruntime_DISABLE_ORT_FORMAT_LOAD=OFF', '-Donnxruntime_MINIMAL_BUILD=ON', '-Donnxruntime_EXTENDED_MINIMAL_BUIOPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=ON', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxr1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN= '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE__FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=xruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-DonnxruUDE_DIR=$(python -c 'from distutils.sysconfig import get_python_inc; print(get_python_inc())')", "-DPYTHON_LIBRARY=$(python -c 'import disig.get_config_var('LIBDIR'))')", '-Dpybind11_DIR=C:\\Users\\prudvikamtam\\anaconda3\\Lib\\site-packages\\pybind11\\share\\cmake\\pybind11'3.0.7599858\x08uild\\cmake\x07ndroid.toolchain.cmake-DANDROID_PLATFORM=android-29', '-DANDROID_ABI=arm64-v8a', '-DANDROID_MIN_SDK=29', '-Ddvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorch-to-TFLite\\onnxruntime\\\\build\\Windows\\host_protoc\\protoc.exe', '-Donnxruntime_PYBINnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=MinSizeRel']
Use gtest from submodule
-- Found PythonInterp: C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/env/Scripts/python.exe (found version "3.9.7")
Doing crosscompiling
-- Found PythonInterp: C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/env/Scripts/python.exe (found suitable version
Use protobuf from submodule
--
-- 3.16.0.0
-- Using the single-header code from C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/onnxruntime/cmake/external/json/
NVCC_ERROR = 
NVCC_OUT = The system cannot find the file specified
CMake Error at C:/Program Files/CMake/cmake-3.21.2-windows-x86_64/share/cmake-3.21/Modules/ExternalProject.cmake:2650 (message):
  error: could not find git for clone of pybind11
Call Stack (most recent call first):
  C:/Program Files/CMake/cmake-3.21.2-windows-x86_64/share/cmake-3.21/Modules/ExternalProject.cmake:3700 (_ep_add_download_command)
  external/pybind11.cmake:12 (ExternalProject_Add)
  onnxruntime_python.cmake:4 (include)
  CMakeLists.txt:1683 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/onnxruntime/build/Windows/MinSizeRel/CMakeFiles/CMakeOutput
See also "C:/Users/prudvikamtam/TouchCoreOneDrive/Work/HRNet-PyTorch-to-TFLite/onnxruntime/build/Windows/MinSizeRel/CMakeFiles/CMakeError.
CMake Warning:
  Value of CMAKE_TOOLCHAIN_FILE contained a newline; truncating


Traceback (most recent call last):
  File "C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxruntime\tools\ci_build\build.py", line 2161, in <module>
    sys.exit(main())
  File "C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxruntime\tools\ci_build\build.py", line 2070, in main
    generate_build_tree(
  File "C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxruntime\tools\ci_build\build.py", line 1022, in generate_
    run_subprocess(
  File "C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxruntime\tools\ci_build\build.py", line 581, in run_subpro
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\Users\prudvikamtam\TouchCoreOneDrive\Work\HRNet-PyTorch-to-TFLite\onnxruntime\tools\python\util\run.py", line 41, in run
    completed_process = subprocess.run(
  File "C:\Users\prudvikamtam\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\cmake-3.21.2-windows-x86_64\\bin\\cmake.exe', 'C:\\Users\\prudvikamtamTFLite\\onnxruntime\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTN_EXECUTABLE=C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorch-to-TFLite\\env\\Scripts\\python.exe', '-Donnxruntime_USE_CUDAe_MINIMAL_BUILD=ON', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=ON', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=ON', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_EAGER_MODE=OFF', "-DPYTHON_INCLUDE_DIR=$(python -c 'from distutils.sysconfig import get_python_inc; print(get_python_inc())')", "-DPYTHON_LIBRARY=$(python -c 'import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))')", '-Dpybind11_DIR=C:\\Users\\prudvikamtam\\anaconda3\\Lib\\site-packages\\pybind11\\share\\cmake\\pybind11', '-DCMAKE_TOOLCHAIN_FILE=C:\\Android\ndk\x13.0.7599858\x08uild\\cmake\x07ndroid.toolchain.cmake-DANDROID_PLATFORM=android-29', '-DANDROID_ABI=arm64-v8a', '-DANDROID_MIN_SDK=29', '-DONNX_CUSTOM_PROTOC_EXECUTABLE=C:\\Users\\prudvikamtam\\TouchCoreOneDrive\\Work\\HRNet-PyTorch-to-TFLite\\onnxruntime\\\\build\\Windows\\host_protoc\\protoc.exe', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-G', 'Ninja', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=MinSizeRel']' returned 
non-zero exit status 1
```

**Comment by yufenglee** [comment]
@gwang-msft, is NNAPI supported in python package?

**Comment by gwang-msft** [comment]
NNAPI is supported in python package for conversion only (build for Windows/Mac/Linux and convert to onnx model to .ort format using python package), we do not support python binding for running on devices such as Android.

Since you have already converted the model using basic optimization, you do not need to build python binding for conversion with NNAPI consideration anymore.

**Comment by Prudvi-RapidQuest** [comment]
Thanks for replying! I did the basic optimization using the pip installed onnxruntime, but when I tried the '--use_nnapi' arg during conversion it says not included in the build and I have re-build it. 
Are you saying that if I pip install onnxruntime and also build it using nnapi? I'm sorry I'm a little confused here, been trying to convert an .onnx model to .ort with nnapi enabled for quite sometime now.

**Comment by gwang-msft** [comment]
If you want to run your model using NNAPI on Android, this can be done in two ways,

- Convert the model using basic optimization, build the ONNX Runtime binary for Android with NNAPI or use our[pre-built package](https://search.maven.org/artifact/com.microsoft.onnxruntime/onnxruntime-mobile) if you can, you don't need to convert using `--use_nnapi` option, and this is sufficient for most of the cases.

- If you want to run the model on both CPU and NNAPI (depends on the actual device), and use `extend` or `all` optimization with `--use_nnapi` option while converting the model, you will need to
  1. Build ONNX Runtime with python wheel for your host system, (e.g. Windows, Mac, Linux) with `--use_nnapi` option, you may need to use `--skip_tests` as well
  2. Install the python wheel built in step i (uninstall the existing ONNX Runtime pypi package)
  3. Convert the onnx model to .ort format using `--use_nnapi` option, also generate the `required_operators.config`
  4. Custom build you ONNX Runtime for Android using the `required_operators.config` generated in step iii

**Comment by Prudvi-RapidQuest** [comment]
I thought not using the '--skip_tests' was the issue but tried step 1 to build onnxruntime with this command
```bash
.\build.bat --config MinSizeRel --android --android_sdk_path C:\Android\Sdk --android_ndk_path  C:\Android\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 29 --cmake_generator Ninja --minimal_build extended --use_nnapi --build_wheel  --cmake_path "C:\Program Files\CMake\cmake-3.21.2-windows-x86_64\bin\cmake.exe" --ctest_path "C:\Program Files\CMake\cmake-3.21.2-windows-x86_64\bin\ctest.exe" --skip_tests
```
but ended up with the same output.

**Comment by gwang-msft** [comment]
The step one is to build the ONNX Runtime for your host system (in your case Windows) to generate a pypi package to be installed to convert onnx models to .ort format. Your building command is for build for Android (with `--android --android_sdk_path C:\Android\Sdk --android_ndk_path C:\Android\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 29`), there is no python API support for Android, so the build will fail.
