### ISSUE TITLE
[ONNXRuntimeError] Failed to createSession in Android.

### ISSUE THREAD

**Issue by solegend** [microsoft/onnxruntime#9195]
**Describe the bug**
   ONNXRuntime crashed when creating session.

> System.err: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: inference_session.cc:1217 AssignNodesToEpsFromHashesImpl Failed to find kernel def hash (2370253020407350728) in kernel registries for LinearClassifier(1) node with name 'LinearClassifier'.

**System information**
- Android R:
- Python 3.7:
- AndroidStudio 4.1.2:

**To Reproduce**
1.  Generate sklearn LogicRegression model as the below methold.
https://onnxruntime.ai/docs/get-started/with-python.html.
[iris_model.zip](https://github.com/microsoft/onnxruntime/files/7235945/iris_model.zip)

2.  load mode.ort file to Android project and  add onnxruntime dependency.

> implementation 'com.microsoft.onnxruntime:onnxruntime-mobile:1.9.0'
> OrtEnvironment env = OrtEnvironment.getEnvironment();
> InputStream is = getResources().openRawResource(R.raw.lr_iris);
> OrtSession session = env.createSession(toByteArray(is));

Thanks.

**Comment by edgchen1** [comment]
The LinearClassifier op is not enabled by default in the mobile package.
This file shows which ones are:
https://github.com/microsoft/onnxruntime/blob/4daa14bc74b5378d5fcb0d6de063a9fa8bd42eac/tools/ci_build/github/android/mobile_package.required_operators.config
You can do a custom build to get the ops you need.
https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/tutorials/mobile/custom-build.md
Sorry, the docs at onnxruntime.ai/docs seem to have some broken links at the moment.

**Comment by solegend** [comment]
I use the below command to convert onnx to ort model with python script, but the result is failure.
Need I rebuild and install onnxruntim package in python environment?
Thanks.

> python -m onnxruntime.tools.convert_onnx_models_to_ort --use_nnapi --enable_type_reduction lr_iris.onnx

> Traceback (most recent call last):                                                                                        File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main                                            "__main__", mod_spec)                                                                                                 File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code                                                       exec(code, run_globals)                                                                                               File "C:\ProgramData\Anaconda3\lib\site-packages\onnxruntime\tools\convert_onnx_models_to_ort.py", line 244, in <module>                                                                                                                          convert_onnx_models_to_ort()                                                                                          File "C:\ProgramData\Anaconda3\lib\site-packages\onnxruntime\tools\convert_onnx_models_to_ort.py", line 227, in convert_onnx_models_to_ort                                                                                                        raise ValueError('The NNAPI Execution Provider was not included in this build of ONNX Runtime.')                    ValueError: The NNAPI Execution Provider was not included in this build of ONNX Runtime.

**Comment by solegend** [comment]
Does onnxruntime support sklearn-baggingClassifier ?

**Comment by solegend** [comment]
Hi @edgchen1 ，
     ONNX Runtime Mobile Custom Build introduces how to create a custom 'minimal' build for Android.   It requires to add --include_ops_by_config to the build parameters, it will build a onnxruntim which only support my custom model.  If I have many models, how to do custom building? How to do full build for Android?
     Besides, does onnxruntime support sklearn-baggingClassifier ?
Thanks.

**Comment by edgchen1** [comment]
> Need I rebuild and install onnxruntim package in python environment?
Right. If you want to use the --use_nnapi conversion option, you can build onnxruntime with the NNAPI EP enabled (--use_nnapi build.py option). Use the build.py --build_wheel option to produce a Python wheel.

> If I have many models, how to do custom building?
The conversion script can actually support multiple models and generate the configuration including the ops needed by all of them. Just pass the directory that contains your models.

> How to do full build for Android?
If you do not want to have a reduced set of ops, just don't use the --include_ops_by_config build.py option and all of the ops will be included. If you want a build with full functionality (e.g. loading ONNX models) and the binary size that comes with it, don't use the --minimal_build build.py option.

**Comment by gwang-msft** [comment]
For reference, NNAPI is for DNN only, which will not support traditional ML ops, if you models use a lot of traditional ML ops, the model conversion using official ONNX Runtime pypi package is sufficient (without using `--use_nnapi` option)

**Comment by solegend** [comment]
Hi @edgchen1  & @gwang-msft  ,
      Thanks for your support.

     I tried to build full ML ops for Android, but it was failure.
     The log shows I need to configure C/C++ compiler, but I think the C/C++ compiler are contained in android NDK(android toolchain llvm), how to cofigure to use llvm toolchain?
     Thanks.
     
```
System information

Windows10
Onnxruntime 1.9.0

Trace :
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/wil'
Synchronizing submodule url for 'server/external/spdlog'
2021-09-29 11:10:05,257 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-29 11:10:05,258 util.run [INFO] - Running subprocess in 'F:\code\onnx\onnxruntime'
  git submodule update --init --recursive
2021-09-29 11:18:19,532 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-09-29 11:18:19,532 build [INFO] - Building protoc for host to be used in cross-compiled build process
2021-09-29 11:18:19,533 util.run [INFO] - Running subprocess in 'F:\code\onnx\onnxruntime\\build\Windows\host_protoc'
  'C:\Program Files\CMake\bin\cmake.exe' 'F:\code\onnx\onnxruntime\cmake\external\protobuf\cmake' -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_WITH_ZLIB_DEFAULT=OFF -Dprotobuf_BUILD_SHARED_LIBS=OFF -G Ninja
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

```

**Comment by gwang-msft** [comment]
The compile failed when trying to build the protobuf compiler (protoc) for your host system (Windows), it cannot use the NDK C/C++ compiler since that's for cross-build Android binaries. 
The simplest way to resolve this is to start the building process from a Visual Studio Developer Command Prompt, see https://docs.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2019

Or you can prebuild protoc from `cmake/external/protobuf` (you will need to sync the submodule first) and add `--path_to_protoc_exe=<path to your protoc>` to the build command.
