### ISSUE TITLE
ORT fails when there is a shape inference issue in if node

### ISSUE THREAD

**Issue by jiafatom** [microsoft/onnxruntime#9339]
**Describe the bug**
I have a ONNX model from https://github.com/pytorch/pytorch/issues/55144, `fp32_squeeze_repro.onnx`, and then this script fails:
```python
x = torch.rand(1, 10)
runtime = onnxruntime.InferenceSession('fp32_squeeze_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy())))
```
The traceback is:
```
Traceback (most recent call last):
  File "/home/david/dev/pytorch_rel/test/onnx/test_pytorch_common.py", line 88, in wrapper
    return func(self)
  File "/home/david/dev/pytorch_rel/test/onnx/test_pytorch_onnx_onnxruntime.py", line 8196, in test_export_param
    runtime = onnxruntime.InferenceSession('fp32_squeeze_repro.onnx')
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (If_20) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Node (Squeeze_21) Op (Squeeze) [ShapeInferenceError] Dimension of input 1 must be 1 instead of 12
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: 3.7

**To Reproduce**
- ONNX model Attached, please rename zip to onnx.
[fp32_squeeze_repro.zip](https://github.com/microsoft/onnxruntime/files/7333124/fp32_squeeze_repro.zip)

**Comment by hariharans29** [comment]
Closing this as the behavior is expected for the provided repro model.
