### ISSUE TITLE
Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' 

### ISSUE THREAD

**Issue by svmdev** [microsoft/onnxruntime#9438]
**Describe the bug**
System.EntryPointNotFoundException: Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in shared library 'onnxruntime'

**Urgency**
No hard deadlines

**System information**
- OS MS Windows 10 -> Docker container Linux mode ( Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Base image: nvidia/cuda:11.4.2-devel-ubuntu20.04
- dotnet: latest
- Project: ASP.NET 5: +nuget: Microsoft.ML.OnnxRuntime.Gpu

**To Reproduce**
On line:
var _inferenceSession = new InferenceSession(modelData,
SessionOptions.MakeSessionOptionWithCudaProvider(gpuDeviceId)
an exception is thrown

**Expected behavior**
Ok.

**Screenshots**

<img width="1214" alt="onnx_gpu_ex" src="https://user-images.githubusercontent.com/15991559/137890860-00e98b90-5770-415d-8848-b167c02392d1.png">

**Additional context**

For CPU:
var _inferenceSession = new InferenceSession(modelData)
works great.

**Comment by skottmckay** [comment]
What onnxruntime version are you using?

Can you also please double check that the project with the error is using the Microsoft.ML.OnnxRuntime.Gpu nuget package and not Microsoft.ML.OnnxRuntime?

**Comment by svmdev** [comment]
**May be related to this problem**

Console test (Windows 10) to create 'InferenceSession' only:
- Project Sdk="Microsoft.NET.Sdk", OutputType = Exe, TargetFramework=net5.0,
- PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.9.0"

<img width="884" alt="onnx1" src="https://user-images.githubusercontent.com/15991559/138014705-004a889d-dae9-4bd8-9c07-56d1929d8088.png">



<img width="1362" alt="onnx2" src="https://user-images.githubusercontent.com/15991559/138014750-01249ad9-a586-4311-a54b-5446f75d5de1.png">

, also resulted in an error:

>   HResult=0x80131500
  Message=[ErrorCode:RuntimeException] D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithCudaProvider(Int32 deviceId)
   at OnnxGpuTestConsole.Program.Main(String[] args) 
<img width="1464" alt="onnx3" src="https://user-images.githubusercontent.com/15991559/138014766-62116c71-af9d-403d-a103-fcd2da1c8083.png">

**Comment by skottmckay** [comment]
While your app is running in the debugger can you try running this tool to check where it's loading onnxruntime.dll from?

https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls

Provide the exe name as the argument.

**Comment by skottmckay** [comment]
In your most recent setup where the entry point is found, but you're running the code in an environment that does not have CUDA installed, I believe the issue is the environment (which creates the logger) is lazy initialized in InferenceSession but the error is triggered before that happens. If you add the following before creating the session options do you get an error about CUDA not being able to be loaded?
```csharp
var ortEnvInstance = OrtEnv.Instance();
var so = SessionOptions.MakeSessionOptionWithCudaProvider(0);
...
```

With the original issue, if it's unable to find the entry point in the shared library that would typically result from using the Microsoft.ML.OnnxRuntime package and calling OrtSessionOptionsAppendExecutionProvider_CUDA. However you stated you were using Microsoft.ML.OnnxRuntime.Gpu which should include the entry point. Did you check all the files in the nuget packages in this setup to validate it's the Microsoft.ML.OnnxRuntime.Gpu package or just in the setup on the machine without CUDA?
