### ISSUE TITLE
onnx inference with multiprocess

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#9625]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:1.6
- Python version:3.6
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2/8.0
- GPU model and memory:

when i execute the demo with onnx model that has serval models piplines,i try inference in multiprocess like this:

def Mulprocesstest(img_path, Jsonpath, numP=4):
    params = Loopparams(img_inputpath, LibJsonpath, numP)

    p_list = []
    for i, paramin in enumerate(params):
        p = Process(target=Looptest, args=(paramin,))
        p_list.append(p)
        p.start()

    for p in p_list:
        p.join()

when i set numP=2 and 1 it execute exactly,but when set >3,4,5...etc it raise errors s follows:
2021-10-30 15:52:10.654619372 [E:onnxruntime:, inference_session.cc:1268 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=siit-PC ; expr=cudnnCreate(&cudnn_handle_); 

2021-10-30 15:52:10.655134609 [E:onnxruntime:, inference_session.cc:1268 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=siit-PC ; expr=cudnnCreate(&cudnn_handle_); 

2021-10-30 15:52:10.657744214 [E:onnxruntime:, inference_session.cc:1268 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudnnStatus_t; bool THRW = true] CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=siit-PC ; expr=cudnnCreate(&cudnn_handle_); 

Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 225, in prepare
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 225, in prepare
    prepare(preparation_data)
    prepare(preparation_data)
    prepare(preparation_data)

**Comment by skottmckay** [comment]
Please provide full working code and preferably the model and input to reproduce.

**Comment by pranavsharma** [comment]
Have you looked at [this](https://github.com/microsoft/onnxruntime/issues/7846#issuecomment-850217402)?

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
