### ISSUE TITLE
build bug with cuda 10.2 and cudnn8.0

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#9631]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:master branch
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2/8.0
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

when execte ./build.sh --parallel --build_shared_lib --build_wheel --config=RelWithDebInfo --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/local/cuda --cuda_version=10.2  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52 --skip_tests

adding 'onnxruntime_gpu-1.10.0.data/purelib/onnxruntime/transformers/longformer/longformer_helper.py'
adding 'onnxruntime_gpu-1.10.0.dist-info/METADATA'
adding 'onnxruntime_gpu-1.10.0.dist-info/WHEEL'
adding 'onnxruntime_gpu-1.10.0.dist-info/entry_points.txt'
adding 'onnxruntime_gpu-1.10.0.dist-info/top_level.txt'
adding 'onnxruntime_gpu-1.10.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
2021-10-31 23:19:13,451 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-10-31 23:19:13,451 build [INFO] - Build complete

 
but when execute   ./build.sh --parallel --build_shared_lib --build_wheel --config=RelWithDebInfo --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/local/cuda --cuda_version=10.2  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52    with no --skip_tests flag

errors comes:

6/6 Test #6: onnxruntime_api_tests_without_env ......   Passed    0.02 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =  36.69 sec

The following tests FAILED:
	  1 - onnxruntime_test_all (Failed)
Errors while running CTest
Traceback (most recent call last):
  File "sensors/onnxruntime/tools/ci_build/build.py", line 2353, in <module>
    sys.exit(main())
  File "/sensors/onnxruntime/tools/ci_build/build.py", line 2277, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "sensors/onnxruntime/tools/ci_build/build.py", line 1592, in run_onnxruntime_tests
    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)
  File "sensors/onnxruntime/tools/ci_build/build.py", line 631, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)

**Comment by snnn** [comment]
What GPU hardware do you have?

**Comment by cqray1990** [comment]
@snnn cuda 10.2 /cudnn 8.0 2080ti driver 460
