### ISSUE TITLE
Optimization changes the graph so it cannot run on Cuda

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#9778]
**Describe the bug**
I have an ONNX that works fine on CPU, but in order to run it on GPU I have to disable the optimization with `ORT_DISABLE_ALL`.
Otherwise I get error about `LayerNormalization_token_12` which is not standard ONNX

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory:

**To Reproduce**
Load the model exported, and run on cuda

**Expected behavior**
If the EP is cuda optimization should not add a node that is not acceptable. 

**Additional context**

```log
2021-11-13 13:40:44 2021-11-13 13:40:43.730084854 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running LayerNormalization node. Name:'LayerNormalization_token_12' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
2021-11-13 13:40:44 Traceback (most recent call last):
2021-11-13 13:40:44   File "scripts/captioning/process_tsv.py", line 272, in <module>
2021-11-13 13:40:44     main()
2021-11-13 13:40:44   File "scripts/captioning/process_tsv.py", line 218, in main
2021-11-13 13:40:44     outputs = sess.run(cap_targets, hists)
2021-11-13 13:40:44   File "/tmp/site-packages/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
2021-11-13 13:40:44     return self._sess.run(output_names, input_feed, run_options)
2021-11-13 13:40:44 onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running LayerNormalization node. Name:'LayerNormalization_token_12' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
```

**Comment by hariharans29** [comment]
The complaint is not that `LayerNormalization_token_12` is not in the ONNX standard. The problem seems to be with the LayerNorm CUDA kernel implementation (`CUDA error cudaErrorInvalidConfiguration:invalid configuration argument`).

When you set optimization level to ORT_DISABLE_ALL, the LayerNorm fusion doesn't kick-in and it doesn't run the problematic CUDA kernel.

Can you provide a minimalistic model to repro ? @wangyems @tianleiwu : Can you please take a look at this potential issue with the LyaerNorm CUDA kernel when you get a chance ?

**Comment by dashesy** [comment]
Thanks. Yes that seems to be the issue. Will create a small model to show this issue.

**Comment by wschin** [comment]
This sounds strange. [LayerNormalization exists in ORT](https://github.com/microsoft/onnxruntime/blob/229c9a4e1c2508fcac0dbe38418db1c9e9012833/onnxruntime/contrib_ops/cuda/cuda_contrib_kernels.cc#L72) as an contributed operator, so it should be runnable. Could you please share how do you install onnxruntime?

**Comment by wangyems** [comment]
Found similar issue with an internal model. Will work on investigation.

**Comment by wangyems** [comment]
@dashesy Can you please try this branch https://github.com/microsoft/onnxruntime/tree/wangye/layernorm2 on your model?

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
