### ISSUE TITLE
Error message in ORT 1.9.0 is not as clear as previous ORT versions

### ISSUE THREAD

**Issue by yetingqiaqia** [microsoft/onnxruntime#9878]
**Describe the bug**

Hi ORT team, I feel the error msg in ORT 1.9.0 is not clear enough to help figure out the root cause. To resolve my issue, I actually had to downgrade to previous ORT1.8.1 to check the error msg.

See below for comparison:

Error msg in ORT 1.9.0:
```
Provider:  ['CPUExecutionProvider']
Provider options: {'CPUExecutionProvider': {}}
Traceback (most recent call last):
  File "resnet_torch_vs_onnx.py", line 151, in <module>
    onnx_evaluate()
  File "resnet_torch_vs_onnx.py", line 26, in onnx_evaluate
    cuda_options = options['CUDAExecutionProvider']
KeyError: 'CUDAExecutionProvider'
```

Error msg in ORT 1.8.1:
```
Traceback (most recent call last):
  File "resnet_torch_vs_onnx.py", line 151, in <module>
    onnx_evaluate()
  File "resnet_torch_vs_onnx.py", line 9, in onnx_evaluate
    import onnxruntime as ort
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/__init__.py", line 34, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/_pybind_state.py", line 11, in <module>
    from . import _ld_preload  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcudart = CDLL("libcudart.so.11.0", mode=RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

```

**Why I met this issue**
I am using a Linux machine which used to run ORT1.9.1+CUDA well. (I installed it in a Linux docker container 'A'). Then I tried to build, install and test ORT+TensorRT in a different Linux docker container 'B'. However, that build failed and impacted my existing ORT 1.9.1 package 'A'. 
However, the difficult thing is, ORT 1.9.1 only prints ```KeyError: 'CUDAExecutionProvider'``` which seems to be useless that I have no idea which part of CUDA is broken because of the build failure.
After struggling for a while, I found ORT 1.8.1 actually shows clear msg about what is missing. 

**To Reproduce**
You can use below code with any models in a non-CUDA environment (for example, a CPU machine).

- This is the model I am using: https://drive.google.com/file/d/1Z2lrFbQ61mqZOapz4GQUUINn4aFCgvRH/view?usp=sharing

```python
import onnxruntime as ort
sess_options = ort.SessionOptions()
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
sess_options.enable_mem_pattern=False
sess = ort.InferenceSession("graph_opset12_optimized_fp16_keep_io_True.onnx", sess_options, providers=["CPUExecutionProvider","CUDAExecutionProvider"])
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name

options = sess.get_provider_options()
print("Provider: ", sess.get_providers())
print("Provider options:", options)
cuda_options = options['CUDAExecutionProvider']

```

**Expected behavior**
I expect the error msg should be clear enough to tell the user what's wrong and how to fix. A simple ```KeyError: 'CUDAExecutionProvider'``` is not clear enough. 

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by askhade** [comment]
@yetingqiaqia : Don't you see error: 
[E:onnxruntime:Default, provider_bridge_ort.cc:940 onnxruntime::ProviderLibrary::Get] LoadLibrary failed with error 126 "The specified module could not be found." when trying to load "C:\Users\askhade\Documents\Python3.6\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll" ?

**Comment by yetingqiaqia** [comment]
@askhade , you already re-produced my Error msg of ORT 1.9.0, i.e., `KeyError: 'CUDAExecutionProvider'`
My point is, **the error msg in ORT1.9.0 is not clear. The error in ORT1.8.1 is much clearer than ORT1.9.0.** 
In ORT1.8.1, with error msg `OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory`, I am able to identify the root cause and set the environment variable for libcudart properly.

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
