### ISSUE TITLE
Yolov5 ORT train failed with onnxruntime backend

### ISSUE THREAD

**Issue by aseprohman** [microsoft/onnxruntime#9936]
```
/opt/conda/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_utils.py:162: UserWarning: User Module's attribute name _apply collides with ORTModule's attribute name. User Module's method may not be called upon invocation through ORTModule.
  warnings.warn(f"User Module's attribute name {attribute_name} collides with ORTModule's attribute name. "
Transferred 428/481 items from weights/yolov5m.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 79 weight, 82 weight (no decay), 82 bias
Traceback (most recent call last):
  File "train-ort.py", line 635, in <module>
    main(opt)
  File "train-ort.py", line 532, in main
    train(opt.hyp, opt, device, callbacks)
  File "train-ort.py", line 185, in train
    ema = ModelEMA(model) if RANK in [-1, 0] else None
  File "/workspace/Trainer/yolov5/utils/torch_utils.py", line 296, in __init__
    self.ema = deepcopy(model.module if is_parallel(model) else model).eval()  # FP32 EMA
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/conda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'odict_values' object
```

Hello all, 
I see error when run onnxruntime-training with yolov5 in python. can anyone suggest me how to fixed this issue ?
thanks

**Comment by ytaous** [comment]
Hi, can u pls provide more details on the env settings/package versions, etc.?

@baijumeswani

**Comment by ytaous** [comment]
Hi, got back from dev for possible fix - https://github.com/microsoft/onnxruntime/pull/9634
please try our onnxruntime nightly and see if it works for you (dated passed the date of the PR)

https://download.onnxruntime.ai/onnxruntime_nightly_cu111.html
