### ISSUE TITLE
pip3 onnx==1.8.0 is not working on Jetson Xavier

### ISSUE THREAD

**Issue by dsnsabari** [microsoft/onnxruntime#9984]
I am getting the "**Error:No matching distribution found for onnx=1.8.0**" error , while installing the onnx 1.8.0. Please help me on installation.

**Comment by jcwchen** [comment]
Hi @dsnsabari,
This should be a question for ONNX library. Are you using an ARM machine? There is no pre-build ARM distribution for ONNX 1.8.0. Still, you should be able to build it from source. Do you encounter any error while installing ONNX 1.8.0 from source distribution?

**Comment by dsnsabari** [comment]
@jcwchen  , I haven't tried to install it from the source. Let me try it. could you share the steps from installing from source?

**Comment by jcwchen** [comment]
Please follow the steps here: https://github.com/onnx/onnx#build-onnx-from-source Thanks!

**Comment by dsnsabari** [comment]
@jcwchen thank you so much

**Comment by jcwchen** [comment]
> @jcwchen I tried the build the ONNX from source. It was not working. I am getting the below error.
> 
> ```
> ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf
>        cwd: None
>   Complete output (31 lines):
>   Traceback (most recent call last):
>     File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>       "__main__", mod_spec)
>     File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>       exec(code, run_globals)
>     File "/usr/local/lib/python3.6/dist-packages/pip/__main__.py", line 29, in <module>
>       from pip._internal.cli.main import main as _main
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
>       from pip._internal.cli.autocompletion import autocomplete
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
>       from pip._internal.cli.main_parser import create_main_parser
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
>       from pip._internal.cli import cmdoptions
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
>       from pip._internal.cli.parser import ConfigOptionParser
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
>       from pip._internal.configuration import Configuration, ConfigurationError
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/configuration.py", line 26, in <module>
>       from pip._internal.utils.logging import getLogger
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/logging.py", line 13, in <module>
>       from pip._internal.utils.misc import ensure_dir
>     File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 36, in <module>
>       from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
>     File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/tenacity/__init__.py", line 26, in <module>
>       from concurrent import futures
>     File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
>       from concurrent.futures._base import (FIRST_COMPLETED,
>     File "/usr/local/lib/python3.6/dist-packages/concurrent/futures/_base.py", line 357
>       raise type(self._exception), self._exception, self._traceback
>                                  ^
>   SyntaxError: invalid syntax
>   ----------------------------------------
> WARNING: Discarding file:///home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0. Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf Check the logs for full command output.
> ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-exue87ie/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com -- setuptools wheel protobuf Check the logs for full command output.
> ```

(Move this comment from here: https://github.com/onnx/onnx/issues/3886#issuecomment-990531230)
Did you bump into this error while installing protobuf? Which command did you bump into this error?

Regarding to the error itself, relates issue is [here](https://github.com/agronholm/pythonfutures/issues/41). It seems certain library does not use futures library properly.

**Comment by dsnsabari** [comment]
@jcwchen  , I followed the below steps for installing the ONNX 1.8.0 from the source. 

I used the source file from the below link. 
https://github.com/onnx/onnx/releases


```
export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
git clone --recursive https://github.com/onnx/onnx.git
cd onnx
# prefer lite proto
set CMAKE_ARGS=-DONNX_USE_LITE_PROTO=ON
pip install -e 
```

**Comment by dsnsabari** [comment]
@jcwchen , I have fixed the future python file issue.  Now i am getting new issue. 

```
<pre>sudo pip3 install -e .
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions&gt;=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx==1.8.0) (3.10.0.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.8.0) (1.11.0)
Requirement already satisfied: numpy in /home/rachel/.local/lib/python3.6/site-packages (from onnx==1.8.0) (1.19.5)
Requirement already satisfied: protobuf in /home/rachel/.local/lib/python3.6/site-packages (from onnx==1.8.0) (3.16.0)
Installing collected packages: onnx
  Running setup.py develop for onnx
<font color="#CC0000">    ERROR: Command errored out with exit status 1:</font>
<font color="#CC0000">     command: /usr/bin/python3 -c &apos;import io, os, sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&apos;&quot;&apos;&quot;&apos;;f = getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__) if os.path.exists(__file__) else io.StringIO(&apos;&quot;&apos;&quot;&apos;from setuptools import setup; setup()&apos;&quot;&apos;&quot;&apos;);code = f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; develop --no-deps</font>
<font color="#CC0000">         cwd: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/</font>
<font color="#CC0000">    Complete output (61 lines):</font>
<font color="#CC0000">    fatal: not a git repository (or any of the parent directories): .git</font>
<font color="#CC0000">    running develop</font>
<font color="#CC0000">    running build_py</font>
<font color="#CC0000">    running create_version</font>
<font color="#CC0000">    running cmake_build</font>
<font color="#CC0000">    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-ml.proto</font>
<font color="#CC0000">    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-operators-ml.proto</font>
<font color="#CC0000">    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-data.proto</font>
<font color="#CC0000">    CMake Warning at CMakeLists.txt:412 (find_package):</font>
<font color="#CC0000">      By not providing &quot;Findpybind11.cmake&quot; in CMAKE_MODULE_PATH this project has</font>
<font color="#CC0000">      asked CMake to find a package configuration file provided by &quot;pybind11&quot;,</font>
<font color="#CC0000">      but CMake did not find one.</font>
<font color="#CC0000">    </font>
<font color="#CC0000">      Could not find a package configuration file provided by &quot;pybind11&quot;</font>
<font color="#CC0000">      (requested version 2.2) with any of the following names:</font>
<font color="#CC0000">    </font>
<font color="#CC0000">        pybind11Config.cmake</font>
<font color="#CC0000">        pybind11-config.cmake</font>
<font color="#CC0000">    </font>
<font color="#CC0000">      Add the installation prefix of &quot;pybind11&quot; to CMAKE_PREFIX_PATH or set</font>
<font color="#CC0000">      &quot;pybind11_DIR&quot; to a directory containing one of the above files.  If</font>
<font color="#CC0000">      &quot;pybind11&quot; provides a separate development package or SDK, be sure it has</font>
<font color="#CC0000">      been installed.</font>
<font color="#CC0000">    </font>
<font color="#CC0000">    </font>
<font color="#CC0000">    CMake Error at CMakeLists.txt:421 (message):</font>
<font color="#CC0000">      cannot find pybind</font>
<font color="#CC0000">    </font>
<font color="#CC0000">    </font>
<font color="#CC0000">    -- Configuring incomplete, errors occurred!</font>
<font color="#CC0000">    See also &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log&quot;.</font>
<font color="#CC0000">    See also &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/CMakeFiles/CMakeError.log&quot;.</font>
<font color="#CC0000">    Traceback (most recent call last):</font>
<font color="#CC0000">      File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;</font>
<font color="#CC0000">      File &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&quot;, line 341, in &lt;module&gt;</font>
<font color="#CC0000">        &apos;backend-test-tools = onnx.backend.test.cmd_tools:main&apos;,</font>
<font color="#CC0000">      File &quot;/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py&quot;, line 163, in setup</font>
<font color="#CC0000">        return distutils.core.setup(**attrs)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/core.py&quot;, line 148, in setup</font>
<font color="#CC0000">        dist.run_commands()</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/dist.py&quot;, line 955, in run_commands</font>
<font color="#CC0000">        self.run_command(cmd)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/dist.py&quot;, line 974, in run_command</font>
<font color="#CC0000">        cmd_obj.run()</font>
<font color="#CC0000">      File &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&quot;, line 233, in run</font>
<font color="#CC0000">        self.run_command(&apos;build_py&apos;)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/cmd.py&quot;, line 313, in run_command</font>
<font color="#CC0000">        self.distribution.run_command(command)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/dist.py&quot;, line 974, in run_command</font>
<font color="#CC0000">        cmd_obj.run()</font>
<font color="#CC0000">      File &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&quot;, line 217, in run</font>
<font color="#CC0000">        self.run_command(&apos;cmake_build&apos;)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/cmd.py&quot;, line 313, in run_command</font>
<font color="#CC0000">        self.distribution.run_command(command)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/distutils/dist.py&quot;, line 974, in run_command</font>
<font color="#CC0000">        cmd_obj.run()</font>
<font color="#CC0000">      File &quot;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&quot;, line 203, in run</font>
<font color="#CC0000">        subprocess.check_call(cmake_args)</font>
<font color="#CC0000">      File &quot;/usr/lib/python3.6/subprocess.py&quot;, line 311, in check_call</font>
<font color="#CC0000">        raise CalledProcessError(retcode, cmd)</font>
<font color="#CC0000">    subprocess.CalledProcessError: Command &apos;[&apos;/usr/bin/cmake&apos;, &apos;-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m&apos;, &apos;-DPYTHON_EXECUTABLE=/usr/bin/python3&apos;, &apos;-DBUILD_ONNX_PYTHON=ON&apos;, &apos;-DCMAKE_EXPORT_COMPILE_COMMANDS=ON&apos;, &apos;-DONNX_NAMESPACE=onnx&apos;, &apos;-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so&apos;, &apos;-DCMAKE_BUILD_TYPE=Release&apos;, &apos;-DONNX_ML=1&apos;, &apos;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0&apos;]&apos; returned non-zero exit status 1.</font>
<font color="#CC0000">    ----------------------------------------</font>
<font color="#CC0000">ERROR: Command errored out with exit status 1: /usr/bin/python3 -c &apos;import io, os, sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py&apos;&quot;&apos;&quot;&apos;;f = getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__) if os.path.exists(__file__) else io.StringIO(&apos;&quot;&apos;&quot;&apos;from setuptools import setup; setup()&apos;&quot;&apos;&quot;&apos;);code = f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; develop --no-deps Check the logs for full command output.</font>
</pre>
```

**Comment by jcwchen** [comment]
Thanks for providing the error log. On arm machine, you might need to build pybind11 from source as well.. Could you please try to build pybind11 from source before building ONNX? You can follow the steps [here](https://github.com/onnx/onnx/issues/1624#issuecomment-799314072).

**Comment by dsnsabari** [comment]
okay. I will try it.

**Comment by dsnsabari** [comment]
@jcwchen , I installed the pybind11 from source. But still i am getting the same error. 

 ```
sudo pip3 install -e .
[sudo] password for rachel: 
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: protobuf in /home/rachel/.local/lib/python3.6/site-packages (from onnx==1.8.0) (3.16.0)
Requirement already satisfied: numpy in /home/rachel/.local/lib/python3.6/site-packages (from onnx==1.8.0) (1.19.5)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.8.0) (1.11.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx==1.8.0) (3.10.0.2)
Installing collected packages: onnx
  Running setup.py develop for onnx
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py'"'"'; __file__='"'"'/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/
    Complete output (117 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running develop
    running build_py
    running create_version
    running cmake_build
    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-data.proto
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Found pybind11: /usr/local/include (found version "2.9.0dev1")
    --
    -- ******** Summary ********
    --   CMake version         : 3.10.2
    --   CMake command         : /usr/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 7.5.0
    --   CXX flags             :  -Wnon-virtual-dtor
    --   Build type            : Release
    --   Compile definitions   :
    --   CMAKE_PREFIX_PATH     :
    --   CMAKE_INSTALL_PREFIX  : /usr/local
    --   CMAKE_MODULE_PATH     :
    --
    --   ONNX version          : 1.8.0
    --   ONNX NAMESPACE        : onnx
    --   ONNX_BUILD_TESTS      : OFF
    --   ONNX_BUILD_BENCHMARKS : OFF
    --   ONNX_USE_LITE_PROTO   : OFF
    --   ONNXIFI_DUMMY_BACKEND : OFF
    --   ONNXIFI_ENABLE_EXT    : OFF
    --
    --   Protobuf compiler     : /usr/bin/protoc
    --   Protobuf includes     : /usr/include
    --   Protobuf libraries    : /usr/lib/aarch64-linux-gnu/libprotobuf.so;-lpthread
    --   BUILD_ONNX_PYTHON     : ON
    --     Python version      :
    --     Python executable   : /usr/bin/python3
    --     Python includes     : /usr/include/python3.6m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build
    Scanning dependencies of target gen_onnx_proto
    Scanning dependencies of target onnxifi_loader
    Scanning dependencies of target onnxifi_dummy
    [  1%] Running gen_proto.py on onnx/onnx.in.proto
    [  3%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
    [  4%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
    /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
    /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/onnx/onnxifi_dummy.c:173:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
               *function = &onnxGetExtensionFunctionAddress;
                         ^
    /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/onnx/onnxifi_dummy.c:176:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
               *function = &onnxSetIOAndRunGraph;
                         ^
    [  6%] Linking C static library libonnxifi_loader.a
    Processing /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/onnx/onnx.in.proto
    Writing /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-ml.proto
    Writing /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-ml.proto3
    generating /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx_pb.py
    [  7%] Running C++ protocol buffer compiler on /home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/.setuptools-cmake-build/onnx/onnx-ml.proto
    [  9%] Linking C shared library libonnxifi_dummy.so
    [  9%] Built target onnxifi_loader
    Scanning dependencies of target onnxifi_wrapper
    [ 10%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
    [ 10%] Built target onnxifi_dummy
    Traceback (most recent call last):
      File "/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/tools/protoc-gen-mypy.py", line 26, in <module>
        import google.protobuf.descriptor_pb2 as d_typed
      File "/tmp/pip-build-env-az4k1bg8/overlay/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 5, in <module>
        from google.protobuf import descriptor as _descriptor
      File "/tmp/pip-build-env-az4k1bg8/overlay/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 113
        class DescriptorBase(metaclass=DescriptorMetaclass):
                                      ^
    SyntaxError: invalid syntax
    --mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
    CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx-ml.pb.cc' failed
    make[2]: *** [onnx/onnx-ml.pb.cc] Error 1
    CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
    make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 12%] Linking C shared module libonnxifi.so
    [ 12%] Built target onnxifi_wrapper
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py", line 341, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py", line 233, in run
        self.run_command('build_py')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py", line 217, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py", line 211, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py'"'"'; __file__='"'"'/home/rachel/Desktop/TRT-SSD-MobileNetV2-master/onnx-1.8.0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

**Comment by jcwchen** [comment]
Now it seems like a Protobuf version issue. May I know what your Protobuf version is? IIRC, for ONNX 1.8.0, it's better to use Protobuf >= 3.11.

**Comment by dsnsabari** [comment]
@jcwchen  I checked the Protobuf version in my device. It has the protobuf 3.16.0.

```
pip3 install protobuf==3.16.0
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: protobuf==3.16.0 in ./.local/lib/python3.6/site-packages (3.16.0)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf==3.16.0) (1.11.0)

```

**Comment by jywu-msft** [comment]
what is the protobuf version associated with the protobuf detected by cmake in these locations
`   --   Protobuf compiler     : /usr/bin/protoc
   --   Protobuf includes     : /usr/include
   --   Protobuf libraries    : /usr/lib/aarch64-linux-gnu/libprotobuf.so;-lpthread
`

**Comment by snnn** [comment]
This issue has been automatically closed as 'not planned' because it has been marked as 'stale' for more than 30 days without activity. If you believe this is still an issue, please feel free to reopen it.
